// SPDX-FileCopyrightText: 2013-2022 Paul Colby <git@colby.id.au>
// SPDX-License-Identifier: LGPL-3.0-or-later

#ifndef QTAWSAPIGATEWAYMANAGEMENTGLOBAL_H
#define QTAWSAPIGATEWAYMANAGEMENTGLOBAL_H

// Export declaration macros.
#if defined(QTAWS_SHARED) || !defined(QTAWS_STATIC)
#  ifdef QTAWS_STATIC
#    error "Both QTAWS_SHARED and QTAWS_STATIC defined."
#  endif
#  if defined QTAWSAPIGATEWAYMANAGEMENT_LIBRARY
#    define QTAWSAPIGATEWAYMANAGEMENT_EXPORT Q_DECL_EXPORT
#  else
#    define QTAWSAPIGATEWAYMANAGEMENT_EXPORT Q_DECL_IMPORT
#  endif
#else
#    define QTAWSAPIGATEWAYMANAGEMENT_EXPORT
#endif


#endif // QTAWSAPIGATEWAYMANAGEMENTGLOBAL_H
