var searchData=
[
  ['kinesisanalyticsclient',['KinesisAnalyticsClient',['../classKinesisAnalyticsClient.html',1,'KinesisAnalyticsClient'],['../classKinesisAnalyticsClient.html#a2675a8fd0c9ee84deab38bcfd753151c',1,'KinesisAnalyticsClient::KinesisAnalyticsClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classKinesisAnalyticsClient.html#a26a0e5d3081810ab7c0da49928104916',1,'KinesisAnalyticsClient::KinesisAnalyticsClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['kinesisanalyticsclientprivate',['KinesisAnalyticsClientPrivate',['../classKinesisAnalyticsClientPrivate.html',1,'KinesisAnalyticsClientPrivate'],['../classKinesisAnalyticsClientPrivate.html#a422a63aa515d5a02f4a844f1f171a470',1,'KinesisAnalyticsClientPrivate::KinesisAnalyticsClientPrivate()']]],
  ['kinesisclient',['KinesisClient',['../classKinesisClient.html',1,'KinesisClient'],['../classKinesisClient.html#a0e4a8fead8f1145cbcd29ed5e1cb92e6',1,'KinesisClient::KinesisClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classKinesisClient.html#ab1c08ae88214b19f724c271c69994fd0',1,'KinesisClient::KinesisClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['kinesisclientprivate',['KinesisClientPrivate',['../classKinesisClientPrivate.html',1,'KinesisClientPrivate'],['../classKinesisClientPrivate.html#ae9639bc8c5a098350f59d9fbfd73cae5',1,'KinesisClientPrivate::KinesisClientPrivate()']]],
  ['kmsclient',['KMSClient',['../classKMSClient.html',1,'KMSClient'],['../classKMSClient.html#a08b636b58ad433707a125ad35913e838',1,'KMSClient::KMSClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classKMSClient.html#a5c8b898ef812d967a5fdce5843d667ea',1,'KMSClient::KMSClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['kmsclientprivate',['KMSClientPrivate',['../classKMSClientPrivate.html',1,'KMSClientPrivate'],['../classKMSClientPrivate.html#a44220ca5425c405af7a0d2f546982155',1,'KMSClientPrivate::KMSClientPrivate()']]]
];
