var searchData=
[
  ['gameliftclient',['GameLiftClient',['../classGameLiftClient.html',1,'GameLiftClient'],['../classGameLiftClient.html#ad00017c8b11bfaa10da5459607781d82',1,'GameLiftClient::GameLiftClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classGameLiftClient.html#a394954f483ca252fe12105f8d4fa8e10',1,'GameLiftClient::GameLiftClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['gameliftclientprivate',['GameLiftClientPrivate',['../classGameLiftClientPrivate.html',1,'GameLiftClientPrivate'],['../classGameLiftClientPrivate.html#ae40fcf038e065a98f96ebbd2599fb792',1,'GameLiftClientPrivate::GameLiftClientPrivate()']]],
  ['getendpoint',['getEndpoint',['../classAwsEndpoint.html#a972e747803e29799e4b2ca6c211c7240',1,'AwsEndpoint']]],
  ['getqueueurl',['getQueueUrl',['../classSqsClient.html#a2a5e2b31b7064619ff7c8ed79a629a00',1,'SqsClient::getQueueUrl(const SqsGetQueueUrlRequest &amp;request)'],['../classSqsClient.html#ae4cecbd6532edf1badd44c77fe086502',1,'SqsClient::getQueueUrl(const QString &amp;queueName, const QString &amp;queueOwnerAWSAccountId=QString())']]],
  ['glacierclient',['GlacierClient',['../classGlacierClient.html',1,'GlacierClient'],['../classGlacierClient.html#ad16322cc530cf209ac63ada3d4473b7d',1,'GlacierClient::GlacierClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classGlacierClient.html#ad4a54c188324e6f14fc5d6cac2d81c0d',1,'GlacierClient::GlacierClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['glacierclientprivate',['GlacierClientPrivate',['../classGlacierClientPrivate.html',1,'GlacierClientPrivate'],['../classGlacierClientPrivate.html#a99280156a3473e55f63f84979cb70b05',1,'GlacierClientPrivate::GlacierClientPrivate()']]]
];
