var searchData=
[
  ['rdsclient',['RdsClient',['../classAWS_1_1RDS_1_1RdsClient.html',1,'AWS::RDS']]],
  ['rdsclientprivate',['RdsClientPrivate',['../classAWS_1_1RDS_1_1RdsClientPrivate.html',1,'AWS::RDS']]],
  ['redshiftclient',['RedshiftClient',['../classAWS_1_1Redshift_1_1RedshiftClient.html',1,'AWS::Redshift']]],
  ['redshiftclientprivate',['RedshiftClientPrivate',['../classAWS_1_1Redshift_1_1RedshiftClientPrivate.html',1,'AWS::Redshift']]],
  ['regionendpointinfo',['RegionEndpointInfo',['../structAwsEndpointPrivate_1_1RegionEndpointInfo.html',1,'AwsEndpointPrivate']]],
  ['regioninfo',['RegionInfo',['../structAwsEndpointPrivate_1_1RegionInfo.html',1,'AwsEndpointPrivate']]],
  ['rekognitionclient',['RekognitionClient',['../classAWS_1_1Rekognition_1_1RekognitionClient.html',1,'AWS::Rekognition']]],
  ['rekognitionclientprivate',['RekognitionClientPrivate',['../classAWS_1_1Rekognition_1_1RekognitionClientPrivate.html',1,'AWS::Rekognition']]],
  ['resourcegroupsclient',['ResourceGroupsClient',['../classAWS_1_1ResourceGroups_1_1ResourceGroupsClient.html',1,'AWS::ResourceGroups']]],
  ['resourcegroupsclientprivate',['ResourceGroupsClientPrivate',['../classAWS_1_1ResourceGroups_1_1ResourceGroupsClientPrivate.html',1,'AWS::ResourceGroups']]],
  ['resourcegroupstaggingapiclient',['ResourceGroupsTaggingAPIClient',['../classAWS_1_1ResourceGroupsTaggingAPI_1_1ResourceGroupsTaggingAPIClient.html',1,'AWS::ResourceGroupsTaggingAPI']]],
  ['resourcegroupstaggingapiclientprivate',['ResourceGroupsTaggingAPIClientPrivate',['../classAWS_1_1ResourceGroupsTaggingAPI_1_1ResourceGroupsTaggingAPIClientPrivate.html',1,'AWS::ResourceGroupsTaggingAPI']]],
  ['route53client',['Route53Client',['../classAWS_1_1Route53_1_1Route53Client.html',1,'AWS::Route53']]],
  ['route53clientprivate',['Route53ClientPrivate',['../classAWS_1_1Route53_1_1Route53ClientPrivate.html',1,'AWS::Route53']]],
  ['route53domainsclient',['Route53DomainsClient',['../classAWS_1_1Route53Domains_1_1Route53DomainsClient.html',1,'AWS::Route53Domains']]],
  ['route53domainsclientprivate',['Route53DomainsClientPrivate',['../classAWS_1_1Route53Domains_1_1Route53DomainsClientPrivate.html',1,'AWS::Route53Domains']]]
];
