var searchData=
[
  ['kinesisanalyticsclient',['KinesisAnalyticsClient',['../classKinesisAnalyticsClient.html#a2675a8fd0c9ee84deab38bcfd753151c',1,'KinesisAnalyticsClient::KinesisAnalyticsClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classKinesisAnalyticsClient.html#a26a0e5d3081810ab7c0da49928104916',1,'KinesisAnalyticsClient::KinesisAnalyticsClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['kinesisanalyticsclientprivate',['KinesisAnalyticsClientPrivate',['../classKinesisAnalyticsClientPrivate.html#a422a63aa515d5a02f4a844f1f171a470',1,'KinesisAnalyticsClientPrivate']]],
  ['kinesisclient',['KinesisClient',['../classKinesisClient.html#a0e4a8fead8f1145cbcd29ed5e1cb92e6',1,'KinesisClient::KinesisClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classKinesisClient.html#ab1c08ae88214b19f724c271c69994fd0',1,'KinesisClient::KinesisClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['kinesisclientprivate',['KinesisClientPrivate',['../classKinesisClientPrivate.html#ae9639bc8c5a098350f59d9fbfd73cae5',1,'KinesisClientPrivate']]],
  ['kmsclient',['KmsClient',['../classKmsClient.html#aba95a2203b03d21860233bbe70c54cde',1,'KmsClient::KmsClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classKmsClient.html#a4a01045c3b81154894c09fffdd684fe1',1,'KmsClient::KmsClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['kmsclientprivate',['KmsClientPrivate',['../classKmsClientPrivate.html#a831f7effb16a6e8e5777e82b5894cf04',1,'KmsClientPrivate']]]
];
