/*
    Copyright 2013-2019 Paul Colby

    This file is part of QtAws.

    QtAws is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    QtAws is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with the QtAws.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef QTAWS_IOTCLIENT_H
#define QTAWS_IOTCLIENT_H

#include "core/awsabstractclient.h"

class QNetworkReply;

namespace QtAws {
namespace IoT {

class IoTClientPrivate;
class AcceptCertificateTransferRequest;
class AcceptCertificateTransferResponse;
class AddThingToBillingGroupRequest;
class AddThingToBillingGroupResponse;
class AddThingToThingGroupRequest;
class AddThingToThingGroupResponse;
class AssociateTargetsWithJobRequest;
class AssociateTargetsWithJobResponse;
class AttachPolicyRequest;
class AttachPolicyResponse;
class AttachPrincipalPolicyRequest;
class AttachPrincipalPolicyResponse;
class AttachSecurityProfileRequest;
class AttachSecurityProfileResponse;
class AttachThingPrincipalRequest;
class AttachThingPrincipalResponse;
class CancelAuditTaskRequest;
class CancelAuditTaskResponse;
class CancelCertificateTransferRequest;
class CancelCertificateTransferResponse;
class CancelJobRequest;
class CancelJobResponse;
class CancelJobExecutionRequest;
class CancelJobExecutionResponse;
class ClearDefaultAuthorizerRequest;
class ClearDefaultAuthorizerResponse;
class CreateAuthorizerRequest;
class CreateAuthorizerResponse;
class CreateBillingGroupRequest;
class CreateBillingGroupResponse;
class CreateCertificateFromCsrRequest;
class CreateCertificateFromCsrResponse;
class CreateDynamicThingGroupRequest;
class CreateDynamicThingGroupResponse;
class CreateJobRequest;
class CreateJobResponse;
class CreateKeysAndCertificateRequest;
class CreateKeysAndCertificateResponse;
class CreateOTAUpdateRequest;
class CreateOTAUpdateResponse;
class CreatePolicyRequest;
class CreatePolicyResponse;
class CreatePolicyVersionRequest;
class CreatePolicyVersionResponse;
class CreateRoleAliasRequest;
class CreateRoleAliasResponse;
class CreateScheduledAuditRequest;
class CreateScheduledAuditResponse;
class CreateSecurityProfileRequest;
class CreateSecurityProfileResponse;
class CreateStreamRequest;
class CreateStreamResponse;
class CreateThingRequest;
class CreateThingResponse;
class CreateThingGroupRequest;
class CreateThingGroupResponse;
class CreateThingTypeRequest;
class CreateThingTypeResponse;
class CreateTopicRuleRequest;
class CreateTopicRuleResponse;
class DeleteAccountAuditConfigurationRequest;
class DeleteAccountAuditConfigurationResponse;
class DeleteAuthorizerRequest;
class DeleteAuthorizerResponse;
class DeleteBillingGroupRequest;
class DeleteBillingGroupResponse;
class DeleteCACertificateRequest;
class DeleteCACertificateResponse;
class DeleteCertificateRequest;
class DeleteCertificateResponse;
class DeleteDynamicThingGroupRequest;
class DeleteDynamicThingGroupResponse;
class DeleteJobRequest;
class DeleteJobResponse;
class DeleteJobExecutionRequest;
class DeleteJobExecutionResponse;
class DeleteOTAUpdateRequest;
class DeleteOTAUpdateResponse;
class DeletePolicyRequest;
class DeletePolicyResponse;
class DeletePolicyVersionRequest;
class DeletePolicyVersionResponse;
class DeleteRegistrationCodeRequest;
class DeleteRegistrationCodeResponse;
class DeleteRoleAliasRequest;
class DeleteRoleAliasResponse;
class DeleteScheduledAuditRequest;
class DeleteScheduledAuditResponse;
class DeleteSecurityProfileRequest;
class DeleteSecurityProfileResponse;
class DeleteStreamRequest;
class DeleteStreamResponse;
class DeleteThingRequest;
class DeleteThingResponse;
class DeleteThingGroupRequest;
class DeleteThingGroupResponse;
class DeleteThingTypeRequest;
class DeleteThingTypeResponse;
class DeleteTopicRuleRequest;
class DeleteTopicRuleResponse;
class DeleteV2LoggingLevelRequest;
class DeleteV2LoggingLevelResponse;
class DeprecateThingTypeRequest;
class DeprecateThingTypeResponse;
class DescribeAccountAuditConfigurationRequest;
class DescribeAccountAuditConfigurationResponse;
class DescribeAuditTaskRequest;
class DescribeAuditTaskResponse;
class DescribeAuthorizerRequest;
class DescribeAuthorizerResponse;
class DescribeBillingGroupRequest;
class DescribeBillingGroupResponse;
class DescribeCACertificateRequest;
class DescribeCACertificateResponse;
class DescribeCertificateRequest;
class DescribeCertificateResponse;
class DescribeDefaultAuthorizerRequest;
class DescribeDefaultAuthorizerResponse;
class DescribeEndpointRequest;
class DescribeEndpointResponse;
class DescribeEventConfigurationsRequest;
class DescribeEventConfigurationsResponse;
class DescribeIndexRequest;
class DescribeIndexResponse;
class DescribeJobRequest;
class DescribeJobResponse;
class DescribeJobExecutionRequest;
class DescribeJobExecutionResponse;
class DescribeRoleAliasRequest;
class DescribeRoleAliasResponse;
class DescribeScheduledAuditRequest;
class DescribeScheduledAuditResponse;
class DescribeSecurityProfileRequest;
class DescribeSecurityProfileResponse;
class DescribeStreamRequest;
class DescribeStreamResponse;
class DescribeThingRequest;
class DescribeThingResponse;
class DescribeThingGroupRequest;
class DescribeThingGroupResponse;
class DescribeThingRegistrationTaskRequest;
class DescribeThingRegistrationTaskResponse;
class DescribeThingTypeRequest;
class DescribeThingTypeResponse;
class DetachPolicyRequest;
class DetachPolicyResponse;
class DetachPrincipalPolicyRequest;
class DetachPrincipalPolicyResponse;
class DetachSecurityProfileRequest;
class DetachSecurityProfileResponse;
class DetachThingPrincipalRequest;
class DetachThingPrincipalResponse;
class DisableTopicRuleRequest;
class DisableTopicRuleResponse;
class EnableTopicRuleRequest;
class EnableTopicRuleResponse;
class GetEffectivePoliciesRequest;
class GetEffectivePoliciesResponse;
class GetIndexingConfigurationRequest;
class GetIndexingConfigurationResponse;
class GetJobDocumentRequest;
class GetJobDocumentResponse;
class GetLoggingOptionsRequest;
class GetLoggingOptionsResponse;
class GetOTAUpdateRequest;
class GetOTAUpdateResponse;
class GetPolicyRequest;
class GetPolicyResponse;
class GetPolicyVersionRequest;
class GetPolicyVersionResponse;
class GetRegistrationCodeRequest;
class GetRegistrationCodeResponse;
class GetStatisticsRequest;
class GetStatisticsResponse;
class GetTopicRuleRequest;
class GetTopicRuleResponse;
class GetV2LoggingOptionsRequest;
class GetV2LoggingOptionsResponse;
class ListActiveViolationsRequest;
class ListActiveViolationsResponse;
class ListAttachedPoliciesRequest;
class ListAttachedPoliciesResponse;
class ListAuditFindingsRequest;
class ListAuditFindingsResponse;
class ListAuditTasksRequest;
class ListAuditTasksResponse;
class ListAuthorizersRequest;
class ListAuthorizersResponse;
class ListBillingGroupsRequest;
class ListBillingGroupsResponse;
class ListCACertificatesRequest;
class ListCACertificatesResponse;
class ListCertificatesRequest;
class ListCertificatesResponse;
class ListCertificatesByCARequest;
class ListCertificatesByCAResponse;
class ListIndicesRequest;
class ListIndicesResponse;
class ListJobExecutionsForJobRequest;
class ListJobExecutionsForJobResponse;
class ListJobExecutionsForThingRequest;
class ListJobExecutionsForThingResponse;
class ListJobsRequest;
class ListJobsResponse;
class ListOTAUpdatesRequest;
class ListOTAUpdatesResponse;
class ListOutgoingCertificatesRequest;
class ListOutgoingCertificatesResponse;
class ListPoliciesRequest;
class ListPoliciesResponse;
class ListPolicyPrincipalsRequest;
class ListPolicyPrincipalsResponse;
class ListPolicyVersionsRequest;
class ListPolicyVersionsResponse;
class ListPrincipalPoliciesRequest;
class ListPrincipalPoliciesResponse;
class ListPrincipalThingsRequest;
class ListPrincipalThingsResponse;
class ListRoleAliasesRequest;
class ListRoleAliasesResponse;
class ListScheduledAuditsRequest;
class ListScheduledAuditsResponse;
class ListSecurityProfilesRequest;
class ListSecurityProfilesResponse;
class ListSecurityProfilesForTargetRequest;
class ListSecurityProfilesForTargetResponse;
class ListStreamsRequest;
class ListStreamsResponse;
class ListTagsForResourceRequest;
class ListTagsForResourceResponse;
class ListTargetsForPolicyRequest;
class ListTargetsForPolicyResponse;
class ListTargetsForSecurityProfileRequest;
class ListTargetsForSecurityProfileResponse;
class ListThingGroupsRequest;
class ListThingGroupsResponse;
class ListThingGroupsForThingRequest;
class ListThingGroupsForThingResponse;
class ListThingPrincipalsRequest;
class ListThingPrincipalsResponse;
class ListThingRegistrationTaskReportsRequest;
class ListThingRegistrationTaskReportsResponse;
class ListThingRegistrationTasksRequest;
class ListThingRegistrationTasksResponse;
class ListThingTypesRequest;
class ListThingTypesResponse;
class ListThingsRequest;
class ListThingsResponse;
class ListThingsInBillingGroupRequest;
class ListThingsInBillingGroupResponse;
class ListThingsInThingGroupRequest;
class ListThingsInThingGroupResponse;
class ListTopicRulesRequest;
class ListTopicRulesResponse;
class ListV2LoggingLevelsRequest;
class ListV2LoggingLevelsResponse;
class ListViolationEventsRequest;
class ListViolationEventsResponse;
class RegisterCACertificateRequest;
class RegisterCACertificateResponse;
class RegisterCertificateRequest;
class RegisterCertificateResponse;
class RegisterThingRequest;
class RegisterThingResponse;
class RejectCertificateTransferRequest;
class RejectCertificateTransferResponse;
class RemoveThingFromBillingGroupRequest;
class RemoveThingFromBillingGroupResponse;
class RemoveThingFromThingGroupRequest;
class RemoveThingFromThingGroupResponse;
class ReplaceTopicRuleRequest;
class ReplaceTopicRuleResponse;
class SearchIndexRequest;
class SearchIndexResponse;
class SetDefaultAuthorizerRequest;
class SetDefaultAuthorizerResponse;
class SetDefaultPolicyVersionRequest;
class SetDefaultPolicyVersionResponse;
class SetLoggingOptionsRequest;
class SetLoggingOptionsResponse;
class SetV2LoggingLevelRequest;
class SetV2LoggingLevelResponse;
class SetV2LoggingOptionsRequest;
class SetV2LoggingOptionsResponse;
class StartOnDemandAuditTaskRequest;
class StartOnDemandAuditTaskResponse;
class StartThingRegistrationTaskRequest;
class StartThingRegistrationTaskResponse;
class StopThingRegistrationTaskRequest;
class StopThingRegistrationTaskResponse;
class TagResourceRequest;
class TagResourceResponse;
class TestAuthorizationRequest;
class TestAuthorizationResponse;
class TestInvokeAuthorizerRequest;
class TestInvokeAuthorizerResponse;
class TransferCertificateRequest;
class TransferCertificateResponse;
class UntagResourceRequest;
class UntagResourceResponse;
class UpdateAccountAuditConfigurationRequest;
class UpdateAccountAuditConfigurationResponse;
class UpdateAuthorizerRequest;
class UpdateAuthorizerResponse;
class UpdateBillingGroupRequest;
class UpdateBillingGroupResponse;
class UpdateCACertificateRequest;
class UpdateCACertificateResponse;
class UpdateCertificateRequest;
class UpdateCertificateResponse;
class UpdateDynamicThingGroupRequest;
class UpdateDynamicThingGroupResponse;
class UpdateEventConfigurationsRequest;
class UpdateEventConfigurationsResponse;
class UpdateIndexingConfigurationRequest;
class UpdateIndexingConfigurationResponse;
class UpdateJobRequest;
class UpdateJobResponse;
class UpdateRoleAliasRequest;
class UpdateRoleAliasResponse;
class UpdateScheduledAuditRequest;
class UpdateScheduledAuditResponse;
class UpdateSecurityProfileRequest;
class UpdateSecurityProfileResponse;
class UpdateStreamRequest;
class UpdateStreamResponse;
class UpdateThingRequest;
class UpdateThingResponse;
class UpdateThingGroupRequest;
class UpdateThingGroupResponse;
class UpdateThingGroupsForThingRequest;
class UpdateThingGroupsForThingResponse;
class ValidateSecurityProfileBehaviorsRequest;
class ValidateSecurityProfileBehaviorsResponse;

class QTAWS_EXPORT IoTClient : public QtAws::Core::AwsAbstractClient {
    Q_OBJECT

public:
    IoTClient(
        const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion,
        QtAws::Core::AwsAbstractCredentials * credentials = NULL,
        QNetworkAccessManager * const manager = NULL,
        QObject * const parent = 0);

    IoTClient(
        const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL,
        QNetworkAccessManager * const manager = NULL,
        QObject * const parent = 0);

public slots:
    AcceptCertificateTransferResponse * acceptCertificateTransfer(const AcceptCertificateTransferRequest &request);
    AddThingToBillingGroupResponse * addThingToBillingGroup(const AddThingToBillingGroupRequest &request);
    AddThingToThingGroupResponse * addThingToThingGroup(const AddThingToThingGroupRequest &request);
    AssociateTargetsWithJobResponse * associateTargetsWithJob(const AssociateTargetsWithJobRequest &request);
    AttachPolicyResponse * attachPolicy(const AttachPolicyRequest &request);
    AttachPrincipalPolicyResponse * attachPrincipalPolicy(const AttachPrincipalPolicyRequest &request);
    AttachSecurityProfileResponse * attachSecurityProfile(const AttachSecurityProfileRequest &request);
    AttachThingPrincipalResponse * attachThingPrincipal(const AttachThingPrincipalRequest &request);
    CancelAuditTaskResponse * cancelAuditTask(const CancelAuditTaskRequest &request);
    CancelCertificateTransferResponse * cancelCertificateTransfer(const CancelCertificateTransferRequest &request);
    CancelJobResponse * cancelJob(const CancelJobRequest &request);
    CancelJobExecutionResponse * cancelJobExecution(const CancelJobExecutionRequest &request);
    ClearDefaultAuthorizerResponse * clearDefaultAuthorizer(const ClearDefaultAuthorizerRequest &request);
    CreateAuthorizerResponse * createAuthorizer(const CreateAuthorizerRequest &request);
    CreateBillingGroupResponse * createBillingGroup(const CreateBillingGroupRequest &request);
    CreateCertificateFromCsrResponse * createCertificateFromCsr(const CreateCertificateFromCsrRequest &request);
    CreateDynamicThingGroupResponse * createDynamicThingGroup(const CreateDynamicThingGroupRequest &request);
    CreateJobResponse * createJob(const CreateJobRequest &request);
    CreateKeysAndCertificateResponse * createKeysAndCertificate(const CreateKeysAndCertificateRequest &request);
    CreateOTAUpdateResponse * createOTAUpdate(const CreateOTAUpdateRequest &request);
    CreatePolicyResponse * createPolicy(const CreatePolicyRequest &request);
    CreatePolicyVersionResponse * createPolicyVersion(const CreatePolicyVersionRequest &request);
    CreateRoleAliasResponse * createRoleAlias(const CreateRoleAliasRequest &request);
    CreateScheduledAuditResponse * createScheduledAudit(const CreateScheduledAuditRequest &request);
    CreateSecurityProfileResponse * createSecurityProfile(const CreateSecurityProfileRequest &request);
    CreateStreamResponse * createStream(const CreateStreamRequest &request);
    CreateThingResponse * createThing(const CreateThingRequest &request);
    CreateThingGroupResponse * createThingGroup(const CreateThingGroupRequest &request);
    CreateThingTypeResponse * createThingType(const CreateThingTypeRequest &request);
    CreateTopicRuleResponse * createTopicRule(const CreateTopicRuleRequest &request);
    DeleteAccountAuditConfigurationResponse * deleteAccountAuditConfiguration(const DeleteAccountAuditConfigurationRequest &request);
    DeleteAuthorizerResponse * deleteAuthorizer(const DeleteAuthorizerRequest &request);
    DeleteBillingGroupResponse * deleteBillingGroup(const DeleteBillingGroupRequest &request);
    DeleteCACertificateResponse * deleteCACertificate(const DeleteCACertificateRequest &request);
    DeleteCertificateResponse * deleteCertificate(const DeleteCertificateRequest &request);
    DeleteDynamicThingGroupResponse * deleteDynamicThingGroup(const DeleteDynamicThingGroupRequest &request);
    DeleteJobResponse * deleteJob(const DeleteJobRequest &request);
    DeleteJobExecutionResponse * deleteJobExecution(const DeleteJobExecutionRequest &request);
    DeleteOTAUpdateResponse * deleteOTAUpdate(const DeleteOTAUpdateRequest &request);
    DeletePolicyResponse * deletePolicy(const DeletePolicyRequest &request);
    DeletePolicyVersionResponse * deletePolicyVersion(const DeletePolicyVersionRequest &request);
    DeleteRegistrationCodeResponse * deleteRegistrationCode(const DeleteRegistrationCodeRequest &request);
    DeleteRoleAliasResponse * deleteRoleAlias(const DeleteRoleAliasRequest &request);
    DeleteScheduledAuditResponse * deleteScheduledAudit(const DeleteScheduledAuditRequest &request);
    DeleteSecurityProfileResponse * deleteSecurityProfile(const DeleteSecurityProfileRequest &request);
    DeleteStreamResponse * deleteStream(const DeleteStreamRequest &request);
    DeleteThingResponse * deleteThing(const DeleteThingRequest &request);
    DeleteThingGroupResponse * deleteThingGroup(const DeleteThingGroupRequest &request);
    DeleteThingTypeResponse * deleteThingType(const DeleteThingTypeRequest &request);
    DeleteTopicRuleResponse * deleteTopicRule(const DeleteTopicRuleRequest &request);
    DeleteV2LoggingLevelResponse * deleteV2LoggingLevel(const DeleteV2LoggingLevelRequest &request);
    DeprecateThingTypeResponse * deprecateThingType(const DeprecateThingTypeRequest &request);
    DescribeAccountAuditConfigurationResponse * describeAccountAuditConfiguration(const DescribeAccountAuditConfigurationRequest &request);
    DescribeAuditTaskResponse * describeAuditTask(const DescribeAuditTaskRequest &request);
    DescribeAuthorizerResponse * describeAuthorizer(const DescribeAuthorizerRequest &request);
    DescribeBillingGroupResponse * describeBillingGroup(const DescribeBillingGroupRequest &request);
    DescribeCACertificateResponse * describeCACertificate(const DescribeCACertificateRequest &request);
    DescribeCertificateResponse * describeCertificate(const DescribeCertificateRequest &request);
    DescribeDefaultAuthorizerResponse * describeDefaultAuthorizer(const DescribeDefaultAuthorizerRequest &request);
    DescribeEndpointResponse * describeEndpoint(const DescribeEndpointRequest &request);
    DescribeEventConfigurationsResponse * describeEventConfigurations(const DescribeEventConfigurationsRequest &request);
    DescribeIndexResponse * describeIndex(const DescribeIndexRequest &request);
    DescribeJobResponse * describeJob(const DescribeJobRequest &request);
    DescribeJobExecutionResponse * describeJobExecution(const DescribeJobExecutionRequest &request);
    DescribeRoleAliasResponse * describeRoleAlias(const DescribeRoleAliasRequest &request);
    DescribeScheduledAuditResponse * describeScheduledAudit(const DescribeScheduledAuditRequest &request);
    DescribeSecurityProfileResponse * describeSecurityProfile(const DescribeSecurityProfileRequest &request);
    DescribeStreamResponse * describeStream(const DescribeStreamRequest &request);
    DescribeThingResponse * describeThing(const DescribeThingRequest &request);
    DescribeThingGroupResponse * describeThingGroup(const DescribeThingGroupRequest &request);
    DescribeThingRegistrationTaskResponse * describeThingRegistrationTask(const DescribeThingRegistrationTaskRequest &request);
    DescribeThingTypeResponse * describeThingType(const DescribeThingTypeRequest &request);
    DetachPolicyResponse * detachPolicy(const DetachPolicyRequest &request);
    DetachPrincipalPolicyResponse * detachPrincipalPolicy(const DetachPrincipalPolicyRequest &request);
    DetachSecurityProfileResponse * detachSecurityProfile(const DetachSecurityProfileRequest &request);
    DetachThingPrincipalResponse * detachThingPrincipal(const DetachThingPrincipalRequest &request);
    DisableTopicRuleResponse * disableTopicRule(const DisableTopicRuleRequest &request);
    EnableTopicRuleResponse * enableTopicRule(const EnableTopicRuleRequest &request);
    GetEffectivePoliciesResponse * getEffectivePolicies(const GetEffectivePoliciesRequest &request);
    GetIndexingConfigurationResponse * getIndexingConfiguration(const GetIndexingConfigurationRequest &request);
    GetJobDocumentResponse * getJobDocument(const GetJobDocumentRequest &request);
    GetLoggingOptionsResponse * getLoggingOptions(const GetLoggingOptionsRequest &request);
    GetOTAUpdateResponse * getOTAUpdate(const GetOTAUpdateRequest &request);
    GetPolicyResponse * getPolicy(const GetPolicyRequest &request);
    GetPolicyVersionResponse * getPolicyVersion(const GetPolicyVersionRequest &request);
    GetRegistrationCodeResponse * getRegistrationCode(const GetRegistrationCodeRequest &request);
    GetStatisticsResponse * getStatistics(const GetStatisticsRequest &request);
    GetTopicRuleResponse * getTopicRule(const GetTopicRuleRequest &request);
    GetV2LoggingOptionsResponse * getV2LoggingOptions(const GetV2LoggingOptionsRequest &request);
    ListActiveViolationsResponse * listActiveViolations(const ListActiveViolationsRequest &request);
    ListAttachedPoliciesResponse * listAttachedPolicies(const ListAttachedPoliciesRequest &request);
    ListAuditFindingsResponse * listAuditFindings(const ListAuditFindingsRequest &request);
    ListAuditTasksResponse * listAuditTasks(const ListAuditTasksRequest &request);
    ListAuthorizersResponse * listAuthorizers(const ListAuthorizersRequest &request);
    ListBillingGroupsResponse * listBillingGroups(const ListBillingGroupsRequest &request);
    ListCACertificatesResponse * listCACertificates(const ListCACertificatesRequest &request);
    ListCertificatesResponse * listCertificates(const ListCertificatesRequest &request);
    ListCertificatesByCAResponse * listCertificatesByCA(const ListCertificatesByCARequest &request);
    ListIndicesResponse * listIndices(const ListIndicesRequest &request);
    ListJobExecutionsForJobResponse * listJobExecutionsForJob(const ListJobExecutionsForJobRequest &request);
    ListJobExecutionsForThingResponse * listJobExecutionsForThing(const ListJobExecutionsForThingRequest &request);
    ListJobsResponse * listJobs(const ListJobsRequest &request);
    ListOTAUpdatesResponse * listOTAUpdates(const ListOTAUpdatesRequest &request);
    ListOutgoingCertificatesResponse * listOutgoingCertificates(const ListOutgoingCertificatesRequest &request);
    ListPoliciesResponse * listPolicies(const ListPoliciesRequest &request);
    ListPolicyPrincipalsResponse * listPolicyPrincipals(const ListPolicyPrincipalsRequest &request);
    ListPolicyVersionsResponse * listPolicyVersions(const ListPolicyVersionsRequest &request);
    ListPrincipalPoliciesResponse * listPrincipalPolicies(const ListPrincipalPoliciesRequest &request);
    ListPrincipalThingsResponse * listPrincipalThings(const ListPrincipalThingsRequest &request);
    ListRoleAliasesResponse * listRoleAliases(const ListRoleAliasesRequest &request);
    ListScheduledAuditsResponse * listScheduledAudits(const ListScheduledAuditsRequest &request);
    ListSecurityProfilesResponse * listSecurityProfiles(const ListSecurityProfilesRequest &request);
    ListSecurityProfilesForTargetResponse * listSecurityProfilesForTarget(const ListSecurityProfilesForTargetRequest &request);
    ListStreamsResponse * listStreams(const ListStreamsRequest &request);
    ListTagsForResourceResponse * listTagsForResource(const ListTagsForResourceRequest &request);
    ListTargetsForPolicyResponse * listTargetsForPolicy(const ListTargetsForPolicyRequest &request);
    ListTargetsForSecurityProfileResponse * listTargetsForSecurityProfile(const ListTargetsForSecurityProfileRequest &request);
    ListThingGroupsResponse * listThingGroups(const ListThingGroupsRequest &request);
    ListThingGroupsForThingResponse * listThingGroupsForThing(const ListThingGroupsForThingRequest &request);
    ListThingPrincipalsResponse * listThingPrincipals(const ListThingPrincipalsRequest &request);
    ListThingRegistrationTaskReportsResponse * listThingRegistrationTaskReports(const ListThingRegistrationTaskReportsRequest &request);
    ListThingRegistrationTasksResponse * listThingRegistrationTasks(const ListThingRegistrationTasksRequest &request);
    ListThingTypesResponse * listThingTypes(const ListThingTypesRequest &request);
    ListThingsResponse * listThings(const ListThingsRequest &request);
    ListThingsInBillingGroupResponse * listThingsInBillingGroup(const ListThingsInBillingGroupRequest &request);
    ListThingsInThingGroupResponse * listThingsInThingGroup(const ListThingsInThingGroupRequest &request);
    ListTopicRulesResponse * listTopicRules(const ListTopicRulesRequest &request);
    ListV2LoggingLevelsResponse * listV2LoggingLevels(const ListV2LoggingLevelsRequest &request);
    ListViolationEventsResponse * listViolationEvents(const ListViolationEventsRequest &request);
    RegisterCACertificateResponse * registerCACertificate(const RegisterCACertificateRequest &request);
    RegisterCertificateResponse * registerCertificate(const RegisterCertificateRequest &request);
    RegisterThingResponse * registerThing(const RegisterThingRequest &request);
    RejectCertificateTransferResponse * rejectCertificateTransfer(const RejectCertificateTransferRequest &request);
    RemoveThingFromBillingGroupResponse * removeThingFromBillingGroup(const RemoveThingFromBillingGroupRequest &request);
    RemoveThingFromThingGroupResponse * removeThingFromThingGroup(const RemoveThingFromThingGroupRequest &request);
    ReplaceTopicRuleResponse * replaceTopicRule(const ReplaceTopicRuleRequest &request);
    SearchIndexResponse * searchIndex(const SearchIndexRequest &request);
    SetDefaultAuthorizerResponse * setDefaultAuthorizer(const SetDefaultAuthorizerRequest &request);
    SetDefaultPolicyVersionResponse * setDefaultPolicyVersion(const SetDefaultPolicyVersionRequest &request);
    SetLoggingOptionsResponse * setLoggingOptions(const SetLoggingOptionsRequest &request);
    SetV2LoggingLevelResponse * setV2LoggingLevel(const SetV2LoggingLevelRequest &request);
    SetV2LoggingOptionsResponse * setV2LoggingOptions(const SetV2LoggingOptionsRequest &request);
    StartOnDemandAuditTaskResponse * startOnDemandAuditTask(const StartOnDemandAuditTaskRequest &request);
    StartThingRegistrationTaskResponse * startThingRegistrationTask(const StartThingRegistrationTaskRequest &request);
    StopThingRegistrationTaskResponse * stopThingRegistrationTask(const StopThingRegistrationTaskRequest &request);
    TagResourceResponse * tagResource(const TagResourceRequest &request);
    TestAuthorizationResponse * testAuthorization(const TestAuthorizationRequest &request);
    TestInvokeAuthorizerResponse * testInvokeAuthorizer(const TestInvokeAuthorizerRequest &request);
    TransferCertificateResponse * transferCertificate(const TransferCertificateRequest &request);
    UntagResourceResponse * untagResource(const UntagResourceRequest &request);
    UpdateAccountAuditConfigurationResponse * updateAccountAuditConfiguration(const UpdateAccountAuditConfigurationRequest &request);
    UpdateAuthorizerResponse * updateAuthorizer(const UpdateAuthorizerRequest &request);
    UpdateBillingGroupResponse * updateBillingGroup(const UpdateBillingGroupRequest &request);
    UpdateCACertificateResponse * updateCACertificate(const UpdateCACertificateRequest &request);
    UpdateCertificateResponse * updateCertificate(const UpdateCertificateRequest &request);
    UpdateDynamicThingGroupResponse * updateDynamicThingGroup(const UpdateDynamicThingGroupRequest &request);
    UpdateEventConfigurationsResponse * updateEventConfigurations(const UpdateEventConfigurationsRequest &request);
    UpdateIndexingConfigurationResponse * updateIndexingConfiguration(const UpdateIndexingConfigurationRequest &request);
    UpdateJobResponse * updateJob(const UpdateJobRequest &request);
    UpdateRoleAliasResponse * updateRoleAlias(const UpdateRoleAliasRequest &request);
    UpdateScheduledAuditResponse * updateScheduledAudit(const UpdateScheduledAuditRequest &request);
    UpdateSecurityProfileResponse * updateSecurityProfile(const UpdateSecurityProfileRequest &request);
    UpdateStreamResponse * updateStream(const UpdateStreamRequest &request);
    UpdateThingResponse * updateThing(const UpdateThingRequest &request);
    UpdateThingGroupResponse * updateThingGroup(const UpdateThingGroupRequest &request);
    UpdateThingGroupsForThingResponse * updateThingGroupsForThing(const UpdateThingGroupsForThingRequest &request);
    ValidateSecurityProfileBehaviorsResponse * validateSecurityProfileBehaviors(const ValidateSecurityProfileBehaviorsRequest &request);

private:
    Q_DECLARE_PRIVATE(IoTClient)
    Q_DISABLE_COPY(IoTClient)

};

} // namespace IoT
} // namespace QtAws

#endif
