include(../../common.pri)

TARGET = QtAwsElasticBeanstalk
TEMPLATE = lib
QT -= gui
QT += network
DEFINES += QTAWS_LIBRARY
DEFINES += QT_NO_CAST_FROM_ASCII QT_NO_CAST_TO_ASCII

INCLUDEPATH = $$TOPDIR/src

HEADERS += \
    abortenvironmentupdaterequest.h \
    abortenvironmentupdaterequest_p.h \
    abortenvironmentupdateresponse.h \
    abortenvironmentupdateresponse_p.h \
    applyenvironmentmanagedactionrequest.h \
    applyenvironmentmanagedactionrequest_p.h \
    applyenvironmentmanagedactionresponse.h \
    applyenvironmentmanagedactionresponse_p.h \
    checkdnsavailabilityrequest.h \
    checkdnsavailabilityrequest_p.h \
    checkdnsavailabilityresponse.h \
    checkdnsavailabilityresponse_p.h \
    composeenvironmentsrequest.h \
    composeenvironmentsrequest_p.h \
    composeenvironmentsresponse.h \
    composeenvironmentsresponse_p.h \
    createapplicationrequest.h \
    createapplicationrequest_p.h \
    createapplicationresponse.h \
    createapplicationresponse_p.h \
    createapplicationversionrequest.h \
    createapplicationversionrequest_p.h \
    createapplicationversionresponse.h \
    createapplicationversionresponse_p.h \
    createconfigurationtemplaterequest.h \
    createconfigurationtemplaterequest_p.h \
    createconfigurationtemplateresponse.h \
    createconfigurationtemplateresponse_p.h \
    createenvironmentrequest.h \
    createenvironmentrequest_p.h \
    createenvironmentresponse.h \
    createenvironmentresponse_p.h \
    createplatformversionrequest.h \
    createplatformversionrequest_p.h \
    createplatformversionresponse.h \
    createplatformversionresponse_p.h \
    createstoragelocationrequest.h \
    createstoragelocationrequest_p.h \
    createstoragelocationresponse.h \
    createstoragelocationresponse_p.h \
    deleteapplicationrequest.h \
    deleteapplicationrequest_p.h \
    deleteapplicationresponse.h \
    deleteapplicationresponse_p.h \
    deleteapplicationversionrequest.h \
    deleteapplicationversionrequest_p.h \
    deleteapplicationversionresponse.h \
    deleteapplicationversionresponse_p.h \
    deleteconfigurationtemplaterequest.h \
    deleteconfigurationtemplaterequest_p.h \
    deleteconfigurationtemplateresponse.h \
    deleteconfigurationtemplateresponse_p.h \
    deleteenvironmentconfigurationrequest.h \
    deleteenvironmentconfigurationrequest_p.h \
    deleteenvironmentconfigurationresponse.h \
    deleteenvironmentconfigurationresponse_p.h \
    deleteplatformversionrequest.h \
    deleteplatformversionrequest_p.h \
    deleteplatformversionresponse.h \
    deleteplatformversionresponse_p.h \
    describeaccountattributesrequest.h \
    describeaccountattributesrequest_p.h \
    describeaccountattributesresponse.h \
    describeaccountattributesresponse_p.h \
    describeapplicationsrequest.h \
    describeapplicationsrequest_p.h \
    describeapplicationsresponse.h \
    describeapplicationsresponse_p.h \
    describeapplicationversionsrequest.h \
    describeapplicationversionsrequest_p.h \
    describeapplicationversionsresponse.h \
    describeapplicationversionsresponse_p.h \
    describeconfigurationoptionsrequest.h \
    describeconfigurationoptionsrequest_p.h \
    describeconfigurationoptionsresponse.h \
    describeconfigurationoptionsresponse_p.h \
    describeconfigurationsettingsrequest.h \
    describeconfigurationsettingsrequest_p.h \
    describeconfigurationsettingsresponse.h \
    describeconfigurationsettingsresponse_p.h \
    describeenvironmenthealthrequest.h \
    describeenvironmenthealthrequest_p.h \
    describeenvironmenthealthresponse.h \
    describeenvironmenthealthresponse_p.h \
    describeenvironmentmanagedactionhistoryrequest.h \
    describeenvironmentmanagedactionhistoryrequest_p.h \
    describeenvironmentmanagedactionhistoryresponse.h \
    describeenvironmentmanagedactionhistoryresponse_p.h \
    describeenvironmentmanagedactionsrequest.h \
    describeenvironmentmanagedactionsrequest_p.h \
    describeenvironmentmanagedactionsresponse.h \
    describeenvironmentmanagedactionsresponse_p.h \
    describeenvironmentresourcesrequest.h \
    describeenvironmentresourcesrequest_p.h \
    describeenvironmentresourcesresponse.h \
    describeenvironmentresourcesresponse_p.h \
    describeenvironmentsrequest.h \
    describeenvironmentsrequest_p.h \
    describeenvironmentsresponse.h \
    describeenvironmentsresponse_p.h \
    describeeventsrequest.h \
    describeeventsrequest_p.h \
    describeeventsresponse.h \
    describeeventsresponse_p.h \
    describeinstanceshealthrequest.h \
    describeinstanceshealthrequest_p.h \
    describeinstanceshealthresponse.h \
    describeinstanceshealthresponse_p.h \
    describeplatformversionrequest.h \
    describeplatformversionrequest_p.h \
    describeplatformversionresponse.h \
    describeplatformversionresponse_p.h \
    elasticbeanstalkclient.h \
    elasticbeanstalkclient_p.h \
    elasticbeanstalkrequest.h \
    elasticbeanstalkrequest_p.h \
    elasticbeanstalkresponse.h \
    elasticbeanstalkresponse_p.h \
    listavailablesolutionstacksrequest.h \
    listavailablesolutionstacksrequest_p.h \
    listavailablesolutionstacksresponse.h \
    listavailablesolutionstacksresponse_p.h \
    listplatformversionsrequest.h \
    listplatformversionsrequest_p.h \
    listplatformversionsresponse.h \
    listplatformversionsresponse_p.h \
    listtagsforresourcerequest.h \
    listtagsforresourcerequest_p.h \
    listtagsforresourceresponse.h \
    listtagsforresourceresponse_p.h \
    rebuildenvironmentrequest.h \
    rebuildenvironmentrequest_p.h \
    rebuildenvironmentresponse.h \
    rebuildenvironmentresponse_p.h \
    requestenvironmentinforequest.h \
    requestenvironmentinforequest_p.h \
    requestenvironmentinforesponse.h \
    requestenvironmentinforesponse_p.h \
    restartappserverrequest.h \
    restartappserverrequest_p.h \
    restartappserverresponse.h \
    restartappserverresponse_p.h \
    retrieveenvironmentinforequest.h \
    retrieveenvironmentinforequest_p.h \
    retrieveenvironmentinforesponse.h \
    retrieveenvironmentinforesponse_p.h \
    swapenvironmentcnamesrequest.h \
    swapenvironmentcnamesrequest_p.h \
    swapenvironmentcnamesresponse.h \
    swapenvironmentcnamesresponse_p.h \
    terminateenvironmentrequest.h \
    terminateenvironmentrequest_p.h \
    terminateenvironmentresponse.h \
    terminateenvironmentresponse_p.h \
    updateapplicationrequest.h \
    updateapplicationrequest_p.h \
    updateapplicationresourcelifecyclerequest.h \
    updateapplicationresourcelifecyclerequest_p.h \
    updateapplicationresourcelifecycleresponse.h \
    updateapplicationresourcelifecycleresponse_p.h \
    updateapplicationresponse.h \
    updateapplicationresponse_p.h \
    updateapplicationversionrequest.h \
    updateapplicationversionrequest_p.h \
    updateapplicationversionresponse.h \
    updateapplicationversionresponse_p.h \
    updateconfigurationtemplaterequest.h \
    updateconfigurationtemplaterequest_p.h \
    updateconfigurationtemplateresponse.h \
    updateconfigurationtemplateresponse_p.h \
    updateenvironmentrequest.h \
    updateenvironmentrequest_p.h \
    updateenvironmentresponse.h \
    updateenvironmentresponse_p.h \
    updatetagsforresourcerequest.h \
    updatetagsforresourcerequest_p.h \
    updatetagsforresourceresponse.h \
    updatetagsforresourceresponse_p.h \
    validateconfigurationsettingsrequest.h \
    validateconfigurationsettingsrequest_p.h \
    validateconfigurationsettingsresponse.h \
    validateconfigurationsettingsresponse_p.h \

SOURCES += \
    abortenvironmentupdaterequest.cpp \
    abortenvironmentupdateresponse.cpp \
    applyenvironmentmanagedactionrequest.cpp \
    applyenvironmentmanagedactionresponse.cpp \
    checkdnsavailabilityrequest.cpp \
    checkdnsavailabilityresponse.cpp \
    composeenvironmentsrequest.cpp \
    composeenvironmentsresponse.cpp \
    createapplicationrequest.cpp \
    createapplicationresponse.cpp \
    createapplicationversionrequest.cpp \
    createapplicationversionresponse.cpp \
    createconfigurationtemplaterequest.cpp \
    createconfigurationtemplateresponse.cpp \
    createenvironmentrequest.cpp \
    createenvironmentresponse.cpp \
    createplatformversionrequest.cpp \
    createplatformversionresponse.cpp \
    createstoragelocationrequest.cpp \
    createstoragelocationresponse.cpp \
    deleteapplicationrequest.cpp \
    deleteapplicationresponse.cpp \
    deleteapplicationversionrequest.cpp \
    deleteapplicationversionresponse.cpp \
    deleteconfigurationtemplaterequest.cpp \
    deleteconfigurationtemplateresponse.cpp \
    deleteenvironmentconfigurationrequest.cpp \
    deleteenvironmentconfigurationresponse.cpp \
    deleteplatformversionrequest.cpp \
    deleteplatformversionresponse.cpp \
    describeaccountattributesrequest.cpp \
    describeaccountattributesresponse.cpp \
    describeapplicationsrequest.cpp \
    describeapplicationsresponse.cpp \
    describeapplicationversionsrequest.cpp \
    describeapplicationversionsresponse.cpp \
    describeconfigurationoptionsrequest.cpp \
    describeconfigurationoptionsresponse.cpp \
    describeconfigurationsettingsrequest.cpp \
    describeconfigurationsettingsresponse.cpp \
    describeenvironmenthealthrequest.cpp \
    describeenvironmenthealthresponse.cpp \
    describeenvironmentmanagedactionhistoryrequest.cpp \
    describeenvironmentmanagedactionhistoryresponse.cpp \
    describeenvironmentmanagedactionsrequest.cpp \
    describeenvironmentmanagedactionsresponse.cpp \
    describeenvironmentresourcesrequest.cpp \
    describeenvironmentresourcesresponse.cpp \
    describeenvironmentsrequest.cpp \
    describeenvironmentsresponse.cpp \
    describeeventsrequest.cpp \
    describeeventsresponse.cpp \
    describeinstanceshealthrequest.cpp \
    describeinstanceshealthresponse.cpp \
    describeplatformversionrequest.cpp \
    describeplatformversionresponse.cpp \
    elasticbeanstalkclient.cpp \
    elasticbeanstalkrequest.cpp \
    elasticbeanstalkresponse.cpp \
    listavailablesolutionstacksrequest.cpp \
    listavailablesolutionstacksresponse.cpp \
    listplatformversionsrequest.cpp \
    listplatformversionsresponse.cpp \
    listtagsforresourcerequest.cpp \
    listtagsforresourceresponse.cpp \
    rebuildenvironmentrequest.cpp \
    rebuildenvironmentresponse.cpp \
    requestenvironmentinforequest.cpp \
    requestenvironmentinforesponse.cpp \
    restartappserverrequest.cpp \
    restartappserverresponse.cpp \
    retrieveenvironmentinforequest.cpp \
    retrieveenvironmentinforesponse.cpp \
    swapenvironmentcnamesrequest.cpp \
    swapenvironmentcnamesresponse.cpp \
    terminateenvironmentrequest.cpp \
    terminateenvironmentresponse.cpp \
    updateapplicationrequest.cpp \
    updateapplicationresourcelifecyclerequest.cpp \
    updateapplicationresourcelifecycleresponse.cpp \
    updateapplicationresponse.cpp \
    updateapplicationversionrequest.cpp \
    updateapplicationversionresponse.cpp \
    updateconfigurationtemplaterequest.cpp \
    updateconfigurationtemplateresponse.cpp \
    updateenvironmentrequest.cpp \
    updateenvironmentresponse.cpp \
    updatetagsforresourcerequest.cpp \
    updatetagsforresourceresponse.cpp \
    validateconfigurationsettingsrequest.cpp \
    validateconfigurationsettingsresponse.cpp \

win32:CONFIG += skip_target_version_ext
