include(../../common.pri)

TARGET = QtAwsGameLift
TEMPLATE = lib
QT -= gui
QT += network
DEFINES += QTAWS_LIBRARY
DEFINES += QT_NO_CAST_FROM_ASCII QT_NO_CAST_TO_ASCII

INCLUDEPATH = $$TOPDIR/src

HEADERS += \
    acceptmatchrequest.h \
    acceptmatchrequest_p.h \
    acceptmatchresponse.h \
    acceptmatchresponse_p.h \
    createaliasrequest.h \
    createaliasrequest_p.h \
    createaliasresponse.h \
    createaliasresponse_p.h \
    createbuildrequest.h \
    createbuildrequest_p.h \
    createbuildresponse.h \
    createbuildresponse_p.h \
    createfleetrequest.h \
    createfleetrequest_p.h \
    createfleetresponse.h \
    createfleetresponse_p.h \
    creategamesessionqueuerequest.h \
    creategamesessionqueuerequest_p.h \
    creategamesessionqueueresponse.h \
    creategamesessionqueueresponse_p.h \
    creategamesessionrequest.h \
    creategamesessionrequest_p.h \
    creategamesessionresponse.h \
    creategamesessionresponse_p.h \
    creatematchmakingconfigurationrequest.h \
    creatematchmakingconfigurationrequest_p.h \
    creatematchmakingconfigurationresponse.h \
    creatematchmakingconfigurationresponse_p.h \
    creatematchmakingrulesetrequest.h \
    creatematchmakingrulesetrequest_p.h \
    creatematchmakingrulesetresponse.h \
    creatematchmakingrulesetresponse_p.h \
    createplayersessionrequest.h \
    createplayersessionrequest_p.h \
    createplayersessionresponse.h \
    createplayersessionresponse_p.h \
    createplayersessionsrequest.h \
    createplayersessionsrequest_p.h \
    createplayersessionsresponse.h \
    createplayersessionsresponse_p.h \
    createvpcpeeringauthorizationrequest.h \
    createvpcpeeringauthorizationrequest_p.h \
    createvpcpeeringauthorizationresponse.h \
    createvpcpeeringauthorizationresponse_p.h \
    createvpcpeeringconnectionrequest.h \
    createvpcpeeringconnectionrequest_p.h \
    createvpcpeeringconnectionresponse.h \
    createvpcpeeringconnectionresponse_p.h \
    deletealiasrequest.h \
    deletealiasrequest_p.h \
    deletealiasresponse.h \
    deletealiasresponse_p.h \
    deletebuildrequest.h \
    deletebuildrequest_p.h \
    deletebuildresponse.h \
    deletebuildresponse_p.h \
    deletefleetrequest.h \
    deletefleetrequest_p.h \
    deletefleetresponse.h \
    deletefleetresponse_p.h \
    deletegamesessionqueuerequest.h \
    deletegamesessionqueuerequest_p.h \
    deletegamesessionqueueresponse.h \
    deletegamesessionqueueresponse_p.h \
    deletematchmakingconfigurationrequest.h \
    deletematchmakingconfigurationrequest_p.h \
    deletematchmakingconfigurationresponse.h \
    deletematchmakingconfigurationresponse_p.h \
    deletescalingpolicyrequest.h \
    deletescalingpolicyrequest_p.h \
    deletescalingpolicyresponse.h \
    deletescalingpolicyresponse_p.h \
    deletevpcpeeringauthorizationrequest.h \
    deletevpcpeeringauthorizationrequest_p.h \
    deletevpcpeeringauthorizationresponse.h \
    deletevpcpeeringauthorizationresponse_p.h \
    deletevpcpeeringconnectionrequest.h \
    deletevpcpeeringconnectionrequest_p.h \
    deletevpcpeeringconnectionresponse.h \
    deletevpcpeeringconnectionresponse_p.h \
    describealiasrequest.h \
    describealiasrequest_p.h \
    describealiasresponse.h \
    describealiasresponse_p.h \
    describebuildrequest.h \
    describebuildrequest_p.h \
    describebuildresponse.h \
    describebuildresponse_p.h \
    describeec2instancelimitsrequest.h \
    describeec2instancelimitsrequest_p.h \
    describeec2instancelimitsresponse.h \
    describeec2instancelimitsresponse_p.h \
    describefleetattributesrequest.h \
    describefleetattributesrequest_p.h \
    describefleetattributesresponse.h \
    describefleetattributesresponse_p.h \
    describefleetcapacityrequest.h \
    describefleetcapacityrequest_p.h \
    describefleetcapacityresponse.h \
    describefleetcapacityresponse_p.h \
    describefleeteventsrequest.h \
    describefleeteventsrequest_p.h \
    describefleeteventsresponse.h \
    describefleeteventsresponse_p.h \
    describefleetportsettingsrequest.h \
    describefleetportsettingsrequest_p.h \
    describefleetportsettingsresponse.h \
    describefleetportsettingsresponse_p.h \
    describefleetutilizationrequest.h \
    describefleetutilizationrequest_p.h \
    describefleetutilizationresponse.h \
    describefleetutilizationresponse_p.h \
    describegamesessiondetailsrequest.h \
    describegamesessiondetailsrequest_p.h \
    describegamesessiondetailsresponse.h \
    describegamesessiondetailsresponse_p.h \
    describegamesessionplacementrequest.h \
    describegamesessionplacementrequest_p.h \
    describegamesessionplacementresponse.h \
    describegamesessionplacementresponse_p.h \
    describegamesessionqueuesrequest.h \
    describegamesessionqueuesrequest_p.h \
    describegamesessionqueuesresponse.h \
    describegamesessionqueuesresponse_p.h \
    describegamesessionsrequest.h \
    describegamesessionsrequest_p.h \
    describegamesessionsresponse.h \
    describegamesessionsresponse_p.h \
    describeinstancesrequest.h \
    describeinstancesrequest_p.h \
    describeinstancesresponse.h \
    describeinstancesresponse_p.h \
    describematchmakingconfigurationsrequest.h \
    describematchmakingconfigurationsrequest_p.h \
    describematchmakingconfigurationsresponse.h \
    describematchmakingconfigurationsresponse_p.h \
    describematchmakingrequest.h \
    describematchmakingrequest_p.h \
    describematchmakingresponse.h \
    describematchmakingresponse_p.h \
    describematchmakingrulesetsrequest.h \
    describematchmakingrulesetsrequest_p.h \
    describematchmakingrulesetsresponse.h \
    describematchmakingrulesetsresponse_p.h \
    describeplayersessionsrequest.h \
    describeplayersessionsrequest_p.h \
    describeplayersessionsresponse.h \
    describeplayersessionsresponse_p.h \
    describeruntimeconfigurationrequest.h \
    describeruntimeconfigurationrequest_p.h \
    describeruntimeconfigurationresponse.h \
    describeruntimeconfigurationresponse_p.h \
    describescalingpoliciesrequest.h \
    describescalingpoliciesrequest_p.h \
    describescalingpoliciesresponse.h \
    describescalingpoliciesresponse_p.h \
    describevpcpeeringauthorizationsrequest.h \
    describevpcpeeringauthorizationsrequest_p.h \
    describevpcpeeringauthorizationsresponse.h \
    describevpcpeeringauthorizationsresponse_p.h \
    describevpcpeeringconnectionsrequest.h \
    describevpcpeeringconnectionsrequest_p.h \
    describevpcpeeringconnectionsresponse.h \
    describevpcpeeringconnectionsresponse_p.h \
    gameliftclient.h \
    gameliftclient_p.h \
    gameliftrequest.h \
    gameliftrequest_p.h \
    gameliftresponse.h \
    gameliftresponse_p.h \
    getgamesessionlogurlrequest.h \
    getgamesessionlogurlrequest_p.h \
    getgamesessionlogurlresponse.h \
    getgamesessionlogurlresponse_p.h \
    getinstanceaccessrequest.h \
    getinstanceaccessrequest_p.h \
    getinstanceaccessresponse.h \
    getinstanceaccessresponse_p.h \
    listaliasesrequest.h \
    listaliasesrequest_p.h \
    listaliasesresponse.h \
    listaliasesresponse_p.h \
    listbuildsrequest.h \
    listbuildsrequest_p.h \
    listbuildsresponse.h \
    listbuildsresponse_p.h \
    listfleetsrequest.h \
    listfleetsrequest_p.h \
    listfleetsresponse.h \
    listfleetsresponse_p.h \
    putscalingpolicyrequest.h \
    putscalingpolicyrequest_p.h \
    putscalingpolicyresponse.h \
    putscalingpolicyresponse_p.h \
    requestuploadcredentialsrequest.h \
    requestuploadcredentialsrequest_p.h \
    requestuploadcredentialsresponse.h \
    requestuploadcredentialsresponse_p.h \
    resolvealiasrequest.h \
    resolvealiasrequest_p.h \
    resolvealiasresponse.h \
    resolvealiasresponse_p.h \
    searchgamesessionsrequest.h \
    searchgamesessionsrequest_p.h \
    searchgamesessionsresponse.h \
    searchgamesessionsresponse_p.h \
    startgamesessionplacementrequest.h \
    startgamesessionplacementrequest_p.h \
    startgamesessionplacementresponse.h \
    startgamesessionplacementresponse_p.h \
    startmatchbackfillrequest.h \
    startmatchbackfillrequest_p.h \
    startmatchbackfillresponse.h \
    startmatchbackfillresponse_p.h \
    startmatchmakingrequest.h \
    startmatchmakingrequest_p.h \
    startmatchmakingresponse.h \
    startmatchmakingresponse_p.h \
    stopgamesessionplacementrequest.h \
    stopgamesessionplacementrequest_p.h \
    stopgamesessionplacementresponse.h \
    stopgamesessionplacementresponse_p.h \
    stopmatchmakingrequest.h \
    stopmatchmakingrequest_p.h \
    stopmatchmakingresponse.h \
    stopmatchmakingresponse_p.h \
    updatealiasrequest.h \
    updatealiasrequest_p.h \
    updatealiasresponse.h \
    updatealiasresponse_p.h \
    updatebuildrequest.h \
    updatebuildrequest_p.h \
    updatebuildresponse.h \
    updatebuildresponse_p.h \
    updatefleetattributesrequest.h \
    updatefleetattributesrequest_p.h \
    updatefleetattributesresponse.h \
    updatefleetattributesresponse_p.h \
    updatefleetcapacityrequest.h \
    updatefleetcapacityrequest_p.h \
    updatefleetcapacityresponse.h \
    updatefleetcapacityresponse_p.h \
    updatefleetportsettingsrequest.h \
    updatefleetportsettingsrequest_p.h \
    updatefleetportsettingsresponse.h \
    updatefleetportsettingsresponse_p.h \
    updategamesessionqueuerequest.h \
    updategamesessionqueuerequest_p.h \
    updategamesessionqueueresponse.h \
    updategamesessionqueueresponse_p.h \
    updategamesessionrequest.h \
    updategamesessionrequest_p.h \
    updategamesessionresponse.h \
    updategamesessionresponse_p.h \
    updatematchmakingconfigurationrequest.h \
    updatematchmakingconfigurationrequest_p.h \
    updatematchmakingconfigurationresponse.h \
    updatematchmakingconfigurationresponse_p.h \
    updateruntimeconfigurationrequest.h \
    updateruntimeconfigurationrequest_p.h \
    updateruntimeconfigurationresponse.h \
    updateruntimeconfigurationresponse_p.h \
    validatematchmakingrulesetrequest.h \
    validatematchmakingrulesetrequest_p.h \
    validatematchmakingrulesetresponse.h \
    validatematchmakingrulesetresponse_p.h \

SOURCES += \
    acceptmatchrequest.cpp \
    acceptmatchresponse.cpp \
    createaliasrequest.cpp \
    createaliasresponse.cpp \
    createbuildrequest.cpp \
    createbuildresponse.cpp \
    createfleetrequest.cpp \
    createfleetresponse.cpp \
    creategamesessionqueuerequest.cpp \
    creategamesessionqueueresponse.cpp \
    creategamesessionrequest.cpp \
    creategamesessionresponse.cpp \
    creatematchmakingconfigurationrequest.cpp \
    creatematchmakingconfigurationresponse.cpp \
    creatematchmakingrulesetrequest.cpp \
    creatematchmakingrulesetresponse.cpp \
    createplayersessionrequest.cpp \
    createplayersessionresponse.cpp \
    createplayersessionsrequest.cpp \
    createplayersessionsresponse.cpp \
    createvpcpeeringauthorizationrequest.cpp \
    createvpcpeeringauthorizationresponse.cpp \
    createvpcpeeringconnectionrequest.cpp \
    createvpcpeeringconnectionresponse.cpp \
    deletealiasrequest.cpp \
    deletealiasresponse.cpp \
    deletebuildrequest.cpp \
    deletebuildresponse.cpp \
    deletefleetrequest.cpp \
    deletefleetresponse.cpp \
    deletegamesessionqueuerequest.cpp \
    deletegamesessionqueueresponse.cpp \
    deletematchmakingconfigurationrequest.cpp \
    deletematchmakingconfigurationresponse.cpp \
    deletescalingpolicyrequest.cpp \
    deletescalingpolicyresponse.cpp \
    deletevpcpeeringauthorizationrequest.cpp \
    deletevpcpeeringauthorizationresponse.cpp \
    deletevpcpeeringconnectionrequest.cpp \
    deletevpcpeeringconnectionresponse.cpp \
    describealiasrequest.cpp \
    describealiasresponse.cpp \
    describebuildrequest.cpp \
    describebuildresponse.cpp \
    describeec2instancelimitsrequest.cpp \
    describeec2instancelimitsresponse.cpp \
    describefleetattributesrequest.cpp \
    describefleetattributesresponse.cpp \
    describefleetcapacityrequest.cpp \
    describefleetcapacityresponse.cpp \
    describefleeteventsrequest.cpp \
    describefleeteventsresponse.cpp \
    describefleetportsettingsrequest.cpp \
    describefleetportsettingsresponse.cpp \
    describefleetutilizationrequest.cpp \
    describefleetutilizationresponse.cpp \
    describegamesessiondetailsrequest.cpp \
    describegamesessiondetailsresponse.cpp \
    describegamesessionplacementrequest.cpp \
    describegamesessionplacementresponse.cpp \
    describegamesessionqueuesrequest.cpp \
    describegamesessionqueuesresponse.cpp \
    describegamesessionsrequest.cpp \
    describegamesessionsresponse.cpp \
    describeinstancesrequest.cpp \
    describeinstancesresponse.cpp \
    describematchmakingconfigurationsrequest.cpp \
    describematchmakingconfigurationsresponse.cpp \
    describematchmakingrequest.cpp \
    describematchmakingresponse.cpp \
    describematchmakingrulesetsrequest.cpp \
    describematchmakingrulesetsresponse.cpp \
    describeplayersessionsrequest.cpp \
    describeplayersessionsresponse.cpp \
    describeruntimeconfigurationrequest.cpp \
    describeruntimeconfigurationresponse.cpp \
    describescalingpoliciesrequest.cpp \
    describescalingpoliciesresponse.cpp \
    describevpcpeeringauthorizationsrequest.cpp \
    describevpcpeeringauthorizationsresponse.cpp \
    describevpcpeeringconnectionsrequest.cpp \
    describevpcpeeringconnectionsresponse.cpp \
    gameliftclient.cpp \
    gameliftrequest.cpp \
    gameliftresponse.cpp \
    getgamesessionlogurlrequest.cpp \
    getgamesessionlogurlresponse.cpp \
    getinstanceaccessrequest.cpp \
    getinstanceaccessresponse.cpp \
    listaliasesrequest.cpp \
    listaliasesresponse.cpp \
    listbuildsrequest.cpp \
    listbuildsresponse.cpp \
    listfleetsrequest.cpp \
    listfleetsresponse.cpp \
    putscalingpolicyrequest.cpp \
    putscalingpolicyresponse.cpp \
    requestuploadcredentialsrequest.cpp \
    requestuploadcredentialsresponse.cpp \
    resolvealiasrequest.cpp \
    resolvealiasresponse.cpp \
    searchgamesessionsrequest.cpp \
    searchgamesessionsresponse.cpp \
    startgamesessionplacementrequest.cpp \
    startgamesessionplacementresponse.cpp \
    startmatchbackfillrequest.cpp \
    startmatchbackfillresponse.cpp \
    startmatchmakingrequest.cpp \
    startmatchmakingresponse.cpp \
    stopgamesessionplacementrequest.cpp \
    stopgamesessionplacementresponse.cpp \
    stopmatchmakingrequest.cpp \
    stopmatchmakingresponse.cpp \
    updatealiasrequest.cpp \
    updatealiasresponse.cpp \
    updatebuildrequest.cpp \
    updatebuildresponse.cpp \
    updatefleetattributesrequest.cpp \
    updatefleetattributesresponse.cpp \
    updatefleetcapacityrequest.cpp \
    updatefleetcapacityresponse.cpp \
    updatefleetportsettingsrequest.cpp \
    updatefleetportsettingsresponse.cpp \
    updategamesessionqueuerequest.cpp \
    updategamesessionqueueresponse.cpp \
    updategamesessionrequest.cpp \
    updategamesessionresponse.cpp \
    updatematchmakingconfigurationrequest.cpp \
    updatematchmakingconfigurationresponse.cpp \
    updateruntimeconfigurationrequest.cpp \
    updateruntimeconfigurationresponse.cpp \
    validatematchmakingrulesetrequest.cpp \
    validatematchmakingrulesetresponse.cpp \

win32:CONFIG += skip_target_version_ext
