libqtaws: AWS::CodeBuild::CodeBuildClient Class Reference
AWS::CodeBuild::CodeBuildClient Class Reference
Client for AWS CodeBuild.
Public Slots
BatchDeleteBuildsResponse * batchDeleteBuilds (const BatchDeleteBuildsRequest &request)
BatchGetBuildsResponse * batchGetBuilds (const BatchGetBuildsRequest &request)
BatchGetProjectsResponse * batchGetProjects (const BatchGetProjectsRequest &request)
CreateProjectResponse * createProject (const CreateProjectRequest &request)
CreateWebhookResponse * createWebhook (const CreateWebhookRequest &request)
DeleteProjectResponse * deleteProject (const DeleteProjectRequest &request)
DeleteWebhookResponse * deleteWebhook (const DeleteWebhookRequest &request)
InvalidateProjectCacheResponse * invalidateProjectCache (const InvalidateProjectCacheRequest &request)
ListBuildsResponse * listBuilds (const ListBuildsRequest &request)
ListBuildsForProjectResponse * listBuildsForProject (const ListBuildsForProjectRequest &request)
ListCuratedEnvironmentImagesResponse * listCuratedEnvironmentImages (const ListCuratedEnvironmentImagesRequest &request)
ListProjectsResponse * listProjects (const ListProjectsRequest &request)
StartBuildResponse * startBuild (const StartBuildRequest &request)
StopBuildResponse * stopBuild (const StopBuildRequest &request)
UpdateProjectResponse * updateProject (const UpdateProjectRequest &request)
Public Member Functions
CodeBuildClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodeBuildClient object.
CodeBuildClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodeBuildClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS CodeBuild.
<fullname>AWS CodeBuild</fullname>
AWS CodeBuild is a fully managed build service in the cloud. AWS CodeBuild compiles your source code, runs unit tests, and produces artifacts that are ready to deploy. AWS CodeBuild eliminates the need to provision, manage, and scale your own build servers. It provides prepackaged build environments for the most popular programming languages and build tools, such as Apache Maven, Gradle, and more. You can also fully customize build environments in AWS CodeBuild to use your own build tools. AWS CodeBuild scales automatically to meet peak build requests, and you pay only for the build time you consume. For more information about AWS CodeBuild, see the AWS CodeBuild User
Guide>
AWS CodeBuild supports these
operations>
BatchDeleteBuilds: Deletes one or more
builds>
BatchGetProjects: Gets information about one or more build projects. A build project defines how AWS CodeBuild will run a build. This includes information such as where to get the source code to build, the build environment to use, the build commands to run, and where to store the build output. A build environment represents a combination of operating system, programming language runtime, and tools that AWS CodeBuild will use to run a build. Also, you can add tags to build projects to help manage your resources and
costs>
CreateProject: Creates a build
project>
CreateWebhook: For an existing AWS CodeBuild build project that has its source code stored in a GitHub repository, enables AWS CodeBuild to begin automatically rebuilding the source code every time a code change is pushed to the
repository>
DeleteProject: Deletes a build
project>
DeleteWebhook: For an existing AWS CodeBuild build project that has its source code stored in a GitHub repository, stops AWS CodeBuild from automatically rebuilding the source code every time a code change is pushed to the
repository>
ListProjects: Gets a list of build project names, with each build project name representing a single build
project>
UpdateProject: Changes the settings of an existing build
project>
BatchGetBuilds: Gets information about one or more
builds>
ListBuilds: Gets a list of build IDs, with each build ID representing a single
build>
ListBuildsForProject: Gets a list of build IDs for the specified build project, with each build ID representing a single
build>
StartBuild: Starts running a
build>
StopBuild: Attempts to stop running a
build>
ListCuratedEnvironmentImages: Gets information about Docker images that are managed by AWS
Definition at line 36 of file codebuildclient.h.
Constructor & Destructor Documentation
CodeBuildClient() [1/2]
AWS::CodeBuild::CodeBuildClient::CodeBuildClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodeBuildClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 122 of file codebuildclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new CodeBuildClientPrivate(this), parent)
 {
     Q_D(CodeBuildClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
CodeBuildClient() [2/2]
AWS::CodeBuild::CodeBuildClient::CodeBuildClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodeBuildClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 152 of file codebuildclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new CodeBuildClientPrivate(this), parent)
 {
     Q_D(CodeBuildClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
codebuild/codebuildclient.h
codebuild/codebuildclient.cpp