libqtaws: EcsClient Class Reference
EcsClient Class Reference
Client for Amazon EC2 Container Service (ECS)
Public Slots
EcsCreateClusterResponse * createCluster (const EcsCreateClusterRequest &request)
EcsCreateServiceResponse * createService (const EcsCreateServiceRequest &request)
EcsDeleteClusterResponse * deleteCluster (const EcsDeleteClusterRequest &request)
EcsDeleteServiceResponse * deleteService (const EcsDeleteServiceRequest &request)
EcsDeregisterContainerInstanceResponse * deregisterContainerInstance (const EcsDeregisterContainerInstanceRequest &request)
EcsDeregisterTaskDefinitionResponse * deregisterTaskDefinition (const EcsDeregisterTaskDefinitionRequest &request)
EcsDescribeClustersResponse * describeClusters (const EcsDescribeClustersRequest &request)
EcsDescribeContainerInstancesResponse * describeContainerInstances (const EcsDescribeContainerInstancesRequest &request)
EcsDescribeServicesResponse * describeServices (const EcsDescribeServicesRequest &request)
EcsDescribeTaskDefinitionResponse * describeTaskDefinition (const EcsDescribeTaskDefinitionRequest &request)
EcsDescribeTasksResponse * describeTasks (const EcsDescribeTasksRequest &request)
EcsDiscoverPollEndpointResponse * discoverPollEndpoint (const EcsDiscoverPollEndpointRequest &request)
EcsListClustersResponse * listClusters (const EcsListClustersRequest &request)
EcsListContainerInstancesResponse * listContainerInstances (const EcsListContainerInstancesRequest &request)
EcsListServicesResponse * listServices (const EcsListServicesRequest &request)
EcsListTaskDefinitionFamiliesResponse * listTaskDefinitionFamilies (const EcsListTaskDefinitionFamiliesRequest &request)
EcsListTaskDefinitionsResponse * listTaskDefinitions (const EcsListTaskDefinitionsRequest &request)
EcsListTasksResponse * listTasks (const EcsListTasksRequest &request)
EcsRegisterContainerInstanceResponse * registerContainerInstance (const EcsRegisterContainerInstanceRequest &request)
EcsRegisterTaskDefinitionResponse * registerTaskDefinition (const EcsRegisterTaskDefinitionRequest &request)
EcsRunTaskResponse * runTask (const EcsRunTaskRequest &request)
EcsStartTaskResponse * startTask (const EcsStartTaskRequest &request)
EcsStopTaskResponse * stopTask (const EcsStopTaskRequest &request)
EcsSubmitContainerStateChangeResponse * submitContainerStateChange (const EcsSubmitContainerStateChangeRequest &request)
EcsSubmitTaskStateChangeResponse * submitTaskStateChange (const EcsSubmitTaskStateChangeRequest &request)
EcsUpdateContainerAgentResponse * updateContainerAgent (const EcsUpdateContainerAgentRequest &request)
EcsUpdateServiceResponse * updateService (const EcsUpdateServiceRequest &request)
Public Member Functions
EcsClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new EcsClient object.
EcsClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new EcsClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon EC2 Container Service (ECS)
Amazon EC2 Container Service (Amazon ECS) is a highly scalable, fast, container management service that makes it easy to run, stop, and manage Docker containers on a cluster of EC2 instances. Amazon ECS lets you launch and stop container-enabled applications with simple API calls, allows you to get the state of your cluster from a centralized service, and gives you access to many familiar Amazon EC2 features like security groups, Amazon EBS volumes, and IAM roles.
You can use Amazon ECS to schedule the placement of containers across your cluster based on your resource needs, isolation policies, and availability requirements. Amazon EC2 Container Service eliminates the need for you to operate your own cluster management and configuration management systems or worry about scaling your management infrastructure.
Definition at line 33 of file ecsclient.h.
Constructor & Destructor Documentation
EcsClient::EcsClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new EcsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 48 of file ecsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new EcsClientPrivate(this), parent)
 {
     Q_D(EcsClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
EcsClient::EcsClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new EcsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 78 of file ecsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new EcsClientPrivate(this), parent)
 {
     Q_D(EcsClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
ecs/ecsclient.h
ecs/ecsclient.cpp