libqtaws: AWS::SSM::SsmClient Class Reference
AWS::SSM::SsmClient Class Reference
Client for Amazon Simple Systems Manager (SSM) (SSM)
Public Slots
AddTagsToResourceResponse * addTagsToResource (const AddTagsToResourceRequest &request)
CancelCommandResponse * cancelCommand (const CancelCommandRequest &request)
CreateActivationResponse * createActivation (const CreateActivationRequest &request)
CreateAssociationResponse * createAssociation (const CreateAssociationRequest &request)
CreateAssociationBatchResponse * createAssociationBatch (const CreateAssociationBatchRequest &request)
CreateDocumentResponse * createDocument (const CreateDocumentRequest &request)
CreateMaintenanceWindowResponse * createMaintenanceWindow (const CreateMaintenanceWindowRequest &request)
CreatePatchBaselineResponse * createPatchBaseline (const CreatePatchBaselineRequest &request)
CreateResourceDataSyncResponse * createResourceDataSync (const CreateResourceDataSyncRequest &request)
DeleteActivationResponse * deleteActivation (const DeleteActivationRequest &request)
DeleteAssociationResponse * deleteAssociation (const DeleteAssociationRequest &request)
DeleteDocumentResponse * deleteDocument (const DeleteDocumentRequest &request)
DeleteMaintenanceWindowResponse * deleteMaintenanceWindow (const DeleteMaintenanceWindowRequest &request)
DeleteParameterResponse * deleteParameter (const DeleteParameterRequest &request)
DeleteParametersResponse * deleteParameters (const DeleteParametersRequest &request)
DeletePatchBaselineResponse * deletePatchBaseline (const DeletePatchBaselineRequest &request)
DeleteResourceDataSyncResponse * deleteResourceDataSync (const DeleteResourceDataSyncRequest &request)
DeregisterManagedInstanceResponse * deregisterManagedInstance (const DeregisterManagedInstanceRequest &request)
DeregisterPatchBaselineForPatchGroupResponse * deregisterPatchBaselineForPatchGroup (const DeregisterPatchBaselineForPatchGroupRequest &request)
DeregisterTargetFromMaintenanceWindowResponse * deregisterTargetFromMaintenanceWindow (const DeregisterTargetFromMaintenanceWindowRequest &request)
DeregisterTaskFromMaintenanceWindowResponse * deregisterTaskFromMaintenanceWindow (const DeregisterTaskFromMaintenanceWindowRequest &request)
DescribeActivationsResponse * describeActivations (const DescribeActivationsRequest &request)
DescribeAssociationResponse * describeAssociation (const DescribeAssociationRequest &request)
DescribeAutomationExecutionsResponse * describeAutomationExecutions (const DescribeAutomationExecutionsRequest &request)
DescribeAutomationStepExecutionsResponse * describeAutomationStepExecutions (const DescribeAutomationStepExecutionsRequest &request)
DescribeAvailablePatchesResponse * describeAvailablePatches (const DescribeAvailablePatchesRequest &request)
DescribeDocumentResponse * describeDocument (const DescribeDocumentRequest &request)
DescribeDocumentPermissionResponse * describeDocumentPermission (const DescribeDocumentPermissionRequest &request)
DescribeEffectiveInstanceAssociationsResponse * describeEffectiveInstanceAssociations (const DescribeEffectiveInstanceAssociationsRequest &request)
DescribeEffectivePatchesForPatchBaselineResponse * describeEffectivePatchesForPatchBaseline (const DescribeEffectivePatchesForPatchBaselineRequest &request)
DescribeInstanceAssociationsStatusResponse * describeInstanceAssociationsStatus (const DescribeInstanceAssociationsStatusRequest &request)
DescribeInstanceInformationResponse * describeInstanceInformation (const DescribeInstanceInformationRequest &request)
DescribeInstancePatchStatesResponse * describeInstancePatchStates (const DescribeInstancePatchStatesRequest &request)
DescribeInstancePatchStatesForPatchGroupResponse * describeInstancePatchStatesForPatchGroup (const DescribeInstancePatchStatesForPatchGroupRequest &request)
DescribeInstancePatchesResponse * describeInstancePatches (const DescribeInstancePatchesRequest &request)
DescribeMaintenanceWindowExecutionTaskInvocationsResponse * describeMaintenanceWindowExecutionTaskInvocations (const DescribeMaintenanceWindowExecutionTaskInvocationsRequest &request)
DescribeMaintenanceWindowExecutionTasksResponse * describeMaintenanceWindowExecutionTasks (const DescribeMaintenanceWindowExecutionTasksRequest &request)
DescribeMaintenanceWindowExecutionsResponse * describeMaintenanceWindowExecutions (const DescribeMaintenanceWindowExecutionsRequest &request)
DescribeMaintenanceWindowTargetsResponse * describeMaintenanceWindowTargets (const DescribeMaintenanceWindowTargetsRequest &request)
DescribeMaintenanceWindowTasksResponse * describeMaintenanceWindowTasks (const DescribeMaintenanceWindowTasksRequest &request)
DescribeMaintenanceWindowsResponse * describeMaintenanceWindows (const DescribeMaintenanceWindowsRequest &request)
DescribeParametersResponse * describeParameters (const DescribeParametersRequest &request)
DescribePatchBaselinesResponse * describePatchBaselines (const DescribePatchBaselinesRequest &request)
DescribePatchGroupStateResponse * describePatchGroupState (const DescribePatchGroupStateRequest &request)
DescribePatchGroupsResponse * describePatchGroups (const DescribePatchGroupsRequest &request)
GetAutomationExecutionResponse * getAutomationExecution (const GetAutomationExecutionRequest &request)
GetCommandInvocationResponse * getCommandInvocation (const GetCommandInvocationRequest &request)
GetDefaultPatchBaselineResponse * getDefaultPatchBaseline (const GetDefaultPatchBaselineRequest &request)
GetDeployablePatchSnapshotForInstanceResponse * getDeployablePatchSnapshotForInstance (const GetDeployablePatchSnapshotForInstanceRequest &request)
GetDocumentResponse * getDocument (const GetDocumentRequest &request)
GetInventoryResponse * getInventory (const GetInventoryRequest &request)
GetInventorySchemaResponse * getInventorySchema (const GetInventorySchemaRequest &request)
GetMaintenanceWindowResponse * getMaintenanceWindow (const GetMaintenanceWindowRequest &request)
GetMaintenanceWindowExecutionResponse * getMaintenanceWindowExecution (const GetMaintenanceWindowExecutionRequest &request)
GetMaintenanceWindowExecutionTaskResponse * getMaintenanceWindowExecutionTask (const GetMaintenanceWindowExecutionTaskRequest &request)
GetMaintenanceWindowExecutionTaskInvocationResponse * getMaintenanceWindowExecutionTaskInvocation (const GetMaintenanceWindowExecutionTaskInvocationRequest &request)
GetMaintenanceWindowTaskResponse * getMaintenanceWindowTask (const GetMaintenanceWindowTaskRequest &request)
GetParameterResponse * getParameter (const GetParameterRequest &request)
GetParameterHistoryResponse * getParameterHistory (const GetParameterHistoryRequest &request)
GetParametersResponse * getParameters (const GetParametersRequest &request)
GetParametersByPathResponse * getParametersByPath (const GetParametersByPathRequest &request)
GetPatchBaselineResponse * getPatchBaseline (const GetPatchBaselineRequest &request)
GetPatchBaselineForPatchGroupResponse * getPatchBaselineForPatchGroup (const GetPatchBaselineForPatchGroupRequest &request)
ListAssociationVersionsResponse * listAssociationVersions (const ListAssociationVersionsRequest &request)
ListAssociationsResponse * listAssociations (const ListAssociationsRequest &request)
ListCommandInvocationsResponse * listCommandInvocations (const ListCommandInvocationsRequest &request)
ListCommandsResponse * listCommands (const ListCommandsRequest &request)
ListComplianceItemsResponse * listComplianceItems (const ListComplianceItemsRequest &request)
ListComplianceSummariesResponse * listComplianceSummaries (const ListComplianceSummariesRequest &request)
ListDocumentVersionsResponse * listDocumentVersions (const ListDocumentVersionsRequest &request)
ListDocumentsResponse * listDocuments (const ListDocumentsRequest &request)
ListInventoryEntriesResponse * listInventoryEntries (const ListInventoryEntriesRequest &request)
ListResourceComplianceSummariesResponse * listResourceComplianceSummaries (const ListResourceComplianceSummariesRequest &request)
ListResourceDataSyncResponse * listResourceDataSync (const ListResourceDataSyncRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
ModifyDocumentPermissionResponse * modifyDocumentPermission (const ModifyDocumentPermissionRequest &request)
PutComplianceItemsResponse * putComplianceItems (const PutComplianceItemsRequest &request)
PutInventoryResponse * putInventory (const PutInventoryRequest &request)
PutParameterResponse * putParameter (const PutParameterRequest &request)
RegisterDefaultPatchBaselineResponse * registerDefaultPatchBaseline (const RegisterDefaultPatchBaselineRequest &request)
RegisterPatchBaselineForPatchGroupResponse * registerPatchBaselineForPatchGroup (const RegisterPatchBaselineForPatchGroupRequest &request)
RegisterTargetWithMaintenanceWindowResponse * registerTargetWithMaintenanceWindow (const RegisterTargetWithMaintenanceWindowRequest &request)
RegisterTaskWithMaintenanceWindowResponse * registerTaskWithMaintenanceWindow (const RegisterTaskWithMaintenanceWindowRequest &request)
RemoveTagsFromResourceResponse * removeTagsFromResource (const RemoveTagsFromResourceRequest &request)
SendAutomationSignalResponse * sendAutomationSignal (const SendAutomationSignalRequest &request)
SendCommandResponse * sendCommand (const SendCommandRequest &request)
StartAutomationExecutionResponse * startAutomationExecution (const StartAutomationExecutionRequest &request)
StopAutomationExecutionResponse * stopAutomationExecution (const StopAutomationExecutionRequest &request)
UpdateAssociationResponse * updateAssociation (const UpdateAssociationRequest &request)
UpdateAssociationStatusResponse * updateAssociationStatus (const UpdateAssociationStatusRequest &request)
UpdateDocumentResponse * updateDocument (const UpdateDocumentRequest &request)
UpdateDocumentDefaultVersionResponse * updateDocumentDefaultVersion (const UpdateDocumentDefaultVersionRequest &request)
UpdateMaintenanceWindowResponse * updateMaintenanceWindow (const UpdateMaintenanceWindowRequest &request)
UpdateMaintenanceWindowTargetResponse * updateMaintenanceWindowTarget (const UpdateMaintenanceWindowTargetRequest &request)
UpdateMaintenanceWindowTaskResponse * updateMaintenanceWindowTask (const UpdateMaintenanceWindowTaskRequest &request)
UpdateManagedInstanceRoleResponse * updateManagedInstanceRole (const UpdateManagedInstanceRoleRequest &request)
UpdatePatchBaselineResponse * updatePatchBaseline (const UpdatePatchBaselineRequest &request)
Public Member Functions
SsmClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SsmClient object.
SsmClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SsmClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Simple Systems Manager (SSM) (SSM)
<fullname>AWS Systems Manager</fullname>
AWS Systems Manager is a collection of capabilities that helps you automate management tasks such as collecting system inventory, applying operating system (OS) patches, automating the creation of Amazon Machine Images (AMIs), and configuring operating systems (OSs) and applications at scale. Systems Manager lets you remotely and securely manage the configuration of your managed instances. A managed instance is any Amazon EC2 instance or on-premises machine in your hybrid environment that has been configured for Systems
Manager>
This reference is intended to be used with the AWS Systems Manager User Guide>
To get started, verify prerequisites and configure managed instances. For more information, see Systems Manager Prerequisites>
For information about other API actions you can perform on Amazon EC2 instances, see the Amazon EC2 API Reference. For information about how to use a Query API, see Making API Requests.
Definition at line 36 of file ssmclient.h.
Constructor & Destructor Documentation
SsmClient() [1/2]
AWS::SSM::SsmClient::SsmClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SsmClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 70 of file ssmclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new SsmClientPrivate(this), parent)
 {
     Q_D(SsmClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
SsmClient() [2/2]
AWS::SSM::SsmClient::SsmClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SsmClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 100 of file ssmclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new SsmClientPrivate(this), parent)
 {
     Q_D(SsmClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
ssm/ssmclient.h
ssm/ssmclient.cpp