libqtaws: AWS::AlexaForBusiness::AlexaForBusinessClient Class Reference
AWS::AlexaForBusiness::AlexaForBusinessClient Class Reference
Client for Alexa For Business.
Public Slots
AssociateDeviceWithRoomResponse * associateDeviceWithRoom (const AssociateDeviceWithRoomRequest &request)
AssociateSkillGroupWithRoomResponse * associateSkillGroupWithRoom (const AssociateSkillGroupWithRoomRequest &request)
CreateProfileResponse * createProfile (const CreateProfileRequest &request)
CreateRoomResponse * createRoom (const CreateRoomRequest &request)
CreateSkillGroupResponse * createSkillGroup (const CreateSkillGroupRequest &request)
CreateUserResponse * createUser (const CreateUserRequest &request)
DeleteProfileResponse * deleteProfile (const DeleteProfileRequest &request)
DeleteRoomResponse * deleteRoom (const DeleteRoomRequest &request)
DeleteRoomSkillParameterResponse * deleteRoomSkillParameter (const DeleteRoomSkillParameterRequest &request)
DeleteSkillGroupResponse * deleteSkillGroup (const DeleteSkillGroupRequest &request)
DeleteUserResponse * deleteUser (const DeleteUserRequest &request)
DisassociateDeviceFromRoomResponse * disassociateDeviceFromRoom (const DisassociateDeviceFromRoomRequest &request)
DisassociateSkillGroupFromRoomResponse * disassociateSkillGroupFromRoom (const DisassociateSkillGroupFromRoomRequest &request)
GetDeviceResponse * getDevice (const GetDeviceRequest &request)
GetProfileResponse * getProfile (const GetProfileRequest &request)
GetRoomResponse * getRoom (const GetRoomRequest &request)
GetRoomSkillParameterResponse * getRoomSkillParameter (const GetRoomSkillParameterRequest &request)
GetSkillGroupResponse * getSkillGroup (const GetSkillGroupRequest &request)
ListSkillsResponse * listSkills (const ListSkillsRequest &request)
ListTagsResponse * listTags (const ListTagsRequest &request)
PutRoomSkillParameterResponse * putRoomSkillParameter (const PutRoomSkillParameterRequest &request)
ResolveRoomResponse * resolveRoom (const ResolveRoomRequest &request)
RevokeInvitationResponse * revokeInvitation (const RevokeInvitationRequest &request)
SearchDevicesResponse * searchDevices (const SearchDevicesRequest &request)
SearchProfilesResponse * searchProfiles (const SearchProfilesRequest &request)
SearchRoomsResponse * searchRooms (const SearchRoomsRequest &request)
SearchSkillGroupsResponse * searchSkillGroups (const SearchSkillGroupsRequest &request)
SearchUsersResponse * searchUsers (const SearchUsersRequest &request)
SendInvitationResponse * sendInvitation (const SendInvitationRequest &request)
StartDeviceSyncResponse * startDeviceSync (const StartDeviceSyncRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateDeviceResponse * updateDevice (const UpdateDeviceRequest &request)
UpdateProfileResponse * updateProfile (const UpdateProfileRequest &request)
UpdateRoomResponse * updateRoom (const UpdateRoomRequest &request)
UpdateSkillGroupResponse * updateSkillGroup (const UpdateSkillGroupRequest &request)
Public Member Functions
AlexaForBusinessClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AlexaForBusinessClient object.
AlexaForBusinessClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AlexaForBusinessClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Alexa For Business.
Alexa for Business makes it easy for you to use Alexa in your organization. Alexa for Business gives you the tools you need to manage Alexa devices, enroll your users, and assign skills, at scale. You can build your own context-aware voice skills using the Alexa Skills Kit, and the Alexa for Business APIs, and you can make these available as private skills for your organization. Alexa for Business also makes it easy to voice-enable your products and services, providing context-aware voice experiences for your
Definition at line 36 of file alexaforbusinessclient.h.
Constructor & Destructor Documentation
AlexaForBusinessClient() [1/2]
AWS::AlexaForBusiness::AlexaForBusinessClient::AlexaForBusinessClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AlexaForBusinessClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 51 of file alexaforbusinessclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new AlexaForBusinessClientPrivate(this), parent)
 {
     Q_D(AlexaForBusinessClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
AlexaForBusinessClient() [2/2]
AWS::AlexaForBusiness::AlexaForBusinessClient::AlexaForBusinessClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AlexaForBusinessClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 81 of file alexaforbusinessclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new AlexaForBusinessClientPrivate(this), parent)
 {
     Q_D(AlexaForBusinessClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
alexaforbusiness/alexaforbusinessclient.h
alexaforbusiness/alexaforbusinessclient.cpp