libqtaws: CloudFormationClient Class Reference
CloudFormationClient Class Reference
Client for AWS CloudFormation.
Public Slots
CloudFormationCancelUpdateStackResponse * cancelUpdateStack (const CloudFormationCancelUpdateStackRequest &request)
CloudFormationContinueUpdateRollbackResponse * continueUpdateRollback (const CloudFormationContinueUpdateRollbackRequest &request)
CloudFormationCreateChangeSetResponse * createChangeSet (const CloudFormationCreateChangeSetRequest &request)
CloudFormationCreateStackResponse * createStack (const CloudFormationCreateStackRequest &request)
CloudFormationDeleteChangeSetResponse * deleteChangeSet (const CloudFormationDeleteChangeSetRequest &request)
CloudFormationDeleteStackResponse * deleteStack (const CloudFormationDeleteStackRequest &request)
CloudFormationDescribeAccountLimitsResponse * describeAccountLimits (const CloudFormationDescribeAccountLimitsRequest &request)
CloudFormationDescribeChangeSetResponse * describeChangeSet (const CloudFormationDescribeChangeSetRequest &request)
CloudFormationDescribeStackEventsResponse * describeStackEvents (const CloudFormationDescribeStackEventsRequest &request)
CloudFormationDescribeStackResourceResponse * describeStackResource (const CloudFormationDescribeStackResourceRequest &request)
CloudFormationDescribeStackResourcesResponse * describeStackResources (const CloudFormationDescribeStackResourcesRequest &request)
CloudFormationDescribeStacksResponse * describeStacks (const CloudFormationDescribeStacksRequest &request)
CloudFormationEstimateTemplateCostResponse * estimateTemplateCost (const CloudFormationEstimateTemplateCostRequest &request)
CloudFormationExecuteChangeSetResponse * executeChangeSet (const CloudFormationExecuteChangeSetRequest &request)
CloudFormationGetStackPolicyResponse * getStackPolicy (const CloudFormationGetStackPolicyRequest &request)
CloudFormationGetTemplateResponse * getTemplate (const CloudFormationGetTemplateRequest &request)
CloudFormationGetTemplateSummaryResponse * getTemplateSummary (const CloudFormationGetTemplateSummaryRequest &request)
CloudFormationListChangeSetsResponse * listChangeSets (const CloudFormationListChangeSetsRequest &request)
CloudFormationListStackResourcesResponse * listStackResources (const CloudFormationListStackResourcesRequest &request)
CloudFormationListStacksResponse * listStacks (const CloudFormationListStacksRequest &request)
CloudFormationSetStackPolicyResponse * setStackPolicy (const CloudFormationSetStackPolicyRequest &request)
CloudFormationSignalResourceResponse * signalResource (const CloudFormationSignalResourceRequest &request)
CloudFormationUpdateStackResponse * updateStack (const CloudFormationUpdateStackRequest &request)
CloudFormationValidateTemplateResponse * validateTemplate (const CloudFormationValidateTemplateRequest &request)
Public Member Functions
CloudFormationClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudFormationClient object.
CloudFormationClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudFormationClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS CloudFormation.
<fullname>AWS CloudFormation</fullname>
AWS CloudFormation enables you to create and manage AWS infrastructure deployments predictably and repeatedly. AWS CloudFormation helps you leverage AWS products such as Amazon EC2, EBS, Amazon SNS, ELB, and Auto Scaling to build highly-reliable, highly scalable, cost effective applications without worrying about creating and configuring the underlying AWS infrastructure.
With AWS CloudFormation, you declare all of your resources and dependencies in a template file. The template defines a collection of resources as a single unit called a stack. AWS CloudFormation creates and deletes all member resources of the stack together and manages all dependencies between the resources for you.
For more information about this product, go to the CloudFormation Product Page.
Amazon CloudFormation makes use of other AWS products. If you need additional technical information about a specific AWS product, you can find the product's technical documentation at http://docs.aws.amazon.com/.
Definition at line 33 of file cloudformationclient.h.
Constructor & Destructor Documentation
CloudFormationClient::CloudFormationClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudFormationClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 54 of file cloudformationclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new CloudFormationClientPrivate(this), parent)
 {
     Q_D(CloudFormationClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
CloudFormationClient::CloudFormationClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudFormationClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 84 of file cloudformationclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new CloudFormationClientPrivate(this), parent)
 {
     Q_D(CloudFormationClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
cloudformation/cloudformationclient.h
cloudformation/cloudformationclient.cpp