libqtaws: AWS::OpsWorksCM::OpsWorksCMClient Class Reference
AWS::OpsWorksCM::OpsWorksCMClient Class Reference
Client for AWS OpsWorks for Chef Automate (OpsWorksCM)
Public Slots
AssociateNodeResponse * associateNode (const AssociateNodeRequest &request)
CreateBackupResponse * createBackup (const CreateBackupRequest &request)
CreateServerResponse * createServer (const CreateServerRequest &request)
DeleteBackupResponse * deleteBackup (const DeleteBackupRequest &request)
DeleteServerResponse * deleteServer (const DeleteServerRequest &request)
DescribeAccountAttributesResponse * describeAccountAttributes (const DescribeAccountAttributesRequest &request)
DescribeBackupsResponse * describeBackups (const DescribeBackupsRequest &request)
DescribeEventsResponse * describeEvents (const DescribeEventsRequest &request)
DescribeNodeAssociationStatusResponse * describeNodeAssociationStatus (const DescribeNodeAssociationStatusRequest &request)
DescribeServersResponse * describeServers (const DescribeServersRequest &request)
DisassociateNodeResponse * disassociateNode (const DisassociateNodeRequest &request)
RestoreServerResponse * restoreServer (const RestoreServerRequest &request)
StartMaintenanceResponse * startMaintenance (const StartMaintenanceRequest &request)
UpdateServerResponse * updateServer (const UpdateServerRequest &request)
UpdateServerEngineAttributesResponse * updateServerEngineAttributes (const UpdateServerEngineAttributesRequest &request)
Public Member Functions
OpsWorksCMClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new OpsWorksCMClient object.
OpsWorksCMClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new OpsWorksCMClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS OpsWorks for Chef Automate (OpsWorksCM)
<fullname>AWS OpsWorks CM</fullname>
AWS OpsWorks for configuration management (CM) is a service that runs and manages configuration management servers.
</p
Glossary of terms
</p
Server: A configuration management server that can be highly-available. The configuration management server runs on an Amazon Elastic Compute Cloud (EC2) instance, and may use various other AWS services, such as Amazon Relational Database Service (RDS) and Elastic Load Balancing. A server is a generic abstraction over the configuration manager that you want to use, much like Amazon RDS. In AWS OpsWorks CM, you do not start or stop servers. After you create servers, they continue to run until they are
deleted>
Engine: The engine is the specific configuration manager that you want to use. Valid values in this release include Chef and
Puppet>
Backup: This is an application-level backup of the data that the configuration manager stores. AWS OpsWorks CM creates an S3 bucket for backups when you launch the first server. A backup maintains a snapshot of a server's configuration-related attributes at the time the backup
starts>
Events: Events are always related to a server. Events are written during server creation, when health checks run, when backups are created, when system maintenance is performed, etc. When you delete a server, the server's events are also
deleted>
Account attributes: Every account has attributes that are assigned in the AWS OpsWorks CM database. These attributes store information about configuration limits (servers, backups, etc.) and your customer account.
</p
Endpoints
</p
AWS OpsWorks CM supports the following endpoints, all HTTPS. You must connect to one of the following endpoints. Your servers can only be accessed or managed within the endpoint in which they are
created>
opsworks-cm.us-east-1.amazonaws.co>
opsworks-cm.us-west-2.amazonaws.co>
opsworks-cm.eu-west-1.amazonaws.co>
Throttling limits
</p
All API operations allow for five requests per second with a burst of 10 requests per
Definition at line 36 of file opsworkscmclient.h.
Constructor & Destructor Documentation
OpsWorksCMClient() [1/2]
AWS::OpsWorksCM::OpsWorksCMClient::OpsWorksCMClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new OpsWorksCMClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 106 of file opsworkscmclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new OpsWorksCMClientPrivate(this), parent)
 {
     Q_D(OpsWorksCMClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
OpsWorksCMClient() [2/2]
AWS::OpsWorksCM::OpsWorksCMClient::OpsWorksCMClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new OpsWorksCMClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 136 of file opsworkscmclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new OpsWorksCMClientPrivate(this), parent)
 {
     Q_D(OpsWorksCMClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
opsworkscm/opsworkscmclient.h
opsworkscm/opsworkscmclient.cpp