libqtaws: RdsClient Class Reference
RdsClient Class Reference
Client for Amazon Relational Database Service (RDS)
Public Slots
RdsAddSourceIdentifierToSubscriptionResponse * addSourceIdentifierToSubscription (const RdsAddSourceIdentifierToSubscriptionRequest &request)
RdsAddTagsToResourceResponse * addTagsToResource (const RdsAddTagsToResourceRequest &request)
RdsApplyPendingMaintenanceActionResponse * applyPendingMaintenanceAction (const RdsApplyPendingMaintenanceActionRequest &request)
RdsAuthorizeDBSecurityGroupIngressResponse * authorizeDBSecurityGroupIngress (const RdsAuthorizeDBSecurityGroupIngressRequest &request)
RdsCopyDBClusterParameterGroupResponse * copyDBClusterParameterGroup (const RdsCopyDBClusterParameterGroupRequest &request)
RdsCopyDBClusterSnapshotResponse * copyDBClusterSnapshot (const RdsCopyDBClusterSnapshotRequest &request)
RdsCopyDBParameterGroupResponse * copyDBParameterGroup (const RdsCopyDBParameterGroupRequest &request)
RdsCopyDBSnapshotResponse * copyDBSnapshot (const RdsCopyDBSnapshotRequest &request)
RdsCopyOptionGroupResponse * copyOptionGroup (const RdsCopyOptionGroupRequest &request)
RdsCreateDBClusterResponse * createDBCluster (const RdsCreateDBClusterRequest &request)
RdsCreateDBClusterParameterGroupResponse * createDBClusterParameterGroup (const RdsCreateDBClusterParameterGroupRequest &request)
RdsCreateDBClusterSnapshotResponse * createDBClusterSnapshot (const RdsCreateDBClusterSnapshotRequest &request)
RdsCreateDBInstanceResponse * createDBInstance (const RdsCreateDBInstanceRequest &request)
RdsCreateDBInstanceReadReplicaResponse * createDBInstanceReadReplica (const RdsCreateDBInstanceReadReplicaRequest &request)
RdsCreateDBParameterGroupResponse * createDBParameterGroup (const RdsCreateDBParameterGroupRequest &request)
RdsCreateDBSecurityGroupResponse * createDBSecurityGroup (const RdsCreateDBSecurityGroupRequest &request)
RdsCreateDBSnapshotResponse * createDBSnapshot (const RdsCreateDBSnapshotRequest &request)
RdsCreateDBSubnetGroupResponse * createDBSubnetGroup (const RdsCreateDBSubnetGroupRequest &request)
RdsCreateEventSubscriptionResponse * createEventSubscription (const RdsCreateEventSubscriptionRequest &request)
RdsCreateOptionGroupResponse * createOptionGroup (const RdsCreateOptionGroupRequest &request)
RdsDeleteDBClusterResponse * deleteDBCluster (const RdsDeleteDBClusterRequest &request)
RdsDeleteDBClusterParameterGroupResponse * deleteDBClusterParameterGroup (const RdsDeleteDBClusterParameterGroupRequest &request)
RdsDeleteDBClusterSnapshotResponse * deleteDBClusterSnapshot (const RdsDeleteDBClusterSnapshotRequest &request)
RdsDeleteDBInstanceResponse * deleteDBInstance (const RdsDeleteDBInstanceRequest &request)
RdsDeleteDBParameterGroupResponse * deleteDBParameterGroup (const RdsDeleteDBParameterGroupRequest &request)
RdsDeleteDBSecurityGroupResponse * deleteDBSecurityGroup (const RdsDeleteDBSecurityGroupRequest &request)
RdsDeleteDBSnapshotResponse * deleteDBSnapshot (const RdsDeleteDBSnapshotRequest &request)
RdsDeleteDBSubnetGroupResponse * deleteDBSubnetGroup (const RdsDeleteDBSubnetGroupRequest &request)
RdsDeleteEventSubscriptionResponse * deleteEventSubscription (const RdsDeleteEventSubscriptionRequest &request)
RdsDeleteOptionGroupResponse * deleteOptionGroup (const RdsDeleteOptionGroupRequest &request)
RdsDescribeAccountAttributesResponse * describeAccountAttributes (const RdsDescribeAccountAttributesRequest &request)
RdsDescribeCertificatesResponse * describeCertificates (const RdsDescribeCertificatesRequest &request)
RdsDescribeDBClusterParameterGroupsResponse * describeDBClusterParameterGroups (const RdsDescribeDBClusterParameterGroupsRequest &request)
RdsDescribeDBClusterParametersResponse * describeDBClusterParameters (const RdsDescribeDBClusterParametersRequest &request)
RdsDescribeDBClusterSnapshotAttributesResponse * describeDBClusterSnapshotAttributes (const RdsDescribeDBClusterSnapshotAttributesRequest &request)
RdsDescribeDBClusterSnapshotsResponse * describeDBClusterSnapshots (const RdsDescribeDBClusterSnapshotsRequest &request)
RdsDescribeDBClustersResponse * describeDBClusters (const RdsDescribeDBClustersRequest &request)
RdsDescribeDBEngineVersionsResponse * describeDBEngineVersions (const RdsDescribeDBEngineVersionsRequest &request)
RdsDescribeDBInstancesResponse * describeDBInstances (const RdsDescribeDBInstancesRequest &request)
RdsDescribeDBLogFilesResponse * describeDBLogFiles (const RdsDescribeDBLogFilesRequest &request)
RdsDescribeDBParameterGroupsResponse * describeDBParameterGroups (const RdsDescribeDBParameterGroupsRequest &request)
RdsDescribeDBParametersResponse * describeDBParameters (const RdsDescribeDBParametersRequest &request)
RdsDescribeDBSecurityGroupsResponse * describeDBSecurityGroups (const RdsDescribeDBSecurityGroupsRequest &request)
RdsDescribeDBSnapshotAttributesResponse * describeDBSnapshotAttributes (const RdsDescribeDBSnapshotAttributesRequest &request)
RdsDescribeDBSnapshotsResponse * describeDBSnapshots (const RdsDescribeDBSnapshotsRequest &request)
RdsDescribeDBSubnetGroupsResponse * describeDBSubnetGroups (const RdsDescribeDBSubnetGroupsRequest &request)
RdsDescribeEngineDefaultClusterParametersResponse * describeEngineDefaultClusterParameters (const RdsDescribeEngineDefaultClusterParametersRequest &request)
RdsDescribeEngineDefaultParametersResponse * describeEngineDefaultParameters (const RdsDescribeEngineDefaultParametersRequest &request)
RdsDescribeEventCategoriesResponse * describeEventCategories (const RdsDescribeEventCategoriesRequest &request)
RdsDescribeEventSubscriptionsResponse * describeEventSubscriptions (const RdsDescribeEventSubscriptionsRequest &request)
RdsDescribeEventsResponse * describeEvents (const RdsDescribeEventsRequest &request)
RdsDescribeOptionGroupOptionsResponse * describeOptionGroupOptions (const RdsDescribeOptionGroupOptionsRequest &request)
RdsDescribeOptionGroupsResponse * describeOptionGroups (const RdsDescribeOptionGroupsRequest &request)
RdsDescribeOrderableDBInstanceOptionsResponse * describeOrderableDBInstanceOptions (const RdsDescribeOrderableDBInstanceOptionsRequest &request)
RdsDescribePendingMaintenanceActionsResponse * describePendingMaintenanceActions (const RdsDescribePendingMaintenanceActionsRequest &request)
RdsDescribeReservedDBInstancesResponse * describeReservedDBInstances (const RdsDescribeReservedDBInstancesRequest &request)
RdsDescribeReservedDBInstancesOfferingsResponse * describeReservedDBInstancesOfferings (const RdsDescribeReservedDBInstancesOfferingsRequest &request)
RdsDescribeSourceRegionsResponse * describeSourceRegions (const RdsDescribeSourceRegionsRequest &request)
RdsDownloadDBLogFilePortionResponse * downloadDBLogFilePortion (const RdsDownloadDBLogFilePortionRequest &request)
RdsFailoverDBClusterResponse * failoverDBCluster (const RdsFailoverDBClusterRequest &request)
RdsListTagsForResourceResponse * listTagsForResource (const RdsListTagsForResourceRequest &request)
RdsModifyDBClusterResponse * modifyDBCluster (const RdsModifyDBClusterRequest &request)
RdsModifyDBClusterParameterGroupResponse * modifyDBClusterParameterGroup (const RdsModifyDBClusterParameterGroupRequest &request)
RdsModifyDBClusterSnapshotAttributeResponse * modifyDBClusterSnapshotAttribute (const RdsModifyDBClusterSnapshotAttributeRequest &request)
RdsModifyDBInstanceResponse * modifyDBInstance (const RdsModifyDBInstanceRequest &request)
RdsModifyDBParameterGroupResponse * modifyDBParameterGroup (const RdsModifyDBParameterGroupRequest &request)
RdsModifyDBSnapshotAttributeResponse * modifyDBSnapshotAttribute (const RdsModifyDBSnapshotAttributeRequest &request)
RdsModifyDBSubnetGroupResponse * modifyDBSubnetGroup (const RdsModifyDBSubnetGroupRequest &request)
RdsModifyEventSubscriptionResponse * modifyEventSubscription (const RdsModifyEventSubscriptionRequest &request)
RdsModifyOptionGroupResponse * modifyOptionGroup (const RdsModifyOptionGroupRequest &request)
RdsPromoteReadReplicaResponse * promoteReadReplica (const RdsPromoteReadReplicaRequest &request)
RdsPromoteReadReplicaDBClusterResponse * promoteReadReplicaDBCluster (const RdsPromoteReadReplicaDBClusterRequest &request)
RdsPurchaseReservedDBInstancesOfferingResponse * purchaseReservedDBInstancesOffering (const RdsPurchaseReservedDBInstancesOfferingRequest &request)
RdsRebootDBInstanceResponse * rebootDBInstance (const RdsRebootDBInstanceRequest &request)
RdsRemoveSourceIdentifierFromSubscriptionResponse * removeSourceIdentifierFromSubscription (const RdsRemoveSourceIdentifierFromSubscriptionRequest &request)
RdsRemoveTagsFromResourceResponse * removeTagsFromResource (const RdsRemoveTagsFromResourceRequest &request)
RdsResetDBClusterParameterGroupResponse * resetDBClusterParameterGroup (const RdsResetDBClusterParameterGroupRequest &request)
RdsResetDBParameterGroupResponse * resetDBParameterGroup (const RdsResetDBParameterGroupRequest &request)
RdsRestoreDBClusterFromS3Response * restoreDBClusterFromS3 (const RdsRestoreDBClusterFromS3Request &request)
RdsRestoreDBClusterFromSnapshotResponse * restoreDBClusterFromSnapshot (const RdsRestoreDBClusterFromSnapshotRequest &request)
RdsRestoreDBClusterToPointInTimeResponse * restoreDBClusterToPointInTime (const RdsRestoreDBClusterToPointInTimeRequest &request)
RdsRestoreDBInstanceFromDBSnapshotResponse * restoreDBInstanceFromDBSnapshot (const RdsRestoreDBInstanceFromDBSnapshotRequest &request)
RdsRestoreDBInstanceToPointInTimeResponse * restoreDBInstanceToPointInTime (const RdsRestoreDBInstanceToPointInTimeRequest &request)
RdsRevokeDBSecurityGroupIngressResponse * revokeDBSecurityGroupIngress (const RdsRevokeDBSecurityGroupIngressRequest &request)
Public Member Functions
RdsClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new RdsClient object.
RdsClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new RdsClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Relational Database Service (RDS)
<fullname>Amazon Relational Database Service</fullname>
Amazon Relational Database Service (Amazon RDS) is a web service that makes it easier to set up, operate, and scale a relational database in the cloud. It provides cost-efficient, resizeable capacity for an industry-standard relational database and manages common database administration tasks, freeing up developers to focus on what makes their applications and businesses unique.
Amazon RDS gives you access to the capabilities of a MySQL, MariaDB, PostgreSQL, Microsoft SQL Server, Oracle, or Amazon Aurora database server. These capabilities mean that the code, applications, and tools you already use today with your existing databases work with Amazon RDS without modification. Amazon RDS automatically backs up your database and maintains the database software that powers your DB instance. Amazon RDS is flexible: you can scale your database instance's compute resources and storage capacity to meet your application's demand. As with all Amazon Web Services, there are no up-front investments, and you pay only for the resources you use.
This interface reference for Amazon RDS contains documentation for a programming or command line interface you can use to manage Amazon RDS. Note that Amazon RDS is asynchronous, which means that some interfaces might require techniques such as polling or callback functions to determine when a command has been applied. In this reference, the parameter descriptions indicate whether a command is applied immediately, on the next instance reboot, or during the maintenance window. The reference structure is as follows, and we list following some related topics from the user guide.
Amazon RDS API Reference
For the alphabetical list of API actions, see API Actions.
For the alphabetical list of data types, see Data Types.
For a list of common query parameters, see Common Parameters.
For descriptions of the error codes, see Common Errors.
Amazon RDS User Guide
For a summary of the Amazon RDS interfaces, see Available RDS Interfaces.
For more information about how to use the Query API, see Using the Query API.
Definition at line 33 of file rdsclient.h.
Constructor & Destructor Documentation
RdsClient::RdsClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new RdsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 84 of file rdsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new RdsClientPrivate(this), parent)
 {
     Q_D(RdsClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
RdsClient::RdsClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new RdsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 114 of file rdsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new RdsClientPrivate(this), parent)
 {
     Q_D(RdsClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
rds/rdsclient.h
rds/rdsclient.cpp