libqtaws: SqsChangeMessageVisibilityBatchResponse Class Reference
SqsChangeMessageVisibilityBatchResponse Class Reference
Handles SQS ChangeMessageVisibilityBatch responses.
Public Member Functions
SqsChangeMessageVisibilityBatchResponse (const SqsChangeMessageVisibilityBatchRequest &request, QNetworkReply *const reply, QObject *const parent=0)
Constructs a new SqsResponse object.
virtual bool isValid () const
Is this AWS response valid?
virtual const SqsChangeMessageVisibilityBatchRequest * request () const
Get this response's originating AWS request.
Public Member Functions inherited from SqsResponse
SqsResponse (QObject *const parent=0)
Constructs a new SqsResponse object.
virtual QString errorString () const
Get this response's error string.
virtual bool hasError () const
Did any error occurr processing this reponse?
QString requestId () const
Get the SQS request ID, if any, included in the SQS response.
SqsErrorList serviceErrors () const
Get list of SQS errors, if any, included in the SQS response.
Public Member Functions inherited from AwsAbstractResponse
AwsAbstractResponse (QObject *const parent=0)
Constructs a new AwsAbstractResponse object.
virtual ~AwsAbstractResponse ()
AwsAbstractResponse destructor.
virtual QNetworkReply::NetworkError networkError () const
Get this response's network error, if there is one.
virtual QXmlStreamReader::Error xmlParseError () const
Get this response's XML parse error, if there is one.
virtual QString xmlParseErrorString () const
Get this response's XML parse error string, if there is one.
Protected Slots
virtual void parseSuccess (QIODevice &response)
Parse an SQS ChangeMessageVisibilityBatch response.
Protected Slots inherited from SqsResponse
virtual void parseFailure (QIODevice &response)
Parse a failure response.
Protected Slots inherited from AwsAbstractResponse
virtual void replyFinished ()
Slot to be invoked when the internal network reply is finished.
Friends
class TestSqsChangeMessageVisibilityBatchResponse
Additional Inherited Members
Signals inherited from AwsAbstractResponse
void finished ()
Signal emitted when this object has finished parsing the response.
Static Public Member Functions inherited from AwsAbstractResponse
static QVariantMap toVariant (QXmlStreamReader &xml, const QString &prefix=QLatin1String("."), const int maxDepth=1024)
Convert an XML stream to a hierarchical QVariantMap.
Protected Member Functions inherited from SqsResponse
SqsResponse (SqsResponsePrivate *const d, QObject *const parent)
Constructs a new SqsResponse object.
Protected Member Functions inherited from AwsAbstractResponse
AwsAbstractResponse (AwsAbstractResponsePrivate *const d, QObject *const parent)
Constructs a new AwsAbstractResponse object.
virtual bool isSuccess (QNetworkReply *const reply) const
Does a network reply indicate a successful response?
void setReply (QNetworkReply *reply)
Set the network reply from which to expect an AWS response.
void setRequest (const AwsAbstractRequest *const request)
Set this response's originating AWS request.
void setXmlError (const QXmlStreamReader &xml)
Record the details of an XML parse error.
virtual void parse (QNetworkReply *const reply)
Parse an AWS response from a network reply.
virtual void parseFailure (QIODevice &response)=0
Parse a failure response.
virtual void parseSuccess (QIODevice &response)=0
Parse a successful response.
Protected Attributes inherited from AwsAbstractResponse
AwsAbstractResponsePrivate *const d_ptr
Internal d-pointer.
Detailed Description
Handles SQS ChangeMessageVisibilityBatch responses.
See also
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ChangeMessageVisibilityBatch.html
Definition at line 30 of file sqschangemessagevisibilitybatchresponse.h.
Constructor & Destructor Documentation
SqsChangeMessageVisibilityBatchResponse()
SqsChangeMessageVisibilityBatchResponse::SqsChangeMessageVisibilityBatchResponse (const SqsChangeMessageVisibilityBatchRequest & request, QNetworkReply *const reply, QObject *const parent = 0)
Constructs a new SqsResponse object.
Parameters
request Original AWS request.
reply AWS network response to observe.
parent This object's parent.
Definition at line 44 of file sqschangemessagevisibilitybatchresponse.cpp.
References AwsAbstractResponse::setReply(), and AwsAbstractResponse::setRequest().
     : SqsResponse(new SqsChangeMessageVisibilityBatchResponsePrivate(this), parent)
 {
     setRequest(new SqsChangeMessageVisibilityBatchRequest(request));
     setReply(reply);
 }
Member Function Documentation
isValid()
bool SqsChangeMessageVisibilityBatchResponse::isValid () const virtual
Is this AWS response valid?
This base implementation simply checks for the absense of network and XML parsing errors. Derived classes may override this function to check other error types, and/or apply additional validation rules.
Returns
true if this response is considered valid, false otherwise.
Note
This function may be equivalent to !hasError, however, it is not safe for this function's implementation to be just that, since derived classes may assume the inverse, resulting in an infinite cycle between the two functions.
See also
hasError
Todo:
Reimplemented from SqsResponse.
Definition at line 53 of file sqschangemessagevisibilitybatchresponse.cpp.
References SqsResponse::isValid().
 {
     //Q_D(const SqsChangeMessageVisibilityBatchResponse);
     /// @todo
     return ((false) && (SqsResponse::isValid()));
 }
parseSuccess
void SqsChangeMessageVisibilityBatchResponse::parseSuccess (QIODevice & response) protected virtual slot
Parse an SQS ChangeMessageVisibilityBatch response.
This implementation parses SQS ChangeMessageVisibilityBatchResponse elements, as defined by http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
For example:
<ChangeMessageVisibilityBatchResponse>
  <ResponseMetadata>
    <RequestId>7a62c49f-347e-4fc4-9331-6e8e7a96aa73</RequestId>
  </ResponseMetadata>
</ChangeMessageVisibilityBatchResponse>
Parameters
response Response to parse.
See also
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Todo:
Definition at line 86 of file sqschangemessagevisibilitybatchresponse.cpp.
 {
     Q_D(SqsChangeMessageVisibilityBatchResponse);
     QXmlStreamReader xml(&response);
     while (xml.readNextStartElement()) {
         /// @todo
         if (xml.name() == QLatin1String("ChangeMessageVisibilityBatchResponse")) {
             d->parseChangeMessageVisibilityBatchResponse(xml);
         } else {
             qWarning() << "ignoring" << xml.name();
             xml.skipCurrentElement();
         }
     }
 }
request()
const SqsChangeMessageVisibilityBatchRequest * SqsChangeMessageVisibilityBatchResponse::request () const virtual
Get this response's originating AWS request.
Returns
This response's originating AWS request.
Implements AwsAbstractResponse.
Definition at line 60 of file sqschangemessagevisibilitybatchresponse.cpp.
 {
     Q_D(const SqsChangeMessageVisibilityBatchResponse);
     return static_cast<const SqsChangeMessageVisibilityBatchRequest *>(d->request);
 }
The documentation for this class was generated from the following files:
sqs/sqschangemessagevisibilitybatchresponse.h
sqs/sqschangemessagevisibilitybatchresponse.cpp