libqtaws: SqsCreateQueueRequest Class Reference
SqsCreateQueueRequest Class Reference
Implements SQS CreateQueue requests.
Public Member Functions
SqsCreateQueueRequest (const QString &queueName)
Constructs a new SqsCreateQueueRequest object.
SqsCreateQueueRequest (const SqsCreateQueueRequest &other)
Constructs a new SqsCreateQueueRequest object by copying another.
SqsCreateQueueRequest ()
Constructs an invalid SqsCreateQueueRequest object.
virtual bool isValid () const
Is this request valid?
QVariant attribute (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of an attribute to be set on the created queue.
QVariantMap attributes () const
Get a map of all attributes set to be included with this request.
int delaySeconds () const
Get the value of DelaySeconds queue attribute.
int maximumMessageSize () const
Get the value of MaximumMessageSize queue attribute.
int messageRetentionPeriod () const
Get the value of MessageRetentionPeriod queue attribute.
QString policy () const
Get the value of Policy queue attribute.
QString queueName () const
Get the name of the queue to be created.
int receiveMessageWaitTimeSeconds () const
Get the value of the ReceiveMessageWaitTimeoutSeconds queue attribute.
int visibilityTimeout () const
Get the value of the VisibilityTimeout queue attribute.
void setAttribute (const QString &name, const QVariant &value)
Set the value of an attribute to be include in the create queue request.
void setAttributes (const QVariantMap &attributes)
Set the attributes to be included in the create queue request.
void setDelaySeconds (int delay)
Set the value of DelaySeconds queue attribute.
void setMaximumMessageSize (int size)
Set the value of MaximumMessageSize queue attribute.
void setMessageRetentionPeriod (int period)
Set the value of MessageRetentionPeriod queue attribute.
void setPolicy (const QString &policy)
Set the value of Policy queue attribute.
void setQueueName (const QString &queueName)
Set the name of the queue to be created.
void setReceiveMessageWaitTimeSeconds (int time)
Set the value of ReceiveMessageWaitTimeoutSeconds queue attribute.
void setVisibilityTimeout (int timeout)
Set the value of VisibilityTimeout queue attribute.
Public Member Functions inherited from SqsRequest
SqsRequest (const Action action)
Constructs a new SqsRequest object.
SqsRequest (const SqsRequest &other)
Constructs a new SqsRequest object by copying another.
SqsRequest & operator= (const SqsRequest &other)
Assignment operator.
Action action () const
Get the SQS action to be performed by this request.
QString actionString () const
Get the name of the SQS action to be performed by this request.
QString apiVersion () const
Get the SQS API version implemented by this request.
void setAction (const Action action)
Set the SQS action to be performed by this request.
void setApiVersion (const QString &version)
Set the SQS API version to include in this request.
virtual bool operator== (const SqsRequest &other) const
Equality operator.
Public Member Functions inherited from AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const
Construct an SqsCreateQueueResponse object.
Protected Member Functions inherited from SqsRequest
SqsRequest (SqsRequestPrivate *const d)
Constructs a new SqsRequest object.
int clearParameter (const QString &name)
Remove a parameter from the parameters to be included with this request.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this SQS request.
const QVariantMap & parameters () const
Get all parameters included with this SQS request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this SQS request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this SQS request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this SQS request.
Protected Member Functions inherited from AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
Friends
class TestSqsCreateQueueRequest
Additional Inherited Members
Public Types inherited from SqsRequest
enum Action {
AddPermissionAction = 0x00001, ChangeMessageVisibilityAction = 0x00002, ChangeMessageVisibilityBatchAction = 0x00004, CreateQueueAction = 0x00008,
DeleteMessageAction = 0x00010, DeleteMessageBatchAction = 0x00020, DeleteQueueAction = 0x00040, GetQueueAttributesAction = 0x00080,
GetQueueUrlAction = 0x00100, ListDeadLetterSourceQueuesAction = 0x00200, ListQueuesAction = 0x00400, PurgeQueueAction = 0x00800,
ReceiveMessageAction = 0x01000, RemovePermissionAction = 0x02000, SendMessageAction = 0x04000, SendMessageBatchAction = 0x08000,
SetQueueAttributesAction = 0x10000
}
Actions supported by SQS.
Static Public Member Functions inherited from SqsRequest
static bool isValidQueueName (const QString &queueName)
Check if queueName is a valid SQS queue name.
Protected Attributes inherited from AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Implements SQS CreateQueue requests.
See also
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html
Definition at line 31 of file sqscreatequeuerequest.h.
Constructor & Destructor Documentation
SqsCreateQueueRequest() [1/3]
SqsCreateQueueRequest::SqsCreateQueueRequest (const QString & queueName)
Constructs a new SqsCreateQueueRequest object.
Parameters
queueName Name of the queue to be created.
Definition at line 48 of file sqscreatequeuerequest.cpp.
References setQueueName().
     : SqsRequest(new SqsCreateQueueRequestPrivate(SqsRequest::CreateQueueAction, this))
 {
     setQueueName(queueName);
 }
SqsCreateQueueRequest() [2/3]
SqsCreateQueueRequest::SqsCreateQueueRequest (const SqsCreateQueueRequest & other)
Constructs a new SqsCreateQueueRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 59 of file sqscreatequeuerequest.cpp.
     : SqsRequest(new SqsCreateQueueRequestPrivate(*other.d_func(), this))
 {
 }
SqsCreateQueueRequest() [3/3]
SqsCreateQueueRequest::SqsCreateQueueRequest ()
Constructs an invalid SqsCreateQueueRequest object.
The constructed object will not be considered valid (ie isValid will return false) untill setQueueName is invoked with a non-empty queue name.
Definition at line 71 of file sqscreatequeuerequest.cpp.
     : SqsRequest(new SqsCreateQueueRequestPrivate(SqsRequest::CreateQueueAction, this))
 {
 }
Member Function Documentation
attribute()
QVariant SqsCreateQueueRequest::attribute (const QString & name, const QVariant & defaultValue = QVariant()) const
Get the value of an attribute to be set on the created queue.
The name parameter should be one of the attributes defined by the SQS documentation. The explicit attribute accessors function (such as delaySecond, maximumMessageSize, etc) should be used instead of directly accessing attributes via this function. However, this function may be used if Amazon adds support for new attributes that are not yet covered by this library explicitly.
Parameters
name Name of the queue attribute to get the value of.
defaultValue Value to return if name is not found.
Returns
Value of the name attribute, or defaultValue if not found.
Definition at line 107 of file sqscreatequeuerequest.cpp.
References attributes().
Referenced by delaySeconds(), maximumMessageSize(), messageRetentionPeriod(), policy(), receiveMessageWaitTimeSeconds(), and visibilityTimeout().
 {
     return attributes().value(name, defaultValue);
 }
attributes()
QVariantMap SqsCreateQueueRequest::attributes () const
Get a map of all attributes set to be included with this request.
Returns
A map of all attributes set to be included with this request.
Definition at line 117 of file sqscreatequeuerequest.cpp.
References SqsRequest::parameter().
Referenced by attribute(), and setAttribute().
 {
     return parameter(ATTRIBUTE_ENTRY_N).toMap();
 }
delaySeconds()
int SqsCreateQueueRequest::delaySeconds () const
Get the value of DelaySeconds queue attribute.
Returns
The value of DelaySeconds queue attribute, or -1 if not set.
Definition at line 127 of file sqscreatequeuerequest.cpp.
References attribute().
 {
     return attribute(DELAY_SECONDS, -1).toInt();
 }
isValid()
bool SqsCreateQueueRequest::isValid () const virtual
Is this request valid?
This implementation simply checks that this request has a valid queue name, as defined by SqsRequest::isValidQueueName.
Returns
true if this request is considered valid, false other.
See also
SqsRequest::isValidQueueName
Implements AwsAbstractRequest.
Definition at line 87 of file sqscreatequeuerequest.cpp.
References SqsRequest::isValidQueueName(), and queueName().
 {
     return isValidQueueName(queueName());
 }
maximumMessageSize()
int SqsCreateQueueRequest::maximumMessageSize () const
Get the value of MaximumMessageSize queue attribute.
Returns
The value of MaximumMessageSize queue attribute, or -1 if not set.
Definition at line 137 of file sqscreatequeuerequest.cpp.
References attribute().
 {
     return attribute(MAXIMUM_MESSAGE_SIZE, -1).toInt();
 }
messageRetentionPeriod()
int SqsCreateQueueRequest::messageRetentionPeriod () const
Get the value of MessageRetentionPeriod queue attribute.
Returns
The value of MessageRetentionPeriod queue attribute, or -1 if not set.
Definition at line 147 of file sqscreatequeuerequest.cpp.
References attribute().
 {
     return attribute(MESSAGE_RETENTION_PERIOD, -1).toInt();
 }
policy()
QString SqsCreateQueueRequest::policy () const
Get the value of Policy queue attribute.
Returns
The value of Policy queue attribute, or a null QString if not set.
Definition at line 157 of file sqscreatequeuerequest.cpp.
References attribute().
 {
     return attribute(POLICY).toString();
 }
queueName()
QString SqsCreateQueueRequest::queueName () const
Get the name of the queue to be created.
Returns
The name of the queue to be created, or a null QString if not yet set.
Definition at line 167 of file sqscreatequeuerequest.cpp.
References SqsRequest::parameter().
Referenced by isValid().
 {
     return parameter(QUEUE_NAME).toString();
 }
receiveMessageWaitTimeSeconds()
int SqsCreateQueueRequest::receiveMessageWaitTimeSeconds () const
Get the value of the ReceiveMessageWaitTimeoutSeconds queue attribute.
Returns
The value of the ReceiveMessageWaitTimeoutSeconds queue attribute, or -1 if not set.
Definition at line 178 of file sqscreatequeuerequest.cpp.
References attribute().
 {
     return attribute(RECEIVE_MESSAGE_WAIT_TIMEOUT_SECONDS, -1).toInt();
 }
response()
AwsAbstractResponse * SqsCreateQueueRequest::response (QNetworkReply *const reply) const protected virtual
Construct an SqsCreateQueueResponse object.
Parameters
reply Network reply this response should observe.
Returns
An SqsCreateQueueResponse instance for reply.
See also
AwsAbstractClient::send
Implements AwsAbstractRequest.
Definition at line 328 of file sqscreatequeuerequest.cpp.
 {
     return new SqsCreateQueueResponse(*this, reply);
 }
setAttribute()
void SqsCreateQueueRequest::setAttribute (const QString & name, const QVariant & value)
Set the value of an attribute to be include in the create queue request.
The name parameter should be one of the attributes defined by the SQS documentation. The explicit attribute setter functions (such as delaySecond, maximumMessageSize, etc) should be used instead of directly setting attributes via this function. However, this function may be used if Amazon adds support for new attributes that are not yet covered by this library explicitly.
Parameters
name Name of the queue attribute to set the value of.
value Value to set for the name attribute.
Note
Attribues can be removed by setting value to a null QVariant.
Definition at line 208 of file sqscreatequeuerequest.cpp.
References attributes(), and setAttributes().
Referenced by setDelaySeconds(), setMaximumMessageSize(), setMessageRetentionPeriod(), setPolicy(), setReceiveMessageWaitTimeSeconds(), and setVisibilityTimeout().
 {
     QVariantMap attributes = this->attributes();
     if (value.isNull()) {
         attributes.remove(name);
     } else {
         attributes.insert(name, value);
     }
     setAttributes(attributes);
 }
setAttributes()
void SqsCreateQueueRequest::setAttributes (const QVariantMap & attributes)
Set the attributes to be included in the create queue request.
The given attributes will entirely replace any existing attibutes map.
Parameters
attributes Map of all attributes to be includes with the request.
Definition at line 226 of file sqscreatequeuerequest.cpp.
References SqsRequest::setParameter().
Referenced by SqsClient::createQueue(), and setAttribute().
 {
     setParameter(ATTRIBUTE_ENTRY_N, attributes);
 }
setDelaySeconds()
void SqsCreateQueueRequest::setDelaySeconds (int delay)
Set the value of DelaySeconds queue attribute.
If delay is negative, then any existing DelaySeconds attribute will be cleared instead.
Parameters
delay Value to set for the DelaySeconds attribute.
Definition at line 239 of file sqscreatequeuerequest.cpp.
References setAttribute().
 {
     setAttribute(DELAY_SECONDS, (delay < 0) ? QVariant() : QVariant(delay));
 }
setMaximumMessageSize()
void SqsCreateQueueRequest::setMaximumMessageSize (int size)
Set the value of MaximumMessageSize queue attribute.
If size is negative, then any existing MaximumMessageSize attribute will be cleared instead.
Parameters
size Value to set for the MaximumMessageSize attribute.
Definition at line 252 of file sqscreatequeuerequest.cpp.
References setAttribute().
 {
     setAttribute(MAXIMUM_MESSAGE_SIZE, (size < 0) ? QVariant() : QVariant(size));
 }
setMessageRetentionPeriod()
void SqsCreateQueueRequest::setMessageRetentionPeriod (int period)
Set the value of MessageRetentionPeriod queue attribute.
If period is negative, then any existing MessageRetentionPeriod attribute will be cleared instead.
Parameters
period Value to set for the MessageRetentionPeriod attribute.
Definition at line 265 of file sqscreatequeuerequest.cpp.
References setAttribute().
 {
     setAttribute(MESSAGE_RETENTION_PERIOD, (period < 0) ? QVariant() : QVariant(period));
 }
setPolicy()
void SqsCreateQueueRequest::setPolicy (const QString & policy)
Set the value of Policy queue attribute.
If policy is a null QString, then any existing Policy attribute will be cleared instead.
Parameters
policy Value to set for the Policy attribute.
Definition at line 278 of file sqscreatequeuerequest.cpp.
References setAttribute().
 {
     setAttribute(POLICY, (policy.isNull()) ? QVariant() : QVariant(policy));
 }
setQueueName()
void SqsCreateQueueRequest::setQueueName (const QString & queueName)
Set the name of the queue to be created.
Todo:
add setPolicy overload that takes an AwsPolicy object reference.
Parameters
queueName Name of the queue to be created.
Definition at line 288 of file sqscreatequeuerequest.cpp.
References SqsRequest::setParameter().
Referenced by SqsCreateQueueRequest().
 {
     setParameter(QUEUE_NAME, queueName);
 }
setReceiveMessageWaitTimeSeconds()
void SqsCreateQueueRequest::setReceiveMessageWaitTimeSeconds (int time)
Set the value of ReceiveMessageWaitTimeoutSeconds queue attribute.
If time is negative, then any existing ReceiveMessageWaitTimeoutSeconds attribute will be cleared instead.
Parameters
time Value to set for the ReceiveMessageWaitTimeoutSeconds attribute.
Definition at line 301 of file sqscreatequeuerequest.cpp.
References setAttribute().
 {
     setAttribute(RECEIVE_MESSAGE_WAIT_TIMEOUT_SECONDS, (time < 0) ? QVariant() : QVariant(time));
 }
setVisibilityTimeout()
void SqsCreateQueueRequest::setVisibilityTimeout (int timeout)
Set the value of VisibilityTimeout queue attribute.
If timeout is negative, then any existing VisibilityTimeout attribute will be cleared instead
Parameters
timeout Value to set for the VisibilityTimeout attribute.
Definition at line 314 of file sqscreatequeuerequest.cpp.
References setAttribute().
 {
     setAttribute(VISIBILITY_TIMEOUT, (timeout < 0) ? QVariant() : QVariant(timeout));
 }
visibilityTimeout()
int SqsCreateQueueRequest::visibilityTimeout () const
Get the value of the VisibilityTimeout queue attribute.
Returns
The value of the VisibilityTimeout queue attribute, or -1 if not set.
Definition at line 188 of file sqscreatequeuerequest.cpp.
References attribute().
 {
     return attribute(VISIBILITY_TIMEOUT, -1).toInt();
 }
The documentation for this class was generated from the following files:
sqs/sqscreatequeuerequest.h
sqs/sqscreatequeuerequest.cpp