libqtaws: AWS::WorkMail::WorkMailClient Class Reference
AWS::WorkMail::WorkMailClient Class Reference
Client for Amazon WorkMail.
Public Slots
AssociateDelegateToResourceResponse * associateDelegateToResource (const AssociateDelegateToResourceRequest &request)
AssociateMemberToGroupResponse * associateMemberToGroup (const AssociateMemberToGroupRequest &request)
CreateAliasResponse * createAlias (const CreateAliasRequest &request)
CreateGroupResponse * createGroup (const CreateGroupRequest &request)
CreateResourceResponse * createResource (const CreateResourceRequest &request)
CreateUserResponse * createUser (const CreateUserRequest &request)
DeleteAliasResponse * deleteAlias (const DeleteAliasRequest &request)
DeleteGroupResponse * deleteGroup (const DeleteGroupRequest &request)
DeleteResourceResponse * deleteResource (const DeleteResourceRequest &request)
DeleteUserResponse * deleteUser (const DeleteUserRequest &request)
DeregisterFromWorkMailResponse * deregisterFromWorkMail (const DeregisterFromWorkMailRequest &request)
DescribeGroupResponse * describeGroup (const DescribeGroupRequest &request)
DescribeOrganizationResponse * describeOrganization (const DescribeOrganizationRequest &request)
DescribeResourceResponse * describeResource (const DescribeResourceRequest &request)
DescribeUserResponse * describeUser (const DescribeUserRequest &request)
DisassociateDelegateFromResourceResponse * disassociateDelegateFromResource (const DisassociateDelegateFromResourceRequest &request)
DisassociateMemberFromGroupResponse * disassociateMemberFromGroup (const DisassociateMemberFromGroupRequest &request)
ListAliasesResponse * listAliases (const ListAliasesRequest &request)
ListGroupMembersResponse * listGroupMembers (const ListGroupMembersRequest &request)
ListGroupsResponse * listGroups (const ListGroupsRequest &request)
ListOrganizationsResponse * listOrganizations (const ListOrganizationsRequest &request)
ListResourceDelegatesResponse * listResourceDelegates (const ListResourceDelegatesRequest &request)
ListResourcesResponse * listResources (const ListResourcesRequest &request)
ListUsersResponse * listUsers (const ListUsersRequest &request)
RegisterToWorkMailResponse * registerToWorkMail (const RegisterToWorkMailRequest &request)
ResetPasswordResponse * resetPassword (const ResetPasswordRequest &request)
UpdatePrimaryEmailAddressResponse * updatePrimaryEmailAddress (const UpdatePrimaryEmailAddressRequest &request)
UpdateResourceResponse * updateResource (const UpdateResourceRequest &request)
Public Member Functions
WorkMailClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WorkMailClient object.
WorkMailClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WorkMailClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon WorkMail.
Amazon WorkMail is a secure, managed business email and calendaring service with support for existing desktop and mobile email clients. You can access your email, contacts, and calendars using Microsoft Outlook, your browser, or their native iOS and Android email applications. You can integrate Amazon WorkMail with your existing corporate directory and control both the keys that encrypt your data and the location in which your data is
stored>
The Amazon WorkMail API is designed for the following
scenarios>
Listing and describing
organization>
Managing
user>
Managing
group>
Managing
resource>
All Amazon WorkMail API actions are Amazon-authenticated and certificate-signed. They not only require the use of the AWS SDK, but also allow for the exclusive use of IAM users and roles to help facilitate access, trust, and permission policies. By creating a role and allowing an IAM user to access the Amazon WorkMail site, the IAM user gains full administrative visibility into the entire Amazon WorkMail organization (or as set in the IAM policy). This includes, but is not limited to, the ability to create, update, and delete users, groups, and resources. This allows developers to perform the scenarios listed above, as well as give users the ability to grant access on a selective basis using the IAM
Definition at line 36 of file workmailclient.h.
Constructor & Destructor Documentation
WorkMailClient() [1/2]
AWS::WorkMail::WorkMailClient::WorkMailClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WorkMailClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 79 of file workmailclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new WorkMailClientPrivate(this), parent)
 {
     Q_D(WorkMailClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
WorkMailClient() [2/2]
AWS::WorkMail::WorkMailClient::WorkMailClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WorkMailClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 109 of file workmailclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new WorkMailClientPrivate(this), parent)
 {
     Q_D(WorkMailClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
workmail/workmailclient.h
workmail/workmailclient.cpp