libqtaws: AWS::DynamoDB::DynamoDBClient Class Reference
AWS::DynamoDB::DynamoDBClient Class Reference
Client for Amazon DynamoDB.
Public Slots
BatchGetItemResponse * batchGetItem (const BatchGetItemRequest &request)
BatchWriteItemResponse * batchWriteItem (const BatchWriteItemRequest &request)
CreateBackupResponse * createBackup (const CreateBackupRequest &request)
CreateGlobalTableResponse * createGlobalTable (const CreateGlobalTableRequest &request)
CreateTableResponse * createTable (const CreateTableRequest &request)
DeleteBackupResponse * deleteBackup (const DeleteBackupRequest &request)
DeleteItemResponse * deleteItem (const DeleteItemRequest &request)
DeleteTableResponse * deleteTable (const DeleteTableRequest &request)
DescribeBackupResponse * describeBackup (const DescribeBackupRequest &request)
DescribeContinuousBackupsResponse * describeContinuousBackups (const DescribeContinuousBackupsRequest &request)
DescribeGlobalTableResponse * describeGlobalTable (const DescribeGlobalTableRequest &request)
DescribeLimitsResponse * describeLimits (const DescribeLimitsRequest &request)
DescribeTableResponse * describeTable (const DescribeTableRequest &request)
DescribeTimeToLiveResponse * describeTimeToLive (const DescribeTimeToLiveRequest &request)
GetItemResponse * getItem (const GetItemRequest &request)
ListBackupsResponse * listBackups (const ListBackupsRequest &request)
ListGlobalTablesResponse * listGlobalTables (const ListGlobalTablesRequest &request)
ListTablesResponse * listTables (const ListTablesRequest &request)
ListTagsOfResourceResponse * listTagsOfResource (const ListTagsOfResourceRequest &request)
PutItemResponse * putItem (const PutItemRequest &request)
QueryResponse * query (const QueryRequest &request)
RestoreTableFromBackupResponse * restoreTableFromBackup (const RestoreTableFromBackupRequest &request)
ScanResponse * scan (const ScanRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateGlobalTableResponse * updateGlobalTable (const UpdateGlobalTableRequest &request)
UpdateItemResponse * updateItem (const UpdateItemRequest &request)
UpdateTableResponse * updateTable (const UpdateTableRequest &request)
UpdateTimeToLiveResponse * updateTimeToLive (const UpdateTimeToLiveRequest &request)
Public Member Functions
DynamoDBClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DynamoDBClient object.
DynamoDBClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DynamoDBClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon DynamoDB.
<fullname>Amazon DynamoDB</fullname>
Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability. DynamoDB lets you offload the administrative burdens of operating and scaling a distributed database, so that you don't have to worry about hardware provisioning, setup and configuration, replication, software patching, or cluster
scaling>
With DynamoDB, you can create database tables that can store and retrieve any amount of data, and serve any level of request traffic. You can scale up or scale down your tables' throughput capacity without downtime or performance degradation, and use the AWS Management Console to monitor resource utilization and performance
metrics>
DynamoDB automatically spreads the data and traffic for your tables over a sufficient number of servers to handle your throughput and storage requirements, while maintaining consistent and fast performance. All of your data is stored on solid state disks (SSDs) and automatically replicated across multiple Availability Zones in an AWS region, providing built-in high availability and data durability.
Definition at line 36 of file dynamodbclient.h.
Constructor & Destructor Documentation
DynamoDBClient() [1/2]
AWS::DynamoDB::DynamoDBClient::DynamoDBClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DynamoDBClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 65 of file dynamodbclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new DynamoDBClientPrivate(this), parent)
 {
     Q_D(DynamoDBClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
DynamoDBClient() [2/2]
AWS::DynamoDB::DynamoDBClient::DynamoDBClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DynamoDBClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 95 of file dynamodbclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new DynamoDBClientPrivate(this), parent)
 {
     Q_D(DynamoDBClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
dynamodb/dynamodbclient.h
dynamodb/dynamodbclient.cpp