libqtaws: AWS::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client Class Reference
AWS::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client Class Reference
Client for Elastic Load Balancing (Elastic Load Balancing v2)
Public Slots
AddListenerCertificatesResponse * addListenerCertificates (const AddListenerCertificatesRequest &request)
AddTagsResponse * addTags (const AddTagsRequest &request)
CreateListenerResponse * createListener (const CreateListenerRequest &request)
CreateLoadBalancerResponse * createLoadBalancer (const CreateLoadBalancerRequest &request)
CreateRuleResponse * createRule (const CreateRuleRequest &request)
CreateTargetGroupResponse * createTargetGroup (const CreateTargetGroupRequest &request)
DeleteListenerResponse * deleteListener (const DeleteListenerRequest &request)
DeleteLoadBalancerResponse * deleteLoadBalancer (const DeleteLoadBalancerRequest &request)
DeleteRuleResponse * deleteRule (const DeleteRuleRequest &request)
DeleteTargetGroupResponse * deleteTargetGroup (const DeleteTargetGroupRequest &request)
DeregisterTargetsResponse * deregisterTargets (const DeregisterTargetsRequest &request)
DescribeAccountLimitsResponse * describeAccountLimits (const DescribeAccountLimitsRequest &request)
DescribeListenerCertificatesResponse * describeListenerCertificates (const DescribeListenerCertificatesRequest &request)
DescribeListenersResponse * describeListeners (const DescribeListenersRequest &request)
DescribeLoadBalancerAttributesResponse * describeLoadBalancerAttributes (const DescribeLoadBalancerAttributesRequest &request)
DescribeLoadBalancersResponse * describeLoadBalancers (const DescribeLoadBalancersRequest &request)
DescribeRulesResponse * describeRules (const DescribeRulesRequest &request)
DescribeSSLPoliciesResponse * describeSSLPolicies (const DescribeSSLPoliciesRequest &request)
DescribeTagsResponse * describeTags (const DescribeTagsRequest &request)
DescribeTargetGroupAttributesResponse * describeTargetGroupAttributes (const DescribeTargetGroupAttributesRequest &request)
DescribeTargetGroupsResponse * describeTargetGroups (const DescribeTargetGroupsRequest &request)
DescribeTargetHealthResponse * describeTargetHealth (const DescribeTargetHealthRequest &request)
ModifyListenerResponse * modifyListener (const ModifyListenerRequest &request)
ModifyLoadBalancerAttributesResponse * modifyLoadBalancerAttributes (const ModifyLoadBalancerAttributesRequest &request)
ModifyRuleResponse * modifyRule (const ModifyRuleRequest &request)
ModifyTargetGroupResponse * modifyTargetGroup (const ModifyTargetGroupRequest &request)
ModifyTargetGroupAttributesResponse * modifyTargetGroupAttributes (const ModifyTargetGroupAttributesRequest &request)
RegisterTargetsResponse * registerTargets (const RegisterTargetsRequest &request)
RemoveListenerCertificatesResponse * removeListenerCertificates (const RemoveListenerCertificatesRequest &request)
RemoveTagsResponse * removeTags (const RemoveTagsRequest &request)
SetIpAddressTypeResponse * setIpAddressType (const SetIpAddressTypeRequest &request)
SetRulePrioritiesResponse * setRulePriorities (const SetRulePrioritiesRequest &request)
SetSecurityGroupsResponse * setSecurityGroups (const SetSecurityGroupsRequest &request)
SetSubnetsResponse * setSubnets (const SetSubnetsRequest &request)
Public Member Functions
ElasticLoadBalancingv2Client (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticLoadBalancingv2Client object.
ElasticLoadBalancingv2Client (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticLoadBalancingv2Client object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Elastic Load Balancing (Elastic Load Balancing v2)
<fullname>Elastic Load Balancing</fullname>
A load balancer distributes incoming traffic across targets, such as your EC2 instances. This enables you to increase the availability of your application. The load balancer also monitors the health of its registered targets and ensures that it routes traffic only to healthy targets. You configure your load balancer to accept incoming traffic by specifying one or more listeners, which are configured with a protocol and port number for connections from clients to the load balancer. You configure a target group with a protocol and port number for connections from the load balancer to the targets, and with health check settings to be used when checking the health status of the
targets>
Elastic Load Balancing supports the following types of load balancers: Application Load Balancers, Network Load Balancers, and Classic Load
Balancers>
An Application Load Balancer makes routing and load balancing decisions at the application layer (HTTP/HTTPS). A Network Load Balancer makes routing and load balancing decisions at the transport layer (TCP). Both Application Load Balancers and Network Load Balancers can route requests to one or more ports on each EC2 instance or container instance in your virtual private cloud
(VPC)>
A Classic Load Balancer makes routing and load balancing decisions either at the transport layer (TCP/SSL) or the application layer (HTTP/HTTPS), and supports either EC2-Classic or a VPC. For more information, see the Elastic Load Balancing User Guide>
This reference covers the 2015-12-01 API, which supports Application Load Balancers and Network Load Balancers. The 2012-06-01 API supports Classic Load
Balancers>
To get started, complete the following
tasks>
Create a load balancer using
CreateLoadBalancer>
Create a target group using
CreateTargetGroup>
Register targets for the target group using
RegisterTargets>
Create one or more listeners for your load balancer using
CreateListener>
To delete a load balancer and its related resources, complete the following
tasks>
Delete the load balancer using
DeleteLoadBalancer>
Delete the target group using
DeleteTargetGroup>
All Elastic Load Balancing operations are idempotent, which means that they complete at most one time. If you repeat an operation, it
Definition at line 36 of file elasticloadbalancingv2client.h.
Constructor & Destructor Documentation
ElasticLoadBalancingv2Client() [1/2]
AWS::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::ElasticLoadBalancingv2Client (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticLoadBalancingv2Client object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 114 of file elasticloadbalancingv2client.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new ElasticLoadBalancingv2ClientPrivate(this), parent)
 {
     Q_D(ElasticLoadBalancingv2Client);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
ElasticLoadBalancingv2Client() [2/2]
AWS::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::ElasticLoadBalancingv2Client (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticLoadBalancingv2Client object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 144 of file elasticloadbalancingv2client.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new ElasticLoadBalancingv2ClientPrivate(this), parent)
 {
     Q_D(ElasticLoadBalancingv2Client);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
elasticloadbalancingv2/elasticloadbalancingv2client.h
elasticloadbalancingv2/elasticloadbalancingv2client.cpp