libqtaws: SqsCreateQueueResponsePrivate Class Reference
SqsCreateQueueResponsePrivate Class Reference
Private implementation for SqsCreateQueueResponse.
Public Member Functions
SqsCreateQueueResponsePrivate (SqsCreateQueueResponse *const q)
Constructs a new SqsCreateQueueResponsePrivate object.
void parseCreateQueueResponse (QXmlStreamReader &xml)
Parse an SQS CreateQueueResponse element.
void parseCreateQueueResult (QXmlStreamReader &xml)
Parse an SQS CreateQueueResult element.
Public Member Functions inherited from SqsResponsePrivate
SqsResponsePrivate (SqsResponse *const q)
Constructs a new SqsResponsePrivate object.
void parseErrorResponse (QXmlStreamReader &xml)
Parse an SQS ErrorResponse element.
void parseResponseMetadata (QXmlStreamReader &xml)
Parse an SQS ResponseMetadata element.
Public Member Functions inherited from AwsAbstractResponsePrivate
AwsAbstractResponsePrivate (AwsAbstractResponse *const q)
Constructs a new AwsAbstractResponsePrivate object.
virtual ~AwsAbstractResponsePrivate ()
AwsAbstractResponsePrivate destructor.
Public Attributes
QString queueUrl
Created queue URL.
Public Attributes inherited from SqsResponsePrivate
SqsErrorList errors
SQS errors.
QString requestId
SQS request ID.
Public Attributes inherited from AwsAbstractResponsePrivate
QNetworkReply * reply
Network reply for this response.
const AwsAbstractRequest * request
AWS request for this response.
QXmlStreamReader::Error xmlError
XML parse error code.
QString xmlErrorString
XML parse error string.
Private Attributes
SqsCreateQueueResponse *const q_ptr
Internal q-pointer.
Additional Inherited Members
Protected Attributes inherited from AwsAbstractResponsePrivate
AwsAbstractResponse *const q_ptr
Internal q-pointer.
Detailed Description
Private implementation for SqsCreateQueueResponse.
Definition at line 29 of file sqscreatequeueresponse_p.h.
Constructor & Destructor Documentation
SqsCreateQueueResponsePrivate::SqsCreateQueueResponsePrivate (SqsCreateQueueResponse *const q)
Constructs a new SqsCreateQueueResponsePrivate object.
Parameters
q Pointer to this object's public SqsCreateQueueResponse instance.
Definition at line 129 of file sqscreatequeueresponse.cpp.
     : SqsResponsePrivate(q), q_ptr(q)
 {
 }
Member Function Documentation
void SqsCreateQueueResponsePrivate::parseCreateQueueResponse (QXmlStreamReader & xml)
Parse an SQS CreateQueueResponse element.
This implementation parses SQS CreateQueueResponse elements, as defined by http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
For example:
 <CreateQueueResponse>
   <CreateQueueResult>
     <QueueUrl>http://sqs.us-east-1.amazonaws.com/123456789012/testQueue</QueueUrl>
   </CreateQueueResult>
   <ResponseMetadata>
     <RequestId>7a62c49f-347e-4fc4-9331-6e8e7a96aa73</RequestId>
   </ResponseMetadata>
 </CreateQueueResponse>
Parameters
xml XML stream to parse.
See also
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Definition at line 158 of file sqscreatequeueresponse.cpp.
References parseCreateQueueResult(), and SqsResponsePrivate::parseResponseMetadata().
 {
     Q_ASSERT(xml.name() == QLatin1String("CreateQueueResponse"));
     while (xml.readNextStartElement()) {
         if (xml.name() == QLatin1String("CreateQueueResult")) {
             parseCreateQueueResult(xml);
         } else if (xml.name() == QLatin1String("ResponseMetadata")) {
             parseResponseMetadata(xml);
         } else {
             qWarning() << "ignoring" << xml.name();
             xml.skipCurrentElement();
         }
     }
 }
void SqsCreateQueueResponsePrivate::parseCreateQueueResult (QXmlStreamReader & xml)
Parse an SQS CreateQueueResult element.
This implementation parses SQS CreateQueueResult elements, as defined by http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
For example:
 <CreateQueueResult>
   <QueueUrl>http://sqs.us-east-1.amazonaws.com/123456789012/testQueue</QueueUrl>
 </CreateQueueResult>
Parameters
xml XML stream to parse.
See also
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Definition at line 191 of file sqscreatequeueresponse.cpp.
References queueUrl.
Referenced by parseCreateQueueResponse().
 {
     Q_ASSERT(xml.name() == QLatin1String("CreateQueueResult"));
     while (xml.readNextStartElement()) {
         if (xml.name() == QLatin1String("QueueUrl")) {
             queueUrl = xml.readElementText();
         } else {
             qWarning() << "ignoring" << xml.name();
             xml.skipCurrentElement();
         }
     }
 }
The documentation for this class was generated from the following files:
sqs/sqscreatequeueresponse_p.h
sqs/sqscreatequeueresponse.cpp