libqtaws: RedshiftClient Class Reference
RedshiftClient Class Reference
Client for Amazon Redshift.
Public Slots
RedshiftAuthorizeClusterSecurityGroupIngressResponse * authorizeClusterSecurityGroupIngress (const RedshiftAuthorizeClusterSecurityGroupIngressRequest &request)
RedshiftAuthorizeSnapshotAccessResponse * authorizeSnapshotAccess (const RedshiftAuthorizeSnapshotAccessRequest &request)
RedshiftCopyClusterSnapshotResponse * copyClusterSnapshot (const RedshiftCopyClusterSnapshotRequest &request)
RedshiftCreateClusterResponse * createCluster (const RedshiftCreateClusterRequest &request)
RedshiftCreateClusterParameterGroupResponse * createClusterParameterGroup (const RedshiftCreateClusterParameterGroupRequest &request)
RedshiftCreateClusterSecurityGroupResponse * createClusterSecurityGroup (const RedshiftCreateClusterSecurityGroupRequest &request)
RedshiftCreateClusterSnapshotResponse * createClusterSnapshot (const RedshiftCreateClusterSnapshotRequest &request)
RedshiftCreateClusterSubnetGroupResponse * createClusterSubnetGroup (const RedshiftCreateClusterSubnetGroupRequest &request)
RedshiftCreateEventSubscriptionResponse * createEventSubscription (const RedshiftCreateEventSubscriptionRequest &request)
RedshiftCreateHsmClientCertificateResponse * createHsmClientCertificate (const RedshiftCreateHsmClientCertificateRequest &request)
RedshiftCreateHsmConfigurationResponse * createHsmConfiguration (const RedshiftCreateHsmConfigurationRequest &request)
RedshiftCreateSnapshotCopyGrantResponse * createSnapshotCopyGrant (const RedshiftCreateSnapshotCopyGrantRequest &request)
RedshiftCreateTagsResponse * createTags (const RedshiftCreateTagsRequest &request)
RedshiftDeleteClusterResponse * deleteCluster (const RedshiftDeleteClusterRequest &request)
RedshiftDeleteClusterParameterGroupResponse * deleteClusterParameterGroup (const RedshiftDeleteClusterParameterGroupRequest &request)
RedshiftDeleteClusterSecurityGroupResponse * deleteClusterSecurityGroup (const RedshiftDeleteClusterSecurityGroupRequest &request)
RedshiftDeleteClusterSnapshotResponse * deleteClusterSnapshot (const RedshiftDeleteClusterSnapshotRequest &request)
RedshiftDeleteClusterSubnetGroupResponse * deleteClusterSubnetGroup (const RedshiftDeleteClusterSubnetGroupRequest &request)
RedshiftDeleteEventSubscriptionResponse * deleteEventSubscription (const RedshiftDeleteEventSubscriptionRequest &request)
RedshiftDeleteHsmClientCertificateResponse * deleteHsmClientCertificate (const RedshiftDeleteHsmClientCertificateRequest &request)
RedshiftDeleteHsmConfigurationResponse * deleteHsmConfiguration (const RedshiftDeleteHsmConfigurationRequest &request)
RedshiftDeleteSnapshotCopyGrantResponse * deleteSnapshotCopyGrant (const RedshiftDeleteSnapshotCopyGrantRequest &request)
RedshiftDeleteTagsResponse * deleteTags (const RedshiftDeleteTagsRequest &request)
RedshiftDescribeClusterParameterGroupsResponse * describeClusterParameterGroups (const RedshiftDescribeClusterParameterGroupsRequest &request)
RedshiftDescribeClusterParametersResponse * describeClusterParameters (const RedshiftDescribeClusterParametersRequest &request)
RedshiftDescribeClusterSecurityGroupsResponse * describeClusterSecurityGroups (const RedshiftDescribeClusterSecurityGroupsRequest &request)
RedshiftDescribeClusterSnapshotsResponse * describeClusterSnapshots (const RedshiftDescribeClusterSnapshotsRequest &request)
RedshiftDescribeClusterSubnetGroupsResponse * describeClusterSubnetGroups (const RedshiftDescribeClusterSubnetGroupsRequest &request)
RedshiftDescribeClusterVersionsResponse * describeClusterVersions (const RedshiftDescribeClusterVersionsRequest &request)
RedshiftDescribeClustersResponse * describeClusters (const RedshiftDescribeClustersRequest &request)
RedshiftDescribeDefaultClusterParametersResponse * describeDefaultClusterParameters (const RedshiftDescribeDefaultClusterParametersRequest &request)
RedshiftDescribeEventCategoriesResponse * describeEventCategories (const RedshiftDescribeEventCategoriesRequest &request)
RedshiftDescribeEventSubscriptionsResponse * describeEventSubscriptions (const RedshiftDescribeEventSubscriptionsRequest &request)
RedshiftDescribeEventsResponse * describeEvents (const RedshiftDescribeEventsRequest &request)
RedshiftDescribeHsmClientCertificatesResponse * describeHsmClientCertificates (const RedshiftDescribeHsmClientCertificatesRequest &request)
RedshiftDescribeHsmConfigurationsResponse * describeHsmConfigurations (const RedshiftDescribeHsmConfigurationsRequest &request)
RedshiftDescribeLoggingStatusResponse * describeLoggingStatus (const RedshiftDescribeLoggingStatusRequest &request)
RedshiftDescribeOrderableClusterOptionsResponse * describeOrderableClusterOptions (const RedshiftDescribeOrderableClusterOptionsRequest &request)
RedshiftDescribeReservedNodeOfferingsResponse * describeReservedNodeOfferings (const RedshiftDescribeReservedNodeOfferingsRequest &request)
RedshiftDescribeReservedNodesResponse * describeReservedNodes (const RedshiftDescribeReservedNodesRequest &request)
RedshiftDescribeResizeResponse * describeResize (const RedshiftDescribeResizeRequest &request)
RedshiftDescribeSnapshotCopyGrantsResponse * describeSnapshotCopyGrants (const RedshiftDescribeSnapshotCopyGrantsRequest &request)
RedshiftDescribeTableRestoreStatusResponse * describeTableRestoreStatus (const RedshiftDescribeTableRestoreStatusRequest &request)
RedshiftDescribeTagsResponse * describeTags (const RedshiftDescribeTagsRequest &request)
RedshiftDisableLoggingResponse * disableLogging (const RedshiftDisableLoggingRequest &request)
RedshiftDisableSnapshotCopyResponse * disableSnapshotCopy (const RedshiftDisableSnapshotCopyRequest &request)
RedshiftEnableLoggingResponse * enableLogging (const RedshiftEnableLoggingRequest &request)
RedshiftEnableSnapshotCopyResponse * enableSnapshotCopy (const RedshiftEnableSnapshotCopyRequest &request)
RedshiftModifyClusterResponse * modifyCluster (const RedshiftModifyClusterRequest &request)
RedshiftModifyClusterIamRolesResponse * modifyClusterIamRoles (const RedshiftModifyClusterIamRolesRequest &request)
RedshiftModifyClusterParameterGroupResponse * modifyClusterParameterGroup (const RedshiftModifyClusterParameterGroupRequest &request)
RedshiftModifyClusterSubnetGroupResponse * modifyClusterSubnetGroup (const RedshiftModifyClusterSubnetGroupRequest &request)
RedshiftModifyEventSubscriptionResponse * modifyEventSubscription (const RedshiftModifyEventSubscriptionRequest &request)
RedshiftModifySnapshotCopyRetentionPeriodResponse * modifySnapshotCopyRetentionPeriod (const RedshiftModifySnapshotCopyRetentionPeriodRequest &request)
RedshiftPurchaseReservedNodeOfferingResponse * purchaseReservedNodeOffering (const RedshiftPurchaseReservedNodeOfferingRequest &request)
RedshiftRebootClusterResponse * rebootCluster (const RedshiftRebootClusterRequest &request)
RedshiftResetClusterParameterGroupResponse * resetClusterParameterGroup (const RedshiftResetClusterParameterGroupRequest &request)
RedshiftRestoreFromClusterSnapshotResponse * restoreFromClusterSnapshot (const RedshiftRestoreFromClusterSnapshotRequest &request)
RedshiftRestoreTableFromClusterSnapshotResponse * restoreTableFromClusterSnapshot (const RedshiftRestoreTableFromClusterSnapshotRequest &request)
RedshiftRevokeClusterSecurityGroupIngressResponse * revokeClusterSecurityGroupIngress (const RedshiftRevokeClusterSecurityGroupIngressRequest &request)
RedshiftRevokeSnapshotAccessResponse * revokeSnapshotAccess (const RedshiftRevokeSnapshotAccessRequest &request)
RedshiftRotateEncryptionKeyResponse * rotateEncryptionKey (const RedshiftRotateEncryptionKeyRequest &request)
Public Member Functions
RedshiftClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new RedshiftClient object.
RedshiftClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new RedshiftClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Redshift.
<fullname>Amazon Redshift</fullname> Overview
This is an interface reference for Amazon Redshift. It contains documentation for one of the programming or command line interfaces you can use to manage Amazon Redshift clusters. Note that Amazon Redshift is asynchronous, which means that some interfaces may require techniques, such as polling or asynchronous callback handlers, to determine when a command has been applied. In this reference, the parameter descriptions indicate whether a change is applied immediately, on the next instance reboot, or during the next maintenance window. For a summary of the Amazon Redshift cluster management interfaces, go to Using the Amazon Redshift Management Interfaces .
Amazon Redshift manages all the work of setting up, operating, and scaling a data warehouse: provisioning capacity, monitoring and backing up the cluster, and applying patches and upgrades to the Amazon Redshift engine. You can focus on using your data to acquire new insights for your business and customers.
If you are a first-time user of Amazon Redshift, we recommend that you begin by reading the The Amazon Redshift Getting Started Guide
If you are a database developer, the Amazon Redshift Database Developer Guide explains how to design, build, query, and maintain the databases that make up your data warehouse.
Definition at line 33 of file redshiftclient.h.
Constructor & Destructor Documentation
RedshiftClient::RedshiftClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new RedshiftClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 54 of file redshiftclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new RedshiftClientPrivate(this), parent)
 {
     Q_D(RedshiftClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
RedshiftClient::RedshiftClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new RedshiftClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 84 of file redshiftclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new RedshiftClientPrivate(this), parent)
 {
     Q_D(RedshiftClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
redshift/redshiftclient.h
redshift/redshiftclient.cpp