libqtaws: AWS::SQS::SqsClient Class Reference
AWS::SQS::SqsClient Class Reference
Client for Amazon Simple Queue Service (SQS)
Public Slots
AddPermissionResponse * addPermission (const AddPermissionRequest &request)
ChangeMessageVisibilityResponse * changeMessageVisibility (const ChangeMessageVisibilityRequest &request)
ChangeMessageVisibilityBatchResponse * changeMessageVisibilityBatch (const ChangeMessageVisibilityBatchRequest &request)
CreateQueueResponse * createQueue (const CreateQueueRequest &request)
DeleteMessageResponse * deleteMessage (const DeleteMessageRequest &request)
DeleteMessageBatchResponse * deleteMessageBatch (const DeleteMessageBatchRequest &request)
DeleteQueueResponse * deleteQueue (const DeleteQueueRequest &request)
GetQueueAttributesResponse * getQueueAttributes (const GetQueueAttributesRequest &request)
GetQueueUrlResponse * getQueueUrl (const GetQueueUrlRequest &request)
ListDeadLetterSourceQueuesResponse * listDeadLetterSourceQueues (const ListDeadLetterSourceQueuesRequest &request)
ListQueueTagsResponse * listQueueTags (const ListQueueTagsRequest &request)
ListQueuesResponse * listQueues (const ListQueuesRequest &request)
PurgeQueueResponse * purgeQueue (const PurgeQueueRequest &request)
ReceiveMessageResponse * receiveMessage (const ReceiveMessageRequest &request)
RemovePermissionResponse * removePermission (const RemovePermissionRequest &request)
SendMessageResponse * sendMessage (const SendMessageRequest &request)
SendMessageBatchResponse * sendMessageBatch (const SendMessageBatchRequest &request)
SetQueueAttributesResponse * setQueueAttributes (const SetQueueAttributesRequest &request)
TagQueueResponse * tagQueue (const TagQueueRequest &request)
UntagQueueResponse * untagQueue (const UntagQueueRequest &request)
Public Member Functions
SqsClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SqsClient object.
SqsClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SqsClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Simple Queue Service (SQS)
Welcome to the Amazon Simple Queue Service API
Reference>
Amazon Simple Queue Service (Amazon SQS) is a reliable, highly-scalable hosted queue for storing messages as they travel between applications or microservices. Amazon SQS moves data between distributed application components and helps you decouple these
components> <note>
Standard queues are available in all regions. FIFO queues are available in the US East (N. Virginia), US East (Ohio), US West (Oregon), and EU (Ireland)
regions> </note>
You can use AWS SDKs to access Amazon SQS using your favorite programming language. The SDKs perform tasks such as the following
automatically>
Cryptographically sign your service
request>
Retry
request>
Handle error
response>
Additional Information
</p
Amazon SQS Product Page
</p
Amazon Simple Queue Service Developer Guide
</p
Making API Requests
</p
Using Amazon SQS Message Attributes
</p
Using Amazon SQS Dead-Letter Queues
</p
Amazon Web Services General Reference
</p
Regions and Endpoints
Definition at line 36 of file sqsclient.h.
Constructor & Destructor Documentation
SqsClient() [1/2]
SqsClient::SqsClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SqsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 112 of file sqsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new SqsClientPrivate(this), parent)
 {
     Q_D(SqsClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
SqsClient() [2/2]
SqsClient::SqsClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SqsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 142 of file sqsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new SqsClientPrivate(this), parent)
 {
     Q_D(SqsClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
sqs2/sqsclient.h
sqs2/sqsclient.cpp