libqtaws: AWS::Inspector::InspectorClient Class Reference
AWS::Inspector::InspectorClient Class Reference
Client for Amazon Inspector.
Public Slots
AddAttributesToFindingsResponse * addAttributesToFindings (const AddAttributesToFindingsRequest &request)
CreateAssessmentTargetResponse * createAssessmentTarget (const CreateAssessmentTargetRequest &request)
CreateAssessmentTemplateResponse * createAssessmentTemplate (const CreateAssessmentTemplateRequest &request)
CreateResourceGroupResponse * createResourceGroup (const CreateResourceGroupRequest &request)
DeleteAssessmentRunResponse * deleteAssessmentRun (const DeleteAssessmentRunRequest &request)
DeleteAssessmentTargetResponse * deleteAssessmentTarget (const DeleteAssessmentTargetRequest &request)
DeleteAssessmentTemplateResponse * deleteAssessmentTemplate (const DeleteAssessmentTemplateRequest &request)
DescribeAssessmentRunsResponse * describeAssessmentRuns (const DescribeAssessmentRunsRequest &request)
DescribeAssessmentTargetsResponse * describeAssessmentTargets (const DescribeAssessmentTargetsRequest &request)
DescribeAssessmentTemplatesResponse * describeAssessmentTemplates (const DescribeAssessmentTemplatesRequest &request)
DescribeCrossAccountAccessRoleResponse * describeCrossAccountAccessRole ()
DescribeFindingsResponse * describeFindings (const DescribeFindingsRequest &request)
DescribeResourceGroupsResponse * describeResourceGroups (const DescribeResourceGroupsRequest &request)
DescribeRulesPackagesResponse * describeRulesPackages (const DescribeRulesPackagesRequest &request)
GetAssessmentReportResponse * getAssessmentReport (const GetAssessmentReportRequest &request)
GetTelemetryMetadataResponse * getTelemetryMetadata (const GetTelemetryMetadataRequest &request)
ListAssessmentRunAgentsResponse * listAssessmentRunAgents (const ListAssessmentRunAgentsRequest &request)
ListAssessmentRunsResponse * listAssessmentRuns (const ListAssessmentRunsRequest &request)
ListAssessmentTargetsResponse * listAssessmentTargets (const ListAssessmentTargetsRequest &request)
ListAssessmentTemplatesResponse * listAssessmentTemplates (const ListAssessmentTemplatesRequest &request)
ListEventSubscriptionsResponse * listEventSubscriptions (const ListEventSubscriptionsRequest &request)
ListFindingsResponse * listFindings (const ListFindingsRequest &request)
ListRulesPackagesResponse * listRulesPackages (const ListRulesPackagesRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
PreviewAgentsResponse * previewAgents (const PreviewAgentsRequest &request)
RegisterCrossAccountAccessRoleResponse * registerCrossAccountAccessRole (const RegisterCrossAccountAccessRoleRequest &request)
RemoveAttributesFromFindingsResponse * removeAttributesFromFindings (const RemoveAttributesFromFindingsRequest &request)
SetTagsForResourceResponse * setTagsForResource (const SetTagsForResourceRequest &request)
StartAssessmentRunResponse * startAssessmentRun (const StartAssessmentRunRequest &request)
StopAssessmentRunResponse * stopAssessmentRun (const StopAssessmentRunRequest &request)
SubscribeToEventResponse * subscribeToEvent (const SubscribeToEventRequest &request)
UnsubscribeFromEventResponse * unsubscribeFromEvent (const UnsubscribeFromEventRequest &request)
UpdateAssessmentTargetResponse * updateAssessmentTarget (const UpdateAssessmentTargetRequest &request)
Public Member Functions
InspectorClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new InspectorClient object.
InspectorClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new InspectorClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Inspector.
<fullname>Amazon Inspector</fullname>
Amazon Inspector enables you to analyze the behavior of your AWS resources and to identify potential security issues. For more information, see Amazon Inspector User
Definition at line 36 of file inspectorclient.h.
Constructor & Destructor Documentation
InspectorClient() [1/2]
AWS::Inspector::InspectorClient::InspectorClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new InspectorClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 51 of file inspectorclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new InspectorClientPrivate(this), parent)
 {
     Q_D(InspectorClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
InspectorClient() [2/2]
AWS::Inspector::InspectorClient::InspectorClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new InspectorClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 81 of file inspectorclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new InspectorClientPrivate(this), parent)
 {
     Q_D(InspectorClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
inspector/inspectorclient.h
inspector/inspectorclient.cpp