libqtaws: GlacierClient Class Reference
GlacierClient Class Reference
Client for Amazon Glacier.
Public Slots
GlacierAbortMultipartUploadResponse * abortMultipartUpload (const GlacierAbortMultipartUploadRequest &request)
GlacierAbortVaultLockResponse * abortVaultLock (const GlacierAbortVaultLockRequest &request)
GlacierAddTagsToVaultResponse * addTagsToVault (const GlacierAddTagsToVaultRequest &request)
GlacierCompleteMultipartUploadResponse * completeMultipartUpload (const GlacierCompleteMultipartUploadRequest &request)
GlacierCompleteVaultLockResponse * completeVaultLock (const GlacierCompleteVaultLockRequest &request)
GlacierCreateVaultResponse * createVault (const GlacierCreateVaultRequest &request)
GlacierDeleteArchiveResponse * deleteArchive (const GlacierDeleteArchiveRequest &request)
GlacierDeleteVaultResponse * deleteVault (const GlacierDeleteVaultRequest &request)
GlacierDeleteVaultAccessPolicyResponse * deleteVaultAccessPolicy (const GlacierDeleteVaultAccessPolicyRequest &request)
GlacierDeleteVaultNotificationsResponse * deleteVaultNotifications (const GlacierDeleteVaultNotificationsRequest &request)
GlacierDescribeJobResponse * describeJob (const GlacierDescribeJobRequest &request)
GlacierDescribeVaultResponse * describeVault (const GlacierDescribeVaultRequest &request)
GlacierGetDataRetrievalPolicyResponse * getDataRetrievalPolicy (const GlacierGetDataRetrievalPolicyRequest &request)
GlacierGetJobOutputResponse * getJobOutput (const GlacierGetJobOutputRequest &request)
GlacierGetVaultAccessPolicyResponse * getVaultAccessPolicy (const GlacierGetVaultAccessPolicyRequest &request)
GlacierGetVaultLockResponse * getVaultLock (const GlacierGetVaultLockRequest &request)
GlacierGetVaultNotificationsResponse * getVaultNotifications (const GlacierGetVaultNotificationsRequest &request)
GlacierInitiateJobResponse * initiateJob (const GlacierInitiateJobRequest &request)
GlacierInitiateMultipartUploadResponse * initiateMultipartUpload (const GlacierInitiateMultipartUploadRequest &request)
GlacierInitiateVaultLockResponse * initiateVaultLock (const GlacierInitiateVaultLockRequest &request)
GlacierListJobsResponse * listJobs (const GlacierListJobsRequest &request)
GlacierListMultipartUploadsResponse * listMultipartUploads (const GlacierListMultipartUploadsRequest &request)
GlacierListPartsResponse * listParts (const GlacierListPartsRequest &request)
GlacierListTagsForVaultResponse * listTagsForVault (const GlacierListTagsForVaultRequest &request)
GlacierListVaultsResponse * listVaults (const GlacierListVaultsRequest &request)
GlacierRemoveTagsFromVaultResponse * removeTagsFromVault (const GlacierRemoveTagsFromVaultRequest &request)
GlacierSetDataRetrievalPolicyResponse * setDataRetrievalPolicy (const GlacierSetDataRetrievalPolicyRequest &request)
GlacierSetVaultAccessPolicyResponse * setVaultAccessPolicy (const GlacierSetVaultAccessPolicyRequest &request)
GlacierSetVaultNotificationsResponse * setVaultNotifications (const GlacierSetVaultNotificationsRequest &request)
GlacierUploadArchiveResponse * uploadArchive (const GlacierUploadArchiveRequest &request)
GlacierUploadMultipartPartResponse * uploadMultipartPart (const GlacierUploadMultipartPartRequest &request)
Public Member Functions
GlacierClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new GlacierClient object.
GlacierClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new GlacierClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Glacier.
Amazon Glacier is a storage solution for "cold data."
Amazon Glacier is an extremely low-cost storage service that provides secure, durable, and easy-to-use storage for data backup and archival. With Amazon Glacier, customers can store their data cost effectively for months, years, or decades. Amazon Glacier also enables customers to offload the administrative burdens of operating and scaling storage to AWS, so they don't have to worry about capacity planning, hardware provisioning, data replication, hardware failure and recovery, or time-consuming hardware migrations.
Amazon Glacier is a great storage choice when low storage cost is paramount, your data is rarely retrieved, and retrieval latency of several hours is acceptable. If your application requires fast or frequent access to your data, consider using Amazon S3. For more information, go to Amazon Simple Storage Service (Amazon S3).
You can store any kind of data in any format. There is no maximum limit on the total amount of data you can store in Amazon Glacier.
If you are a first-time user of Amazon Glacier, we recommend that you begin by reading the following sections in the Amazon Glacier Developer Guide:
What is Amazon Glacier - This section of the Developer Guide describes the underlying data model, the operations it supports, and the AWS SDKs that you can use to interact with the service.
Getting Started with Amazon Glacier - The Getting Started section walks you through the process of creating a vault, uploading archives, creating jobs to download archives, retrieving the job output, and deleting archives.
Definition at line 33 of file glacierclient.h.
Constructor & Destructor Documentation
GlacierClient::GlacierClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new GlacierClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 64 of file glacierclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new GlacierClientPrivate(this), parent)
 {
     Q_D(GlacierClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
GlacierClient::GlacierClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new GlacierClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 94 of file glacierclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new GlacierClientPrivate(this), parent)
 {
     Q_D(GlacierClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
glacier/glacierclient.h
glacier/glacierclient.cpp