libqtaws: AWS::CognitoIdentity::CognitoIdentityClient Class Reference
AWS::CognitoIdentity::CognitoIdentityClient Class Reference
Client for Amazon Cognito Identity.
Public Slots
CreateIdentityPoolResponse * createIdentityPool (const CreateIdentityPoolRequest &request)
DeleteIdentitiesResponse * deleteIdentities (const DeleteIdentitiesRequest &request)
DeleteIdentityPoolResponse * deleteIdentityPool (const DeleteIdentityPoolRequest &request)
DescribeIdentityResponse * describeIdentity (const DescribeIdentityRequest &request)
DescribeIdentityPoolResponse * describeIdentityPool (const DescribeIdentityPoolRequest &request)
GetCredentialsForIdentityResponse * getCredentialsForIdentity (const GetCredentialsForIdentityRequest &request)
GetIdResponse * getId (const GetIdRequest &request)
GetIdentityPoolRolesResponse * getIdentityPoolRoles (const GetIdentityPoolRolesRequest &request)
GetOpenIdTokenResponse * getOpenIdToken (const GetOpenIdTokenRequest &request)
GetOpenIdTokenForDeveloperIdentityResponse * getOpenIdTokenForDeveloperIdentity (const GetOpenIdTokenForDeveloperIdentityRequest &request)
ListIdentitiesResponse * listIdentities (const ListIdentitiesRequest &request)
ListIdentityPoolsResponse * listIdentityPools (const ListIdentityPoolsRequest &request)
LookupDeveloperIdentityResponse * lookupDeveloperIdentity (const LookupDeveloperIdentityRequest &request)
MergeDeveloperIdentitiesResponse * mergeDeveloperIdentities (const MergeDeveloperIdentitiesRequest &request)
SetIdentityPoolRolesResponse * setIdentityPoolRoles (const SetIdentityPoolRolesRequest &request)
UnlinkDeveloperIdentityResponse * unlinkDeveloperIdentity (const UnlinkDeveloperIdentityRequest &request)
UnlinkIdentityResponse * unlinkIdentity (const UnlinkIdentityRequest &request)
UpdateIdentityPoolResponse * updateIdentityPool (const UpdateIdentityPoolRequest &request)
Public Member Functions
CognitoIdentityClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CognitoIdentityClient object.
CognitoIdentityClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CognitoIdentityClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Cognito Identity.
<fullname>Amazon Cognito</fullname>
Amazon Cognito is a web service that delivers scoped temporary credentials to mobile devices and other untrusted environments. Amazon Cognito uniquely identifies a device and supplies the user with a consistent identity over the lifetime of an
application>
Using Amazon Cognito, you can enable authentication with one or more third-party identity providers (Facebook, Google, or Login with Amazon), and you can also choose to support unauthenticated access from your app. Cognito delivers a unique identifier for each user and acts as an OpenID token provider trusted by AWS Security Token Service (STS) to access temporary, limited-privilege AWS
credentials>
To provide end-user credentials, first make an unsigned call to GetId. If the end user is authenticated with one of the supported identity providers, set the Logins map with the identity provider token. GetId returns a unique identifier for the
user>
Next, make an unsigned call to GetCredentialsForIdentity. This call expects the same Logins map as the GetId call, as well as the IdentityID originally returned by GetId. Assuming your identity pool has been configured via the SetIdentityPoolRoles operation, GetCredentialsForIdentity will return AWS credentials for your use. If your pool has not been configured with SetIdentityPoolRoles, or if you want to follow legacy flow, make an unsigned call to GetOpenIdToken, which returns the OpenID token necessary to call STS and retrieve AWS credentials. This call expects the same Logins map as the GetId call, as well as the IdentityID originally returned by GetId. The token returned by GetOpenIdToken can be passed to the STS operation AssumeRoleWithWebIdentity to retrieve AWS
credentials>
If you want to use Amazon Cognito in an Android, iOS, or Unity application, you will probably want to make API calls via the AWS Mobile SDK. To learn more, see the AWS Mobile SDK Developer
Definition at line 36 of file cognitoidentityclient.h.
Constructor & Destructor Documentation
CognitoIdentityClient() [1/2]
AWS::CognitoIdentity::CognitoIdentityClient::CognitoIdentityClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CognitoIdentityClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 84 of file cognitoidentityclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new CognitoIdentityClientPrivate(this), parent)
 {
     Q_D(CognitoIdentityClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
CognitoIdentityClient() [2/2]
AWS::CognitoIdentity::CognitoIdentityClient::CognitoIdentityClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CognitoIdentityClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 114 of file cognitoidentityclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new CognitoIdentityClientPrivate(this), parent)
 {
     Q_D(CognitoIdentityClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
cognito-identity/cognitoidentityclient.h
cognito-identity/cognitoidentityclient.cpp