libqtaws: AWS::ElasticLoadBalancing::ElasticLoadBalancingClient Class Reference
AWS::ElasticLoadBalancing::ElasticLoadBalancingClient Class Reference
Client for Elastic Load Balancing.
Public Slots
AddTagsResponse * addTags (const AddTagsRequest &request)
ApplySecurityGroupsToLoadBalancerResponse * applySecurityGroupsToLoadBalancer (const ApplySecurityGroupsToLoadBalancerRequest &request)
AttachLoadBalancerToSubnetsResponse * attachLoadBalancerToSubnets (const AttachLoadBalancerToSubnetsRequest &request)
ConfigureHealthCheckResponse * configureHealthCheck (const ConfigureHealthCheckRequest &request)
CreateAppCookieStickinessPolicyResponse * createAppCookieStickinessPolicy (const CreateAppCookieStickinessPolicyRequest &request)
CreateLBCookieStickinessPolicyResponse * createLBCookieStickinessPolicy (const CreateLBCookieStickinessPolicyRequest &request)
CreateLoadBalancerResponse * createLoadBalancer (const CreateLoadBalancerRequest &request)
CreateLoadBalancerListenersResponse * createLoadBalancerListeners (const CreateLoadBalancerListenersRequest &request)
CreateLoadBalancerPolicyResponse * createLoadBalancerPolicy (const CreateLoadBalancerPolicyRequest &request)
DeleteLoadBalancerResponse * deleteLoadBalancer (const DeleteLoadBalancerRequest &request)
DeleteLoadBalancerListenersResponse * deleteLoadBalancerListeners (const DeleteLoadBalancerListenersRequest &request)
DeleteLoadBalancerPolicyResponse * deleteLoadBalancerPolicy (const DeleteLoadBalancerPolicyRequest &request)
DeregisterInstancesFromLoadBalancerResponse * deregisterInstancesFromLoadBalancer (const DeregisterInstancesFromLoadBalancerRequest &request)
DescribeAccountLimitsResponse * describeAccountLimits (const DescribeAccountLimitsRequest &request)
DescribeInstanceHealthResponse * describeInstanceHealth (const DescribeInstanceHealthRequest &request)
DescribeLoadBalancerAttributesResponse * describeLoadBalancerAttributes (const DescribeLoadBalancerAttributesRequest &request)
DescribeLoadBalancerPoliciesResponse * describeLoadBalancerPolicies (const DescribeLoadBalancerPoliciesRequest &request)
DescribeLoadBalancerPolicyTypesResponse * describeLoadBalancerPolicyTypes (const DescribeLoadBalancerPolicyTypesRequest &request)
DescribeLoadBalancersResponse * describeLoadBalancers (const DescribeLoadBalancersRequest &request)
DescribeTagsResponse * describeTags (const DescribeTagsRequest &request)
DetachLoadBalancerFromSubnetsResponse * detachLoadBalancerFromSubnets (const DetachLoadBalancerFromSubnetsRequest &request)
DisableAvailabilityZonesForLoadBalancerResponse * disableAvailabilityZonesForLoadBalancer (const DisableAvailabilityZonesForLoadBalancerRequest &request)
EnableAvailabilityZonesForLoadBalancerResponse * enableAvailabilityZonesForLoadBalancer (const EnableAvailabilityZonesForLoadBalancerRequest &request)
ModifyLoadBalancerAttributesResponse * modifyLoadBalancerAttributes (const ModifyLoadBalancerAttributesRequest &request)
RegisterInstancesWithLoadBalancerResponse * registerInstancesWithLoadBalancer (const RegisterInstancesWithLoadBalancerRequest &request)
RemoveTagsResponse * removeTags (const RemoveTagsRequest &request)
SetLoadBalancerListenerSSLCertificateResponse * setLoadBalancerListenerSSLCertificate (const SetLoadBalancerListenerSSLCertificateRequest &request)
SetLoadBalancerPoliciesForBackendServerResponse * setLoadBalancerPoliciesForBackendServer (const SetLoadBalancerPoliciesForBackendServerRequest &request)
SetLoadBalancerPoliciesOfListenerResponse * setLoadBalancerPoliciesOfListener (const SetLoadBalancerPoliciesOfListenerRequest &request)
Public Member Functions
ElasticLoadBalancingClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticLoadBalancingClient object.
ElasticLoadBalancingClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticLoadBalancingClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Elastic Load Balancing.
<fullname>Elastic Load Balancing</fullname>
A load balancer can distribute incoming traffic across your EC2 instances. This enables you to increase the availability of your application. The load balancer also monitors the health of its registered instances and ensures that it routes traffic only to healthy instances. You configure your load balancer to accept incoming traffic by specifying one or more listeners, which are configured with a protocol and port number for connections from clients to the load balancer and a protocol and port number for connections from the load balancer to the
instances>
Elastic Load Balancing supports three types of load balancers: Application Load Balancers, Network Load Balancers, and Classic Load Balancers. You can select a load balancer based on your application needs. For more information, see the Elastic Load Balancing User Guide>
This reference covers the 2012-06-01 API, which supports Classic Load Balancers. The 2015-12-01 API supports Application Load Balancers and Network Load
Balancers>
To get started, create a load balancer with one or more listeners using CreateLoadBalancer. Register your instances with the load balancer using
RegisterInstancesWithLoadBalancer>
All Elastic Load Balancing operations are idempotent, which means that they complete at most one time. If you repeat an operation, it succeeds with a 200 OK response
Definition at line 36 of file elasticloadbalancingclient.h.
Constructor & Destructor Documentation
ElasticLoadBalancingClient() [1/2]
AWS::ElasticLoadBalancing::ElasticLoadBalancingClient::ElasticLoadBalancingClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticLoadBalancingClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 74 of file elasticloadbalancingclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new ElasticLoadBalancingClientPrivate(this), parent)
 {
     Q_D(ElasticLoadBalancingClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
ElasticLoadBalancingClient() [2/2]
AWS::ElasticLoadBalancing::ElasticLoadBalancingClient::ElasticLoadBalancingClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticLoadBalancingClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 104 of file elasticloadbalancingclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new ElasticLoadBalancingClientPrivate(this), parent)
 {
     Q_D(ElasticLoadBalancingClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
elasticloadbalancing/elasticloadbalancingclient.h
elasticloadbalancing/elasticloadbalancingclient.cpp