libqtaws: ConfigServiceClient Class Reference
ConfigServiceClient Class Reference
Client for AWS Config (Config Service)
Public Slots
ConfigServiceDeleteConfigRuleResponse * deleteConfigRule (const ConfigServiceDeleteConfigRuleRequest &request)
ConfigServiceDeleteConfigurationRecorderResponse * deleteConfigurationRecorder (const ConfigServiceDeleteConfigurationRecorderRequest &request)
ConfigServiceDeleteDeliveryChannelResponse * deleteDeliveryChannel (const ConfigServiceDeleteDeliveryChannelRequest &request)
ConfigServiceDeleteEvaluationResultsResponse * deleteEvaluationResults (const ConfigServiceDeleteEvaluationResultsRequest &request)
ConfigServiceDeliverConfigSnapshotResponse * deliverConfigSnapshot (const ConfigServiceDeliverConfigSnapshotRequest &request)
ConfigServiceDescribeComplianceByConfigRuleResponse * describeComplianceByConfigRule (const ConfigServiceDescribeComplianceByConfigRuleRequest &request)
ConfigServiceDescribeComplianceByResourceResponse * describeComplianceByResource (const ConfigServiceDescribeComplianceByResourceRequest &request)
ConfigServiceDescribeConfigRuleEvaluationStatusResponse * describeConfigRuleEvaluationStatus (const ConfigServiceDescribeConfigRuleEvaluationStatusRequest &request)
ConfigServiceDescribeConfigRulesResponse * describeConfigRules (const ConfigServiceDescribeConfigRulesRequest &request)
ConfigServiceDescribeConfigurationRecorderStatusResponse * describeConfigurationRecorderStatus (const ConfigServiceDescribeConfigurationRecorderStatusRequest &request)
ConfigServiceDescribeConfigurationRecordersResponse * describeConfigurationRecorders (const ConfigServiceDescribeConfigurationRecordersRequest &request)
ConfigServiceDescribeDeliveryChannelStatusResponse * describeDeliveryChannelStatus (const ConfigServiceDescribeDeliveryChannelStatusRequest &request)
ConfigServiceDescribeDeliveryChannelsResponse * describeDeliveryChannels (const ConfigServiceDescribeDeliveryChannelsRequest &request)
ConfigServiceGetComplianceDetailsByConfigRuleResponse * getComplianceDetailsByConfigRule (const ConfigServiceGetComplianceDetailsByConfigRuleRequest &request)
ConfigServiceGetComplianceDetailsByResourceResponse * getComplianceDetailsByResource (const ConfigServiceGetComplianceDetailsByResourceRequest &request)
ConfigServiceGetComplianceSummaryByConfigRuleResponse * getComplianceSummaryByConfigRule ()
ConfigServiceGetComplianceSummaryByResourceTypeResponse * getComplianceSummaryByResourceType (const ConfigServiceGetComplianceSummaryByResourceTypeRequest &request)
ConfigServiceGetResourceConfigHistoryResponse * getResourceConfigHistory (const ConfigServiceGetResourceConfigHistoryRequest &request)
ConfigServiceListDiscoveredResourcesResponse * listDiscoveredResources (const ConfigServiceListDiscoveredResourcesRequest &request)
ConfigServicePutConfigRuleResponse * putConfigRule (const ConfigServicePutConfigRuleRequest &request)
ConfigServicePutConfigurationRecorderResponse * putConfigurationRecorder (const ConfigServicePutConfigurationRecorderRequest &request)
ConfigServicePutDeliveryChannelResponse * putDeliveryChannel (const ConfigServicePutDeliveryChannelRequest &request)
ConfigServicePutEvaluationsResponse * putEvaluations (const ConfigServicePutEvaluationsRequest &request)
ConfigServiceStartConfigRulesEvaluationResponse * startConfigRulesEvaluation (const ConfigServiceStartConfigRulesEvaluationRequest &request)
ConfigServiceStartConfigurationRecorderResponse * startConfigurationRecorder (const ConfigServiceStartConfigurationRecorderRequest &request)
ConfigServiceStopConfigurationRecorderResponse * stopConfigurationRecorder (const ConfigServiceStopConfigurationRecorderRequest &request)
Public Member Functions
ConfigServiceClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ConfigServiceClient object.
ConfigServiceClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ConfigServiceClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Config (Config Service)
<fullname>AWS Config</fullname>
AWS Config provides a way to keep track of the configurations of all the AWS resources associated with your AWS account. You can use AWS Config to get the current and historical configurations of each AWS resource and also to get information about the relationship between the resources. An AWS resource can be an Amazon Compute Cloud (Amazon EC2) instance, an Elastic Block Store (EBS) volume, an Elastic network Interface (ENI), or a security group. For a complete list of resources currently supported by AWS Config, see Supported AWS Resources.
You can access and manage AWS Config through the AWS Management Console, the AWS Command Line Interface (AWS CLI), the AWS Config API, or the AWS SDKs for AWS Config
This reference guide contains documentation for the AWS Config API and the AWS CLI commands that you can use to manage AWS Config.
The AWS Config API uses the Signature Version 4 protocol for signing requests. For more information about how to sign a request with this protocol, see Signature Version 4 Signing Process.
For detailed information about AWS Config features and their associated actions or commands, as well as how to work with AWS Management Console, see What Is AWS Config? in the AWS Config Developer Guide.
Definition at line 33 of file configserviceclient.h.
Constructor & Destructor Documentation
ConfigServiceClient::ConfigServiceClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ConfigServiceClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 56 of file configserviceclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new ConfigServiceClientPrivate(this), parent)
 {
     Q_D(ConfigServiceClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
ConfigServiceClient::ConfigServiceClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ConfigServiceClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 86 of file configserviceclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new ConfigServiceClientPrivate(this), parent)
 {
     Q_D(ConfigServiceClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
config/configserviceclient.h
config/configserviceclient.cpp