libqtaws: SqsResponse Class Reference
SqsResponse Class Reference
Interface class for processing SQS responses.
Public Member Functions
SqsResponse (QObject *const parent=0)
Constructs a new SqsResponse object.
virtual QString errorString () const
Get this response's error string.
virtual bool hasError () const
Did any error occurr processing this reponse?
virtual bool isValid () const
Is this AWS response valid?
QString requestId () const
Get the SQS request ID, if any, included in the SQS response.
SqsErrorList serviceErrors () const
Get list of SQS errors, if any, included in the SQS response.
Public Member Functions inherited from AwsAbstractResponse
AwsAbstractResponse (QObject *const parent=0)
Constructs a new AwsAbstractResponse object.
virtual ~AwsAbstractResponse ()
AwsAbstractResponse destructor.
virtual QNetworkReply::NetworkError networkError () const
Get this response's network error, if there is one.
virtual QXmlStreamReader::Error xmlParseError () const
Get this response's XML parse error, if there is one.
virtual QString xmlParseErrorString () const
Get this response's XML parse error string, if there is one.
virtual const AwsAbstractRequest * request () const =0
Get this response's originating AWS request.
Protected Slots
virtual void parseFailure (QIODevice &response)
Parse a failure response.
Protected Slots inherited from AwsAbstractResponse
virtual void replyFinished ()
Slot to be invoked when the internal network reply is finished.
Protected Member Functions
SqsResponse (SqsResponsePrivate *const d, QObject *const parent)
Constructs a new SqsResponse object.
Protected Member Functions inherited from AwsAbstractResponse
AwsAbstractResponse (AwsAbstractResponsePrivate *const d, QObject *const parent)
Constructs a new AwsAbstractResponse object.
virtual bool isSuccess (QNetworkReply *const reply) const
Does a network reply indicate a successful response?
void setReply (QNetworkReply *reply)
Set the network reply from which to expect an AWS response.
void setRequest (const AwsAbstractRequest *const request)
Set this response's originating AWS request.
void setXmlError (const QXmlStreamReader &xml)
Record the details of an XML parse error.
virtual void parse (QNetworkReply *const reply)
Parse an AWS response from a network reply.
virtual void parseFailure (QIODevice &response)=0
Parse a failure response.
virtual void parseSuccess (QIODevice &response)=0
Parse a successful response.
Friends
class TestSqsResponse
Additional Inherited Members
Signals inherited from AwsAbstractResponse
void finished ()
Signal emitted when this object has finished parsing the response.
Static Public Member Functions inherited from AwsAbstractResponse
static QVariantMap toVariant (QXmlStreamReader &xml, const QString &prefix=QLatin1String("."), const int maxDepth=1024)
Convert an XML stream to a hierarchical QVariantMap.
Protected Attributes inherited from AwsAbstractResponse
AwsAbstractResponsePrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for processing SQS responses.
Definition at line 33 of file sqsresponse.h.
Constructor & Destructor Documentation
SqsResponse() [1/2]
SqsResponse::SqsResponse (QObject *const parent = 0)
Constructs a new SqsResponse object.
Parameters
parent This object's parent.
Definition at line 40 of file sqsresponse.cpp.
     : AwsAbstractResponse(new SqsResponsePrivate(this), parent)
 {
 }
SqsResponse() [2/2]
SqsResponse::SqsResponse (SqsResponsePrivate *const d, QObject *const parent) protected
Constructs a new SqsResponse object.
This overload allows derived classes to provide their own private class implementation that inherits from SqsRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
parent This object's parent.
Definition at line 58 of file sqsresponse.cpp.
     : AwsAbstractResponse(d, parent)
 {
 }
Member Function Documentation
errorString()
QString SqsResponse::errorString () const virtual
Get this response's error string.
This override checks for SQS service errors, and if found, returns the first one. Otherwise, this override delegates to the base implementation (which checks for network and XML parse errors, for example).
Also consider using the serviceErrors function to retrieve all of the servive errors (if any), not just the first one (though often SQS will only return one error per response).
Returns
An error string, or a null QString if this response has no errors.
See also
AwsAbstractResponse::errorString
hasError
serviceErrors
Reimplemented from AwsAbstractResponse.
Definition at line 81 of file sqsresponse.cpp.
References AwsAbstractResponse::errorString().
 {
     Q_D(const SqsResponse);
     return (d->errors.empty()) ? AwsAbstractResponse::errorString() : d->errors.first().message();
 }
hasError()
bool SqsResponse::hasError () const virtual
Did any error occurr processing this reponse?
Errors could be anything from network requests errors, to errors validating AWS response content.
This base implementation supports network, and XML parsing errors. Derived classes may override this function to support additional error types.
Returns
true if this response contains one or more errors, false otherwise.
Note
This function may be equivalent to !isValid, however, it is not safe for this function's implementation to be just that, since derived classes may assume the inverse, resulting in an infinite cycle between the two functions.
See also
errorString
isValid
Reimplemented from AwsAbstractResponse.
Definition at line 87 of file sqsresponse.cpp.
References AwsAbstractResponse::hasError(), and serviceErrors().
 {
     return ((!serviceErrors().isEmpty()) || (AwsAbstractResponse::hasError()));
 }
isValid()
bool SqsResponse::isValid () const virtual
Is this AWS response valid?
This base implementation simply checks for the absense of network and XML parsing errors. Derived classes may override this function to check other error types, and/or apply additional validation rules.
Returns
true if this response is considered valid, false otherwise.
Note
This function may be equivalent to !hasError, however, it is not safe for this function's implementation to be just that, since derived classes may assume the inverse, resulting in an infinite cycle between the two functions.
See also
hasError
Reimplemented from AwsAbstractResponse.
Reimplemented in SqsChangeMessageVisibilityBatchResponse, SqsCreateQueueResponse, SqsDeleteMessageBatchResponse, SqsGetQueueAttributesResponse, SqsGetQueueUrlResponse, SqsListDeadLetterSourceQueuesResponse, SqsListQueuesResponse, SqsReceiveMessageResponse, SqsSendMessageBatchResponse, and SqsSendMessageResponse.
Definition at line 92 of file sqsresponse.cpp.
References AwsAbstractResponse::isValid(), and serviceErrors().
Referenced by SqsChangeMessageVisibilityBatchResponse::isValid(), SqsSendMessageResponse::isValid(), SqsSendMessageBatchResponse::isValid(), SqsReceiveMessageResponse::isValid(), SqsListQueuesResponse::isValid(), SqsListDeadLetterSourceQueuesResponse::isValid(), SqsGetQueueUrlResponse::isValid(), SqsGetQueueAttributesResponse::isValid(), SqsDeleteMessageBatchResponse::isValid(), and SqsCreateQueueResponse::isValid().
 {
     return ((serviceErrors().isEmpty()) && (AwsAbstractResponse::isValid()));
 }
parseFailure
void SqsResponse::parseFailure (QIODevice & response) protected virtual slot
Parse a failure response.
This implementation parses SQS ErrorResponse elements, as defined by http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
For example:
<ErrorResponse>
  <Error>
    <Type>Sender</Type>
    <Code>AccessDenied</Code>
    <Message>Access to the resource http://sqs.us-east-1.amazonaws.com/ is denied.</Message>
    <Detail/>
  </Error>
  <Error>
    ...
  </Error>
  <RequestId>9a285199-c8d6-47c2-bdb2-314cb47d599d</RequestId>
</ErrorResponse>
Parameters
response Response to parse.
Note
Unlike most other SQS responses, the SQS ErrorResponse does not wrap the RequestId element in a ResponseMetadata element.
See also
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Definition at line 150 of file sqsresponse.cpp.
References AwsAbstractResponse::setXmlError().
 {
     Q_D(SqsResponse);
     QXmlStreamReader xml(&response);
     if (xml.readNextStartElement()) {
         if (xml.name() == QLatin1String("ErrorResponse")) {
             d->parseErrorResponse(xml);
         } else {
             qWarning() << "ignoring" << xml.name();
             xml.skipCurrentElement();
         }
     }
     setXmlError(xml);
 }
requestId()
QString SqsResponse::requestId () const
Get the SQS request ID, if any, included in the SQS response.
Returns
SQS request ID, or a null QString if not found.
Definition at line 102 of file sqsresponse.cpp.
 {
     Q_D(const SqsResponse);
     return d->requestId;
 }
serviceErrors()
SqsErrorList SqsResponse::serviceErrors () const
Get list of SQS errors, if any, included in the SQS response.
Returns
A (possinly empty) list of SQS errors found in the SQS reponse.
See also
errorString
Definition at line 115 of file sqsresponse.cpp.
Referenced by hasError(), and isValid().
 {
     Q_D(const SqsResponse);
     return d->errors;
 }
The documentation for this class was generated from the following files:
sqs/sqsresponse.h
sqs/sqsresponse.cpp