libqtaws: AwsBasicCredentials Class Reference
AwsBasicCredentials Class Reference
Basic non-refreshable implementation of AwsAbstractCredentials.
Public Slots
virtual void setAccessKeyId (const QString &accessKeyId)
Set the AWS access key ID for this credentials object.
virtual void setSecretKey (const QString &secretKey)
Set the AWS secret access key for this credentials object.
virtual void setToken (const QString &token)
Set the AWS security token for this credentials object.
Public Slots inherited from AwsAbstractCredentials
virtual bool refresh ()
Refresh this object's credentials.
Public Member Functions
AwsBasicCredentials (const QString &accessKeyid, const QString &secretKey, const QString &token, QObject *const parent=0)
Constructs a new AwsBasicCredentials object.
AwsBasicCredentials (const QString &accessKeyid, const QString &secretKey, QObject *const parent=0)
Constructs a new AwsBasicCredentials object.
virtual QString accessKeyId () const
AWS access key ID for this credentials object.
virtual QString secretKey () const
AWS secret access key for this credentials object.
virtual QString token () const
AWS security token for this credentials object.
Public Member Functions inherited from AwsAbstractCredentials
AwsAbstractCredentials (QObject *const parent=0)
Construct an AwsAbstractCredentials object.
virtual ~AwsAbstractCredentials ()
AwsAbstractCredentials destructor.
virtual QDateTime expiration () const
DateTime at which the credentials will expire.
virtual bool isExpired () const
Is this credentials object currently expired.
virtual bool isRefreshable () const
Is this credentials object refreshable.
Additional Inherited Members
Signals inherited from AwsAbstractCredentials
void changed ()
Signal emitted when this object's credentials have been updated.
Protected Member Functions inherited from AwsAbstractCredentials
AwsAbstractCredentials (AwsAbstractCredentialsPrivate *const d, QObject *const parent)
Construct an AwsAbstractCredentials object.
Protected Attributes inherited from AwsAbstractCredentials
AwsAbstractCredentialsPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Basic non-refreshable implementation of AwsAbstractCredentials.
Definition at line 29 of file awsbasiccredentials.h.
Constructor & Destructor Documentation
AwsBasicCredentials() [1/2]
AwsBasicCredentials::AwsBasicCredentials (const QString & accessKeyId, const QString & secretKey, const QString & token, QObject *const parent = 0)
Constructs a new AwsBasicCredentials object.
Constructs a new AwsBasicCredentials object, with the specified AWS access key, AWS secret key, and AWS security token.
Parameters
accessKeyId The AWS access key ID to use for this credentials object.
secretKey The AWS secret access key to use for this credentials object.
token The AWS security token to use for this credentials object.
parent This object's parent.
Definition at line 42 of file awsbasiccredentials.cpp.
References accessKeyId(), secretKey(), and token().
     : AwsAbstractCredentials(new AwsBasicCredentialsPrivate(this), parent)
 {
     Q_D(AwsBasicCredentials);
     d->accessKeyId = accessKeyId;
     d->secretKey = secretKey;
     d->token = token;
 }
AwsBasicCredentials() [2/2]
AwsBasicCredentials::AwsBasicCredentials (const QString & accessKeyId, const QString & secretKey, QObject *const parent = 0)
Constructs a new AwsBasicCredentials object.
Constructs a new AwsBasicCredentials object, with the specified AWS access key and AWS secret key. The object's security token will be left as null string, unless set later via setToken().
Parameters
accessKeyId The AWS access key ID to use for this credentials object.
secretKey The AWS secret access key to use for this credentials object.
parent This object's parent.
Definition at line 65 of file awsbasiccredentials.cpp.
References accessKeyId(), and secretKey().
     : AwsAbstractCredentials(new AwsBasicCredentialsPrivate(this), parent)
 {
     Q_D(AwsBasicCredentials);
     d->accessKeyId = accessKeyId;
     d->secretKey = secretKey;
 }
Member Function Documentation
accessKeyId()
QString AwsBasicCredentials::accessKeyId () const virtual
AWS access key ID for this credentials object.
Returns
The AWS access key ID for this credentials object.
Implements AwsAbstractCredentials.
Definition at line 76 of file awsbasiccredentials.cpp.
Referenced by AwsBasicCredentials(), and setAccessKeyId().
 {
     Q_D(const AwsBasicCredentials);
     return d->accessKeyId;
 }
secretKey()
QString AwsBasicCredentials::secretKey () const virtual
AWS secret access key for this credentials object.
Returns
The AWS secret access key for this credentials object.
Implements AwsAbstractCredentials.
Definition at line 82 of file awsbasiccredentials.cpp.
Referenced by AwsBasicCredentials(), and setSecretKey().
 {
     Q_D(const AwsBasicCredentials);
     return d->secretKey;
 }
setAccessKeyId
void AwsBasicCredentials::setAccessKeyId (const QString & accessKeyId) virtual slot
Set the AWS access key ID for this credentials object.
Parameters
accessKeyId The AWS access key ID to set for this credentials object.
Definition at line 99 of file awsbasiccredentials.cpp.
References accessKeyId(), and AwsAbstractCredentials::changed().
 {
     Q_D(AwsBasicCredentials);
     d->accessKeyId = accessKeyId;
     emit changed();
 }
setSecretKey
void AwsBasicCredentials::setSecretKey (const QString & secretKey) virtual slot
Set the AWS secret access key for this credentials object.
Parameters
secretKey The AWS secret access key to set for this credentials object.
Definition at line 111 of file awsbasiccredentials.cpp.
References AwsAbstractCredentials::changed(), and secretKey().
 {
     Q_D(AwsBasicCredentials);
     d->secretKey = secretKey;
     emit changed();
 }
setToken
void AwsBasicCredentials::setToken (const QString & token) virtual slot
Set the AWS security token for this credentials object.
Parameters
token The AWS security token to set for this credentials object.
Definition at line 123 of file awsbasiccredentials.cpp.
References AwsAbstractCredentials::changed(), and token().
 {
     Q_D(AwsBasicCredentials);
     d->token = token;
     emit changed();
 }
token()
QString AwsBasicCredentials::token () const virtual
AWS security token for this credentials object.
Returns
The AWS security token for this credentials object.
Implements AwsAbstractCredentials.
Definition at line 88 of file awsbasiccredentials.cpp.
Referenced by AwsBasicCredentials(), and setToken().
 {
     Q_D(const AwsBasicCredentials);
     return d->token;
 }
The documentation for this class was generated from the following files:
core/awsbasiccredentials.h
core/awsbasiccredentials.cpp