libqtaws: AWS::DirectoryService::DirectoryServiceClient Class Reference
AWS::DirectoryService::DirectoryServiceClient Class Reference
Client for AWS Directory Service.
Public Slots
AddIpRoutesResponse * addIpRoutes (const AddIpRoutesRequest &request)
AddTagsToResourceResponse * addTagsToResource (const AddTagsToResourceRequest &request)
CancelSchemaExtensionResponse * cancelSchemaExtension (const CancelSchemaExtensionRequest &request)
ConnectDirectoryResponse * connectDirectory (const ConnectDirectoryRequest &request)
CreateAliasResponse * createAlias (const CreateAliasRequest &request)
CreateComputerResponse * createComputer (const CreateComputerRequest &request)
CreateConditionalForwarderResponse * createConditionalForwarder (const CreateConditionalForwarderRequest &request)
CreateDirectoryResponse * createDirectory (const CreateDirectoryRequest &request)
CreateMicrosoftADResponse * createMicrosoftAD (const CreateMicrosoftADRequest &request)
CreateSnapshotResponse * createSnapshot (const CreateSnapshotRequest &request)
CreateTrustResponse * createTrust (const CreateTrustRequest &request)
DeleteConditionalForwarderResponse * deleteConditionalForwarder (const DeleteConditionalForwarderRequest &request)
DeleteDirectoryResponse * deleteDirectory (const DeleteDirectoryRequest &request)
DeleteSnapshotResponse * deleteSnapshot (const DeleteSnapshotRequest &request)
DeleteTrustResponse * deleteTrust (const DeleteTrustRequest &request)
DeregisterEventTopicResponse * deregisterEventTopic (const DeregisterEventTopicRequest &request)
DescribeConditionalForwardersResponse * describeConditionalForwarders (const DescribeConditionalForwardersRequest &request)
DescribeDirectoriesResponse * describeDirectories (const DescribeDirectoriesRequest &request)
DescribeDomainControllersResponse * describeDomainControllers (const DescribeDomainControllersRequest &request)
DescribeEventTopicsResponse * describeEventTopics (const DescribeEventTopicsRequest &request)
DescribeSnapshotsResponse * describeSnapshots (const DescribeSnapshotsRequest &request)
DescribeTrustsResponse * describeTrusts (const DescribeTrustsRequest &request)
DisableRadiusResponse * disableRadius (const DisableRadiusRequest &request)
DisableSsoResponse * disableSso (const DisableSsoRequest &request)
EnableRadiusResponse * enableRadius (const EnableRadiusRequest &request)
EnableSsoResponse * enableSso (const EnableSsoRequest &request)
GetDirectoryLimitsResponse * getDirectoryLimits (const GetDirectoryLimitsRequest &request)
GetSnapshotLimitsResponse * getSnapshotLimits (const GetSnapshotLimitsRequest &request)
ListIpRoutesResponse * listIpRoutes (const ListIpRoutesRequest &request)
ListSchemaExtensionsResponse * listSchemaExtensions (const ListSchemaExtensionsRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
RegisterEventTopicResponse * registerEventTopic (const RegisterEventTopicRequest &request)
RemoveIpRoutesResponse * removeIpRoutes (const RemoveIpRoutesRequest &request)
RemoveTagsFromResourceResponse * removeTagsFromResource (const RemoveTagsFromResourceRequest &request)
RestoreFromSnapshotResponse * restoreFromSnapshot (const RestoreFromSnapshotRequest &request)
StartSchemaExtensionResponse * startSchemaExtension (const StartSchemaExtensionRequest &request)
UpdateConditionalForwarderResponse * updateConditionalForwarder (const UpdateConditionalForwarderRequest &request)
UpdateNumberOfDomainControllersResponse * updateNumberOfDomainControllers (const UpdateNumberOfDomainControllersRequest &request)
UpdateRadiusResponse * updateRadius (const UpdateRadiusRequest &request)
VerifyTrustResponse * verifyTrust (const VerifyTrustRequest &request)
Public Member Functions
DirectoryServiceClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DirectoryServiceClient object.
DirectoryServiceClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DirectoryServiceClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Directory Service.
<fullname>AWS Directory Service</fullname>
AWS Directory Service is a web service that makes it easy for you to setup and run directories in the AWS cloud, or connect your AWS resources with an existing on-premises Microsoft Active Directory. This guide provides detailed information about AWS Directory Service operations, data types, parameters, and errors. For information about AWS Directory Services features, see AWS Directory Service and the AWS Directory Service Administration Guide> <note>
AWS provides SDKs that consist of libraries and sample code for various programming languages and platforms (Java, Ruby, .Net, iOS, Android, etc.). The SDKs provide a convenient way to create programmatic access to AWS Directory Service and other AWS services. For more information about the AWS SDKs, including how to download and install them, see Tools for Amazon Web
Definition at line 36 of file directoryserviceclient.h.
Constructor & Destructor Documentation
DirectoryServiceClient() [1/2]
AWS::DirectoryService::DirectoryServiceClient::DirectoryServiceClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DirectoryServiceClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 60 of file directoryserviceclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new DirectoryServiceClientPrivate(this), parent)
 {
     Q_D(DirectoryServiceClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
DirectoryServiceClient() [2/2]
AWS::DirectoryService::DirectoryServiceClient::DirectoryServiceClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DirectoryServiceClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 90 of file directoryserviceclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new DirectoryServiceClientPrivate(this), parent)
 {
     Q_D(DirectoryServiceClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
ds/directoryserviceclient.h
ds/directoryserviceclient.cpp