libqtaws: CodePipelineClient Class Reference
CodePipelineClient Class Reference
Public Member Functions
CodePipelineClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodePipelineClient object.
CodePipelineClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodePipelineClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
<fullname>AWS CodePipeline</fullname>
Overview
This is the AWS CodePipeline API Reference. This guide provides descriptions of the actions and data types for AWS CodePipeline. Some functionality for your pipeline is only configurable through the API. For additional information, see the AWS CodePipeline User Guide.
You can use the AWS CodePipeline API to work with pipelines, stages, actions, gates, and transitions, as described below.
Pipelines are models of automated release processes. Each pipeline is uniquely named, and consists of actions, gates, and stages.
You can work with pipelines by calling:
CreatePipeline, which creates a uniquely-named pipeline.
DeletePipeline, which deletes the specified pipeline.
GetPipeline, which returns information about a pipeline structure.
GetPipelineExecution, which returns information about a specific execution of a pipeline.
GetPipelineState, which returns information about the current state of the stages and actions of a pipeline.
ListPipelines, which gets a summary of all of the pipelines associated with your account.
StartPipelineExecution, which runs the the most recent revision of an artifact through the pipeline.
UpdatePipeline, which updates a pipeline with edits or changes to the structure of the pipeline.
Pipelines include stages, which are which are logical groupings of gates and actions. Each stage contains one or more actions that must complete before the next stage begins. A stage will result in success or failure. If a stage fails, then the pipeline stops at that stage and will remain stopped until either a new version of an artifact appears in the source location, or a user takes action to re-run the most recent artifact through the pipeline. You can call GetPipelineState, which displays the status of a pipeline, including the status of stages in the pipeline, or GetPipeline, which returns the entire structure of the pipeline, including the stages of that pipeline. For more information about the structure of stages and actions, also refer to the AWS CodePipeline Pipeline Structure Reference.
Pipeline stages include actions, which are categorized into categories such as source or build actions performed within a stage of a pipeline. For example, you can use a source action to import artifacts into a pipeline from a source such as Amazon S3. Like stages, you do not work with actions directly in most cases, but you do define and interact with actions when working with pipeline operations such as CreatePipeline and GetPipelineState.
Pipelines also include transitions, which allow the transition of artifacts from one stage to the next in a pipeline after the actions in one stage complete.
You can work with transitions by calling:
DisableStageTransition, which prevents artifacts from transitioning to the next stage in a pipeline.
EnableStageTransition, which enables transition of artifacts between stages in a pipeline.
Using the API to integrate with AWS CodePipeline
For third-party integrators or developers who want to create their own integrations with AWS CodePipeline, the expected sequence varies from the standard API user. In order to integrate with AWS CodePipeline, developers will need to work with the following items:
Jobs, which are instances of an action. For example, a job for a source action might import a revision of an artifact from a source.
You can work with jobs by calling:
AcknowledgeJob, which confirms whether a job worker has received the specified job,
GetJobDetails, which returns the details of a job,
PollForJobs, which determines whether there are any jobs to act upon,
PutJobFailureResult, which provides details of a job failure, and
PutJobSuccessResult, which provides details of a job success.
Third party jobs, which are instances of an action created by a partner action and integrated into AWS CodePipeline. Partner actions are created by members of the AWS Partner Network.
You can work with third party jobs by calling:
AcknowledgeThirdPartyJob, which confirms whether a job worker has received the specified job,
GetThirdPartyJobDetails, which requests the details of a job for a partner action,
PollForThirdPartyJobs, which determines whether there are any jobs to act upon,
PutThirdPartyJobFailureResult, which provides details of a job failure, and
PutThirdPartyJobSuccessResult, which provides details of a job success.
Definition at line 33 of file codepipelineclient.h.
Constructor & Destructor Documentation
CodePipelineClient::CodePipelineClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodePipelineClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 44 of file codepipelineclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new CodePipelineClientPrivate(this), parent)
 {
     Q_D(CodePipelineClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
CodePipelineClient::CodePipelineClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodePipelineClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 74 of file codepipelineclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new CodePipelineClientPrivate(this), parent)
 {
     Q_D(CodePipelineClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
codepipeline/codepipelineclient.h
codepipeline/codepipelineclient.cpp