libqtaws: ElasticBeanstalkClient Class Reference
ElasticBeanstalkClient Class Reference
Client for AWS Elastic Beanstalk.
Public Slots
ElasticBeanstalkAbortEnvironmentUpdateResponse * abortEnvironmentUpdate (const ElasticBeanstalkAbortEnvironmentUpdateRequest &request)
ElasticBeanstalkApplyEnvironmentManagedActionResponse * applyEnvironmentManagedAction (const ElasticBeanstalkApplyEnvironmentManagedActionRequest &request)
ElasticBeanstalkCheckDNSAvailabilityResponse * checkDNSAvailability (const ElasticBeanstalkCheckDNSAvailabilityRequest &request)
ElasticBeanstalkComposeEnvironmentsResponse * composeEnvironments (const ElasticBeanstalkComposeEnvironmentsRequest &request)
ElasticBeanstalkCreateApplicationResponse * createApplication (const ElasticBeanstalkCreateApplicationRequest &request)
ElasticBeanstalkCreateApplicationVersionResponse * createApplicationVersion (const ElasticBeanstalkCreateApplicationVersionRequest &request)
ElasticBeanstalkCreateConfigurationTemplateResponse * createConfigurationTemplate (const ElasticBeanstalkCreateConfigurationTemplateRequest &request)
ElasticBeanstalkCreateEnvironmentResponse * createEnvironment (const ElasticBeanstalkCreateEnvironmentRequest &request)
ElasticBeanstalkCreateStorageLocationResponse * createStorageLocation ()
ElasticBeanstalkDeleteApplicationResponse * deleteApplication (const ElasticBeanstalkDeleteApplicationRequest &request)
ElasticBeanstalkDeleteApplicationVersionResponse * deleteApplicationVersion (const ElasticBeanstalkDeleteApplicationVersionRequest &request)
ElasticBeanstalkDeleteConfigurationTemplateResponse * deleteConfigurationTemplate (const ElasticBeanstalkDeleteConfigurationTemplateRequest &request)
ElasticBeanstalkDeleteEnvironmentConfigurationResponse * deleteEnvironmentConfiguration (const ElasticBeanstalkDeleteEnvironmentConfigurationRequest &request)
ElasticBeanstalkDescribeApplicationVersionsResponse * describeApplicationVersions (const ElasticBeanstalkDescribeApplicationVersionsRequest &request)
ElasticBeanstalkDescribeApplicationsResponse * describeApplications (const ElasticBeanstalkDescribeApplicationsRequest &request)
ElasticBeanstalkDescribeConfigurationOptionsResponse * describeConfigurationOptions (const ElasticBeanstalkDescribeConfigurationOptionsRequest &request)
ElasticBeanstalkDescribeConfigurationSettingsResponse * describeConfigurationSettings (const ElasticBeanstalkDescribeConfigurationSettingsRequest &request)
ElasticBeanstalkDescribeEnvironmentHealthResponse * describeEnvironmentHealth (const ElasticBeanstalkDescribeEnvironmentHealthRequest &request)
ElasticBeanstalkDescribeEnvironmentManagedActionHistoryResponse * describeEnvironmentManagedActionHistory (const ElasticBeanstalkDescribeEnvironmentManagedActionHistoryRequest &request)
ElasticBeanstalkDescribeEnvironmentManagedActionsResponse * describeEnvironmentManagedActions (const ElasticBeanstalkDescribeEnvironmentManagedActionsRequest &request)
ElasticBeanstalkDescribeEnvironmentResourcesResponse * describeEnvironmentResources (const ElasticBeanstalkDescribeEnvironmentResourcesRequest &request)
ElasticBeanstalkDescribeEnvironmentsResponse * describeEnvironments (const ElasticBeanstalkDescribeEnvironmentsRequest &request)
ElasticBeanstalkDescribeEventsResponse * describeEvents (const ElasticBeanstalkDescribeEventsRequest &request)
ElasticBeanstalkDescribeInstancesHealthResponse * describeInstancesHealth (const ElasticBeanstalkDescribeInstancesHealthRequest &request)
ElasticBeanstalkListAvailableSolutionStacksResponse * listAvailableSolutionStacks ()
ElasticBeanstalkRebuildEnvironmentResponse * rebuildEnvironment (const ElasticBeanstalkRebuildEnvironmentRequest &request)
ElasticBeanstalkRequestEnvironmentInfoResponse * requestEnvironmentInfo (const ElasticBeanstalkRequestEnvironmentInfoRequest &request)
ElasticBeanstalkRestartAppServerResponse * restartAppServer (const ElasticBeanstalkRestartAppServerRequest &request)
ElasticBeanstalkRetrieveEnvironmentInfoResponse * retrieveEnvironmentInfo (const ElasticBeanstalkRetrieveEnvironmentInfoRequest &request)
ElasticBeanstalkSwapEnvironmentCNAMEsResponse * swapEnvironmentCNAMEs (const ElasticBeanstalkSwapEnvironmentCNAMEsRequest &request)
ElasticBeanstalkTerminateEnvironmentResponse * terminateEnvironment (const ElasticBeanstalkTerminateEnvironmentRequest &request)
ElasticBeanstalkUpdateApplicationResponse * updateApplication (const ElasticBeanstalkUpdateApplicationRequest &request)
ElasticBeanstalkUpdateApplicationVersionResponse * updateApplicationVersion (const ElasticBeanstalkUpdateApplicationVersionRequest &request)
ElasticBeanstalkUpdateConfigurationTemplateResponse * updateConfigurationTemplate (const ElasticBeanstalkUpdateConfigurationTemplateRequest &request)
ElasticBeanstalkUpdateEnvironmentResponse * updateEnvironment (const ElasticBeanstalkUpdateEnvironmentRequest &request)
ElasticBeanstalkValidateConfigurationSettingsResponse * validateConfigurationSettings (const ElasticBeanstalkValidateConfigurationSettingsRequest &request)
Public Member Functions
ElasticBeanstalkClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticBeanstalkClient object.
ElasticBeanstalkClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticBeanstalkClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Elastic Beanstalk.
<fullname>AWS Elastic Beanstalk</fullname>
AWS Elastic Beanstalk makes it easy for you to create, deploy, and manage scalable, fault-tolerant applications running on the Amazon Web Services cloud.
For more information about this product, go to the AWS Elastic Beanstalk details page. The location of the latest AWS Elastic Beanstalk WSDL is http://elasticbeanstalk.s3.amazonaws.com/doc/2010-12-01/AWSElasticBeanstalk.wsdl. To install the Software Development Kits (SDKs), Integrated Development Environment (IDE) Toolkits, and command line tools that enable you to access the API, go to Tools for Amazon Web Services.
Endpoints
For a list of region-specific endpoints that AWS Elastic Beanstalk supports, go to Regions and Endpoints in the Amazon Web Services Glossary.
Definition at line 33 of file elasticbeanstalkclient.h.
Constructor & Destructor Documentation
ElasticBeanstalkClient::ElasticBeanstalkClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticBeanstalkClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 54 of file elasticbeanstalkclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new ElasticBeanstalkClientPrivate(this), parent)
 {
     Q_D(ElasticBeanstalkClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
ElasticBeanstalkClient::ElasticBeanstalkClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticBeanstalkClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 84 of file elasticbeanstalkclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new ElasticBeanstalkClientPrivate(this), parent)
 {
     Q_D(ElasticBeanstalkClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
elasticbeanstalk/elasticbeanstalkclient.h
elasticbeanstalk/elasticbeanstalkclient.cpp