libqtaws: MachineLearningClient Class Reference
MachineLearningClient Class Reference
Client for Amazon Machine Learning.
Public Slots
MachineLearningAddTagsResponse * addTags (const MachineLearningAddTagsRequest &request)
MachineLearningCreateBatchPredictionResponse * createBatchPrediction (const MachineLearningCreateBatchPredictionRequest &request)
MachineLearningCreateDataSourceFromRDSResponse * createDataSourceFromRDS (const MachineLearningCreateDataSourceFromRDSRequest &request)
MachineLearningCreateDataSourceFromRedshiftResponse * createDataSourceFromRedshift (const MachineLearningCreateDataSourceFromRedshiftRequest &request)
MachineLearningCreateDataSourceFromS3Response * createDataSourceFromS3 (const MachineLearningCreateDataSourceFromS3Request &request)
MachineLearningCreateEvaluationResponse * createEvaluation (const MachineLearningCreateEvaluationRequest &request)
MachineLearningCreateMLModelResponse * createMLModel (const MachineLearningCreateMLModelRequest &request)
MachineLearningCreateRealtimeEndpointResponse * createRealtimeEndpoint (const MachineLearningCreateRealtimeEndpointRequest &request)
MachineLearningDeleteBatchPredictionResponse * deleteBatchPrediction (const MachineLearningDeleteBatchPredictionRequest &request)
MachineLearningDeleteDataSourceResponse * deleteDataSource (const MachineLearningDeleteDataSourceRequest &request)
MachineLearningDeleteEvaluationResponse * deleteEvaluation (const MachineLearningDeleteEvaluationRequest &request)
MachineLearningDeleteMLModelResponse * deleteMLModel (const MachineLearningDeleteMLModelRequest &request)
MachineLearningDeleteRealtimeEndpointResponse * deleteRealtimeEndpoint (const MachineLearningDeleteRealtimeEndpointRequest &request)
MachineLearningDeleteTagsResponse * deleteTags (const MachineLearningDeleteTagsRequest &request)
MachineLearningDescribeBatchPredictionsResponse * describeBatchPredictions (const MachineLearningDescribeBatchPredictionsRequest &request)
MachineLearningDescribeDataSourcesResponse * describeDataSources (const MachineLearningDescribeDataSourcesRequest &request)
MachineLearningDescribeEvaluationsResponse * describeEvaluations (const MachineLearningDescribeEvaluationsRequest &request)
MachineLearningDescribeMLModelsResponse * describeMLModels (const MachineLearningDescribeMLModelsRequest &request)
MachineLearningDescribeTagsResponse * describeTags (const MachineLearningDescribeTagsRequest &request)
MachineLearningGetBatchPredictionResponse * getBatchPrediction (const MachineLearningGetBatchPredictionRequest &request)
MachineLearningGetDataSourceResponse * getDataSource (const MachineLearningGetDataSourceRequest &request)
MachineLearningGetEvaluationResponse * getEvaluation (const MachineLearningGetEvaluationRequest &request)
MachineLearningGetMLModelResponse * getMLModel (const MachineLearningGetMLModelRequest &request)
MachineLearningPredictResponse * predict (const MachineLearningPredictRequest &request)
MachineLearningUpdateBatchPredictionResponse * updateBatchPrediction (const MachineLearningUpdateBatchPredictionRequest &request)
MachineLearningUpdateDataSourceResponse * updateDataSource (const MachineLearningUpdateDataSourceRequest &request)
MachineLearningUpdateEvaluationResponse * updateEvaluation (const MachineLearningUpdateEvaluationRequest &request)
MachineLearningUpdateMLModelResponse * updateMLModel (const MachineLearningUpdateMLModelRequest &request)
Public Member Functions
MachineLearningClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MachineLearningClient object.
MachineLearningClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MachineLearningClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Machine Learning.
Definition of the public APIs exposed by Amazon Machine Learning
Definition at line 33 of file machinelearningclient.h.
Constructor & Destructor Documentation
MachineLearningClient::MachineLearningClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MachineLearningClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 46 of file machinelearningclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new MachineLearningClientPrivate(this), parent)
 {
     Q_D(MachineLearningClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
MachineLearningClient::MachineLearningClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MachineLearningClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 76 of file machinelearningclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new MachineLearningClientPrivate(this), parent)
 {
     Q_D(MachineLearningClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
machinelearning/machinelearningclient.h
machinelearning/machinelearningclient.cpp