libqtaws: AwsAbstractCredentials Class Reference
AwsAbstractCredentials Class Reference abstract
Interface class for providing AWS credentials.
Public Slots
virtual bool refresh ()
Refresh this object's credentials.
Signals
void changed ()
Signal emitted when this object's credentials have been updated.
Public Member Functions
AwsAbstractCredentials (QObject *const parent=0)
Construct an AwsAbstractCredentials object.
virtual ~AwsAbstractCredentials ()
AwsAbstractCredentials destructor.
virtual QString accessKeyId () const =0
AWS access key ID for this credentials object.
virtual QString secretKey () const =0
AWS secret access key for this credentials object.
virtual QString token () const =0
AWS security token for this credentials object.
virtual QDateTime expiration () const
DateTime at which the credentials will expire.
virtual bool isExpired () const
Is this credentials object currently expired.
virtual bool isRefreshable () const
Is this credentials object refreshable.
Protected Member Functions
AwsAbstractCredentials (AwsAbstractCredentialsPrivate *const d, QObject *const parent)
Construct an AwsAbstractCredentials object.
Protected Attributes
AwsAbstractCredentialsPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing AWS credentials.
Definition at line 32 of file awsabstractcredentials.h.
Constructor & Destructor Documentation
AwsAbstractCredentials::AwsAbstractCredentials (QObject *const parent = 0)
Construct an AwsAbstractCredentials object.
Parameters
parent
Definition at line 38 of file awsabstractcredentials.cpp.
     : QObject(parent), d_ptr(new AwsAbstractCredentialsPrivate(this))
 {
 }
AwsAbstractCredentials::~AwsAbstractCredentials () virtual
AwsAbstractCredentials destructor.
This virtual destructor does nothing (yet) - its here to allow for safe polymorphic destruction.
Definition at line 68 of file awsabstractcredentials.cpp.
References d_ptr.
 {
     delete d_ptr;
 }
AwsAbstractCredentials::AwsAbstractCredentials (AwsAbstractCredentialsPrivate *const d, QObject *const parent) protected
Construct an AwsAbstractCredentials object.
This overload allows derived classes to provide their own private class implementation that inherits from AwsAbstractCredentialsPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
parent This object's parent.
Definition at line 55 of file awsabstractcredentials.cpp.
     : QObject(parent), d_ptr(d)
 {
 }
Member Function Documentation
QString AwsAbstractCredentials::accessKeyId () const pure virtual
AWS access key ID for this credentials object.
Returns
The AWS access key ID for this credentials object.
Implemented in AwsBasicCredentials, and AwsAnonymousCredentials.
Referenced by AwsSignatureV0Private::adornRequest(), AwsSignatureV2Private::adornRequest(), AwsSignatureV3Private::authorizationHeaderValue(), and AwsSignatureV4Private::authorizationHeaderValue().
void AwsAbstractCredentials::changed () signal
Signal emitted when this object's credentials have been updated.
See also
refresh()
Referenced by AwsBasicCredentials::setAccessKeyId(), AwsBasicCredentials::setSecretKey(), and AwsBasicCredentials::setToken().
QDateTime AwsAbstractCredentials::expiration () const virtual
DateTime at which the credentials will expire.
This method should not be invoked unless the object is known to be refreshable (ie isRefreshable() returns true). As the base implementation of isRefreshable() always returns false, this implementation of expiration() should not be invoked.
Derived classes that return true from isRefreshable() must also override this function to provide the appropriate expiration timestamp (which may a null QDateTime if the credentials never expire).
Returns
The DateTime at whcih the credentials will expire.
See also
isExpired()
isRefreshable()
refresh()
Definition at line 114 of file awsabstractcredentials.cpp.
References isRefreshable().
Referenced by isExpired().
 {
     if (isRefreshable()) {
         qWarning() << "AwsAbstractCredentials: expiration must be implemented by refreshable derived classes";
     } else {
         qWarning() << "AwsAbstractCredentials: expiration should not be invoked on non-refreshable objects";
     }
     return QDateTime(); // A null QDateTime.
 }
bool AwsAbstractCredentials::isExpired () const virtual
Is this credentials object currently expired.
In this base implementation, non-refreshable credentials (ie those for which isRefreshable() returns false) are assumed to never expire, whereas refreshable credentials are assume to be expired only if expiration() returns a valid QDateTime representing a time in the past (ie earlier than QDateTime::currentDateTimeUtc()).
Derived classes may override this method to implement custom expiration logic.
Returns
true if this credentials object is expired, false otherwise.
See also
expiration()
isRefreshable()
refresh()
Definition at line 140 of file awsabstractcredentials.cpp.
References expiration(), and isRefreshable().
 {
     if (isRefreshable()) {
         const QDateTime expiration = this->expiration();
         return ((expiration.isValid()) && (expiration < QDateTime::currentDateTimeUtc()));
     }
     return false; // Non-refreshable credentials do not expire, by default.
 }
bool AwsAbstractCredentials::isRefreshable () const virtual
Is this credentials object refreshable.
This base implementation always returns false - ie credentials are not refreshable by default. However, dervived classes may override this method as appropriate.
Derived classes that override this method must also override the expiration() method (merely returning a null QDateTime is the credentials do not expire), and may wish to override isExpired() also.
Returns
true if this credentials object is expired, false otherwise.
See also
expiration()
isExpired()
refresh()
Definition at line 165 of file awsabstractcredentials.cpp.
Referenced by expiration(), isExpired(), and refresh().
 {
     return false;
 }
bool AwsAbstractCredentials::refresh () virtual slot
Refresh this object's credentials.
This slot begins an asynchronous refresh transaction, and should be followed by a change() signal when the credentials have been refreshed.
This method should not be invoked unless the object is known to be refreshable (ie isRefreshable() returns true). As the base implementation of isRefreshable() always returns false, this implementation of expiration() should not be invoked.
Derived classes that return true from isRefreshable() must also override this function to provide the appropriate refresh behaviour.
Returns
true if the refresh transaction has begun successfully, false otherwise.
See also
isRefreshable()
changed()
Definition at line 188 of file awsabstractcredentials.cpp.
References isRefreshable().
 {
     if (isRefreshable()) {
         qWarning() << "AwsAbstractCredentials: refresh must be implemented by refreshable derived classes";
     } else {
         qWarning() << "AwsAbstractCredentials: refresh should not be invoked on non-refreshable objects";
     }
     return false;
 }
QString AwsAbstractCredentials::secretKey () const pure virtual
AWS secret access key for this credentials object.
Returns
The AWS secret access key for this credentials object.
Implemented in AwsBasicCredentials, and AwsAnonymousCredentials.
Referenced by AwsSignatureV3Private::authorizationHeaderValue(), AwsSignatureV0::sign(), AwsSignatureV2::sign(), and AwsSignatureV4Private::signingKey().
QString AwsAbstractCredentials::token () const pure virtual
AWS security token for this credentials object.
Returns
The AWS security token for this credentials object.
Implemented in AwsBasicCredentials, and AwsAnonymousCredentials.
The documentation for this class was generated from the following files:
core/awsabstractcredentials.h
core/awsabstractcredentials.cpp