libqtaws: AWS::MediaLive::MediaLiveClient Class Reference
AWS::MediaLive::MediaLiveClient Class Reference
Client for AWS Elemental MediaLive.
Public Slots
CreateChannelResponse * createChannel (const CreateChannelRequest &request)
CreateInputResponse * createInput (const CreateInputRequest &request)
CreateInputSecurityGroupResponse * createInputSecurityGroup (const CreateInputSecurityGroupRequest &request)
DeleteChannelResponse * deleteChannel (const DeleteChannelRequest &request)
DeleteInputResponse * deleteInput (const DeleteInputRequest &request)
DeleteInputSecurityGroupResponse * deleteInputSecurityGroup (const DeleteInputSecurityGroupRequest &request)
DescribeChannelResponse * describeChannel (const DescribeChannelRequest &request)
DescribeInputResponse * describeInput (const DescribeInputRequest &request)
DescribeInputSecurityGroupResponse * describeInputSecurityGroup (const DescribeInputSecurityGroupRequest &request)
ListChannelsResponse * listChannels (const ListChannelsRequest &request)
ListInputSecurityGroupsResponse * listInputSecurityGroups (const ListInputSecurityGroupsRequest &request)
ListInputsResponse * listInputs (const ListInputsRequest &request)
StartChannelResponse * startChannel (const StartChannelRequest &request)
StopChannelResponse * stopChannel (const StopChannelRequest &request)
UpdateChannelResponse * updateChannel (const UpdateChannelRequest &request)
Public Member Functions
MediaLiveClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MediaLiveClient object.
MediaLiveClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MediaLiveClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Elemental MediaLive.
Definition at line 36 of file medialiveclient.h.
Constructor & Destructor Documentation
MediaLiveClient() [1/2]
AWS::MediaLive::MediaLiveClient::MediaLiveClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MediaLiveClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 46 of file medialiveclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new MediaLiveClientPrivate(this), parent)
 {
     Q_D(MediaLiveClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
MediaLiveClient() [2/2]
AWS::MediaLive::MediaLiveClient::MediaLiveClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MediaLiveClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 76 of file medialiveclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new MediaLiveClientPrivate(this), parent)
 {
     Q_D(MediaLiveClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
medialive/medialiveclient.h
medialive/medialiveclient.cpp