libqtaws: AWS::WAF::WafClient Class Reference
AWS::WAF::WafClient Class Reference
Client for AWS WAF.
Public Slots
CreateByteMatchSetResponse * createByteMatchSet (const CreateByteMatchSetRequest &request)
CreateGeoMatchSetResponse * createGeoMatchSet (const CreateGeoMatchSetRequest &request)
CreateIPSetResponse * createIPSet (const CreateIPSetRequest &request)
CreateRateBasedRuleResponse * createRateBasedRule (const CreateRateBasedRuleRequest &request)
CreateRegexMatchSetResponse * createRegexMatchSet (const CreateRegexMatchSetRequest &request)
CreateRegexPatternSetResponse * createRegexPatternSet (const CreateRegexPatternSetRequest &request)
CreateRuleResponse * createRule (const CreateRuleRequest &request)
CreateRuleGroupResponse * createRuleGroup (const CreateRuleGroupRequest &request)
CreateSizeConstraintSetResponse * createSizeConstraintSet (const CreateSizeConstraintSetRequest &request)
CreateSqlInjectionMatchSetResponse * createSqlInjectionMatchSet (const CreateSqlInjectionMatchSetRequest &request)
CreateWebACLResponse * createWebACL (const CreateWebACLRequest &request)
CreateXssMatchSetResponse * createXssMatchSet (const CreateXssMatchSetRequest &request)
DeleteByteMatchSetResponse * deleteByteMatchSet (const DeleteByteMatchSetRequest &request)
DeleteGeoMatchSetResponse * deleteGeoMatchSet (const DeleteGeoMatchSetRequest &request)
DeleteIPSetResponse * deleteIPSet (const DeleteIPSetRequest &request)
DeletePermissionPolicyResponse * deletePermissionPolicy (const DeletePermissionPolicyRequest &request)
DeleteRateBasedRuleResponse * deleteRateBasedRule (const DeleteRateBasedRuleRequest &request)
DeleteRegexMatchSetResponse * deleteRegexMatchSet (const DeleteRegexMatchSetRequest &request)
DeleteRegexPatternSetResponse * deleteRegexPatternSet (const DeleteRegexPatternSetRequest &request)
DeleteRuleResponse * deleteRule (const DeleteRuleRequest &request)
DeleteRuleGroupResponse * deleteRuleGroup (const DeleteRuleGroupRequest &request)
DeleteSizeConstraintSetResponse * deleteSizeConstraintSet (const DeleteSizeConstraintSetRequest &request)
DeleteSqlInjectionMatchSetResponse * deleteSqlInjectionMatchSet (const DeleteSqlInjectionMatchSetRequest &request)
DeleteWebACLResponse * deleteWebACL (const DeleteWebACLRequest &request)
DeleteXssMatchSetResponse * deleteXssMatchSet (const DeleteXssMatchSetRequest &request)
GetByteMatchSetResponse * getByteMatchSet (const GetByteMatchSetRequest &request)
GetChangeTokenResponse * getChangeToken (const GetChangeTokenRequest &request)
GetChangeTokenStatusResponse * getChangeTokenStatus (const GetChangeTokenStatusRequest &request)
GetGeoMatchSetResponse * getGeoMatchSet (const GetGeoMatchSetRequest &request)
GetIPSetResponse * getIPSet (const GetIPSetRequest &request)
GetPermissionPolicyResponse * getPermissionPolicy (const GetPermissionPolicyRequest &request)
GetRateBasedRuleResponse * getRateBasedRule (const GetRateBasedRuleRequest &request)
GetRateBasedRuleManagedKeysResponse * getRateBasedRuleManagedKeys (const GetRateBasedRuleManagedKeysRequest &request)
GetRegexMatchSetResponse * getRegexMatchSet (const GetRegexMatchSetRequest &request)
GetRegexPatternSetResponse * getRegexPatternSet (const GetRegexPatternSetRequest &request)
GetRuleResponse * getRule (const GetRuleRequest &request)
GetRuleGroupResponse * getRuleGroup (const GetRuleGroupRequest &request)
GetSampledRequestsResponse * getSampledRequests (const GetSampledRequestsRequest &request)
GetSizeConstraintSetResponse * getSizeConstraintSet (const GetSizeConstraintSetRequest &request)
GetSqlInjectionMatchSetResponse * getSqlInjectionMatchSet (const GetSqlInjectionMatchSetRequest &request)
GetWebACLResponse * getWebACL (const GetWebACLRequest &request)
GetXssMatchSetResponse * getXssMatchSet (const GetXssMatchSetRequest &request)
ListActivatedRulesInRuleGroupResponse * listActivatedRulesInRuleGroup (const ListActivatedRulesInRuleGroupRequest &request)
ListByteMatchSetsResponse * listByteMatchSets (const ListByteMatchSetsRequest &request)
ListGeoMatchSetsResponse * listGeoMatchSets (const ListGeoMatchSetsRequest &request)
ListIPSetsResponse * listIPSets (const ListIPSetsRequest &request)
ListRateBasedRulesResponse * listRateBasedRules (const ListRateBasedRulesRequest &request)
ListRegexMatchSetsResponse * listRegexMatchSets (const ListRegexMatchSetsRequest &request)
ListRegexPatternSetsResponse * listRegexPatternSets (const ListRegexPatternSetsRequest &request)
ListRuleGroupsResponse * listRuleGroups (const ListRuleGroupsRequest &request)
ListRulesResponse * listRules (const ListRulesRequest &request)
ListSizeConstraintSetsResponse * listSizeConstraintSets (const ListSizeConstraintSetsRequest &request)
ListSqlInjectionMatchSetsResponse * listSqlInjectionMatchSets (const ListSqlInjectionMatchSetsRequest &request)
ListSubscribedRuleGroupsResponse * listSubscribedRuleGroups (const ListSubscribedRuleGroupsRequest &request)
ListWebACLsResponse * listWebACLs (const ListWebACLsRequest &request)
ListXssMatchSetsResponse * listXssMatchSets (const ListXssMatchSetsRequest &request)
PutPermissionPolicyResponse * putPermissionPolicy (const PutPermissionPolicyRequest &request)
UpdateByteMatchSetResponse * updateByteMatchSet (const UpdateByteMatchSetRequest &request)
UpdateGeoMatchSetResponse * updateGeoMatchSet (const UpdateGeoMatchSetRequest &request)
UpdateIPSetResponse * updateIPSet (const UpdateIPSetRequest &request)
UpdateRateBasedRuleResponse * updateRateBasedRule (const UpdateRateBasedRuleRequest &request)
UpdateRegexMatchSetResponse * updateRegexMatchSet (const UpdateRegexMatchSetRequest &request)
UpdateRegexPatternSetResponse * updateRegexPatternSet (const UpdateRegexPatternSetRequest &request)
UpdateRuleResponse * updateRule (const UpdateRuleRequest &request)
UpdateRuleGroupResponse * updateRuleGroup (const UpdateRuleGroupRequest &request)
UpdateSizeConstraintSetResponse * updateSizeConstraintSet (const UpdateSizeConstraintSetRequest &request)
UpdateSqlInjectionMatchSetResponse * updateSqlInjectionMatchSet (const UpdateSqlInjectionMatchSetRequest &request)
UpdateWebACLResponse * updateWebACL (const UpdateWebACLRequest &request)
UpdateXssMatchSetResponse * updateXssMatchSet (const UpdateXssMatchSetRequest &request)
Public Member Functions
WafClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WafClient object.
WafClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WafClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS WAF.
This is the AWS WAF API Reference for using AWS WAF with Amazon CloudFront. The AWS WAF actions and data types listed in the reference are available for protecting Amazon CloudFront distributions. You can use these actions and data types via the endpoint waf.amazonaws.com. This guide is for developers who need detailed information about the AWS WAF API actions, data types, and errors. For detailed information about AWS WAF features and an overview of how to use the AWS WAF API, see the AWS WAF Developer
Definition at line 36 of file wafclient.h.
Constructor & Destructor Documentation
WafClient() [1/2]
AWS::WAF::WafClient::WafClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WafClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 51 of file wafclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new WafClientPrivate(this), parent)
 {
     Q_D(WafClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
WafClient() [2/2]
AWS::WAF::WafClient::WafClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WafClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 81 of file wafclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new WafClientPrivate(this), parent)
 {
     Q_D(WafClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
waf/wafclient.h
waf/wafclient.cpp