libqtaws: Route53DomainsClient Class Reference
Route53DomainsClient Class Reference
Client for Amazon Route 53 Domains.
Public Slots
Route53DomainsCheckDomainAvailabilityResponse * checkDomainAvailability (const Route53DomainsCheckDomainAvailabilityRequest &request)
Route53DomainsDeleteTagsForDomainResponse * deleteTagsForDomain (const Route53DomainsDeleteTagsForDomainRequest &request)
Route53DomainsDisableDomainAutoRenewResponse * disableDomainAutoRenew (const Route53DomainsDisableDomainAutoRenewRequest &request)
Route53DomainsDisableDomainTransferLockResponse * disableDomainTransferLock (const Route53DomainsDisableDomainTransferLockRequest &request)
Route53DomainsEnableDomainAutoRenewResponse * enableDomainAutoRenew (const Route53DomainsEnableDomainAutoRenewRequest &request)
Route53DomainsEnableDomainTransferLockResponse * enableDomainTransferLock (const Route53DomainsEnableDomainTransferLockRequest &request)
Route53DomainsGetContactReachabilityStatusResponse * getContactReachabilityStatus (const Route53DomainsGetContactReachabilityStatusRequest &request)
Route53DomainsGetDomainDetailResponse * getDomainDetail (const Route53DomainsGetDomainDetailRequest &request)
Route53DomainsGetDomainSuggestionsResponse * getDomainSuggestions (const Route53DomainsGetDomainSuggestionsRequest &request)
Route53DomainsGetOperationDetailResponse * getOperationDetail (const Route53DomainsGetOperationDetailRequest &request)
Route53DomainsListDomainsResponse * listDomains (const Route53DomainsListDomainsRequest &request)
Route53DomainsListOperationsResponse * listOperations (const Route53DomainsListOperationsRequest &request)
Route53DomainsListTagsForDomainResponse * listTagsForDomain (const Route53DomainsListTagsForDomainRequest &request)
Route53DomainsRegisterDomainResponse * registerDomain (const Route53DomainsRegisterDomainRequest &request)
Route53DomainsRenewDomainResponse * renewDomain (const Route53DomainsRenewDomainRequest &request)
Route53DomainsResendContactReachabilityEmailResponse * resendContactReachabilityEmail (const Route53DomainsResendContactReachabilityEmailRequest &request)
Route53DomainsRetrieveDomainAuthCodeResponse * retrieveDomainAuthCode (const Route53DomainsRetrieveDomainAuthCodeRequest &request)
Route53DomainsTransferDomainResponse * transferDomain (const Route53DomainsTransferDomainRequest &request)
Route53DomainsUpdateDomainContactResponse * updateDomainContact (const Route53DomainsUpdateDomainContactRequest &request)
Route53DomainsUpdateDomainContactPrivacyResponse * updateDomainContactPrivacy (const Route53DomainsUpdateDomainContactPrivacyRequest &request)
Route53DomainsUpdateDomainNameserversResponse * updateDomainNameservers (const Route53DomainsUpdateDomainNameserversRequest &request)
Route53DomainsUpdateTagsForDomainResponse * updateTagsForDomain (const Route53DomainsUpdateTagsForDomainRequest &request)
Route53DomainsViewBillingResponse * viewBilling (const Route53DomainsViewBillingRequest &request)
Public Member Functions
Route53DomainsClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new Route53DomainsClient object.
Route53DomainsClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new Route53DomainsClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Route 53 Domains.
Definition at line 33 of file route53domainsclient.h.
Constructor & Destructor Documentation
Route53DomainsClient::Route53DomainsClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new Route53DomainsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 46 of file route53domainsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new Route53DomainsClientPrivate(this), parent)
 {
     Q_D(Route53DomainsClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
Route53DomainsClient::Route53DomainsClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new Route53DomainsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 76 of file route53domainsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new Route53DomainsClientPrivate(this), parent)
 {
     Q_D(Route53DomainsClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
route53domains/route53domainsclient.h
route53domains/route53domainsclient.cpp