libqtaws: AwsEndpointPrivate Class Reference
AwsEndpointPrivate Class Reference
Private implementation for AwsEndpoint.
Classes
struct HostInfo
The per-host information to load from the endpoints.xml file.
struct RegionEndpointInfo
The per-region endpoint-specific information to load from the endpoints.xml file.
struct RegionInfo
The per-region information to load from the endpoints.xml file.
struct ServiceInfo
The per-service information to load from the endpoints.xml file.
Public Member Functions
AwsEndpointPrivate (AwsEndpoint *const q)
Constructs a new AwsEndpointPrivate object.
Public Attributes
QString hostName
This endpoint's hostname.
QString regionName
This endpoint's region name.
QString serviceName
This endpoint's service name.
Protected Types
typedef QHash< QString, RegionEndpointInfo > RegionServices
Hash of service names to RegionEndpointInfo.
Static Protected Member Functions
static void loadEndpointData (const QString &fileName=QLatin1String(":/aws/endpoints.xml"))
Load endpoint data.
static void loadEndpointData (QIODevice &device)
Load endpoint data.
static void loadEndpointData (QXmlStreamReader &xml)
Load endpoint data.
static void parseRegion (QXmlStreamReader &xml)
Parse a Region element from Amazon's endpoint XML data.
static void parseRegions (QXmlStreamReader &xml)
Parse a Regions element from Amazon's endpoint XML data.
static void parseService (QXmlStreamReader &xml)
Parse a Service element from Amazon's endpoint XML data.
static void parseServices (QXmlStreamReader &xml)
Parse a Services element from Amazon's endpoint XML data.
Static Protected Attributes
static QHash< QString, HostInfo > hosts
Hash of hostnames to HostInfo.
static QHash< QString, RegionInfo > regions
Hash of region names to RegionInfo.
static QHash< QString, ServiceInfo > services
Hash of service names to ServiceInfo.
static QMutex mutex
Mutex for protecting access to static members.
Private Attributes
AwsEndpoint *const q_ptr
Internal q-pointer.
Friends
class TestAwsEndpoint
class TestAwsSignatureV4
Detailed Description
Private implementation for AwsEndpoint.
Definition at line 37 of file awsendpoint_p.h.
Constructor & Destructor Documentation
AwsEndpointPrivate::AwsEndpointPrivate (AwsEndpoint *const q)
Constructs a new AwsEndpointPrivate object.
Parameters
q Pointer to this object's public AwsEndpoint instance.
See also
http://aws-sdk-configurations.amazonwebservices.com/endpoints.xml
Definition at line 417 of file awsendpoint.cpp.
References loadEndpointData().
     : q_ptr(q)
 {
     loadEndpointData();
 }
Member Function Documentation
void AwsEndpointPrivate::loadEndpointData (const QString & fileName = QLatin1String(":/aws/endpoints.xml")) static protected
Load endpoint data.
This function parses AWS endpoint data in XML format. The XML data is expected to match the same format as the file provided by Amazon at http://aws-sdk-configurations.amazonwebservices.com/endpoints.xml
If any data has been loaded previously, this function will return immediately with no parsing performed.
Parameters
fileName Name of the endpoint XML data file to load.
Definition at line 437 of file awsendpoint.cpp.
References hosts, and mutex.
Referenced by AwsEndpointPrivate(), AwsEndpoint::fullServiceName(), AwsEndpoint::getEndpoint(), AwsEndpoint::isSupported(), loadEndpointData(), AwsEndpoint::supportedRegions(), and AwsEndpoint::supportedServices().
 {
     QMutexLocker locker(&mutex);
     if (!hosts.empty()) {
         return; // Already loaded.
     }
     // Open the data file.
     QFile file(fileName);
     loadEndpointData(file);
 }
void AwsEndpointPrivate::loadEndpointData (QIODevice & device) static protected
Load endpoint data.
This function parses AWS endpoint data in XML format. The XML data is expected to match the same format as the file provided by Amazon at http://aws-sdk-configurations.amazonwebservices.com/endpoints.xml
If any data has been loaded previously, this function will return immediately with no parsing performed.
Parameters
device Device to parse XML data from.
Definition at line 463 of file awsendpoint.cpp.
References hosts, loadEndpointData(), and mutex.
 {
     QMutexLocker locker(&mutex);
     if (!hosts.empty()) {
         return; // Already loaded.
     }
     // Open the device, if not already open.
     if ((!device.isOpen()) && (!device.open(QIODevice::ReadOnly))) {
         qWarning() << "AwsEndpoint:" << device.errorString();
         return;
     }
     // Parse the data.
     QXmlStreamReader xml(&device);
     loadEndpointData(xml);
 }
void AwsEndpointPrivate::loadEndpointData (QXmlStreamReader & xml) static protected
Load endpoint data.
This function parses AWS endpoint data in XML format. The XML data is expected to match the same format as the file provided by Amazon at http://aws-sdk-configurations.amazonwebservices.com/endpoints.xml
If any data has been loaded previously, this function will return immediately with no parsing performed.
Parameters
xml XML document to parse.
Definition at line 495 of file awsendpoint.cpp.
References hosts, mutex, parseRegions(), parseServices(), regions, and services.
 {
     QMutexLocker locker(&mutex);
     if (!hosts.empty()) {
         return; // Already loaded.
     }
     // Parse the XML data.
     while (xml.readNextStartElement()) {
         if (xml.name() == QLatin1String("Regions")) {
             parseRegions(xml);
         } else if (xml.name() == QLatin1String("Services")) {
             parseServices(xml);
         } else if (xml.name() != QLatin1String("XML")) {
             qDebug() << "ignoring" << xml.name();
         }
     }
     if (xml.hasError()) {
         qWarning() << "AwsEndpoint:" << xml.errorString();
     }
     Q_ASSERT(!xml.hasError());
     Q_ASSERT(!hosts.isEmpty());
     Q_ASSERT(!regions.isEmpty());
     Q_ASSERT(!services.isEmpty());
 }
void AwsEndpointPrivate::parseRegion (QXmlStreamReader & xml) static protected
Parse a Region element from Amazon's endpoint XML data.
This function parses XML elements like:
 <Region>
   <Name>us-east-1</Name>
   <Endpoint>
     <ServiceName>cloudformation</ServiceName>
     <Http>false</Http>
     <Https>true</Https>
     <Hostname>cloudformation.us-east-1.amazonaws.com</Hostname>
   </Endpoint>
   <Endpoint>
     <ServiceName>cloudfront</ServiceName>
     <Http>true</Http>
     <Https>true</Https>
     <Hostname>cloudfront.amazonaws.com</Hostname>
   </Endpoint>
 </Region>
The parsed entries are automatically added to AwsEndpointPrivate::hosts and AwsEndpointPrivate::regions.
Parameters
xml XML element to parse.
See also
parseRegion
Definition at line 553 of file awsendpoint.cpp.
References hosts, regionName, regions, and serviceName.
Referenced by parseRegions().
 {
     QString regionName;
     while ((!xml.atEnd()) && (xml.readNextStartElement())) {
         if (xml.name() == QLatin1String("Name")) {
             regionName = xml.readElementText();
         } else if (xml.name() == QLatin1String("Endpoint")) {
             Q_ASSERT(!regionName.isEmpty());
             RegionEndpointInfo endpoint;
             QString serviceName;
             while ((!xml.atEnd()) && (xml.readNextStartElement())) {
                 if (xml.name() == QLatin1String("ServiceName")) {
                     serviceName = xml.readElementText();
                 } else if (xml.name() == QLatin1String("Http")) {
                     if (xml.readElementText() == QLatin1String("true")) {
                         endpoint.transports |= AwsEndpoint::HTTP;
                     }
                 } else if (xml.name() == QLatin1String("Https")) {
                     if (xml.readElementText() == QLatin1String("true")) {
                         endpoint.transports |= AwsEndpoint::HTTPS;
                     }
                 } else if (xml.name() == QLatin1String("Hostname")) {
                     endpoint.hostName = xml.readElementText();
                 } else {
                     qDebug() << "ignoring" << xml.name();
                     xml.skipCurrentElement();
                 }
             }
             Q_ASSERT(!serviceName.isEmpty());
             if (serviceName == QLatin1String("email")) {
                 endpoint.transports |= AwsEndpoint::SMTP;
             }
             Q_ASSERT((!hosts.contains(endpoint.hostName)) || (hosts.value(endpoint.hostName).serviceName == serviceName));
             hosts[endpoint.hostName].regionNames.append(regionName);
             hosts[endpoint.hostName].serviceName  = serviceName;
             regions[regionName].services[serviceName] = endpoint;
             //qDebug() << regionName << serviceName << (int)endpoint.transports << endpoint.hostName;
         } else {
             qDebug() << "ignoring" << xml.name();
             xml.skipCurrentElement();
         }
     }
 }
void AwsEndpointPrivate::parseRegions (QXmlStreamReader & xml) static protected
Parse a Regions element from Amazon's endpoint XML data.
This function parse an XML element containing a list of Region elements. See AwsEndpointPrivate::parseRegion for the Region element format.
The parsed entries are automatically added to AwsEndpointPrivate::hosts and AwsEndpointPrivate::regions.
Parameters
xml XML element containing regions to parse.
See also
parseRegion
Definition at line 614 of file awsendpoint.cpp.
References parseRegion().
Referenced by loadEndpointData().
 {
     while ((!xml.atEnd()) && (xml.readNextStartElement())) {
         if (xml.name() == QLatin1String("Region")) {
             parseRegion(xml);
         } else {
             qDebug() << "ignoring" << xml.name();
             xml.skipCurrentElement();
         }
     }
 }
void AwsEndpointPrivate::parseService (QXmlStreamReader & xml) static protected
Parse a Service element from Amazon's endpoint XML data.
This function parses XML elements like:
 <Service>
   <Name>cloudformation</Name>
   <FullName>Amazon CloudFormation</FullName>
   <RegionName>us-east-1</RegionName>
   <RegionName>us-west-1</RegionName>
   <RegionName>us-west-2</RegionName>
   <RegionName>eu-west-1</RegionName>
   <RegionName>ap-northeast-1</RegionName>
   <RegionName>ap-southeast-1</RegionName>
   <RegionName>ap-southeast-2</RegionName>
   <RegionName>sa-east-1</RegionName>
 </Service>
The parsed entries are automatically added to AwsEndpointPrivate::services.
Parameters
xml XML element to parse.
See also
parseServices
Definition at line 654 of file awsendpoint.cpp.
References regionName, serviceName, and services.
Referenced by parseServices().
 {
     QString serviceName;
     while ((!xml.atEnd()) && (xml.readNextStartElement())) {
         if (xml.name() == QLatin1String("Name")) {
             serviceName = xml.readElementText();
         } else if (xml.name() == QLatin1String("FullName")) {
             Q_ASSERT(!serviceName.isEmpty());
             services[serviceName].fullName = xml.readElementText();
         } else if (xml.name() == QLatin1String("RegionName")) {
             Q_ASSERT(!serviceName.isEmpty());
             const QString &regionName = xml.readElementText();
             services[serviceName].regionNames.append(regionName);
             //qDebug() << serviceName << services[serviceName].fullName << regionName;
         } else {
             qDebug() << "ignoring" << xml.name();
             xml.skipCurrentElement();
         }
     }
 }
void AwsEndpointPrivate::parseServices (QXmlStreamReader & xml) static protected
Parse a Services element from Amazon's endpoint XML data.
This function parses an XML element containing a list of Service elements. See AwsEndpointPrivate::parseServices for the Service element format.
The parsed entries are automatically added to AwsEndpointPrivate::services.
Parameters
xml XML element containing services to parse.
See also
parseService
Definition at line 689 of file awsendpoint.cpp.
References parseService().
Referenced by loadEndpointData().
 {
     while ((!xml.atEnd()) && (xml.readNextStartElement())) {
         if (xml.name() == QLatin1String("Service")) {
             parseService(xml);
         } else {
             qDebug() << "ignoring" << xml.name();
             xml.skipCurrentElement();
         }
     }
 }
The documentation for this class was generated from the following files:
core/awsendpoint_p.h
core/awsendpoint.cpp