libqtaws: CodeDeployClient Class Reference
CodeDeployClient Class Reference
Client for AWS CodeDeploy.
Public Slots
CodeDeployAddTagsToOnPremisesInstancesResponse * addTagsToOnPremisesInstances (const CodeDeployAddTagsToOnPremisesInstancesRequest &request)
CodeDeployBatchGetApplicationRevisionsResponse * batchGetApplicationRevisions (const CodeDeployBatchGetApplicationRevisionsRequest &request)
CodeDeployBatchGetApplicationsResponse * batchGetApplications (const CodeDeployBatchGetApplicationsRequest &request)
CodeDeployBatchGetDeploymentGroupsResponse * batchGetDeploymentGroups (const CodeDeployBatchGetDeploymentGroupsRequest &request)
CodeDeployBatchGetDeploymentInstancesResponse * batchGetDeploymentInstances (const CodeDeployBatchGetDeploymentInstancesRequest &request)
CodeDeployBatchGetDeploymentsResponse * batchGetDeployments (const CodeDeployBatchGetDeploymentsRequest &request)
CodeDeployBatchGetOnPremisesInstancesResponse * batchGetOnPremisesInstances (const CodeDeployBatchGetOnPremisesInstancesRequest &request)
CodeDeployCreateApplicationResponse * createApplication (const CodeDeployCreateApplicationRequest &request)
CodeDeployCreateDeploymentResponse * createDeployment (const CodeDeployCreateDeploymentRequest &request)
CodeDeployCreateDeploymentConfigResponse * createDeploymentConfig (const CodeDeployCreateDeploymentConfigRequest &request)
CodeDeployCreateDeploymentGroupResponse * createDeploymentGroup (const CodeDeployCreateDeploymentGroupRequest &request)
CodeDeployDeleteApplicationResponse * deleteApplication (const CodeDeployDeleteApplicationRequest &request)
CodeDeployDeleteDeploymentConfigResponse * deleteDeploymentConfig (const CodeDeployDeleteDeploymentConfigRequest &request)
CodeDeployDeleteDeploymentGroupResponse * deleteDeploymentGroup (const CodeDeployDeleteDeploymentGroupRequest &request)
CodeDeployDeregisterOnPremisesInstanceResponse * deregisterOnPremisesInstance (const CodeDeployDeregisterOnPremisesInstanceRequest &request)
CodeDeployGetApplicationResponse * getApplication (const CodeDeployGetApplicationRequest &request)
CodeDeployGetApplicationRevisionResponse * getApplicationRevision (const CodeDeployGetApplicationRevisionRequest &request)
CodeDeployGetDeploymentResponse * getDeployment (const CodeDeployGetDeploymentRequest &request)
CodeDeployGetDeploymentConfigResponse * getDeploymentConfig (const CodeDeployGetDeploymentConfigRequest &request)
CodeDeployGetDeploymentGroupResponse * getDeploymentGroup (const CodeDeployGetDeploymentGroupRequest &request)
CodeDeployGetDeploymentInstanceResponse * getDeploymentInstance (const CodeDeployGetDeploymentInstanceRequest &request)
CodeDeployGetOnPremisesInstanceResponse * getOnPremisesInstance (const CodeDeployGetOnPremisesInstanceRequest &request)
CodeDeployListApplicationRevisionsResponse * listApplicationRevisions (const CodeDeployListApplicationRevisionsRequest &request)
CodeDeployListApplicationsResponse * listApplications (const CodeDeployListApplicationsRequest &request)
CodeDeployListDeploymentConfigsResponse * listDeploymentConfigs (const CodeDeployListDeploymentConfigsRequest &request)
CodeDeployListDeploymentGroupsResponse * listDeploymentGroups (const CodeDeployListDeploymentGroupsRequest &request)
CodeDeployListDeploymentInstancesResponse * listDeploymentInstances (const CodeDeployListDeploymentInstancesRequest &request)
CodeDeployListDeploymentsResponse * listDeployments (const CodeDeployListDeploymentsRequest &request)
CodeDeployListOnPremisesInstancesResponse * listOnPremisesInstances (const CodeDeployListOnPremisesInstancesRequest &request)
CodeDeployRegisterApplicationRevisionResponse * registerApplicationRevision (const CodeDeployRegisterApplicationRevisionRequest &request)
CodeDeployRegisterOnPremisesInstanceResponse * registerOnPremisesInstance (const CodeDeployRegisterOnPremisesInstanceRequest &request)
CodeDeployRemoveTagsFromOnPremisesInstancesResponse * removeTagsFromOnPremisesInstances (const CodeDeployRemoveTagsFromOnPremisesInstancesRequest &request)
CodeDeployStopDeploymentResponse * stopDeployment (const CodeDeployStopDeploymentRequest &request)
CodeDeployUpdateApplicationResponse * updateApplication (const CodeDeployUpdateApplicationRequest &request)
CodeDeployUpdateDeploymentGroupResponse * updateDeploymentGroup (const CodeDeployUpdateDeploymentGroupRequest &request)
Public Member Functions
CodeDeployClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodeDeployClient object.
CodeDeployClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodeDeployClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS CodeDeploy.
<fullname>AWS CodeDeploy</fullname> Overview
This reference guide provides descriptions of the AWS CodeDeploy APIs. For more information about AWS CodeDeploy, see the AWS CodeDeploy User Guide.
Using the APIs
You can use the AWS CodeDeploy APIs to work with the following:
Applications are unique identifiers used by AWS CodeDeploy to ensure the correct combinations of revisions, deployment configurations, and deployment groups are being referenced during deployments.
You can use the AWS CodeDeploy APIs to create, delete, get, list, and update applications.
Deployment configurations are sets of deployment rules and success and failure conditions used by AWS CodeDeploy during deployments.
You can use the AWS CodeDeploy APIs to create, delete, get, and list deployment configurations.
Deployment groups are groups of instances to which application revisions can be deployed.
You can use the AWS CodeDeploy APIs to create, delete, get, list, and update deployment groups.
Instances represent Amazon EC2 instances to which application revisions are deployed. Instances are identified by their Amazon EC2 tags or Auto Scaling group names. Instances belong to deployment groups.
You can use the AWS CodeDeploy APIs to get and list instance.
Deployments represent the process of deploying revisions to instances.
You can use the AWS CodeDeploy APIs to create, get, list, and stop deployments.
Application revisions are archive files stored in Amazon S3 buckets or GitHub repositories. These revisions contain source content (such as source code, web pages, executable files, and deployment scripts) along with an application specification (AppSpec) file. (The AppSpec file is unique to AWS CodeDeploy; it defines the deployment actions you want AWS CodeDeploy to execute.) Ffor application revisions stored in Amazon S3 buckets, an application revision is uniquely identified by its Amazon S3 object key and its ETag, version, or both. For application revisions stored in GitHub repositories, an application revision is uniquely identified by its repository name and commit ID. Application revisions are deployed through deployment groups.
You can use the AWS CodeDeploy APIs to get, list, and register application revisions.
Definition at line 33 of file codedeployclient.h.
Constructor & Destructor Documentation
CodeDeployClient::CodeDeployClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodeDeployClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 90 of file codedeployclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new CodeDeployClientPrivate(this), parent)
 {
     Q_D(CodeDeployClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
CodeDeployClient::CodeDeployClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodeDeployClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 120 of file codedeployclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new CodeDeployClientPrivate(this), parent)
 {
     Q_D(CodeDeployClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
codedeploy/codedeployclient.h
codedeploy/codedeployclient.cpp