libqtaws: AwsAbstractClient Class Reference
AwsAbstractClient Class Reference
Interface class for providing access to individual AWS services.
Inherits QObject.
Inherited by AWS::ACM::AcmClient, AWS::AlexaForBusiness::AlexaForBusinessClient, AWS::APIGateway::APIGatewayClient, AWS::ApplicationAutoScaling::ApplicationAutoScalingClient, AWS::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient, AWS::AppStream::AppStreamClient, AWS::AppSync::AppSyncClient, AWS::Athena::AthenaClient, AWS::AutoScaling::AutoScalingClient, AWS::AutoScalingPlans::AutoScalingPlansClient, AWS::Batch::BatchClient, AWS::Budgets::BudgetsClient, AWS::Cloud9::Cloud9Client, AWS::CloudDirectory::CloudDirectoryClient, AWS::CloudFormation::CloudFormationClient, AWS::CloudFront::CloudFrontClient, AWS::CloudHSM::CloudHSMClient, AWS::CloudHSMV2::CloudHSMV2Client, AWS::CloudSearch::CloudSearchClient, AWS::CloudSearchDomain::CloudSearchDomainClient, AWS::CloudTrail::CloudTrailClient, AWS::CloudWatch::CloudWatchClient, AWS::CloudWatchEvents::CloudWatchEventsClient, AWS::CloudWatchLogs::CloudWatchLogsClient, AWS::CodeBuild::CodeBuildClient, AWS::CodeCommit::CodeCommitClient, AWS::CodeDeploy::CodeDeployClient, AWS::CodePipeline::CodePipelineClient, AWS::CodeStar::CodeStarClient, AWS::CognitoIdentity::CognitoIdentityClient, AWS::CognitoIdentityProvider::CognitoIdentityProviderClient, AWS::CognitoSync::CognitoSyncClient, AWS::Comprehend::ComprehendClient, AWS::ConfigService::ConfigServiceClient, AWS::CostandUsageReportService::CostandUsageReportServiceClient, AWS::CostExplorer::CostExplorerClient, AWS::DatabaseMigrationService::DatabaseMigrationServiceClient, AWS::DataPipeline::DataPipelineClient, AWS::DAX::DaxClient, AWS::DeviceFarm::DeviceFarmClient, AWS::DirectConnect::DirectConnectClient, AWS::DirectoryService::DirectoryServiceClient, AWS::DynamoDB::DynamoDBClient, AWS::DynamoDBStreams::DynamoDBStreamsClient, AWS::EC2::Ec2Client, AWS::ECR::EcrClient, AWS::ECS::EcsClient, AWS::EFS::EfsClient, AWS::ElastiCache::ElastiCacheClient, AWS::ElasticBeanstalk::ElasticBeanstalkClient, AWS::ElasticLoadBalancing::ElasticLoadBalancingClient, AWS::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client, AWS::ElasticsearchService::ElasticsearchServiceClient, AWS::ElasticTranscoder::ElasticTranscoderClient, AWS::EMR::EmrClient, AWS::Firehose::FirehoseClient, AWS::GameLift::GameLiftClient, AWS::Glacier::GlacierClient, AWS::Glue::GlueClient, AWS::Greengrass::GreengrassClient, AWS::GuardDuty::GuardDutyClient, AWS::Health::HealthClient, AWS::IAM::IamClient, AWS::ImportExport::ImportExportClient, AWS::Inspector::InspectorClient, AWS::IoT::IoTClient, AWS::IoTDataPlane::IoTDataPlaneClient, AWS::IoTJobsDataPlane::IoTJobsDataPlaneClient, AWS::Kinesis::KinesisClient, AWS::KinesisAnalytics::KinesisAnalyticsClient, AWS::KinesisVideo::KinesisVideoClient, AWS::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient, AWS::KinesisVideoMedia::KinesisVideoMediaClient, AWS::KMS::KmsClient, AWS::Lambda::LambdaClient, AWS::LexModelBuildingService::LexModelBuildingServiceClient, AWS::LexRuntimeService::LexRuntimeServiceClient, AWS::Lightsail::LightsailClient, AWS::MachineLearning::MachineLearningClient, AWS::MarketplaceCommerceAnalytics::MarketplaceCommerceAnalyticsClient, AWS::MarketplaceEntitlementService::MarketplaceEntitlementServiceClient, AWS::MarketplaceMetering::MarketplaceMeteringClient, AWS::MediaConvert::MediaConvertClient, AWS::MediaLive::MediaLiveClient, AWS::MediaPackage::MediaPackageClient, AWS::MediaStore::MediaStoreClient, AWS::MediaStoreData::MediaStoreDataClient, AWS::MigrationHub::MigrationHubClient, AWS::Mobile::MobileClient, AWS::MobileAnalytics::MobileAnalyticsClient, AWS::MQ::MqClient, AWS::MTurk::MTurkClient, AWS::OpsWorks::OpsWorksClient, AWS::OpsWorksCM::OpsWorksCMClient, AWS::Organizations::OrganizationsClient, AWS::Pinpoint::PinpointClient, AWS::Polly::PollyClient, AWS::Pricing::PricingClient, AWS::RDS::RdsClient, AWS::Redshift::RedshiftClient, AWS::Rekognition::RekognitionClient, AWS::ResourceGroups::ResourceGroupsClient, AWS::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient, AWS::Route53::Route53Client, AWS::Route53Domains::Route53DomainsClient, AWS::S3::S3Client, AWS::SageMaker::SageMakerClient, AWS::SageMakerRuntime::SageMakerRuntimeClient, AWS::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient, AWS::ServiceCatalog::ServiceCatalogClient, AWS::ServiceDiscovery::ServiceDiscoveryClient, AWS::SES::SesClient, AWS::SFN::SfnClient, AWS::Shield::ShieldClient, AWS::SimpleDB::SimpleDBClient, AWS::SMS::SmsClient, AWS::Snowball::SnowballClient, AWS::SNS::SnsClient, AWS::SQS::SqsClient, AWS::SSM::SsmClient, AWS::StorageGateway::StorageGatewayClient, AWS::STS::StsClient, AWS::Support::SupportClient, AWS::SWF::SwfClient, AWS::TranscribeService::TranscribeServiceClient, AWS::Translate::TranslateClient, AWS::WAF::WafClient, AWS::WAFRegional::WAFRegionalClient, AWS::WorkDocs::WorkDocsClient, AWS::WorkMail::WorkMailClient, AWS::WorkSpaces::WorkSpacesClient, AWS::XRay::XRayClient, and SqsClient.
Public Member Functions
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Protected Member Functions
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Friends
class TestAwsAbstractClient
Detailed Description
Interface class for providing access to individual AWS services.
Definition at line 38 of file awsabstractclient.h.
Constructor & Destructor Documentation
AwsAbstractClient() [1/2]
AwsAbstractClient::AwsAbstractClient (QObject *const parent = 0)
Constructs a new AwsAbstractClient object.
Parameters
parent This object's parent.
Definition at line 44 of file awsabstractclient.cpp.
     : QObject(parent), d_ptr(new AwsAbstractClientPrivate(this))
 {
 }
AwsAbstractClient() [2/2]
AwsAbstractClient::AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent) protected
Constructs a new AwsAbstractClient object.
This overload allows derived classes to provide their own private class implementation that inherits from AwsAbstractClientPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
parent This object's parent.
Definition at line 61 of file awsabstractclient.cpp.
     : QObject(parent), d_ptr(d)
 {
 }
Member Function Documentation
credentials()
AwsAbstractCredentials * AwsAbstractClient::credentials () const protected virtual
Get the credentials object to be used for signing requests.
Returns
An AWS credentials object.
Definition at line 271 of file awsabstractclient.cpp.
Referenced by AWS::ACM::AcmClient::AcmClient(), AWS::AlexaForBusiness::AlexaForBusinessClient::AlexaForBusinessClient(), AWS::APIGateway::APIGatewayClient::APIGatewayClient(), AWS::ApplicationAutoScaling::ApplicationAutoScalingClient::ApplicationAutoScalingClient(), AWS::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::ApplicationDiscoveryServiceClient(), AWS::AppStream::AppStreamClient::AppStreamClient(), AWS::AppSync::AppSyncClient::AppSyncClient(), AWS::Athena::AthenaClient::AthenaClient(), AWS::AutoScaling::AutoScalingClient::AutoScalingClient(), AWS::AutoScalingPlans::AutoScalingPlansClient::AutoScalingPlansClient(), AWS::Batch::BatchClient::BatchClient(), AWS::Budgets::BudgetsClient::BudgetsClient(), AWS::Cloud9::Cloud9Client::Cloud9Client(), AWS::CloudDirectory::CloudDirectoryClient::CloudDirectoryClient(), AWS::CloudFormation::CloudFormationClient::CloudFormationClient(), AWS::CloudFront::CloudFrontClient::CloudFrontClient(), AWS::CloudHSM::CloudHSMClient::CloudHSMClient(), AWS::CloudHSMV2::CloudHSMV2Client::CloudHSMV2Client(), AWS::CloudSearch::CloudSearchClient::CloudSearchClient(), AWS::CloudSearchDomain::CloudSearchDomainClient::CloudSearchDomainClient(), AWS::CloudTrail::CloudTrailClient::CloudTrailClient(), AWS::CloudWatch::CloudWatchClient::CloudWatchClient(), AWS::CloudWatchEvents::CloudWatchEventsClient::CloudWatchEventsClient(), AWS::CloudWatchLogs::CloudWatchLogsClient::CloudWatchLogsClient(), AWS::CodeBuild::CodeBuildClient::CodeBuildClient(), AWS::CodeCommit::CodeCommitClient::CodeCommitClient(), AWS::CodeDeploy::CodeDeployClient::CodeDeployClient(), AWS::CodePipeline::CodePipelineClient::CodePipelineClient(), AWS::CodeStar::CodeStarClient::CodeStarClient(), AWS::CognitoIdentity::CognitoIdentityClient::CognitoIdentityClient(), AWS::CognitoIdentityProvider::CognitoIdentityProviderClient::CognitoIdentityProviderClient(), AWS::CognitoSync::CognitoSyncClient::CognitoSyncClient(), AWS::Comprehend::ComprehendClient::ComprehendClient(), AWS::ConfigService::ConfigServiceClient::ConfigServiceClient(), AWS::CostandUsageReportService::CostandUsageReportServiceClient::CostandUsageReportServiceClient(), AWS::CostExplorer::CostExplorerClient::CostExplorerClient(), AWS::DatabaseMigrationService::DatabaseMigrationServiceClient::DatabaseMigrationServiceClient(), AWS::DataPipeline::DataPipelineClient::DataPipelineClient(), AWS::DAX::DaxClient::DaxClient(), AWS::DeviceFarm::DeviceFarmClient::DeviceFarmClient(), AWS::DirectConnect::DirectConnectClient::DirectConnectClient(), AWS::DirectoryService::DirectoryServiceClient::DirectoryServiceClient(), AWS::DynamoDB::DynamoDBClient::DynamoDBClient(), AWS::DynamoDBStreams::DynamoDBStreamsClient::DynamoDBStreamsClient(), AWS::EC2::Ec2Client::Ec2Client(), AWS::ECR::EcrClient::EcrClient(), AWS::ECS::EcsClient::EcsClient(), AWS::EFS::EfsClient::EfsClient(), AWS::ElastiCache::ElastiCacheClient::ElastiCacheClient(), AWS::ElasticBeanstalk::ElasticBeanstalkClient::ElasticBeanstalkClient(), AWS::ElasticLoadBalancing::ElasticLoadBalancingClient::ElasticLoadBalancingClient(), AWS::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::ElasticLoadBalancingv2Client(), AWS::ElasticsearchService::ElasticsearchServiceClient::ElasticsearchServiceClient(), AWS::ElasticTranscoder::ElasticTranscoderClient::ElasticTranscoderClient(), AWS::EMR::EmrClient::EmrClient(), AWS::Firehose::FirehoseClient::FirehoseClient(), AWS::GameLift::GameLiftClient::GameLiftClient(), AWS::Glacier::GlacierClient::GlacierClient(), AWS::Glue::GlueClient::GlueClient(), AWS::Greengrass::GreengrassClient::GreengrassClient(), AWS::GuardDuty::GuardDutyClient::GuardDutyClient(), AWS::Health::HealthClient::HealthClient(), AWS::IAM::IamClient::IamClient(), AWS::ImportExport::ImportExportClient::ImportExportClient(), AWS::Inspector::InspectorClient::InspectorClient(), AWS::IoT::IoTClient::IoTClient(), AWS::IoTDataPlane::IoTDataPlaneClient::IoTDataPlaneClient(), AWS::IoTJobsDataPlane::IoTJobsDataPlaneClient::IoTJobsDataPlaneClient(), AWS::KinesisAnalytics::KinesisAnalyticsClient::KinesisAnalyticsClient(), AWS::Kinesis::KinesisClient::KinesisClient(), AWS::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient::KinesisVideoArchivedMediaClient(), AWS::KinesisVideo::KinesisVideoClient::KinesisVideoClient(), AWS::KinesisVideoMedia::KinesisVideoMediaClient::KinesisVideoMediaClient(), AWS::KMS::KmsClient::KmsClient(), AWS::Lambda::LambdaClient::LambdaClient(), AWS::LexModelBuildingService::LexModelBuildingServiceClient::LexModelBuildingServiceClient(), AWS::LexRuntimeService::LexRuntimeServiceClient::LexRuntimeServiceClient(), AWS::Lightsail::LightsailClient::LightsailClient(), AWS::MachineLearning::MachineLearningClient::MachineLearningClient(), AWS::MarketplaceCommerceAnalytics::MarketplaceCommerceAnalyticsClient::MarketplaceCommerceAnalyticsClient(), AWS::MarketplaceEntitlementService::MarketplaceEntitlementServiceClient::MarketplaceEntitlementServiceClient(), AWS::MarketplaceMetering::MarketplaceMeteringClient::MarketplaceMeteringClient(), AWS::MediaConvert::MediaConvertClient::MediaConvertClient(), AWS::MediaLive::MediaLiveClient::MediaLiveClient(), AWS::MediaPackage::MediaPackageClient::MediaPackageClient(), AWS::MediaStore::MediaStoreClient::MediaStoreClient(), AWS::MediaStoreData::MediaStoreDataClient::MediaStoreDataClient(), AWS::MigrationHub::MigrationHubClient::MigrationHubClient(), AWS::MobileAnalytics::MobileAnalyticsClient::MobileAnalyticsClient(), AWS::Mobile::MobileClient::MobileClient(), AWS::MQ::MqClient::MqClient(), AWS::MTurk::MTurkClient::MTurkClient(), AWS::OpsWorks::OpsWorksClient::OpsWorksClient(), AWS::OpsWorksCM::OpsWorksCMClient::OpsWorksCMClient(), AWS::Organizations::OrganizationsClient::OrganizationsClient(), AWS::Pinpoint::PinpointClient::PinpointClient(), AWS::Polly::PollyClient::PollyClient(), AWS::Pricing::PricingClient::PricingClient(), AWS::RDS::RdsClient::RdsClient(), AWS::Redshift::RedshiftClient::RedshiftClient(), AWS::Rekognition::RekognitionClient::RekognitionClient(), AWS::ResourceGroups::ResourceGroupsClient::ResourceGroupsClient(), AWS::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient::ResourceGroupsTaggingAPIClient(), AWS::Route53::Route53Client::Route53Client(), AWS::Route53Domains::Route53DomainsClient::Route53DomainsClient(), AWS::S3::S3Client::S3Client(), AWS::SageMaker::SageMakerClient::SageMakerClient(), AWS::SageMakerRuntime::SageMakerRuntimeClient::SageMakerRuntimeClient(), AWS::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::ServerlessApplicationRepositoryClient(), AWS::ServiceCatalog::ServiceCatalogClient::ServiceCatalogClient(), AWS::ServiceDiscovery::ServiceDiscoveryClient::ServiceDiscoveryClient(), AWS::SES::SesClient::SesClient(), setCredentials(), AWS::SFN::SfnClient::SfnClient(), AWS::Shield::ShieldClient::ShieldClient(), AWS::SimpleDB::SimpleDBClient::SimpleDBClient(), AWS::SMS::SmsClient::SmsClient(), AWS::Snowball::SnowballClient::SnowballClient(), AWS::SNS::SnsClient::SnsClient(), AWS::SQS::SqsClient::SqsClient(), SqsClient::SqsClient(), AWS::SSM::SsmClient::SsmClient(), AWS::StorageGateway::StorageGatewayClient::StorageGatewayClient(), AWS::STS::StsClient::StsClient(), AWS::Support::SupportClient::SupportClient(), AWS::SWF::SwfClient::SwfClient(), AWS::TranscribeService::TranscribeServiceClient::TranscribeServiceClient(), AWS::Translate::TranslateClient::TranslateClient(), AWS::WAF::WafClient::WafClient(), AWS::WAFRegional::WAFRegionalClient::WAFRegionalClient(), AWS::WorkDocs::WorkDocsClient::WorkDocsClient(), AWS::WorkMail::WorkMailClient::WorkMailClient(), AWS::WorkSpaces::WorkSpacesClient::WorkSpacesClient(), and AWS::XRay::XRayClient::XRayClient().
 {
     Q_D(const AwsAbstractClient);
     return d->credentials;
 }
endpoint()
QUrl AwsAbstractClient::endpoint () const
Get the endpoint associated with this AWS client.
If a valid QUrl has been set (usually via setEndpoint), then this base implementation will return that QUrl. Otherwise, this base implementation will use the AwsEndpoint class to determine the endpoint to use based on this object's region and serviceName.
Returns
A QUrl specifying this AWS client's endpoint, or an invalid QUrl if none has been set.
See also
setEndpoint
region
serviceName
AwsEndpoint::getEndpoint
Definition at line 94 of file awsabstractclient.cpp.
References AwsEndpoint::getEndpoint(), AwsRegion::name(), region(), and serviceName().
Referenced by AWS::ACM::AcmClient::AcmClient(), AWS::AlexaForBusiness::AlexaForBusinessClient::AlexaForBusinessClient(), AWS::APIGateway::APIGatewayClient::APIGatewayClient(), AWS::ApplicationAutoScaling::ApplicationAutoScalingClient::ApplicationAutoScalingClient(), AWS::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::ApplicationDiscoveryServiceClient(), AWS::AppStream::AppStreamClient::AppStreamClient(), AWS::AppSync::AppSyncClient::AppSyncClient(), AWS::Athena::AthenaClient::AthenaClient(), AWS::AutoScaling::AutoScalingClient::AutoScalingClient(), AWS::AutoScalingPlans::AutoScalingPlansClient::AutoScalingPlansClient(), AWS::Batch::BatchClient::BatchClient(), AWS::Budgets::BudgetsClient::BudgetsClient(), AWS::Cloud9::Cloud9Client::Cloud9Client(), AWS::CloudDirectory::CloudDirectoryClient::CloudDirectoryClient(), AWS::CloudFormation::CloudFormationClient::CloudFormationClient(), AWS::CloudFront::CloudFrontClient::CloudFrontClient(), AWS::CloudHSM::CloudHSMClient::CloudHSMClient(), AWS::CloudHSMV2::CloudHSMV2Client::CloudHSMV2Client(), AWS::CloudSearch::CloudSearchClient::CloudSearchClient(), AWS::CloudSearchDomain::CloudSearchDomainClient::CloudSearchDomainClient(), AWS::CloudTrail::CloudTrailClient::CloudTrailClient(), AWS::CloudWatch::CloudWatchClient::CloudWatchClient(), AWS::CloudWatchEvents::CloudWatchEventsClient::CloudWatchEventsClient(), AWS::CloudWatchLogs::CloudWatchLogsClient::CloudWatchLogsClient(), AWS::CodeBuild::CodeBuildClient::CodeBuildClient(), AWS::CodeCommit::CodeCommitClient::CodeCommitClient(), AWS::CodeDeploy::CodeDeployClient::CodeDeployClient(), AWS::CodePipeline::CodePipelineClient::CodePipelineClient(), AWS::CodeStar::CodeStarClient::CodeStarClient(), AWS::CognitoIdentity::CognitoIdentityClient::CognitoIdentityClient(), AWS::CognitoIdentityProvider::CognitoIdentityProviderClient::CognitoIdentityProviderClient(), AWS::CognitoSync::CognitoSyncClient::CognitoSyncClient(), AWS::Comprehend::ComprehendClient::ComprehendClient(), AWS::ConfigService::ConfigServiceClient::ConfigServiceClient(), AWS::CostandUsageReportService::CostandUsageReportServiceClient::CostandUsageReportServiceClient(), AWS::CostExplorer::CostExplorerClient::CostExplorerClient(), AWS::DatabaseMigrationService::DatabaseMigrationServiceClient::DatabaseMigrationServiceClient(), AWS::DataPipeline::DataPipelineClient::DataPipelineClient(), AWS::DAX::DaxClient::DaxClient(), AWS::DeviceFarm::DeviceFarmClient::DeviceFarmClient(), AWS::DirectConnect::DirectConnectClient::DirectConnectClient(), AWS::DirectoryService::DirectoryServiceClient::DirectoryServiceClient(), AWS::DynamoDB::DynamoDBClient::DynamoDBClient(), AWS::DynamoDBStreams::DynamoDBStreamsClient::DynamoDBStreamsClient(), AWS::EC2::Ec2Client::Ec2Client(), AWS::ECR::EcrClient::EcrClient(), AWS::ECS::EcsClient::EcsClient(), AWS::EFS::EfsClient::EfsClient(), AWS::ElastiCache::ElastiCacheClient::ElastiCacheClient(), AWS::ElasticBeanstalk::ElasticBeanstalkClient::ElasticBeanstalkClient(), AWS::ElasticLoadBalancing::ElasticLoadBalancingClient::ElasticLoadBalancingClient(), AWS::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::ElasticLoadBalancingv2Client(), AWS::ElasticsearchService::ElasticsearchServiceClient::ElasticsearchServiceClient(), AWS::ElasticTranscoder::ElasticTranscoderClient::ElasticTranscoderClient(), AWS::EMR::EmrClient::EmrClient(), AWS::Firehose::FirehoseClient::FirehoseClient(), AWS::GameLift::GameLiftClient::GameLiftClient(), AWS::Glacier::GlacierClient::GlacierClient(), AWS::Glue::GlueClient::GlueClient(), AWS::Greengrass::GreengrassClient::GreengrassClient(), AWS::GuardDuty::GuardDutyClient::GuardDutyClient(), AWS::Health::HealthClient::HealthClient(), AWS::IAM::IamClient::IamClient(), AWS::ImportExport::ImportExportClient::ImportExportClient(), AWS::Inspector::InspectorClient::InspectorClient(), AWS::IoT::IoTClient::IoTClient(), AWS::IoTDataPlane::IoTDataPlaneClient::IoTDataPlaneClient(), AWS::IoTJobsDataPlane::IoTJobsDataPlaneClient::IoTJobsDataPlaneClient(), AWS::KinesisAnalytics::KinesisAnalyticsClient::KinesisAnalyticsClient(), AWS::Kinesis::KinesisClient::KinesisClient(), AWS::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient::KinesisVideoArchivedMediaClient(), AWS::KinesisVideo::KinesisVideoClient::KinesisVideoClient(), AWS::KinesisVideoMedia::KinesisVideoMediaClient::KinesisVideoMediaClient(), AWS::KMS::KmsClient::KmsClient(), AWS::Lambda::LambdaClient::LambdaClient(), AWS::LexModelBuildingService::LexModelBuildingServiceClient::LexModelBuildingServiceClient(), AWS::LexRuntimeService::LexRuntimeServiceClient::LexRuntimeServiceClient(), AWS::Lightsail::LightsailClient::LightsailClient(), AWS::MachineLearning::MachineLearningClient::MachineLearningClient(), AWS::MarketplaceCommerceAnalytics::MarketplaceCommerceAnalyticsClient::MarketplaceCommerceAnalyticsClient(), AWS::MarketplaceEntitlementService::MarketplaceEntitlementServiceClient::MarketplaceEntitlementServiceClient(), AWS::MarketplaceMetering::MarketplaceMeteringClient::MarketplaceMeteringClient(), AWS::MediaConvert::MediaConvertClient::MediaConvertClient(), AWS::MediaLive::MediaLiveClient::MediaLiveClient(), AWS::MediaPackage::MediaPackageClient::MediaPackageClient(), AWS::MediaStore::MediaStoreClient::MediaStoreClient(), AWS::MediaStoreData::MediaStoreDataClient::MediaStoreDataClient(), AWS::MigrationHub::MigrationHubClient::MigrationHubClient(), AWS::MobileAnalytics::MobileAnalyticsClient::MobileAnalyticsClient(), AWS::Mobile::MobileClient::MobileClient(), AWS::MQ::MqClient::MqClient(), AWS::MTurk::MTurkClient::MTurkClient(), AWS::OpsWorks::OpsWorksClient::OpsWorksClient(), AWS::OpsWorksCM::OpsWorksCMClient::OpsWorksCMClient(), AWS::Organizations::OrganizationsClient::OrganizationsClient(), AWS::Pinpoint::PinpointClient::PinpointClient(), AWS::Polly::PollyClient::PollyClient(), AWS::Pricing::PricingClient::PricingClient(), AWS::RDS::RdsClient::RdsClient(), AWS::Redshift::RedshiftClient::RedshiftClient(), AWS::Rekognition::RekognitionClient::RekognitionClient(), AWS::ResourceGroups::ResourceGroupsClient::ResourceGroupsClient(), AWS::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient::ResourceGroupsTaggingAPIClient(), AWS::Route53::Route53Client::Route53Client(), AWS::Route53Domains::Route53DomainsClient::Route53DomainsClient(), AWS::S3::S3Client::S3Client(), AWS::SageMaker::SageMakerClient::SageMakerClient(), AWS::SageMakerRuntime::SageMakerRuntimeClient::SageMakerRuntimeClient(), send(), AWS::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::ServerlessApplicationRepositoryClient(), AWS::ServiceCatalog::ServiceCatalogClient::ServiceCatalogClient(), AWS::ServiceDiscovery::ServiceDiscoveryClient::ServiceDiscoveryClient(), AWS::SES::SesClient::SesClient(), setEndpoint(), AWS::SFN::SfnClient::SfnClient(), AWS::Shield::ShieldClient::ShieldClient(), AWS::SimpleDB::SimpleDBClient::SimpleDBClient(), AWS::SMS::SmsClient::SmsClient(), AWS::Snowball::SnowballClient::SnowballClient(), AWS::SNS::SnsClient::SnsClient(), AWS::SQS::SqsClient::SqsClient(), SqsClient::SqsClient(), AWS::SSM::SsmClient::SsmClient(), AWS::StorageGateway::StorageGatewayClient::StorageGatewayClient(), AWS::STS::StsClient::StsClient(), AWS::Support::SupportClient::SupportClient(), AWS::SWF::SwfClient::SwfClient(), AWS::TranscribeService::TranscribeServiceClient::TranscribeServiceClient(), AWS::Translate::TranslateClient::TranslateClient(), AWS::WAF::WafClient::WafClient(), AWS::WAFRegional::WAFRegionalClient::WAFRegionalClient(), AWS::WorkDocs::WorkDocsClient::WorkDocsClient(), AWS::WorkMail::WorkMailClient::WorkMailClient(), AWS::WorkSpaces::WorkSpacesClient::WorkSpacesClient(), and AWS::XRay::XRayClient::XRayClient().
 {
     Q_D(const AwsAbstractClient);
     return (d->endpoint.isValid()) ? d->endpoint :
         AwsEndpoint::getEndpoint(AwsRegion::name(region()), serviceName());
 }
networkAccessManager()
QNetworkAccessManager * AwsAbstractClient::networkAccessManager () const
Get the network access manager for this AWS service object.
Returns
The QNetworkAccessManager that handles requests for this object.
Definition at line 106 of file awsabstractclient.cpp.
 {
     Q_D(const AwsAbstractClient);
     return d->networkAccessManager;
 }
region()
AwsRegion::Region AwsAbstractClient::region () const
Get the AWS region associated with this client.
Returns
The AWS region for this client, or AwsRegion::InvalidRegion if none has been set.
See also
setRegion
endpoint
Definition at line 121 of file awsabstractclient.cpp.
Referenced by AWS::ACM::AcmClient::AcmClient(), AWS::AlexaForBusiness::AlexaForBusinessClient::AlexaForBusinessClient(), AWS::APIGateway::APIGatewayClient::APIGatewayClient(), AWS::ApplicationAutoScaling::ApplicationAutoScalingClient::ApplicationAutoScalingClient(), AWS::ApplicationDiscoveryService::ApplicationDiscoveryServiceClient::ApplicationDiscoveryServiceClient(), AWS::AppStream::AppStreamClient::AppStreamClient(), AWS::AppSync::AppSyncClient::AppSyncClient(), AWS::Athena::AthenaClient::AthenaClient(), AWS::AutoScaling::AutoScalingClient::AutoScalingClient(), AWS::AutoScalingPlans::AutoScalingPlansClient::AutoScalingPlansClient(), AWS::Batch::BatchClient::BatchClient(), AWS::Budgets::BudgetsClient::BudgetsClient(), AWS::Cloud9::Cloud9Client::Cloud9Client(), AWS::CloudDirectory::CloudDirectoryClient::CloudDirectoryClient(), AWS::CloudFormation::CloudFormationClient::CloudFormationClient(), AWS::CloudFront::CloudFrontClient::CloudFrontClient(), AWS::CloudHSM::CloudHSMClient::CloudHSMClient(), AWS::CloudHSMV2::CloudHSMV2Client::CloudHSMV2Client(), AWS::CloudSearch::CloudSearchClient::CloudSearchClient(), AWS::CloudSearchDomain::CloudSearchDomainClient::CloudSearchDomainClient(), AWS::CloudTrail::CloudTrailClient::CloudTrailClient(), AWS::CloudWatch::CloudWatchClient::CloudWatchClient(), AWS::CloudWatchEvents::CloudWatchEventsClient::CloudWatchEventsClient(), AWS::CloudWatchLogs::CloudWatchLogsClient::CloudWatchLogsClient(), AWS::CodeBuild::CodeBuildClient::CodeBuildClient(), AWS::CodeCommit::CodeCommitClient::CodeCommitClient(), AWS::CodeDeploy::CodeDeployClient::CodeDeployClient(), AWS::CodePipeline::CodePipelineClient::CodePipelineClient(), AWS::CodeStar::CodeStarClient::CodeStarClient(), AWS::CognitoIdentity::CognitoIdentityClient::CognitoIdentityClient(), AWS::CognitoIdentityProvider::CognitoIdentityProviderClient::CognitoIdentityProviderClient(), AWS::CognitoSync::CognitoSyncClient::CognitoSyncClient(), AWS::Comprehend::ComprehendClient::ComprehendClient(), AWS::ConfigService::ConfigServiceClient::ConfigServiceClient(), AWS::CostandUsageReportService::CostandUsageReportServiceClient::CostandUsageReportServiceClient(), AWS::CostExplorer::CostExplorerClient::CostExplorerClient(), AWS::DatabaseMigrationService::DatabaseMigrationServiceClient::DatabaseMigrationServiceClient(), AWS::DataPipeline::DataPipelineClient::DataPipelineClient(), AWS::DAX::DaxClient::DaxClient(), AWS::DeviceFarm::DeviceFarmClient::DeviceFarmClient(), AWS::DirectConnect::DirectConnectClient::DirectConnectClient(), AWS::DirectoryService::DirectoryServiceClient::DirectoryServiceClient(), AWS::DynamoDB::DynamoDBClient::DynamoDBClient(), AWS::DynamoDBStreams::DynamoDBStreamsClient::DynamoDBStreamsClient(), AWS::EC2::Ec2Client::Ec2Client(), AWS::ECR::EcrClient::EcrClient(), AWS::ECS::EcsClient::EcsClient(), AWS::EFS::EfsClient::EfsClient(), AWS::ElastiCache::ElastiCacheClient::ElastiCacheClient(), AWS::ElasticBeanstalk::ElasticBeanstalkClient::ElasticBeanstalkClient(), AWS::ElasticLoadBalancing::ElasticLoadBalancingClient::ElasticLoadBalancingClient(), AWS::ElasticLoadBalancingv2::ElasticLoadBalancingv2Client::ElasticLoadBalancingv2Client(), AWS::ElasticsearchService::ElasticsearchServiceClient::ElasticsearchServiceClient(), AWS::ElasticTranscoder::ElasticTranscoderClient::ElasticTranscoderClient(), AWS::EMR::EmrClient::EmrClient(), endpoint(), AWS::Firehose::FirehoseClient::FirehoseClient(), AWS::GameLift::GameLiftClient::GameLiftClient(), AWS::Glacier::GlacierClient::GlacierClient(), AWS::Glue::GlueClient::GlueClient(), AWS::Greengrass::GreengrassClient::GreengrassClient(), AWS::GuardDuty::GuardDutyClient::GuardDutyClient(), AWS::Health::HealthClient::HealthClient(), AWS::IAM::IamClient::IamClient(), AWS::ImportExport::ImportExportClient::ImportExportClient(), AWS::Inspector::InspectorClient::InspectorClient(), AWS::IoT::IoTClient::IoTClient(), AWS::IoTDataPlane::IoTDataPlaneClient::IoTDataPlaneClient(), AWS::IoTJobsDataPlane::IoTJobsDataPlaneClient::IoTJobsDataPlaneClient(), AWS::KinesisAnalytics::KinesisAnalyticsClient::KinesisAnalyticsClient(), AWS::Kinesis::KinesisClient::KinesisClient(), AWS::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient::KinesisVideoArchivedMediaClient(), AWS::KinesisVideo::KinesisVideoClient::KinesisVideoClient(), AWS::KinesisVideoMedia::KinesisVideoMediaClient::KinesisVideoMediaClient(), AWS::KMS::KmsClient::KmsClient(), AWS::Lambda::LambdaClient::LambdaClient(), AWS::LexModelBuildingService::LexModelBuildingServiceClient::LexModelBuildingServiceClient(), AWS::LexRuntimeService::LexRuntimeServiceClient::LexRuntimeServiceClient(), AWS::Lightsail::LightsailClient::LightsailClient(), AWS::MachineLearning::MachineLearningClient::MachineLearningClient(), AWS::MarketplaceCommerceAnalytics::MarketplaceCommerceAnalyticsClient::MarketplaceCommerceAnalyticsClient(), AWS::MarketplaceEntitlementService::MarketplaceEntitlementServiceClient::MarketplaceEntitlementServiceClient(), AWS::MarketplaceMetering::MarketplaceMeteringClient::MarketplaceMeteringClient(), AWS::MediaConvert::MediaConvertClient::MediaConvertClient(), AWS::MediaLive::MediaLiveClient::MediaLiveClient(), AWS::MediaPackage::MediaPackageClient::MediaPackageClient(), AWS::MediaStore::MediaStoreClient::MediaStoreClient(), AWS::MediaStoreData::MediaStoreDataClient::MediaStoreDataClient(), AWS::MigrationHub::MigrationHubClient::MigrationHubClient(), AWS::MobileAnalytics::MobileAnalyticsClient::MobileAnalyticsClient(), AWS::Mobile::MobileClient::MobileClient(), AWS::MQ::MqClient::MqClient(), AWS::MTurk::MTurkClient::MTurkClient(), AWS::OpsWorks::OpsWorksClient::OpsWorksClient(), AWS::OpsWorksCM::OpsWorksCMClient::OpsWorksCMClient(), AWS::Organizations::OrganizationsClient::OrganizationsClient(), AWS::Pinpoint::PinpointClient::PinpointClient(), AWS::Polly::PollyClient::PollyClient(), AWS::Pricing::PricingClient::PricingClient(), AWS::RDS::RdsClient::RdsClient(), AWS::Redshift::RedshiftClient::RedshiftClient(), AWS::Rekognition::RekognitionClient::RekognitionClient(), AWS::ResourceGroups::ResourceGroupsClient::ResourceGroupsClient(), AWS::ResourceGroupsTaggingAPI::ResourceGroupsTaggingAPIClient::ResourceGroupsTaggingAPIClient(), AWS::Route53::Route53Client::Route53Client(), AWS::Route53Domains::Route53DomainsClient::Route53DomainsClient(), AWS::S3::S3Client::S3Client(), AWS::SageMaker::SageMakerClient::SageMakerClient(), AWS::SageMakerRuntime::SageMakerRuntimeClient::SageMakerRuntimeClient(), AWS::ServerlessApplicationRepository::ServerlessApplicationRepositoryClient::ServerlessApplicationRepositoryClient(), AWS::ServiceCatalog::ServiceCatalogClient::ServiceCatalogClient(), AWS::ServiceDiscovery::ServiceDiscoveryClient::ServiceDiscoveryClient(), AWS::SES::SesClient::SesClient(), setRegion(), AWS::SFN::SfnClient::SfnClient(), AWS::Shield::ShieldClient::ShieldClient(), AWS::SimpleDB::SimpleDBClient::SimpleDBClient(), AWS::SMS::SmsClient::SmsClient(), AWS::Snowball::SnowballClient::SnowballClient(), AWS::SNS::SnsClient::SnsClient(), AWS::SQS::SqsClient::SqsClient(), SqsClient::SqsClient(), AWS::SSM::SsmClient::SsmClient(), AWS::StorageGateway::StorageGatewayClient::StorageGatewayClient(), AWS::STS::StsClient::StsClient(), AWS::Support::SupportClient::SupportClient(), AWS::SWF::SwfClient::SwfClient(), AWS::TranscribeService::TranscribeServiceClient::TranscribeServiceClient(), AWS::Translate::TranslateClient::TranslateClient(), AWS::WAF::WafClient::WafClient(), AWS::WAFRegional::WAFRegionalClient::WAFRegionalClient(), AWS::WorkDocs::WorkDocsClient::WorkDocsClient(), AWS::WorkMail::WorkMailClient::WorkMailClient(), AWS::WorkSpaces::WorkSpacesClient::WorkSpacesClient(), and AWS::XRay::XRayClient::XRayClient().
 {
     Q_D(const AwsAbstractClient);
     return d->region;
 }
send()
AwsAbstractResponse * AwsAbstractClient::send (const AwsAbstractRequest & request) virtual
Send an AWS request.
This base implementation simply uses the request's send method, supplying the necessary resources (ie the credentials, network access manager, and signature object) from this object as required.
Derived classes would not normally need to override this method.
Parameters
request The AWS request to send.
Returns
An object representing the AWS service's response.
Definition at line 140 of file awsabstractclient.cpp.
References endpoint(), AwsAbstractRequest::isValid(), AwsAbstractRequest::send(), and serviceName().
Referenced by SqsClient::addPermission(), SqsClient::changeMessageVisibility(), SqsClient::createQueue(), SqsClient::deleteMessage(), SqsClient::deleteQueue(), SqsClient::getQueueUrl(), SqsClient::listDeadLetterSourceQueues(), SqsClient::listQueues(), SqsClient::purgeQueue(), and SqsClient::removePermission().
 {
     Q_D(AwsAbstractClient);
     Q_ASSERT(d->credentials);
     Q_ASSERT(d->networkAccessManager);
     Q_ASSERT(d->signature);
     Q_ASSERT(request.isValid());
     if (!d->credentials) {
         qWarning() << "credentials not set";
         return NULL;
     } else if (!d->networkAccessManager) {
         qWarning() << "network access manager not set";
         return NULL;
     } else if (!d->signature) {
         qWarning() << "signature not set";
         return NULL;
     } else if (!request.isValid()) {
         qWarning() << serviceName() << "request not valid";
         return NULL;
     }
     return request.send(*d->networkAccessManager, endpoint(),
                         *d->signature, *d->credentials);
 }
serviceName()
QString AwsAbstractClient::serviceName () const
Get the name of the Amazon service this client accesses.
This base implementation simply returns the name set via setServiceName.
Returns
An Amazon service name, such as "sqs" or "sns".
See also
setServiceName
Definition at line 175 of file awsabstractclient.cpp.
Referenced by endpoint(), and send().
 {
     Q_D(const AwsAbstractClient);
     Q_ASSERT(!d->serviceName.isEmpty());
     return d->serviceName;
 }
setCredentials()
void AwsAbstractClient::setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
This object will not take ownership of the supplied credentials pointer. It is the caller's responsibility to ensure that the pointer remains valid for the life of this object, or until setCredentials is used to set a new pointer.
Parameters
credentials Credentials to use for signing requests.
See also
sign
Definition at line 194 of file awsabstractclient.cpp.
References credentials().
 {
     Q_D(AwsAbstractClient);
     d->credentials = credentials;
 }
setEndpoint()
void AwsAbstractClient::setEndpoint (const QUrl & endpoint)
Set the AWS endpoint to use with this client.
Typically, it is simpler for the user to set this client's region instead (via setRegion), and allow this object to then determine the endpoint based on the serviceName and region. However, this method may be used to set an explicit endpoint URL if desired.
Parameters
endpoint Endpoint URL to use for sending AWS requests.
See also
region
send
setRegion
Definition at line 214 of file awsabstractclient.cpp.
References endpoint().
 {
     Q_D(AwsAbstractClient);
     d->endpoint = endpoint;
 }
setNetworkAccessManager()
void AwsAbstractClient::setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
This object will not take ownership of the supplied manager pointer. It is the caller's responsibility to ensure that the pointer remains valid for the life of this object, or until setNetworkAccessManager is used to set a new pointer.
Parameters
manager Network access manager for this AWS service object to use.
Definition at line 230 of file awsabstractclient.cpp.
 {
     Q_D(AwsAbstractClient);
     // If \a manager is already our network access manager, drop out early.
     if (d->networkAccessManager == manager) {
         return;
     }
     // If the old network access manager was our parent, disown our parent.
     if ((d->networkAccessManager != NULL) && (parent() == d->networkAccessManager)) {
         setParent(NULL);
     }
     // Set the network access manager.
     d->networkAccessManager = manager;
 }
setRegion()
void AwsAbstractClient::setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
If an endpoint is not explicitly set (eg via setEndpoint), then the supplied value may be used (in conjuction with serviceName) to determine the endpoint URL when sending requests to the AWS service.
Parameters
region Amazon region for this client to use.
See also
send
setEndpoint
Definition at line 260 of file awsabstractclient.cpp.
References region().
 {
     Q_D(AwsAbstractClient);
     d->region = region;
 }
signature()
AwsAbstractSignature * AwsAbstractClient::signature () const protected virtual
Get the signature object to be used for signing requests.
Returns
An AWS signature object.
Definition at line 282 of file awsabstractclient.cpp.
 {
     Q_D(const AwsAbstractClient);
     return d->signature;
 }
The documentation for this class was generated from the following files:
core/awsabstractclient.h
core/awsabstractclient.cpp