libqtaws: AWS::CodeStar::CodeStarClient Class Reference
AWS::CodeStar::CodeStarClient Class Reference
Client for AWS CodeStar.
Public Slots
AssociateTeamMemberResponse * associateTeamMember (const AssociateTeamMemberRequest &request)
CreateProjectResponse * createProject (const CreateProjectRequest &request)
CreateUserProfileResponse * createUserProfile (const CreateUserProfileRequest &request)
DeleteProjectResponse * deleteProject (const DeleteProjectRequest &request)
DeleteUserProfileResponse * deleteUserProfile (const DeleteUserProfileRequest &request)
DescribeProjectResponse * describeProject (const DescribeProjectRequest &request)
DescribeUserProfileResponse * describeUserProfile (const DescribeUserProfileRequest &request)
DisassociateTeamMemberResponse * disassociateTeamMember (const DisassociateTeamMemberRequest &request)
ListProjectsResponse * listProjects (const ListProjectsRequest &request)
ListResourcesResponse * listResources (const ListResourcesRequest &request)
ListTagsForProjectResponse * listTagsForProject (const ListTagsForProjectRequest &request)
ListTeamMembersResponse * listTeamMembers (const ListTeamMembersRequest &request)
ListUserProfilesResponse * listUserProfiles (const ListUserProfilesRequest &request)
TagProjectResponse * tagProject (const TagProjectRequest &request)
UntagProjectResponse * untagProject (const UntagProjectRequest &request)
UpdateProjectResponse * updateProject (const UpdateProjectRequest &request)
UpdateTeamMemberResponse * updateTeamMember (const UpdateTeamMemberRequest &request)
UpdateUserProfileResponse * updateUserProfile (const UpdateUserProfileRequest &request)
Public Member Functions
CodeStarClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodeStarClient object.
CodeStarClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CodeStarClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS CodeStar.
<fullname>AWS CodeStar</fullname>
This is the API reference for AWS CodeStar. This reference provides descriptions of the operations and data types for the AWS CodeStar API along with usage
examples>
You can use the AWS CodeStar API to work
with>
Projects and their resources, by calling the
following>
DeleteProject, which deletes a
project>
DescribeProject, which lists the attributes of a
project>
ListProjects, which lists all projects associated with your AWS
account>
ListResources, which lists the resources associated with a
project>
ListTagsForProject, which lists the tags associated with a
project>
TagProject, which adds tags to a
project>
UntagProject, which removes tags from a
project>
UpdateProject, which updates the attributes of a
project>
Teams and team members, by calling the
following>
AssociateTeamMember, which adds an IAM user to the team for a
project>
DisassociateTeamMember, which removes an IAM user from the team for a
project>
ListTeamMembers, which lists all the IAM users in the team for a project, including their roles and
attributes>
UpdateTeamMember, which updates a team member's attributes in a
project>
Users, by calling the
following>
CreateUserProfile, which creates a user profile that contains data associated with the user across all
projects>
DeleteUserProfile, which deletes all user profile information across all
projects>
DescribeUserProfile, which describes the profile of a
user>
ListUserProfiles, which lists all user
profiles>
UpdateUserProfile, which updates the profile for a
Definition at line 36 of file codestarclient.h.
Constructor & Destructor Documentation
CodeStarClient() [1/2]
AWS::CodeStar::CodeStarClient::CodeStarClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodeStarClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 134 of file codestarclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new CodeStarClientPrivate(this), parent)
 {
     Q_D(CodeStarClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
CodeStarClient() [2/2]
AWS::CodeStar::CodeStarClient::CodeStarClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CodeStarClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 164 of file codestarclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new CodeStarClientPrivate(this), parent)
 {
     Q_D(CodeStarClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
codestar/codestarclient.h
codestar/codestarclient.cpp