libqtaws: AWS::LexModelBuildingService::LexModelBuildingServiceClient Class Reference
AWS::LexModelBuildingService::LexModelBuildingServiceClient Class Reference
Client for Amazon Lex Model Building Service.
Public Slots
CreateBotVersionResponse * createBotVersion (const CreateBotVersionRequest &request)
CreateIntentVersionResponse * createIntentVersion (const CreateIntentVersionRequest &request)
CreateSlotTypeVersionResponse * createSlotTypeVersion (const CreateSlotTypeVersionRequest &request)
DeleteBotResponse * deleteBot (const DeleteBotRequest &request)
DeleteBotAliasResponse * deleteBotAlias (const DeleteBotAliasRequest &request)
DeleteBotChannelAssociationResponse * deleteBotChannelAssociation (const DeleteBotChannelAssociationRequest &request)
DeleteBotVersionResponse * deleteBotVersion (const DeleteBotVersionRequest &request)
DeleteIntentResponse * deleteIntent (const DeleteIntentRequest &request)
DeleteIntentVersionResponse * deleteIntentVersion (const DeleteIntentVersionRequest &request)
DeleteSlotTypeResponse * deleteSlotType (const DeleteSlotTypeRequest &request)
DeleteSlotTypeVersionResponse * deleteSlotTypeVersion (const DeleteSlotTypeVersionRequest &request)
DeleteUtterancesResponse * deleteUtterances (const DeleteUtterancesRequest &request)
GetBotResponse * getBot (const GetBotRequest &request)
GetBotAliasResponse * getBotAlias (const GetBotAliasRequest &request)
GetBotAliasesResponse * getBotAliases (const GetBotAliasesRequest &request)
GetBotChannelAssociationResponse * getBotChannelAssociation (const GetBotChannelAssociationRequest &request)
GetBotChannelAssociationsResponse * getBotChannelAssociations (const GetBotChannelAssociationsRequest &request)
GetBotVersionsResponse * getBotVersions (const GetBotVersionsRequest &request)
GetBotsResponse * getBots (const GetBotsRequest &request)
GetBuiltinIntentResponse * getBuiltinIntent (const GetBuiltinIntentRequest &request)
GetBuiltinIntentsResponse * getBuiltinIntents (const GetBuiltinIntentsRequest &request)
GetBuiltinSlotTypesResponse * getBuiltinSlotTypes (const GetBuiltinSlotTypesRequest &request)
GetExportResponse * getExport (const GetExportRequest &request)
GetImportResponse * getImport (const GetImportRequest &request)
GetIntentResponse * getIntent (const GetIntentRequest &request)
GetIntentVersionsResponse * getIntentVersions (const GetIntentVersionsRequest &request)
GetIntentsResponse * getIntents (const GetIntentsRequest &request)
GetSlotTypeResponse * getSlotType (const GetSlotTypeRequest &request)
GetSlotTypeVersionsResponse * getSlotTypeVersions (const GetSlotTypeVersionsRequest &request)
GetSlotTypesResponse * getSlotTypes (const GetSlotTypesRequest &request)
GetUtterancesViewResponse * getUtterancesView (const GetUtterancesViewRequest &request)
PutBotResponse * putBot (const PutBotRequest &request)
PutBotAliasResponse * putBotAlias (const PutBotAliasRequest &request)
PutIntentResponse * putIntent (const PutIntentRequest &request)
PutSlotTypeResponse * putSlotType (const PutSlotTypeRequest &request)
StartImportResponse * startImport (const StartImportRequest &request)
Public Member Functions
LexModelBuildingServiceClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new LexModelBuildingServiceClient object.
LexModelBuildingServiceClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new LexModelBuildingServiceClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Lex Model Building Service.
<fullname>Amazon Lex Build-Time Actions</fullname>
Amazon Lex is an AWS service for building conversational voice and text interfaces. Use these actions to create, update, and delete conversational bots for new and existing client applications.
Definition at line 36 of file lexmodelbuildingserviceclient.h.
Constructor & Destructor Documentation
LexModelBuildingServiceClient() [1/2]
AWS::LexModelBuildingService::LexModelBuildingServiceClient::LexModelBuildingServiceClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new LexModelBuildingServiceClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 50 of file lexmodelbuildingserviceclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new LexModelBuildingServiceClientPrivate(this), parent)
 {
     Q_D(LexModelBuildingServiceClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
LexModelBuildingServiceClient() [2/2]
AWS::LexModelBuildingService::LexModelBuildingServiceClient::LexModelBuildingServiceClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new LexModelBuildingServiceClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 80 of file lexmodelbuildingserviceclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new LexModelBuildingServiceClientPrivate(this), parent)
 {
     Q_D(LexModelBuildingServiceClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
lex-models/lexmodelbuildingserviceclient.h
lex-models/lexmodelbuildingserviceclient.cpp