libqtaws: SqsRemovePermissionRequest Class Reference
SqsRemovePermissionRequest Class Reference
Implements SQS RemovePermission requests.
Public Member Functions
SqsRemovePermissionRequest (const QString &queueUrl, const QString &label)
Constructs a new SqsRemovePermissionRequest.
SqsRemovePermissionRequest (const SqsRemovePermissionRequest &other)
Constructs a new SqsRemovePermissionRequest object by copying another.
SqsRemovePermissionRequest ()
Constructs a new SqsRemovePermissionRequest object.
virtual bool isValid () const
Is this request valid?
QString label () const
Get the identification of the permission to remove.
QString queueUrl () const
Get the URL of the Amazon SQS queue to take action on.
void setLabel (const QString &label)
Set the identification of the permission to remove.
void setQueueUrl (const QString &queueUrl)
Set the URL of the queue to add permissions to.
Public Member Functions inherited from SqsRequest
SqsRequest (const Action action)
Constructs a new SqsRequest object.
SqsRequest (const SqsRequest &other)
Constructs a new SqsRequest object by copying another.
SqsRequest & operator= (const SqsRequest &other)
Assignment operator.
Action action () const
Get the SQS action to be performed by this request.
QString actionString () const
Get the name of the SQS action to be performed by this request.
QString apiVersion () const
Get the SQS API version implemented by this request.
void setAction (const Action action)
Set the SQS action to be performed by this request.
void setApiVersion (const QString &version)
Set the SQS API version to include in this request.
virtual bool operator== (const SqsRequest &other) const
Equality operator.
Public Member Functions inherited from AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const
Construct an SqsRemovePermissionResponse object.
Protected Member Functions inherited from SqsRequest
SqsRequest (SqsRequestPrivate *const d)
Constructs a new SqsRequest object.
int clearParameter (const QString &name)
Remove a parameter from the parameters to be included with this request.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this SQS request.
const QVariantMap & parameters () const
Get all parameters included with this SQS request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this SQS request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this SQS request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this SQS request.
Protected Member Functions inherited from AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
Friends
class TestSqsRemovePermissionRequest
Additional Inherited Members
Public Types inherited from SqsRequest
enum Action {
AddPermissionAction = 0x00001, ChangeMessageVisibilityAction = 0x00002, ChangeMessageVisibilityBatchAction = 0x00004, CreateQueueAction = 0x00008,
DeleteMessageAction = 0x00010, DeleteMessageBatchAction = 0x00020, DeleteQueueAction = 0x00040, GetQueueAttributesAction = 0x00080,
GetQueueUrlAction = 0x00100, ListDeadLetterSourceQueuesAction = 0x00200, ListQueuesAction = 0x00400, PurgeQueueAction = 0x00800,
ReceiveMessageAction = 0x01000, RemovePermissionAction = 0x02000, SendMessageAction = 0x04000, SendMessageBatchAction = 0x08000,
SetQueueAttributesAction = 0x10000
}
Actions supported by SQS.
Static Public Member Functions inherited from SqsRequest
static bool isValidQueueName (const QString &queueName)
Check if queueName is a valid SQS queue name.
Protected Attributes inherited from AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Implements SQS RemovePermission requests.
See also
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_RemovePermission.html
SqsRemovePermissionRequest
Definition at line 29 of file sqsremovepermissionrequest.h.
Constructor & Destructor Documentation
SqsRemovePermissionRequest() [1/2]
SqsRemovePermissionRequest::SqsRemovePermissionRequest (const QString & queueUrl, const QString & label)
Constructs a new SqsRemovePermissionRequest.
Parameters
queueUrl URL of the Amazon SQS queue to take action on.
label Identification of the permission to remove.
Definition at line 45 of file sqsremovepermissionrequest.cpp.
References setLabel(), and setQueueUrl().
     : SqsRequest(new SqsRemovePermissionRequestPrivate(SqsRequest::RemovePermissionAction, this))
 {
     setLabel(label);
     setQueueUrl(queueUrl);
 }
SqsRemovePermissionRequest() [2/2]
SqsRemovePermissionRequest::SqsRemovePermissionRequest (const SqsRemovePermissionRequest & other)
Constructs a new SqsRemovePermissionRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 58 of file sqsremovepermissionrequest.cpp.
     : SqsRequest(new SqsRemovePermissionRequestPrivate(*other.d_func(), this))
 {
 }
Member Function Documentation
isValid()
bool SqsRemovePermissionRequest::isValid () const virtual
Is this request valid?
Derived classes must implement this function to provide a level of request validation relevant to the type of request being implemented.
In this context, "valid" means that with valid credentials, the request's networkRequest method should return a request that the caller can reasonably expect AWS to accept (ignoring server side access restrictions and the like).
Returns
true if this request is considered valid, false other.
Implements AwsAbstractRequest.
Definition at line 73 of file sqsremovepermissionrequest.cpp.
References label(), and queueUrl().
 {
     return ((!queueUrl().isEmpty()) &&
             (!label().isEmpty()));
 }
label()
QString SqsRemovePermissionRequest::label () const
Get the identification of the permission to remove.
Returns
The identification of the permission to remove.
Definition at line 84 of file sqsremovepermissionrequest.cpp.
References SqsRequest::parameter().
Referenced by isValid().
 {
     return parameter(LABEL).toString();
 }
queueUrl()
QString SqsRemovePermissionRequest::queueUrl () const
Get the URL of the Amazon SQS queue to take action on.
Returns
The queue URL, or an empty string if not set.
Definition at line 94 of file sqsremovepermissionrequest.cpp.
References SqsRequest::parameter().
Referenced by isValid().
 {
     return parameter(QUEUE_URL).toString();
 }
response()
AwsAbstractResponse * SqsRemovePermissionRequest::response (QNetworkReply *const reply) const protected virtual
Construct an SqsRemovePermissionResponse object.
Parameters
reply Network reply this response should observe.
Returns
An SqsRemovePermissionResponse instance for reply.
See also
AwsAbstractClient::send
Implements AwsAbstractRequest.
Definition at line 128 of file sqsremovepermissionrequest.cpp.
 {
     return new SqsRemovePermissionResponse(*this, reply);
 }
setLabel()
void SqsRemovePermissionRequest::setLabel (const QString & label)
Set the identification of the permission to remove.
Parameters
label The identification of the permission to remove.
Definition at line 104 of file sqsremovepermissionrequest.cpp.
References SqsRequest::setParameter().
Referenced by SqsRemovePermissionRequest().
 {
     setParameter(LABEL, label);
 }
setQueueUrl()
void SqsRemovePermissionRequest::setQueueUrl (const QString & queueUrl)
Set the URL of the queue to add permissions to.
Parameters
queueUrl SQS queue URL.
Definition at line 114 of file sqsremovepermissionrequest.cpp.
References SqsRequest::setParameter().
Referenced by SqsRemovePermissionRequest().
 {
     setParameter(QUEUE_URL, queueUrl);
 }
The documentation for this class was generated from the following files:
sqs/sqsremovepermissionrequest.h
sqs/sqsremovepermissionrequest.cpp