libqtaws: AWS::Route53::Route53Client Class Reference
AWS::Route53::Route53Client Class Reference
Client for Amazon Route 53.
Public Slots
AssociateVPCWithHostedZoneResponse * associateVPCWithHostedZone (const AssociateVPCWithHostedZoneRequest &request)
ChangeResourceRecordSetsResponse * changeResourceRecordSets (const ChangeResourceRecordSetsRequest &request)
ChangeTagsForResourceResponse * changeTagsForResource (const ChangeTagsForResourceRequest &request)
CreateHealthCheckResponse * createHealthCheck (const CreateHealthCheckRequest &request)
CreateHostedZoneResponse * createHostedZone (const CreateHostedZoneRequest &request)
CreateQueryLoggingConfigResponse * createQueryLoggingConfig (const CreateQueryLoggingConfigRequest &request)
CreateReusableDelegationSetResponse * createReusableDelegationSet (const CreateReusableDelegationSetRequest &request)
CreateTrafficPolicyResponse * createTrafficPolicy (const CreateTrafficPolicyRequest &request)
CreateTrafficPolicyInstanceResponse * createTrafficPolicyInstance (const CreateTrafficPolicyInstanceRequest &request)
CreateTrafficPolicyVersionResponse * createTrafficPolicyVersion (const CreateTrafficPolicyVersionRequest &request)
CreateVPCAssociationAuthorizationResponse * createVPCAssociationAuthorization (const CreateVPCAssociationAuthorizationRequest &request)
DeleteHealthCheckResponse * deleteHealthCheck (const DeleteHealthCheckRequest &request)
DeleteHostedZoneResponse * deleteHostedZone (const DeleteHostedZoneRequest &request)
DeleteQueryLoggingConfigResponse * deleteQueryLoggingConfig (const DeleteQueryLoggingConfigRequest &request)
DeleteReusableDelegationSetResponse * deleteReusableDelegationSet (const DeleteReusableDelegationSetRequest &request)
DeleteTrafficPolicyResponse * deleteTrafficPolicy (const DeleteTrafficPolicyRequest &request)
DeleteTrafficPolicyInstanceResponse * deleteTrafficPolicyInstance (const DeleteTrafficPolicyInstanceRequest &request)
DeleteVPCAssociationAuthorizationResponse * deleteVPCAssociationAuthorization (const DeleteVPCAssociationAuthorizationRequest &request)
DisassociateVPCFromHostedZoneResponse * disassociateVPCFromHostedZone (const DisassociateVPCFromHostedZoneRequest &request)
GetAccountLimitResponse * getAccountLimit (const GetAccountLimitRequest &request)
GetChangeResponse * getChange (const GetChangeRequest &request)
GetCheckerIpRangesResponse * getCheckerIpRanges (const GetCheckerIpRangesRequest &request)
GetGeoLocationResponse * getGeoLocation (const GetGeoLocationRequest &request)
GetHealthCheckResponse * getHealthCheck (const GetHealthCheckRequest &request)
GetHealthCheckCountResponse * getHealthCheckCount (const GetHealthCheckCountRequest &request)
GetHealthCheckLastFailureReasonResponse * getHealthCheckLastFailureReason (const GetHealthCheckLastFailureReasonRequest &request)
GetHealthCheckStatusResponse * getHealthCheckStatus (const GetHealthCheckStatusRequest &request)
GetHostedZoneResponse * getHostedZone (const GetHostedZoneRequest &request)
GetHostedZoneCountResponse * getHostedZoneCount (const GetHostedZoneCountRequest &request)
GetHostedZoneLimitResponse * getHostedZoneLimit (const GetHostedZoneLimitRequest &request)
GetQueryLoggingConfigResponse * getQueryLoggingConfig (const GetQueryLoggingConfigRequest &request)
GetReusableDelegationSetResponse * getReusableDelegationSet (const GetReusableDelegationSetRequest &request)
GetReusableDelegationSetLimitResponse * getReusableDelegationSetLimit (const GetReusableDelegationSetLimitRequest &request)
GetTrafficPolicyResponse * getTrafficPolicy (const GetTrafficPolicyRequest &request)
GetTrafficPolicyInstanceResponse * getTrafficPolicyInstance (const GetTrafficPolicyInstanceRequest &request)
GetTrafficPolicyInstanceCountResponse * getTrafficPolicyInstanceCount (const GetTrafficPolicyInstanceCountRequest &request)
ListGeoLocationsResponse * listGeoLocations (const ListGeoLocationsRequest &request)
ListHealthChecksResponse * listHealthChecks (const ListHealthChecksRequest &request)
ListHostedZonesResponse * listHostedZones (const ListHostedZonesRequest &request)
ListHostedZonesByNameResponse * listHostedZonesByName (const ListHostedZonesByNameRequest &request)
ListQueryLoggingConfigsResponse * listQueryLoggingConfigs (const ListQueryLoggingConfigsRequest &request)
ListResourceRecordSetsResponse * listResourceRecordSets (const ListResourceRecordSetsRequest &request)
ListReusableDelegationSetsResponse * listReusableDelegationSets (const ListReusableDelegationSetsRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
ListTagsForResourcesResponse * listTagsForResources (const ListTagsForResourcesRequest &request)
ListTrafficPoliciesResponse * listTrafficPolicies (const ListTrafficPoliciesRequest &request)
ListTrafficPolicyInstancesResponse * listTrafficPolicyInstances (const ListTrafficPolicyInstancesRequest &request)
ListTrafficPolicyInstancesByHostedZoneResponse * listTrafficPolicyInstancesByHostedZone (const ListTrafficPolicyInstancesByHostedZoneRequest &request)
ListTrafficPolicyInstancesByPolicyResponse * listTrafficPolicyInstancesByPolicy (const ListTrafficPolicyInstancesByPolicyRequest &request)
ListTrafficPolicyVersionsResponse * listTrafficPolicyVersions (const ListTrafficPolicyVersionsRequest &request)
ListVPCAssociationAuthorizationsResponse * listVPCAssociationAuthorizations (const ListVPCAssociationAuthorizationsRequest &request)
TestDNSAnswerResponse * testDNSAnswer (const TestDNSAnswerRequest &request)
UpdateHealthCheckResponse * updateHealthCheck (const UpdateHealthCheckRequest &request)
UpdateHostedZoneCommentResponse * updateHostedZoneComment (const UpdateHostedZoneCommentRequest &request)
UpdateTrafficPolicyCommentResponse * updateTrafficPolicyComment (const UpdateTrafficPolicyCommentRequest &request)
UpdateTrafficPolicyInstanceResponse * updateTrafficPolicyInstance (const UpdateTrafficPolicyInstanceRequest &request)
Public Member Functions
Route53Client (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new Route53Client object.
Route53Client (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new Route53Client object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Route 53.
Definition at line 36 of file route53client.h.
Constructor & Destructor Documentation
Route53Client() [1/2]
AWS::Route53::Route53Client::Route53Client (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new Route53Client object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 46 of file route53client.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new Route53ClientPrivate(this), parent)
 {
     Q_D(Route53Client);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
Route53Client() [2/2]
AWS::Route53::Route53Client::Route53Client (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new Route53Client object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 76 of file route53client.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new Route53ClientPrivate(this), parent)
 {
     Q_D(Route53Client);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
route53/route53client.h
route53/route53client.cpp