libqtaws: KinesisAnalyticsClient Class Reference
KinesisAnalyticsClient Class Reference
Client for Amazon Kinesis Analytics.
Public Slots
KinesisAnalyticsAddApplicationInputResponse * addApplicationInput (const KinesisAnalyticsAddApplicationInputRequest &request)
KinesisAnalyticsAddApplicationOutputResponse * addApplicationOutput (const KinesisAnalyticsAddApplicationOutputRequest &request)
KinesisAnalyticsAddApplicationReferenceDataSourceResponse * addApplicationReferenceDataSource (const KinesisAnalyticsAddApplicationReferenceDataSourceRequest &request)
KinesisAnalyticsCreateApplicationResponse * createApplication (const KinesisAnalyticsCreateApplicationRequest &request)
KinesisAnalyticsDeleteApplicationResponse * deleteApplication (const KinesisAnalyticsDeleteApplicationRequest &request)
KinesisAnalyticsDeleteApplicationOutputResponse * deleteApplicationOutput (const KinesisAnalyticsDeleteApplicationOutputRequest &request)
KinesisAnalyticsDeleteApplicationReferenceDataSourceResponse * deleteApplicationReferenceDataSource (const KinesisAnalyticsDeleteApplicationReferenceDataSourceRequest &request)
KinesisAnalyticsDescribeApplicationResponse * describeApplication (const KinesisAnalyticsDescribeApplicationRequest &request)
KinesisAnalyticsDiscoverInputSchemaResponse * discoverInputSchema (const KinesisAnalyticsDiscoverInputSchemaRequest &request)
KinesisAnalyticsListApplicationsResponse * listApplications (const KinesisAnalyticsListApplicationsRequest &request)
KinesisAnalyticsStartApplicationResponse * startApplication (const KinesisAnalyticsStartApplicationRequest &request)
KinesisAnalyticsStopApplicationResponse * stopApplication (const KinesisAnalyticsStopApplicationRequest &request)
KinesisAnalyticsUpdateApplicationResponse * updateApplication (const KinesisAnalyticsUpdateApplicationRequest &request)
Public Member Functions
KinesisAnalyticsClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new KinesisAnalyticsClient object.
KinesisAnalyticsClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new KinesisAnalyticsClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Kinesis Analytics.
Definition at line 33 of file kinesisanalyticsclient.h.
Constructor & Destructor Documentation
KinesisAnalyticsClient::KinesisAnalyticsClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new KinesisAnalyticsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 46 of file kinesisanalyticsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new KinesisAnalyticsClientPrivate(this), parent)
 {
     Q_D(KinesisAnalyticsClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
KinesisAnalyticsClient::KinesisAnalyticsClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new KinesisAnalyticsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 76 of file kinesisanalyticsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new KinesisAnalyticsClientPrivate(this), parent)
 {
     Q_D(KinesisAnalyticsClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
kinesisanalytics/kinesisanalyticsclient.h
kinesisanalytics/kinesisanalyticsclient.cpp