libqtaws: AWS::DeviceFarm::DeviceFarmClient Class Reference
AWS::DeviceFarm::DeviceFarmClient Class Reference
Client for AWS Device Farm.
Public Slots
CreateDevicePoolResponse * createDevicePool (const CreateDevicePoolRequest &request)
CreateNetworkProfileResponse * createNetworkProfile (const CreateNetworkProfileRequest &request)
CreateProjectResponse * createProject (const CreateProjectRequest &request)
CreateRemoteAccessSessionResponse * createRemoteAccessSession (const CreateRemoteAccessSessionRequest &request)
CreateUploadResponse * createUpload (const CreateUploadRequest &request)
DeleteDevicePoolResponse * deleteDevicePool (const DeleteDevicePoolRequest &request)
DeleteNetworkProfileResponse * deleteNetworkProfile (const DeleteNetworkProfileRequest &request)
DeleteProjectResponse * deleteProject (const DeleteProjectRequest &request)
DeleteRemoteAccessSessionResponse * deleteRemoteAccessSession (const DeleteRemoteAccessSessionRequest &request)
DeleteRunResponse * deleteRun (const DeleteRunRequest &request)
DeleteUploadResponse * deleteUpload (const DeleteUploadRequest &request)
GetAccountSettingsResponse * getAccountSettings (const GetAccountSettingsRequest &request)
GetDeviceResponse * getDevice (const GetDeviceRequest &request)
GetDevicePoolResponse * getDevicePool (const GetDevicePoolRequest &request)
GetDevicePoolCompatibilityResponse * getDevicePoolCompatibility (const GetDevicePoolCompatibilityRequest &request)
GetJobResponse * getJob (const GetJobRequest &request)
GetNetworkProfileResponse * getNetworkProfile (const GetNetworkProfileRequest &request)
GetOfferingStatusResponse * getOfferingStatus (const GetOfferingStatusRequest &request)
GetProjectResponse * getProject (const GetProjectRequest &request)
GetRemoteAccessSessionResponse * getRemoteAccessSession (const GetRemoteAccessSessionRequest &request)
GetRunResponse * getRun (const GetRunRequest &request)
GetSuiteResponse * getSuite (const GetSuiteRequest &request)
GetTestResponse * getTest (const GetTestRequest &request)
GetUploadResponse * getUpload (const GetUploadRequest &request)
InstallToRemoteAccessSessionResponse * installToRemoteAccessSession (const InstallToRemoteAccessSessionRequest &request)
ListArtifactsResponse * listArtifacts (const ListArtifactsRequest &request)
ListDevicePoolsResponse * listDevicePools (const ListDevicePoolsRequest &request)
ListDevicesResponse * listDevices (const ListDevicesRequest &request)
ListJobsResponse * listJobs (const ListJobsRequest &request)
ListNetworkProfilesResponse * listNetworkProfiles (const ListNetworkProfilesRequest &request)
ListOfferingPromotionsResponse * listOfferingPromotions (const ListOfferingPromotionsRequest &request)
ListOfferingTransactionsResponse * listOfferingTransactions (const ListOfferingTransactionsRequest &request)
ListOfferingsResponse * listOfferings (const ListOfferingsRequest &request)
ListProjectsResponse * listProjects (const ListProjectsRequest &request)
ListRemoteAccessSessionsResponse * listRemoteAccessSessions (const ListRemoteAccessSessionsRequest &request)
ListRunsResponse * listRuns (const ListRunsRequest &request)
ListSamplesResponse * listSamples (const ListSamplesRequest &request)
ListSuitesResponse * listSuites (const ListSuitesRequest &request)
ListTestsResponse * listTests (const ListTestsRequest &request)
ListUniqueProblemsResponse * listUniqueProblems (const ListUniqueProblemsRequest &request)
ListUploadsResponse * listUploads (const ListUploadsRequest &request)
PurchaseOfferingResponse * purchaseOffering (const PurchaseOfferingRequest &request)
RenewOfferingResponse * renewOffering (const RenewOfferingRequest &request)
ScheduleRunResponse * scheduleRun (const ScheduleRunRequest &request)
StopRemoteAccessSessionResponse * stopRemoteAccessSession (const StopRemoteAccessSessionRequest &request)
StopRunResponse * stopRun (const StopRunRequest &request)
UpdateDevicePoolResponse * updateDevicePool (const UpdateDevicePoolRequest &request)
UpdateNetworkProfileResponse * updateNetworkProfile (const UpdateNetworkProfileRequest &request)
UpdateProjectResponse * updateProject (const UpdateProjectRequest &request)
Public Member Functions
DeviceFarmClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DeviceFarmClient object.
DeviceFarmClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DeviceFarmClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Device Farm.
AWS Device Farm is a service that enables mobile app developers to test Android, iOS, and Fire OS apps on physical phones, tablets, and other devices in the
Definition at line 36 of file devicefarmclient.h.
Constructor & Destructor Documentation
DeviceFarmClient() [1/2]
AWS::DeviceFarm::DeviceFarmClient::DeviceFarmClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DeviceFarmClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 48 of file devicefarmclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new DeviceFarmClientPrivate(this), parent)
 {
     Q_D(DeviceFarmClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
DeviceFarmClient() [2/2]
AWS::DeviceFarm::DeviceFarmClient::DeviceFarmClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DeviceFarmClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 78 of file devicefarmclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new DeviceFarmClientPrivate(this), parent)
 {
     Q_D(DeviceFarmClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
devicefarm/devicefarmclient.h
devicefarm/devicefarmclient.cpp