libqtaws: AWS::Rekognition::RekognitionClient Class Reference
AWS::Rekognition::RekognitionClient Class Reference
Client for Amazon Rekognition.
Public Slots
CompareFacesResponse * compareFaces (const CompareFacesRequest &request)
CreateCollectionResponse * createCollection (const CreateCollectionRequest &request)
CreateStreamProcessorResponse * createStreamProcessor (const CreateStreamProcessorRequest &request)
DeleteCollectionResponse * deleteCollection (const DeleteCollectionRequest &request)
DeleteFacesResponse * deleteFaces (const DeleteFacesRequest &request)
DeleteStreamProcessorResponse * deleteStreamProcessor (const DeleteStreamProcessorRequest &request)
DescribeStreamProcessorResponse * describeStreamProcessor (const DescribeStreamProcessorRequest &request)
DetectFacesResponse * detectFaces (const DetectFacesRequest &request)
DetectLabelsResponse * detectLabels (const DetectLabelsRequest &request)
DetectModerationLabelsResponse * detectModerationLabels (const DetectModerationLabelsRequest &request)
DetectTextResponse * detectText (const DetectTextRequest &request)
GetCelebrityInfoResponse * getCelebrityInfo (const GetCelebrityInfoRequest &request)
GetCelebrityRecognitionResponse * getCelebrityRecognition (const GetCelebrityRecognitionRequest &request)
GetContentModerationResponse * getContentModeration (const GetContentModerationRequest &request)
GetFaceDetectionResponse * getFaceDetection (const GetFaceDetectionRequest &request)
GetFaceSearchResponse * getFaceSearch (const GetFaceSearchRequest &request)
GetLabelDetectionResponse * getLabelDetection (const GetLabelDetectionRequest &request)
GetPersonTrackingResponse * getPersonTracking (const GetPersonTrackingRequest &request)
IndexFacesResponse * indexFaces (const IndexFacesRequest &request)
ListCollectionsResponse * listCollections (const ListCollectionsRequest &request)
ListFacesResponse * listFaces (const ListFacesRequest &request)
ListStreamProcessorsResponse * listStreamProcessors (const ListStreamProcessorsRequest &request)
RecognizeCelebritiesResponse * recognizeCelebrities (const RecognizeCelebritiesRequest &request)
SearchFacesResponse * searchFaces (const SearchFacesRequest &request)
SearchFacesByImageResponse * searchFacesByImage (const SearchFacesByImageRequest &request)
StartCelebrityRecognitionResponse * startCelebrityRecognition (const StartCelebrityRecognitionRequest &request)
StartContentModerationResponse * startContentModeration (const StartContentModerationRequest &request)
StartFaceDetectionResponse * startFaceDetection (const StartFaceDetectionRequest &request)
StartFaceSearchResponse * startFaceSearch (const StartFaceSearchRequest &request)
StartLabelDetectionResponse * startLabelDetection (const StartLabelDetectionRequest &request)
StartPersonTrackingResponse * startPersonTracking (const StartPersonTrackingRequest &request)
StartStreamProcessorResponse * startStreamProcessor (const StartStreamProcessorRequest &request)
StopStreamProcessorResponse * stopStreamProcessor (const StopStreamProcessorRequest &request)
Public Member Functions
RekognitionClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new RekognitionClient object.
RekognitionClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new RekognitionClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Rekognition.
This is the Amazon Rekognition API
Definition at line 36 of file rekognitionclient.h.
Constructor & Destructor Documentation
RekognitionClient() [1/2]
AWS::Rekognition::RekognitionClient::RekognitionClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new RekognitionClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 47 of file rekognitionclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new RekognitionClientPrivate(this), parent)
 {
     Q_D(RekognitionClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
RekognitionClient() [2/2]
AWS::Rekognition::RekognitionClient::RekognitionClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new RekognitionClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 77 of file rekognitionclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new RekognitionClientPrivate(this), parent)
 {
     Q_D(RekognitionClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
rekognition/rekognitionclient.h
rekognition/rekognitionclient.cpp