libqtaws: CloudHSMClient Class Reference
CloudHSMClient Class Reference
Client for Amazon CloudHSM.
Public Slots
CloudHSMAddTagsToResourceResponse * addTagsToResource (const CloudHSMAddTagsToResourceRequest &request)
CloudHSMCreateHapgResponse * createHapg (const CloudHSMCreateHapgRequest &request)
CloudHSMCreateHsmResponse * createHsm (const CloudHSMCreateHsmRequest &request)
CloudHSMCreateLunaClientResponse * createLunaClient (const CloudHSMCreateLunaClientRequest &request)
CloudHSMDeleteHapgResponse * deleteHapg (const CloudHSMDeleteHapgRequest &request)
CloudHSMDeleteHsmResponse * deleteHsm (const CloudHSMDeleteHsmRequest &request)
CloudHSMDeleteLunaClientResponse * deleteLunaClient (const CloudHSMDeleteLunaClientRequest &request)
CloudHSMDescribeHapgResponse * describeHapg (const CloudHSMDescribeHapgRequest &request)
CloudHSMDescribeHsmResponse * describeHsm (const CloudHSMDescribeHsmRequest &request)
CloudHSMDescribeLunaClientResponse * describeLunaClient (const CloudHSMDescribeLunaClientRequest &request)
CloudHSMGetConfigResponse * getConfig (const CloudHSMGetConfigRequest &request)
CloudHSMListAvailableZonesResponse * listAvailableZones (const CloudHSMListAvailableZonesRequest &request)
CloudHSMListHapgsResponse * listHapgs (const CloudHSMListHapgsRequest &request)
CloudHSMListHsmsResponse * listHsms (const CloudHSMListHsmsRequest &request)
CloudHSMListLunaClientsResponse * listLunaClients (const CloudHSMListLunaClientsRequest &request)
CloudHSMListTagsForResourceResponse * listTagsForResource (const CloudHSMListTagsForResourceRequest &request)
CloudHSMModifyHapgResponse * modifyHapg (const CloudHSMModifyHapgRequest &request)
CloudHSMModifyHsmResponse * modifyHsm (const CloudHSMModifyHsmRequest &request)
CloudHSMModifyLunaClientResponse * modifyLunaClient (const CloudHSMModifyLunaClientRequest &request)
CloudHSMRemoveTagsFromResourceResponse * removeTagsFromResource (const CloudHSMRemoveTagsFromResourceRequest &request)
Public Member Functions
CloudHSMClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudHSMClient object.
CloudHSMClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudHSMClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon CloudHSM.
<fullname>AWS CloudHSM Service</fullname>
Definition at line 33 of file cloudhsmclient.h.
Constructor & Destructor Documentation
CloudHSMClient::CloudHSMClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudHSMClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 46 of file cloudhsmclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new CloudHSMClientPrivate(this), parent)
 {
     Q_D(CloudHSMClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
CloudHSMClient::CloudHSMClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudHSMClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 76 of file cloudhsmclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new CloudHSMClientPrivate(this), parent)
 {
     Q_D(CloudHSMClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
cloudhsm/cloudhsmclient.h
cloudhsm/cloudhsmclient.cpp