libqtaws: ServiceCatalogClient Class Reference
ServiceCatalogClient Class Reference
Client for AWS Service Catalog.
Public Slots
ServiceCatalogDescribeProductResponse * describeProduct (const ServiceCatalogDescribeProductRequest &request)
ServiceCatalogDescribeProductViewResponse * describeProductView (const ServiceCatalogDescribeProductViewRequest &request)
ServiceCatalogDescribeProvisioningParametersResponse * describeProvisioningParameters (const ServiceCatalogDescribeProvisioningParametersRequest &request)
ServiceCatalogDescribeRecordResponse * describeRecord (const ServiceCatalogDescribeRecordRequest &request)
ServiceCatalogListLaunchPathsResponse * listLaunchPaths (const ServiceCatalogListLaunchPathsRequest &request)
ServiceCatalogListRecordHistoryResponse * listRecordHistory (const ServiceCatalogListRecordHistoryRequest &request)
ServiceCatalogProvisionProductResponse * provisionProduct (const ServiceCatalogProvisionProductRequest &request)
ServiceCatalogScanProvisionedProductsResponse * scanProvisionedProducts (const ServiceCatalogScanProvisionedProductsRequest &request)
ServiceCatalogSearchProductsResponse * searchProducts (const ServiceCatalogSearchProductsRequest &request)
ServiceCatalogTerminateProvisionedProductResponse * terminateProvisionedProduct (const ServiceCatalogTerminateProvisionedProductRequest &request)
ServiceCatalogUpdateProvisionedProductResponse * updateProvisionedProduct (const ServiceCatalogUpdateProvisionedProductRequest &request)
Public Member Functions
ServiceCatalogClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ServiceCatalogClient object.
ServiceCatalogClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ServiceCatalogClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Service Catalog.
<fullname>AWS Service Catalog</fullname>
Overview
AWS Service Catalog allows organizations to create and manage catalogs of IT services that are approved for use on AWS. This documentation provides reference material for the AWS Service Catalog end user API. To get the most out of this documentation, you need to be familiar with the terminology discussed in AWS Service Catalog Concepts.
Additional Resources
AWS Service Catalog Administrator Guide
AWS Service Catalog User Guide
Definition at line 33 of file servicecatalogclient.h.
Constructor & Destructor Documentation
ServiceCatalogClient::ServiceCatalogClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ServiceCatalogClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 62 of file servicecatalogclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new ServiceCatalogClientPrivate(this), parent)
 {
     Q_D(ServiceCatalogClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
ServiceCatalogClient::ServiceCatalogClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ServiceCatalogClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 92 of file servicecatalogclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new ServiceCatalogClientPrivate(this), parent)
 {
     Q_D(ServiceCatalogClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
servicecatalog/servicecatalogclient.h
servicecatalog/servicecatalogclient.cpp