libqtaws: APIGatewayClient Class Reference
APIGatewayClient Class Reference
Client for Amazon API Gateway.
Public Slots
APIGatewayCreateApiKeyResponse * createApiKey (const APIGatewayCreateApiKeyRequest &request)
APIGatewayCreateAuthorizerResponse * createAuthorizer (const APIGatewayCreateAuthorizerRequest &request)
APIGatewayCreateBasePathMappingResponse * createBasePathMapping (const APIGatewayCreateBasePathMappingRequest &request)
APIGatewayCreateDeploymentResponse * createDeployment (const APIGatewayCreateDeploymentRequest &request)
APIGatewayCreateDomainNameResponse * createDomainName (const APIGatewayCreateDomainNameRequest &request)
APIGatewayCreateModelResponse * createModel (const APIGatewayCreateModelRequest &request)
APIGatewayCreateResourceResponse * createResource (const APIGatewayCreateResourceRequest &request)
APIGatewayCreateRestApiResponse * createRestApi (const APIGatewayCreateRestApiRequest &request)
APIGatewayCreateStageResponse * createStage (const APIGatewayCreateStageRequest &request)
APIGatewayCreateUsagePlanResponse * createUsagePlan (const APIGatewayCreateUsagePlanRequest &request)
APIGatewayCreateUsagePlanKeyResponse * createUsagePlanKey (const APIGatewayCreateUsagePlanKeyRequest &request)
APIGatewayDeleteApiKeyResponse * deleteApiKey (const APIGatewayDeleteApiKeyRequest &request)
APIGatewayDeleteAuthorizerResponse * deleteAuthorizer (const APIGatewayDeleteAuthorizerRequest &request)
APIGatewayDeleteBasePathMappingResponse * deleteBasePathMapping (const APIGatewayDeleteBasePathMappingRequest &request)
APIGatewayDeleteClientCertificateResponse * deleteClientCertificate (const APIGatewayDeleteClientCertificateRequest &request)
APIGatewayDeleteDeploymentResponse * deleteDeployment (const APIGatewayDeleteDeploymentRequest &request)
APIGatewayDeleteDomainNameResponse * deleteDomainName (const APIGatewayDeleteDomainNameRequest &request)
APIGatewayDeleteIntegrationResponse * deleteIntegration (const APIGatewayDeleteIntegrationRequest &request)
APIGatewayDeleteIntegrationResponseResponse * deleteIntegrationResponse (const APIGatewayDeleteIntegrationResponseRequest &request)
APIGatewayDeleteMethodResponse * deleteMethod (const APIGatewayDeleteMethodRequest &request)
APIGatewayDeleteMethodResponseResponse * deleteMethodResponse (const APIGatewayDeleteMethodResponseRequest &request)
APIGatewayDeleteModelResponse * deleteModel (const APIGatewayDeleteModelRequest &request)
APIGatewayDeleteResourceResponse * deleteResource (const APIGatewayDeleteResourceRequest &request)
APIGatewayDeleteRestApiResponse * deleteRestApi (const APIGatewayDeleteRestApiRequest &request)
APIGatewayDeleteStageResponse * deleteStage (const APIGatewayDeleteStageRequest &request)
APIGatewayDeleteUsagePlanResponse * deleteUsagePlan (const APIGatewayDeleteUsagePlanRequest &request)
APIGatewayDeleteUsagePlanKeyResponse * deleteUsagePlanKey (const APIGatewayDeleteUsagePlanKeyRequest &request)
APIGatewayFlushStageAuthorizersCacheResponse * flushStageAuthorizersCache (const APIGatewayFlushStageAuthorizersCacheRequest &request)
APIGatewayFlushStageCacheResponse * flushStageCache (const APIGatewayFlushStageCacheRequest &request)
APIGatewayGenerateClientCertificateResponse * generateClientCertificate (const APIGatewayGenerateClientCertificateRequest &request)
APIGatewayGetAccountResponse * getAccount (const APIGatewayGetAccountRequest &request)
APIGatewayGetApiKeyResponse * getApiKey (const APIGatewayGetApiKeyRequest &request)
APIGatewayGetApiKeysResponse * getApiKeys (const APIGatewayGetApiKeysRequest &request)
APIGatewayGetAuthorizerResponse * getAuthorizer (const APIGatewayGetAuthorizerRequest &request)
APIGatewayGetAuthorizersResponse * getAuthorizers (const APIGatewayGetAuthorizersRequest &request)
APIGatewayGetBasePathMappingResponse * getBasePathMapping (const APIGatewayGetBasePathMappingRequest &request)
APIGatewayGetBasePathMappingsResponse * getBasePathMappings (const APIGatewayGetBasePathMappingsRequest &request)
APIGatewayGetClientCertificateResponse * getClientCertificate (const APIGatewayGetClientCertificateRequest &request)
APIGatewayGetClientCertificatesResponse * getClientCertificates (const APIGatewayGetClientCertificatesRequest &request)
APIGatewayGetDeploymentResponse * getDeployment (const APIGatewayGetDeploymentRequest &request)
APIGatewayGetDeploymentsResponse * getDeployments (const APIGatewayGetDeploymentsRequest &request)
APIGatewayGetDomainNameResponse * getDomainName (const APIGatewayGetDomainNameRequest &request)
APIGatewayGetDomainNamesResponse * getDomainNames (const APIGatewayGetDomainNamesRequest &request)
APIGatewayGetExportResponse * getExport (const APIGatewayGetExportRequest &request)
APIGatewayGetIntegrationResponse * getIntegration (const APIGatewayGetIntegrationRequest &request)
APIGatewayGetIntegrationResponseResponse * getIntegrationResponse (const APIGatewayGetIntegrationResponseRequest &request)
APIGatewayGetMethodResponse * getMethod (const APIGatewayGetMethodRequest &request)
APIGatewayGetMethodResponseResponse * getMethodResponse (const APIGatewayGetMethodResponseRequest &request)
APIGatewayGetModelResponse * getModel (const APIGatewayGetModelRequest &request)
APIGatewayGetModelTemplateResponse * getModelTemplate (const APIGatewayGetModelTemplateRequest &request)
APIGatewayGetModelsResponse * getModels (const APIGatewayGetModelsRequest &request)
APIGatewayGetResourceResponse * getResource (const APIGatewayGetResourceRequest &request)
APIGatewayGetResourcesResponse * getResources (const APIGatewayGetResourcesRequest &request)
APIGatewayGetRestApiResponse * getRestApi (const APIGatewayGetRestApiRequest &request)
APIGatewayGetRestApisResponse * getRestApis (const APIGatewayGetRestApisRequest &request)
APIGatewayGetSdkResponse * getSdk (const APIGatewayGetSdkRequest &request)
APIGatewayGetStageResponse * getStage (const APIGatewayGetStageRequest &request)
APIGatewayGetStagesResponse * getStages (const APIGatewayGetStagesRequest &request)
APIGatewayGetUsageResponse * getUsage (const APIGatewayGetUsageRequest &request)
APIGatewayGetUsagePlanResponse * getUsagePlan (const APIGatewayGetUsagePlanRequest &request)
APIGatewayGetUsagePlanKeyResponse * getUsagePlanKey (const APIGatewayGetUsagePlanKeyRequest &request)
APIGatewayGetUsagePlanKeysResponse * getUsagePlanKeys (const APIGatewayGetUsagePlanKeysRequest &request)
APIGatewayGetUsagePlansResponse * getUsagePlans (const APIGatewayGetUsagePlansRequest &request)
APIGatewayImportApiKeysResponse * importApiKeys (const APIGatewayImportApiKeysRequest &request)
APIGatewayImportRestApiResponse * importRestApi (const APIGatewayImportRestApiRequest &request)
APIGatewayPutIntegrationResponse * putIntegration (const APIGatewayPutIntegrationRequest &request)
APIGatewayPutIntegrationResponseResponse * putIntegrationResponse (const APIGatewayPutIntegrationResponseRequest &request)
APIGatewayPutMethodResponse * putMethod (const APIGatewayPutMethodRequest &request)
APIGatewayPutMethodResponseResponse * putMethodResponse (const APIGatewayPutMethodResponseRequest &request)
APIGatewayPutRestApiResponse * putRestApi (const APIGatewayPutRestApiRequest &request)
APIGatewayTestInvokeAuthorizerResponse * testInvokeAuthorizer (const APIGatewayTestInvokeAuthorizerRequest &request)
APIGatewayTestInvokeMethodResponse * testInvokeMethod (const APIGatewayTestInvokeMethodRequest &request)
APIGatewayUpdateAccountResponse * updateAccount (const APIGatewayUpdateAccountRequest &request)
APIGatewayUpdateApiKeyResponse * updateApiKey (const APIGatewayUpdateApiKeyRequest &request)
APIGatewayUpdateAuthorizerResponse * updateAuthorizer (const APIGatewayUpdateAuthorizerRequest &request)
APIGatewayUpdateBasePathMappingResponse * updateBasePathMapping (const APIGatewayUpdateBasePathMappingRequest &request)
APIGatewayUpdateClientCertificateResponse * updateClientCertificate (const APIGatewayUpdateClientCertificateRequest &request)
APIGatewayUpdateDeploymentResponse * updateDeployment (const APIGatewayUpdateDeploymentRequest &request)
APIGatewayUpdateDomainNameResponse * updateDomainName (const APIGatewayUpdateDomainNameRequest &request)
APIGatewayUpdateIntegrationResponse * updateIntegration (const APIGatewayUpdateIntegrationRequest &request)
APIGatewayUpdateIntegrationResponseResponse * updateIntegrationResponse (const APIGatewayUpdateIntegrationResponseRequest &request)
APIGatewayUpdateMethodResponse * updateMethod (const APIGatewayUpdateMethodRequest &request)
APIGatewayUpdateMethodResponseResponse * updateMethodResponse (const APIGatewayUpdateMethodResponseRequest &request)
APIGatewayUpdateModelResponse * updateModel (const APIGatewayUpdateModelRequest &request)
APIGatewayUpdateResourceResponse * updateResource (const APIGatewayUpdateResourceRequest &request)
APIGatewayUpdateRestApiResponse * updateRestApi (const APIGatewayUpdateRestApiRequest &request)
APIGatewayUpdateStageResponse * updateStage (const APIGatewayUpdateStageRequest &request)
APIGatewayUpdateUsageResponse * updateUsage (const APIGatewayUpdateUsageRequest &request)
APIGatewayUpdateUsagePlanResponse * updateUsagePlan (const APIGatewayUpdateUsagePlanRequest &request)
Public Member Functions
APIGatewayClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new APIGatewayClient object.
APIGatewayClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new APIGatewayClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon API Gateway.
<fullname>Amazon API Gateway</fullname>
Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. Amazon API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.
Definition at line 33 of file apigatewayclient.h.
Constructor & Destructor Documentation
APIGatewayClient::APIGatewayClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new APIGatewayClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 48 of file apigatewayclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new APIGatewayClientPrivate(this), parent)
 {
     Q_D(APIGatewayClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
APIGatewayClient::APIGatewayClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new APIGatewayClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 78 of file apigatewayclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new APIGatewayClientPrivate(this), parent)
 {
     Q_D(APIGatewayClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
apigateway/apigatewayclient.h
apigateway/apigatewayclient.cpp