libqtaws: AwsSignatureV0 Class Reference
AwsSignatureV0 Class Reference
Implements AWS Signature Version 0 (deprecated by Amazon).
Public Member Functions
AwsSignatureV0 ()
Constructs a new AwsSignatureV0 object.
virtual void sign (const AwsAbstractCredentials &credentials, const QNetworkAccessManager::Operation operation, QNetworkRequest &request, const QByteArray &data=QByteArray()) const
Sign an AWS request.
virtual int version () const
AWS Signature version implemented by this class.
Public Member Functions inherited from AwsAbstractSignature
AwsAbstractSignature ()
Initialises an AwsAbstractSignature object.
virtual ~AwsAbstractSignature ()
AwsAbstractSignature destructor.
Protected Member Functions
AwsSignatureV0 (AwsSignatureV0Private *const d)
Constructs a new AwsSignatureV0 object with a specific private implementation.
Protected Member Functions inherited from AwsAbstractSignature
AwsAbstractSignature (AwsAbstractSignaturePrivate *const d)
Initialises an AwsAbstractSignature object.
Friends
class TestAwsSignatureV0
Additional Inherited Members
Protected Attributes inherited from AwsAbstractSignature
AwsAbstractSignaturePrivate *const d_ptr
Internal d-pointer.
Detailed Description
Implements AWS Signature Version 0 (deprecated by Amazon).
Deprecated:
Amazon has officially deprecated signature Version 0 in favor of later, more secure signatures, such as AwsSignatureV2 and AwsSignatureV4.
As version 0 signatures are rightly regarded as insecure, this class will refuse to sign requests that use insecure transports such as HTTP instead of HTTPS. However, insecure signatures can be enabled (why would you want to?) by defining QTAWS_ALLOW_INSECURE_SIGNATURES when compiling this library.
See also
http://s3.amazonaws.com/awsdocs/SQS/20070501/sqs-dg-20070501.pdf
Definition at line 30 of file awssignaturev0.h.
Constructor & Destructor Documentation
AwsSignatureV0::AwsSignatureV0 ()
Constructs a new AwsSignatureV0 object.
Use instances of this object to provide Version 0 signatures for AWS services.
Definition at line 57 of file awssignaturev0.cpp.
                                : AwsAbstractSignature(new AwsSignatureV0Private(this))
 {
 }
AwsSignatureV0::AwsSignatureV0 (AwsSignatureV0Private *const d) protected
Constructs a new AwsSignatureV0 object with a specific private implementation.
This internal constructor allows derived classes to provide their own derived private implementation. Specifically, AwsSignatureV1 uses this constructor to extend this class.
Parameters
d Internal private implementation to use.
See also
AwsSignatureV1
Definition at line 75 of file awssignaturev0.cpp.
                                                               : AwsAbstractSignature(d)
 {
 }
Member Function Documentation
void AwsSignatureV0::sign (const AwsAbstractCredentials & credentials, const QNetworkAccessManager::Operation operation, QNetworkRequest & request, const QByteArray & data = QByteArray()) const virtual
Sign an AWS request.
Note, credentials must be valid before calling this function. So, for example, if credentials has expired, and is refreshable, it is the caller's responsibility to refresh the credentials before calling this function.
Parameters
operation The network operation to sign request for.
request The network request to be signed.
credentials The credentials to use for signing.
data Optional POST / PUT data to sign request for.
Implements AwsAbstractSignature.
Definition at line 80 of file awssignaturev0.cpp.
References AwsAbstractCredentials::secretKey(), and version().
 {
     Q_UNUSED(operation) // Not included in V0 signatures.
     Q_UNUSED(data)      // Not included in V0 signatures.
     Q_D(const AwsSignatureV0);
     // Refuse to sign non-HTTPS requests, unless built with QTAWS_ALLOW_INSECURE_SIGNATURES defined.
 #ifndef QTAWS_ALLOW_INSECURE_SIGNATURES
     if (request.url().scheme() != QString::fromLatin1("https")) {
         qWarning("AwsSignatureV%d::sign Refusing to sign insecure (non-HTTPS) request", version());
         Q_ASSERT_X(false, Q_FUNC_INFO, "insecure V1 signatures not enabled");
         return;
     }
 #endif
     // Set the AWSAccessKeyId, SignatureVersion and Timestamp query items, if not already.
     d->adornRequest(request, credentials);
     // Calculate the signature.
     const QByteArray stringToSign = d->canonicalQuery(QUrlQuery(request.url().query()));
     const QString signature = QString::fromUtf8(QUrl::toPercentEncoding(QString::fromUtf8(
         QMessageAuthenticationCode::hash(stringToSign, credentials.secretKey().toUtf8(),
                                          QCryptographicHash::Sha1).toBase64())));
     // Append the signature to the request.
     QUrl url = request.url();
     url.setQuery(url.query() + QLatin1String("&Signature=") + signature);
     request.setUrl(url);
 }
int AwsSignatureV0::version () const virtual
AWS Signature version implemented by this class.
Derived classes must implement this function to report the version of the AWS Signature implemented by the class.
Returns
The AWS Signature version implemented by this class.
Implements AwsAbstractSignature.
Reimplemented in AwsSignatureV1.
Definition at line 111 of file awssignaturev0.cpp.
Referenced by sign().
 {
     return 0;
 }
The documentation for this class was generated from the following files:
core/awssignaturev0.h
core/awssignaturev0.cpp