libqtaws: AwsSignatureV2Private Class Reference
AwsSignatureV2Private Class Reference
Private implementation for AwsSignatureV2.
Public Member Functions
AwsSignatureV2Private (const QCryptographicHash::Algorithm algorithm, AwsSignatureV2 *const q)
Constructs a new AwsSignatureV2Private object.
void adornRequest (QNetworkRequest &request, const AwsAbstractCredentials &credentials) const
Add AWS Signature Version 2 adornments to an AWS request.
QByteArray canonicalRequest (const QNetworkAccessManager::Operation operation, const QUrl &url) const
Create an AWS V2 Signature canonical request.
QByteArray signatureMethod (const QCryptographicHash::Algorithm algorithm) const
Create an AWS V2 Signature method designation.
Public Member Functions inherited from AwsAbstractSignaturePrivate
virtual ~AwsAbstractSignaturePrivate ()
AwsAbstractSignaturePrivate destructor.
AwsAbstractSignaturePrivate (AwsAbstractSignature *const q)
Constructs a new AwsAbstractSignaturePrivate object.
QString canonicalPath (const QUrl &url) const
Create an AWS Signature canonical path.
QByteArray canonicalQuery (const QUrlQuery &query) const
Create an AWS Signature canonical query.
QString httpMethod (const QNetworkAccessManager::Operation operation) const
Create an AWS Signature request method string.
bool setQueryItem (QUrlQuery &query, const QString &key, const QString &value, const bool warnOnNonIdenticalDuplicate=true) const
Set a query item, checking for existing values first.
Public Attributes
QCryptographicHash::Algorithm hashAlgorithm
Hash algorithm to use when signing.
Friends
class TestAwsSignatureV2
Additional Inherited Members
Protected Attributes inherited from AwsAbstractSignaturePrivate
AwsAbstractSignature *const q_ptr
Internal q-pointer.
Detailed Description
Private implementation for AwsSignatureV2.
Warning
This is an internal private implementation class, and as such external should code should not depend directly on anything contained within this class.
See also
http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html
Definition at line 34 of file awssignaturev2_p.h.
Constructor & Destructor Documentation
AwsSignatureV2Private::AwsSignatureV2Private (const QCryptographicHash::Algorithm algorithm, AwsSignatureV2 *const q)
Constructs a new AwsSignatureV2Private object.
Parameters
q Pointer to this object's public AwsSignatureV2 instance.
Definition at line 103 of file awssignaturev2.cpp.
     : AwsAbstractSignaturePrivate(q), hashAlgorithm(algorithm)
 {
 }
Member Function Documentation
void AwsSignatureV2Private::adornRequest (QNetworkRequest & request, const AwsAbstractCredentials & credentials) const
Add AWS Signature Version 2 adornments to an AWS request.
In addition to service-specific request parameters, Amazon requires that version 2 signatures contain a number of common query parameters. This functions adds those query parameters to request if they're not already present.
The query parameters added by this function, as required by Amazon, are:
AWSAccessKeyId - set to credentials.accessKeyId().
SignatureMethod - set to HMAC-SHA1 or HMAC-SHA256.
SignatureVersion - set to 2.
Timestamp - set to a current UTC timestamp in an ISO 8601 format, like 2013-10-30T12:34:56Z.
Parameters
request Request to adorn.
credentials Credentials to use when adorning request.
See also
signatureMethod
http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html
Definition at line 132 of file awssignaturev2.cpp.
References AwsAbstractCredentials::accessKeyId(), hashAlgorithm, AwsAbstractSignaturePrivate::setQueryItem(), and signatureMethod().
 {
     // Set / add the necessary query items.
     QUrl url = request.url();
     QUrlQuery query(url);
     setQueryItem(query, QLatin1String("AWSAccessKeyId"), credentials.accessKeyId());
     setQueryItem(query, QLatin1String("SignatureVersion"), QLatin1String("2"));
     setQueryItem(query, QLatin1String("SignatureMethod"), QString::fromUtf8(signatureMethod(hashAlgorithm)));
     setQueryItem(query, QLatin1String("Timestamp"),
                     QString::fromUtf8(QUrl::toPercentEncoding(
                         QDateTime::currentDateTimeUtc().toString(QLatin1String("yyyy-MM-ddThh:mm:ssZ"))
                     )),
                     false); // Don't warn if its already set to something else.
     // If we've touched the query items (likely), then update the request.
     if (query != QUrlQuery(url)) {
         qDebug() << url;
         url.setQuery(query);
         qDebug() << url;
         request.setUrl(url);
     }
 }
QByteArray AwsSignatureV2Private::canonicalRequest (const QNetworkAccessManager::Operation operation, const QUrl & url) const
Create an AWS V2 Signature canonical request.
This function creates a canonical representation of an AWS request as defined by Amazon's V2 signature specification.
For example, for the following HTTP GET request:
https://elasticmapreduce.amazonaws.com?Action=DescribeJobFlows&Version=2009-03-31&AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&SignatureVersion=2SignatureMethod=HmacSHA256Timestamp=2011-10-03T15%3A19%3A30
this function will return the following canonical form:
GET
elasticmapreduce.amazonaws.com
/
AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Action=DescribeJobFlows&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2011-10-03T15%3A19%3A30&Version=2009-03-31
Note
All URL components are encoded to UTF-8, as required by Amazon.
Parameters
operation The HTTP method being requested.
url The URL being request.
Returns
An AWS V2 Signature canonical request.
See also
http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html
Definition at line 184 of file awssignaturev2.cpp.
References AwsAbstractSignaturePrivate::canonicalPath(), AwsAbstractSignaturePrivate::canonicalQuery(), and AwsAbstractSignaturePrivate::httpMethod().
 {
     return httpMethod(operation).toUtf8() + '\n' +
            url.host().toUtf8() + '\n' +
            canonicalPath(url).toUtf8() + '\n' +
            canonicalQuery(QUrlQuery(url));
 }
QByteArray AwsSignatureV2Private::signatureMethod (const QCryptographicHash::Algorithm algorithm) const
Create an AWS V2 Signature method designation.
This function returns a signature method designation, as defined by Amazon, for use with V2 signatures.
For example, if the algorith is QCryptographicHash::Sha256, this function will return HmacSHA256.
Note
Amazon only supports two algorithms for V2 signatures - SHA1 and SHA256.
Parameters
algorithm The hash algorithm to get the canonical designation for.
Returns
An AWS V2 Signature method designation.
See also
http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html
Definition at line 210 of file awssignaturev2.cpp.
Referenced by adornRequest().
 {
     switch (algorithm) {
         case QCryptographicHash::Sha1:     return "HmacSHA1";
         case QCryptographicHash::Sha256:   return "HmacSHA256";
         default:
             Q_ASSERT_X(false, Q_FUNC_INFO, "invalid algorithm");
             return "invalid-algorithm";
     }
 }
The documentation for this class was generated from the following files:
core/awssignaturev2_p.h
core/awssignaturev2.cpp