libqtaws: AWS::CognitoSync::CognitoSyncClient Class Reference
AWS::CognitoSync::CognitoSyncClient Class Reference
Client for Amazon Cognito Sync.
Public Slots
BulkPublishResponse * bulkPublish (const BulkPublishRequest &request)
DeleteDatasetResponse * deleteDataset (const DeleteDatasetRequest &request)
DescribeDatasetResponse * describeDataset (const DescribeDatasetRequest &request)
DescribeIdentityPoolUsageResponse * describeIdentityPoolUsage (const DescribeIdentityPoolUsageRequest &request)
DescribeIdentityUsageResponse * describeIdentityUsage (const DescribeIdentityUsageRequest &request)
GetBulkPublishDetailsResponse * getBulkPublishDetails (const GetBulkPublishDetailsRequest &request)
GetCognitoEventsResponse * getCognitoEvents (const GetCognitoEventsRequest &request)
GetIdentityPoolConfigurationResponse * getIdentityPoolConfiguration (const GetIdentityPoolConfigurationRequest &request)
ListDatasetsResponse * listDatasets (const ListDatasetsRequest &request)
ListIdentityPoolUsageResponse * listIdentityPoolUsage (const ListIdentityPoolUsageRequest &request)
ListRecordsResponse * listRecords (const ListRecordsRequest &request)
RegisterDeviceResponse * registerDevice (const RegisterDeviceRequest &request)
SetCognitoEventsResponse * setCognitoEvents (const SetCognitoEventsRequest &request)
SetIdentityPoolConfigurationResponse * setIdentityPoolConfiguration (const SetIdentityPoolConfigurationRequest &request)
SubscribeToDatasetResponse * subscribeToDataset (const SubscribeToDatasetRequest &request)
UnsubscribeFromDatasetResponse * unsubscribeFromDataset (const UnsubscribeFromDatasetRequest &request)
UpdateRecordsResponse * updateRecords (const UpdateRecordsRequest &request)
Public Member Functions
CognitoSyncClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CognitoSyncClient object.
CognitoSyncClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CognitoSyncClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Cognito Sync.
<fullname>Amazon Cognito Sync</fullname>
Amazon Cognito Sync provides an AWS service and client library that enable cross-device syncing of application-related user data. High-level client libraries are available for both iOS and Android. You can use these libraries to persist data locally so that it's available even if the device is offline. Developer credentials don't need to be stored on the mobile device to access the service. You can use Amazon Cognito to obtain a normalized user ID and credentials. User data is persisted in a dataset that can store up to 1 MB of key-value pairs, and you can have up to 20 datasets per user
identity>
With Amazon Cognito Sync, the data stored for each identity is accessible only to credentials assigned to that identity. In order to use the Cognito Sync service, you need to make API calls using credentials retrieved with Amazon Cognito Identity service>
If you want to use Cognito Sync in an Android or iOS application, you will probably want to make API calls via the AWS Mobile SDK. To learn more, see the Developer Guide for Android and the Developer Guide for
Definition at line 36 of file cognitosyncclient.h.
Constructor & Destructor Documentation
CognitoSyncClient() [1/2]
AWS::CognitoSync::CognitoSyncClient::CognitoSyncClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CognitoSyncClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 66 of file cognitosyncclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new CognitoSyncClientPrivate(this), parent)
 {
     Q_D(CognitoSyncClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
CognitoSyncClient() [2/2]
AWS::CognitoSync::CognitoSyncClient::CognitoSyncClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CognitoSyncClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 96 of file cognitosyncclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new CognitoSyncClientPrivate(this), parent)
 {
     Q_D(CognitoSyncClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
cognito-sync/cognitosyncclient.h
cognito-sync/cognitosyncclient.cpp