libqtaws: AutoScalingClient Class Reference
AutoScalingClient Class Reference
Client for Auto Scaling.
Public Slots
AutoScalingAttachInstancesResponse * attachInstances (const AutoScalingAttachInstancesRequest &request)
AutoScalingAttachLoadBalancerTargetGroupsResponse * attachLoadBalancerTargetGroups (const AutoScalingAttachLoadBalancerTargetGroupsRequest &request)
AutoScalingAttachLoadBalancersResponse * attachLoadBalancers (const AutoScalingAttachLoadBalancersRequest &request)
AutoScalingCompleteLifecycleActionResponse * completeLifecycleAction (const AutoScalingCompleteLifecycleActionRequest &request)
AutoScalingCreateAutoScalingGroupResponse * createAutoScalingGroup (const AutoScalingCreateAutoScalingGroupRequest &request)
AutoScalingCreateLaunchConfigurationResponse * createLaunchConfiguration (const AutoScalingCreateLaunchConfigurationRequest &request)
AutoScalingCreateOrUpdateTagsResponse * createOrUpdateTags (const AutoScalingCreateOrUpdateTagsRequest &request)
AutoScalingDeleteAutoScalingGroupResponse * deleteAutoScalingGroup (const AutoScalingDeleteAutoScalingGroupRequest &request)
AutoScalingDeleteLaunchConfigurationResponse * deleteLaunchConfiguration (const AutoScalingDeleteLaunchConfigurationRequest &request)
AutoScalingDeleteLifecycleHookResponse * deleteLifecycleHook (const AutoScalingDeleteLifecycleHookRequest &request)
AutoScalingDeleteNotificationConfigurationResponse * deleteNotificationConfiguration (const AutoScalingDeleteNotificationConfigurationRequest &request)
AutoScalingDeletePolicyResponse * deletePolicy (const AutoScalingDeletePolicyRequest &request)
AutoScalingDeleteScheduledActionResponse * deleteScheduledAction (const AutoScalingDeleteScheduledActionRequest &request)
AutoScalingDeleteTagsResponse * deleteTags (const AutoScalingDeleteTagsRequest &request)
AutoScalingDescribeAccountLimitsResponse * describeAccountLimits ()
AutoScalingDescribeAdjustmentTypesResponse * describeAdjustmentTypes ()
AutoScalingDescribeAutoScalingGroupsResponse * describeAutoScalingGroups (const AutoScalingDescribeAutoScalingGroupsRequest &request)
AutoScalingDescribeAutoScalingInstancesResponse * describeAutoScalingInstances (const AutoScalingDescribeAutoScalingInstancesRequest &request)
AutoScalingDescribeAutoScalingNotificationTypesResponse * describeAutoScalingNotificationTypes ()
AutoScalingDescribeLaunchConfigurationsResponse * describeLaunchConfigurations (const AutoScalingDescribeLaunchConfigurationsRequest &request)
AutoScalingDescribeLifecycleHookTypesResponse * describeLifecycleHookTypes ()
AutoScalingDescribeLifecycleHooksResponse * describeLifecycleHooks (const AutoScalingDescribeLifecycleHooksRequest &request)
AutoScalingDescribeLoadBalancerTargetGroupsResponse * describeLoadBalancerTargetGroups (const AutoScalingDescribeLoadBalancerTargetGroupsRequest &request)
AutoScalingDescribeLoadBalancersResponse * describeLoadBalancers (const AutoScalingDescribeLoadBalancersRequest &request)
AutoScalingDescribeMetricCollectionTypesResponse * describeMetricCollectionTypes ()
AutoScalingDescribeNotificationConfigurationsResponse * describeNotificationConfigurations (const AutoScalingDescribeNotificationConfigurationsRequest &request)
AutoScalingDescribePoliciesResponse * describePolicies (const AutoScalingDescribePoliciesRequest &request)
AutoScalingDescribeScalingActivitiesResponse * describeScalingActivities (const AutoScalingDescribeScalingActivitiesRequest &request)
AutoScalingDescribeScalingProcessTypesResponse * describeScalingProcessTypes ()
AutoScalingDescribeScheduledActionsResponse * describeScheduledActions (const AutoScalingDescribeScheduledActionsRequest &request)
AutoScalingDescribeTagsResponse * describeTags (const AutoScalingDescribeTagsRequest &request)
AutoScalingDescribeTerminationPolicyTypesResponse * describeTerminationPolicyTypes ()
AutoScalingDetachInstancesResponse * detachInstances (const AutoScalingDetachInstancesRequest &request)
AutoScalingDetachLoadBalancerTargetGroupsResponse * detachLoadBalancerTargetGroups (const AutoScalingDetachLoadBalancerTargetGroupsRequest &request)
AutoScalingDetachLoadBalancersResponse * detachLoadBalancers (const AutoScalingDetachLoadBalancersRequest &request)
AutoScalingDisableMetricsCollectionResponse * disableMetricsCollection (const AutoScalingDisableMetricsCollectionRequest &request)
AutoScalingEnableMetricsCollectionResponse * enableMetricsCollection (const AutoScalingEnableMetricsCollectionRequest &request)
AutoScalingEnterStandbyResponse * enterStandby (const AutoScalingEnterStandbyRequest &request)
AutoScalingExecutePolicyResponse * executePolicy (const AutoScalingExecutePolicyRequest &request)
AutoScalingExitStandbyResponse * exitStandby (const AutoScalingExitStandbyRequest &request)
AutoScalingPutLifecycleHookResponse * putLifecycleHook (const AutoScalingPutLifecycleHookRequest &request)
AutoScalingPutNotificationConfigurationResponse * putNotificationConfiguration (const AutoScalingPutNotificationConfigurationRequest &request)
AutoScalingPutScalingPolicyResponse * putScalingPolicy (const AutoScalingPutScalingPolicyRequest &request)
AutoScalingPutScheduledUpdateGroupActionResponse * putScheduledUpdateGroupAction (const AutoScalingPutScheduledUpdateGroupActionRequest &request)
AutoScalingRecordLifecycleActionHeartbeatResponse * recordLifecycleActionHeartbeat (const AutoScalingRecordLifecycleActionHeartbeatRequest &request)
AutoScalingResumeProcessesResponse * resumeProcesses (const AutoScalingResumeProcessesRequest &request)
AutoScalingSetDesiredCapacityResponse * setDesiredCapacity (const AutoScalingSetDesiredCapacityRequest &request)
AutoScalingSetInstanceHealthResponse * setInstanceHealth (const AutoScalingSetInstanceHealthRequest &request)
AutoScalingSetInstanceProtectionResponse * setInstanceProtection (const AutoScalingSetInstanceProtectionRequest &request)
AutoScalingSuspendProcessesResponse * suspendProcesses (const AutoScalingSuspendProcessesRequest &request)
AutoScalingTerminateInstanceInAutoScalingGroupResponse * terminateInstanceInAutoScalingGroup (const AutoScalingTerminateInstanceInAutoScalingGroupRequest &request)
AutoScalingUpdateAutoScalingGroupResponse * updateAutoScalingGroup (const AutoScalingUpdateAutoScalingGroupRequest &request)
Public Member Functions
AutoScalingClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AutoScalingClient object.
AutoScalingClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AutoScalingClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Auto Scaling.
<fullname>Auto Scaling</fullname>
Auto Scaling is designed to automatically launch or terminate EC2 instances based on user-defined policies, schedules, and health checks. Use this service in conjunction with the Amazon CloudWatch and Elastic Load Balancing services.
Definition at line 33 of file autoscalingclient.h.
Constructor & Destructor Documentation
AutoScalingClient::AutoScalingClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AutoScalingClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 48 of file autoscalingclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new AutoScalingClientPrivate(this), parent)
 {
     Q_D(AutoScalingClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
AutoScalingClient::AutoScalingClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AutoScalingClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 78 of file autoscalingclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new AutoScalingClientPrivate(this), parent)
 {
     Q_D(AutoScalingClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
autoscaling/autoscalingclient.h
autoscaling/autoscalingclient.cpp