libqtaws: SqsAddPermissionRequest Class Reference
SqsAddPermissionRequest Class Reference
Implements SQS AddPermission requests.
Public Types
enum PermissibleAction {
SendMessageAction = SqsRequest::SendMessageAction, ReceiveMessageAction = SqsRequest::ReceiveMessageAction, DeleteMessageAction = SqsRequest::DeleteMessageAction, ChangeMessageVisibilityAction = SqsRequest::ChangeMessageVisibilityAction,
GetQueueAttributesAction = SqsRequest::GetQueueAttributesAction, GetQueueUrlAction = SqsRequest::GetQueueUrlAction
}
The subset of SQS actions that may be used with the AddPermission action.
typedef QMap< QString, PermissibleActions > PermissionsMap
Map of principals (aka accountIds) to their permissions.
Public Types inherited from SqsRequest
enum Action {
AddPermissionAction = 0x00001, ChangeMessageVisibilityAction = 0x00002, ChangeMessageVisibilityBatchAction = 0x00004, CreateQueueAction = 0x00008,
DeleteMessageAction = 0x00010, DeleteMessageBatchAction = 0x00020, DeleteQueueAction = 0x00040, GetQueueAttributesAction = 0x00080,
GetQueueUrlAction = 0x00100, ListDeadLetterSourceQueuesAction = 0x00200, ListQueuesAction = 0x00400, PurgeQueueAction = 0x00800,
ReceiveMessageAction = 0x01000, RemovePermissionAction = 0x02000, SendMessageAction = 0x04000, SendMessageBatchAction = 0x08000,
SetQueueAttributesAction = 0x10000
}
Actions supported by SQS.
Public Member Functions
SqsAddPermissionRequest (const QString &label, const PermissionsMap &permissions=PermissionsMap(), const QString &queueUrl=QString())
Constructs a new SqsAddPermissionRequest.
SqsAddPermissionRequest (const SqsAddPermissionRequest &other)
Constructs a new SqsAddPermissionRequest object by copying another.
SqsAddPermissionRequest ()
Constructs a new SqsAddPermissionRequest object.
virtual bool isValid () const
Is this request valid?
QString label () const
Get the label for this AddPermission request.
PermissibleActions permissions (const QString &accountId) const
Get the permissions to be set for accountId.
PermissionsMap permissions () const
Get all of the permissions to be set in the request.
QString queueUrl () const
Get the URL of the Amazon SQS queue to take action on.
void setLabel (const QString &label)
Set the unique label to use for this group of permissions.
void setQueueUrl (const QString &queueUrl)
Set the URL of the queue to add permissions to.
void setPermission (const QString &accountId, const PermissibleAction action, const bool permitted=true)
Set a permissions to be added for a given principal.
void setPermissions (const QString &accountId, const PermissibleActions &actions)
Set the permissions to be added for a given principal.
void setPermissions (const PermissionsMap &permissions)
Set all of the permissions this request will add to SQS.
Public Member Functions inherited from SqsRequest
SqsRequest (const Action action)
Constructs a new SqsRequest object.
SqsRequest (const SqsRequest &other)
Constructs a new SqsRequest object by copying another.
SqsRequest & operator= (const SqsRequest &other)
Assignment operator.
Action action () const
Get the SQS action to be performed by this request.
QString actionString () const
Get the name of the SQS action to be performed by this request.
QString apiVersion () const
Get the SQS API version implemented by this request.
void setAction (const Action action)
Set the SQS action to be performed by this request.
void setApiVersion (const QString &version)
Set the SQS API version to include in this request.
virtual bool operator== (const SqsRequest &other) const
Equality operator.
Public Member Functions inherited from AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const
Construct an SqsAddPermissionResponse object.
Protected Member Functions inherited from SqsRequest
SqsRequest (SqsRequestPrivate *const d)
Constructs a new SqsRequest object.
int clearParameter (const QString &name)
Remove a parameter from the parameters to be included with this request.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this SQS request.
const QVariantMap & parameters () const
Get all parameters included with this SQS request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this SQS request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this SQS request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this SQS request.
Protected Member Functions inherited from AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
Friends
class TestSqsAddPermissionRequest
Additional Inherited Members
Static Public Member Functions inherited from SqsRequest
static bool isValidQueueName (const QString &queueName)
Check if queueName is a valid SQS queue name.
Protected Attributes inherited from AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Implements SQS AddPermission requests.
See also
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_AddPermission.html
SqsRemovePermissionRequest
Definition at line 29 of file sqsaddpermissionrequest.h.
Constructor & Destructor Documentation
SqsAddPermissionRequest::SqsAddPermissionRequest (const QString & label, const PermissionsMap & permissions = PermissionsMap(), const QString & queueUrl = QString())
Constructs a new SqsAddPermissionRequest.
Parameters
label Unique identifier for the permission(s) to be set.
permissions Permissions to grant.
queueUrl URL of the queue permissions are to be granted on.
Definition at line 50 of file sqsaddpermissionrequest.cpp.
References setLabel(), setPermissions(), and setQueueUrl().
     : SqsRequest(new SqsAddPermissionRequestPrivate(SqsRequest::AddPermissionAction, this))
 {
     setLabel(label);
     setQueueUrl(queueUrl);
     setPermissions(permissions);
 }
SqsAddPermissionRequest::SqsAddPermissionRequest (const SqsAddPermissionRequest & other)
Constructs a new SqsAddPermissionRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 64 of file sqsaddpermissionrequest.cpp.
     : SqsRequest(new SqsAddPermissionRequestPrivate(*other.d_func(), this))
 {
 }
Member Function Documentation
bool SqsAddPermissionRequest::isValid () const virtual
Is this request valid?
Derived classes must implement this function to provide a level of request validation relevant to the type of request being implemented.
In this context, "valid" means that with valid credentials, the request's networkRequest method should return a request that the caller can reasonably expect AWS to accept (ignoring server side access restrictions and the like).
Returns
true if this request is considered valid, false other.
Implements AwsAbstractRequest.
Definition at line 79 of file sqsaddpermissionrequest.cpp.
References SqsRequest::isValidQueueName(), label(), permissions(), and queueUrl().
 {
     return ((isValidQueueName(label())) &&
             (!permissions().isEmpty()) &&
             (!queueUrl().isEmpty()));
 }
QString SqsAddPermissionRequest::label () const
Get the label for this AddPermission request.
Returns
The label for this AddPermission request.
Definition at line 91 of file sqsaddpermissionrequest.cpp.
References SqsRequest::parameter().
Referenced by isValid().
 {
     return parameter(LABEL).toString();
 }
SqsAddPermissionRequest::PermissibleActions SqsAddPermissionRequest::permissions (const QString & accountId) const
Get the permissions to be set for accountId.
Parameters
accountId The principal to get permissions for.
Returns
A set of action flags that will be allowed for accountId.
Definition at line 103 of file sqsaddpermissionrequest.cpp.
References permissions().
 {
     return permissions().value(accountId);
 }
SqsAddPermissionRequest::PermissionsMap SqsAddPermissionRequest::permissions () const
Get all of the permissions to be set in the request.
Returns
A map of all permissions to be set.
Definition at line 114 of file sqsaddpermissionrequest.cpp.
Referenced by isValid(), permissions(), setPermission(), and setPermissions().
 {
     Q_D(const SqsAddPermissionRequest);
     return d->permissions;
 }
QString SqsAddPermissionRequest::queueUrl () const
Get the URL of the Amazon SQS queue to take action on.
Returns
The queue URL, or an empty string if not set.
Definition at line 125 of file sqsaddpermissionrequest.cpp.
References SqsRequest::parameter().
Referenced by isValid().
 {
     return parameter(QUEUE_URL).toString();
 }
AwsAbstractResponse * SqsAddPermissionRequest::response (QNetworkReply *const reply) const protected virtual
Construct an SqsAddPermissionResponse object.
Parameters
reply Network reply this response should observe.
Returns
An SqsAddPermissionResponse instance for reply.
See also
AwsAbstractClient::send
Implements AwsAbstractRequest.
Definition at line 218 of file sqsaddpermissionrequest.cpp.
 {
     return new SqsAddPermissionResponse(*this, reply);
 }
void SqsAddPermissionRequest::setLabel (const QString & label)
Set the unique label to use for this group of permissions.
Parameters
label Unique label to use.
Definition at line 135 of file sqsaddpermissionrequest.cpp.
References SqsRequest::setParameter().
Referenced by SqsAddPermissionRequest().
 {
     setParameter(LABEL, label);
 }
void SqsAddPermissionRequest::setPermission (const QString & accountId, const PermissibleAction action, const bool permitted = true)
Set a permissions to be added for a given principal.
Note, this adds or removes the action permission for accountId, within the context of this request only. That is, if the principal accountId already has the action permission granted on the remote SQS service, this request will not be modifying that existing permission; see SqsRemovePermissionRequest for that.
Parameters
accountId Principal to set permssions for.
action Action to permit or not.
permitted Whether action should be permitted or not for accountId.
Definition at line 163 of file sqsaddpermissionrequest.cpp.
References SqsRequest::action(), permissions(), and setPermissions().
 {
     PermissibleActions actions = permissions(accountId);
     if (permitted) {
         actions |= action;
     } else {
         actions &= ~action;
     }
     setPermissions(accountId, actions);
 }
void SqsAddPermissionRequest::setPermissions (const QString & accountId, const PermissibleActions & actions)
Set the permissions to be added for a given principal.
Note, this sets the permissions for accountId, replacing any existing permissions - but only within the context of this request. That is, if the principal accountId has other permissions alredy set on the remote SQS service, this request will have no affect on those (or rather will be in addition to those).
Parameters
accountId Principal to set permssions for.
actions Set of actions to permit for accountId.
Definition at line 187 of file sqsaddpermissionrequest.cpp.
Referenced by setPermission(), and SqsAddPermissionRequest().
 {
     Q_D(SqsAddPermissionRequest);
     d->permissions.insert(accountId, actions);
 }
void SqsAddPermissionRequest::setPermissions (const PermissionsMap & permissions)
Set all of the permissions this request will add to SQS.
permissions is a map of principals (accountIds) to set of permission flags.
Parameters
permissions Complete set of permissions to set.
See also
permissions
Definition at line 203 of file sqsaddpermissionrequest.cpp.
References permissions().
 {
     Q_D(SqsAddPermissionRequest);
     d->permissions = permissions;
 }
void SqsAddPermissionRequest::setQueueUrl (const QString & queueUrl)
Set the URL of the queue to add permissions to.
Parameters
queueUrl SQS queue URL.
Definition at line 145 of file sqsaddpermissionrequest.cpp.
References SqsRequest::setParameter().
Referenced by SqsAddPermissionRequest().
 {
     setParameter(QUEUE_URL, queueUrl);
 }
The documentation for this class was generated from the following files:
sqs/sqsaddpermissionrequest.h
sqs/sqsaddpermissionrequest.cpp