libqtaws: ElasticLoadBalancingClient Class Reference
ElasticLoadBalancingClient Class Reference
Client for Elastic Load Balancing.
Public Slots
ElasticLoadBalancingAddTagsResponse * addTags (const ElasticLoadBalancingAddTagsRequest &request)
ElasticLoadBalancingApplySecurityGroupsToLoadBalancerResponse * applySecurityGroupsToLoadBalancer (const ElasticLoadBalancingApplySecurityGroupsToLoadBalancerRequest &request)
ElasticLoadBalancingAttachLoadBalancerToSubnetsResponse * attachLoadBalancerToSubnets (const ElasticLoadBalancingAttachLoadBalancerToSubnetsRequest &request)
ElasticLoadBalancingConfigureHealthCheckResponse * configureHealthCheck (const ElasticLoadBalancingConfigureHealthCheckRequest &request)
ElasticLoadBalancingCreateAppCookieStickinessPolicyResponse * createAppCookieStickinessPolicy (const ElasticLoadBalancingCreateAppCookieStickinessPolicyRequest &request)
ElasticLoadBalancingCreateLBCookieStickinessPolicyResponse * createLBCookieStickinessPolicy (const ElasticLoadBalancingCreateLBCookieStickinessPolicyRequest &request)
ElasticLoadBalancingCreateLoadBalancerResponse * createLoadBalancer (const ElasticLoadBalancingCreateLoadBalancerRequest &request)
ElasticLoadBalancingCreateLoadBalancerListenersResponse * createLoadBalancerListeners (const ElasticLoadBalancingCreateLoadBalancerListenersRequest &request)
ElasticLoadBalancingCreateLoadBalancerPolicyResponse * createLoadBalancerPolicy (const ElasticLoadBalancingCreateLoadBalancerPolicyRequest &request)
ElasticLoadBalancingDeleteLoadBalancerResponse * deleteLoadBalancer (const ElasticLoadBalancingDeleteLoadBalancerRequest &request)
ElasticLoadBalancingDeleteLoadBalancerListenersResponse * deleteLoadBalancerListeners (const ElasticLoadBalancingDeleteLoadBalancerListenersRequest &request)
ElasticLoadBalancingDeleteLoadBalancerPolicyResponse * deleteLoadBalancerPolicy (const ElasticLoadBalancingDeleteLoadBalancerPolicyRequest &request)
ElasticLoadBalancingDeregisterInstancesFromLoadBalancerResponse * deregisterInstancesFromLoadBalancer (const ElasticLoadBalancingDeregisterInstancesFromLoadBalancerRequest &request)
ElasticLoadBalancingDescribeInstanceHealthResponse * describeInstanceHealth (const ElasticLoadBalancingDescribeInstanceHealthRequest &request)
ElasticLoadBalancingDescribeLoadBalancerAttributesResponse * describeLoadBalancerAttributes (const ElasticLoadBalancingDescribeLoadBalancerAttributesRequest &request)
ElasticLoadBalancingDescribeLoadBalancerPoliciesResponse * describeLoadBalancerPolicies (const ElasticLoadBalancingDescribeLoadBalancerPoliciesRequest &request)
ElasticLoadBalancingDescribeLoadBalancerPolicyTypesResponse * describeLoadBalancerPolicyTypes (const ElasticLoadBalancingDescribeLoadBalancerPolicyTypesRequest &request)
ElasticLoadBalancingDescribeLoadBalancersResponse * describeLoadBalancers (const ElasticLoadBalancingDescribeLoadBalancersRequest &request)
ElasticLoadBalancingDescribeTagsResponse * describeTags (const ElasticLoadBalancingDescribeTagsRequest &request)
ElasticLoadBalancingDetachLoadBalancerFromSubnetsResponse * detachLoadBalancerFromSubnets (const ElasticLoadBalancingDetachLoadBalancerFromSubnetsRequest &request)
ElasticLoadBalancingDisableAvailabilityZonesForLoadBalancerResponse * disableAvailabilityZonesForLoadBalancer (const ElasticLoadBalancingDisableAvailabilityZonesForLoadBalancerRequest &request)
ElasticLoadBalancingEnableAvailabilityZonesForLoadBalancerResponse * enableAvailabilityZonesForLoadBalancer (const ElasticLoadBalancingEnableAvailabilityZonesForLoadBalancerRequest &request)
ElasticLoadBalancingModifyLoadBalancerAttributesResponse * modifyLoadBalancerAttributes (const ElasticLoadBalancingModifyLoadBalancerAttributesRequest &request)
ElasticLoadBalancingRegisterInstancesWithLoadBalancerResponse * registerInstancesWithLoadBalancer (const ElasticLoadBalancingRegisterInstancesWithLoadBalancerRequest &request)
ElasticLoadBalancingRemoveTagsResponse * removeTags (const ElasticLoadBalancingRemoveTagsRequest &request)
ElasticLoadBalancingSetLoadBalancerListenerSSLCertificateResponse * setLoadBalancerListenerSSLCertificate (const ElasticLoadBalancingSetLoadBalancerListenerSSLCertificateRequest &request)
ElasticLoadBalancingSetLoadBalancerPoliciesForBackendServerResponse * setLoadBalancerPoliciesForBackendServer (const ElasticLoadBalancingSetLoadBalancerPoliciesForBackendServerRequest &request)
ElasticLoadBalancingSetLoadBalancerPoliciesOfListenerResponse * setLoadBalancerPoliciesOfListener (const ElasticLoadBalancingSetLoadBalancerPoliciesOfListenerRequest &request)
Public Member Functions
ElasticLoadBalancingClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticLoadBalancingClient object.
ElasticLoadBalancingClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticLoadBalancingClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Elastic Load Balancing.
<fullname>Elastic Load Balancing</fullname>
A load balancer distributes incoming traffic across your EC2 instances. This enables you to increase the availability of your application. The load balancer also monitors the health of its registered instances and ensures that it routes traffic only to healthy instances. You configure your load balancer to accept incoming traffic by specifying one or more listeners, which are configured with a protocol and port number for connections from clients to the load balancer and a protocol and port number for connections from the load balancer to the instances.
Elastic Load Balancing supports two types of load balancers: Classic load balancers and Application load balancers (new). A Classic load balancer makes routing and load balancing decisions either at the transport layer (TCP/SSL) or the application layer (HTTP/HTTPS), and supports either EC2-Classic or a VPC. An Application load balancer makes routing and load balancing decisions at the application layer (HTTP/HTTPS), supports path-based routing, and can route requests to one or more ports on each EC2 instance or container instance in your virtual private cloud (VPC). For more information, see the .
This reference covers the 2012-06-01 API, which supports Classic load balancers. The 2015-12-01 API supports Application load balancers.
To get started, create a load balancer with one or more listeners using CreateLoadBalancer. Register your instances with the load balancer using RegisterInstancesWithLoadBalancer.
All Elastic Load Balancing operations are idempotent, which means that they complete at most one time. If you repeat an operation, it succeeds with a 200 OK response code.
Definition at line 33 of file elasticloadbalancingclient.h.
Constructor & Destructor Documentation
ElasticLoadBalancingClient::ElasticLoadBalancingClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticLoadBalancingClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 56 of file elasticloadbalancingclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new ElasticLoadBalancingClientPrivate(this), parent)
 {
     Q_D(ElasticLoadBalancingClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
ElasticLoadBalancingClient::ElasticLoadBalancingClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticLoadBalancingClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 86 of file elasticloadbalancingclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new ElasticLoadBalancingClientPrivate(this), parent)
 {
     Q_D(ElasticLoadBalancingClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
elasticloadbalancing/elasticloadbalancingclient.h
elasticloadbalancing/elasticloadbalancingclient.cpp