libqtaws: SwfClient Class Reference
SwfClient Class Reference
Client for Amazon Simple Workflow Service (SWF)
Public Slots
SwfCountClosedWorkflowExecutionsResponse * countClosedWorkflowExecutions (const SwfCountClosedWorkflowExecutionsRequest &request)
SwfCountOpenWorkflowExecutionsResponse * countOpenWorkflowExecutions (const SwfCountOpenWorkflowExecutionsRequest &request)
SwfCountPendingActivityTasksResponse * countPendingActivityTasks (const SwfCountPendingActivityTasksRequest &request)
SwfCountPendingDecisionTasksResponse * countPendingDecisionTasks (const SwfCountPendingDecisionTasksRequest &request)
SwfDeprecateActivityTypeResponse * deprecateActivityType (const SwfDeprecateActivityTypeRequest &request)
SwfDeprecateDomainResponse * deprecateDomain (const SwfDeprecateDomainRequest &request)
SwfDeprecateWorkflowTypeResponse * deprecateWorkflowType (const SwfDeprecateWorkflowTypeRequest &request)
SwfDescribeActivityTypeResponse * describeActivityType (const SwfDescribeActivityTypeRequest &request)
SwfDescribeDomainResponse * describeDomain (const SwfDescribeDomainRequest &request)
SwfDescribeWorkflowExecutionResponse * describeWorkflowExecution (const SwfDescribeWorkflowExecutionRequest &request)
SwfDescribeWorkflowTypeResponse * describeWorkflowType (const SwfDescribeWorkflowTypeRequest &request)
SwfGetWorkflowExecutionHistoryResponse * getWorkflowExecutionHistory (const SwfGetWorkflowExecutionHistoryRequest &request)
SwfListActivityTypesResponse * listActivityTypes (const SwfListActivityTypesRequest &request)
SwfListClosedWorkflowExecutionsResponse * listClosedWorkflowExecutions (const SwfListClosedWorkflowExecutionsRequest &request)
SwfListDomainsResponse * listDomains (const SwfListDomainsRequest &request)
SwfListOpenWorkflowExecutionsResponse * listOpenWorkflowExecutions (const SwfListOpenWorkflowExecutionsRequest &request)
SwfListWorkflowTypesResponse * listWorkflowTypes (const SwfListWorkflowTypesRequest &request)
SwfPollForActivityTaskResponse * pollForActivityTask (const SwfPollForActivityTaskRequest &request)
SwfPollForDecisionTaskResponse * pollForDecisionTask (const SwfPollForDecisionTaskRequest &request)
SwfRecordActivityTaskHeartbeatResponse * recordActivityTaskHeartbeat (const SwfRecordActivityTaskHeartbeatRequest &request)
SwfRegisterActivityTypeResponse * registerActivityType (const SwfRegisterActivityTypeRequest &request)
SwfRegisterDomainResponse * registerDomain (const SwfRegisterDomainRequest &request)
SwfRegisterWorkflowTypeResponse * registerWorkflowType (const SwfRegisterWorkflowTypeRequest &request)
SwfRequestCancelWorkflowExecutionResponse * requestCancelWorkflowExecution (const SwfRequestCancelWorkflowExecutionRequest &request)
SwfRespondActivityTaskCanceledResponse * respondActivityTaskCanceled (const SwfRespondActivityTaskCanceledRequest &request)
SwfRespondActivityTaskCompletedResponse * respondActivityTaskCompleted (const SwfRespondActivityTaskCompletedRequest &request)
SwfRespondActivityTaskFailedResponse * respondActivityTaskFailed (const SwfRespondActivityTaskFailedRequest &request)
SwfRespondDecisionTaskCompletedResponse * respondDecisionTaskCompleted (const SwfRespondDecisionTaskCompletedRequest &request)
SwfSignalWorkflowExecutionResponse * signalWorkflowExecution (const SwfSignalWorkflowExecutionRequest &request)
SwfStartWorkflowExecutionResponse * startWorkflowExecution (const SwfStartWorkflowExecutionRequest &request)
SwfTerminateWorkflowExecutionResponse * terminateWorkflowExecution (const SwfTerminateWorkflowExecutionRequest &request)
Public Member Functions
SwfClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SwfClient object.
SwfClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SwfClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Simple Workflow Service (SWF)
<fullname>Amazon Simple Workflow Service</fullname>
The Amazon Simple Workflow Service (Amazon SWF) makes it easy to build applications that use Amazon's cloud to coordinate work across distributed components. In Amazon SWF, a task represents a logical unit of work that is performed by a component of your workflow. Coordinating tasks in a workflow involves managing intertask dependencies, scheduling, and concurrency in accordance with the logical flow of the application.
Amazon SWF gives you full control over implementing tasks and coordinating them without worrying about underlying complexities such as tracking their progress and maintaining their state.
This documentation serves as reference only. For a broader overview of the Amazon SWF programming model, see the Amazon SWF Developer Guide.
Definition at line 33 of file swfclient.h.
Constructor & Destructor Documentation
SwfClient::SwfClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SwfClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 52 of file swfclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new SwfClientPrivate(this), parent)
 {
     Q_D(SwfClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
SwfClient::SwfClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SwfClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 82 of file swfclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new SwfClientPrivate(this), parent)
 {
     Q_D(SwfClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
swf/swfclient.h
swf/swfclient.cpp