libqtaws: AWS::Lambda::LambdaClient Class Reference
AWS::Lambda::LambdaClient Class Reference
Client for AWS Lambda.
Public Slots
AddPermissionResponse * addPermission (const AddPermissionRequest &request)
CreateAliasResponse * createAlias (const CreateAliasRequest &request)
CreateEventSourceMappingResponse * createEventSourceMapping (const CreateEventSourceMappingRequest &request)
CreateFunctionResponse * createFunction (const CreateFunctionRequest &request)
DeleteAliasResponse * deleteAlias (const DeleteAliasRequest &request)
DeleteEventSourceMappingResponse * deleteEventSourceMapping (const DeleteEventSourceMappingRequest &request)
DeleteFunctionResponse * deleteFunction (const DeleteFunctionRequest &request)
DeleteFunctionConcurrencyResponse * deleteFunctionConcurrency (const DeleteFunctionConcurrencyRequest &request)
GetAccountSettingsResponse * getAccountSettings (const GetAccountSettingsRequest &request)
GetAliasResponse * getAlias (const GetAliasRequest &request)
GetEventSourceMappingResponse * getEventSourceMapping (const GetEventSourceMappingRequest &request)
GetFunctionResponse * getFunction (const GetFunctionRequest &request)
GetFunctionConfigurationResponse * getFunctionConfiguration (const GetFunctionConfigurationRequest &request)
GetPolicyResponse * getPolicy (const GetPolicyRequest &request)
InvokeResponse * invoke (const InvokeRequest &request)
InvokeAsyncResponse * invokeAsync (const InvokeAsyncRequest &request)
ListAliasesResponse * listAliases (const ListAliasesRequest &request)
ListEventSourceMappingsResponse * listEventSourceMappings (const ListEventSourceMappingsRequest &request)
ListFunctionsResponse * listFunctions (const ListFunctionsRequest &request)
ListTagsResponse * listTags (const ListTagsRequest &request)
ListVersionsByFunctionResponse * listVersionsByFunction (const ListVersionsByFunctionRequest &request)
PublishVersionResponse * publishVersion (const PublishVersionRequest &request)
PutFunctionConcurrencyResponse * putFunctionConcurrency (const PutFunctionConcurrencyRequest &request)
RemovePermissionResponse * removePermission (const RemovePermissionRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateAliasResponse * updateAlias (const UpdateAliasRequest &request)
UpdateEventSourceMappingResponse * updateEventSourceMapping (const UpdateEventSourceMappingRequest &request)
UpdateFunctionCodeResponse * updateFunctionCode (const UpdateFunctionCodeRequest &request)
UpdateFunctionConfigurationResponse * updateFunctionConfiguration (const UpdateFunctionConfigurationRequest &request)
Public Member Functions
LambdaClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new LambdaClient object.
LambdaClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new LambdaClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Lambda.
<fullname>AWS Lambda</fullname>
Overview
</p
This is the AWS Lambda API Reference. The AWS Lambda Developer Guide provides additional information. For the service overview, see What is AWS Lambda, and for information about how the service works, see AWS Lambda: How it Works in the AWS Lambda Developer
Definition at line 36 of file lambdaclient.h.
Constructor & Destructor Documentation
LambdaClient() [1/2]
AWS::Lambda::LambdaClient::LambdaClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new LambdaClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 57 of file lambdaclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new LambdaClientPrivate(this), parent)
 {
     Q_D(LambdaClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
LambdaClient() [2/2]
AWS::Lambda::LambdaClient::LambdaClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new LambdaClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 87 of file lambdaclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new LambdaClientPrivate(this), parent)
 {
     Q_D(LambdaClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
lambda/lambdaclient.h
lambda/lambdaclient.cpp