libqtaws: SqsChangeMessageVisibilityRequest Class Reference
SqsChangeMessageVisibilityRequest Class Reference
Implements SQS ChangeMessageVisibility requests.
Public Member Functions
SqsChangeMessageVisibilityRequest (const QString &queueUrl, const QString &receiptHandle, const int visbilityTimeout)
Constructs a new SqsChangeMessageVisibilityRequest.
SqsChangeMessageVisibilityRequest (const SqsChangeMessageVisibilityRequest &other)
Constructs a new SqsChangeMessageVisibilityRequest object by copying another.
SqsChangeMessageVisibilityRequest ()
Constructs a new SqsChangeMessageVisibilityRequest object.
virtual bool isValid () const
Is this request valid?
QString queueUrl () const
Get the URL of the Amazon SQS queue to take action on.
QString receiptHandle () const
Get the receipt handle associated with the message whose visibility timeout should be changed.
int visibilityTimeout () const
The value (in seconds) for the message's visibility timeout.
void setQueueUrl (const QString &queueUrl)
Set the URL of the Amazon SQS queue to take action on.
void setReceiptHandle (const QString &receiptHandle)
Set the receipt handle associated with the message whose visibility timeout should be changed.
void setVisibilityTimeout (const int timeout)
Set the value (in seconds) for the message's visibility timeout.
Public Member Functions inherited from SqsRequest
SqsRequest (const Action action)
Constructs a new SqsRequest object.
SqsRequest (const SqsRequest &other)
Constructs a new SqsRequest object by copying another.
SqsRequest & operator= (const SqsRequest &other)
Assignment operator.
Action action () const
Get the SQS action to be performed by this request.
QString actionString () const
Get the name of the SQS action to be performed by this request.
QString apiVersion () const
Get the SQS API version implemented by this request.
void setAction (const Action action)
Set the SQS action to be performed by this request.
void setApiVersion (const QString &version)
Set the SQS API version to include in this request.
virtual bool operator== (const SqsRequest &other) const
Equality operator.
Public Member Functions inherited from AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const
Construct an SqsChangeMessageVisibilityResponse object.
Protected Member Functions inherited from SqsRequest
SqsRequest (SqsRequestPrivate *const d)
Constructs a new SqsRequest object.
int clearParameter (const QString &name)
Remove a parameter from the parameters to be included with this request.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this SQS request.
const QVariantMap & parameters () const
Get all parameters included with this SQS request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this SQS request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this SQS request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this SQS request.
Protected Member Functions inherited from AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
Friends
class TestSqsChangeMessageVisibilityRequest
Additional Inherited Members
Public Types inherited from SqsRequest
enum Action {
AddPermissionAction = 0x00001, ChangeMessageVisibilityAction = 0x00002, ChangeMessageVisibilityBatchAction = 0x00004, CreateQueueAction = 0x00008,
DeleteMessageAction = 0x00010, DeleteMessageBatchAction = 0x00020, DeleteQueueAction = 0x00040, GetQueueAttributesAction = 0x00080,
GetQueueUrlAction = 0x00100, ListDeadLetterSourceQueuesAction = 0x00200, ListQueuesAction = 0x00400, PurgeQueueAction = 0x00800,
ReceiveMessageAction = 0x01000, RemovePermissionAction = 0x02000, SendMessageAction = 0x04000, SendMessageBatchAction = 0x08000,
SetQueueAttributesAction = 0x10000
}
Actions supported by SQS.
Static Public Member Functions inherited from SqsRequest
static bool isValidQueueName (const QString &queueName)
Check if queueName is a valid SQS queue name.
Protected Attributes inherited from AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Implements SQS ChangeMessageVisibility requests.
See also
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ChangeMessageVisibility.html
SqsRemovePermissionRequest
Definition at line 29 of file sqschangemessagevisibilityrequest.h.
Constructor & Destructor Documentation
SqsChangeMessageVisibilityRequest() [1/2]
SqsChangeMessageVisibilityRequest::SqsChangeMessageVisibilityRequest (const QString & queueUrl, const QString & receiptHandle, const int visbilityTimeout)
Constructs a new SqsChangeMessageVisibilityRequest.
Parameters
queueUrl URL of the Amazon SQS queue to take action on.
receiptHandle Receipt handle associated with the message whose visibility timeout should be changed.
visbilityTimeout New value (in seconds) for the message's visibility timeout.
Definition at line 49 of file sqschangemessagevisibilityrequest.cpp.
References setQueueUrl(), setReceiptHandle(), and setVisibilityTimeout().
     : SqsRequest(new SqsChangeMessageVisibilityRequestPrivate(SqsRequest::ChangeMessageVisibilityAction, this))
 {
     setQueueUrl(queueUrl);
     setReceiptHandle(receiptHandle);
     setVisibilityTimeout(visbilityTimeout);
 }
SqsChangeMessageVisibilityRequest() [2/2]
SqsChangeMessageVisibilityRequest::SqsChangeMessageVisibilityRequest (const SqsChangeMessageVisibilityRequest & other)
Constructs a new SqsChangeMessageVisibilityRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 63 of file sqschangemessagevisibilityrequest.cpp.
     : SqsRequest(new SqsChangeMessageVisibilityRequestPrivate(*other.d_func(), this))
 {
 }
Member Function Documentation
isValid()
bool SqsChangeMessageVisibilityRequest::isValid () const virtual
Is this request valid?
Derived classes must implement this function to provide a level of request validation relevant to the type of request being implemented.
In this context, "valid" means that with valid credentials, the request's networkRequest method should return a request that the caller can reasonably expect AWS to accept (ignoring server side access restrictions and the like).
Returns
true if this request is considered valid, false other.
Implements AwsAbstractRequest.
Definition at line 78 of file sqschangemessagevisibilityrequest.cpp.
References queueUrl(), receiptHandle(), and visibilityTimeout().
 {
     return ((!queueUrl().isEmpty()) &&
             (!receiptHandle().isEmpty()) &&
             (visibilityTimeout() >= 0));
 }
queueUrl()
QString SqsChangeMessageVisibilityRequest::queueUrl () const
Get the URL of the Amazon SQS queue to take action on.
Returns
The queue URL, or an empty string if not set.
Definition at line 90 of file sqschangemessagevisibilityrequest.cpp.
References SqsRequest::parameter().
Referenced by isValid().
 {
     return parameter(QUEUE_URL).toString();
 }
receiptHandle()
QString SqsChangeMessageVisibilityRequest::receiptHandle () const
Get the receipt handle associated with the message whose visibility timeout should be changed.
Returns
The receipt handle, or an empty string if not set.
Definition at line 101 of file sqschangemessagevisibilityrequest.cpp.
References SqsRequest::parameter().
Referenced by isValid().
 {
     return parameter(RECEIPT_HANDLE).toString();
 }
response()
AwsAbstractResponse * SqsChangeMessageVisibilityRequest::response (QNetworkReply *const reply) const protected virtual
Construct an SqsChangeMessageVisibilityResponse object.
Parameters
reply Network reply this response should observe.
Returns
An SqsChangeMessageVisibilityResponse instance for reply.
See also
AwsAbstractClient::send
Implements AwsAbstractRequest.
Definition at line 156 of file sqschangemessagevisibilityrequest.cpp.
 {
     return new SqsChangeMessageVisibilityResponse(*this, reply);
 }
setQueueUrl()
void SqsChangeMessageVisibilityRequest::setQueueUrl (const QString & queueUrl)
Set the URL of the Amazon SQS queue to take action on.
Parameters
queueUrl URL of the Amazon SQS queue to take action on.
Definition at line 121 of file sqschangemessagevisibilityrequest.cpp.
References SqsRequest::setParameter().
Referenced by SqsChangeMessageVisibilityRequest().
 {
     setParameter(QUEUE_URL, queueUrl);
 }
setReceiptHandle()
void SqsChangeMessageVisibilityRequest::setReceiptHandle (const QString & receiptHandle)
Set the receipt handle associated with the message whose visibility timeout should be changed.
Parameters
receiptHandle Handle of the message to change.
Definition at line 132 of file sqschangemessagevisibilityrequest.cpp.
References SqsRequest::setParameter().
Referenced by SqsChangeMessageVisibilityRequest().
 {
     setParameter(RECEIPT_HANDLE, receiptHandle);
 }
setVisibilityTimeout()
void SqsChangeMessageVisibilityRequest::setVisibilityTimeout (const int timeout)
Set the value (in seconds) for the message's visibility timeout.
Parameters
timeout New message visbility timeout period (in seconds) to set.
Definition at line 142 of file sqschangemessagevisibilityrequest.cpp.
References SqsRequest::setParameter().
Referenced by SqsChangeMessageVisibilityRequest().
 {
     setParameter(VISIBILITY_TIMEOUT, timeout);
 }
visibilityTimeout()
int SqsChangeMessageVisibilityRequest::visibilityTimeout () const
The value (in seconds) for the message's visibility timeout.
Returns
The new message visbility timeout period (in seconds), or -1 if not set.
Definition at line 111 of file sqschangemessagevisibilityrequest.cpp.
References SqsRequest::parameter().
Referenced by isValid().
 {
     return parameter(VISIBILITY_TIMEOUT, -1).toInt();
 }
The documentation for this class was generated from the following files:
sqs/sqschangemessagevisibilityrequest.h
sqs/sqschangemessagevisibilityrequest.cpp