libqtaws: LambdaClient Class Reference
LambdaClient Class Reference
Client for AWS Lambda.
Public Slots
LambdaAddPermissionResponse * addPermission (const LambdaAddPermissionRequest &request)
LambdaCreateAliasResponse * createAlias (const LambdaCreateAliasRequest &request)
LambdaCreateEventSourceMappingResponse * createEventSourceMapping (const LambdaCreateEventSourceMappingRequest &request)
LambdaCreateFunctionResponse * createFunction (const LambdaCreateFunctionRequest &request)
LambdaDeleteAliasResponse * deleteAlias (const LambdaDeleteAliasRequest &request)
LambdaDeleteEventSourceMappingResponse * deleteEventSourceMapping (const LambdaDeleteEventSourceMappingRequest &request)
LambdaDeleteFunctionResponse * deleteFunction (const LambdaDeleteFunctionRequest &request)
LambdaGetAliasResponse * getAlias (const LambdaGetAliasRequest &request)
LambdaGetEventSourceMappingResponse * getEventSourceMapping (const LambdaGetEventSourceMappingRequest &request)
LambdaGetFunctionResponse * getFunction (const LambdaGetFunctionRequest &request)
LambdaGetFunctionConfigurationResponse * getFunctionConfiguration (const LambdaGetFunctionConfigurationRequest &request)
LambdaGetPolicyResponse * getPolicy (const LambdaGetPolicyRequest &request)
LambdaInvokeResponse * invoke (const LambdaInvokeRequest &request)
LambdaInvokeAsyncResponse * invokeAsync (const LambdaInvokeAsyncRequest &request)
LambdaListAliasesResponse * listAliases (const LambdaListAliasesRequest &request)
LambdaListEventSourceMappingsResponse * listEventSourceMappings (const LambdaListEventSourceMappingsRequest &request)
LambdaListFunctionsResponse * listFunctions (const LambdaListFunctionsRequest &request)
LambdaListVersionsByFunctionResponse * listVersionsByFunction (const LambdaListVersionsByFunctionRequest &request)
LambdaPublishVersionResponse * publishVersion (const LambdaPublishVersionRequest &request)
LambdaRemovePermissionResponse * removePermission (const LambdaRemovePermissionRequest &request)
LambdaUpdateAliasResponse * updateAlias (const LambdaUpdateAliasRequest &request)
LambdaUpdateEventSourceMappingResponse * updateEventSourceMapping (const LambdaUpdateEventSourceMappingRequest &request)
LambdaUpdateFunctionCodeResponse * updateFunctionCode (const LambdaUpdateFunctionCodeRequest &request)
LambdaUpdateFunctionConfigurationResponse * updateFunctionConfiguration (const LambdaUpdateFunctionConfigurationRequest &request)
Public Member Functions
LambdaClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new LambdaClient object.
LambdaClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new LambdaClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Lambda.
<fullname>AWS Lambda</fullname>
Overview
This is the AWS Lambda API Reference. The AWS Lambda Developer Guide provides additional information. For the service overview, go to What is AWS Lambda, and for information about how the service works, go to AWS Lambda: How it Works in the AWS Lambda Developer Guide.
Definition at line 33 of file lambdaclient.h.
Constructor & Destructor Documentation
LambdaClient::LambdaClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new LambdaClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 50 of file lambdaclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new LambdaClientPrivate(this), parent)
 {
     Q_D(LambdaClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
LambdaClient::LambdaClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new LambdaClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 80 of file lambdaclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new LambdaClientPrivate(this), parent)
 {
     Q_D(LambdaClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
lambda/lambdaclient.h
lambda/lambdaclient.cpp