libqtaws: AWS::Redshift::RedshiftClient Class Reference
AWS::Redshift::RedshiftClient Class Reference
Client for Amazon Redshift.
Public Slots
AuthorizeClusterSecurityGroupIngressResponse * authorizeClusterSecurityGroupIngress (const AuthorizeClusterSecurityGroupIngressRequest &request)
AuthorizeSnapshotAccessResponse * authorizeSnapshotAccess (const AuthorizeSnapshotAccessRequest &request)
CopyClusterSnapshotResponse * copyClusterSnapshot (const CopyClusterSnapshotRequest &request)
CreateClusterResponse * createCluster (const CreateClusterRequest &request)
CreateClusterParameterGroupResponse * createClusterParameterGroup (const CreateClusterParameterGroupRequest &request)
CreateClusterSecurityGroupResponse * createClusterSecurityGroup (const CreateClusterSecurityGroupRequest &request)
CreateClusterSnapshotResponse * createClusterSnapshot (const CreateClusterSnapshotRequest &request)
CreateClusterSubnetGroupResponse * createClusterSubnetGroup (const CreateClusterSubnetGroupRequest &request)
CreateEventSubscriptionResponse * createEventSubscription (const CreateEventSubscriptionRequest &request)
CreateHsmClientCertificateResponse * createHsmClientCertificate (const CreateHsmClientCertificateRequest &request)
CreateHsmConfigurationResponse * createHsmConfiguration (const CreateHsmConfigurationRequest &request)
CreateSnapshotCopyGrantResponse * createSnapshotCopyGrant (const CreateSnapshotCopyGrantRequest &request)
CreateTagsResponse * createTags (const CreateTagsRequest &request)
DeleteClusterResponse * deleteCluster (const DeleteClusterRequest &request)
DeleteClusterParameterGroupResponse * deleteClusterParameterGroup (const DeleteClusterParameterGroupRequest &request)
DeleteClusterSecurityGroupResponse * deleteClusterSecurityGroup (const DeleteClusterSecurityGroupRequest &request)
DeleteClusterSnapshotResponse * deleteClusterSnapshot (const DeleteClusterSnapshotRequest &request)
DeleteClusterSubnetGroupResponse * deleteClusterSubnetGroup (const DeleteClusterSubnetGroupRequest &request)
DeleteEventSubscriptionResponse * deleteEventSubscription (const DeleteEventSubscriptionRequest &request)
DeleteHsmClientCertificateResponse * deleteHsmClientCertificate (const DeleteHsmClientCertificateRequest &request)
DeleteHsmConfigurationResponse * deleteHsmConfiguration (const DeleteHsmConfigurationRequest &request)
DeleteSnapshotCopyGrantResponse * deleteSnapshotCopyGrant (const DeleteSnapshotCopyGrantRequest &request)
DeleteTagsResponse * deleteTags (const DeleteTagsRequest &request)
DescribeClusterParameterGroupsResponse * describeClusterParameterGroups (const DescribeClusterParameterGroupsRequest &request)
DescribeClusterParametersResponse * describeClusterParameters (const DescribeClusterParametersRequest &request)
DescribeClusterSecurityGroupsResponse * describeClusterSecurityGroups (const DescribeClusterSecurityGroupsRequest &request)
DescribeClusterSnapshotsResponse * describeClusterSnapshots (const DescribeClusterSnapshotsRequest &request)
DescribeClusterSubnetGroupsResponse * describeClusterSubnetGroups (const DescribeClusterSubnetGroupsRequest &request)
DescribeClusterVersionsResponse * describeClusterVersions (const DescribeClusterVersionsRequest &request)
DescribeClustersResponse * describeClusters (const DescribeClustersRequest &request)
DescribeDefaultClusterParametersResponse * describeDefaultClusterParameters (const DescribeDefaultClusterParametersRequest &request)
DescribeEventCategoriesResponse * describeEventCategories (const DescribeEventCategoriesRequest &request)
DescribeEventSubscriptionsResponse * describeEventSubscriptions (const DescribeEventSubscriptionsRequest &request)
DescribeEventsResponse * describeEvents (const DescribeEventsRequest &request)
DescribeHsmClientCertificatesResponse * describeHsmClientCertificates (const DescribeHsmClientCertificatesRequest &request)
DescribeHsmConfigurationsResponse * describeHsmConfigurations (const DescribeHsmConfigurationsRequest &request)
DescribeLoggingStatusResponse * describeLoggingStatus (const DescribeLoggingStatusRequest &request)
DescribeOrderableClusterOptionsResponse * describeOrderableClusterOptions (const DescribeOrderableClusterOptionsRequest &request)
DescribeReservedNodeOfferingsResponse * describeReservedNodeOfferings (const DescribeReservedNodeOfferingsRequest &request)
DescribeReservedNodesResponse * describeReservedNodes (const DescribeReservedNodesRequest &request)
DescribeResizeResponse * describeResize (const DescribeResizeRequest &request)
DescribeSnapshotCopyGrantsResponse * describeSnapshotCopyGrants (const DescribeSnapshotCopyGrantsRequest &request)
DescribeTableRestoreStatusResponse * describeTableRestoreStatus (const DescribeTableRestoreStatusRequest &request)
DescribeTagsResponse * describeTags (const DescribeTagsRequest &request)
DisableLoggingResponse * disableLogging (const DisableLoggingRequest &request)
DisableSnapshotCopyResponse * disableSnapshotCopy (const DisableSnapshotCopyRequest &request)
EnableLoggingResponse * enableLogging (const EnableLoggingRequest &request)
EnableSnapshotCopyResponse * enableSnapshotCopy (const EnableSnapshotCopyRequest &request)
GetClusterCredentialsResponse * getClusterCredentials (const GetClusterCredentialsRequest &request)
ModifyClusterResponse * modifyCluster (const ModifyClusterRequest &request)
ModifyClusterIamRolesResponse * modifyClusterIamRoles (const ModifyClusterIamRolesRequest &request)
ModifyClusterParameterGroupResponse * modifyClusterParameterGroup (const ModifyClusterParameterGroupRequest &request)
ModifyClusterSubnetGroupResponse * modifyClusterSubnetGroup (const ModifyClusterSubnetGroupRequest &request)
ModifyEventSubscriptionResponse * modifyEventSubscription (const ModifyEventSubscriptionRequest &request)
ModifySnapshotCopyRetentionPeriodResponse * modifySnapshotCopyRetentionPeriod (const ModifySnapshotCopyRetentionPeriodRequest &request)
PurchaseReservedNodeOfferingResponse * purchaseReservedNodeOffering (const PurchaseReservedNodeOfferingRequest &request)
RebootClusterResponse * rebootCluster (const RebootClusterRequest &request)
ResetClusterParameterGroupResponse * resetClusterParameterGroup (const ResetClusterParameterGroupRequest &request)
RestoreFromClusterSnapshotResponse * restoreFromClusterSnapshot (const RestoreFromClusterSnapshotRequest &request)
RestoreTableFromClusterSnapshotResponse * restoreTableFromClusterSnapshot (const RestoreTableFromClusterSnapshotRequest &request)
RevokeClusterSecurityGroupIngressResponse * revokeClusterSecurityGroupIngress (const RevokeClusterSecurityGroupIngressRequest &request)
RevokeSnapshotAccessResponse * revokeSnapshotAccess (const RevokeSnapshotAccessRequest &request)
RotateEncryptionKeyResponse * rotateEncryptionKey (const RotateEncryptionKeyRequest &request)
Public Member Functions
RedshiftClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new RedshiftClient object.
RedshiftClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new RedshiftClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Redshift.
<fullname>Amazon Redshift</fullname>
Overview
</p
This is an interface reference for Amazon Redshift. It contains documentation for one of the programming or command line interfaces you can use to manage Amazon Redshift clusters. Note that Amazon Redshift is asynchronous, which means that some interfaces may require techniques, such as polling or asynchronous callback handlers, to determine when a command has been applied. In this reference, the parameter descriptions indicate whether a change is applied immediately, on the next instance reboot, or during the next maintenance window. For a summary of the Amazon Redshift cluster management interfaces, go to Using the Amazon Redshift Management Interfaces>
Amazon Redshift manages all the work of setting up, operating, and scaling a data warehouse: provisioning capacity, monitoring and backing up the cluster, and applying patches and upgrades to the Amazon Redshift engine. You can focus on using your data to acquire new insights for your business and
customers>
If you are a first-time user of Amazon Redshift, we recommend that you begin by reading the Amazon Redshift Getting Started Guide>
If you are a database developer, the Amazon Redshift Database Developer Guide explains how to design, build, query, and maintain the databases that make up your data warehouse.
Definition at line 36 of file redshiftclient.h.
Constructor & Destructor Documentation
RedshiftClient() [1/2]
AWS::Redshift::RedshiftClient::RedshiftClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new RedshiftClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 76 of file redshiftclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new RedshiftClientPrivate(this), parent)
 {
     Q_D(RedshiftClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
RedshiftClient() [2/2]
AWS::Redshift::RedshiftClient::RedshiftClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new RedshiftClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 106 of file redshiftclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new RedshiftClientPrivate(this), parent)
 {
     Q_D(RedshiftClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
redshift/redshiftclient.h
redshift/redshiftclient.cpp