libqtaws: GameLiftClient Class Reference
GameLiftClient Class Reference
Client for Amazon GameLift.
Public Slots
GameLiftCreateAliasResponse * createAlias (const GameLiftCreateAliasRequest &request)
GameLiftCreateBuildResponse * createBuild (const GameLiftCreateBuildRequest &request)
GameLiftCreateFleetResponse * createFleet (const GameLiftCreateFleetRequest &request)
GameLiftCreateGameSessionResponse * createGameSession (const GameLiftCreateGameSessionRequest &request)
GameLiftCreatePlayerSessionResponse * createPlayerSession (const GameLiftCreatePlayerSessionRequest &request)
GameLiftCreatePlayerSessionsResponse * createPlayerSessions (const GameLiftCreatePlayerSessionsRequest &request)
GameLiftDeleteAliasResponse * deleteAlias (const GameLiftDeleteAliasRequest &request)
GameLiftDeleteBuildResponse * deleteBuild (const GameLiftDeleteBuildRequest &request)
GameLiftDeleteFleetResponse * deleteFleet (const GameLiftDeleteFleetRequest &request)
GameLiftDeleteScalingPolicyResponse * deleteScalingPolicy (const GameLiftDeleteScalingPolicyRequest &request)
GameLiftDescribeAliasResponse * describeAlias (const GameLiftDescribeAliasRequest &request)
GameLiftDescribeBuildResponse * describeBuild (const GameLiftDescribeBuildRequest &request)
GameLiftDescribeEC2InstanceLimitsResponse * describeEC2InstanceLimits (const GameLiftDescribeEC2InstanceLimitsRequest &request)
GameLiftDescribeFleetAttributesResponse * describeFleetAttributes (const GameLiftDescribeFleetAttributesRequest &request)
GameLiftDescribeFleetCapacityResponse * describeFleetCapacity (const GameLiftDescribeFleetCapacityRequest &request)
GameLiftDescribeFleetEventsResponse * describeFleetEvents (const GameLiftDescribeFleetEventsRequest &request)
GameLiftDescribeFleetPortSettingsResponse * describeFleetPortSettings (const GameLiftDescribeFleetPortSettingsRequest &request)
GameLiftDescribeFleetUtilizationResponse * describeFleetUtilization (const GameLiftDescribeFleetUtilizationRequest &request)
GameLiftDescribeGameSessionDetailsResponse * describeGameSessionDetails (const GameLiftDescribeGameSessionDetailsRequest &request)
GameLiftDescribeGameSessionsResponse * describeGameSessions (const GameLiftDescribeGameSessionsRequest &request)
GameLiftDescribePlayerSessionsResponse * describePlayerSessions (const GameLiftDescribePlayerSessionsRequest &request)
GameLiftDescribeRuntimeConfigurationResponse * describeRuntimeConfiguration (const GameLiftDescribeRuntimeConfigurationRequest &request)
GameLiftDescribeScalingPoliciesResponse * describeScalingPolicies (const GameLiftDescribeScalingPoliciesRequest &request)
GameLiftGetGameSessionLogUrlResponse * getGameSessionLogUrl (const GameLiftGetGameSessionLogUrlRequest &request)
GameLiftListAliasesResponse * listAliases (const GameLiftListAliasesRequest &request)
GameLiftListBuildsResponse * listBuilds (const GameLiftListBuildsRequest &request)
GameLiftListFleetsResponse * listFleets (const GameLiftListFleetsRequest &request)
GameLiftPutScalingPolicyResponse * putScalingPolicy (const GameLiftPutScalingPolicyRequest &request)
GameLiftRequestUploadCredentialsResponse * requestUploadCredentials (const GameLiftRequestUploadCredentialsRequest &request)
GameLiftResolveAliasResponse * resolveAlias (const GameLiftResolveAliasRequest &request)
GameLiftSearchGameSessionsResponse * searchGameSessions (const GameLiftSearchGameSessionsRequest &request)
GameLiftUpdateAliasResponse * updateAlias (const GameLiftUpdateAliasRequest &request)
GameLiftUpdateBuildResponse * updateBuild (const GameLiftUpdateBuildRequest &request)
GameLiftUpdateFleetAttributesResponse * updateFleetAttributes (const GameLiftUpdateFleetAttributesRequest &request)
GameLiftUpdateFleetCapacityResponse * updateFleetCapacity (const GameLiftUpdateFleetCapacityRequest &request)
GameLiftUpdateFleetPortSettingsResponse * updateFleetPortSettings (const GameLiftUpdateFleetPortSettingsRequest &request)
GameLiftUpdateGameSessionResponse * updateGameSession (const GameLiftUpdateGameSessionRequest &request)
GameLiftUpdateRuntimeConfigurationResponse * updateRuntimeConfiguration (const GameLiftUpdateRuntimeConfigurationRequest &request)
Public Member Functions
GameLiftClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new GameLiftClient object.
GameLiftClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new GameLiftClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon GameLift.
<fullname>Amazon GameLift Service</fullname>
Welcome to the Amazon GameLift API Reference. Amazon GameLift is a managed Amazon Web Services (AWS) service for developers who need a scalable, server-based solution for multiplayer games. Amazon GameLift provides setup and deployment of game servers, and handles infrastructure scaling and session management.
This reference describes the low-level service API for GameLift. You can call this API directly or use the AWS SDK for your preferred language. The AWS SDK includes a set of high-level GameLift actions multiplayer game sessions. Alternatively, you can use the AWS command-line interface (CLI) tool, which includes commands for GameLift. For administrative actions, you can also use the Amazon GameLift console.
More Resources
Amazon GameLift Developer Guide: Learn more about GameLift features and how to use them
Lumberyard and GameLift Tutorials: Get started fast with walkthroughs and sample projects
GameDev Blog: Stay up to date with new features and techniques
GameDev Forums: Connect with the GameDev community
Manage Games and Players Through GameLift
Call these actions from your game clients and/or services to create and manage multiplayer game sessions and player sessions.
Game sessions
CreateGameSession
DescribeGameSessions
DescribeGameSessionDetails
UpdateGameSession
SearchGameSessions
Player sessions
CreatePlayerSession
CreatePlayerSessions
DescribePlayerSessions
Other actions:
GetGameSessionLogUrl
Set Up and Manage Game Servers
Use these administrative actions to configure GameLift to host your game servers. When setting up GameLift, you'll need to (1) configure a build for your game and upload build files, and (2) set up one or more fleets to host game sessions. Once you've created and activated a fleet, you can assign aliases to it, scale capacity, track performance and utilization, etc.
Manage your builds:
ListBuilds
CreateBuild
DescribeBuild
UpdateBuild
DeleteBuild
RequestUploadCredentials
Manage your fleets:
ListFleets
CreateFleet
Describe fleets:
DescribeFleetAttributes
DescribeFleetCapacity
DescribeFleetPortSettings
DescribeFleetUtilization
DescribeEC2InstanceLimits
DescribeFleetEvents
DescribeRuntimeConfiguration
Update fleets:
UpdateFleetAttributes
UpdateFleetCapacity
UpdateFleetPortSettings
UpdateRuntimeConfiguration
DeleteFleet
Manage fleet aliases:
ListAliases
CreateAlias
DescribeAlias
UpdateAlias
DeleteAlias
ResolveAlias
Manage autoscaling:
PutScalingPolicy
DescribeScalingPolicies
DeleteScalingPolicy
To view changes to the API, see the GameLift Document History page.
Definition at line 33 of file gameliftclient.h.
Constructor & Destructor Documentation
GameLiftClient::GameLiftClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new GameLiftClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 68 of file gameliftclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new GameLiftClientPrivate(this), parent)
 {
     Q_D(GameLiftClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
GameLiftClient::GameLiftClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new GameLiftClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 98 of file gameliftclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new GameLiftClientPrivate(this), parent)
 {
     Q_D(GameLiftClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
gamelift/gameliftclient.h
gamelift/gameliftclient.cpp