libqtaws: AWS::DAX::DaxClient Class Reference
AWS::DAX::DaxClient Class Reference
Client for Amazon DynamoDB Accelerator (DAX) (DAX)
Public Slots
CreateClusterResponse * createCluster (const CreateClusterRequest &request)
CreateParameterGroupResponse * createParameterGroup (const CreateParameterGroupRequest &request)
CreateSubnetGroupResponse * createSubnetGroup (const CreateSubnetGroupRequest &request)
DecreaseReplicationFactorResponse * decreaseReplicationFactor (const DecreaseReplicationFactorRequest &request)
DeleteClusterResponse * deleteCluster (const DeleteClusterRequest &request)
DeleteParameterGroupResponse * deleteParameterGroup (const DeleteParameterGroupRequest &request)
DeleteSubnetGroupResponse * deleteSubnetGroup (const DeleteSubnetGroupRequest &request)
DescribeClustersResponse * describeClusters (const DescribeClustersRequest &request)
DescribeDefaultParametersResponse * describeDefaultParameters (const DescribeDefaultParametersRequest &request)
DescribeEventsResponse * describeEvents (const DescribeEventsRequest &request)
DescribeParameterGroupsResponse * describeParameterGroups (const DescribeParameterGroupsRequest &request)
DescribeParametersResponse * describeParameters (const DescribeParametersRequest &request)
DescribeSubnetGroupsResponse * describeSubnetGroups (const DescribeSubnetGroupsRequest &request)
IncreaseReplicationFactorResponse * increaseReplicationFactor (const IncreaseReplicationFactorRequest &request)
ListTagsResponse * listTags (const ListTagsRequest &request)
RebootNodeResponse * rebootNode (const RebootNodeRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateClusterResponse * updateCluster (const UpdateClusterRequest &request)
UpdateParameterGroupResponse * updateParameterGroup (const UpdateParameterGroupRequest &request)
UpdateSubnetGroupResponse * updateSubnetGroup (const UpdateSubnetGroupRequest &request)
Public Member Functions
DaxClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DaxClient object.
DaxClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DaxClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon DynamoDB Accelerator (DAX) (DAX)
DAX is a managed caching service engineered for Amazon DynamoDB. DAX dramatically speeds up database reads by caching frequently-accessed data from DynamoDB, so applications can access that data with sub-millisecond latency. You can create a DAX cluster easily, using the AWS Management Console. With a few simple modifications to your code, your application can begin taking advantage of the DAX cluster and realize significant improvements in read
Definition at line 36 of file daxclient.h.
Constructor & Destructor Documentation
DaxClient() [1/2]
AWS::DAX::DaxClient::DaxClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DaxClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 50 of file daxclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new DaxClientPrivate(this), parent)
 {
     Q_D(DaxClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
DaxClient() [2/2]
AWS::DAX::DaxClient::DaxClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DaxClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 80 of file daxclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new DaxClientPrivate(this), parent)
 {
     Q_D(DaxClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
dax/daxclient.h
dax/daxclient.cpp