libqtaws: AWS::KMS::KmsClient Class Reference
AWS::KMS::KmsClient Class Reference
Client for AWS Key Management Service (KMS)
Public Slots
CancelKeyDeletionResponse * cancelKeyDeletion (const CancelKeyDeletionRequest &request)
CreateAliasResponse * createAlias (const CreateAliasRequest &request)
CreateGrantResponse * createGrant (const CreateGrantRequest &request)
CreateKeyResponse * createKey (const CreateKeyRequest &request)
DecryptResponse * decrypt (const DecryptRequest &request)
DeleteAliasResponse * deleteAlias (const DeleteAliasRequest &request)
DeleteImportedKeyMaterialResponse * deleteImportedKeyMaterial (const DeleteImportedKeyMaterialRequest &request)
DescribeKeyResponse * describeKey (const DescribeKeyRequest &request)
DisableKeyResponse * disableKey (const DisableKeyRequest &request)
DisableKeyRotationResponse * disableKeyRotation (const DisableKeyRotationRequest &request)
EnableKeyResponse * enableKey (const EnableKeyRequest &request)
EnableKeyRotationResponse * enableKeyRotation (const EnableKeyRotationRequest &request)
EncryptResponse * encrypt (const EncryptRequest &request)
GenerateDataKeyResponse * generateDataKey (const GenerateDataKeyRequest &request)
GenerateDataKeyWithoutPlaintextResponse * generateDataKeyWithoutPlaintext (const GenerateDataKeyWithoutPlaintextRequest &request)
GenerateRandomResponse * generateRandom (const GenerateRandomRequest &request)
GetKeyPolicyResponse * getKeyPolicy (const GetKeyPolicyRequest &request)
GetKeyRotationStatusResponse * getKeyRotationStatus (const GetKeyRotationStatusRequest &request)
GetParametersForImportResponse * getParametersForImport (const GetParametersForImportRequest &request)
ImportKeyMaterialResponse * importKeyMaterial (const ImportKeyMaterialRequest &request)
ListAliasesResponse * listAliases (const ListAliasesRequest &request)
ListGrantsResponse * listGrants (const ListGrantsRequest &request)
ListKeyPoliciesResponse * listKeyPolicies (const ListKeyPoliciesRequest &request)
ListKeysResponse * listKeys (const ListKeysRequest &request)
ListResourceTagsResponse * listResourceTags (const ListResourceTagsRequest &request)
ListRetirableGrantsResponse * listRetirableGrants (const ListRetirableGrantsRequest &request)
PutKeyPolicyResponse * putKeyPolicy (const PutKeyPolicyRequest &request)
ReEncryptResponse * reEncrypt (const ReEncryptRequest &request)
RetireGrantResponse * retireGrant (const RetireGrantRequest &request)
RevokeGrantResponse * revokeGrant (const RevokeGrantRequest &request)
ScheduleKeyDeletionResponse * scheduleKeyDeletion (const ScheduleKeyDeletionRequest &request)
TagResourceResponse * tagResource (const TagResourceRequest &request)
UntagResourceResponse * untagResource (const UntagResourceRequest &request)
UpdateAliasResponse * updateAlias (const UpdateAliasRequest &request)
UpdateKeyDescriptionResponse * updateKeyDescription (const UpdateKeyDescriptionRequest &request)
Public Member Functions
KmsClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new KmsClient object.
KmsClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new KmsClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Key Management Service (KMS)
<fullname>AWS Key Management Service</fullname>
AWS Key Management Service (AWS KMS) is an encryption and key management web service. This guide describes the AWS KMS operations that you can call programmatically. For general information about AWS KMS, see the AWS Key Management Service Developer Guide> <note>
AWS provides SDKs that consist of libraries and sample code for various programming languages and platforms (Java, Ruby, .Net, iOS, Android, etc.). The SDKs provide a convenient way to create programmatic access to AWS KMS and other AWS services. For example, the SDKs take care of tasks such as signing requests (see below), managing errors, and retrying requests automatically. For more information about the AWS SDKs, including how to download and install them, see Tools for Amazon Web Services> </note>
We recommend that you use the AWS SDKs to make programmatic API calls to AWS
KMS>
Clients must support TLS (Transport Layer Security) 1.0. We recommend TLS 1.2. Clients must also support cipher suites with Perfect Forward Secrecy (PFS) such as Ephemeral Diffie-Hellman (DHE) or Elliptic Curve Ephemeral Diffie-Hellman (ECDHE). Most modern systems such as Java 7 and later support these
modes>
Signing Requests
</p
Requests must be signed by using an access key ID and a secret access key. We strongly recommend that you do not use your AWS account (root) access key ID and secret key for everyday work with AWS KMS. Instead, use the access key ID and secret access key for an IAM user, or you can use the AWS Security Token Service to generate temporary security credentials that you can use to sign
requests>
All AWS KMS operations require Signature Version 4>
Logging API Requests
</p
AWS KMS supports AWS CloudTrail, a service that logs AWS API calls and related events for your AWS account and delivers them to an Amazon S3 bucket that you specify. By using the information collected by CloudTrail, you can determine what requests were made to AWS KMS, who made the request, when it was made, and so on. To learn more about CloudTrail, including how to turn it on and find your log files, see the AWS CloudTrail User Guide>
Additional Resources
</p
For more information about credentials and request signing, see the
following>
AWS Security Credentials - This topic provides general information about the types of credentials used for accessing
AWS>
Temporary Security Credentials - This section of the IAM User Guide describes how to create and use temporary security
credentials>
Signature Version 4 Signing Process
This set of topics walks you through the process of signing a request using an access key ID and a secret access
key>
Commonly Used APIs
</p
Of the APIs discussed in this guide, the following will prove the most useful for most applications. You will likely perform actions other than these, such as creating keys and assigning policies, by using the
console>
Encrypt
</p
Decrypt
</p
GenerateDataKey
</p
GenerateDataKeyWithoutPlaintext
Definition at line 36 of file kmsclient.h.
Constructor & Destructor Documentation
KmsClient() [1/2]
AWS::KMS::KmsClient::KmsClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new KmsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 145 of file kmsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new KmsClientPrivate(this), parent)
 {
     Q_D(KmsClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
KmsClient() [2/2]
AWS::KMS::KmsClient::KmsClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new KmsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 175 of file kmsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new KmsClientPrivate(this), parent)
 {
     Q_D(KmsClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
kms/kmsclient.h
kms/kmsclient.cpp