libqtaws: AWS::Pinpoint::PinpointClient Class Reference
AWS::Pinpoint::PinpointClient Class Reference
Client for Amazon Pinpoint.
Public Slots
CreateAppResponse * createApp (const CreateAppRequest &request)
CreateCampaignResponse * createCampaign (const CreateCampaignRequest &request)
CreateExportJobResponse * createExportJob (const CreateExportJobRequest &request)
CreateImportJobResponse * createImportJob (const CreateImportJobRequest &request)
CreateSegmentResponse * createSegment (const CreateSegmentRequest &request)
DeleteAdmChannelResponse * deleteAdmChannel (const DeleteAdmChannelRequest &request)
DeleteApnsChannelResponse * deleteApnsChannel (const DeleteApnsChannelRequest &request)
DeleteApnsSandboxChannelResponse * deleteApnsSandboxChannel (const DeleteApnsSandboxChannelRequest &request)
DeleteApnsVoipChannelResponse * deleteApnsVoipChannel (const DeleteApnsVoipChannelRequest &request)
DeleteApnsVoipSandboxChannelResponse * deleteApnsVoipSandboxChannel (const DeleteApnsVoipSandboxChannelRequest &request)
DeleteAppResponse * deleteApp (const DeleteAppRequest &request)
DeleteBaiduChannelResponse * deleteBaiduChannel (const DeleteBaiduChannelRequest &request)
DeleteCampaignResponse * deleteCampaign (const DeleteCampaignRequest &request)
DeleteEmailChannelResponse * deleteEmailChannel (const DeleteEmailChannelRequest &request)
DeleteEndpointResponse * deleteEndpoint (const DeleteEndpointRequest &request)
DeleteEventStreamResponse * deleteEventStream (const DeleteEventStreamRequest &request)
DeleteGcmChannelResponse * deleteGcmChannel (const DeleteGcmChannelRequest &request)
DeleteSegmentResponse * deleteSegment (const DeleteSegmentRequest &request)
DeleteSmsChannelResponse * deleteSmsChannel (const DeleteSmsChannelRequest &request)
GetAdmChannelResponse * getAdmChannel (const GetAdmChannelRequest &request)
GetApnsChannelResponse * getApnsChannel (const GetApnsChannelRequest &request)
GetApnsSandboxChannelResponse * getApnsSandboxChannel (const GetApnsSandboxChannelRequest &request)
GetApnsVoipChannelResponse * getApnsVoipChannel (const GetApnsVoipChannelRequest &request)
GetApnsVoipSandboxChannelResponse * getApnsVoipSandboxChannel (const GetApnsVoipSandboxChannelRequest &request)
GetAppResponse * getApp (const GetAppRequest &request)
GetApplicationSettingsResponse * getApplicationSettings (const GetApplicationSettingsRequest &request)
GetAppsResponse * getApps (const GetAppsRequest &request)
GetBaiduChannelResponse * getBaiduChannel (const GetBaiduChannelRequest &request)
GetCampaignResponse * getCampaign (const GetCampaignRequest &request)
GetCampaignActivitiesResponse * getCampaignActivities (const GetCampaignActivitiesRequest &request)
GetCampaignVersionResponse * getCampaignVersion (const GetCampaignVersionRequest &request)
GetCampaignVersionsResponse * getCampaignVersions (const GetCampaignVersionsRequest &request)
GetCampaignsResponse * getCampaigns (const GetCampaignsRequest &request)
GetEmailChannelResponse * getEmailChannel (const GetEmailChannelRequest &request)
GetEndpointResponse * getEndpoint (const GetEndpointRequest &request)
GetEventStreamResponse * getEventStream (const GetEventStreamRequest &request)
GetExportJobResponse * getExportJob (const GetExportJobRequest &request)
GetExportJobsResponse * getExportJobs (const GetExportJobsRequest &request)
GetGcmChannelResponse * getGcmChannel (const GetGcmChannelRequest &request)
GetImportJobResponse * getImportJob (const GetImportJobRequest &request)
GetImportJobsResponse * getImportJobs (const GetImportJobsRequest &request)
GetSegmentResponse * getSegment (const GetSegmentRequest &request)
GetSegmentExportJobsResponse * getSegmentExportJobs (const GetSegmentExportJobsRequest &request)
GetSegmentImportJobsResponse * getSegmentImportJobs (const GetSegmentImportJobsRequest &request)
GetSegmentVersionResponse * getSegmentVersion (const GetSegmentVersionRequest &request)
GetSegmentVersionsResponse * getSegmentVersions (const GetSegmentVersionsRequest &request)
GetSegmentsResponse * getSegments (const GetSegmentsRequest &request)
GetSmsChannelResponse * getSmsChannel (const GetSmsChannelRequest &request)
PutEventStreamResponse * putEventStream (const PutEventStreamRequest &request)
SendMessagesResponse * sendMessages (const SendMessagesRequest &request)
SendUsersMessagesResponse * sendUsersMessages (const SendUsersMessagesRequest &request)
UpdateAdmChannelResponse * updateAdmChannel (const UpdateAdmChannelRequest &request)
UpdateApnsChannelResponse * updateApnsChannel (const UpdateApnsChannelRequest &request)
UpdateApnsSandboxChannelResponse * updateApnsSandboxChannel (const UpdateApnsSandboxChannelRequest &request)
UpdateApnsVoipChannelResponse * updateApnsVoipChannel (const UpdateApnsVoipChannelRequest &request)
UpdateApnsVoipSandboxChannelResponse * updateApnsVoipSandboxChannel (const UpdateApnsVoipSandboxChannelRequest &request)
UpdateApplicationSettingsResponse * updateApplicationSettings (const UpdateApplicationSettingsRequest &request)
UpdateBaiduChannelResponse * updateBaiduChannel (const UpdateBaiduChannelRequest &request)
UpdateCampaignResponse * updateCampaign (const UpdateCampaignRequest &request)
UpdateEmailChannelResponse * updateEmailChannel (const UpdateEmailChannelRequest &request)
UpdateEndpointResponse * updateEndpoint (const UpdateEndpointRequest &request)
UpdateEndpointsBatchResponse * updateEndpointsBatch (const UpdateEndpointsBatchRequest &request)
UpdateGcmChannelResponse * updateGcmChannel (const UpdateGcmChannelRequest &request)
UpdateSegmentResponse * updateSegment (const UpdateSegmentRequest &request)
UpdateSmsChannelResponse * updateSmsChannel (const UpdateSmsChannelRequest &request)
Public Member Functions
PinpointClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new PinpointClient object.
PinpointClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new PinpointClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Pinpoint.
Definition at line 36 of file pinpointclient.h.
Constructor & Destructor Documentation
PinpointClient() [1/2]
AWS::Pinpoint::PinpointClient::PinpointClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new PinpointClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 46 of file pinpointclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new PinpointClientPrivate(this), parent)
 {
     Q_D(PinpointClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
PinpointClient() [2/2]
AWS::Pinpoint::PinpointClient::PinpointClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new PinpointClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 76 of file pinpointclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new PinpointClientPrivate(this), parent)
 {
     Q_D(PinpointClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
pinpoint/pinpointclient.h
pinpoint/pinpointclient.cpp