libqtaws: AWS::CloudSearch::CloudSearchClient Class Reference
AWS::CloudSearch::CloudSearchClient Class Reference
Client for Amazon CloudSearch.
Public Slots
BuildSuggestersResponse * buildSuggesters (const BuildSuggestersRequest &request)
CreateDomainResponse * createDomain (const CreateDomainRequest &request)
DefineAnalysisSchemeResponse * defineAnalysisScheme (const DefineAnalysisSchemeRequest &request)
DefineExpressionResponse * defineExpression (const DefineExpressionRequest &request)
DefineIndexFieldResponse * defineIndexField (const DefineIndexFieldRequest &request)
DefineSuggesterResponse * defineSuggester (const DefineSuggesterRequest &request)
DeleteAnalysisSchemeResponse * deleteAnalysisScheme (const DeleteAnalysisSchemeRequest &request)
DeleteDomainResponse * deleteDomain (const DeleteDomainRequest &request)
DeleteExpressionResponse * deleteExpression (const DeleteExpressionRequest &request)
DeleteIndexFieldResponse * deleteIndexField (const DeleteIndexFieldRequest &request)
DeleteSuggesterResponse * deleteSuggester (const DeleteSuggesterRequest &request)
DescribeAnalysisSchemesResponse * describeAnalysisSchemes (const DescribeAnalysisSchemesRequest &request)
DescribeAvailabilityOptionsResponse * describeAvailabilityOptions (const DescribeAvailabilityOptionsRequest &request)
DescribeDomainsResponse * describeDomains (const DescribeDomainsRequest &request)
DescribeExpressionsResponse * describeExpressions (const DescribeExpressionsRequest &request)
DescribeIndexFieldsResponse * describeIndexFields (const DescribeIndexFieldsRequest &request)
DescribeScalingParametersResponse * describeScalingParameters (const DescribeScalingParametersRequest &request)
DescribeServiceAccessPoliciesResponse * describeServiceAccessPolicies (const DescribeServiceAccessPoliciesRequest &request)
DescribeSuggestersResponse * describeSuggesters (const DescribeSuggestersRequest &request)
IndexDocumentsResponse * indexDocuments (const IndexDocumentsRequest &request)
ListDomainNamesResponse * listDomainNames ()
UpdateAvailabilityOptionsResponse * updateAvailabilityOptions (const UpdateAvailabilityOptionsRequest &request)
UpdateScalingParametersResponse * updateScalingParameters (const UpdateScalingParametersRequest &request)
UpdateServiceAccessPoliciesResponse * updateServiceAccessPolicies (const UpdateServiceAccessPoliciesRequest &request)
Public Member Functions
CloudSearchClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudSearchClient object.
CloudSearchClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new CloudSearchClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon CloudSearch.
<fullname>Amazon CloudSearch Configuration Service</fullname>
You use the Amazon CloudSearch configuration service to create, configure, and manage search domains. Configuration service requests are submitted using the AWS Query protocol. AWS Query requests are HTTP or HTTPS requests submitted via HTTP GET or POST with a query parameter named
Action>
The endpoint for configuration service requests is region-specific: cloudsearch.region.amazonaws.com. For example, cloudsearch.us-east-1.amazonaws.com. For a current list of supported regions and endpoints, see Regions and
Definition at line 36 of file cloudsearchclient.h.
Constructor & Destructor Documentation
CloudSearchClient() [1/2]
AWS::CloudSearch::CloudSearchClient::CloudSearchClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudSearchClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 57 of file cloudsearchclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new CloudSearchClientPrivate(this), parent)
 {
     Q_D(CloudSearchClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
CloudSearchClient() [2/2]
AWS::CloudSearch::CloudSearchClient::CloudSearchClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new CloudSearchClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 87 of file cloudsearchclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new CloudSearchClientPrivate(this), parent)
 {
     Q_D(CloudSearchClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
cloudsearch/cloudsearchclient.h
cloudsearch/cloudsearchclient.cpp