libqtaws: AWS::Organizations::OrganizationsClient Class Reference
AWS::Organizations::OrganizationsClient Class Reference
Client for AWS Organizations.
Public Slots
AcceptHandshakeResponse * acceptHandshake (const AcceptHandshakeRequest &request)
AttachPolicyResponse * attachPolicy (const AttachPolicyRequest &request)
CancelHandshakeResponse * cancelHandshake (const CancelHandshakeRequest &request)
CreateAccountResponse * createAccount (const CreateAccountRequest &request)
CreateOrganizationResponse * createOrganization (const CreateOrganizationRequest &request)
CreateOrganizationalUnitResponse * createOrganizationalUnit (const CreateOrganizationalUnitRequest &request)
CreatePolicyResponse * createPolicy (const CreatePolicyRequest &request)
DeclineHandshakeResponse * declineHandshake (const DeclineHandshakeRequest &request)
DeleteOrganizationResponse * deleteOrganization ()
DeleteOrganizationalUnitResponse * deleteOrganizationalUnit (const DeleteOrganizationalUnitRequest &request)
DeletePolicyResponse * deletePolicy (const DeletePolicyRequest &request)
DescribeAccountResponse * describeAccount (const DescribeAccountRequest &request)
DescribeCreateAccountStatusResponse * describeCreateAccountStatus (const DescribeCreateAccountStatusRequest &request)
DescribeHandshakeResponse * describeHandshake (const DescribeHandshakeRequest &request)
DescribeOrganizationResponse * describeOrganization ()
DescribeOrganizationalUnitResponse * describeOrganizationalUnit (const DescribeOrganizationalUnitRequest &request)
DescribePolicyResponse * describePolicy (const DescribePolicyRequest &request)
DetachPolicyResponse * detachPolicy (const DetachPolicyRequest &request)
DisableAWSServiceAccessResponse * disableAWSServiceAccess (const DisableAWSServiceAccessRequest &request)
DisablePolicyTypeResponse * disablePolicyType (const DisablePolicyTypeRequest &request)
EnableAWSServiceAccessResponse * enableAWSServiceAccess (const EnableAWSServiceAccessRequest &request)
EnableAllFeaturesResponse * enableAllFeatures (const EnableAllFeaturesRequest &request)
EnablePolicyTypeResponse * enablePolicyType (const EnablePolicyTypeRequest &request)
InviteAccountToOrganizationResponse * inviteAccountToOrganization (const InviteAccountToOrganizationRequest &request)
LeaveOrganizationResponse * leaveOrganization ()
ListAWSServiceAccessForOrganizationResponse * listAWSServiceAccessForOrganization (const ListAWSServiceAccessForOrganizationRequest &request)
ListAccountsResponse * listAccounts (const ListAccountsRequest &request)
ListAccountsForParentResponse * listAccountsForParent (const ListAccountsForParentRequest &request)
ListChildrenResponse * listChildren (const ListChildrenRequest &request)
ListCreateAccountStatusResponse * listCreateAccountStatus (const ListCreateAccountStatusRequest &request)
ListHandshakesForAccountResponse * listHandshakesForAccount (const ListHandshakesForAccountRequest &request)
ListHandshakesForOrganizationResponse * listHandshakesForOrganization (const ListHandshakesForOrganizationRequest &request)
ListOrganizationalUnitsForParentResponse * listOrganizationalUnitsForParent (const ListOrganizationalUnitsForParentRequest &request)
ListParentsResponse * listParents (const ListParentsRequest &request)
ListPoliciesResponse * listPolicies (const ListPoliciesRequest &request)
ListPoliciesForTargetResponse * listPoliciesForTarget (const ListPoliciesForTargetRequest &request)
ListRootsResponse * listRoots (const ListRootsRequest &request)
ListTargetsForPolicyResponse * listTargetsForPolicy (const ListTargetsForPolicyRequest &request)
MoveAccountResponse * moveAccount (const MoveAccountRequest &request)
RemoveAccountFromOrganizationResponse * removeAccountFromOrganization (const RemoveAccountFromOrganizationRequest &request)
UpdateOrganizationalUnitResponse * updateOrganizationalUnit (const UpdateOrganizationalUnitRequest &request)
UpdatePolicyResponse * updatePolicy (const UpdatePolicyRequest &request)
Public Member Functions
OrganizationsClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new OrganizationsClient object.
OrganizationsClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new OrganizationsClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Organizations.
<fullname>AWS Organizations API Reference</fullname>
AWS Organizations is a web service that enables you to consolidate your multiple AWS accounts into an organization and centrally manage your accounts and their
resources>
This guide provides descriptions of the Organizations API. For more information about using this service, see the AWS Organizations User Guide>
API Version
</p
This version of the Organizations API Reference documents the Organizations API version
2016-11-28> <note>
As an alternative to using the API directly, you can use one of the AWS SDKs, which consist of libraries and sample code for various programming languages and platforms (Java, Ruby, .NET, iOS, Android, and more). The SDKs provide a convenient way to create programmatic access to AWS Organizations. For example, the SDKs take care of cryptographically signing requests, managing errors, and retrying requests automatically. For more information about the AWS SDKs, including how to download and install them, see Tools for Amazon Web Services> </note>
We recommend that you use the AWS SDKs to make programmatic API calls to Organizations. However, you also can use the Organizations Query API to make direct calls to the Organizations web service. To learn more about the Organizations Query API, see Making Query Requests in the AWS Organizations User Guide. Organizations supports GET and POST requests for all actions. That is, the API does not require you to use GET for some actions and POST for others. However, GET requests are subject to the limitation size of a URL. Therefore, for operations that require larger sizes, use a POST
request>
Signing Requests
</p
When you send HTTP requests to AWS, you must sign the requests so that AWS can identify who sent them. You sign requests with your AWS access key, which consists of an access key ID and a secret access key. We strongly recommend that you do not create an access key for your root account. Anyone who has the access key for your root account has unrestricted access to all the resources in your account. Instead, create an access key for an IAM user account that has administrative privileges. As another option, use AWS Security Token Service to generate temporary security credentials, and use those credentials to sign requests.
</p
To sign requests, we recommend that you use Signature Version 4. If you have an existing application that uses Signature Version 2, you do not have to update it to use Signature Version 4. However, some operations now require Signature Version 4. The documentation for operations that require version 4 indicate this requirement.
</p
When you use the AWS Command Line Interface (AWS CLI) or one of the AWS SDKs to make requests to AWS, these tools automatically sign the requests for you with the access key that you specify when you configure the
tools>
In this release, each organization can have only one root. In a future release, a single organization will support multiple
roots>
Support and Feedback for AWS Organizations
</p
We welcome your feedback. Send your comments to feedback-awsorganizations@amazon.com or post your feedback and questions in the AWS Organizations support forum. For more information about the AWS support forums, see Forums Help>
Endpoint to Call When Using the CLI or the AWS API
</p
For the current release of Organizations, you must specify the us-east-1 region for all AWS API and CLI calls. You can do this in the CLI by using these parameters and
commands>
Use the following parameter with each command to specify both the endpoint and its
region>
–endpoint-url https://organizations.us-east-1.amazonaws.com
</p
Use the default endpoint, but configure your default region with this
command>
aws configure set default.region us-east-1
</p
Use the following parameter with each command to specify the
endpoint>
–region us-east-1
</p
For the various SDKs used to call the APIs, see the documentation for the SDK of interest to learn how to direct the requests to a specific endpoint. For more information, see Regions and Endpoints in the AWS General Reference.
</p
How examples are presented
</p
The JSON returned by the AWS Organizations service as response to your requests is returned as a single long string without line breaks or formatting whitespace. Both line breaks and whitespace are included in the examples in this guide to improve readability. When example input parameters also would result in long strings that would extend beyond the screen, we insert line breaks to enhance readability. You should always submit the input as a single JSON text
string>
Recording API Requests
</p
AWS Organizations supports AWS CloudTrail, a service that records AWS API calls for your AWS account and delivers log files to an Amazon S3 bucket. By using information collected by AWS CloudTrail, you can determine which requests were successfully made to Organizations, who made the request, when it was made, and so on. For more about AWS Organizations and its support for AWS CloudTrail, see Logging AWS Organizations Events with AWS CloudTrail in the AWS Organizations User Guide. To learn more about CloudTrail, including how to turn it on and find your log files, see the AWS CloudTrail User
Definition at line 36 of file organizationsclient.h.
Constructor & Destructor Documentation
OrganizationsClient() [1/2]
AWS::Organizations::OrganizationsClient::OrganizationsClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new OrganizationsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 188 of file organizationsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new OrganizationsClientPrivate(this), parent)
 {
     Q_D(OrganizationsClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
OrganizationsClient() [2/2]
AWS::Organizations::OrganizationsClient::OrganizationsClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new OrganizationsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 218 of file organizationsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new OrganizationsClientPrivate(this), parent)
 {
     Q_D(OrganizationsClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
organizations/organizationsclient.h
organizations/organizationsclient.cpp