libqtaws: AWS::DatabaseMigrationService::DatabaseMigrationServiceClient Class Reference
AWS::DatabaseMigrationService::DatabaseMigrationServiceClient Class Reference
Client for AWS Database Migration Service.
Public Slots
AddTagsToResourceResponse * addTagsToResource (const AddTagsToResourceRequest &request)
CreateEndpointResponse * createEndpoint (const CreateEndpointRequest &request)
CreateEventSubscriptionResponse * createEventSubscription (const CreateEventSubscriptionRequest &request)
CreateReplicationInstanceResponse * createReplicationInstance (const CreateReplicationInstanceRequest &request)
CreateReplicationSubnetGroupResponse * createReplicationSubnetGroup (const CreateReplicationSubnetGroupRequest &request)
CreateReplicationTaskResponse * createReplicationTask (const CreateReplicationTaskRequest &request)
DeleteCertificateResponse * deleteCertificate (const DeleteCertificateRequest &request)
DeleteEndpointResponse * deleteEndpoint (const DeleteEndpointRequest &request)
DeleteEventSubscriptionResponse * deleteEventSubscription (const DeleteEventSubscriptionRequest &request)
DeleteReplicationInstanceResponse * deleteReplicationInstance (const DeleteReplicationInstanceRequest &request)
DeleteReplicationSubnetGroupResponse * deleteReplicationSubnetGroup (const DeleteReplicationSubnetGroupRequest &request)
DeleteReplicationTaskResponse * deleteReplicationTask (const DeleteReplicationTaskRequest &request)
DescribeAccountAttributesResponse * describeAccountAttributes (const DescribeAccountAttributesRequest &request)
DescribeCertificatesResponse * describeCertificates (const DescribeCertificatesRequest &request)
DescribeConnectionsResponse * describeConnections (const DescribeConnectionsRequest &request)
DescribeEndpointTypesResponse * describeEndpointTypes (const DescribeEndpointTypesRequest &request)
DescribeEndpointsResponse * describeEndpoints (const DescribeEndpointsRequest &request)
DescribeEventCategoriesResponse * describeEventCategories (const DescribeEventCategoriesRequest &request)
DescribeEventSubscriptionsResponse * describeEventSubscriptions (const DescribeEventSubscriptionsRequest &request)
DescribeEventsResponse * describeEvents (const DescribeEventsRequest &request)
DescribeOrderableReplicationInstancesResponse * describeOrderableReplicationInstances (const DescribeOrderableReplicationInstancesRequest &request)
DescribeRefreshSchemasStatusResponse * describeRefreshSchemasStatus (const DescribeRefreshSchemasStatusRequest &request)
DescribeReplicationInstanceTaskLogsResponse * describeReplicationInstanceTaskLogs (const DescribeReplicationInstanceTaskLogsRequest &request)
DescribeReplicationInstancesResponse * describeReplicationInstances (const DescribeReplicationInstancesRequest &request)
DescribeReplicationSubnetGroupsResponse * describeReplicationSubnetGroups (const DescribeReplicationSubnetGroupsRequest &request)
DescribeReplicationTaskAssessmentResultsResponse * describeReplicationTaskAssessmentResults (const DescribeReplicationTaskAssessmentResultsRequest &request)
DescribeReplicationTasksResponse * describeReplicationTasks (const DescribeReplicationTasksRequest &request)
DescribeSchemasResponse * describeSchemas (const DescribeSchemasRequest &request)
DescribeTableStatisticsResponse * describeTableStatistics (const DescribeTableStatisticsRequest &request)
ImportCertificateResponse * importCertificate (const ImportCertificateRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
ModifyEndpointResponse * modifyEndpoint (const ModifyEndpointRequest &request)
ModifyEventSubscriptionResponse * modifyEventSubscription (const ModifyEventSubscriptionRequest &request)
ModifyReplicationInstanceResponse * modifyReplicationInstance (const ModifyReplicationInstanceRequest &request)
ModifyReplicationSubnetGroupResponse * modifyReplicationSubnetGroup (const ModifyReplicationSubnetGroupRequest &request)
ModifyReplicationTaskResponse * modifyReplicationTask (const ModifyReplicationTaskRequest &request)
RebootReplicationInstanceResponse * rebootReplicationInstance (const RebootReplicationInstanceRequest &request)
RefreshSchemasResponse * refreshSchemas (const RefreshSchemasRequest &request)
ReloadTablesResponse * reloadTables (const ReloadTablesRequest &request)
RemoveTagsFromResourceResponse * removeTagsFromResource (const RemoveTagsFromResourceRequest &request)
StartReplicationTaskResponse * startReplicationTask (const StartReplicationTaskRequest &request)
StartReplicationTaskAssessmentResponse * startReplicationTaskAssessment (const StartReplicationTaskAssessmentRequest &request)
StopReplicationTaskResponse * stopReplicationTask (const StopReplicationTaskRequest &request)
TestConnectionResponse * testConnection (const TestConnectionRequest &request)
Public Member Functions
DatabaseMigrationServiceClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DatabaseMigrationServiceClient object.
DatabaseMigrationServiceClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DatabaseMigrationServiceClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Database Migration Service.
<fullname>AWS Database Migration Service</fullname>
AWS Database Migration Service (AWS DMS) can migrate your data to and from the most widely used commercial and open-source databases such as Oracle, PostgreSQL, Microsoft SQL Server, Amazon Redshift, MariaDB, Amazon Aurora, MySQL, and SAP Adaptive Server Enterprise (ASE). The service supports homogeneous migrations such as Oracle to Oracle, as well as heterogeneous migrations between different database platforms, such as Oracle to MySQL or SQL Server to
PostgreSQL>
For more information about AWS DMS, see the AWS DMS user guide at What Is AWS Database Migration Service?
Definition at line 36 of file databasemigrationserviceclient.h.
Constructor & Destructor Documentation
DatabaseMigrationServiceClient() [1/2]
AWS::DatabaseMigrationService::DatabaseMigrationServiceClient::DatabaseMigrationServiceClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DatabaseMigrationServiceClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 57 of file databasemigrationserviceclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new DatabaseMigrationServiceClientPrivate(this), parent)
 {
     Q_D(DatabaseMigrationServiceClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
DatabaseMigrationServiceClient() [2/2]
AWS::DatabaseMigrationService::DatabaseMigrationServiceClient::DatabaseMigrationServiceClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DatabaseMigrationServiceClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 87 of file databasemigrationserviceclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new DatabaseMigrationServiceClientPrivate(this), parent)
 {
     Q_D(DatabaseMigrationServiceClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
dms/databasemigrationserviceclient.h
dms/databasemigrationserviceclient.cpp