libqtaws: AWS::MTurk::MTurkClient Class Reference
AWS::MTurk::MTurkClient Class Reference
Client for Amazon Mechanical Turk (MTurk)
Public Slots
AcceptQualificationRequestResponse * acceptQualificationRequest (const AcceptQualificationRequestRequest &request)
ApproveAssignmentResponse * approveAssignment (const ApproveAssignmentRequest &request)
AssociateQualificationWithWorkerResponse * associateQualificationWithWorker (const AssociateQualificationWithWorkerRequest &request)
CreateAdditionalAssignmentsForHITResponse * createAdditionalAssignmentsForHIT (const CreateAdditionalAssignmentsForHITRequest &request)
CreateHITResponse * createHIT (const CreateHITRequest &request)
CreateHITTypeResponse * createHITType (const CreateHITTypeRequest &request)
CreateHITWithHITTypeResponse * createHITWithHITType (const CreateHITWithHITTypeRequest &request)
CreateQualificationTypeResponse * createQualificationType (const CreateQualificationTypeRequest &request)
CreateWorkerBlockResponse * createWorkerBlock (const CreateWorkerBlockRequest &request)
DeleteHITResponse * deleteHIT (const DeleteHITRequest &request)
DeleteQualificationTypeResponse * deleteQualificationType (const DeleteQualificationTypeRequest &request)
DeleteWorkerBlockResponse * deleteWorkerBlock (const DeleteWorkerBlockRequest &request)
DisassociateQualificationFromWorkerResponse * disassociateQualificationFromWorker (const DisassociateQualificationFromWorkerRequest &request)
GetAccountBalanceResponse * getAccountBalance (const GetAccountBalanceRequest &request)
GetAssignmentResponse * getAssignment (const GetAssignmentRequest &request)
GetFileUploadURLResponse * getFileUploadURL (const GetFileUploadURLRequest &request)
GetHITResponse * getHIT (const GetHITRequest &request)
GetQualificationScoreResponse * getQualificationScore (const GetQualificationScoreRequest &request)
GetQualificationTypeResponse * getQualificationType (const GetQualificationTypeRequest &request)
ListAssignmentsForHITResponse * listAssignmentsForHIT (const ListAssignmentsForHITRequest &request)
ListBonusPaymentsResponse * listBonusPayments (const ListBonusPaymentsRequest &request)
ListHITsResponse * listHITs (const ListHITsRequest &request)
ListHITsForQualificationTypeResponse * listHITsForQualificationType (const ListHITsForQualificationTypeRequest &request)
ListQualificationRequestsResponse * listQualificationRequests (const ListQualificationRequestsRequest &request)
ListQualificationTypesResponse * listQualificationTypes (const ListQualificationTypesRequest &request)
ListReviewPolicyResultsForHITResponse * listReviewPolicyResultsForHIT (const ListReviewPolicyResultsForHITRequest &request)
ListReviewableHITsResponse * listReviewableHITs (const ListReviewableHITsRequest &request)
ListWorkerBlocksResponse * listWorkerBlocks (const ListWorkerBlocksRequest &request)
ListWorkersWithQualificationTypeResponse * listWorkersWithQualificationType (const ListWorkersWithQualificationTypeRequest &request)
NotifyWorkersResponse * notifyWorkers (const NotifyWorkersRequest &request)
RejectAssignmentResponse * rejectAssignment (const RejectAssignmentRequest &request)
RejectQualificationRequestResponse * rejectQualificationRequest (const RejectQualificationRequestRequest &request)
SendBonusResponse * sendBonus (const SendBonusRequest &request)
SendTestEventNotificationResponse * sendTestEventNotification (const SendTestEventNotificationRequest &request)
UpdateExpirationForHITResponse * updateExpirationForHIT (const UpdateExpirationForHITRequest &request)
UpdateHITReviewStatusResponse * updateHITReviewStatus (const UpdateHITReviewStatusRequest &request)
UpdateHITTypeOfHITResponse * updateHITTypeOfHIT (const UpdateHITTypeOfHITRequest &request)
UpdateNotificationSettingsResponse * updateNotificationSettings (const UpdateNotificationSettingsRequest &request)
UpdateQualificationTypeResponse * updateQualificationType (const UpdateQualificationTypeRequest &request)
Public Member Functions
MTurkClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MTurkClient object.
MTurkClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new MTurkClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Mechanical Turk (MTurk)
Definition at line 36 of file mturkclient.h.
Constructor & Destructor Documentation
MTurkClient() [1/2]
AWS::MTurk::MTurkClient::MTurkClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MTurkClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 46 of file mturkclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new MTurkClientPrivate(this), parent)
 {
     Q_D(MTurkClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
MTurkClient() [2/2]
AWS::MTurk::MTurkClient::MTurkClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new MTurkClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 76 of file mturkclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new MTurkClientPrivate(this), parent)
 {
     Q_D(MTurkClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
mturk-requester/mturkclient.h
mturk-requester/mturkclient.cpp