libqtaws: AwsAbstractResponse Class Reference
AwsAbstractResponse Class Reference abstract
Interface class for processing AWS responses.
Signals
void finished ()
Signal emitted when this object has finished parsing the response.
Public Member Functions
AwsAbstractResponse (QObject *const parent=0)
Constructs a new AwsAbstractResponse object.
virtual ~AwsAbstractResponse ()
AwsAbstractResponse destructor.
virtual QString errorString () const
Get this response's error string.
virtual bool hasError () const
Did any error occurr processing this reponse?
virtual bool isValid () const
Is this AWS response valid?
virtual QNetworkReply::NetworkError networkError () const
Get this response's network error, if there is one.
virtual QXmlStreamReader::Error xmlParseError () const
Get this response's XML parse error, if there is one.
virtual QString xmlParseErrorString () const
Get this response's XML parse error string, if there is one.
virtual const AwsAbstractRequest * request () const =0
Get this response's originating AWS request.
Static Public Member Functions
static QVariantMap toVariant (QXmlStreamReader &xml, const QString &prefix=QLatin1String("."), const int maxDepth=1024)
Convert an XML stream to a hierarchical QVariantMap.
Protected Slots
virtual void replyFinished ()
Slot to be invoked when the internal network reply is finished.
Protected Member Functions
AwsAbstractResponse (AwsAbstractResponsePrivate *const d, QObject *const parent)
Constructs a new AwsAbstractResponse object.
virtual bool isSuccess (QNetworkReply *const reply) const
Does a network reply indicate a successful response?
void setReply (QNetworkReply *reply)
Set the network reply from which to expect an AWS response.
void setRequest (const AwsAbstractRequest *const request)
Set this response's originating AWS request.
void setXmlError (const QXmlStreamReader &xml)
Record the details of an XML parse error.
virtual void parse (QNetworkReply *const reply)
Parse an AWS response from a network reply.
virtual void parseFailure (QIODevice &response)=0
Parse a failure response.
virtual void parseSuccess (QIODevice &response)=0
Parse a successful response.
Protected Attributes
AwsAbstractResponsePrivate *const d_ptr
Internal d-pointer.
Friends
class TestAwsAbstractResponse
Detailed Description
Interface class for processing AWS responses.
Typically instances of AwsAbstractResponse-derviced classes are returned by their respective AwsAbstractRequest-derived classes, often via an intermediate AwsAbstractClient-derived class.
For example, sending an SqsCreateQueueRequest results in a pointer to an SqsCreateQueueResponse object, optionally via an SqsClient instance.
See also
AwsAbstractRequest
AwsAbstractClient
Definition at line 33 of file awsabstractresponse.h.
Constructor & Destructor Documentation
AwsAbstractResponse() [1/2]
AwsAbstractResponse::AwsAbstractResponse (QObject *const parent = 0)
Constructs a new AwsAbstractResponse object.
Parameters
parent This object's parent.
Definition at line 51 of file awsabstractresponse.cpp.
     : QObject(parent), d_ptr(new AwsAbstractResponsePrivate(this))
 {
 }
AwsAbstractResponse() [2/2]
AwsAbstractResponse::AwsAbstractResponse (AwsAbstractResponsePrivate *const d, QObject *const parent) protected
Constructs a new AwsAbstractResponse object.
This overload allows derived classes to provide their own private class implementation that inherits from AwsAbstractRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
parent This object's parent.
Definition at line 68 of file awsabstractresponse.cpp.
     : QObject(parent), d_ptr(d)
 {
 }
Member Function Documentation
errorString()
QString AwsAbstractResponse::errorString () const virtual
Get this response's error string.
This base implementation returns either the internal network reply object's error string (if the reply object has an error), or the internal XML parse error (if one was set, eg via set setXmlError), otherwise a null QString.
Derived classes may override this function to support additional error types. Typically such derived implementations would check this base implementation's result first, or fallback to this base implementation. For example:
if (weHaveOurOwnCustomError()) {
    return customErrorString();
} else {
    return AwsAbstractResponse::errorString();
}
Returns
An error string, or a null QString if this response has no errors.
See also
hasError
networkError
xmlParseError
Reimplemented in SqsResponse.
Definition at line 109 of file awsabstractresponse.cpp.
References networkError(), xmlParseError(), and xmlParseErrorString().
Referenced by SqsResponse::errorString().
 {
     Q_D(const AwsAbstractResponse);
     if (networkError() != QNetworkReply::NoError) {
         return d->reply->errorString();
     } else if (xmlParseError() != QXmlStreamReader::NoError) {
         return xmlParseErrorString();
     } else {
         return QString();
     }
 }
finished
void AwsAbstractResponse::finished () signal
Signal emitted when this object has finished parsing the response.
Upon receiving this signal, slots should check isValid or hasError to check if the response was successful or not.
See also
hasError
isValid
Referenced by parse(), and setReply().
hasError()
bool AwsAbstractResponse::hasError () const virtual
Did any error occurr processing this reponse?
Errors could be anything from network requests errors, to errors validating AWS response content.
This base implementation supports network, and XML parsing errors. Derived classes may override this function to support additional error types.
Returns
true if this response contains one or more errors, false otherwise.
Note
This function may be equivalent to !isValid, however, it is not safe for this function's implementation to be just that, since derived classes may assume the inverse, resulting in an infinite cycle between the two functions.
See also
errorString
isValid
Reimplemented in SqsResponse.
Definition at line 141 of file awsabstractresponse.cpp.
Referenced by SqsResponse::hasError().
 {
     Q_D(const AwsAbstractResponse);
     return (((d->reply) && (d->reply->error() != QNetworkReply::NoError)) ||
             (d->xmlError != QXmlStreamReader::NoError));
 }
isSuccess()
bool AwsAbstractResponse::isSuccess (QNetworkReply *const reply) const protected virtual
Does a network reply indicate a successful response?
This base implementation simply checks that reply has no errors, and that it represents an HTTP response with a 2xx HTTP status code.
Derived classes may override this function to perform other checks, and/or to support non-HTTP responses.
This function is used by the base implementation of the parse function, to delegate responsibility to either the parseSuccess or parseFailure functions.
Parameters
reply Network reply to check for success.
Returns
true if reply indicates a successful response, false otherwise.
See also
parse
Definition at line 330 of file awsabstractresponse.cpp.
Referenced by parse().
 {
     return ((reply->error() == QNetworkReply::NoError) &&
             ((reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt() / 100) == 2));
 }
isValid()
bool AwsAbstractResponse::isValid () const virtual
Is this AWS response valid?
This base implementation simply checks for the absense of network and XML parsing errors. Derived classes may override this function to check other error types, and/or apply additional validation rules.
Returns
true if this response is considered valid, false otherwise.
Note
This function may be equivalent to !hasError, however, it is not safe for this function's implementation to be just that, since derived classes may assume the inverse, resulting in an infinite cycle between the two functions.
See also
hasError
Reimplemented in SqsResponse, SqsChangeMessageVisibilityBatchResponse, SqsCreateQueueResponse, SqsDeleteMessageBatchResponse, SqsGetQueueAttributesResponse, SqsGetQueueUrlResponse, SqsListDeadLetterSourceQueuesResponse, SqsListQueuesResponse, SqsReceiveMessageResponse, SqsSendMessageBatchResponse, and SqsSendMessageResponse.
Definition at line 164 of file awsabstractresponse.cpp.
Referenced by SqsResponse::isValid().
 {
     Q_D(const AwsAbstractResponse);
     return (((!d->reply) || (d->reply->error() == QNetworkReply::NoError)) &&
             (d->xmlError == QXmlStreamReader::NoError));
 }
networkError()
QNetworkReply::NetworkError AwsAbstractResponse::networkError () const virtual
Get this response's network error, if there is one.
Returns
This response's network error, if there is one, otherwise QNetworkReply::NoError.
See also
hasError
errorString
Definition at line 180 of file awsabstractresponse.cpp.
Referenced by errorString().
 {
     Q_D(const AwsAbstractResponse);
     return (d->reply) ? d->reply->error() : QNetworkReply::NoError;
 }
parse()
void AwsAbstractResponse::parse (QNetworkReply *const reply) protected virtual
Parse an AWS response from a network reply.
This base implementation reports networks, if any occurred, otherwise uses the result of the virtual isSuccess function to delegate parsing to either the pure virtual parseSuccess or pure virtual parseFailure methods.
Typically derived classes will only implement parseSuccess and parseFailure, without needing to override this function.
Parameters
reply Network reply from which to parse the AWS response.
See also
isSuccess
parseSuccess
parseFailure
Definition at line 404 of file awsabstractresponse.cpp.
References finished(), isSuccess(), parseFailure(), and parseSuccess().
Referenced by replyFinished().
 {
     if (reply->error() != QNetworkReply::NoError) {
         qWarning() << reply->errorString();
     } else if (isSuccess(reply)) {
         parseSuccess(*reply);
     } else {
         parseFailure(*reply);
     }
     emit finished();
 }
parseFailure()
void AwsAbstractResponse::parseFailure (QIODevice & response) protected pure virtual
Parse a failure response.
Derived classes must implement this function to process failure responses (as defined by the virtual isSuccess function).
Parameters
response Response to parse.
Referenced by parse().
parseSuccess()
void AwsAbstractResponse::parseSuccess (QIODevice & response) protected pure virtual
Parse a successful response.
Derived classes must implement this function to process successful responses (as defined by the virtual isSuccess function).
Parameters
response Response to parse.
Referenced by parse().
replyFinished
void AwsAbstractResponse::replyFinished () protected virtual slot
Slot to be invoked when the internal network reply is finished.
This slot should only be connectedd to QNetworkReply signals (specifcally, this function asserts that the signal sender is an qobject-castable to QNetworkReply).
This is convenience slot, that really exists just to abstract the sender casting logic from the parse function (ie so derived classes can override parse without having to implement explicit casts).
Definition at line 449 of file awsabstractresponse.cpp.
References parse().
Referenced by setReply().
 {
     QNetworkReply * const reply = qobject_cast<QNetworkReply *>(sender());
     Q_ASSERT(reply);
     if (reply) {
         parse(reply);
     }
 }
request()
const AwsAbstractRequest * AwsAbstractResponse::request () const pure virtual
Get this response's originating AWS request.
Returns
This response's originating AWS request.
Implemented in SqsChangeMessageVisibilityBatchResponse, SqsCreateQueueResponse, SqsDeleteMessageBatchResponse, SqsGetQueueAttributesResponse, SqsGetQueueUrlResponse, SqsListDeadLetterSourceQueuesResponse, SqsListQueuesResponse, SqsReceiveMessageResponse, SqsSendMessageBatchResponse, SqsSendMessageResponse, SqsAddPermissionResponse, SqsChangeMessageVisibilityResponse, SqsDeleteMessageResponse, SqsDeleteQueueResponse, SqsPurgeQueueResponse, SqsRemovePermissionResponse, and SqsSetQueueAttributesResponse.
Referenced by setRequest().
setReply()
void AwsAbstractResponse::setReply (QNetworkReply * reply) protected
Set the network reply from which to expect an AWS response.
Parameters
reply Network reply to an AWS requests.
Definition at line 341 of file awsabstractresponse.cpp.
References finished(), and replyFinished().
Referenced by SqsAddPermissionResponse::SqsAddPermissionResponse(), SqsChangeMessageVisibilityBatchResponse::SqsChangeMessageVisibilityBatchResponse(), SqsChangeMessageVisibilityResponse::SqsChangeMessageVisibilityResponse(), SqsCreateQueueResponse::SqsCreateQueueResponse(), SqsDeleteMessageBatchResponse::SqsDeleteMessageBatchResponse(), SqsDeleteMessageResponse::SqsDeleteMessageResponse(), SqsDeleteQueueResponse::SqsDeleteQueueResponse(), SqsGetQueueAttributesResponse::SqsGetQueueAttributesResponse(), SqsGetQueueUrlResponse::SqsGetQueueUrlResponse(), SqsListDeadLetterSourceQueuesResponse::SqsListDeadLetterSourceQueuesResponse(), SqsListQueuesResponse::SqsListQueuesResponse(), SqsPurgeQueueResponse::SqsPurgeQueueResponse(), SqsReceiveMessageResponse::SqsReceiveMessageResponse(), SqsRemovePermissionResponse::SqsRemovePermissionResponse(), SqsSendMessageBatchResponse::SqsSendMessageBatchResponse(), SqsSendMessageResponse::SqsSendMessageResponse(), and SqsSetQueueAttributesResponse::SqsSetQueueAttributesResponse().
 {
     Q_D(AwsAbstractResponse);
     connect(reply, SIGNAL(finished()), this, SLOT(replyFinished()));
     d->reply = reply;
 }
setRequest()
void AwsAbstractResponse::setRequest (const AwsAbstractRequest *const request) protected
Set this response's originating AWS request.
Note
This object will take ownership of the request pointer, and will delete request on destruction.
Callers should normally create a new request instance (making use of the request classes' copy-constructors). For example:
setRequest(new SpecializedAwsRequest(specializedRequest));
Parameters
request AWS request to set.
Definition at line 363 of file awsabstractresponse.cpp.
References request().
Referenced by SqsAddPermissionResponse::SqsAddPermissionResponse(), SqsChangeMessageVisibilityBatchResponse::SqsChangeMessageVisibilityBatchResponse(), SqsChangeMessageVisibilityResponse::SqsChangeMessageVisibilityResponse(), SqsCreateQueueResponse::SqsCreateQueueResponse(), SqsDeleteMessageBatchResponse::SqsDeleteMessageBatchResponse(), SqsDeleteMessageResponse::SqsDeleteMessageResponse(), SqsDeleteQueueResponse::SqsDeleteQueueResponse(), SqsGetQueueAttributesResponse::SqsGetQueueAttributesResponse(), SqsGetQueueUrlResponse::SqsGetQueueUrlResponse(), SqsListDeadLetterSourceQueuesResponse::SqsListDeadLetterSourceQueuesResponse(), SqsListQueuesResponse::SqsListQueuesResponse(), SqsPurgeQueueResponse::SqsPurgeQueueResponse(), SqsReceiveMessageResponse::SqsReceiveMessageResponse(), SqsRemovePermissionResponse::SqsRemovePermissionResponse(), SqsSendMessageBatchResponse::SqsSendMessageBatchResponse(), SqsSendMessageResponse::SqsSendMessageResponse(), and SqsSetQueueAttributesResponse::SqsSetQueueAttributesResponse().
 {
     Q_D(AwsAbstractResponse);
     delete d->request;
     d->request = request;
 }
setXmlError()
void AwsAbstractResponse::setXmlError (const QXmlStreamReader & xml) protected
Record the details of an XML parse error.
If xml has no error, this effectively clears any existing XML parsing error.
Parameters
xml XML reader from which to fetch an parse error code and string.
See also
xmlParseError
xmlParseErrorString
Definition at line 381 of file awsabstractresponse.cpp.
Referenced by SqsResponse::parseFailure().
 {
     Q_D(AwsAbstractResponse);
     d->xmlError = xml.error();
     d->xmlErrorString = xml.errorString();
 }
toVariant()
QVariantMap AwsAbstractResponse::toVariant (QXmlStreamReader & xml, const QString & prefix = QLatin1String("."), const int maxDepth = 1024) static
Convert an XML stream to a hierarchical QVariantMap.
Todo:
Find a better home for "QVariantMap toVariant(QXmlStreamReader &xml, ...)"
This function is used internally to embed opaque XML structures, such as the SQS service's ErrorResponse::Error::Detail, which the SQS schema defines as an arbitrary complex type.
Note
This static function exists within the AwsAbstractResponse for historic reasons. It should probably be moved our of this class, and into a more generic utility space at some point.
Parameters
xml XML stream to convert.
prefix Prefix to apply to special (non-element) child entry names.
maxDepth Maximum depth to traverse before truncating the tree.
Returns
A QVariantMap representing the xml XML fragment.
Todo:
Move this toVariant function to somewhere more generic.
Definition at line 243 of file awsabstractresponse.cpp.
Referenced by SqsErrorPrivate::parse().
 {
     if (maxDepth < 0) {
         qWarning() << QObject::tr("max depth exceeded");
         return QVariantMap();
     }
     if (xml.hasError()) {
         qWarning() << xml.errorString();
         return QVariantMap();
     }
     if (xml.tokenType() == QXmlStreamReader::NoToken)
         xml.readNext();
     if ((xml.tokenType() != QXmlStreamReader::StartDocument) &&
         (xml.tokenType() != QXmlStreamReader::StartElement)) {
         qWarning() << QObject::tr("unexpected XML tokenType %1 (%2)")
                       .arg(xml.tokenString()).arg(xml.tokenType());
         return QVariantMap();
     }
     QVariantMap map;
     if (xml.tokenType() == QXmlStreamReader::StartDocument) {
         map.insert(prefix + QLatin1String("DocumentEncoding"), xml.documentEncoding().toString());
         map.insert(prefix + QLatin1String("DocumentVersion"), xml.documentVersion().toString());
         map.insert(prefix + QLatin1String("StandaloneDocument"), xml.isStandaloneDocument());
     } else {
         if (!xml.namespaceUri().isEmpty())
             map.insert(prefix + QLatin1String("NamespaceUri"), xml.namespaceUri().toString());
         foreach (const QXmlStreamAttribute &attribute, xml.attributes()) {
             QVariantMap attributeMap;
             attributeMap.insert(QLatin1String("Value"), attribute.value().toString());
             if (!attribute.namespaceUri().isEmpty())
                 attributeMap.insert(QLatin1String("NamespaceUri"), attribute.namespaceUri().toString());
             if (!attribute.prefix().isEmpty())
                 attributeMap.insert(QLatin1String("Prefix"), attribute.prefix().toString());
             attributeMap.insert(QLatin1String("QualifiedName"), attribute.qualifiedName().toString());
             map.insertMulti(prefix + attribute.name().toString(), attributeMap);
         }
     }
     for (xml.readNext(); (!xml.atEnd()) && (xml.tokenType() != QXmlStreamReader::EndElement)
           && (xml.tokenType() != QXmlStreamReader::EndDocument); xml.readNext()) {
         switch (xml.tokenType()) {
         case QXmlStreamReader::Characters:
         case QXmlStreamReader::Comment:
         case QXmlStreamReader::DTD:
         case QXmlStreamReader::EntityReference:
             map.insertMulti(prefix + xml.tokenString(), xml.text().toString());
             break;
         case QXmlStreamReader::ProcessingInstruction:
             map.insertMulti(prefix + xml.processingInstructionTarget().toString(),
                             xml.processingInstructionData().toString());
             break;
         case QXmlStreamReader::StartElement: {
             const QString elementName = xml.name().toString();
             map.insertMulti(elementName, toVariant(xml, prefix, maxDepth-1));
             break;
         }
         default:
             qWarning() << QObject::tr("unexpected XML tokenType %1 (%2)")
                           .arg(xml.tokenString()).arg(xml.tokenType());
         }
     }
     return map;
 }
xmlParseError()
QXmlStreamReader::Error AwsAbstractResponse::xmlParseError () const virtual
Get this response's XML parse error, if there is one.
Returns
This response's XML parse error, if there is one, otherwise QXmlStreamReader::NoError.
See also
hasError
errorString
Definition at line 195 of file awsabstractresponse.cpp.
Referenced by errorString().
 {
     Q_D(const AwsAbstractResponse);
     return d->xmlError;
 }
xmlParseErrorString()
QString AwsAbstractResponse::xmlParseErrorString () const virtual
Get this response's XML parse error string, if there is one.
Returns
This response's XML parse error string, if there is one, otherwise a null QString.
See also
hasError
errorString
Definition at line 210 of file awsabstractresponse.cpp.
Referenced by errorString().
 {
     Q_D(const AwsAbstractResponse);
     return d->xmlErrorString;
 }
The documentation for this class was generated from the following files:
core/awsabstractresponse.h
core/awsabstractresponse.cpp