libqtaws: AWS::ACM::AcmClient Class Reference
AWS::ACM::AcmClient Class Reference
Client for AWS Certificate Manager (ACM)
Public Slots
AddTagsToCertificateResponse * addTagsToCertificate (const AddTagsToCertificateRequest &request)
DeleteCertificateResponse * deleteCertificate (const DeleteCertificateRequest &request)
DescribeCertificateResponse * describeCertificate (const DescribeCertificateRequest &request)
GetCertificateResponse * getCertificate (const GetCertificateRequest &request)
ImportCertificateResponse * importCertificate (const ImportCertificateRequest &request)
ListCertificatesResponse * listCertificates (const ListCertificatesRequest &request)
ListTagsForCertificateResponse * listTagsForCertificate (const ListTagsForCertificateRequest &request)
RemoveTagsFromCertificateResponse * removeTagsFromCertificate (const RemoveTagsFromCertificateRequest &request)
RequestCertificateResponse * requestCertificate (const RequestCertificateRequest &request)
ResendValidationEmailResponse * resendValidationEmail (const ResendValidationEmailRequest &request)
Public Member Functions
AcmClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AcmClient object.
AcmClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new AcmClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Certificate Manager (ACM)
<fullname>AWS Certificate Manager</fullname>
Welcome to the AWS Certificate Manager (ACM) API
documentation>
You can use ACM to manage SSL/TLS certificates for your AWS-based websites and applications. For general information about using ACM, see the AWS Certificate Manager User Guide
Definition at line 36 of file acmclient.h.
Constructor & Destructor Documentation
AcmClient() [1/2]
AWS::ACM::AcmClient::AcmClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AcmClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 55 of file acmclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new AcmClientPrivate(this), parent)
 {
     Q_D(AcmClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
AcmClient() [2/2]
AWS::ACM::AcmClient::AcmClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new AcmClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 85 of file acmclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new AcmClientPrivate(this), parent)
 {
     Q_D(AcmClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
acm/acmclient.h
acm/acmclient.cpp