libqtaws: ApplicationDiscoveryServiceClient Class Reference
ApplicationDiscoveryServiceClient Class Reference
Client for AWS Application Discovery Service.
Public Slots
ApplicationDiscoveryServiceCreateTagsResponse * createTags (const ApplicationDiscoveryServiceCreateTagsRequest &request)
ApplicationDiscoveryServiceDeleteTagsResponse * deleteTags (const ApplicationDiscoveryServiceDeleteTagsRequest &request)
ApplicationDiscoveryServiceDescribeAgentsResponse * describeAgents (const ApplicationDiscoveryServiceDescribeAgentsRequest &request)
ApplicationDiscoveryServiceDescribeConfigurationsResponse * describeConfigurations (const ApplicationDiscoveryServiceDescribeConfigurationsRequest &request)
ApplicationDiscoveryServiceDescribeExportConfigurationsResponse * describeExportConfigurations (const ApplicationDiscoveryServiceDescribeExportConfigurationsRequest &request)
ApplicationDiscoveryServiceDescribeTagsResponse * describeTags (const ApplicationDiscoveryServiceDescribeTagsRequest &request)
ApplicationDiscoveryServiceExportConfigurationsResponse * exportConfigurations ()
ApplicationDiscoveryServiceListConfigurationsResponse * listConfigurations (const ApplicationDiscoveryServiceListConfigurationsRequest &request)
ApplicationDiscoveryServiceStartDataCollectionByAgentIdsResponse * startDataCollectionByAgentIds (const ApplicationDiscoveryServiceStartDataCollectionByAgentIdsRequest &request)
ApplicationDiscoveryServiceStopDataCollectionByAgentIdsResponse * stopDataCollectionByAgentIds (const ApplicationDiscoveryServiceStopDataCollectionByAgentIdsRequest &request)
Public Member Functions
ApplicationDiscoveryServiceClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ApplicationDiscoveryServiceClient object.
ApplicationDiscoveryServiceClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ApplicationDiscoveryServiceClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Application Discovery Service.
The AWS Application Discovery Service helps Systems Integrators quickly and reliably plan application migration projects by automatically identifying applications running in on-premises data centers, their associated dependencies, and their performance profile.
Planning data center migrations can involve thousands of workloads that are often deeply interdependent. Application discovery and dependency mapping are important early first steps in the migration process, but difficult to perform at scale due to the lack of automated tools.
The AWS Application Discovery Service automatically collects configuration and usage data from servers to develop a list of applications, how they perform, and how they are interdependent. This information is securely retained in an AWS Application Discovery Service database which you can export as a CSV file into your preferred visualization tool or cloud migration solution to help reduce the complexity and time in planning your cloud migration.
The Application Discovery Service is currently available for preview. Only customers who are engaged with AWS Professional Services or a certified AWS partner can use the service. To see the list of certified partners and request access to the Application Discovery Service, complete the following preview form.
This API reference provides descriptions, syntax, and usage examples for each of the actions and data types for the Discovery Service. The topic for each action shows the API request parameters and the response. Alternatively, you can use one of the AWS SDKs to access an API that is tailored to the programming language or platform that you're using. For more information, see AWS SDKs.
This guide is intended for use with the AWS Discovery Service User Guide .
The following are short descriptions of each API action, organized by function.
Managing AWS Agents Using the Application Discovery Service
An AWS agent is software that you install on on-premises servers and virtual machines that are targeted for discovery and migration. Agents run on Linux and Windows Server and collect server configuration and activity information about your applications and infrastructure. Specifically, agents collect the following information and send it to the Application Discovery Service using Secure Sockets Layer (SSL) encryption:
User information (user name, home directory)
Group information (name)
List of installed packages
List of kernel modules
All create and stop process events
DNS queries
NIC information
TCP/UDP process listening ports
TCPV4/V6 connections
Operating system information
System performance
Process performance
The Application Discovery Service API includes the following actions to manage AWS agents:
StartDataCollectionByAgentIds: Instructs the specified agents to start collecting data. The Application Discovery Service takes several minutes to receive and process data after you initiate data collection.
StopDataCollectionByAgentIds: Instructs the specified agents to stop collecting data.
DescribeAgents: Lists AWS agents by ID or lists all agents associated with your user account if you did not specify an agent ID. The output includes agent IDs, IP addresses, media access control (MAC) addresses, agent health, host name where the agent resides, and the version number of each agent.
Querying Configuration Items
A configuration item is an IT asset that was discovered in your data center by an AWS agent. When you use the Application Discovery Service, you can specify filters and query specific configuration items. The service supports Server, Process, and Connection configuration items. This means you can specify a value for the following keys and query your IT assets:
Server
server.HostName
server.osName
server.osVersion
server.configurationId
server.agentId
Process
process.name
process.CommandLine
process.configurationId
server.hostName
server.osName
server.osVersion
server.configurationId
server.agentId
Connection
connection.sourceIp
connection.sourcePort
connection.destinationIp
connection.destinationPort
sourceProcess.configurationId
sourceProcess.commandLine
sourceProcess.name
destinationProcessId.configurationId
destinationProcess.commandLine
destinationProcess.name
sourceServer.configurationId
sourceServer.hostName
sourceServer.osName
sourceServer.osVersion
destinationServer.configurationId
destinationServer.hostName
destinationServer.osName
destinationServer.osVersion
The Application Discovery Service includes the following actions for querying configuration items.
DescribeConfigurations: Retrieves a list of attributes for a specific configuration ID. For example, the output for a server configuration item includes a list of attributes about the server, including host name, operating system, number of network cards, etc.
ListConfigurations: Retrieves a list of configuration items according to the criteria you specify in a filter. The filter criteria identify relationship requirements. For example, you can specify filter criteria of process.name with values of nginx and apache.
Tagging Discovered Configuration Items
You can tag discovered configuration items. Tags are metadata that help you categorize IT assets in your data center. Tags use a key-value format. For example, {"key": "serverType", "value": "webServer"}.
CreateTags: Creates one or more tags for a configuration items.
DescribeTags: Retrieves a list of configuration items that are tagged with a specific tag. Or, retrieves a list of all tags assigned to a specific configuration item.
DeleteTags: Deletes the association between a configuration item and one or more tags.
Exporting Data
You can export data as a CSV file to an Amazon S3 bucket or into your preferred visualization tool or cloud migration solution to help reduce the complexity and time in planning your cloud migration.
ExportConfigurations: Exports all discovered configuration data to an Amazon S3 bucket. Data includes tags and tag associations, processes, connections, servers, and system performance. This API returns an export ID which you can query using the GetExportStatus API.
DescribeExportConfigurations: Gets the status of the data export. When the export is complete, the service returns an Amazon S3 URL where you can download CSV files that include the data.
Definition at line 33 of file applicationdiscoveryserviceclient.h.
Constructor & Destructor Documentation
ApplicationDiscoveryServiceClient::ApplicationDiscoveryServiceClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ApplicationDiscoveryServiceClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 308 of file applicationdiscoveryserviceclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new ApplicationDiscoveryServiceClientPrivate(this), parent)
 {
     Q_D(ApplicationDiscoveryServiceClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
ApplicationDiscoveryServiceClient::ApplicationDiscoveryServiceClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ApplicationDiscoveryServiceClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 338 of file applicationdiscoveryserviceclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new ApplicationDiscoveryServiceClientPrivate(this), parent)
 {
     Q_D(ApplicationDiscoveryServiceClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
discovery/applicationdiscoveryserviceclient.h
discovery/applicationdiscoveryserviceclient.cpp