libqtaws: AWS::ElastiCache::ElastiCacheClient Class Reference
AWS::ElastiCache::ElastiCacheClient Class Reference
Client for Amazon ElastiCache.
Public Slots
AddTagsToResourceResponse * addTagsToResource (const AddTagsToResourceRequest &request)
AuthorizeCacheSecurityGroupIngressResponse * authorizeCacheSecurityGroupIngress (const AuthorizeCacheSecurityGroupIngressRequest &request)
CopySnapshotResponse * copySnapshot (const CopySnapshotRequest &request)
CreateCacheClusterResponse * createCacheCluster (const CreateCacheClusterRequest &request)
CreateCacheParameterGroupResponse * createCacheParameterGroup (const CreateCacheParameterGroupRequest &request)
CreateCacheSecurityGroupResponse * createCacheSecurityGroup (const CreateCacheSecurityGroupRequest &request)
CreateCacheSubnetGroupResponse * createCacheSubnetGroup (const CreateCacheSubnetGroupRequest &request)
CreateReplicationGroupResponse * createReplicationGroup (const CreateReplicationGroupRequest &request)
CreateSnapshotResponse * createSnapshot (const CreateSnapshotRequest &request)
DeleteCacheClusterResponse * deleteCacheCluster (const DeleteCacheClusterRequest &request)
DeleteCacheParameterGroupResponse * deleteCacheParameterGroup (const DeleteCacheParameterGroupRequest &request)
DeleteCacheSecurityGroupResponse * deleteCacheSecurityGroup (const DeleteCacheSecurityGroupRequest &request)
DeleteCacheSubnetGroupResponse * deleteCacheSubnetGroup (const DeleteCacheSubnetGroupRequest &request)
DeleteReplicationGroupResponse * deleteReplicationGroup (const DeleteReplicationGroupRequest &request)
DeleteSnapshotResponse * deleteSnapshot (const DeleteSnapshotRequest &request)
DescribeCacheClustersResponse * describeCacheClusters (const DescribeCacheClustersRequest &request)
DescribeCacheEngineVersionsResponse * describeCacheEngineVersions (const DescribeCacheEngineVersionsRequest &request)
DescribeCacheParameterGroupsResponse * describeCacheParameterGroups (const DescribeCacheParameterGroupsRequest &request)
DescribeCacheParametersResponse * describeCacheParameters (const DescribeCacheParametersRequest &request)
DescribeCacheSecurityGroupsResponse * describeCacheSecurityGroups (const DescribeCacheSecurityGroupsRequest &request)
DescribeCacheSubnetGroupsResponse * describeCacheSubnetGroups (const DescribeCacheSubnetGroupsRequest &request)
DescribeEngineDefaultParametersResponse * describeEngineDefaultParameters (const DescribeEngineDefaultParametersRequest &request)
DescribeEventsResponse * describeEvents (const DescribeEventsRequest &request)
DescribeReplicationGroupsResponse * describeReplicationGroups (const DescribeReplicationGroupsRequest &request)
DescribeReservedCacheNodesResponse * describeReservedCacheNodes (const DescribeReservedCacheNodesRequest &request)
DescribeReservedCacheNodesOfferingsResponse * describeReservedCacheNodesOfferings (const DescribeReservedCacheNodesOfferingsRequest &request)
DescribeSnapshotsResponse * describeSnapshots (const DescribeSnapshotsRequest &request)
ListAllowedNodeTypeModificationsResponse * listAllowedNodeTypeModifications (const ListAllowedNodeTypeModificationsRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
ModifyCacheClusterResponse * modifyCacheCluster (const ModifyCacheClusterRequest &request)
ModifyCacheParameterGroupResponse * modifyCacheParameterGroup (const ModifyCacheParameterGroupRequest &request)
ModifyCacheSubnetGroupResponse * modifyCacheSubnetGroup (const ModifyCacheSubnetGroupRequest &request)
ModifyReplicationGroupResponse * modifyReplicationGroup (const ModifyReplicationGroupRequest &request)
ModifyReplicationGroupShardConfigurationResponse * modifyReplicationGroupShardConfiguration (const ModifyReplicationGroupShardConfigurationRequest &request)
PurchaseReservedCacheNodesOfferingResponse * purchaseReservedCacheNodesOffering (const PurchaseReservedCacheNodesOfferingRequest &request)
RebootCacheClusterResponse * rebootCacheCluster (const RebootCacheClusterRequest &request)
RemoveTagsFromResourceResponse * removeTagsFromResource (const RemoveTagsFromResourceRequest &request)
ResetCacheParameterGroupResponse * resetCacheParameterGroup (const ResetCacheParameterGroupRequest &request)
RevokeCacheSecurityGroupIngressResponse * revokeCacheSecurityGroupIngress (const RevokeCacheSecurityGroupIngressRequest &request)
TestFailoverResponse * testFailover (const TestFailoverRequest &request)
Public Member Functions
ElastiCacheClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElastiCacheClient object.
ElastiCacheClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElastiCacheClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon ElastiCache.
<fullname>Amazon ElastiCache</fullname>
Amazon ElastiCache is a web service that makes it easier to set up, operate, and scale a distributed cache in the
cloud>
With ElastiCache, customers get all of the benefits of a high-performance, in-memory cache with less of the administrative burden involved in launching and managing a distributed cache. The service makes setup, scaling, and cluster failure handling much simpler than in a self-managed cache
deployment>
In addition, through integration with Amazon CloudWatch, customers get enhanced visibility into the key performance statistics associated with their cache and can receive alarms if a part of their cache runs
Definition at line 36 of file elasticacheclient.h.
Constructor & Destructor Documentation
ElastiCacheClient() [1/2]
AWS::ElastiCache::ElastiCacheClient::ElastiCacheClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElastiCacheClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 60 of file elasticacheclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new ElastiCacheClientPrivate(this), parent)
 {
     Q_D(ElastiCacheClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
ElastiCacheClient() [2/2]
AWS::ElastiCache::ElastiCacheClient::ElastiCacheClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElastiCacheClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 90 of file elasticacheclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new ElastiCacheClientPrivate(this), parent)
 {
     Q_D(ElastiCacheClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
elasticache/elasticacheclient.h
elasticache/elasticacheclient.cpp