libqtaws: AWS::SageMaker::SageMakerClient Class Reference
AWS::SageMaker::SageMakerClient Class Reference
Client for Amazon SageMaker Service.
Public Slots
AddTagsResponse * addTags (const AddTagsRequest &request)
CreateEndpointResponse * createEndpoint (const CreateEndpointRequest &request)
CreateEndpointConfigResponse * createEndpointConfig (const CreateEndpointConfigRequest &request)
CreateModelResponse * createModel (const CreateModelRequest &request)
CreateNotebookInstanceResponse * createNotebookInstance (const CreateNotebookInstanceRequest &request)
CreateNotebookInstanceLifecycleConfigResponse * createNotebookInstanceLifecycleConfig (const CreateNotebookInstanceLifecycleConfigRequest &request)
CreatePresignedNotebookInstanceUrlResponse * createPresignedNotebookInstanceUrl (const CreatePresignedNotebookInstanceUrlRequest &request)
CreateTrainingJobResponse * createTrainingJob (const CreateTrainingJobRequest &request)
DeleteEndpointResponse * deleteEndpoint (const DeleteEndpointRequest &request)
DeleteEndpointConfigResponse * deleteEndpointConfig (const DeleteEndpointConfigRequest &request)
DeleteModelResponse * deleteModel (const DeleteModelRequest &request)
DeleteNotebookInstanceResponse * deleteNotebookInstance (const DeleteNotebookInstanceRequest &request)
DeleteNotebookInstanceLifecycleConfigResponse * deleteNotebookInstanceLifecycleConfig (const DeleteNotebookInstanceLifecycleConfigRequest &request)
DeleteTagsResponse * deleteTags (const DeleteTagsRequest &request)
DescribeEndpointResponse * describeEndpoint (const DescribeEndpointRequest &request)
DescribeEndpointConfigResponse * describeEndpointConfig (const DescribeEndpointConfigRequest &request)
DescribeModelResponse * describeModel (const DescribeModelRequest &request)
DescribeNotebookInstanceResponse * describeNotebookInstance (const DescribeNotebookInstanceRequest &request)
DescribeNotebookInstanceLifecycleConfigResponse * describeNotebookInstanceLifecycleConfig (const DescribeNotebookInstanceLifecycleConfigRequest &request)
DescribeTrainingJobResponse * describeTrainingJob (const DescribeTrainingJobRequest &request)
ListEndpointConfigsResponse * listEndpointConfigs (const ListEndpointConfigsRequest &request)
ListEndpointsResponse * listEndpoints (const ListEndpointsRequest &request)
ListModelsResponse * listModels (const ListModelsRequest &request)
ListNotebookInstanceLifecycleConfigsResponse * listNotebookInstanceLifecycleConfigs (const ListNotebookInstanceLifecycleConfigsRequest &request)
ListNotebookInstancesResponse * listNotebookInstances (const ListNotebookInstancesRequest &request)
ListTagsResponse * listTags (const ListTagsRequest &request)
ListTrainingJobsResponse * listTrainingJobs (const ListTrainingJobsRequest &request)
StartNotebookInstanceResponse * startNotebookInstance (const StartNotebookInstanceRequest &request)
StopNotebookInstanceResponse * stopNotebookInstance (const StopNotebookInstanceRequest &request)
StopTrainingJobResponse * stopTrainingJob (const StopTrainingJobRequest &request)
UpdateEndpointResponse * updateEndpoint (const UpdateEndpointRequest &request)
UpdateEndpointWeightsAndCapacitiesResponse * updateEndpointWeightsAndCapacities (const UpdateEndpointWeightsAndCapacitiesRequest &request)
UpdateNotebookInstanceResponse * updateNotebookInstance (const UpdateNotebookInstanceRequest &request)
UpdateNotebookInstanceLifecycleConfigResponse * updateNotebookInstanceLifecycleConfig (const UpdateNotebookInstanceLifecycleConfigRequest &request)
Public Member Functions
SageMakerClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SageMakerClient object.
SageMakerClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SageMakerClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon SageMaker Service.
Definition at line 36 of file sagemakerclient.h.
Constructor & Destructor Documentation
SageMakerClient() [1/2]
AWS::SageMaker::SageMakerClient::SageMakerClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SageMakerClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 46 of file sagemakerclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new SageMakerClientPrivate(this), parent)
 {
     Q_D(SageMakerClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
SageMakerClient() [2/2]
AWS::SageMaker::SageMakerClient::SageMakerClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SageMakerClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 76 of file sagemakerclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new SageMakerClientPrivate(this), parent)
 {
     Q_D(SageMakerClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
sagemaker/sagemakerclient.h
sagemaker/sagemakerclient.cpp