libqtaws: WorkSpacesClient Class Reference
WorkSpacesClient Class Reference
Client for Amazon WorkSpaces.
Public Slots
WorkSpacesCreateTagsResponse * createTags (const WorkSpacesCreateTagsRequest &request)
WorkSpacesCreateWorkspacesResponse * createWorkspaces (const WorkSpacesCreateWorkspacesRequest &request)
WorkSpacesDeleteTagsResponse * deleteTags (const WorkSpacesDeleteTagsRequest &request)
WorkSpacesDescribeTagsResponse * describeTags (const WorkSpacesDescribeTagsRequest &request)
WorkSpacesDescribeWorkspaceBundlesResponse * describeWorkspaceBundles (const WorkSpacesDescribeWorkspaceBundlesRequest &request)
WorkSpacesDescribeWorkspaceDirectoriesResponse * describeWorkspaceDirectories (const WorkSpacesDescribeWorkspaceDirectoriesRequest &request)
WorkSpacesDescribeWorkspacesResponse * describeWorkspaces (const WorkSpacesDescribeWorkspacesRequest &request)
WorkSpacesDescribeWorkspacesConnectionStatusResponse * describeWorkspacesConnectionStatus (const WorkSpacesDescribeWorkspacesConnectionStatusRequest &request)
WorkSpacesModifyWorkspacePropertiesResponse * modifyWorkspaceProperties (const WorkSpacesModifyWorkspacePropertiesRequest &request)
WorkSpacesRebootWorkspacesResponse * rebootWorkspaces (const WorkSpacesRebootWorkspacesRequest &request)
WorkSpacesRebuildWorkspacesResponse * rebuildWorkspaces (const WorkSpacesRebuildWorkspacesRequest &request)
WorkSpacesStartWorkspacesResponse * startWorkspaces (const WorkSpacesStartWorkspacesRequest &request)
WorkSpacesStopWorkspacesResponse * stopWorkspaces (const WorkSpacesStopWorkspacesRequest &request)
WorkSpacesTerminateWorkspacesResponse * terminateWorkspaces (const WorkSpacesTerminateWorkspacesRequest &request)
Public Member Functions
WorkSpacesClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WorkSpacesClient object.
WorkSpacesClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new WorkSpacesClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon WorkSpaces.
<fullname>Amazon WorkSpaces Service</fullname>
This reference provides detailed information about the Amazon WorkSpaces operations.
Definition at line 33 of file workspacesclient.h.
Constructor & Destructor Documentation
WorkSpacesClient::WorkSpacesClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WorkSpacesClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 48 of file workspacesclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new WorkSpacesClientPrivate(this), parent)
 {
     Q_D(WorkSpacesClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
WorkSpacesClient::WorkSpacesClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new WorkSpacesClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 78 of file workspacesclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new WorkSpacesClientPrivate(this), parent)
 {
     Q_D(WorkSpacesClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
workspaces/workspacesclient.h
workspaces/workspacesclient.cpp