libqtaws: AWS::StorageGateway::StorageGatewayClient Class Reference
AWS::StorageGateway::StorageGatewayClient Class Reference
Client for AWS Storage Gateway.
Public Slots
ActivateGatewayResponse * activateGateway (const ActivateGatewayRequest &request)
AddCacheResponse * addCache (const AddCacheRequest &request)
AddTagsToResourceResponse * addTagsToResource (const AddTagsToResourceRequest &request)
AddUploadBufferResponse * addUploadBuffer (const AddUploadBufferRequest &request)
AddWorkingStorageResponse * addWorkingStorage (const AddWorkingStorageRequest &request)
CancelArchivalResponse * cancelArchival (const CancelArchivalRequest &request)
CancelRetrievalResponse * cancelRetrieval (const CancelRetrievalRequest &request)
CreateCachediSCSIVolumeResponse * createCachediSCSIVolume (const CreateCachediSCSIVolumeRequest &request)
CreateNFSFileShareResponse * createNFSFileShare (const CreateNFSFileShareRequest &request)
CreateSnapshotResponse * createSnapshot (const CreateSnapshotRequest &request)
CreateSnapshotFromVolumeRecoveryPointResponse * createSnapshotFromVolumeRecoveryPoint (const CreateSnapshotFromVolumeRecoveryPointRequest &request)
CreateStorediSCSIVolumeResponse * createStorediSCSIVolume (const CreateStorediSCSIVolumeRequest &request)
CreateTapeWithBarcodeResponse * createTapeWithBarcode (const CreateTapeWithBarcodeRequest &request)
CreateTapesResponse * createTapes (const CreateTapesRequest &request)
DeleteBandwidthRateLimitResponse * deleteBandwidthRateLimit (const DeleteBandwidthRateLimitRequest &request)
DeleteChapCredentialsResponse * deleteChapCredentials (const DeleteChapCredentialsRequest &request)
DeleteFileShareResponse * deleteFileShare (const DeleteFileShareRequest &request)
DeleteGatewayResponse * deleteGateway (const DeleteGatewayRequest &request)
DeleteSnapshotScheduleResponse * deleteSnapshotSchedule (const DeleteSnapshotScheduleRequest &request)
DeleteTapeResponse * deleteTape (const DeleteTapeRequest &request)
DeleteTapeArchiveResponse * deleteTapeArchive (const DeleteTapeArchiveRequest &request)
DeleteVolumeResponse * deleteVolume (const DeleteVolumeRequest &request)
DescribeBandwidthRateLimitResponse * describeBandwidthRateLimit (const DescribeBandwidthRateLimitRequest &request)
DescribeCacheResponse * describeCache (const DescribeCacheRequest &request)
DescribeCachediSCSIVolumesResponse * describeCachediSCSIVolumes (const DescribeCachediSCSIVolumesRequest &request)
DescribeChapCredentialsResponse * describeChapCredentials (const DescribeChapCredentialsRequest &request)
DescribeGatewayInformationResponse * describeGatewayInformation (const DescribeGatewayInformationRequest &request)
DescribeMaintenanceStartTimeResponse * describeMaintenanceStartTime (const DescribeMaintenanceStartTimeRequest &request)
DescribeNFSFileSharesResponse * describeNFSFileShares (const DescribeNFSFileSharesRequest &request)
DescribeSnapshotScheduleResponse * describeSnapshotSchedule (const DescribeSnapshotScheduleRequest &request)
DescribeStorediSCSIVolumesResponse * describeStorediSCSIVolumes (const DescribeStorediSCSIVolumesRequest &request)
DescribeTapeArchivesResponse * describeTapeArchives (const DescribeTapeArchivesRequest &request)
DescribeTapeRecoveryPointsResponse * describeTapeRecoveryPoints (const DescribeTapeRecoveryPointsRequest &request)
DescribeTapesResponse * describeTapes (const DescribeTapesRequest &request)
DescribeUploadBufferResponse * describeUploadBuffer (const DescribeUploadBufferRequest &request)
DescribeVTLDevicesResponse * describeVTLDevices (const DescribeVTLDevicesRequest &request)
DescribeWorkingStorageResponse * describeWorkingStorage (const DescribeWorkingStorageRequest &request)
DisableGatewayResponse * disableGateway (const DisableGatewayRequest &request)
ListFileSharesResponse * listFileShares (const ListFileSharesRequest &request)
ListGatewaysResponse * listGateways (const ListGatewaysRequest &request)
ListLocalDisksResponse * listLocalDisks (const ListLocalDisksRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
ListTapesResponse * listTapes (const ListTapesRequest &request)
ListVolumeInitiatorsResponse * listVolumeInitiators (const ListVolumeInitiatorsRequest &request)
ListVolumeRecoveryPointsResponse * listVolumeRecoveryPoints (const ListVolumeRecoveryPointsRequest &request)
ListVolumesResponse * listVolumes (const ListVolumesRequest &request)
NotifyWhenUploadedResponse * notifyWhenUploaded (const NotifyWhenUploadedRequest &request)
RefreshCacheResponse * refreshCache (const RefreshCacheRequest &request)
RemoveTagsFromResourceResponse * removeTagsFromResource (const RemoveTagsFromResourceRequest &request)
ResetCacheResponse * resetCache (const ResetCacheRequest &request)
RetrieveTapeArchiveResponse * retrieveTapeArchive (const RetrieveTapeArchiveRequest &request)
RetrieveTapeRecoveryPointResponse * retrieveTapeRecoveryPoint (const RetrieveTapeRecoveryPointRequest &request)
SetLocalConsolePasswordResponse * setLocalConsolePassword (const SetLocalConsolePasswordRequest &request)
ShutdownGatewayResponse * shutdownGateway (const ShutdownGatewayRequest &request)
StartGatewayResponse * startGateway (const StartGatewayRequest &request)
UpdateBandwidthRateLimitResponse * updateBandwidthRateLimit (const UpdateBandwidthRateLimitRequest &request)
UpdateChapCredentialsResponse * updateChapCredentials (const UpdateChapCredentialsRequest &request)
UpdateGatewayInformationResponse * updateGatewayInformation (const UpdateGatewayInformationRequest &request)
UpdateGatewaySoftwareNowResponse * updateGatewaySoftwareNow (const UpdateGatewaySoftwareNowRequest &request)
UpdateMaintenanceStartTimeResponse * updateMaintenanceStartTime (const UpdateMaintenanceStartTimeRequest &request)
UpdateNFSFileShareResponse * updateNFSFileShare (const UpdateNFSFileShareRequest &request)
UpdateSnapshotScheduleResponse * updateSnapshotSchedule (const UpdateSnapshotScheduleRequest &request)
UpdateVTLDeviceTypeResponse * updateVTLDeviceType (const UpdateVTLDeviceTypeRequest &request)
Public Member Functions
StorageGatewayClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new StorageGatewayClient object.
StorageGatewayClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new StorageGatewayClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Storage Gateway.
<fullname>AWS Storage Gateway Service</fullname>
AWS Storage Gateway is the service that connects an on-premises software appliance with cloud-based storage to provide seamless and secure integration between an organization's on-premises IT environment and AWS's storage infrastructure. The service enables you to securely upload data to the AWS cloud for cost effective backup and rapid disaster
recovery>
Use the following links to get started using the AWS Storage Gateway Service API
Reference>
AWS Storage Gateway Required Request Headers: Describes the required headers that you must send with every POST request to AWS Storage
Gateway>
Signing Requests: AWS Storage Gateway requires that you authenticate every request you send; this topic describes how sign such a
request>
Error Responses: Provides reference information about AWS Storage Gateway
errors>
Operations in AWS Storage Gateway: Contains detailed descriptions of all AWS Storage Gateway operations, their request parameters, response elements, possible errors, and examples of requests and
responses>
AWS Storage Gateway Regions and Endpoints: Provides a list of each region and endpoints available for use with AWS Storage Gateway.
</p
<note>
AWS Storage Gateway resource IDs are in uppercase. When you use these resource IDs with the Amazon EC2 API, EC2 expects resource IDs in lowercase. You must change your resource ID to lowercase to use it with the EC2 API. For example, in Storage Gateway the ID for a volume might be vol-AA22BB012345DAF670. When you use this ID with the EC2 API, you must change it to vol-aa22bb012345daf670. Otherwise, the EC2 API might not behave as
expected> </note> <important>
IDs for Storage Gateway volumes and Amazon EBS snapshots created from gateway volumes are changing to a longer format. Starting in December 2016, all new volumes and snapshots will be created with a 17-character string. Starting in April 2016, you will be able to use these longer IDs so you can test your systems with the new format. For more information, see Longer EC2 and EBS Resource IDs>
For example, a volume Amazon Resource Name (ARN) with the longer volume ID format looks like the
following>
arn:aws:storagegateway:us-west-2:111122223333:gateway/sgw-12A3456B/volume/vol-1122AABBCCDDEEFFG>
A snapshot ID with the longer ID format looks like the following:
snap-78e226633445566ee>
For more information, see Announcement: Heads-up Longer AWS Storage Gateway volume and snapshot IDs coming in
Definition at line 36 of file storagegatewayclient.h.
Constructor & Destructor Documentation
StorageGatewayClient() [1/2]
AWS::StorageGateway::StorageGatewayClient::StorageGatewayClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new StorageGatewayClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 115 of file storagegatewayclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new StorageGatewayClientPrivate(this), parent)
 {
     Q_D(StorageGatewayClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
StorageGatewayClient() [2/2]
AWS::StorageGateway::StorageGatewayClient::StorageGatewayClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new StorageGatewayClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 145 of file storagegatewayclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new StorageGatewayClientPrivate(this), parent)
 {
     Q_D(StorageGatewayClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
storagegateway/storagegatewayclient.h
storagegateway/storagegatewayclient.cpp