libqtaws: AWS::Comprehend::ComprehendClient Class Reference
AWS::Comprehend::ComprehendClient Class Reference
Client for Amazon Comprehend.
Public Slots
BatchDetectDominantLanguageResponse * batchDetectDominantLanguage (const BatchDetectDominantLanguageRequest &request)
BatchDetectEntitiesResponse * batchDetectEntities (const BatchDetectEntitiesRequest &request)
BatchDetectKeyPhrasesResponse * batchDetectKeyPhrases (const BatchDetectKeyPhrasesRequest &request)
BatchDetectSentimentResponse * batchDetectSentiment (const BatchDetectSentimentRequest &request)
DescribeTopicsDetectionJobResponse * describeTopicsDetectionJob (const DescribeTopicsDetectionJobRequest &request)
DetectDominantLanguageResponse * detectDominantLanguage (const DetectDominantLanguageRequest &request)
DetectEntitiesResponse * detectEntities (const DetectEntitiesRequest &request)
DetectKeyPhrasesResponse * detectKeyPhrases (const DetectKeyPhrasesRequest &request)
DetectSentimentResponse * detectSentiment (const DetectSentimentRequest &request)
ListTopicsDetectionJobsResponse * listTopicsDetectionJobs (const ListTopicsDetectionJobsRequest &request)
StartTopicsDetectionJobResponse * startTopicsDetectionJob (const StartTopicsDetectionJobRequest &request)
Public Member Functions
ComprehendClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ComprehendClient object.
ComprehendClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ComprehendClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Comprehend.
Amazon Comprehend is an AWS service for gaining insight into the content of documents. Use these actions to determine the topics contained in your documents, the topics they discuss, the predominant sentiment expressed in them, the predominant language used, and
Definition at line 36 of file comprehendclient.h.
Constructor & Destructor Documentation
ComprehendClient() [1/2]
AWS::Comprehend::ComprehendClient::ComprehendClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ComprehendClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 49 of file comprehendclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new ComprehendClientPrivate(this), parent)
 {
     Q_D(ComprehendClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
ComprehendClient() [2/2]
AWS::Comprehend::ComprehendClient::ComprehendClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ComprehendClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 79 of file comprehendclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new ComprehendClientPrivate(this), parent)
 {
     Q_D(ComprehendClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
comprehend/comprehendclient.h
comprehend/comprehendclient.cpp