libqtaws: AWS::ResourceGroups::ResourceGroupsClient Class Reference
AWS::ResourceGroups::ResourceGroupsClient Class Reference
Client for AWS Resource Groups.
Public Slots
CreateGroupResponse * createGroup (const CreateGroupRequest &request)
DeleteGroupResponse * deleteGroup (const DeleteGroupRequest &request)
GetGroupResponse * getGroup (const GetGroupRequest &request)
GetGroupQueryResponse * getGroupQuery (const GetGroupQueryRequest &request)
GetTagsResponse * getTags (const GetTagsRequest &request)
ListGroupResourcesResponse * listGroupResources (const ListGroupResourcesRequest &request)
ListGroupsResponse * listGroups (const ListGroupsRequest &request)
SearchResourcesResponse * searchResources (const SearchResourcesRequest &request)
TagResponse * tag (const TagRequest &request)
UntagResponse * untag (const UntagRequest &request)
UpdateGroupResponse * updateGroup (const UpdateGroupRequest &request)
UpdateGroupQueryResponse * updateGroupQuery (const UpdateGroupQueryRequest &request)
Public Member Functions
ResourceGroupsClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ResourceGroupsClient object.
ResourceGroupsClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ResourceGroupsClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Resource Groups.
<fullname>AWS Resource Groups</fullname>
AWS Resource Groups lets you organize AWS resources such as Amazon EC2 instances, Amazon Relational Database Service databases, and Amazon S3 buckets into groups using criteria that you define as tags. A resource group is a collection of resources that match the resource types specified in a query, and share one or more tags or portions of tags. You can create a group of resources based on their roles in your cloud infrastructure, lifecycle stages, regions, application layers, or virtually any criteria. Resource groups enable you to automate management tasks, such as those in AWS Systems Manager Automation documents, on tag-related resources in AWS Systems Manager. Groups of tagged resources also let you quickly view a custom console in AWS Systems Manager that shows AWS Config compliance and other monitoring data about member
resources>
To create a resource group, build a resource query, and specify tags that identify the criteria that members of the group have in common. Tags are key-value
pairs>
For more information about Resource Groups, see the AWS Resource Groups User Guide>
AWS Resource Groups uses a REST-compliant API that you can use to perform the following types of
operations>
Create, Read, Update, and Delete (CRUD) operations on resource groups and resource query
entitie>
Applying, editing, and removing tags from resource
group>
Resolving resource group member ARNs so they can be returned as search
result>
Getting data about resources that are members of a
grou>
Searching AWS resources based on a resource
Definition at line 36 of file resourcegroupsclient.h.
Constructor & Destructor Documentation
ResourceGroupsClient() [1/2]
AWS::ResourceGroups::ResourceGroupsClient::ResourceGroupsClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ResourceGroupsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 90 of file resourcegroupsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new ResourceGroupsClientPrivate(this), parent)
 {
     Q_D(ResourceGroupsClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
ResourceGroupsClient() [2/2]
AWS::ResourceGroups::ResourceGroupsClient::ResourceGroupsClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ResourceGroupsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 120 of file resourcegroupsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new ResourceGroupsClientPrivate(this), parent)
 {
     Q_D(ResourceGroupsClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
resource-groups/resourcegroupsclient.h
resource-groups/resourcegroupsclient.cpp