libqtaws: DynamoDBStreamsClient Class Reference
DynamoDBStreamsClient Class Reference
Client for Amazon DynamoDB Streams.
Public Slots
DynamoDBStreamsDescribeStreamResponse * describeStream (const DynamoDBStreamsDescribeStreamRequest &request)
DynamoDBStreamsGetRecordsResponse * getRecords (const DynamoDBStreamsGetRecordsRequest &request)
DynamoDBStreamsGetShardIteratorResponse * getShardIterator (const DynamoDBStreamsGetShardIteratorRequest &request)
DynamoDBStreamsListStreamsResponse * listStreams (const DynamoDBStreamsListStreamsRequest &request)
Public Member Functions
DynamoDBStreamsClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DynamoDBStreamsClient object.
DynamoDBStreamsClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DynamoDBStreamsClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon DynamoDB Streams.
<fullname>Amazon DynamoDB Streams</fullname>
This is the Amazon DynamoDB Streams API Reference. This guide describes the low-level API actions for accessing streams and processing stream records. For information about application development with DynamoDB Streams, see the Amazon DynamoDB Developer Guide.
Note that this document is intended for use with the following DynamoDB documentation:
Amazon DynamoDB Developer Guide
Amazon DynamoDB API Reference
The following are short descriptions of each low-level DynamoDB Streams API action, organized by function.
DescribeStream - Returns detailed information about a particular stream.
GetRecords - Retrieves the stream records from within a shard.
GetShardIterator - Returns information on how to retrieve the streams record from a shard with a given shard ID.
ListStreams - Returns a list of all the streams associated with the current AWS account and endpoint.
Definition at line 33 of file dynamodbstreamsclient.h.
Constructor & Destructor Documentation
DynamoDBStreamsClient::DynamoDBStreamsClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DynamoDBStreamsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 80 of file dynamodbstreamsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new DynamoDBStreamsClientPrivate(this), parent)
 {
     Q_D(DynamoDBStreamsClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
DynamoDBStreamsClient::DynamoDBStreamsClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DynamoDBStreamsClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 110 of file dynamodbstreamsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new DynamoDBStreamsClientPrivate(this), parent)
 {
     Q_D(DynamoDBStreamsClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
dynamodbstreams/dynamodbstreamsclient.h
dynamodbstreams/dynamodbstreamsclient.cpp