libqtaws: SqsClient Class Reference
SqsClient Class Reference
Client for Amazon's Simple Queue Service (SQS)
Public Slots
SqsAddPermissionResponse * addPermission (const SqsAddPermissionRequest &request)
Add permissions to an SQS queue.
SqsChangeMessageVisibilityResponse * changeMessageVisibility (const SqsChangeMessageVisibilityRequest &request)
Change the visibility timeout of a received SQS message.
SqsChangeMessageVisibilityResponse * changeMessageVisibility (const QString &queueUrl, const QString &receiptHandle, const int visbilityTimeout)
Change the visibility timeout of a received SQS message.
SqsCreateQueueResponse * createQueue (const SqsCreateQueueRequest &request)
Create an SQS queue.
SqsCreateQueueResponse * createQueue (const QString &queueName, const QVariantMap &attributes=QVariantMap())
Create an SQS queue.
SqsDeleteMessageResponse * deleteMessage (const SqsDeleteMessageRequest &request)
Deletes the specified message from the specified queue.
SqsDeleteMessageResponse * deleteMessage (const QString &queueUrl, const QString &receiptHandle)
Deletes the specified message from the specified queue.
SqsDeleteQueueResponse * deleteQueue (const SqsDeleteQueueRequest &request)
Deletes the queue specified by the queue URL.
SqsDeleteQueueResponse * deleteQueue (const QString &queueUrl)
Deletes the queue specified by the queue URL.
SqsGetQueueUrlResponse * getQueueUrl (const SqsGetQueueUrlRequest &request)
Gets the URL of an existing queue.
SqsGetQueueUrlResponse * getQueueUrl (const QString &queueName, const QString &queueOwnerAWSAccountId=QString())
Gets the URL of an existing queue.
SqsListDeadLetterSourceQueuesResponse * listDeadLetterSourceQueues (const SqsListDeadLetterSourceQueuesRequest &request)
Get a list of queues that have the RedrivePolicy queue attribute configured with a dead letter queue.
SqsListDeadLetterSourceQueuesResponse * listDeadLetterSourceQueues (const QString &queueUrl)
Get a list of queues that have the RedrivePolicy queue attribute configured with a dead letter queue.
SqsListQueuesResponse * listQueues (const SqsListQueuesRequest &request)
Get a list of queues belonging to the authorized account.
SqsListQueuesResponse * listQueues (const QString &queueNamePrefix=QString())
Get a list of queues belonging to the authorized account.
SqsPurgeQueueResponse * purgeQueue (const SqsPurgeQueueRequest &request)
Deletes the messages in a queue specified by the queue URL.
SqsPurgeQueueResponse * purgeQueue (const QString &queueUrl)
Deletes the messages in a queue specified by the queue URL.
SqsRemovePermissionResponse * removePermission (const SqsRemovePermissionRequest &request)
Revokes any permissions in the queue policy that matches the specified label.
SqsRemovePermissionResponse * removePermission (const QString &queueUrl, const QString &label)
Revokes any permissions in the queue policy that matches the specified label.
Public Member Functions
SqsClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SqsClient object.
SqsClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SqsClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Friends
class TestSqsClient
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon's Simple Queue Service (SQS)
See also
http://aws.amazon.com/sqs/
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/
http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl
Definition at line 60 of file sqsclient.h.
Constructor & Destructor Documentation
SqsClient::SqsClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SqsClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 84 of file sqsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
     : AwsAbstractClient(new SqsClientPrivate(this), parent)
 {
     Q_D(SqsClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = SQS_SERVICE_NAME;
 }
SqsClient::SqsClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SqsClient object.
This overload allows the caller to specify the specific SQS endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct SQS endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint SQS endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 113 of file sqsclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
     : AwsAbstractClient(new SqsClientPrivate(this), parent)
 {
     Q_D(SqsClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = SQS_SERVICE_NAME;
 }
Member Function Documentation
SqsAddPermissionResponse * SqsClient::addPermission (const SqsAddPermissionRequest & request) slot
Add permissions to an SQS queue.
Parameters
request Request to send to SQS.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 135 of file sqsclient.cpp.
References AwsAbstractClient::send().
 {
     return qobject_cast<SqsAddPermissionResponse *>(send(request));
 }
SqsChangeMessageVisibilityResponse * SqsClient::changeMessageVisibility (const SqsChangeMessageVisibilityRequest & request) slot
Change the visibility timeout of a received SQS message.
Parameters
request Request to send to SQS.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 149 of file sqsclient.cpp.
References AwsAbstractClient::send().
Referenced by changeMessageVisibility().
 {
     return qobject_cast<SqsChangeMessageVisibilityResponse *>(send(request));
 }
SqsChangeMessageVisibilityResponse * SqsClient::changeMessageVisibility (const QString & queueUrl, const QString & receiptHandle, const int visbilityTimeout) slot
Change the visibility timeout of a received SQS message.
Parameters
queueUrl URL of the queue receiptHandle relates to.
receiptHandle Handle for the message to set the timeout for.
visbilityTimeout New value (in seconds) for the message's visibility timeout.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 166 of file sqsclient.cpp.
References changeMessageVisibility().
 {
     const SqsChangeMessageVisibilityRequest request(
         queueUrl, receiptHandle, visbilityTimeout);
     return changeMessageVisibility(request);
 }
SqsCreateQueueResponse * SqsClient::createQueue (const SqsCreateQueueRequest & request) slot
Create an SQS queue.
Parameters
request Request to send to SQS.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 184 of file sqsclient.cpp.
References AwsAbstractClient::send().
Referenced by createQueue().
 {
     return qobject_cast<SqsCreateQueueResponse *>(send(request));
 }
SqsCreateQueueResponse * SqsClient::createQueue (const QString & queueName, const QVariantMap & attributes = QVariantMap()) slot
Create an SQS queue.
This convenience overload simply allows callers to skip creating the required SqsCreateQueueRequest object.
Parameters
queueName Name of the queue to create.
attributes Optional attributes to include with the request. See the SqsCreateQueueRequest documentation for valid attributes.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
See also
SqsCreateQueueRequest
Definition at line 205 of file sqsclient.cpp.
References createQueue(), and SqsCreateQueueRequest::setAttributes().
 {
     SqsCreateQueueRequest request(queueName);
     request.setAttributes(attributes);
     return createQueue(request);
 }
SqsDeleteMessageResponse * SqsClient::deleteMessage (const SqsDeleteMessageRequest & request) slot
Deletes the specified message from the specified queue.
Parameters
request Request to send to SQS.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 222 of file sqsclient.cpp.
References AwsAbstractClient::send().
Referenced by deleteMessage().
 {
     return qobject_cast<SqsDeleteMessageResponse *>(send(request));
 }
SqsDeleteMessageResponse * SqsClient::deleteMessage (const QString & queueUrl, const QString & receiptHandle) slot
Deletes the specified message from the specified queue.
Parameters
queueUrl URL of the Amazon SQS queue to take action on.
receiptHandle Receipt handle associated with the message to delete.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
See also
SqsDeleteMessageRequest
Definition at line 240 of file sqsclient.cpp.
References deleteMessage().
 {
     const SqsDeleteMessageRequest request(queueUrl, receiptHandle);
     return deleteMessage(request);
 }
SqsDeleteQueueResponse * SqsClient::deleteQueue (const SqsDeleteQueueRequest & request) slot
Deletes the queue specified by the queue URL.
Parameters
request Request to send to SQS.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
See also
SqsDeleteQueueRequest
Definition at line 258 of file sqsclient.cpp.
References AwsAbstractClient::send().
Referenced by deleteQueue().
 {
     return qobject_cast<SqsDeleteQueueResponse *>(send(request));
 }
SqsDeleteQueueResponse * SqsClient::deleteQueue (const QString & queueUrl) slot
Deletes the queue specified by the queue URL.
Parameters
queueUrl URL of the Amazon SQS queue to take action on.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
See also
SqsDeleteQueueRequest
Definition at line 274 of file sqsclient.cpp.
References deleteQueue().
 {
     const SqsDeleteQueueRequest request(queueUrl);
     return deleteQueue(request);
 }
SqsGetQueueUrlResponse * SqsClient::getQueueUrl (const SqsGetQueueUrlRequest & request) slot
Gets the URL of an existing queue.
Parameters
request Request to send to SQS.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 289 of file sqsclient.cpp.
References AwsAbstractClient::send().
Referenced by getQueueUrl().
 {
     return qobject_cast<SqsGetQueueUrlResponse *>(send(request));
 }
SqsGetQueueUrlResponse * SqsClient::getQueueUrl (const QString & queueName, const QString & queueOwnerAWSAccountId = QString()) slot
Gets the URL of an existing queue.
Parameters
queueName Name of the queue whose URL must be fetched.
queueOwnerAWSAccountId The AWS account ID of the account that created the queue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
See also
SqsGetQueueUrlRequest
Definition at line 306 of file sqsclient.cpp.
References getQueueUrl().
 {
     const SqsGetQueueUrlRequest request(queueName, queueOwnerAWSAccountId);
     return getQueueUrl(request);
 }
SqsListDeadLetterSourceQueuesResponse * SqsClient::listDeadLetterSourceQueues (const SqsListDeadLetterSourceQueuesRequest & request) slot
Get a list of queues that have the RedrivePolicy queue attribute configured with a dead letter queue.
Parameters
request Request to send to SQS.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 323 of file sqsclient.cpp.
References AwsAbstractClient::send().
Referenced by listDeadLetterSourceQueues().
 {
     return qobject_cast<SqsListDeadLetterSourceQueuesResponse *>(send(request));
 }
SqsListDeadLetterSourceQueuesResponse * SqsClient::listDeadLetterSourceQueues (const QString & queueUrl) slot
Get a list of queues that have the RedrivePolicy queue attribute configured with a dead letter queue.
Parameters
queueUrl URL of a dead letter queue.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
See also
SqsListDeadLetterSourceQueuesRequest
Definition at line 341 of file sqsclient.cpp.
References listDeadLetterSourceQueues().
 {
     const SqsListDeadLetterSourceQueuesRequest request(queueUrl);
     return listDeadLetterSourceQueues(request);
 }
SqsListQueuesResponse * SqsClient::listQueues (const SqsListQueuesRequest & request) slot
Get a list of queues belonging to the authorized account.
Parameters
request Request to send to SQS.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 357 of file sqsclient.cpp.
References AwsAbstractClient::send().
Referenced by listQueues().
 {
     return qobject_cast<SqsListQueuesResponse *>(send(request));
 }
SqsListQueuesResponse * SqsClient::listQueues (const QString & queueNamePrefix = QString()) slot
Get a list of queues belonging to the authorized account.
Parameters
queueNamePrefix String to use for filtering the list results.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
See also
SqsListQueuesRequest
Definition at line 373 of file sqsclient.cpp.
References listQueues().
 {
     const SqsListQueuesRequest request(queueNamePrefix);
     return listQueues(request);
 }
SqsPurgeQueueResponse * SqsClient::purgeQueue (const SqsPurgeQueueRequest & request) slot
Deletes the messages in a queue specified by the queue URL.
Parameters
request Request to send to SQS.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 388 of file sqsclient.cpp.
References AwsAbstractClient::send().
Referenced by purgeQueue().
 {
     return qobject_cast<SqsPurgeQueueResponse *>(send(request));
 }
SqsPurgeQueueResponse * SqsClient::purgeQueue (const QString & queueUrl) slot
Deletes the messages in a queue specified by the queue URL.
Parameters
queueUrl URL of the Amazon SQS queue to take action on.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
See also
SqsPurgeQueueResponse
Definition at line 404 of file sqsclient.cpp.
References purgeQueue().
 {
     const SqsPurgeQueueRequest request(queueUrl);
     return purgeQueue(request);
 }
SqsRemovePermissionResponse * SqsClient::removePermission (const SqsRemovePermissionRequest & request) slot
Revokes any permissions in the queue policy that matches the specified label.
Parameters
request Request to send to SQS.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
Definition at line 420 of file sqsclient.cpp.
References AwsAbstractClient::send().
Referenced by removePermission().
 {
     return qobject_cast<SqsRemovePermissionResponse *>(send(request));
 }
SqsRemovePermissionResponse * SqsClient::removePermission (const QString & queueUrl, const QString & label) slot
Revokes any permissions in the queue policy that matches the specified label.
Parameters
queueUrl URL of the Amazon SQS queue to take action on.
label Identification of the permission to remove.
Returns
A pointer to a related response object.
Note
The caller is to take responsbility for the resulting pointer.
See also
SqsRemovePermissionRequest
Definition at line 439 of file sqsclient.cpp.
References removePermission().
 {
     const SqsRemovePermissionRequest request(queueUrl, label);
     return removePermission(request);
 }
The documentation for this class was generated from the following files:
sqs/sqsclient.h
sqs/sqsclient.cpp