libqtaws: DeviceFarmClient Class Reference
DeviceFarmClient Class Reference
Client for AWS Device Farm.
Public Slots
DeviceFarmCreateDevicePoolResponse * createDevicePool (const DeviceFarmCreateDevicePoolRequest &request)
DeviceFarmCreateProjectResponse * createProject (const DeviceFarmCreateProjectRequest &request)
DeviceFarmCreateRemoteAccessSessionResponse * createRemoteAccessSession (const DeviceFarmCreateRemoteAccessSessionRequest &request)
DeviceFarmCreateUploadResponse * createUpload (const DeviceFarmCreateUploadRequest &request)
DeviceFarmDeleteDevicePoolResponse * deleteDevicePool (const DeviceFarmDeleteDevicePoolRequest &request)
DeviceFarmDeleteProjectResponse * deleteProject (const DeviceFarmDeleteProjectRequest &request)
DeviceFarmDeleteRemoteAccessSessionResponse * deleteRemoteAccessSession (const DeviceFarmDeleteRemoteAccessSessionRequest &request)
DeviceFarmDeleteRunResponse * deleteRun (const DeviceFarmDeleteRunRequest &request)
DeviceFarmDeleteUploadResponse * deleteUpload (const DeviceFarmDeleteUploadRequest &request)
DeviceFarmGetAccountSettingsResponse * getAccountSettings (const DeviceFarmGetAccountSettingsRequest &request)
DeviceFarmGetDeviceResponse * getDevice (const DeviceFarmGetDeviceRequest &request)
DeviceFarmGetDevicePoolResponse * getDevicePool (const DeviceFarmGetDevicePoolRequest &request)
DeviceFarmGetDevicePoolCompatibilityResponse * getDevicePoolCompatibility (const DeviceFarmGetDevicePoolCompatibilityRequest &request)
DeviceFarmGetJobResponse * getJob (const DeviceFarmGetJobRequest &request)
DeviceFarmGetOfferingStatusResponse * getOfferingStatus (const DeviceFarmGetOfferingStatusRequest &request)
DeviceFarmGetProjectResponse * getProject (const DeviceFarmGetProjectRequest &request)
DeviceFarmGetRemoteAccessSessionResponse * getRemoteAccessSession (const DeviceFarmGetRemoteAccessSessionRequest &request)
DeviceFarmGetRunResponse * getRun (const DeviceFarmGetRunRequest &request)
DeviceFarmGetSuiteResponse * getSuite (const DeviceFarmGetSuiteRequest &request)
DeviceFarmGetTestResponse * getTest (const DeviceFarmGetTestRequest &request)
DeviceFarmGetUploadResponse * getUpload (const DeviceFarmGetUploadRequest &request)
DeviceFarmInstallToRemoteAccessSessionResponse * installToRemoteAccessSession (const DeviceFarmInstallToRemoteAccessSessionRequest &request)
DeviceFarmListArtifactsResponse * listArtifacts (const DeviceFarmListArtifactsRequest &request)
DeviceFarmListDevicePoolsResponse * listDevicePools (const DeviceFarmListDevicePoolsRequest &request)
DeviceFarmListDevicesResponse * listDevices (const DeviceFarmListDevicesRequest &request)
DeviceFarmListJobsResponse * listJobs (const DeviceFarmListJobsRequest &request)
DeviceFarmListOfferingTransactionsResponse * listOfferingTransactions (const DeviceFarmListOfferingTransactionsRequest &request)
DeviceFarmListOfferingsResponse * listOfferings (const DeviceFarmListOfferingsRequest &request)
DeviceFarmListProjectsResponse * listProjects (const DeviceFarmListProjectsRequest &request)
DeviceFarmListRemoteAccessSessionsResponse * listRemoteAccessSessions (const DeviceFarmListRemoteAccessSessionsRequest &request)
DeviceFarmListRunsResponse * listRuns (const DeviceFarmListRunsRequest &request)
DeviceFarmListSamplesResponse * listSamples (const DeviceFarmListSamplesRequest &request)
DeviceFarmListSuitesResponse * listSuites (const DeviceFarmListSuitesRequest &request)
DeviceFarmListTestsResponse * listTests (const DeviceFarmListTestsRequest &request)
DeviceFarmListUniqueProblemsResponse * listUniqueProblems (const DeviceFarmListUniqueProblemsRequest &request)
DeviceFarmListUploadsResponse * listUploads (const DeviceFarmListUploadsRequest &request)
DeviceFarmPurchaseOfferingResponse * purchaseOffering (const DeviceFarmPurchaseOfferingRequest &request)
DeviceFarmRenewOfferingResponse * renewOffering (const DeviceFarmRenewOfferingRequest &request)
DeviceFarmScheduleRunResponse * scheduleRun (const DeviceFarmScheduleRunRequest &request)
DeviceFarmStopRemoteAccessSessionResponse * stopRemoteAccessSession (const DeviceFarmStopRemoteAccessSessionRequest &request)
DeviceFarmStopRunResponse * stopRun (const DeviceFarmStopRunRequest &request)
DeviceFarmUpdateDevicePoolResponse * updateDevicePool (const DeviceFarmUpdateDevicePoolRequest &request)
DeviceFarmUpdateProjectResponse * updateProject (const DeviceFarmUpdateProjectRequest &request)
Public Member Functions
DeviceFarmClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DeviceFarmClient object.
DeviceFarmClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new DeviceFarmClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Device Farm.
AWS Device Farm is a service that enables mobile app developers to test Android, iOS, and Fire OS apps on physical phones, tablets, and other devices in the cloud.
Definition at line 33 of file devicefarmclient.h.
Constructor & Destructor Documentation
DeviceFarmClient::DeviceFarmClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DeviceFarmClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 46 of file devicefarmclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new DeviceFarmClientPrivate(this), parent)
 {
     Q_D(DeviceFarmClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
DeviceFarmClient::DeviceFarmClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new DeviceFarmClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 76 of file devicefarmclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new DeviceFarmClientPrivate(this), parent)
 {
     Q_D(DeviceFarmClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
devicefarm/devicefarmclient.h
devicefarm/devicefarmclient.cpp