libqtaws: AwsAbstractSignaturePrivate Class Reference
AwsAbstractSignaturePrivate Class Reference
Private implementation for AwsAbstractSignature.
Public Member Functions
virtual ~AwsAbstractSignaturePrivate ()
AwsAbstractSignaturePrivate destructor.
AwsAbstractSignaturePrivate (AwsAbstractSignature *const q)
Constructs a new AwsAbstractSignaturePrivate object.
QString canonicalPath (const QUrl &url) const
Create an AWS Signature canonical path.
QByteArray canonicalQuery (const QUrlQuery &query) const
Create an AWS Signature canonical query.
QString httpMethod (const QNetworkAccessManager::Operation operation) const
Create an AWS Signature request method string.
bool setQueryItem (QUrlQuery &query, const QString &key, const QString &value, const bool warnOnNonIdenticalDuplicate=true) const
Set a query item, checking for existing values first.
Protected Attributes
AwsAbstractSignature *const q_ptr
Internal q-pointer.
Friends
class TestAwsAbstractSignature
Detailed Description
Private implementation for AwsAbstractSignature.
Warning
This is an internal private implementation class, and as such external should code should not depend directly on anything contained within this class.
Definition at line 32 of file awsabstractsignature_p.h.
Constructor & Destructor Documentation
AwsAbstractSignaturePrivate::~AwsAbstractSignaturePrivate () virtual
AwsAbstractSignaturePrivate destructor.
This virtual destructor does nothing (yet) - its here to allow for safe polymorphic destruction.
Definition at line 116 of file awsabstractsignature.cpp.
 {
 }
AwsAbstractSignaturePrivate::AwsAbstractSignaturePrivate (AwsAbstractSignature *const q)
Constructs a new AwsAbstractSignaturePrivate object.
Parameters
q Pointer to this object's public AwsAbstractSignature instance.
Definition at line 103 of file awsabstractsignature.cpp.
                                                                                        : q_ptr(q)
 {
 }
Member Function Documentation
QString AwsAbstractSignaturePrivate::canonicalPath (const QUrl & url) const
Create an AWS Signature canonical path.
This function simply returns the fully-URL-encoded path. However, if the path is empty, then a single '/' is returned, as is required by Amazon for both V2 and V4 signatures (and presumably other versions too).
Parameters
url URL from which to extract the path.
Returns
An AWS Signature canonical path.
See also
http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html
http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html
Definition at line 135 of file awsabstractsignature.cpp.
Referenced by AwsSignatureV2Private::canonicalRequest(), AwsSignatureV3Private::canonicalRequest(), and AwsSignatureV4Private::canonicalRequest().
 {
     QString path = QDir::cleanPath(QLatin1Char('/') + url.path(QUrl::FullyEncoded));
     // If the path begins with "//", remove one of the redundant slashes.
     // Note, this is only needed on Windows, because there QDir::speparator is
     // '\', and internally QDir::cleanPath swaps all separators to '/', before
     // calling qt_normalizePathSegments with allowUncPaths set to true, so that
     // '//' is preserved to allow of Windows UNC paths beginning with '\\'.
     // This should probably be reported as a bug in Qt::cleanPath("//...").
 #ifdef Q_OS_WIN
     if (path.startsWith(QLatin1String("//"))) {
         path.remove(0, 1); // Remove the first of two forward slashes.
     }
 #endif
     // Restore the trailing '/' if QDir::cleanPath (rightly) removed one.
     if ((url.path().endsWith(QLatin1Char('/'))) && (!path.endsWith(QLatin1Char('/')))) {
         path += QLatin1Char('/');
     }
     return path;
 }
QByteArray AwsAbstractSignaturePrivate::canonicalQuery (const QUrlQuery & query) const
Create an AWS Signature canonical query.
This function returns an HTTP query string in Amazon's canonical form. That is, all query parameters are sorted by keys (but not keys-then-values), then joined with & separators, in key=value pairs with both keys and values being URL percent encoded.
Note
The canonical form produced by this function is used by Amazon's later signature formats (versions 2, 3 and 4), but not their earlier formats (versions 0 and 1).
Parameters
query Query to encode the HTTP query string from.
Returns
An AWS Signature canonical query string.
See also
http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html
http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html
Definition at line 178 of file awsabstractsignature.cpp.
Referenced by AwsSignatureV2Private::canonicalRequest(), AwsSignatureV3Private::canonicalRequest(), and AwsSignatureV4Private::canonicalRequest().
 {
     typedef QPair<QString, QString> QStringPair;
     QList<QStringPair> list = query.queryItems(QUrl::FullyDecoded);
     qSort(list);
     QString result;
     foreach (const QStringPair &pair, list) {
         if (!result.isEmpty()) result += QLatin1Char('&');
         result += QString::fromUtf8(QUrl::toPercentEncoding(pair.first)) + QLatin1Char('=') +
                   QString::fromUtf8(QUrl::toPercentEncoding(pair.second));
     }
     return result.toUtf8();
 }
QString AwsAbstractSignaturePrivate::httpMethod (const QNetworkAccessManager::Operation operation) const
Create an AWS Signature request method string.
This function simply converts QNetworkAccessManager operations (enum values) to strings appropriate to use in AWS signatures.
Parameters
operation The network operation to convert to string.
Returns
A string representation of operation, or an empty string if the operation is not recognised or otherwise unsupported.
Definition at line 203 of file awsabstractsignature.cpp.
Referenced by AwsSignatureV2Private::canonicalRequest(), AwsSignatureV3Private::canonicalRequest(), and AwsSignatureV4Private::canonicalRequest().
 {
     switch (operation) {
         case QNetworkAccessManager::DeleteOperation: return QLatin1String("DELETE");
         case QNetworkAccessManager::HeadOperation:   return QLatin1String("HEAD");
         case QNetworkAccessManager::GetOperation:    return QLatin1String("GET");
         case QNetworkAccessManager::PostOperation:   return QLatin1String("POST");
         case QNetworkAccessManager::PutOperation:    return QLatin1String("PUT");
         case QNetworkAccessManager::CustomOperation: // Fall through.
         default:
             // Catch this in debug mode for easier development / debugging.
             Q_ASSERT_X(false, Q_FUNC_INFO, "invalid operation");
     }
     return QString(); // Operation was invalid / unsupported.
 }
bool AwsAbstractSignaturePrivate::setQueryItem (QUrlQuery & query, const QString & key, const QString & value, const bool warnOnNonIdenticalDuplicate = true) const
Set a query item, checking for existing values first.
This function is a light wrapper around QUrlQuery::addQueryItem() that first checks for existing values. Existing values will not be overwritten, instead if existing values are found, this function will simply check if the exsting value matches the desired value, and if not, will return false and optionally (according to warnOnNonIdenticalDuplicate) issue a qWarning().
Typically, when setting something that must be a specific value, such as an access key ID, warnOnNonIdenticalDuplicate would be true. However, when setting query items as a fall-back default, such as a current timestamp, warnOnNonIdenticalDuplicate would typically be set to false.
Parameters
query URL query to add the query item to.
key Query item key to add to query.
value Query item value to add to query.
warnOnNonIdenticalDuplicate If true, and an exisiting key value is found in query that has a value other than value, then a qWarning() is issued, otherwise the duplicate is silently ignored.
Returns
true if the query item was set successfully or was already set to the requested value previously, false otherwise.
Definition at line 244 of file awsabstractsignature.cpp.
Referenced by AwsSignatureV0Private::adornRequest(), and AwsSignatureV2Private::adornRequest().
 {
     if (query.hasQueryItem(key)) {
         const QString existingValue = query.queryItemValue(key, QUrl::FullyEncoded);
         const bool existingQueryItemIsIdentical = (existingValue == value);
         if ((warnOnNonIdenticalDuplicate) && (!existingQueryItemIsIdentical)) {
             qWarning() << "AwsAbstractSignature::setQueryItem Not overwriting existing value for key"
                        << key << ':' << existingValue;
         }
         return existingQueryItemIsIdentical;
     }
     query.addQueryItem(key, value);
     return true;
 }
The documentation for this class was generated from the following files:
core/awsabstractsignature_p.h
core/awsabstractsignature.cpp