libqtaws: OpsWorksClient Class Reference
OpsWorksClient Class Reference
Client for AWS OpsWorks.
Public Slots
OpsWorksAssignInstanceResponse * assignInstance (const OpsWorksAssignInstanceRequest &request)
OpsWorksAssignVolumeResponse * assignVolume (const OpsWorksAssignVolumeRequest &request)
OpsWorksAssociateElasticIpResponse * associateElasticIp (const OpsWorksAssociateElasticIpRequest &request)
OpsWorksAttachElasticLoadBalancerResponse * attachElasticLoadBalancer (const OpsWorksAttachElasticLoadBalancerRequest &request)
OpsWorksCloneStackResponse * cloneStack (const OpsWorksCloneStackRequest &request)
OpsWorksCreateAppResponse * createApp (const OpsWorksCreateAppRequest &request)
OpsWorksCreateDeploymentResponse * createDeployment (const OpsWorksCreateDeploymentRequest &request)
OpsWorksCreateInstanceResponse * createInstance (const OpsWorksCreateInstanceRequest &request)
OpsWorksCreateLayerResponse * createLayer (const OpsWorksCreateLayerRequest &request)
OpsWorksCreateStackResponse * createStack (const OpsWorksCreateStackRequest &request)
OpsWorksCreateUserProfileResponse * createUserProfile (const OpsWorksCreateUserProfileRequest &request)
OpsWorksDeleteAppResponse * deleteApp (const OpsWorksDeleteAppRequest &request)
OpsWorksDeleteInstanceResponse * deleteInstance (const OpsWorksDeleteInstanceRequest &request)
OpsWorksDeleteLayerResponse * deleteLayer (const OpsWorksDeleteLayerRequest &request)
OpsWorksDeleteStackResponse * deleteStack (const OpsWorksDeleteStackRequest &request)
OpsWorksDeleteUserProfileResponse * deleteUserProfile (const OpsWorksDeleteUserProfileRequest &request)
OpsWorksDeregisterEcsClusterResponse * deregisterEcsCluster (const OpsWorksDeregisterEcsClusterRequest &request)
OpsWorksDeregisterElasticIpResponse * deregisterElasticIp (const OpsWorksDeregisterElasticIpRequest &request)
OpsWorksDeregisterInstanceResponse * deregisterInstance (const OpsWorksDeregisterInstanceRequest &request)
OpsWorksDeregisterRdsDbInstanceResponse * deregisterRdsDbInstance (const OpsWorksDeregisterRdsDbInstanceRequest &request)
OpsWorksDeregisterVolumeResponse * deregisterVolume (const OpsWorksDeregisterVolumeRequest &request)
OpsWorksDescribeAgentVersionsResponse * describeAgentVersions (const OpsWorksDescribeAgentVersionsRequest &request)
OpsWorksDescribeAppsResponse * describeApps (const OpsWorksDescribeAppsRequest &request)
OpsWorksDescribeCommandsResponse * describeCommands (const OpsWorksDescribeCommandsRequest &request)
OpsWorksDescribeDeploymentsResponse * describeDeployments (const OpsWorksDescribeDeploymentsRequest &request)
OpsWorksDescribeEcsClustersResponse * describeEcsClusters (const OpsWorksDescribeEcsClustersRequest &request)
OpsWorksDescribeElasticIpsResponse * describeElasticIps (const OpsWorksDescribeElasticIpsRequest &request)
OpsWorksDescribeElasticLoadBalancersResponse * describeElasticLoadBalancers (const OpsWorksDescribeElasticLoadBalancersRequest &request)
OpsWorksDescribeInstancesResponse * describeInstances (const OpsWorksDescribeInstancesRequest &request)
OpsWorksDescribeLayersResponse * describeLayers (const OpsWorksDescribeLayersRequest &request)
OpsWorksDescribeLoadBasedAutoScalingResponse * describeLoadBasedAutoScaling (const OpsWorksDescribeLoadBasedAutoScalingRequest &request)
OpsWorksDescribeMyUserProfileResponse * describeMyUserProfile ()
OpsWorksDescribePermissionsResponse * describePermissions (const OpsWorksDescribePermissionsRequest &request)
OpsWorksDescribeRaidArraysResponse * describeRaidArrays (const OpsWorksDescribeRaidArraysRequest &request)
OpsWorksDescribeRdsDbInstancesResponse * describeRdsDbInstances (const OpsWorksDescribeRdsDbInstancesRequest &request)
OpsWorksDescribeServiceErrorsResponse * describeServiceErrors (const OpsWorksDescribeServiceErrorsRequest &request)
OpsWorksDescribeStackProvisioningParametersResponse * describeStackProvisioningParameters (const OpsWorksDescribeStackProvisioningParametersRequest &request)
OpsWorksDescribeStackSummaryResponse * describeStackSummary (const OpsWorksDescribeStackSummaryRequest &request)
OpsWorksDescribeStacksResponse * describeStacks (const OpsWorksDescribeStacksRequest &request)
OpsWorksDescribeTimeBasedAutoScalingResponse * describeTimeBasedAutoScaling (const OpsWorksDescribeTimeBasedAutoScalingRequest &request)
OpsWorksDescribeUserProfilesResponse * describeUserProfiles (const OpsWorksDescribeUserProfilesRequest &request)
OpsWorksDescribeVolumesResponse * describeVolumes (const OpsWorksDescribeVolumesRequest &request)
OpsWorksDetachElasticLoadBalancerResponse * detachElasticLoadBalancer (const OpsWorksDetachElasticLoadBalancerRequest &request)
OpsWorksDisassociateElasticIpResponse * disassociateElasticIp (const OpsWorksDisassociateElasticIpRequest &request)
OpsWorksGetHostnameSuggestionResponse * getHostnameSuggestion (const OpsWorksGetHostnameSuggestionRequest &request)
OpsWorksGrantAccessResponse * grantAccess (const OpsWorksGrantAccessRequest &request)
OpsWorksRebootInstanceResponse * rebootInstance (const OpsWorksRebootInstanceRequest &request)
OpsWorksRegisterEcsClusterResponse * registerEcsCluster (const OpsWorksRegisterEcsClusterRequest &request)
OpsWorksRegisterElasticIpResponse * registerElasticIp (const OpsWorksRegisterElasticIpRequest &request)
OpsWorksRegisterInstanceResponse * registerInstance (const OpsWorksRegisterInstanceRequest &request)
OpsWorksRegisterRdsDbInstanceResponse * registerRdsDbInstance (const OpsWorksRegisterRdsDbInstanceRequest &request)
OpsWorksRegisterVolumeResponse * registerVolume (const OpsWorksRegisterVolumeRequest &request)
OpsWorksSetLoadBasedAutoScalingResponse * setLoadBasedAutoScaling (const OpsWorksSetLoadBasedAutoScalingRequest &request)
OpsWorksSetPermissionResponse * setPermission (const OpsWorksSetPermissionRequest &request)
OpsWorksSetTimeBasedAutoScalingResponse * setTimeBasedAutoScaling (const OpsWorksSetTimeBasedAutoScalingRequest &request)
OpsWorksStartInstanceResponse * startInstance (const OpsWorksStartInstanceRequest &request)
OpsWorksStartStackResponse * startStack (const OpsWorksStartStackRequest &request)
OpsWorksStopInstanceResponse * stopInstance (const OpsWorksStopInstanceRequest &request)
OpsWorksStopStackResponse * stopStack (const OpsWorksStopStackRequest &request)
OpsWorksUnassignInstanceResponse * unassignInstance (const OpsWorksUnassignInstanceRequest &request)
OpsWorksUnassignVolumeResponse * unassignVolume (const OpsWorksUnassignVolumeRequest &request)
OpsWorksUpdateAppResponse * updateApp (const OpsWorksUpdateAppRequest &request)
OpsWorksUpdateElasticIpResponse * updateElasticIp (const OpsWorksUpdateElasticIpRequest &request)
OpsWorksUpdateInstanceResponse * updateInstance (const OpsWorksUpdateInstanceRequest &request)
OpsWorksUpdateLayerResponse * updateLayer (const OpsWorksUpdateLayerRequest &request)
OpsWorksUpdateMyUserProfileResponse * updateMyUserProfile (const OpsWorksUpdateMyUserProfileRequest &request)
OpsWorksUpdateRdsDbInstanceResponse * updateRdsDbInstance (const OpsWorksUpdateRdsDbInstanceRequest &request)
OpsWorksUpdateStackResponse * updateStack (const OpsWorksUpdateStackRequest &request)
OpsWorksUpdateUserProfileResponse * updateUserProfile (const OpsWorksUpdateUserProfileRequest &request)
OpsWorksUpdateVolumeResponse * updateVolume (const OpsWorksUpdateVolumeRequest &request)
Public Member Functions
OpsWorksClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new OpsWorksClient object.
OpsWorksClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new OpsWorksClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS OpsWorks.
<fullname>AWS OpsWorks</fullname>
Welcome to the AWS OpsWorks API Reference. This guide provides descriptions, syntax, and usage examples for AWS OpsWorks actions and data types, including common parameters and error codes.
AWS OpsWorks is an application management service that provides an integrated experience for overseeing the complete application lifecycle. For information about this product, go to the AWS OpsWorks details page.
SDKs and CLI
The most common way to use the AWS OpsWorks API is by using the AWS Command Line Interface (CLI) or by using one of the AWS SDKs to implement applications in your preferred language. For more information, see:
AWS CLI
AWS SDK for Java
AWS SDK for .NET
AWS SDK for PHP 2
AWS SDK for Ruby
AWS SDK for Node.js
AWS SDK for Python(Boto)
Endpoints
AWS OpsWorks supports the following endpoints, all HTTPS. You must connect to one of the following endpoints. Stacks can only be accessed or managed within the endpoint in which they are created.
opsworks.us-east-1.amazonaws.com
opsworks.us-west-1.amazonaws.com
opsworks.us-west-2.amazonaws.com
opsworks.eu-west-1.amazonaws.com
opsworks.eu-central-1.amazonaws.com
opsworks.ap-northeast-1.amazonaws.com
opsworks.ap-northeast-2.amazonaws.com
opsworks.ap-south-1.amazonaws.com
opsworks.ap-southeast-1.amazonaws.com
opsworks.ap-southeast-2.amazonaws.com
opsworks.sa-east-1.amazonaws.com
Chef Versions
When you call CreateStack, CloneStack, or UpdateStack we recommend you use the ConfigurationManager parameter to specify the Chef version. The recommended and default value for Linux stacks is currently 12. Windows stacks use Chef 12.2. For more information, see Chef Versions.
<note>
You can specify Chef 12, 11.10, or 11.4 for your Linux stack. We recommend migrating your existing Linux stacks to Chef 12 as soon as possible.
</note>
Definition at line 33 of file opsworksclient.h.
Constructor & Destructor Documentation
OpsWorksClient::OpsWorksClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new OpsWorksClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 144 of file opsworksclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new OpsWorksClientPrivate(this), parent)
 {
     Q_D(OpsWorksClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
OpsWorksClient::OpsWorksClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new OpsWorksClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 174 of file opsworksclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new OpsWorksClientPrivate(this), parent)
 {
     Q_D(OpsWorksClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
opsworks/opsworksclient.h
opsworks/opsworksclient.cpp