libqtaws: AWS::SFN::SfnClient Class Reference
AWS::SFN::SfnClient Class Reference
Client for AWS Step Functions (SFN)
Public Slots
CreateActivityResponse * createActivity (const CreateActivityRequest &request)
CreateStateMachineResponse * createStateMachine (const CreateStateMachineRequest &request)
DeleteActivityResponse * deleteActivity (const DeleteActivityRequest &request)
DeleteStateMachineResponse * deleteStateMachine (const DeleteStateMachineRequest &request)
DescribeActivityResponse * describeActivity (const DescribeActivityRequest &request)
DescribeExecutionResponse * describeExecution (const DescribeExecutionRequest &request)
DescribeStateMachineResponse * describeStateMachine (const DescribeStateMachineRequest &request)
DescribeStateMachineForExecutionResponse * describeStateMachineForExecution (const DescribeStateMachineForExecutionRequest &request)
GetActivityTaskResponse * getActivityTask (const GetActivityTaskRequest &request)
GetExecutionHistoryResponse * getExecutionHistory (const GetExecutionHistoryRequest &request)
ListActivitiesResponse * listActivities (const ListActivitiesRequest &request)
ListExecutionsResponse * listExecutions (const ListExecutionsRequest &request)
ListStateMachinesResponse * listStateMachines (const ListStateMachinesRequest &request)
SendTaskFailureResponse * sendTaskFailure (const SendTaskFailureRequest &request)
SendTaskHeartbeatResponse * sendTaskHeartbeat (const SendTaskHeartbeatRequest &request)
SendTaskSuccessResponse * sendTaskSuccess (const SendTaskSuccessRequest &request)
StartExecutionResponse * startExecution (const StartExecutionRequest &request)
StopExecutionResponse * stopExecution (const StopExecutionRequest &request)
UpdateStateMachineResponse * updateStateMachine (const UpdateStateMachineRequest &request)
Public Member Functions
SfnClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SfnClient object.
SfnClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new SfnClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Step Functions (SFN)
<fullname>AWS Step Functions</fullname>
AWS Step Functions is a service that lets you coordinate the components of distributed applications and microservices using visual
workflows>
You can use Step Functions to build applications from individual components, each of which performs a discrete function, or task, allowing you to scale and change applications quickly. Step Functions provides a console that helps visualize the components of your application as a series of steps. Step Functions automatically triggers and tracks each step, and retries steps when there are errors, so your application executes predictably and in the right order every time. Step Functions logs the state of each step, so you can quickly diagnose and debug any
issues>
Step Functions manages operations and underlying infrastructure to ensure your application is available at any scale. You can run tasks on AWS, your own servers, or any system that has access to AWS. You can access and use Step Functions using the console, the AWS SDKs, or an HTTP API. For more information about Step Functions, see the AWS Step Functions Developer Guide
Definition at line 36 of file sfnclient.h.
Constructor & Destructor Documentation
SfnClient() [1/2]
AWS::SFN::SfnClient::SfnClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SfnClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 65 of file sfnclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new SfnClientPrivate(this), parent)
 {
     Q_D(SfnClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
SfnClient() [2/2]
AWS::SFN::SfnClient::SfnClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new SfnClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 95 of file sfnclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new SfnClientPrivate(this), parent)
 {
     Q_D(SfnClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
states/sfnclient.h
states/sfnclient.cpp