libqtaws: AWS::Glue::GlueClient Class Reference
AWS::Glue::GlueClient Class Reference
Client for AWS Glue.
Public Slots
BatchCreatePartitionResponse * batchCreatePartition (const BatchCreatePartitionRequest &request)
BatchDeleteConnectionResponse * batchDeleteConnection (const BatchDeleteConnectionRequest &request)
BatchDeletePartitionResponse * batchDeletePartition (const BatchDeletePartitionRequest &request)
BatchDeleteTableResponse * batchDeleteTable (const BatchDeleteTableRequest &request)
BatchDeleteTableVersionResponse * batchDeleteTableVersion (const BatchDeleteTableVersionRequest &request)
BatchGetPartitionResponse * batchGetPartition (const BatchGetPartitionRequest &request)
BatchStopJobRunResponse * batchStopJobRun (const BatchStopJobRunRequest &request)
CreateClassifierResponse * createClassifier (const CreateClassifierRequest &request)
CreateConnectionResponse * createConnection (const CreateConnectionRequest &request)
CreateCrawlerResponse * createCrawler (const CreateCrawlerRequest &request)
CreateDatabaseResponse * createDatabase (const CreateDatabaseRequest &request)
CreateDevEndpointResponse * createDevEndpoint (const CreateDevEndpointRequest &request)
CreateJobResponse * createJob (const CreateJobRequest &request)
CreatePartitionResponse * createPartition (const CreatePartitionRequest &request)
CreateScriptResponse * createScript (const CreateScriptRequest &request)
CreateTableResponse * createTable (const CreateTableRequest &request)
CreateTriggerResponse * createTrigger (const CreateTriggerRequest &request)
CreateUserDefinedFunctionResponse * createUserDefinedFunction (const CreateUserDefinedFunctionRequest &request)
DeleteClassifierResponse * deleteClassifier (const DeleteClassifierRequest &request)
DeleteConnectionResponse * deleteConnection (const DeleteConnectionRequest &request)
DeleteCrawlerResponse * deleteCrawler (const DeleteCrawlerRequest &request)
DeleteDatabaseResponse * deleteDatabase (const DeleteDatabaseRequest &request)
DeleteDevEndpointResponse * deleteDevEndpoint (const DeleteDevEndpointRequest &request)
DeleteJobResponse * deleteJob (const DeleteJobRequest &request)
DeletePartitionResponse * deletePartition (const DeletePartitionRequest &request)
DeleteTableResponse * deleteTable (const DeleteTableRequest &request)
DeleteTableVersionResponse * deleteTableVersion (const DeleteTableVersionRequest &request)
DeleteTriggerResponse * deleteTrigger (const DeleteTriggerRequest &request)
DeleteUserDefinedFunctionResponse * deleteUserDefinedFunction (const DeleteUserDefinedFunctionRequest &request)
GetCatalogImportStatusResponse * getCatalogImportStatus (const GetCatalogImportStatusRequest &request)
GetClassifierResponse * getClassifier (const GetClassifierRequest &request)
GetClassifiersResponse * getClassifiers (const GetClassifiersRequest &request)
GetConnectionResponse * getConnection (const GetConnectionRequest &request)
GetConnectionsResponse * getConnections (const GetConnectionsRequest &request)
GetCrawlerResponse * getCrawler (const GetCrawlerRequest &request)
GetCrawlerMetricsResponse * getCrawlerMetrics (const GetCrawlerMetricsRequest &request)
GetCrawlersResponse * getCrawlers (const GetCrawlersRequest &request)
GetDatabaseResponse * getDatabase (const GetDatabaseRequest &request)
GetDatabasesResponse * getDatabases (const GetDatabasesRequest &request)
GetDataflowGraphResponse * getDataflowGraph (const GetDataflowGraphRequest &request)
GetDevEndpointResponse * getDevEndpoint (const GetDevEndpointRequest &request)
GetDevEndpointsResponse * getDevEndpoints (const GetDevEndpointsRequest &request)
GetJobResponse * getJob (const GetJobRequest &request)
GetJobRunResponse * getJobRun (const GetJobRunRequest &request)
GetJobRunsResponse * getJobRuns (const GetJobRunsRequest &request)
GetJobsResponse * getJobs (const GetJobsRequest &request)
GetMappingResponse * getMapping (const GetMappingRequest &request)
GetPartitionResponse * getPartition (const GetPartitionRequest &request)
GetPartitionsResponse * getPartitions (const GetPartitionsRequest &request)
GetPlanResponse * getPlan (const GetPlanRequest &request)
GetTableResponse * getTable (const GetTableRequest &request)
GetTableVersionResponse * getTableVersion (const GetTableVersionRequest &request)
GetTableVersionsResponse * getTableVersions (const GetTableVersionsRequest &request)
GetTablesResponse * getTables (const GetTablesRequest &request)
GetTriggerResponse * getTrigger (const GetTriggerRequest &request)
GetTriggersResponse * getTriggers (const GetTriggersRequest &request)
GetUserDefinedFunctionResponse * getUserDefinedFunction (const GetUserDefinedFunctionRequest &request)
GetUserDefinedFunctionsResponse * getUserDefinedFunctions (const GetUserDefinedFunctionsRequest &request)
ImportCatalogToGlueResponse * importCatalogToGlue (const ImportCatalogToGlueRequest &request)
ResetJobBookmarkResponse * resetJobBookmark (const ResetJobBookmarkRequest &request)
StartCrawlerResponse * startCrawler (const StartCrawlerRequest &request)
StartCrawlerScheduleResponse * startCrawlerSchedule (const StartCrawlerScheduleRequest &request)
StartJobRunResponse * startJobRun (const StartJobRunRequest &request)
StartTriggerResponse * startTrigger (const StartTriggerRequest &request)
StopCrawlerResponse * stopCrawler (const StopCrawlerRequest &request)
StopCrawlerScheduleResponse * stopCrawlerSchedule (const StopCrawlerScheduleRequest &request)
StopTriggerResponse * stopTrigger (const StopTriggerRequest &request)
UpdateClassifierResponse * updateClassifier (const UpdateClassifierRequest &request)
UpdateConnectionResponse * updateConnection (const UpdateConnectionRequest &request)
UpdateCrawlerResponse * updateCrawler (const UpdateCrawlerRequest &request)
UpdateCrawlerScheduleResponse * updateCrawlerSchedule (const UpdateCrawlerScheduleRequest &request)
UpdateDatabaseResponse * updateDatabase (const UpdateDatabaseRequest &request)
UpdateDevEndpointResponse * updateDevEndpoint (const UpdateDevEndpointRequest &request)
UpdateJobResponse * updateJob (const UpdateJobRequest &request)
UpdatePartitionResponse * updatePartition (const UpdatePartitionRequest &request)
UpdateTableResponse * updateTable (const UpdateTableRequest &request)
UpdateTriggerResponse * updateTrigger (const UpdateTriggerRequest &request)
UpdateUserDefinedFunctionResponse * updateUserDefinedFunction (const UpdateUserDefinedFunctionRequest &request)
Public Member Functions
GlueClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new GlueClient object.
GlueClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new GlueClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Glue.
<fullname>AWS Glue</fullname>
Defines the public endpoint for the AWS Glue
Definition at line 36 of file glueclient.h.
Constructor & Destructor Documentation
GlueClient() [1/2]
AWS::Glue::GlueClient::GlueClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new GlueClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 49 of file glueclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new GlueClientPrivate(this), parent)
 {
     Q_D(GlueClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
GlueClient() [2/2]
AWS::Glue::GlueClient::GlueClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new GlueClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 79 of file glueclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new GlueClientPrivate(this), parent)
 {
     Q_D(GlueClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
glue/glueclient.h
glue/glueclient.cpp