libqtaws: S3Client Class Reference
S3Client Class Reference
Client for Amazon Simple Storage Service (S3)
Public Slots
S3AbortMultipartUploadResponse * abortMultipartUpload (const S3AbortMultipartUploadRequest &request)
S3CompleteMultipartUploadResponse * completeMultipartUpload (const S3CompleteMultipartUploadRequest &request)
S3CopyObjectResponse * copyObject (const S3CopyObjectRequest &request)
S3CreateBucketResponse * createBucket (const S3CreateBucketRequest &request)
S3CreateMultipartUploadResponse * createMultipartUpload (const S3CreateMultipartUploadRequest &request)
S3DeleteBucketResponse * deleteBucket (const S3DeleteBucketRequest &request)
S3DeleteBucketCorsResponse * deleteBucketCors (const S3DeleteBucketCorsRequest &request)
S3DeleteBucketLifecycleResponse * deleteBucketLifecycle (const S3DeleteBucketLifecycleRequest &request)
S3DeleteBucketPolicyResponse * deleteBucketPolicy (const S3DeleteBucketPolicyRequest &request)
S3DeleteBucketReplicationResponse * deleteBucketReplication (const S3DeleteBucketReplicationRequest &request)
S3DeleteBucketTaggingResponse * deleteBucketTagging (const S3DeleteBucketTaggingRequest &request)
S3DeleteBucketWebsiteResponse * deleteBucketWebsite (const S3DeleteBucketWebsiteRequest &request)
S3DeleteObjectResponse * deleteObject (const S3DeleteObjectRequest &request)
S3DeleteObjectsResponse * deleteObjects (const S3DeleteObjectsRequest &request)
S3GetBucketAccelerateConfigurationResponse * getBucketAccelerateConfiguration (const S3GetBucketAccelerateConfigurationRequest &request)
S3GetBucketAclResponse * getBucketAcl (const S3GetBucketAclRequest &request)
S3GetBucketCorsResponse * getBucketCors (const S3GetBucketCorsRequest &request)
S3GetBucketLifecycleResponse * getBucketLifecycle (const S3GetBucketLifecycleRequest &request)
S3GetBucketLifecycleConfigurationResponse * getBucketLifecycleConfiguration (const S3GetBucketLifecycleConfigurationRequest &request)
S3GetBucketLocationResponse * getBucketLocation (const S3GetBucketLocationRequest &request)
S3GetBucketLoggingResponse * getBucketLogging (const S3GetBucketLoggingRequest &request)
S3GetBucketNotificationResponse * getBucketNotification (const S3GetBucketNotificationRequest &request)
S3GetBucketNotificationConfigurationResponse * getBucketNotificationConfiguration (const S3GetBucketNotificationConfigurationRequest &request)
S3GetBucketPolicyResponse * getBucketPolicy (const S3GetBucketPolicyRequest &request)
S3GetBucketReplicationResponse * getBucketReplication (const S3GetBucketReplicationRequest &request)
S3GetBucketRequestPaymentResponse * getBucketRequestPayment (const S3GetBucketRequestPaymentRequest &request)
S3GetBucketTaggingResponse * getBucketTagging (const S3GetBucketTaggingRequest &request)
S3GetBucketVersioningResponse * getBucketVersioning (const S3GetBucketVersioningRequest &request)
S3GetBucketWebsiteResponse * getBucketWebsite (const S3GetBucketWebsiteRequest &request)
S3GetObjectResponse * getObject (const S3GetObjectRequest &request)
S3GetObjectAclResponse * getObjectAcl (const S3GetObjectAclRequest &request)
S3GetObjectTorrentResponse * getObjectTorrent (const S3GetObjectTorrentRequest &request)
S3HeadBucketResponse * headBucket (const S3HeadBucketRequest &request)
S3HeadObjectResponse * headObject (const S3HeadObjectRequest &request)
S3ListBucketsResponse * listBuckets ()
S3ListMultipartUploadsResponse * listMultipartUploads (const S3ListMultipartUploadsRequest &request)
S3ListObjectVersionsResponse * listObjectVersions (const S3ListObjectVersionsRequest &request)
S3ListObjectsResponse * listObjects (const S3ListObjectsRequest &request)
S3ListObjectsV2Response * listObjectsV2 (const S3ListObjectsV2Request &request)
S3ListPartsResponse * listParts (const S3ListPartsRequest &request)
S3PutBucketAccelerateConfigurationResponse * putBucketAccelerateConfiguration (const S3PutBucketAccelerateConfigurationRequest &request)
S3PutBucketAclResponse * putBucketAcl (const S3PutBucketAclRequest &request)
S3PutBucketCorsResponse * putBucketCors (const S3PutBucketCorsRequest &request)
S3PutBucketLifecycleResponse * putBucketLifecycle (const S3PutBucketLifecycleRequest &request)
S3PutBucketLifecycleConfigurationResponse * putBucketLifecycleConfiguration (const S3PutBucketLifecycleConfigurationRequest &request)
S3PutBucketLoggingResponse * putBucketLogging (const S3PutBucketLoggingRequest &request)
S3PutBucketNotificationResponse * putBucketNotification (const S3PutBucketNotificationRequest &request)
S3PutBucketNotificationConfigurationResponse * putBucketNotificationConfiguration (const S3PutBucketNotificationConfigurationRequest &request)
S3PutBucketPolicyResponse * putBucketPolicy (const S3PutBucketPolicyRequest &request)
S3PutBucketReplicationResponse * putBucketReplication (const S3PutBucketReplicationRequest &request)
S3PutBucketRequestPaymentResponse * putBucketRequestPayment (const S3PutBucketRequestPaymentRequest &request)
S3PutBucketTaggingResponse * putBucketTagging (const S3PutBucketTaggingRequest &request)
S3PutBucketVersioningResponse * putBucketVersioning (const S3PutBucketVersioningRequest &request)
S3PutBucketWebsiteResponse * putBucketWebsite (const S3PutBucketWebsiteRequest &request)
S3PutObjectResponse * putObject (const S3PutObjectRequest &request)
S3PutObjectAclResponse * putObjectAcl (const S3PutObjectAclRequest &request)
S3RestoreObjectResponse * restoreObject (const S3RestoreObjectRequest &request)
S3UploadPartResponse * uploadPart (const S3UploadPartRequest &request)
S3UploadPartCopyResponse * uploadPartCopy (const S3UploadPartCopyRequest &request)
Public Member Functions
S3Client (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new S3Client object.
S3Client (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new S3Client object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for Amazon Simple Storage Service (S3)
Definition at line 33 of file s3client.h.
Constructor & Destructor Documentation
S3Client::S3Client (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new S3Client object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 46 of file s3client.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new S3ClientPrivate(this), parent)
 {
     Q_D(S3Client);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
S3Client::S3Client (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new S3Client object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 76 of file s3client.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new S3ClientPrivate(this), parent)
 {
     Q_D(S3Client);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
s3/s3client.h
s3/s3client.cpp