libqtaws: AwsAbstractRequest Class Reference
AwsAbstractRequest Class Reference abstract
Interface class for providing AWS requests.
Public Member Functions
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Protected Member Functions
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const =0
Build a network request for the given endpoint.
Protected Attributes
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Friends
class TestAwsAbstractRequest
Detailed Description
Interface class for providing AWS requests.
Typically, a user would pass a derived class (such as SqsCreateQueueRequest) to an AwsAbstractClient-derived class (such as SqsClient) to send a request to an AWS service.
Note, by design, requests based on this class are endpoint-agnostic. That is, you may instantiate a request (such as an SqsCreateQueueRequest), and pass it to multiple clients (such as a US instance of SqsClient as well as an AU instance of SqsClient). Thus it is the caller (typically an AwsAbstractClient-derived class) that is responsible for for setting the region / endpoint information, allowing requests to be reused unmodified multiple times, and/or in multiple regions.
Definition at line 39 of file awsabstractrequest.h.
Constructor & Destructor Documentation
AwsAbstractRequest::AwsAbstractRequest (AwsAbstractRequestPrivate *const d) protected
Constructs a new AwsAbstractRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from AwsAbstractRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 94 of file awsabstractrequest.cpp.
                                                                           : d_ptr(d)
 {
 }
Member Function Documentation
QByteArray AwsAbstractRequest::data () const virtual
Get the data, if relevant, to be included with PUT and/or POST operations.
Returns
Definition at line 127 of file awsabstractrequest.cpp.
Referenced by networkRequest(), operator=(), operator==(), and setData().
 {
     Q_D(const AwsAbstractRequest);
     return d->data;
 }
bool AwsAbstractRequest::isValid () const pure virtual
Is this request valid?
Derived classes must implement this function to provide a level of request validation relevant to the type of request being implemented.
In this context, "valid" means that with valid credentials, the request's networkRequest method should return a request that the caller can reasonably expect AWS to accept (ignoring server side access restrictions and the like).
Returns
true if this request is considered valid, false other.
Implemented in SqsAddPermissionRequest, SqsChangeMessageVisibilityRequest, SqsCreateQueueRequest, SqsGetQueueUrlRequest, SqsChangeMessageVisibilityBatchRequest, SqsDeleteMessageBatchRequest, SqsDeleteMessageRequest, SqsDeleteQueueRequest, SqsGetQueueAttributesRequest, SqsListDeadLetterSourceQueuesRequest, SqsListQueuesRequest, SqsPurgeQueueRequest, SqsReceiveMessageRequest, SqsRemovePermissionRequest, SqsSendMessageBatchRequest, SqsSendMessageRequest, and SqsSetQueueAttributesRequest.
Referenced by AwsAbstractClient::send(), and send().
QNetworkRequest AwsAbstractRequest::networkRequest (const QUrl & endpoint, const AwsAbstractSignature & signature, const AwsAbstractCredentials & credentials) const virtual
Construct a QNetworkRequest for this AWS request.
This base implementation used the protected unsignedRequest function to fetch the basic request to be sent, then uses signature and credentials to sign the request before returning to the caller.
Derived classes may override this if their specific AWS service required more advanced logic (or disallow signing, for example).
Parameters
endpoint AWS endpoint the request is to be for.
signature AWS signature class for signing the request.
credentials AWS credentials to use for signing the request.
Returns
A valid, signed (where appropriate) request that can be sent to via a network access manager to perform the configured request.
See also
unsignedRequest
Definition at line 152 of file awsabstractrequest.cpp.
References data(), operation(), AwsAbstractSignature::sign(), and unsignedRequest().
Referenced by send().
 {
     QNetworkRequest request(unsignedRequest(endpoint));
     signature.sign(credentials, operation(), request, data());
     return request;
 }
QNetworkAccessManager::Operation AwsAbstractRequest::operation () const virtual
Get the network operation this request uses.
This defaults to QNetworkAccessManager::GetOperation unless overridden or changed via setOperation.
Returns
Network operation to use when sending this request.
See also
setOperation
Definition at line 172 of file awsabstractrequest.cpp.
Referenced by networkRequest(), operator=(), operator==(), send(), and setOperation().
 {
     Q_D(const AwsAbstractRequest);
     return d->operation;
 }
AwsAbstractRequest & AwsAbstractRequest::operator= (const AwsAbstractRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 76 of file awsabstractrequest.cpp.
References data(), and operation().
 {
     Q_D(AwsAbstractRequest);
     d->data = other.d_func()->data;
     d->operation = other.d_func()->operation;
     return *this;
 }
bool AwsAbstractRequest::operator== (const AwsAbstractRequest & other) const virtual
Equality operator.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 227 of file awsabstractrequest.cpp.
References data(), and operation().
 {
     return ((data() == other.data()) && (operation() == other.operation()));
 }
AwsAbstractResponse * AwsAbstractRequest::response (QNetworkReply *const reply) const protected pure virtual
Construct an appropriate AWS response object.
Derived classes must implement this pure virtual function to return the relevant AwsAbstractResponse-derived object for their request type.
For example, the SqsCreateQueueRequest::response implementation returns an instance of the related SqsCreateQueueResponse class. Typically an AwsAbstractClient-derived class will cast this the returned pointer to the relevant known type in its send method.
Parameters
reply Network reply this response should observe.
Returns
An AWS response object for reply.
See also
AwsAbstractClient::send
Implemented in SqsAddPermissionRequest, SqsCreateQueueRequest, SqsChangeMessageVisibilityRequest, SqsGetQueueUrlRequest, SqsDeleteMessageRequest, SqsRemovePermissionRequest, SqsDeleteQueueRequest, SqsListDeadLetterSourceQueuesRequest, SqsListQueuesRequest, SqsPurgeQueueRequest, SqsChangeMessageVisibilityBatchRequest, SqsDeleteMessageBatchRequest, SqsGetQueueAttributesRequest, SqsReceiveMessageRequest, SqsSendMessageBatchRequest, SqsSendMessageRequest, and SqsSetQueueAttributesRequest.
Referenced by send().
AwsAbstractResponse * AwsAbstractRequest::send (QNetworkAccessManager & manager, const QUrl & endpoint, const AwsAbstractSignature & signature, const AwsAbstractCredentials & credentials) const virtual
Send this request to a given Amazon endpoint, via the specified network access manager.
Parameters
manager Network access manager to send the request via.
endpoint AWS service endpoint to send the request to.
signature Signature implementation to use to sign the request.
credentials AWS credentials to use to sign the request.
Returns
AwsAbstractResponse-derived object representing the AWS service's response.
Definition at line 189 of file awsabstractrequest.cpp.
References isValid(), networkRequest(), operation(), and response().
Referenced by AwsAbstractClient::send().
 {
     Q_ASSERT(isValid());
     Q_D(const AwsAbstractRequest);
     const QNetworkRequest request(networkRequest(endpoint, signature, credentials));
     qDebug() << "Request URL:" << request.url().toString(QUrl::FullyEncoded);
     if (request.hasRawHeader("Authorization")) {
         qDebug() << "Authorization:" << request.rawHeader("Authorization");
     }
     switch (operation()) {
         case QNetworkAccessManager::DeleteOperation:
             return response(manager.deleteResource(request));
         case QNetworkAccessManager::HeadOperation:
             return response(manager.head(request));
         case QNetworkAccessManager::GetOperation:
             return response(manager.get(request));
         case QNetworkAccessManager::PostOperation:
             return response(d->post(manager, request));
         case QNetworkAccessManager::PutOperation:
             return response(d->put(manager, request));
         case QNetworkAccessManager::CustomOperation: // Fall through.
         default:
             // Catch this in debug mode for easier development / debugging.
             Q_ASSERT_X(false, Q_FUNC_INFO, "invalid operation");
     }
     return NULL;
 }
void AwsAbstractRequest::setData (const QByteArray & data) protected
Set the data to be used with POST and/or PUT operations.
Parameters
data POST/PUT data.
Definition at line 237 of file awsabstractrequest.cpp.
References data().
 {
     Q_D(AwsAbstractRequest);
     d->data = data;
 }
void AwsAbstractRequest::setOperation (const QNetworkAccessManager::Operation operation) protected
Set the network operation to use when submitting this request.
Parameters
operation Network operation to use.
Definition at line 248 of file awsabstractrequest.cpp.
References operation().
 {
     Q_D(AwsAbstractRequest);
     d->operation = operation;
 }
QNetworkRequest AwsAbstractRequest::unsignedRequest (const QUrl & endpoint) const protected pure virtual
Build a network request for the given endpoint.
Derived classes must implement this pure virtual function to build network requests that the networkRequest function can sign, before being subitted to Amazon.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for the given endpoint.
Implemented in SqsRequest.
Referenced by networkRequest().
The documentation for this class was generated from the following files:
core/awsabstractrequest.h
core/awsabstractrequest.cpp