libqtaws: SqsRequest Class Reference
SqsRequest Class Reference
Interface class for providing SQS requests.
Public Types
enum Action {
AddPermissionAction = 0x00001, ChangeMessageVisibilityAction = 0x00002, ChangeMessageVisibilityBatchAction = 0x00004, CreateQueueAction = 0x00008,
DeleteMessageAction = 0x00010, DeleteMessageBatchAction = 0x00020, DeleteQueueAction = 0x00040, GetQueueAttributesAction = 0x00080,
GetQueueUrlAction = 0x00100, ListDeadLetterSourceQueuesAction = 0x00200, ListQueuesAction = 0x00400, PurgeQueueAction = 0x00800,
ReceiveMessageAction = 0x01000, RemovePermissionAction = 0x02000, SendMessageAction = 0x04000, SendMessageBatchAction = 0x08000,
SetQueueAttributesAction = 0x10000
}
Actions supported by SQS.
Public Member Functions
SqsRequest (const Action action)
Constructs a new SqsRequest object.
SqsRequest (const SqsRequest &other)
Constructs a new SqsRequest object by copying another.
SqsRequest & operator= (const SqsRequest &other)
Assignment operator.
Action action () const
Get the SQS action to be performed by this request.
QString actionString () const
Get the name of the SQS action to be performed by this request.
QString apiVersion () const
Get the SQS API version implemented by this request.
void setAction (const Action action)
Set the SQS action to be performed by this request.
void setApiVersion (const QString &version)
Set the SQS API version to include in this request.
virtual bool operator== (const SqsRequest &other) const
Equality operator.
Public Member Functions inherited from AwsAbstractRequest
AwsAbstractRequest ()
Constructs a new AwsAbstractRequest object.
AwsAbstractRequest (const AwsAbstractRequest &other)
Constructs a new AwsAbstractRequest object by copying another.
AwsAbstractRequest & operator= (const AwsAbstractRequest &other)
Assignment operator.
virtual ~AwsAbstractRequest ()
AwsAbstractRequest destructor.
virtual QByteArray data () const
Get the data, if relevant, to be included with PUT and/or POST operations.
virtual bool isValid () const =0
Is this request valid?
virtual QNetworkRequest networkRequest (const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Construct a QNetworkRequest for this AWS request.
virtual QNetworkAccessManager::Operation operation () const
Get the network operation this request uses.
virtual AwsAbstractResponse * send (QNetworkAccessManager &manager, const QUrl &endpoint, const AwsAbstractSignature &signature, const AwsAbstractCredentials &credentials) const
Send this request to a given Amazon endpoint, via the specified network access manager.
virtual bool operator== (const AwsAbstractRequest &other) const
Equality operator.
Static Public Member Functions
static bool isValidQueueName (const QString &queueName)
Check if queueName is a valid SQS queue name.
Protected Member Functions
SqsRequest (SqsRequestPrivate *const d)
Constructs a new SqsRequest object.
int clearParameter (const QString &name)
Remove a parameter from the parameters to be included with this request.
void clearParameters ()
Clear all parameters that were to be included with this request.
QVariant parameter (const QString &name, const QVariant &defaultValue=QVariant()) const
Get the value of a parameter included with this SQS request.
const QVariantMap & parameters () const
Get all parameters included with this SQS request.
void setParameter (const QString &name, const QVariant &value)
Set a parameter to include with this SQS request.
void setParameters (const QVariantMap &parameters)
Set all parameters to include with this SQS request.
virtual QNetworkRequest unsignedRequest (const QUrl &endpoint) const
Build a network request object for this SQS request.
Protected Member Functions inherited from AwsAbstractRequest
AwsAbstractRequest (AwsAbstractRequestPrivate *const d)
Constructs a new AwsAbstractRequest object.
void setData (const QByteArray &data)
Set the data to be used with POST and/or PUT operations.
void setOperation (const QNetworkAccessManager::Operation operation)
Set the network operation to use when submitting this request.
virtual AwsAbstractResponse * response (QNetworkReply *const reply) const =0
Construct an appropriate AWS response object.
Friends
class TestSqsRequest
Additional Inherited Members
Protected Attributes inherited from AwsAbstractRequest
AwsAbstractRequestPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Interface class for providing SQS requests.
Definition at line 35 of file sqsrequest.h.
Constructor & Destructor Documentation
SqsRequest::SqsRequest (const Action action)
Constructs a new SqsRequest object.
Parameters
action The SQS action to request.
Definition at line 44 of file sqsrequest.cpp.
     : AwsAbstractRequest(new SqsRequestPrivate(action, this))
 {
 }
SqsRequest::SqsRequest (const SqsRequest & other)
Constructs a new SqsRequest object by copying another.
Parameters
other Instance to copy.
Definition at line 55 of file sqsrequest.cpp.
     : AwsAbstractRequest(new SqsRequestPrivate(*other.d_func(), this))
 {
 }
SqsRequest::SqsRequest (SqsRequestPrivate *const d) protected
Constructs a new SqsRequest object.
This overload allows derived classes to provide their own private class implementation that inherits from SqsRequestPrivate.
Parameters
d Pointer to private data (aka D-Pointer).
Definition at line 89 of file sqsrequest.cpp.
                                                   : AwsAbstractRequest(d)
 {
 }
Member Function Documentation
SqsRequest::Action SqsRequest::action () const
Get the SQS action to be performed by this request.
Returns
The SQS action to be performed by this request.
Definition at line 99 of file sqsrequest.cpp.
Referenced by actionString(), operator=(), operator==(), setAction(), and SqsAddPermissionRequest::setPermission().
 {
     Q_D(const SqsRequest);
     return d->action;
 }
QString SqsRequest::actionString () const
Get the name of the SQS action to be performed by this request.
Returns
The name of the SQS action to be performed by this request.
Definition at line 110 of file sqsrequest.cpp.
References action().
 {
     Q_D(const SqsRequest);
     return d->toString(action());
 }
QString SqsRequest::apiVersion () const
Get the SQS API version implemented by this request.
Returns
The SQS API version implmented by this request.
Definition at line 121 of file sqsrequest.cpp.
Referenced by operator=(), and operator==().
 {
     Q_D(const SqsRequest);
     return d->apiVersion;
 }
int SqsRequest::clearParameter (const QString & name) protected
Remove a parameter from the parameters to be included with this request.
Parameters
name Name of the parameter to remove.
Returns
Count of parameters removed (should be 0 or 1).
Definition at line 195 of file sqsrequest.cpp.
 {
     Q_D(SqsRequest);
     return d->parameters.remove(name);
 }
bool SqsRequest::isValidQueueName (const QString & queueName) static
Check if queueName is a valid SQS queue name.
From SQS FAQs:
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.
Parameters
queueName Name to check for validity.
Returns
true if queueName is a valid SQS queue name, false otherwise.
See also
http://aws.amazon.com/sqs/faqs/
Definition at line 182 of file sqsrequest.cpp.
Referenced by SqsCreateQueueRequest::isValid(), and SqsAddPermissionRequest::isValid().
 {
     const QRegExp pattern(QLatin1String("[a-zA-Z0-9-_]{1,80}"));
     return pattern.exactMatch(queueName);
 }
SqsRequest & SqsRequest::operator= (const SqsRequest & other)
Assignment operator.
Assigns other to this.
Parameters
other Instance to copy.
Returns
A reference to this.
Definition at line 70 of file sqsrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     Q_D(SqsRequest);
     d->action = other.d_func()->action;
     d->apiVersion = other.d_func()->apiVersion;
     d->parameters = other.d_func()->parameters;
     return *this;
 }
bool SqsRequest::operator== (const SqsRequest & other) const virtual
Equality operator.
Note, most derived Sqs*Request classes do not need to provider their own implementations of this function, since most such request classes rely on this class' parameters functionality for all request parameters, and that parameters map is already checked via this implementation.
Parameters
other Instance to compare this to.
Returns
true if this and other are considered equal.
Definition at line 161 of file sqsrequest.cpp.
References action(), apiVersion(), and parameters().
 {
     return ((action() == other.action()) &&
             (apiVersion() == other.apiVersion()) &&
             (parameters() == other.parameters()) &&
             (AwsAbstractRequest::operator ==(other)));
 }
QVariant SqsRequest::parameter (const QString & name, const QVariant & defaultValue = QVariant()) const protected
Get the value of a parameter included with this SQS request.
Parameters
name Name of the parameter to get the value of.
defaultValue Default value to return if no such parameter has been set.
Returns
The value of the specified parameter, or defaultValue of not set.
Definition at line 218 of file sqsrequest.cpp.
Referenced by SqsCreateQueueRequest::attributes(), SqsRemovePermissionRequest::label(), SqsAddPermissionRequest::label(), SqsCreateQueueRequest::queueName(), SqsDeleteMessageRequest::queueUrl(), SqsDeleteQueueRequest::queueUrl(), SqsPurgeQueueRequest::queueUrl(), SqsRemovePermissionRequest::queueUrl(), SqsChangeMessageVisibilityRequest::queueUrl(), SqsAddPermissionRequest::queueUrl(), SqsDeleteMessageRequest::receiptHandle(), SqsChangeMessageVisibilityRequest::receiptHandle(), and SqsChangeMessageVisibilityRequest::visibilityTimeout().
 {
     Q_D(const SqsRequest);
     return d->parameters.value(name, defaultValue);
 }
const QVariantMap & SqsRequest::parameters () const protected
Get all parameters included with this SQS request.
Returns
A map of parameters included with this request.
Definition at line 229 of file sqsrequest.cpp.
Referenced by operator=(), operator==(), and setParameters().
 {
     Q_D(const SqsRequest);
     return d->parameters;
 }
void SqsRequest::setAction (const Action action)
Set the SQS action to be performed by this request.
Parameters
action The action to be performed by this request.
Definition at line 132 of file sqsrequest.cpp.
References action().
 {
     Q_D(SqsRequest);
     d->action = action;
 }
void SqsRequest::setApiVersion (const QString & version)
Set the SQS API version to include in this request.
Parameters
version The SQS API version to include in this request.
Definition at line 143 of file sqsrequest.cpp.
 {
     Q_D(SqsRequest);
     d->apiVersion = version;
 }
void SqsRequest::setParameter (const QString & name, const QVariant & value) protected
Set a parameter to include with this SQS request.
Parameters
name Name of the parameter to include.
value Value of the parameter to include.
Definition at line 241 of file sqsrequest.cpp.
Referenced by SqsCreateQueueRequest::setAttributes(), SqsRemovePermissionRequest::setLabel(), SqsAddPermissionRequest::setLabel(), SqsCreateQueueRequest::setQueueName(), SqsDeleteQueueRequest::setQueueUrl(), SqsPurgeQueueRequest::setQueueUrl(), SqsDeleteMessageRequest::setQueueUrl(), SqsRemovePermissionRequest::setQueueUrl(), SqsChangeMessageVisibilityRequest::setQueueUrl(), SqsAddPermissionRequest::setQueueUrl(), SqsDeleteMessageRequest::setReceiptHandle(), SqsChangeMessageVisibilityRequest::setReceiptHandle(), and SqsChangeMessageVisibilityRequest::setVisibilityTimeout().
 {
     Q_D(SqsRequest);
     d->parameters.insert(name, value);
 }
void SqsRequest::setParameters (const QVariantMap & parameters) protected
Set all parameters to include with this SQS request.
Any request parameters set previously will be discarded.
Parameters
parameters New request parameters to inclued with this request.
Definition at line 254 of file sqsrequest.cpp.
References parameters().
 {
     Q_D(SqsRequest);
     d->parameters = parameters;
 }
QNetworkRequest SqsRequest::unsignedRequest (const QUrl & endpoint) const protected virtual
Build a network request object for this SQS request.
This SQS implementation builds request URLs by combining the common query parameters (such as Action and Version), with any that have been added (via setParameter) by child classes.
Parameters
endpoint AWS endpoint to build this request for.
Returns
A network request for this SQS request using the given endpoint.
Implements AwsAbstractRequest.
Definition at line 271 of file sqsrequest.cpp.
 {
     Q_D(const SqsRequest);
     QUrl url(endpoint);
     url.setQuery(d->urlQuery());
     return QNetworkRequest(url);
 }
The documentation for this class was generated from the following files:
sqs/sqsrequest.h
sqs/sqsrequest.cpp