libqtaws: AWS::ElasticBeanstalk::ElasticBeanstalkClient Class Reference
AWS::ElasticBeanstalk::ElasticBeanstalkClient Class Reference
Client for AWS Elastic Beanstalk.
Public Slots
AbortEnvironmentUpdateResponse * abortEnvironmentUpdate (const AbortEnvironmentUpdateRequest &request)
ApplyEnvironmentManagedActionResponse * applyEnvironmentManagedAction (const ApplyEnvironmentManagedActionRequest &request)
CheckDNSAvailabilityResponse * checkDNSAvailability (const CheckDNSAvailabilityRequest &request)
ComposeEnvironmentsResponse * composeEnvironments (const ComposeEnvironmentsRequest &request)
CreateApplicationResponse * createApplication (const CreateApplicationRequest &request)
CreateApplicationVersionResponse * createApplicationVersion (const CreateApplicationVersionRequest &request)
CreateConfigurationTemplateResponse * createConfigurationTemplate (const CreateConfigurationTemplateRequest &request)
CreateEnvironmentResponse * createEnvironment (const CreateEnvironmentRequest &request)
CreatePlatformVersionResponse * createPlatformVersion (const CreatePlatformVersionRequest &request)
CreateStorageLocationResponse * createStorageLocation ()
DeleteApplicationResponse * deleteApplication (const DeleteApplicationRequest &request)
DeleteApplicationVersionResponse * deleteApplicationVersion (const DeleteApplicationVersionRequest &request)
DeleteConfigurationTemplateResponse * deleteConfigurationTemplate (const DeleteConfigurationTemplateRequest &request)
DeleteEnvironmentConfigurationResponse * deleteEnvironmentConfiguration (const DeleteEnvironmentConfigurationRequest &request)
DeletePlatformVersionResponse * deletePlatformVersion (const DeletePlatformVersionRequest &request)
DescribeAccountAttributesResponse * describeAccountAttributes ()
DescribeApplicationVersionsResponse * describeApplicationVersions (const DescribeApplicationVersionsRequest &request)
DescribeApplicationsResponse * describeApplications (const DescribeApplicationsRequest &request)
DescribeConfigurationOptionsResponse * describeConfigurationOptions (const DescribeConfigurationOptionsRequest &request)
DescribeConfigurationSettingsResponse * describeConfigurationSettings (const DescribeConfigurationSettingsRequest &request)
DescribeEnvironmentHealthResponse * describeEnvironmentHealth (const DescribeEnvironmentHealthRequest &request)
DescribeEnvironmentManagedActionHistoryResponse * describeEnvironmentManagedActionHistory (const DescribeEnvironmentManagedActionHistoryRequest &request)
DescribeEnvironmentManagedActionsResponse * describeEnvironmentManagedActions (const DescribeEnvironmentManagedActionsRequest &request)
DescribeEnvironmentResourcesResponse * describeEnvironmentResources (const DescribeEnvironmentResourcesRequest &request)
DescribeEnvironmentsResponse * describeEnvironments (const DescribeEnvironmentsRequest &request)
DescribeEventsResponse * describeEvents (const DescribeEventsRequest &request)
DescribeInstancesHealthResponse * describeInstancesHealth (const DescribeInstancesHealthRequest &request)
DescribePlatformVersionResponse * describePlatformVersion (const DescribePlatformVersionRequest &request)
ListAvailableSolutionStacksResponse * listAvailableSolutionStacks ()
ListPlatformVersionsResponse * listPlatformVersions (const ListPlatformVersionsRequest &request)
ListTagsForResourceResponse * listTagsForResource (const ListTagsForResourceRequest &request)
RebuildEnvironmentResponse * rebuildEnvironment (const RebuildEnvironmentRequest &request)
RequestEnvironmentInfoResponse * requestEnvironmentInfo (const RequestEnvironmentInfoRequest &request)
RestartAppServerResponse * restartAppServer (const RestartAppServerRequest &request)
RetrieveEnvironmentInfoResponse * retrieveEnvironmentInfo (const RetrieveEnvironmentInfoRequest &request)
SwapEnvironmentCNAMEsResponse * swapEnvironmentCNAMEs (const SwapEnvironmentCNAMEsRequest &request)
TerminateEnvironmentResponse * terminateEnvironment (const TerminateEnvironmentRequest &request)
UpdateApplicationResponse * updateApplication (const UpdateApplicationRequest &request)
UpdateApplicationResourceLifecycleResponse * updateApplicationResourceLifecycle (const UpdateApplicationResourceLifecycleRequest &request)
UpdateApplicationVersionResponse * updateApplicationVersion (const UpdateApplicationVersionRequest &request)
UpdateConfigurationTemplateResponse * updateConfigurationTemplate (const UpdateConfigurationTemplateRequest &request)
UpdateEnvironmentResponse * updateEnvironment (const UpdateEnvironmentRequest &request)
UpdateTagsForResourceResponse * updateTagsForResource (const UpdateTagsForResourceRequest &request)
ValidateConfigurationSettingsResponse * validateConfigurationSettings (const ValidateConfigurationSettingsRequest &request)
Public Member Functions
ElasticBeanstalkClient (const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticBeanstalkClient object.
ElasticBeanstalkClient (const QUrl &endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)
Constructs a new ElasticBeanstalkClient object.
Public Member Functions inherited from AwsAbstractClient
AwsAbstractClient (QObject *const parent=0)
Constructs a new AwsAbstractClient object.
virtual ~AwsAbstractClient ()
AwsAbstractClient destructor.
QUrl endpoint () const
Get the endpoint associated with this AWS client.
QNetworkAccessManager * networkAccessManager () const
Get the network access manager for this AWS service object.
AwsRegion::Region region () const
Get the AWS region associated with this client.
virtual AwsAbstractResponse * send (const AwsAbstractRequest &request)
Send an AWS request.
QString serviceName () const
Get the name of the Amazon service this client accesses.
void setCredentials (AwsAbstractCredentials *const credentials)
Set the credentials object for this client to use for signing requests.
void setEndpoint (const QUrl &endpoint)
Set the AWS endpoint to use with this client.
void setNetworkAccessManager (QNetworkAccessManager *const manager)
Set the network access manager for this AWS service object.
void setRegion (const AwsRegion::Region region)
Set the AWS region this client accesses.
Additional Inherited Members
Protected Member Functions inherited from AwsAbstractClient
AwsAbstractClient (AwsAbstractClientPrivate *const d, QObject *const parent)
Constructs a new AwsAbstractClient object.
virtual AwsAbstractCredentials * credentials () const
Get the credentials object to be used for signing requests.
virtual AwsAbstractSignature * signature () const
Get the signature object to be used for signing requests.
Protected Attributes inherited from AwsAbstractClient
AwsAbstractClientPrivate *const d_ptr
Internal d-pointer.
Detailed Description
Client for AWS Elastic Beanstalk.
<fullname>AWS Elastic Beanstalk</fullname>
AWS Elastic Beanstalk makes it easy for you to create, deploy, and manage scalable, fault-tolerant applications running on the Amazon Web Services
cloud>
For more information about this product, go to the AWS Elastic Beanstalk details page. The location of the latest AWS Elastic Beanstalk WSDL is http://elasticbeanstalk.s3.amazonaws.com/doc/2010-12-01/AWSElasticBeanstalk.wsdl. To install the Software Development Kits (SDKs), Integrated Development Environment (IDE) Toolkits, and command line tools that enable you to access the API, go to Tools for Amazon Web Services>
Endpoints
</p
For a list of region-specific endpoints that AWS Elastic Beanstalk supports, go to Regions and Endpoints in the Amazon Web Services
Definition at line 36 of file elasticbeanstalkclient.h.
Constructor & Destructor Documentation
ElasticBeanstalkClient() [1/2]
AWS::ElasticBeanstalk::ElasticBeanstalkClient::ElasticBeanstalkClient (const AwsRegion::Region region = AwsRegion::InvalidRegion, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticBeanstalkClient object.
Parameters
region AWS region for this client to service requests for.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
Definition at line 68 of file elasticbeanstalkclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::region().
 : AwsAbstractClient(new ElasticBeanstalkClientPrivate(this), parent)
 {
     Q_D(ElasticBeanstalkClient);
     d->region = region;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
ElasticBeanstalkClient() [2/2]
AWS::ElasticBeanstalk::ElasticBeanstalkClient::ElasticBeanstalkClient (const QUrl & endpoint, AwsAbstractCredentials * credentials = NULL, QNetworkAccessManager *const manager = NULL, QObject *const parent = 0)
Constructs a new ElasticBeanstalkClient object.
This overload allows the caller to specify the specific endpoint to send requests to. Typically, it is easier to use the alternative constructor, which allows the caller to specify an AWS region instead, in which case this client will determine the correct endpoint for the given region automatically (via AwsEndpoint::getEndpoint).
Parameters
endpoint Endpoint for building requests URLs.
credentials AWS credentials to use for signing requests.
manager Network access manager for sending requests.
parent This object's parent.
See also
AwsEndpoint::getEndpoint
Definition at line 98 of file elasticbeanstalkclient.cpp.
References AwsAbstractClient::credentials(), and AwsAbstractClient::endpoint().
 : AwsAbstractClient(new ElasticBeanstalkClientPrivate(this), parent)
 {
     Q_D(ElasticBeanstalkClient);
     d->endpoint = endpoint;
     d->credentials = credentials;
     d->networkAccessManager = manager;
     d->serviceName = QLatin1String("{{servicename}}");
 }
The documentation for this class was generated from the following files:
elasticbeanstalk/elasticbeanstalkclient.h
elasticbeanstalk/elasticbeanstalkclient.cpp