include(../../common.pri)

TARGET = QtAwsChime
TEMPLATE = lib
QT -= gui
QT += network
DEFINES += QTAWS_LIBRARY
DEFINES += QT_NO_CAST_FROM_ASCII QT_NO_CAST_TO_ASCII

INCLUDEPATH = $$TOPDIR/src

HEADERS += \
    associatephonenumberswithvoiceconnectorrequest.h \
    associatephonenumberswithvoiceconnectorrequest_p.h \
    associatephonenumberswithvoiceconnectorresponse.h \
    associatephonenumberswithvoiceconnectorresponse_p.h \
    associatephonenumberwithuserrequest.h \
    associatephonenumberwithuserrequest_p.h \
    associatephonenumberwithuserresponse.h \
    associatephonenumberwithuserresponse_p.h \
    batchdeletephonenumberrequest.h \
    batchdeletephonenumberrequest_p.h \
    batchdeletephonenumberresponse.h \
    batchdeletephonenumberresponse_p.h \
    batchsuspenduserrequest.h \
    batchsuspenduserrequest_p.h \
    batchsuspenduserresponse.h \
    batchsuspenduserresponse_p.h \
    batchunsuspenduserrequest.h \
    batchunsuspenduserrequest_p.h \
    batchunsuspenduserresponse.h \
    batchunsuspenduserresponse_p.h \
    batchupdatephonenumberrequest.h \
    batchupdatephonenumberrequest_p.h \
    batchupdatephonenumberresponse.h \
    batchupdatephonenumberresponse_p.h \
    batchupdateuserrequest.h \
    batchupdateuserrequest_p.h \
    batchupdateuserresponse.h \
    batchupdateuserresponse_p.h \
    chimeclient.h \
    chimeclient_p.h \
    chimerequest.h \
    chimerequest_p.h \
    chimeresponse.h \
    chimeresponse_p.h \
    createaccountrequest.h \
    createaccountrequest_p.h \
    createaccountresponse.h \
    createaccountresponse_p.h \
    createbotrequest.h \
    createbotrequest_p.h \
    createbotresponse.h \
    createbotresponse_p.h \
    createphonenumberorderrequest.h \
    createphonenumberorderrequest_p.h \
    createphonenumberorderresponse.h \
    createphonenumberorderresponse_p.h \
    createvoiceconnectorrequest.h \
    createvoiceconnectorrequest_p.h \
    createvoiceconnectorresponse.h \
    createvoiceconnectorresponse_p.h \
    deleteaccountrequest.h \
    deleteaccountrequest_p.h \
    deleteaccountresponse.h \
    deleteaccountresponse_p.h \
    deleteeventsconfigurationrequest.h \
    deleteeventsconfigurationrequest_p.h \
    deleteeventsconfigurationresponse.h \
    deleteeventsconfigurationresponse_p.h \
    deletephonenumberrequest.h \
    deletephonenumberrequest_p.h \
    deletephonenumberresponse.h \
    deletephonenumberresponse_p.h \
    deletevoiceconnectororiginationrequest.h \
    deletevoiceconnectororiginationrequest_p.h \
    deletevoiceconnectororiginationresponse.h \
    deletevoiceconnectororiginationresponse_p.h \
    deletevoiceconnectorrequest.h \
    deletevoiceconnectorrequest_p.h \
    deletevoiceconnectorresponse.h \
    deletevoiceconnectorresponse_p.h \
    deletevoiceconnectorterminationcredentialsrequest.h \
    deletevoiceconnectorterminationcredentialsrequest_p.h \
    deletevoiceconnectorterminationcredentialsresponse.h \
    deletevoiceconnectorterminationcredentialsresponse_p.h \
    deletevoiceconnectorterminationrequest.h \
    deletevoiceconnectorterminationrequest_p.h \
    deletevoiceconnectorterminationresponse.h \
    deletevoiceconnectorterminationresponse_p.h \
    disassociatephonenumberfromuserrequest.h \
    disassociatephonenumberfromuserrequest_p.h \
    disassociatephonenumberfromuserresponse.h \
    disassociatephonenumberfromuserresponse_p.h \
    disassociatephonenumbersfromvoiceconnectorrequest.h \
    disassociatephonenumbersfromvoiceconnectorrequest_p.h \
    disassociatephonenumbersfromvoiceconnectorresponse.h \
    disassociatephonenumbersfromvoiceconnectorresponse_p.h \
    getaccountrequest.h \
    getaccountrequest_p.h \
    getaccountresponse.h \
    getaccountresponse_p.h \
    getaccountsettingsrequest.h \
    getaccountsettingsrequest_p.h \
    getaccountsettingsresponse.h \
    getaccountsettingsresponse_p.h \
    getbotrequest.h \
    getbotrequest_p.h \
    getbotresponse.h \
    getbotresponse_p.h \
    geteventsconfigurationrequest.h \
    geteventsconfigurationrequest_p.h \
    geteventsconfigurationresponse.h \
    geteventsconfigurationresponse_p.h \
    getglobalsettingsrequest.h \
    getglobalsettingsrequest_p.h \
    getglobalsettingsresponse.h \
    getglobalsettingsresponse_p.h \
    getphonenumberorderrequest.h \
    getphonenumberorderrequest_p.h \
    getphonenumberorderresponse.h \
    getphonenumberorderresponse_p.h \
    getphonenumberrequest.h \
    getphonenumberrequest_p.h \
    getphonenumberresponse.h \
    getphonenumberresponse_p.h \
    getuserrequest.h \
    getuserrequest_p.h \
    getuserresponse.h \
    getuserresponse_p.h \
    getusersettingsrequest.h \
    getusersettingsrequest_p.h \
    getusersettingsresponse.h \
    getusersettingsresponse_p.h \
    getvoiceconnectororiginationrequest.h \
    getvoiceconnectororiginationrequest_p.h \
    getvoiceconnectororiginationresponse.h \
    getvoiceconnectororiginationresponse_p.h \
    getvoiceconnectorrequest.h \
    getvoiceconnectorrequest_p.h \
    getvoiceconnectorresponse.h \
    getvoiceconnectorresponse_p.h \
    getvoiceconnectorterminationhealthrequest.h \
    getvoiceconnectorterminationhealthrequest_p.h \
    getvoiceconnectorterminationhealthresponse.h \
    getvoiceconnectorterminationhealthresponse_p.h \
    getvoiceconnectorterminationrequest.h \
    getvoiceconnectorterminationrequest_p.h \
    getvoiceconnectorterminationresponse.h \
    getvoiceconnectorterminationresponse_p.h \
    inviteusersrequest.h \
    inviteusersrequest_p.h \
    inviteusersresponse.h \
    inviteusersresponse_p.h \
    listaccountsrequest.h \
    listaccountsrequest_p.h \
    listaccountsresponse.h \
    listaccountsresponse_p.h \
    listbotsrequest.h \
    listbotsrequest_p.h \
    listbotsresponse.h \
    listbotsresponse_p.h \
    listphonenumberordersrequest.h \
    listphonenumberordersrequest_p.h \
    listphonenumberordersresponse.h \
    listphonenumberordersresponse_p.h \
    listphonenumbersrequest.h \
    listphonenumbersrequest_p.h \
    listphonenumbersresponse.h \
    listphonenumbersresponse_p.h \
    listusersrequest.h \
    listusersrequest_p.h \
    listusersresponse.h \
    listusersresponse_p.h \
    listvoiceconnectorsrequest.h \
    listvoiceconnectorsrequest_p.h \
    listvoiceconnectorsresponse.h \
    listvoiceconnectorsresponse_p.h \
    listvoiceconnectorterminationcredentialsrequest.h \
    listvoiceconnectorterminationcredentialsrequest_p.h \
    listvoiceconnectorterminationcredentialsresponse.h \
    listvoiceconnectorterminationcredentialsresponse_p.h \
    logoutuserrequest.h \
    logoutuserrequest_p.h \
    logoutuserresponse.h \
    logoutuserresponse_p.h \
    puteventsconfigurationrequest.h \
    puteventsconfigurationrequest_p.h \
    puteventsconfigurationresponse.h \
    puteventsconfigurationresponse_p.h \
    putvoiceconnectororiginationrequest.h \
    putvoiceconnectororiginationrequest_p.h \
    putvoiceconnectororiginationresponse.h \
    putvoiceconnectororiginationresponse_p.h \
    putvoiceconnectorterminationcredentialsrequest.h \
    putvoiceconnectorterminationcredentialsrequest_p.h \
    putvoiceconnectorterminationcredentialsresponse.h \
    putvoiceconnectorterminationcredentialsresponse_p.h \
    putvoiceconnectorterminationrequest.h \
    putvoiceconnectorterminationrequest_p.h \
    putvoiceconnectorterminationresponse.h \
    putvoiceconnectorterminationresponse_p.h \
    regeneratesecuritytokenrequest.h \
    regeneratesecuritytokenrequest_p.h \
    regeneratesecuritytokenresponse.h \
    regeneratesecuritytokenresponse_p.h \
    resetpersonalpinrequest.h \
    resetpersonalpinrequest_p.h \
    resetpersonalpinresponse.h \
    resetpersonalpinresponse_p.h \
    restorephonenumberrequest.h \
    restorephonenumberrequest_p.h \
    restorephonenumberresponse.h \
    restorephonenumberresponse_p.h \
    searchavailablephonenumbersrequest.h \
    searchavailablephonenumbersrequest_p.h \
    searchavailablephonenumbersresponse.h \
    searchavailablephonenumbersresponse_p.h \
    updateaccountrequest.h \
    updateaccountrequest_p.h \
    updateaccountresponse.h \
    updateaccountresponse_p.h \
    updateaccountsettingsrequest.h \
    updateaccountsettingsrequest_p.h \
    updateaccountsettingsresponse.h \
    updateaccountsettingsresponse_p.h \
    updatebotrequest.h \
    updatebotrequest_p.h \
    updatebotresponse.h \
    updatebotresponse_p.h \
    updateglobalsettingsrequest.h \
    updateglobalsettingsrequest_p.h \
    updateglobalsettingsresponse.h \
    updateglobalsettingsresponse_p.h \
    updatephonenumberrequest.h \
    updatephonenumberrequest_p.h \
    updatephonenumberresponse.h \
    updatephonenumberresponse_p.h \
    updateuserrequest.h \
    updateuserrequest_p.h \
    updateuserresponse.h \
    updateuserresponse_p.h \
    updateusersettingsrequest.h \
    updateusersettingsrequest_p.h \
    updateusersettingsresponse.h \
    updateusersettingsresponse_p.h \
    updatevoiceconnectorrequest.h \
    updatevoiceconnectorrequest_p.h \
    updatevoiceconnectorresponse.h \
    updatevoiceconnectorresponse_p.h \

SOURCES += \
    associatephonenumberswithvoiceconnectorrequest.cpp \
    associatephonenumberswithvoiceconnectorresponse.cpp \
    associatephonenumberwithuserrequest.cpp \
    associatephonenumberwithuserresponse.cpp \
    batchdeletephonenumberrequest.cpp \
    batchdeletephonenumberresponse.cpp \
    batchsuspenduserrequest.cpp \
    batchsuspenduserresponse.cpp \
    batchunsuspenduserrequest.cpp \
    batchunsuspenduserresponse.cpp \
    batchupdatephonenumberrequest.cpp \
    batchupdatephonenumberresponse.cpp \
    batchupdateuserrequest.cpp \
    batchupdateuserresponse.cpp \
    chimeclient.cpp \
    chimerequest.cpp \
    chimeresponse.cpp \
    createaccountrequest.cpp \
    createaccountresponse.cpp \
    createbotrequest.cpp \
    createbotresponse.cpp \
    createphonenumberorderrequest.cpp \
    createphonenumberorderresponse.cpp \
    createvoiceconnectorrequest.cpp \
    createvoiceconnectorresponse.cpp \
    deleteaccountrequest.cpp \
    deleteaccountresponse.cpp \
    deleteeventsconfigurationrequest.cpp \
    deleteeventsconfigurationresponse.cpp \
    deletephonenumberrequest.cpp \
    deletephonenumberresponse.cpp \
    deletevoiceconnectororiginationrequest.cpp \
    deletevoiceconnectororiginationresponse.cpp \
    deletevoiceconnectorrequest.cpp \
    deletevoiceconnectorresponse.cpp \
    deletevoiceconnectorterminationcredentialsrequest.cpp \
    deletevoiceconnectorterminationcredentialsresponse.cpp \
    deletevoiceconnectorterminationrequest.cpp \
    deletevoiceconnectorterminationresponse.cpp \
    disassociatephonenumberfromuserrequest.cpp \
    disassociatephonenumberfromuserresponse.cpp \
    disassociatephonenumbersfromvoiceconnectorrequest.cpp \
    disassociatephonenumbersfromvoiceconnectorresponse.cpp \
    getaccountrequest.cpp \
    getaccountresponse.cpp \
    getaccountsettingsrequest.cpp \
    getaccountsettingsresponse.cpp \
    getbotrequest.cpp \
    getbotresponse.cpp \
    geteventsconfigurationrequest.cpp \
    geteventsconfigurationresponse.cpp \
    getglobalsettingsrequest.cpp \
    getglobalsettingsresponse.cpp \
    getphonenumberorderrequest.cpp \
    getphonenumberorderresponse.cpp \
    getphonenumberrequest.cpp \
    getphonenumberresponse.cpp \
    getuserrequest.cpp \
    getuserresponse.cpp \
    getusersettingsrequest.cpp \
    getusersettingsresponse.cpp \
    getvoiceconnectororiginationrequest.cpp \
    getvoiceconnectororiginationresponse.cpp \
    getvoiceconnectorrequest.cpp \
    getvoiceconnectorresponse.cpp \
    getvoiceconnectorterminationhealthrequest.cpp \
    getvoiceconnectorterminationhealthresponse.cpp \
    getvoiceconnectorterminationrequest.cpp \
    getvoiceconnectorterminationresponse.cpp \
    inviteusersrequest.cpp \
    inviteusersresponse.cpp \
    listaccountsrequest.cpp \
    listaccountsresponse.cpp \
    listbotsrequest.cpp \
    listbotsresponse.cpp \
    listphonenumberordersrequest.cpp \
    listphonenumberordersresponse.cpp \
    listphonenumbersrequest.cpp \
    listphonenumbersresponse.cpp \
    listusersrequest.cpp \
    listusersresponse.cpp \
    listvoiceconnectorsrequest.cpp \
    listvoiceconnectorsresponse.cpp \
    listvoiceconnectorterminationcredentialsrequest.cpp \
    listvoiceconnectorterminationcredentialsresponse.cpp \
    logoutuserrequest.cpp \
    logoutuserresponse.cpp \
    puteventsconfigurationrequest.cpp \
    puteventsconfigurationresponse.cpp \
    putvoiceconnectororiginationrequest.cpp \
    putvoiceconnectororiginationresponse.cpp \
    putvoiceconnectorterminationcredentialsrequest.cpp \
    putvoiceconnectorterminationcredentialsresponse.cpp \
    putvoiceconnectorterminationrequest.cpp \
    putvoiceconnectorterminationresponse.cpp \
    regeneratesecuritytokenrequest.cpp \
    regeneratesecuritytokenresponse.cpp \
    resetpersonalpinrequest.cpp \
    resetpersonalpinresponse.cpp \
    restorephonenumberrequest.cpp \
    restorephonenumberresponse.cpp \
    searchavailablephonenumbersrequest.cpp \
    searchavailablephonenumbersresponse.cpp \
    updateaccountrequest.cpp \
    updateaccountresponse.cpp \
    updateaccountsettingsrequest.cpp \
    updateaccountsettingsresponse.cpp \
    updatebotrequest.cpp \
    updatebotresponse.cpp \
    updateglobalsettingsrequest.cpp \
    updateglobalsettingsresponse.cpp \
    updatephonenumberrequest.cpp \
    updatephonenumberresponse.cpp \
    updateuserrequest.cpp \
    updateuserresponse.cpp \
    updateusersettingsrequest.cpp \
    updateusersettingsresponse.cpp \
    updatevoiceconnectorrequest.cpp \
    updatevoiceconnectorresponse.cpp \

win32:CONFIG += skip_target_version_ext
