/*
    Copyright 2013-2021 Paul Colby

    This file is part of QtAws.

    QtAws is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    QtAws is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with the QtAws.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef QTAWS_CHIMECLIENT_H
#define QTAWS_CHIMECLIENT_H

#include "core/awsabstractclient.h"

#include "qtawschimeglobal.h"

class QNetworkReply;

namespace QtAws {
namespace Chime {

class ChimeClientPrivate;
class AssociatePhoneNumberWithUserRequest;
class AssociatePhoneNumberWithUserResponse;
class AssociatePhoneNumbersWithVoiceConnectorRequest;
class AssociatePhoneNumbersWithVoiceConnectorResponse;
class AssociatePhoneNumbersWithVoiceConnectorGroupRequest;
class AssociatePhoneNumbersWithVoiceConnectorGroupResponse;
class AssociateSigninDelegateGroupsWithAccountRequest;
class AssociateSigninDelegateGroupsWithAccountResponse;
class BatchCreateAttendeeRequest;
class BatchCreateAttendeeResponse;
class BatchCreateChannelMembershipRequest;
class BatchCreateChannelMembershipResponse;
class BatchCreateRoomMembershipRequest;
class BatchCreateRoomMembershipResponse;
class BatchDeletePhoneNumberRequest;
class BatchDeletePhoneNumberResponse;
class BatchSuspendUserRequest;
class BatchSuspendUserResponse;
class BatchUnsuspendUserRequest;
class BatchUnsuspendUserResponse;
class BatchUpdatePhoneNumberRequest;
class BatchUpdatePhoneNumberResponse;
class BatchUpdateUserRequest;
class BatchUpdateUserResponse;
class CreateAccountRequest;
class CreateAccountResponse;
class CreateAppInstanceRequest;
class CreateAppInstanceResponse;
class CreateAppInstanceAdminRequest;
class CreateAppInstanceAdminResponse;
class CreateAppInstanceUserRequest;
class CreateAppInstanceUserResponse;
class CreateAttendeeRequest;
class CreateAttendeeResponse;
class CreateBotRequest;
class CreateBotResponse;
class CreateChannelRequest;
class CreateChannelResponse;
class CreateChannelBanRequest;
class CreateChannelBanResponse;
class CreateChannelMembershipRequest;
class CreateChannelMembershipResponse;
class CreateChannelModeratorRequest;
class CreateChannelModeratorResponse;
class CreateMeetingRequest;
class CreateMeetingResponse;
class CreateMeetingDialOutRequest;
class CreateMeetingDialOutResponse;
class CreateMeetingWithAttendeesRequest;
class CreateMeetingWithAttendeesResponse;
class CreatePhoneNumberOrderRequest;
class CreatePhoneNumberOrderResponse;
class CreateProxySessionRequest;
class CreateProxySessionResponse;
class CreateRoomRequest;
class CreateRoomResponse;
class CreateRoomMembershipRequest;
class CreateRoomMembershipResponse;
class CreateSipMediaApplicationRequest;
class CreateSipMediaApplicationResponse;
class CreateSipMediaApplicationCallRequest;
class CreateSipMediaApplicationCallResponse;
class CreateSipRuleRequest;
class CreateSipRuleResponse;
class CreateUserRequest;
class CreateUserResponse;
class CreateVoiceConnectorRequest;
class CreateVoiceConnectorResponse;
class CreateVoiceConnectorGroupRequest;
class CreateVoiceConnectorGroupResponse;
class DeleteAccountRequest;
class DeleteAccountResponse;
class DeleteAppInstanceRequest;
class DeleteAppInstanceResponse;
class DeleteAppInstanceAdminRequest;
class DeleteAppInstanceAdminResponse;
class DeleteAppInstanceStreamingConfigurationsRequest;
class DeleteAppInstanceStreamingConfigurationsResponse;
class DeleteAppInstanceUserRequest;
class DeleteAppInstanceUserResponse;
class DeleteAttendeeRequest;
class DeleteAttendeeResponse;
class DeleteChannelRequest;
class DeleteChannelResponse;
class DeleteChannelBanRequest;
class DeleteChannelBanResponse;
class DeleteChannelMembershipRequest;
class DeleteChannelMembershipResponse;
class DeleteChannelMessageRequest;
class DeleteChannelMessageResponse;
class DeleteChannelModeratorRequest;
class DeleteChannelModeratorResponse;
class DeleteEventsConfigurationRequest;
class DeleteEventsConfigurationResponse;
class DeleteMeetingRequest;
class DeleteMeetingResponse;
class DeletePhoneNumberRequest;
class DeletePhoneNumberResponse;
class DeleteProxySessionRequest;
class DeleteProxySessionResponse;
class DeleteRoomRequest;
class DeleteRoomResponse;
class DeleteRoomMembershipRequest;
class DeleteRoomMembershipResponse;
class DeleteSipMediaApplicationRequest;
class DeleteSipMediaApplicationResponse;
class DeleteSipRuleRequest;
class DeleteSipRuleResponse;
class DeleteVoiceConnectorRequest;
class DeleteVoiceConnectorResponse;
class DeleteVoiceConnectorEmergencyCallingConfigurationRequest;
class DeleteVoiceConnectorEmergencyCallingConfigurationResponse;
class DeleteVoiceConnectorGroupRequest;
class DeleteVoiceConnectorGroupResponse;
class DeleteVoiceConnectorOriginationRequest;
class DeleteVoiceConnectorOriginationResponse;
class DeleteVoiceConnectorProxyRequest;
class DeleteVoiceConnectorProxyResponse;
class DeleteVoiceConnectorStreamingConfigurationRequest;
class DeleteVoiceConnectorStreamingConfigurationResponse;
class DeleteVoiceConnectorTerminationRequest;
class DeleteVoiceConnectorTerminationResponse;
class DeleteVoiceConnectorTerminationCredentialsRequest;
class DeleteVoiceConnectorTerminationCredentialsResponse;
class DescribeAppInstanceRequest;
class DescribeAppInstanceResponse;
class DescribeAppInstanceAdminRequest;
class DescribeAppInstanceAdminResponse;
class DescribeAppInstanceUserRequest;
class DescribeAppInstanceUserResponse;
class DescribeChannelRequest;
class DescribeChannelResponse;
class DescribeChannelBanRequest;
class DescribeChannelBanResponse;
class DescribeChannelMembershipRequest;
class DescribeChannelMembershipResponse;
class DescribeChannelMembershipForAppInstanceUserRequest;
class DescribeChannelMembershipForAppInstanceUserResponse;
class DescribeChannelModeratedByAppInstanceUserRequest;
class DescribeChannelModeratedByAppInstanceUserResponse;
class DescribeChannelModeratorRequest;
class DescribeChannelModeratorResponse;
class DisassociatePhoneNumberFromUserRequest;
class DisassociatePhoneNumberFromUserResponse;
class DisassociatePhoneNumbersFromVoiceConnectorRequest;
class DisassociatePhoneNumbersFromVoiceConnectorResponse;
class DisassociatePhoneNumbersFromVoiceConnectorGroupRequest;
class DisassociatePhoneNumbersFromVoiceConnectorGroupResponse;
class DisassociateSigninDelegateGroupsFromAccountRequest;
class DisassociateSigninDelegateGroupsFromAccountResponse;
class GetAccountRequest;
class GetAccountResponse;
class GetAccountSettingsRequest;
class GetAccountSettingsResponse;
class GetAppInstanceRetentionSettingsRequest;
class GetAppInstanceRetentionSettingsResponse;
class GetAppInstanceStreamingConfigurationsRequest;
class GetAppInstanceStreamingConfigurationsResponse;
class GetAttendeeRequest;
class GetAttendeeResponse;
class GetBotRequest;
class GetBotResponse;
class GetChannelMessageRequest;
class GetChannelMessageResponse;
class GetEventsConfigurationRequest;
class GetEventsConfigurationResponse;
class GetGlobalSettingsRequest;
class GetGlobalSettingsResponse;
class GetMeetingRequest;
class GetMeetingResponse;
class GetMessagingSessionEndpointRequest;
class GetMessagingSessionEndpointResponse;
class GetPhoneNumberRequest;
class GetPhoneNumberResponse;
class GetPhoneNumberOrderRequest;
class GetPhoneNumberOrderResponse;
class GetPhoneNumberSettingsRequest;
class GetPhoneNumberSettingsResponse;
class GetProxySessionRequest;
class GetProxySessionResponse;
class GetRetentionSettingsRequest;
class GetRetentionSettingsResponse;
class GetRoomRequest;
class GetRoomResponse;
class GetSipMediaApplicationRequest;
class GetSipMediaApplicationResponse;
class GetSipMediaApplicationLoggingConfigurationRequest;
class GetSipMediaApplicationLoggingConfigurationResponse;
class GetSipRuleRequest;
class GetSipRuleResponse;
class GetUserRequest;
class GetUserResponse;
class GetUserSettingsRequest;
class GetUserSettingsResponse;
class GetVoiceConnectorRequest;
class GetVoiceConnectorResponse;
class GetVoiceConnectorEmergencyCallingConfigurationRequest;
class GetVoiceConnectorEmergencyCallingConfigurationResponse;
class GetVoiceConnectorGroupRequest;
class GetVoiceConnectorGroupResponse;
class GetVoiceConnectorLoggingConfigurationRequest;
class GetVoiceConnectorLoggingConfigurationResponse;
class GetVoiceConnectorOriginationRequest;
class GetVoiceConnectorOriginationResponse;
class GetVoiceConnectorProxyRequest;
class GetVoiceConnectorProxyResponse;
class GetVoiceConnectorStreamingConfigurationRequest;
class GetVoiceConnectorStreamingConfigurationResponse;
class GetVoiceConnectorTerminationRequest;
class GetVoiceConnectorTerminationResponse;
class GetVoiceConnectorTerminationHealthRequest;
class GetVoiceConnectorTerminationHealthResponse;
class InviteUsersRequest;
class InviteUsersResponse;
class ListAccountsRequest;
class ListAccountsResponse;
class ListAppInstanceAdminsRequest;
class ListAppInstanceAdminsResponse;
class ListAppInstanceUsersRequest;
class ListAppInstanceUsersResponse;
class ListAppInstancesRequest;
class ListAppInstancesResponse;
class ListAttendeeTagsRequest;
class ListAttendeeTagsResponse;
class ListAttendeesRequest;
class ListAttendeesResponse;
class ListBotsRequest;
class ListBotsResponse;
class ListChannelBansRequest;
class ListChannelBansResponse;
class ListChannelMembershipsRequest;
class ListChannelMembershipsResponse;
class ListChannelMembershipsForAppInstanceUserRequest;
class ListChannelMembershipsForAppInstanceUserResponse;
class ListChannelMessagesRequest;
class ListChannelMessagesResponse;
class ListChannelModeratorsRequest;
class ListChannelModeratorsResponse;
class ListChannelsRequest;
class ListChannelsResponse;
class ListChannelsModeratedByAppInstanceUserRequest;
class ListChannelsModeratedByAppInstanceUserResponse;
class ListMeetingTagsRequest;
class ListMeetingTagsResponse;
class ListMeetingsRequest;
class ListMeetingsResponse;
class ListPhoneNumberOrdersRequest;
class ListPhoneNumberOrdersResponse;
class ListPhoneNumbersRequest;
class ListPhoneNumbersResponse;
class ListProxySessionsRequest;
class ListProxySessionsResponse;
class ListRoomMembershipsRequest;
class ListRoomMembershipsResponse;
class ListRoomsRequest;
class ListRoomsResponse;
class ListSipMediaApplicationsRequest;
class ListSipMediaApplicationsResponse;
class ListSipRulesRequest;
class ListSipRulesResponse;
class ListSupportedPhoneNumberCountriesRequest;
class ListSupportedPhoneNumberCountriesResponse;
class ListTagsForResourceRequest;
class ListTagsForResourceResponse;
class ListUsersRequest;
class ListUsersResponse;
class ListVoiceConnectorGroupsRequest;
class ListVoiceConnectorGroupsResponse;
class ListVoiceConnectorTerminationCredentialsRequest;
class ListVoiceConnectorTerminationCredentialsResponse;
class ListVoiceConnectorsRequest;
class ListVoiceConnectorsResponse;
class LogoutUserRequest;
class LogoutUserResponse;
class PutAppInstanceRetentionSettingsRequest;
class PutAppInstanceRetentionSettingsResponse;
class PutAppInstanceStreamingConfigurationsRequest;
class PutAppInstanceStreamingConfigurationsResponse;
class PutEventsConfigurationRequest;
class PutEventsConfigurationResponse;
class PutRetentionSettingsRequest;
class PutRetentionSettingsResponse;
class PutSipMediaApplicationLoggingConfigurationRequest;
class PutSipMediaApplicationLoggingConfigurationResponse;
class PutVoiceConnectorEmergencyCallingConfigurationRequest;
class PutVoiceConnectorEmergencyCallingConfigurationResponse;
class PutVoiceConnectorLoggingConfigurationRequest;
class PutVoiceConnectorLoggingConfigurationResponse;
class PutVoiceConnectorOriginationRequest;
class PutVoiceConnectorOriginationResponse;
class PutVoiceConnectorProxyRequest;
class PutVoiceConnectorProxyResponse;
class PutVoiceConnectorStreamingConfigurationRequest;
class PutVoiceConnectorStreamingConfigurationResponse;
class PutVoiceConnectorTerminationRequest;
class PutVoiceConnectorTerminationResponse;
class PutVoiceConnectorTerminationCredentialsRequest;
class PutVoiceConnectorTerminationCredentialsResponse;
class RedactChannelMessageRequest;
class RedactChannelMessageResponse;
class RedactConversationMessageRequest;
class RedactConversationMessageResponse;
class RedactRoomMessageRequest;
class RedactRoomMessageResponse;
class RegenerateSecurityTokenRequest;
class RegenerateSecurityTokenResponse;
class ResetPersonalPINRequest;
class ResetPersonalPINResponse;
class RestorePhoneNumberRequest;
class RestorePhoneNumberResponse;
class SearchAvailablePhoneNumbersRequest;
class SearchAvailablePhoneNumbersResponse;
class SendChannelMessageRequest;
class SendChannelMessageResponse;
class TagAttendeeRequest;
class TagAttendeeResponse;
class TagMeetingRequest;
class TagMeetingResponse;
class TagResourceRequest;
class TagResourceResponse;
class UntagAttendeeRequest;
class UntagAttendeeResponse;
class UntagMeetingRequest;
class UntagMeetingResponse;
class UntagResourceRequest;
class UntagResourceResponse;
class UpdateAccountRequest;
class UpdateAccountResponse;
class UpdateAccountSettingsRequest;
class UpdateAccountSettingsResponse;
class UpdateAppInstanceRequest;
class UpdateAppInstanceResponse;
class UpdateAppInstanceUserRequest;
class UpdateAppInstanceUserResponse;
class UpdateBotRequest;
class UpdateBotResponse;
class UpdateChannelRequest;
class UpdateChannelResponse;
class UpdateChannelMessageRequest;
class UpdateChannelMessageResponse;
class UpdateChannelReadMarkerRequest;
class UpdateChannelReadMarkerResponse;
class UpdateGlobalSettingsRequest;
class UpdateGlobalSettingsResponse;
class UpdatePhoneNumberRequest;
class UpdatePhoneNumberResponse;
class UpdatePhoneNumberSettingsRequest;
class UpdatePhoneNumberSettingsResponse;
class UpdateProxySessionRequest;
class UpdateProxySessionResponse;
class UpdateRoomRequest;
class UpdateRoomResponse;
class UpdateRoomMembershipRequest;
class UpdateRoomMembershipResponse;
class UpdateSipMediaApplicationRequest;
class UpdateSipMediaApplicationResponse;
class UpdateSipRuleRequest;
class UpdateSipRuleResponse;
class UpdateUserRequest;
class UpdateUserResponse;
class UpdateUserSettingsRequest;
class UpdateUserSettingsResponse;
class UpdateVoiceConnectorRequest;
class UpdateVoiceConnectorResponse;
class UpdateVoiceConnectorGroupRequest;
class UpdateVoiceConnectorGroupResponse;

class QTAWSCHIME_EXPORT ChimeClient : public QtAws::Core::AwsAbstractClient {
    Q_OBJECT

public:
    ChimeClient(
        const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion,
        QtAws::Core::AwsAbstractCredentials * credentials = NULL,
        QNetworkAccessManager * const manager = NULL,
        QObject * const parent = 0);

    explicit ChimeClient(
        const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL,
        QNetworkAccessManager * const manager = NULL,
        QObject * const parent = 0);

public slots:
    AssociatePhoneNumberWithUserResponse * associatePhoneNumberWithUser(const AssociatePhoneNumberWithUserRequest &request);
    AssociatePhoneNumbersWithVoiceConnectorResponse * associatePhoneNumbersWithVoiceConnector(const AssociatePhoneNumbersWithVoiceConnectorRequest &request);
    AssociatePhoneNumbersWithVoiceConnectorGroupResponse * associatePhoneNumbersWithVoiceConnectorGroup(const AssociatePhoneNumbersWithVoiceConnectorGroupRequest &request);
    AssociateSigninDelegateGroupsWithAccountResponse * associateSigninDelegateGroupsWithAccount(const AssociateSigninDelegateGroupsWithAccountRequest &request);
    BatchCreateAttendeeResponse * batchCreateAttendee(const BatchCreateAttendeeRequest &request);
    BatchCreateChannelMembershipResponse * batchCreateChannelMembership(const BatchCreateChannelMembershipRequest &request);
    BatchCreateRoomMembershipResponse * batchCreateRoomMembership(const BatchCreateRoomMembershipRequest &request);
    BatchDeletePhoneNumberResponse * batchDeletePhoneNumber(const BatchDeletePhoneNumberRequest &request);
    BatchSuspendUserResponse * batchSuspendUser(const BatchSuspendUserRequest &request);
    BatchUnsuspendUserResponse * batchUnsuspendUser(const BatchUnsuspendUserRequest &request);
    BatchUpdatePhoneNumberResponse * batchUpdatePhoneNumber(const BatchUpdatePhoneNumberRequest &request);
    BatchUpdateUserResponse * batchUpdateUser(const BatchUpdateUserRequest &request);
    CreateAccountResponse * createAccount(const CreateAccountRequest &request);
    CreateAppInstanceResponse * createAppInstance(const CreateAppInstanceRequest &request);
    CreateAppInstanceAdminResponse * createAppInstanceAdmin(const CreateAppInstanceAdminRequest &request);
    CreateAppInstanceUserResponse * createAppInstanceUser(const CreateAppInstanceUserRequest &request);
    CreateAttendeeResponse * createAttendee(const CreateAttendeeRequest &request);
    CreateBotResponse * createBot(const CreateBotRequest &request);
    CreateChannelResponse * createChannel(const CreateChannelRequest &request);
    CreateChannelBanResponse * createChannelBan(const CreateChannelBanRequest &request);
    CreateChannelMembershipResponse * createChannelMembership(const CreateChannelMembershipRequest &request);
    CreateChannelModeratorResponse * createChannelModerator(const CreateChannelModeratorRequest &request);
    CreateMeetingResponse * createMeeting(const CreateMeetingRequest &request);
    CreateMeetingDialOutResponse * createMeetingDialOut(const CreateMeetingDialOutRequest &request);
    CreateMeetingWithAttendeesResponse * createMeetingWithAttendees(const CreateMeetingWithAttendeesRequest &request);
    CreatePhoneNumberOrderResponse * createPhoneNumberOrder(const CreatePhoneNumberOrderRequest &request);
    CreateProxySessionResponse * createProxySession(const CreateProxySessionRequest &request);
    CreateRoomResponse * createRoom(const CreateRoomRequest &request);
    CreateRoomMembershipResponse * createRoomMembership(const CreateRoomMembershipRequest &request);
    CreateSipMediaApplicationResponse * createSipMediaApplication(const CreateSipMediaApplicationRequest &request);
    CreateSipMediaApplicationCallResponse * createSipMediaApplicationCall(const CreateSipMediaApplicationCallRequest &request);
    CreateSipRuleResponse * createSipRule(const CreateSipRuleRequest &request);
    CreateUserResponse * createUser(const CreateUserRequest &request);
    CreateVoiceConnectorResponse * createVoiceConnector(const CreateVoiceConnectorRequest &request);
    CreateVoiceConnectorGroupResponse * createVoiceConnectorGroup(const CreateVoiceConnectorGroupRequest &request);
    DeleteAccountResponse * deleteAccount(const DeleteAccountRequest &request);
    DeleteAppInstanceResponse * deleteAppInstance(const DeleteAppInstanceRequest &request);
    DeleteAppInstanceAdminResponse * deleteAppInstanceAdmin(const DeleteAppInstanceAdminRequest &request);
    DeleteAppInstanceStreamingConfigurationsResponse * deleteAppInstanceStreamingConfigurations(const DeleteAppInstanceStreamingConfigurationsRequest &request);
    DeleteAppInstanceUserResponse * deleteAppInstanceUser(const DeleteAppInstanceUserRequest &request);
    DeleteAttendeeResponse * deleteAttendee(const DeleteAttendeeRequest &request);
    DeleteChannelResponse * deleteChannel(const DeleteChannelRequest &request);
    DeleteChannelBanResponse * deleteChannelBan(const DeleteChannelBanRequest &request);
    DeleteChannelMembershipResponse * deleteChannelMembership(const DeleteChannelMembershipRequest &request);
    DeleteChannelMessageResponse * deleteChannelMessage(const DeleteChannelMessageRequest &request);
    DeleteChannelModeratorResponse * deleteChannelModerator(const DeleteChannelModeratorRequest &request);
    DeleteEventsConfigurationResponse * deleteEventsConfiguration(const DeleteEventsConfigurationRequest &request);
    DeleteMeetingResponse * deleteMeeting(const DeleteMeetingRequest &request);
    DeletePhoneNumberResponse * deletePhoneNumber(const DeletePhoneNumberRequest &request);
    DeleteProxySessionResponse * deleteProxySession(const DeleteProxySessionRequest &request);
    DeleteRoomResponse * deleteRoom(const DeleteRoomRequest &request);
    DeleteRoomMembershipResponse * deleteRoomMembership(const DeleteRoomMembershipRequest &request);
    DeleteSipMediaApplicationResponse * deleteSipMediaApplication(const DeleteSipMediaApplicationRequest &request);
    DeleteSipRuleResponse * deleteSipRule(const DeleteSipRuleRequest &request);
    DeleteVoiceConnectorResponse * deleteVoiceConnector(const DeleteVoiceConnectorRequest &request);
    DeleteVoiceConnectorEmergencyCallingConfigurationResponse * deleteVoiceConnectorEmergencyCallingConfiguration(const DeleteVoiceConnectorEmergencyCallingConfigurationRequest &request);
    DeleteVoiceConnectorGroupResponse * deleteVoiceConnectorGroup(const DeleteVoiceConnectorGroupRequest &request);
    DeleteVoiceConnectorOriginationResponse * deleteVoiceConnectorOrigination(const DeleteVoiceConnectorOriginationRequest &request);
    DeleteVoiceConnectorProxyResponse * deleteVoiceConnectorProxy(const DeleteVoiceConnectorProxyRequest &request);
    DeleteVoiceConnectorStreamingConfigurationResponse * deleteVoiceConnectorStreamingConfiguration(const DeleteVoiceConnectorStreamingConfigurationRequest &request);
    DeleteVoiceConnectorTerminationResponse * deleteVoiceConnectorTermination(const DeleteVoiceConnectorTerminationRequest &request);
    DeleteVoiceConnectorTerminationCredentialsResponse * deleteVoiceConnectorTerminationCredentials(const DeleteVoiceConnectorTerminationCredentialsRequest &request);
    DescribeAppInstanceResponse * describeAppInstance(const DescribeAppInstanceRequest &request);
    DescribeAppInstanceAdminResponse * describeAppInstanceAdmin(const DescribeAppInstanceAdminRequest &request);
    DescribeAppInstanceUserResponse * describeAppInstanceUser(const DescribeAppInstanceUserRequest &request);
    DescribeChannelResponse * describeChannel(const DescribeChannelRequest &request);
    DescribeChannelBanResponse * describeChannelBan(const DescribeChannelBanRequest &request);
    DescribeChannelMembershipResponse * describeChannelMembership(const DescribeChannelMembershipRequest &request);
    DescribeChannelMembershipForAppInstanceUserResponse * describeChannelMembershipForAppInstanceUser(const DescribeChannelMembershipForAppInstanceUserRequest &request);
    DescribeChannelModeratedByAppInstanceUserResponse * describeChannelModeratedByAppInstanceUser(const DescribeChannelModeratedByAppInstanceUserRequest &request);
    DescribeChannelModeratorResponse * describeChannelModerator(const DescribeChannelModeratorRequest &request);
    DisassociatePhoneNumberFromUserResponse * disassociatePhoneNumberFromUser(const DisassociatePhoneNumberFromUserRequest &request);
    DisassociatePhoneNumbersFromVoiceConnectorResponse * disassociatePhoneNumbersFromVoiceConnector(const DisassociatePhoneNumbersFromVoiceConnectorRequest &request);
    DisassociatePhoneNumbersFromVoiceConnectorGroupResponse * disassociatePhoneNumbersFromVoiceConnectorGroup(const DisassociatePhoneNumbersFromVoiceConnectorGroupRequest &request);
    DisassociateSigninDelegateGroupsFromAccountResponse * disassociateSigninDelegateGroupsFromAccount(const DisassociateSigninDelegateGroupsFromAccountRequest &request);
    GetAccountResponse * getAccount(const GetAccountRequest &request);
    GetAccountSettingsResponse * getAccountSettings(const GetAccountSettingsRequest &request);
    GetAppInstanceRetentionSettingsResponse * getAppInstanceRetentionSettings(const GetAppInstanceRetentionSettingsRequest &request);
    GetAppInstanceStreamingConfigurationsResponse * getAppInstanceStreamingConfigurations(const GetAppInstanceStreamingConfigurationsRequest &request);
    GetAttendeeResponse * getAttendee(const GetAttendeeRequest &request);
    GetBotResponse * getBot(const GetBotRequest &request);
    GetChannelMessageResponse * getChannelMessage(const GetChannelMessageRequest &request);
    GetEventsConfigurationResponse * getEventsConfiguration(const GetEventsConfigurationRequest &request);
    GetGlobalSettingsResponse * getGlobalSettings(const GetGlobalSettingsRequest &request);
    GetGlobalSettingsResponse * getGlobalSettings();
    GetMeetingResponse * getMeeting(const GetMeetingRequest &request);
    GetMessagingSessionEndpointResponse * getMessagingSessionEndpoint(const GetMessagingSessionEndpointRequest &request);
    GetPhoneNumberResponse * getPhoneNumber(const GetPhoneNumberRequest &request);
    GetPhoneNumberOrderResponse * getPhoneNumberOrder(const GetPhoneNumberOrderRequest &request);
    GetPhoneNumberSettingsResponse * getPhoneNumberSettings(const GetPhoneNumberSettingsRequest &request);
    GetPhoneNumberSettingsResponse * getPhoneNumberSettings();
    GetProxySessionResponse * getProxySession(const GetProxySessionRequest &request);
    GetRetentionSettingsResponse * getRetentionSettings(const GetRetentionSettingsRequest &request);
    GetRoomResponse * getRoom(const GetRoomRequest &request);
    GetSipMediaApplicationResponse * getSipMediaApplication(const GetSipMediaApplicationRequest &request);
    GetSipMediaApplicationLoggingConfigurationResponse * getSipMediaApplicationLoggingConfiguration(const GetSipMediaApplicationLoggingConfigurationRequest &request);
    GetSipRuleResponse * getSipRule(const GetSipRuleRequest &request);
    GetUserResponse * getUser(const GetUserRequest &request);
    GetUserSettingsResponse * getUserSettings(const GetUserSettingsRequest &request);
    GetVoiceConnectorResponse * getVoiceConnector(const GetVoiceConnectorRequest &request);
    GetVoiceConnectorEmergencyCallingConfigurationResponse * getVoiceConnectorEmergencyCallingConfiguration(const GetVoiceConnectorEmergencyCallingConfigurationRequest &request);
    GetVoiceConnectorGroupResponse * getVoiceConnectorGroup(const GetVoiceConnectorGroupRequest &request);
    GetVoiceConnectorLoggingConfigurationResponse * getVoiceConnectorLoggingConfiguration(const GetVoiceConnectorLoggingConfigurationRequest &request);
    GetVoiceConnectorOriginationResponse * getVoiceConnectorOrigination(const GetVoiceConnectorOriginationRequest &request);
    GetVoiceConnectorProxyResponse * getVoiceConnectorProxy(const GetVoiceConnectorProxyRequest &request);
    GetVoiceConnectorStreamingConfigurationResponse * getVoiceConnectorStreamingConfiguration(const GetVoiceConnectorStreamingConfigurationRequest &request);
    GetVoiceConnectorTerminationResponse * getVoiceConnectorTermination(const GetVoiceConnectorTerminationRequest &request);
    GetVoiceConnectorTerminationHealthResponse * getVoiceConnectorTerminationHealth(const GetVoiceConnectorTerminationHealthRequest &request);
    InviteUsersResponse * inviteUsers(const InviteUsersRequest &request);
    ListAccountsResponse * listAccounts(const ListAccountsRequest &request);
    ListAppInstanceAdminsResponse * listAppInstanceAdmins(const ListAppInstanceAdminsRequest &request);
    ListAppInstanceUsersResponse * listAppInstanceUsers(const ListAppInstanceUsersRequest &request);
    ListAppInstancesResponse * listAppInstances(const ListAppInstancesRequest &request);
    ListAttendeeTagsResponse * listAttendeeTags(const ListAttendeeTagsRequest &request);
    ListAttendeesResponse * listAttendees(const ListAttendeesRequest &request);
    ListBotsResponse * listBots(const ListBotsRequest &request);
    ListChannelBansResponse * listChannelBans(const ListChannelBansRequest &request);
    ListChannelMembershipsResponse * listChannelMemberships(const ListChannelMembershipsRequest &request);
    ListChannelMembershipsForAppInstanceUserResponse * listChannelMembershipsForAppInstanceUser(const ListChannelMembershipsForAppInstanceUserRequest &request);
    ListChannelMessagesResponse * listChannelMessages(const ListChannelMessagesRequest &request);
    ListChannelModeratorsResponse * listChannelModerators(const ListChannelModeratorsRequest &request);
    ListChannelsResponse * listChannels(const ListChannelsRequest &request);
    ListChannelsModeratedByAppInstanceUserResponse * listChannelsModeratedByAppInstanceUser(const ListChannelsModeratedByAppInstanceUserRequest &request);
    ListMeetingTagsResponse * listMeetingTags(const ListMeetingTagsRequest &request);
    ListMeetingsResponse * listMeetings(const ListMeetingsRequest &request);
    ListPhoneNumberOrdersResponse * listPhoneNumberOrders(const ListPhoneNumberOrdersRequest &request);
    ListPhoneNumbersResponse * listPhoneNumbers(const ListPhoneNumbersRequest &request);
    ListProxySessionsResponse * listProxySessions(const ListProxySessionsRequest &request);
    ListRoomMembershipsResponse * listRoomMemberships(const ListRoomMembershipsRequest &request);
    ListRoomsResponse * listRooms(const ListRoomsRequest &request);
    ListSipMediaApplicationsResponse * listSipMediaApplications(const ListSipMediaApplicationsRequest &request);
    ListSipRulesResponse * listSipRules(const ListSipRulesRequest &request);
    ListSupportedPhoneNumberCountriesResponse * listSupportedPhoneNumberCountries(const ListSupportedPhoneNumberCountriesRequest &request);
    ListTagsForResourceResponse * listTagsForResource(const ListTagsForResourceRequest &request);
    ListUsersResponse * listUsers(const ListUsersRequest &request);
    ListVoiceConnectorGroupsResponse * listVoiceConnectorGroups(const ListVoiceConnectorGroupsRequest &request);
    ListVoiceConnectorTerminationCredentialsResponse * listVoiceConnectorTerminationCredentials(const ListVoiceConnectorTerminationCredentialsRequest &request);
    ListVoiceConnectorsResponse * listVoiceConnectors(const ListVoiceConnectorsRequest &request);
    LogoutUserResponse * logoutUser(const LogoutUserRequest &request);
    PutAppInstanceRetentionSettingsResponse * putAppInstanceRetentionSettings(const PutAppInstanceRetentionSettingsRequest &request);
    PutAppInstanceStreamingConfigurationsResponse * putAppInstanceStreamingConfigurations(const PutAppInstanceStreamingConfigurationsRequest &request);
    PutEventsConfigurationResponse * putEventsConfiguration(const PutEventsConfigurationRequest &request);
    PutRetentionSettingsResponse * putRetentionSettings(const PutRetentionSettingsRequest &request);
    PutSipMediaApplicationLoggingConfigurationResponse * putSipMediaApplicationLoggingConfiguration(const PutSipMediaApplicationLoggingConfigurationRequest &request);
    PutVoiceConnectorEmergencyCallingConfigurationResponse * putVoiceConnectorEmergencyCallingConfiguration(const PutVoiceConnectorEmergencyCallingConfigurationRequest &request);
    PutVoiceConnectorLoggingConfigurationResponse * putVoiceConnectorLoggingConfiguration(const PutVoiceConnectorLoggingConfigurationRequest &request);
    PutVoiceConnectorOriginationResponse * putVoiceConnectorOrigination(const PutVoiceConnectorOriginationRequest &request);
    PutVoiceConnectorProxyResponse * putVoiceConnectorProxy(const PutVoiceConnectorProxyRequest &request);
    PutVoiceConnectorStreamingConfigurationResponse * putVoiceConnectorStreamingConfiguration(const PutVoiceConnectorStreamingConfigurationRequest &request);
    PutVoiceConnectorTerminationResponse * putVoiceConnectorTermination(const PutVoiceConnectorTerminationRequest &request);
    PutVoiceConnectorTerminationCredentialsResponse * putVoiceConnectorTerminationCredentials(const PutVoiceConnectorTerminationCredentialsRequest &request);
    RedactChannelMessageResponse * redactChannelMessage(const RedactChannelMessageRequest &request);
    RedactConversationMessageResponse * redactConversationMessage(const RedactConversationMessageRequest &request);
    RedactRoomMessageResponse * redactRoomMessage(const RedactRoomMessageRequest &request);
    RegenerateSecurityTokenResponse * regenerateSecurityToken(const RegenerateSecurityTokenRequest &request);
    ResetPersonalPINResponse * resetPersonalPIN(const ResetPersonalPINRequest &request);
    RestorePhoneNumberResponse * restorePhoneNumber(const RestorePhoneNumberRequest &request);
    SearchAvailablePhoneNumbersResponse * searchAvailablePhoneNumbers(const SearchAvailablePhoneNumbersRequest &request);
    SendChannelMessageResponse * sendChannelMessage(const SendChannelMessageRequest &request);
    TagAttendeeResponse * tagAttendee(const TagAttendeeRequest &request);
    TagMeetingResponse * tagMeeting(const TagMeetingRequest &request);
    TagResourceResponse * tagResource(const TagResourceRequest &request);
    UntagAttendeeResponse * untagAttendee(const UntagAttendeeRequest &request);
    UntagMeetingResponse * untagMeeting(const UntagMeetingRequest &request);
    UntagResourceResponse * untagResource(const UntagResourceRequest &request);
    UpdateAccountResponse * updateAccount(const UpdateAccountRequest &request);
    UpdateAccountSettingsResponse * updateAccountSettings(const UpdateAccountSettingsRequest &request);
    UpdateAppInstanceResponse * updateAppInstance(const UpdateAppInstanceRequest &request);
    UpdateAppInstanceUserResponse * updateAppInstanceUser(const UpdateAppInstanceUserRequest &request);
    UpdateBotResponse * updateBot(const UpdateBotRequest &request);
    UpdateChannelResponse * updateChannel(const UpdateChannelRequest &request);
    UpdateChannelMessageResponse * updateChannelMessage(const UpdateChannelMessageRequest &request);
    UpdateChannelReadMarkerResponse * updateChannelReadMarker(const UpdateChannelReadMarkerRequest &request);
    UpdateGlobalSettingsResponse * updateGlobalSettings(const UpdateGlobalSettingsRequest &request);
    UpdatePhoneNumberResponse * updatePhoneNumber(const UpdatePhoneNumberRequest &request);
    UpdatePhoneNumberSettingsResponse * updatePhoneNumberSettings(const UpdatePhoneNumberSettingsRequest &request);
    UpdateProxySessionResponse * updateProxySession(const UpdateProxySessionRequest &request);
    UpdateRoomResponse * updateRoom(const UpdateRoomRequest &request);
    UpdateRoomMembershipResponse * updateRoomMembership(const UpdateRoomMembershipRequest &request);
    UpdateSipMediaApplicationResponse * updateSipMediaApplication(const UpdateSipMediaApplicationRequest &request);
    UpdateSipRuleResponse * updateSipRule(const UpdateSipRuleRequest &request);
    UpdateUserResponse * updateUser(const UpdateUserRequest &request);
    UpdateUserSettingsResponse * updateUserSettings(const UpdateUserSettingsRequest &request);
    UpdateVoiceConnectorResponse * updateVoiceConnector(const UpdateVoiceConnectorRequest &request);
    UpdateVoiceConnectorGroupResponse * updateVoiceConnectorGroup(const UpdateVoiceConnectorGroupRequest &request);

protected:
    /// @cond internal
    ChimeClientPrivate * const d_ptr; ///< Internal d-pointer.
    explicit ChimeClient(ChimeClientPrivate * const d);
    /// @endcond

private:
    Q_DECLARE_PRIVATE(ChimeClient)
    Q_DISABLE_COPY(ChimeClient)

};

} // namespace Chime
} // namespace QtAws

#endif
