include(../../common.pri)

TARGET = elasticache
TEMPLATE = lib
QT -= gui
QT += network
DEFINES += QTAWS_LIBRARY
DEFINES += QT_NO_CAST_FROM_ASCII QT_NO_CAST_TO_ASCII

INCLUDEPATH = $$TOPDIR/src

HEADERS += \
    addtagstoresourcerequest.h \
    addtagstoresourcerequest_p.h \
    addtagstoresourceresponse.h \
    addtagstoresourceresponse_p.h \
    authorizecachesecuritygroupingressrequest.h \
    authorizecachesecuritygroupingressrequest_p.h \
    authorizecachesecuritygroupingressresponse.h \
    authorizecachesecuritygroupingressresponse_p.h \
    copysnapshotrequest.h \
    copysnapshotrequest_p.h \
    copysnapshotresponse.h \
    copysnapshotresponse_p.h \
    createcacheclusterrequest.h \
    createcacheclusterrequest_p.h \
    createcacheclusterresponse.h \
    createcacheclusterresponse_p.h \
    createcacheparametergrouprequest.h \
    createcacheparametergrouprequest_p.h \
    createcacheparametergroupresponse.h \
    createcacheparametergroupresponse_p.h \
    createcachesecuritygrouprequest.h \
    createcachesecuritygrouprequest_p.h \
    createcachesecuritygroupresponse.h \
    createcachesecuritygroupresponse_p.h \
    createcachesubnetgrouprequest.h \
    createcachesubnetgrouprequest_p.h \
    createcachesubnetgroupresponse.h \
    createcachesubnetgroupresponse_p.h \
    createreplicationgrouprequest.h \
    createreplicationgrouprequest_p.h \
    createreplicationgroupresponse.h \
    createreplicationgroupresponse_p.h \
    createsnapshotrequest.h \
    createsnapshotrequest_p.h \
    createsnapshotresponse.h \
    createsnapshotresponse_p.h \
    deletecacheclusterrequest.h \
    deletecacheclusterrequest_p.h \
    deletecacheclusterresponse.h \
    deletecacheclusterresponse_p.h \
    deletecacheparametergrouprequest.h \
    deletecacheparametergrouprequest_p.h \
    deletecacheparametergroupresponse.h \
    deletecacheparametergroupresponse_p.h \
    deletecachesecuritygrouprequest.h \
    deletecachesecuritygrouprequest_p.h \
    deletecachesecuritygroupresponse.h \
    deletecachesecuritygroupresponse_p.h \
    deletecachesubnetgrouprequest.h \
    deletecachesubnetgrouprequest_p.h \
    deletecachesubnetgroupresponse.h \
    deletecachesubnetgroupresponse_p.h \
    deletereplicationgrouprequest.h \
    deletereplicationgrouprequest_p.h \
    deletereplicationgroupresponse.h \
    deletereplicationgroupresponse_p.h \
    deletesnapshotrequest.h \
    deletesnapshotrequest_p.h \
    deletesnapshotresponse.h \
    deletesnapshotresponse_p.h \
    describecacheclustersrequest.h \
    describecacheclustersrequest_p.h \
    describecacheclustersresponse.h \
    describecacheclustersresponse_p.h \
    describecacheengineversionsrequest.h \
    describecacheengineversionsrequest_p.h \
    describecacheengineversionsresponse.h \
    describecacheengineversionsresponse_p.h \
    describecacheparametergroupsrequest.h \
    describecacheparametergroupsrequest_p.h \
    describecacheparametergroupsresponse.h \
    describecacheparametergroupsresponse_p.h \
    describecacheparametersrequest.h \
    describecacheparametersrequest_p.h \
    describecacheparametersresponse.h \
    describecacheparametersresponse_p.h \
    describecachesecuritygroupsrequest.h \
    describecachesecuritygroupsrequest_p.h \
    describecachesecuritygroupsresponse.h \
    describecachesecuritygroupsresponse_p.h \
    describecachesubnetgroupsrequest.h \
    describecachesubnetgroupsrequest_p.h \
    describecachesubnetgroupsresponse.h \
    describecachesubnetgroupsresponse_p.h \
    describeenginedefaultparametersrequest.h \
    describeenginedefaultparametersrequest_p.h \
    describeenginedefaultparametersresponse.h \
    describeenginedefaultparametersresponse_p.h \
    describeeventsrequest.h \
    describeeventsrequest_p.h \
    describeeventsresponse.h \
    describeeventsresponse_p.h \
    describereplicationgroupsrequest.h \
    describereplicationgroupsrequest_p.h \
    describereplicationgroupsresponse.h \
    describereplicationgroupsresponse_p.h \
    describereservedcachenodesofferingsrequest.h \
    describereservedcachenodesofferingsrequest_p.h \
    describereservedcachenodesofferingsresponse.h \
    describereservedcachenodesofferingsresponse_p.h \
    describereservedcachenodesrequest.h \
    describereservedcachenodesrequest_p.h \
    describereservedcachenodesresponse.h \
    describereservedcachenodesresponse_p.h \
    describesnapshotsrequest.h \
    describesnapshotsrequest_p.h \
    describesnapshotsresponse.h \
    describesnapshotsresponse_p.h \
    elasticacheclient.h \
    elasticacheclient_p.h \
    elasticacherequest.h \
    elasticacherequest_p.h \
    elasticacheresponse.h \
    elasticacheresponse_p.h \
    listallowednodetypemodificationsrequest.h \
    listallowednodetypemodificationsrequest_p.h \
    listallowednodetypemodificationsresponse.h \
    listallowednodetypemodificationsresponse_p.h \
    listtagsforresourcerequest.h \
    listtagsforresourcerequest_p.h \
    listtagsforresourceresponse.h \
    listtagsforresourceresponse_p.h \
    modifycacheclusterrequest.h \
    modifycacheclusterrequest_p.h \
    modifycacheclusterresponse.h \
    modifycacheclusterresponse_p.h \
    modifycacheparametergrouprequest.h \
    modifycacheparametergrouprequest_p.h \
    modifycacheparametergroupresponse.h \
    modifycacheparametergroupresponse_p.h \
    modifycachesubnetgrouprequest.h \
    modifycachesubnetgrouprequest_p.h \
    modifycachesubnetgroupresponse.h \
    modifycachesubnetgroupresponse_p.h \
    modifyreplicationgrouprequest.h \
    modifyreplicationgrouprequest_p.h \
    modifyreplicationgroupresponse.h \
    modifyreplicationgroupresponse_p.h \
    modifyreplicationgroupshardconfigurationrequest.h \
    modifyreplicationgroupshardconfigurationrequest_p.h \
    modifyreplicationgroupshardconfigurationresponse.h \
    modifyreplicationgroupshardconfigurationresponse_p.h \
    purchasereservedcachenodesofferingrequest.h \
    purchasereservedcachenodesofferingrequest_p.h \
    purchasereservedcachenodesofferingresponse.h \
    purchasereservedcachenodesofferingresponse_p.h \
    rebootcacheclusterrequest.h \
    rebootcacheclusterrequest_p.h \
    rebootcacheclusterresponse.h \
    rebootcacheclusterresponse_p.h \
    removetagsfromresourcerequest.h \
    removetagsfromresourcerequest_p.h \
    removetagsfromresourceresponse.h \
    removetagsfromresourceresponse_p.h \
    resetcacheparametergrouprequest.h \
    resetcacheparametergrouprequest_p.h \
    resetcacheparametergroupresponse.h \
    resetcacheparametergroupresponse_p.h \
    revokecachesecuritygroupingressrequest.h \
    revokecachesecuritygroupingressrequest_p.h \
    revokecachesecuritygroupingressresponse.h \
    revokecachesecuritygroupingressresponse_p.h \
    testfailoverrequest.h \
    testfailoverrequest_p.h \
    testfailoverresponse.h \
    testfailoverresponse_p.h \

SOURCES += \
    addtagstoresourcerequest.cpp \
    addtagstoresourceresponse.cpp \
    authorizecachesecuritygroupingressrequest.cpp \
    authorizecachesecuritygroupingressresponse.cpp \
    copysnapshotrequest.cpp \
    copysnapshotresponse.cpp \
    createcacheclusterrequest.cpp \
    createcacheclusterresponse.cpp \
    createcacheparametergrouprequest.cpp \
    createcacheparametergroupresponse.cpp \
    createcachesecuritygrouprequest.cpp \
    createcachesecuritygroupresponse.cpp \
    createcachesubnetgrouprequest.cpp \
    createcachesubnetgroupresponse.cpp \
    createreplicationgrouprequest.cpp \
    createreplicationgroupresponse.cpp \
    createsnapshotrequest.cpp \
    createsnapshotresponse.cpp \
    deletecacheclusterrequest.cpp \
    deletecacheclusterresponse.cpp \
    deletecacheparametergrouprequest.cpp \
    deletecacheparametergroupresponse.cpp \
    deletecachesecuritygrouprequest.cpp \
    deletecachesecuritygroupresponse.cpp \
    deletecachesubnetgrouprequest.cpp \
    deletecachesubnetgroupresponse.cpp \
    deletereplicationgrouprequest.cpp \
    deletereplicationgroupresponse.cpp \
    deletesnapshotrequest.cpp \
    deletesnapshotresponse.cpp \
    describecacheclustersrequest.cpp \
    describecacheclustersresponse.cpp \
    describecacheengineversionsrequest.cpp \
    describecacheengineversionsresponse.cpp \
    describecacheparametergroupsrequest.cpp \
    describecacheparametergroupsresponse.cpp \
    describecacheparametersrequest.cpp \
    describecacheparametersresponse.cpp \
    describecachesecuritygroupsrequest.cpp \
    describecachesecuritygroupsresponse.cpp \
    describecachesubnetgroupsrequest.cpp \
    describecachesubnetgroupsresponse.cpp \
    describeenginedefaultparametersrequest.cpp \
    describeenginedefaultparametersresponse.cpp \
    describeeventsrequest.cpp \
    describeeventsresponse.cpp \
    describereplicationgroupsrequest.cpp \
    describereplicationgroupsresponse.cpp \
    describereservedcachenodesofferingsrequest.cpp \
    describereservedcachenodesofferingsresponse.cpp \
    describereservedcachenodesrequest.cpp \
    describereservedcachenodesresponse.cpp \
    describesnapshotsrequest.cpp \
    describesnapshotsresponse.cpp \
    elasticacheclient.cpp \
    elasticacherequest.cpp \
    elasticacheresponse.cpp \
    listallowednodetypemodificationsrequest.cpp \
    listallowednodetypemodificationsresponse.cpp \
    listtagsforresourcerequest.cpp \
    listtagsforresourceresponse.cpp \
    modifycacheclusterrequest.cpp \
    modifycacheclusterresponse.cpp \
    modifycacheparametergrouprequest.cpp \
    modifycacheparametergroupresponse.cpp \
    modifycachesubnetgrouprequest.cpp \
    modifycachesubnetgroupresponse.cpp \
    modifyreplicationgrouprequest.cpp \
    modifyreplicationgroupresponse.cpp \
    modifyreplicationgroupshardconfigurationrequest.cpp \
    modifyreplicationgroupshardconfigurationresponse.cpp \
    purchasereservedcachenodesofferingrequest.cpp \
    purchasereservedcachenodesofferingresponse.cpp \
    rebootcacheclusterrequest.cpp \
    rebootcacheclusterresponse.cpp \
    removetagsfromresourcerequest.cpp \
    removetagsfromresourceresponse.cpp \
    resetcacheparametergrouprequest.cpp \
    resetcacheparametergroupresponse.cpp \
    revokecachesecuritygroupingressrequest.cpp \
    revokecachesecuritygroupingressresponse.cpp \
    testfailoverrequest.cpp \
    testfailoverresponse.cpp \

win32:CONFIG += skip_target_version_ext
