include(../../common.pri)

TARGET = redshift
TEMPLATE = lib
QT -= gui
QT += network
DEFINES += QTAWS_LIBRARY
DEFINES += QT_NO_CAST_FROM_ASCII QT_NO_CAST_TO_ASCII

INCLUDEPATH = $$TOPDIR/src

HEADERS += \
    authorizeclustersecuritygroupingressrequest.h \
    authorizeclustersecuritygroupingressrequest_p.h \
    authorizeclustersecuritygroupingressresponse.h \
    authorizeclustersecuritygroupingressresponse_p.h \
    authorizesnapshotaccessrequest.h \
    authorizesnapshotaccessrequest_p.h \
    authorizesnapshotaccessresponse.h \
    authorizesnapshotaccessresponse_p.h \
    copyclustersnapshotrequest.h \
    copyclustersnapshotrequest_p.h \
    copyclustersnapshotresponse.h \
    copyclustersnapshotresponse_p.h \
    createclusterparametergrouprequest.h \
    createclusterparametergrouprequest_p.h \
    createclusterparametergroupresponse.h \
    createclusterparametergroupresponse_p.h \
    createclusterrequest.h \
    createclusterrequest_p.h \
    createclusterresponse.h \
    createclusterresponse_p.h \
    createclustersecuritygrouprequest.h \
    createclustersecuritygrouprequest_p.h \
    createclustersecuritygroupresponse.h \
    createclustersecuritygroupresponse_p.h \
    createclustersnapshotrequest.h \
    createclustersnapshotrequest_p.h \
    createclustersnapshotresponse.h \
    createclustersnapshotresponse_p.h \
    createclustersubnetgrouprequest.h \
    createclustersubnetgrouprequest_p.h \
    createclustersubnetgroupresponse.h \
    createclustersubnetgroupresponse_p.h \
    createeventsubscriptionrequest.h \
    createeventsubscriptionrequest_p.h \
    createeventsubscriptionresponse.h \
    createeventsubscriptionresponse_p.h \
    createhsmclientcertificaterequest.h \
    createhsmclientcertificaterequest_p.h \
    createhsmclientcertificateresponse.h \
    createhsmclientcertificateresponse_p.h \
    createhsmconfigurationrequest.h \
    createhsmconfigurationrequest_p.h \
    createhsmconfigurationresponse.h \
    createhsmconfigurationresponse_p.h \
    createsnapshotcopygrantrequest.h \
    createsnapshotcopygrantrequest_p.h \
    createsnapshotcopygrantresponse.h \
    createsnapshotcopygrantresponse_p.h \
    createtagsrequest.h \
    createtagsrequest_p.h \
    createtagsresponse.h \
    createtagsresponse_p.h \
    deleteclusterparametergrouprequest.h \
    deleteclusterparametergrouprequest_p.h \
    deleteclusterparametergroupresponse.h \
    deleteclusterparametergroupresponse_p.h \
    deleteclusterrequest.h \
    deleteclusterrequest_p.h \
    deleteclusterresponse.h \
    deleteclusterresponse_p.h \
    deleteclustersecuritygrouprequest.h \
    deleteclustersecuritygrouprequest_p.h \
    deleteclustersecuritygroupresponse.h \
    deleteclustersecuritygroupresponse_p.h \
    deleteclustersnapshotrequest.h \
    deleteclustersnapshotrequest_p.h \
    deleteclustersnapshotresponse.h \
    deleteclustersnapshotresponse_p.h \
    deleteclustersubnetgrouprequest.h \
    deleteclustersubnetgrouprequest_p.h \
    deleteclustersubnetgroupresponse.h \
    deleteclustersubnetgroupresponse_p.h \
    deleteeventsubscriptionrequest.h \
    deleteeventsubscriptionrequest_p.h \
    deleteeventsubscriptionresponse.h \
    deleteeventsubscriptionresponse_p.h \
    deletehsmclientcertificaterequest.h \
    deletehsmclientcertificaterequest_p.h \
    deletehsmclientcertificateresponse.h \
    deletehsmclientcertificateresponse_p.h \
    deletehsmconfigurationrequest.h \
    deletehsmconfigurationrequest_p.h \
    deletehsmconfigurationresponse.h \
    deletehsmconfigurationresponse_p.h \
    deletesnapshotcopygrantrequest.h \
    deletesnapshotcopygrantrequest_p.h \
    deletesnapshotcopygrantresponse.h \
    deletesnapshotcopygrantresponse_p.h \
    deletetagsrequest.h \
    deletetagsrequest_p.h \
    deletetagsresponse.h \
    deletetagsresponse_p.h \
    describeclusterparametergroupsrequest.h \
    describeclusterparametergroupsrequest_p.h \
    describeclusterparametergroupsresponse.h \
    describeclusterparametergroupsresponse_p.h \
    describeclusterparametersrequest.h \
    describeclusterparametersrequest_p.h \
    describeclusterparametersresponse.h \
    describeclusterparametersresponse_p.h \
    describeclustersecuritygroupsrequest.h \
    describeclustersecuritygroupsrequest_p.h \
    describeclustersecuritygroupsresponse.h \
    describeclustersecuritygroupsresponse_p.h \
    describeclustersnapshotsrequest.h \
    describeclustersnapshotsrequest_p.h \
    describeclustersnapshotsresponse.h \
    describeclustersnapshotsresponse_p.h \
    describeclustersrequest.h \
    describeclustersrequest_p.h \
    describeclustersresponse.h \
    describeclustersresponse_p.h \
    describeclustersubnetgroupsrequest.h \
    describeclustersubnetgroupsrequest_p.h \
    describeclustersubnetgroupsresponse.h \
    describeclustersubnetgroupsresponse_p.h \
    describeclusterversionsrequest.h \
    describeclusterversionsrequest_p.h \
    describeclusterversionsresponse.h \
    describeclusterversionsresponse_p.h \
    describedefaultclusterparametersrequest.h \
    describedefaultclusterparametersrequest_p.h \
    describedefaultclusterparametersresponse.h \
    describedefaultclusterparametersresponse_p.h \
    describeeventcategoriesrequest.h \
    describeeventcategoriesrequest_p.h \
    describeeventcategoriesresponse.h \
    describeeventcategoriesresponse_p.h \
    describeeventsrequest.h \
    describeeventsrequest_p.h \
    describeeventsresponse.h \
    describeeventsresponse_p.h \
    describeeventsubscriptionsrequest.h \
    describeeventsubscriptionsrequest_p.h \
    describeeventsubscriptionsresponse.h \
    describeeventsubscriptionsresponse_p.h \
    describehsmclientcertificatesrequest.h \
    describehsmclientcertificatesrequest_p.h \
    describehsmclientcertificatesresponse.h \
    describehsmclientcertificatesresponse_p.h \
    describehsmconfigurationsrequest.h \
    describehsmconfigurationsrequest_p.h \
    describehsmconfigurationsresponse.h \
    describehsmconfigurationsresponse_p.h \
    describeloggingstatusrequest.h \
    describeloggingstatusrequest_p.h \
    describeloggingstatusresponse.h \
    describeloggingstatusresponse_p.h \
    describeorderableclusteroptionsrequest.h \
    describeorderableclusteroptionsrequest_p.h \
    describeorderableclusteroptionsresponse.h \
    describeorderableclusteroptionsresponse_p.h \
    describereservednodeofferingsrequest.h \
    describereservednodeofferingsrequest_p.h \
    describereservednodeofferingsresponse.h \
    describereservednodeofferingsresponse_p.h \
    describereservednodesrequest.h \
    describereservednodesrequest_p.h \
    describereservednodesresponse.h \
    describereservednodesresponse_p.h \
    describeresizerequest.h \
    describeresizerequest_p.h \
    describeresizeresponse.h \
    describeresizeresponse_p.h \
    describesnapshotcopygrantsrequest.h \
    describesnapshotcopygrantsrequest_p.h \
    describesnapshotcopygrantsresponse.h \
    describesnapshotcopygrantsresponse_p.h \
    describetablerestorestatusrequest.h \
    describetablerestorestatusrequest_p.h \
    describetablerestorestatusresponse.h \
    describetablerestorestatusresponse_p.h \
    describetagsrequest.h \
    describetagsrequest_p.h \
    describetagsresponse.h \
    describetagsresponse_p.h \
    disableloggingrequest.h \
    disableloggingrequest_p.h \
    disableloggingresponse.h \
    disableloggingresponse_p.h \
    disablesnapshotcopyrequest.h \
    disablesnapshotcopyrequest_p.h \
    disablesnapshotcopyresponse.h \
    disablesnapshotcopyresponse_p.h \
    enableloggingrequest.h \
    enableloggingrequest_p.h \
    enableloggingresponse.h \
    enableloggingresponse_p.h \
    enablesnapshotcopyrequest.h \
    enablesnapshotcopyrequest_p.h \
    enablesnapshotcopyresponse.h \
    enablesnapshotcopyresponse_p.h \
    getclustercredentialsrequest.h \
    getclustercredentialsrequest_p.h \
    getclustercredentialsresponse.h \
    getclustercredentialsresponse_p.h \
    modifyclusteriamrolesrequest.h \
    modifyclusteriamrolesrequest_p.h \
    modifyclusteriamrolesresponse.h \
    modifyclusteriamrolesresponse_p.h \
    modifyclusterparametergrouprequest.h \
    modifyclusterparametergrouprequest_p.h \
    modifyclusterparametergroupresponse.h \
    modifyclusterparametergroupresponse_p.h \
    modifyclusterrequest.h \
    modifyclusterrequest_p.h \
    modifyclusterresponse.h \
    modifyclusterresponse_p.h \
    modifyclustersubnetgrouprequest.h \
    modifyclustersubnetgrouprequest_p.h \
    modifyclustersubnetgroupresponse.h \
    modifyclustersubnetgroupresponse_p.h \
    modifyeventsubscriptionrequest.h \
    modifyeventsubscriptionrequest_p.h \
    modifyeventsubscriptionresponse.h \
    modifyeventsubscriptionresponse_p.h \
    modifysnapshotcopyretentionperiodrequest.h \
    modifysnapshotcopyretentionperiodrequest_p.h \
    modifysnapshotcopyretentionperiodresponse.h \
    modifysnapshotcopyretentionperiodresponse_p.h \
    purchasereservednodeofferingrequest.h \
    purchasereservednodeofferingrequest_p.h \
    purchasereservednodeofferingresponse.h \
    purchasereservednodeofferingresponse_p.h \
    rebootclusterrequest.h \
    rebootclusterrequest_p.h \
    rebootclusterresponse.h \
    rebootclusterresponse_p.h \
    redshiftclient.h \
    redshiftclient_p.h \
    resetclusterparametergrouprequest.h \
    resetclusterparametergrouprequest_p.h \
    resetclusterparametergroupresponse.h \
    resetclusterparametergroupresponse_p.h \
    restorefromclustersnapshotrequest.h \
    restorefromclustersnapshotrequest_p.h \
    restorefromclustersnapshotresponse.h \
    restorefromclustersnapshotresponse_p.h \
    restoretablefromclustersnapshotrequest.h \
    restoretablefromclustersnapshotrequest_p.h \
    restoretablefromclustersnapshotresponse.h \
    restoretablefromclustersnapshotresponse_p.h \
    revokeclustersecuritygroupingressrequest.h \
    revokeclustersecuritygroupingressrequest_p.h \
    revokeclustersecuritygroupingressresponse.h \
    revokeclustersecuritygroupingressresponse_p.h \
    revokesnapshotaccessrequest.h \
    revokesnapshotaccessrequest_p.h \
    revokesnapshotaccessresponse.h \
    revokesnapshotaccessresponse_p.h \
    rotateencryptionkeyrequest.h \
    rotateencryptionkeyrequest_p.h \
    rotateencryptionkeyresponse.h \
    rotateencryptionkeyresponse_p.h \

SOURCES += \
    authorizeclustersecuritygroupingressrequest.cpp \
    authorizeclustersecuritygroupingressresponse.cpp \
    authorizesnapshotaccessrequest.cpp \
    authorizesnapshotaccessresponse.cpp \
    copyclustersnapshotrequest.cpp \
    copyclustersnapshotresponse.cpp \
    createclusterparametergrouprequest.cpp \
    createclusterparametergroupresponse.cpp \
    createclusterrequest.cpp \
    createclusterresponse.cpp \
    createclustersecuritygrouprequest.cpp \
    createclustersecuritygroupresponse.cpp \
    createclustersnapshotrequest.cpp \
    createclustersnapshotresponse.cpp \
    createclustersubnetgrouprequest.cpp \
    createclustersubnetgroupresponse.cpp \
    createeventsubscriptionrequest.cpp \
    createeventsubscriptionresponse.cpp \
    createhsmclientcertificaterequest.cpp \
    createhsmclientcertificateresponse.cpp \
    createhsmconfigurationrequest.cpp \
    createhsmconfigurationresponse.cpp \
    createsnapshotcopygrantrequest.cpp \
    createsnapshotcopygrantresponse.cpp \
    createtagsrequest.cpp \
    createtagsresponse.cpp \
    deleteclusterparametergrouprequest.cpp \
    deleteclusterparametergroupresponse.cpp \
    deleteclusterrequest.cpp \
    deleteclusterresponse.cpp \
    deleteclustersecuritygrouprequest.cpp \
    deleteclustersecuritygroupresponse.cpp \
    deleteclustersnapshotrequest.cpp \
    deleteclustersnapshotresponse.cpp \
    deleteclustersubnetgrouprequest.cpp \
    deleteclustersubnetgroupresponse.cpp \
    deleteeventsubscriptionrequest.cpp \
    deleteeventsubscriptionresponse.cpp \
    deletehsmclientcertificaterequest.cpp \
    deletehsmclientcertificateresponse.cpp \
    deletehsmconfigurationrequest.cpp \
    deletehsmconfigurationresponse.cpp \
    deletesnapshotcopygrantrequest.cpp \
    deletesnapshotcopygrantresponse.cpp \
    deletetagsrequest.cpp \
    deletetagsresponse.cpp \
    describeclusterparametergroupsrequest.cpp \
    describeclusterparametergroupsresponse.cpp \
    describeclusterparametersrequest.cpp \
    describeclusterparametersresponse.cpp \
    describeclustersecuritygroupsrequest.cpp \
    describeclustersecuritygroupsresponse.cpp \
    describeclustersnapshotsrequest.cpp \
    describeclustersnapshotsresponse.cpp \
    describeclustersrequest.cpp \
    describeclustersresponse.cpp \
    describeclustersubnetgroupsrequest.cpp \
    describeclustersubnetgroupsresponse.cpp \
    describeclusterversionsrequest.cpp \
    describeclusterversionsresponse.cpp \
    describedefaultclusterparametersrequest.cpp \
    describedefaultclusterparametersresponse.cpp \
    describeeventcategoriesrequest.cpp \
    describeeventcategoriesresponse.cpp \
    describeeventsrequest.cpp \
    describeeventsresponse.cpp \
    describeeventsubscriptionsrequest.cpp \
    describeeventsubscriptionsresponse.cpp \
    describehsmclientcertificatesrequest.cpp \
    describehsmclientcertificatesresponse.cpp \
    describehsmconfigurationsrequest.cpp \
    describehsmconfigurationsresponse.cpp \
    describeloggingstatusrequest.cpp \
    describeloggingstatusresponse.cpp \
    describeorderableclusteroptionsrequest.cpp \
    describeorderableclusteroptionsresponse.cpp \
    describereservednodeofferingsrequest.cpp \
    describereservednodeofferingsresponse.cpp \
    describereservednodesrequest.cpp \
    describereservednodesresponse.cpp \
    describeresizerequest.cpp \
    describeresizeresponse.cpp \
    describesnapshotcopygrantsrequest.cpp \
    describesnapshotcopygrantsresponse.cpp \
    describetablerestorestatusrequest.cpp \
    describetablerestorestatusresponse.cpp \
    describetagsrequest.cpp \
    describetagsresponse.cpp \
    disableloggingrequest.cpp \
    disableloggingresponse.cpp \
    disablesnapshotcopyrequest.cpp \
    disablesnapshotcopyresponse.cpp \
    enableloggingrequest.cpp \
    enableloggingresponse.cpp \
    enablesnapshotcopyrequest.cpp \
    enablesnapshotcopyresponse.cpp \
    getclustercredentialsrequest.cpp \
    getclustercredentialsresponse.cpp \
    modifyclusteriamrolesrequest.cpp \
    modifyclusteriamrolesresponse.cpp \
    modifyclusterparametergrouprequest.cpp \
    modifyclusterparametergroupresponse.cpp \
    modifyclusterrequest.cpp \
    modifyclusterresponse.cpp \
    modifyclustersubnetgrouprequest.cpp \
    modifyclustersubnetgroupresponse.cpp \
    modifyeventsubscriptionrequest.cpp \
    modifyeventsubscriptionresponse.cpp \
    modifysnapshotcopyretentionperiodrequest.cpp \
    modifysnapshotcopyretentionperiodresponse.cpp \
    purchasereservednodeofferingrequest.cpp \
    purchasereservednodeofferingresponse.cpp \
    rebootclusterrequest.cpp \
    rebootclusterresponse.cpp \
    redshiftclient.cpp \
    resetclusterparametergrouprequest.cpp \
    resetclusterparametergroupresponse.cpp \
    restorefromclustersnapshotrequest.cpp \
    restorefromclustersnapshotresponse.cpp \
    restoretablefromclustersnapshotrequest.cpp \
    restoretablefromclustersnapshotresponse.cpp \
    revokeclustersecuritygroupingressrequest.cpp \
    revokeclustersecuritygroupingressresponse.cpp \
    revokesnapshotaccessrequest.cpp \
    revokesnapshotaccessresponse.cpp \
    rotateencryptionkeyrequest.cpp \
    rotateencryptionkeyresponse.cpp \

win32:CONFIG += skip_target_version_ext
