include(../../common.pri)

TARGET = rds
TEMPLATE = lib
QT -= gui
QT += network
DEFINES += QTAWS_LIBRARY
DEFINES += QT_NO_CAST_FROM_ASCII QT_NO_CAST_TO_ASCII

INCLUDEPATH = $$TOPDIR/src

HEADERS += \
    addroletodbclusterrequest.h \
    addroletodbclusterrequest_p.h \
    addroletodbclusterresponse.h \
    addroletodbclusterresponse_p.h \
    addsourceidentifiertosubscriptionrequest.h \
    addsourceidentifiertosubscriptionrequest_p.h \
    addsourceidentifiertosubscriptionresponse.h \
    addsourceidentifiertosubscriptionresponse_p.h \
    addtagstoresourcerequest.h \
    addtagstoresourcerequest_p.h \
    addtagstoresourceresponse.h \
    addtagstoresourceresponse_p.h \
    applypendingmaintenanceactionrequest.h \
    applypendingmaintenanceactionrequest_p.h \
    applypendingmaintenanceactionresponse.h \
    applypendingmaintenanceactionresponse_p.h \
    authorizedbsecuritygroupingressrequest.h \
    authorizedbsecuritygroupingressrequest_p.h \
    authorizedbsecuritygroupingressresponse.h \
    authorizedbsecuritygroupingressresponse_p.h \
    copydbclusterparametergrouprequest.h \
    copydbclusterparametergrouprequest_p.h \
    copydbclusterparametergroupresponse.h \
    copydbclusterparametergroupresponse_p.h \
    copydbclustersnapshotrequest.h \
    copydbclustersnapshotrequest_p.h \
    copydbclustersnapshotresponse.h \
    copydbclustersnapshotresponse_p.h \
    copydbparametergrouprequest.h \
    copydbparametergrouprequest_p.h \
    copydbparametergroupresponse.h \
    copydbparametergroupresponse_p.h \
    copydbsnapshotrequest.h \
    copydbsnapshotrequest_p.h \
    copydbsnapshotresponse.h \
    copydbsnapshotresponse_p.h \
    copyoptiongrouprequest.h \
    copyoptiongrouprequest_p.h \
    copyoptiongroupresponse.h \
    copyoptiongroupresponse_p.h \
    createdbclusterparametergrouprequest.h \
    createdbclusterparametergrouprequest_p.h \
    createdbclusterparametergroupresponse.h \
    createdbclusterparametergroupresponse_p.h \
    createdbclusterrequest.h \
    createdbclusterrequest_p.h \
    createdbclusterresponse.h \
    createdbclusterresponse_p.h \
    createdbclustersnapshotrequest.h \
    createdbclustersnapshotrequest_p.h \
    createdbclustersnapshotresponse.h \
    createdbclustersnapshotresponse_p.h \
    createdbinstancereadreplicarequest.h \
    createdbinstancereadreplicarequest_p.h \
    createdbinstancereadreplicaresponse.h \
    createdbinstancereadreplicaresponse_p.h \
    createdbinstancerequest.h \
    createdbinstancerequest_p.h \
    createdbinstanceresponse.h \
    createdbinstanceresponse_p.h \
    createdbparametergrouprequest.h \
    createdbparametergrouprequest_p.h \
    createdbparametergroupresponse.h \
    createdbparametergroupresponse_p.h \
    createdbsecuritygrouprequest.h \
    createdbsecuritygrouprequest_p.h \
    createdbsecuritygroupresponse.h \
    createdbsecuritygroupresponse_p.h \
    createdbsnapshotrequest.h \
    createdbsnapshotrequest_p.h \
    createdbsnapshotresponse.h \
    createdbsnapshotresponse_p.h \
    createdbsubnetgrouprequest.h \
    createdbsubnetgrouprequest_p.h \
    createdbsubnetgroupresponse.h \
    createdbsubnetgroupresponse_p.h \
    createeventsubscriptionrequest.h \
    createeventsubscriptionrequest_p.h \
    createeventsubscriptionresponse.h \
    createeventsubscriptionresponse_p.h \
    createoptiongrouprequest.h \
    createoptiongrouprequest_p.h \
    createoptiongroupresponse.h \
    createoptiongroupresponse_p.h \
    deletedbclusterparametergrouprequest.h \
    deletedbclusterparametergrouprequest_p.h \
    deletedbclusterparametergroupresponse.h \
    deletedbclusterparametergroupresponse_p.h \
    deletedbclusterrequest.h \
    deletedbclusterrequest_p.h \
    deletedbclusterresponse.h \
    deletedbclusterresponse_p.h \
    deletedbclustersnapshotrequest.h \
    deletedbclustersnapshotrequest_p.h \
    deletedbclustersnapshotresponse.h \
    deletedbclustersnapshotresponse_p.h \
    deletedbinstancerequest.h \
    deletedbinstancerequest_p.h \
    deletedbinstanceresponse.h \
    deletedbinstanceresponse_p.h \
    deletedbparametergrouprequest.h \
    deletedbparametergrouprequest_p.h \
    deletedbparametergroupresponse.h \
    deletedbparametergroupresponse_p.h \
    deletedbsecuritygrouprequest.h \
    deletedbsecuritygrouprequest_p.h \
    deletedbsecuritygroupresponse.h \
    deletedbsecuritygroupresponse_p.h \
    deletedbsnapshotrequest.h \
    deletedbsnapshotrequest_p.h \
    deletedbsnapshotresponse.h \
    deletedbsnapshotresponse_p.h \
    deletedbsubnetgrouprequest.h \
    deletedbsubnetgrouprequest_p.h \
    deletedbsubnetgroupresponse.h \
    deletedbsubnetgroupresponse_p.h \
    deleteeventsubscriptionrequest.h \
    deleteeventsubscriptionrequest_p.h \
    deleteeventsubscriptionresponse.h \
    deleteeventsubscriptionresponse_p.h \
    deleteoptiongrouprequest.h \
    deleteoptiongrouprequest_p.h \
    deleteoptiongroupresponse.h \
    deleteoptiongroupresponse_p.h \
    describeaccountattributesrequest.h \
    describeaccountattributesrequest_p.h \
    describeaccountattributesresponse.h \
    describeaccountattributesresponse_p.h \
    describecertificatesrequest.h \
    describecertificatesrequest_p.h \
    describecertificatesresponse.h \
    describecertificatesresponse_p.h \
    describedbclusterparametergroupsrequest.h \
    describedbclusterparametergroupsrequest_p.h \
    describedbclusterparametergroupsresponse.h \
    describedbclusterparametergroupsresponse_p.h \
    describedbclusterparametersrequest.h \
    describedbclusterparametersrequest_p.h \
    describedbclusterparametersresponse.h \
    describedbclusterparametersresponse_p.h \
    describedbclustersnapshotattributesrequest.h \
    describedbclustersnapshotattributesrequest_p.h \
    describedbclustersnapshotattributesresponse.h \
    describedbclustersnapshotattributesresponse_p.h \
    describedbclustersnapshotsrequest.h \
    describedbclustersnapshotsrequest_p.h \
    describedbclustersnapshotsresponse.h \
    describedbclustersnapshotsresponse_p.h \
    describedbclustersrequest.h \
    describedbclustersrequest_p.h \
    describedbclustersresponse.h \
    describedbclustersresponse_p.h \
    describedbengineversionsrequest.h \
    describedbengineversionsrequest_p.h \
    describedbengineversionsresponse.h \
    describedbengineversionsresponse_p.h \
    describedbinstancesrequest.h \
    describedbinstancesrequest_p.h \
    describedbinstancesresponse.h \
    describedbinstancesresponse_p.h \
    describedblogfilesrequest.h \
    describedblogfilesrequest_p.h \
    describedblogfilesresponse.h \
    describedblogfilesresponse_p.h \
    describedbparametergroupsrequest.h \
    describedbparametergroupsrequest_p.h \
    describedbparametergroupsresponse.h \
    describedbparametergroupsresponse_p.h \
    describedbparametersrequest.h \
    describedbparametersrequest_p.h \
    describedbparametersresponse.h \
    describedbparametersresponse_p.h \
    describedbsecuritygroupsrequest.h \
    describedbsecuritygroupsrequest_p.h \
    describedbsecuritygroupsresponse.h \
    describedbsecuritygroupsresponse_p.h \
    describedbsnapshotattributesrequest.h \
    describedbsnapshotattributesrequest_p.h \
    describedbsnapshotattributesresponse.h \
    describedbsnapshotattributesresponse_p.h \
    describedbsnapshotsrequest.h \
    describedbsnapshotsrequest_p.h \
    describedbsnapshotsresponse.h \
    describedbsnapshotsresponse_p.h \
    describedbsubnetgroupsrequest.h \
    describedbsubnetgroupsrequest_p.h \
    describedbsubnetgroupsresponse.h \
    describedbsubnetgroupsresponse_p.h \
    describeenginedefaultclusterparametersrequest.h \
    describeenginedefaultclusterparametersrequest_p.h \
    describeenginedefaultclusterparametersresponse.h \
    describeenginedefaultclusterparametersresponse_p.h \
    describeenginedefaultparametersrequest.h \
    describeenginedefaultparametersrequest_p.h \
    describeenginedefaultparametersresponse.h \
    describeenginedefaultparametersresponse_p.h \
    describeeventcategoriesrequest.h \
    describeeventcategoriesrequest_p.h \
    describeeventcategoriesresponse.h \
    describeeventcategoriesresponse_p.h \
    describeeventsrequest.h \
    describeeventsrequest_p.h \
    describeeventsresponse.h \
    describeeventsresponse_p.h \
    describeeventsubscriptionsrequest.h \
    describeeventsubscriptionsrequest_p.h \
    describeeventsubscriptionsresponse.h \
    describeeventsubscriptionsresponse_p.h \
    describeoptiongroupoptionsrequest.h \
    describeoptiongroupoptionsrequest_p.h \
    describeoptiongroupoptionsresponse.h \
    describeoptiongroupoptionsresponse_p.h \
    describeoptiongroupsrequest.h \
    describeoptiongroupsrequest_p.h \
    describeoptiongroupsresponse.h \
    describeoptiongroupsresponse_p.h \
    describeorderabledbinstanceoptionsrequest.h \
    describeorderabledbinstanceoptionsrequest_p.h \
    describeorderabledbinstanceoptionsresponse.h \
    describeorderabledbinstanceoptionsresponse_p.h \
    describependingmaintenanceactionsrequest.h \
    describependingmaintenanceactionsrequest_p.h \
    describependingmaintenanceactionsresponse.h \
    describependingmaintenanceactionsresponse_p.h \
    describereserveddbinstancesofferingsrequest.h \
    describereserveddbinstancesofferingsrequest_p.h \
    describereserveddbinstancesofferingsresponse.h \
    describereserveddbinstancesofferingsresponse_p.h \
    describereserveddbinstancesrequest.h \
    describereserveddbinstancesrequest_p.h \
    describereserveddbinstancesresponse.h \
    describereserveddbinstancesresponse_p.h \
    describesourceregionsrequest.h \
    describesourceregionsrequest_p.h \
    describesourceregionsresponse.h \
    describesourceregionsresponse_p.h \
    describevaliddbinstancemodificationsrequest.h \
    describevaliddbinstancemodificationsrequest_p.h \
    describevaliddbinstancemodificationsresponse.h \
    describevaliddbinstancemodificationsresponse_p.h \
    downloaddblogfileportionrequest.h \
    downloaddblogfileportionrequest_p.h \
    downloaddblogfileportionresponse.h \
    downloaddblogfileportionresponse_p.h \
    failoverdbclusterrequest.h \
    failoverdbclusterrequest_p.h \
    failoverdbclusterresponse.h \
    failoverdbclusterresponse_p.h \
    listtagsforresourcerequest.h \
    listtagsforresourcerequest_p.h \
    listtagsforresourceresponse.h \
    listtagsforresourceresponse_p.h \
    modifydbclusterparametergrouprequest.h \
    modifydbclusterparametergrouprequest_p.h \
    modifydbclusterparametergroupresponse.h \
    modifydbclusterparametergroupresponse_p.h \
    modifydbclusterrequest.h \
    modifydbclusterrequest_p.h \
    modifydbclusterresponse.h \
    modifydbclusterresponse_p.h \
    modifydbclustersnapshotattributerequest.h \
    modifydbclustersnapshotattributerequest_p.h \
    modifydbclustersnapshotattributeresponse.h \
    modifydbclustersnapshotattributeresponse_p.h \
    modifydbinstancerequest.h \
    modifydbinstancerequest_p.h \
    modifydbinstanceresponse.h \
    modifydbinstanceresponse_p.h \
    modifydbparametergrouprequest.h \
    modifydbparametergrouprequest_p.h \
    modifydbparametergroupresponse.h \
    modifydbparametergroupresponse_p.h \
    modifydbsnapshotattributerequest.h \
    modifydbsnapshotattributerequest_p.h \
    modifydbsnapshotattributeresponse.h \
    modifydbsnapshotattributeresponse_p.h \
    modifydbsnapshotrequest.h \
    modifydbsnapshotrequest_p.h \
    modifydbsnapshotresponse.h \
    modifydbsnapshotresponse_p.h \
    modifydbsubnetgrouprequest.h \
    modifydbsubnetgrouprequest_p.h \
    modifydbsubnetgroupresponse.h \
    modifydbsubnetgroupresponse_p.h \
    modifyeventsubscriptionrequest.h \
    modifyeventsubscriptionrequest_p.h \
    modifyeventsubscriptionresponse.h \
    modifyeventsubscriptionresponse_p.h \
    modifyoptiongrouprequest.h \
    modifyoptiongrouprequest_p.h \
    modifyoptiongroupresponse.h \
    modifyoptiongroupresponse_p.h \
    promotereadreplicadbclusterrequest.h \
    promotereadreplicadbclusterrequest_p.h \
    promotereadreplicadbclusterresponse.h \
    promotereadreplicadbclusterresponse_p.h \
    promotereadreplicarequest.h \
    promotereadreplicarequest_p.h \
    promotereadreplicaresponse.h \
    promotereadreplicaresponse_p.h \
    purchasereserveddbinstancesofferingrequest.h \
    purchasereserveddbinstancesofferingrequest_p.h \
    purchasereserveddbinstancesofferingresponse.h \
    purchasereserveddbinstancesofferingresponse_p.h \
    rdsclient.h \
    rdsclient_p.h \
    rdsclientrequest.h \
    rdsclientrequest_p.h \
    rdsclientresponse.h \
    rdsclientresponse_p.h \
    rebootdbinstancerequest.h \
    rebootdbinstancerequest_p.h \
    rebootdbinstanceresponse.h \
    rebootdbinstanceresponse_p.h \
    removerolefromdbclusterrequest.h \
    removerolefromdbclusterrequest_p.h \
    removerolefromdbclusterresponse.h \
    removerolefromdbclusterresponse_p.h \
    removesourceidentifierfromsubscriptionrequest.h \
    removesourceidentifierfromsubscriptionrequest_p.h \
    removesourceidentifierfromsubscriptionresponse.h \
    removesourceidentifierfromsubscriptionresponse_p.h \
    removetagsfromresourcerequest.h \
    removetagsfromresourcerequest_p.h \
    removetagsfromresourceresponse.h \
    removetagsfromresourceresponse_p.h \
    resetdbclusterparametergrouprequest.h \
    resetdbclusterparametergrouprequest_p.h \
    resetdbclusterparametergroupresponse.h \
    resetdbclusterparametergroupresponse_p.h \
    resetdbparametergrouprequest.h \
    resetdbparametergrouprequest_p.h \
    resetdbparametergroupresponse.h \
    resetdbparametergroupresponse_p.h \
    restoredbclusterfroms3request.h \
    restoredbclusterfroms3request_p.h \
    restoredbclusterfroms3response.h \
    restoredbclusterfroms3response_p.h \
    restoredbclusterfromsnapshotrequest.h \
    restoredbclusterfromsnapshotrequest_p.h \
    restoredbclusterfromsnapshotresponse.h \
    restoredbclusterfromsnapshotresponse_p.h \
    restoredbclustertopointintimerequest.h \
    restoredbclustertopointintimerequest_p.h \
    restoredbclustertopointintimeresponse.h \
    restoredbclustertopointintimeresponse_p.h \
    restoredbinstancefromdbsnapshotrequest.h \
    restoredbinstancefromdbsnapshotrequest_p.h \
    restoredbinstancefromdbsnapshotresponse.h \
    restoredbinstancefromdbsnapshotresponse_p.h \
    restoredbinstancefroms3request.h \
    restoredbinstancefroms3request_p.h \
    restoredbinstancefroms3response.h \
    restoredbinstancefroms3response_p.h \
    restoredbinstancetopointintimerequest.h \
    restoredbinstancetopointintimerequest_p.h \
    restoredbinstancetopointintimeresponse.h \
    restoredbinstancetopointintimeresponse_p.h \
    revokedbsecuritygroupingressrequest.h \
    revokedbsecuritygroupingressrequest_p.h \
    revokedbsecuritygroupingressresponse.h \
    revokedbsecuritygroupingressresponse_p.h \
    startdbinstancerequest.h \
    startdbinstancerequest_p.h \
    startdbinstanceresponse.h \
    startdbinstanceresponse_p.h \
    stopdbinstancerequest.h \
    stopdbinstancerequest_p.h \
    stopdbinstanceresponse.h \
    stopdbinstanceresponse_p.h \

SOURCES += \
    addroletodbclusterrequest.cpp \
    addroletodbclusterresponse.cpp \
    addsourceidentifiertosubscriptionrequest.cpp \
    addsourceidentifiertosubscriptionresponse.cpp \
    addtagstoresourcerequest.cpp \
    addtagstoresourceresponse.cpp \
    applypendingmaintenanceactionrequest.cpp \
    applypendingmaintenanceactionresponse.cpp \
    authorizedbsecuritygroupingressrequest.cpp \
    authorizedbsecuritygroupingressresponse.cpp \
    copydbclusterparametergrouprequest.cpp \
    copydbclusterparametergroupresponse.cpp \
    copydbclustersnapshotrequest.cpp \
    copydbclustersnapshotresponse.cpp \
    copydbparametergrouprequest.cpp \
    copydbparametergroupresponse.cpp \
    copydbsnapshotrequest.cpp \
    copydbsnapshotresponse.cpp \
    copyoptiongrouprequest.cpp \
    copyoptiongroupresponse.cpp \
    createdbclusterparametergrouprequest.cpp \
    createdbclusterparametergroupresponse.cpp \
    createdbclusterrequest.cpp \
    createdbclusterresponse.cpp \
    createdbclustersnapshotrequest.cpp \
    createdbclustersnapshotresponse.cpp \
    createdbinstancereadreplicarequest.cpp \
    createdbinstancereadreplicaresponse.cpp \
    createdbinstancerequest.cpp \
    createdbinstanceresponse.cpp \
    createdbparametergrouprequest.cpp \
    createdbparametergroupresponse.cpp \
    createdbsecuritygrouprequest.cpp \
    createdbsecuritygroupresponse.cpp \
    createdbsnapshotrequest.cpp \
    createdbsnapshotresponse.cpp \
    createdbsubnetgrouprequest.cpp \
    createdbsubnetgroupresponse.cpp \
    createeventsubscriptionrequest.cpp \
    createeventsubscriptionresponse.cpp \
    createoptiongrouprequest.cpp \
    createoptiongroupresponse.cpp \
    deletedbclusterparametergrouprequest.cpp \
    deletedbclusterparametergroupresponse.cpp \
    deletedbclusterrequest.cpp \
    deletedbclusterresponse.cpp \
    deletedbclustersnapshotrequest.cpp \
    deletedbclustersnapshotresponse.cpp \
    deletedbinstancerequest.cpp \
    deletedbinstanceresponse.cpp \
    deletedbparametergrouprequest.cpp \
    deletedbparametergroupresponse.cpp \
    deletedbsecuritygrouprequest.cpp \
    deletedbsecuritygroupresponse.cpp \
    deletedbsnapshotrequest.cpp \
    deletedbsnapshotresponse.cpp \
    deletedbsubnetgrouprequest.cpp \
    deletedbsubnetgroupresponse.cpp \
    deleteeventsubscriptionrequest.cpp \
    deleteeventsubscriptionresponse.cpp \
    deleteoptiongrouprequest.cpp \
    deleteoptiongroupresponse.cpp \
    describeaccountattributesrequest.cpp \
    describeaccountattributesresponse.cpp \
    describecertificatesrequest.cpp \
    describecertificatesresponse.cpp \
    describedbclusterparametergroupsrequest.cpp \
    describedbclusterparametergroupsresponse.cpp \
    describedbclusterparametersrequest.cpp \
    describedbclusterparametersresponse.cpp \
    describedbclustersnapshotattributesrequest.cpp \
    describedbclustersnapshotattributesresponse.cpp \
    describedbclustersnapshotsrequest.cpp \
    describedbclustersnapshotsresponse.cpp \
    describedbclustersrequest.cpp \
    describedbclustersresponse.cpp \
    describedbengineversionsrequest.cpp \
    describedbengineversionsresponse.cpp \
    describedbinstancesrequest.cpp \
    describedbinstancesresponse.cpp \
    describedblogfilesrequest.cpp \
    describedblogfilesresponse.cpp \
    describedbparametergroupsrequest.cpp \
    describedbparametergroupsresponse.cpp \
    describedbparametersrequest.cpp \
    describedbparametersresponse.cpp \
    describedbsecuritygroupsrequest.cpp \
    describedbsecuritygroupsresponse.cpp \
    describedbsnapshotattributesrequest.cpp \
    describedbsnapshotattributesresponse.cpp \
    describedbsnapshotsrequest.cpp \
    describedbsnapshotsresponse.cpp \
    describedbsubnetgroupsrequest.cpp \
    describedbsubnetgroupsresponse.cpp \
    describeenginedefaultclusterparametersrequest.cpp \
    describeenginedefaultclusterparametersresponse.cpp \
    describeenginedefaultparametersrequest.cpp \
    describeenginedefaultparametersresponse.cpp \
    describeeventcategoriesrequest.cpp \
    describeeventcategoriesresponse.cpp \
    describeeventsrequest.cpp \
    describeeventsresponse.cpp \
    describeeventsubscriptionsrequest.cpp \
    describeeventsubscriptionsresponse.cpp \
    describeoptiongroupoptionsrequest.cpp \
    describeoptiongroupoptionsresponse.cpp \
    describeoptiongroupsrequest.cpp \
    describeoptiongroupsresponse.cpp \
    describeorderabledbinstanceoptionsrequest.cpp \
    describeorderabledbinstanceoptionsresponse.cpp \
    describependingmaintenanceactionsrequest.cpp \
    describependingmaintenanceactionsresponse.cpp \
    describereserveddbinstancesofferingsrequest.cpp \
    describereserveddbinstancesofferingsresponse.cpp \
    describereserveddbinstancesrequest.cpp \
    describereserveddbinstancesresponse.cpp \
    describesourceregionsrequest.cpp \
    describesourceregionsresponse.cpp \
    describevaliddbinstancemodificationsrequest.cpp \
    describevaliddbinstancemodificationsresponse.cpp \
    downloaddblogfileportionrequest.cpp \
    downloaddblogfileportionresponse.cpp \
    failoverdbclusterrequest.cpp \
    failoverdbclusterresponse.cpp \
    listtagsforresourcerequest.cpp \
    listtagsforresourceresponse.cpp \
    modifydbclusterparametergrouprequest.cpp \
    modifydbclusterparametergroupresponse.cpp \
    modifydbclusterrequest.cpp \
    modifydbclusterresponse.cpp \
    modifydbclustersnapshotattributerequest.cpp \
    modifydbclustersnapshotattributeresponse.cpp \
    modifydbinstancerequest.cpp \
    modifydbinstanceresponse.cpp \
    modifydbparametergrouprequest.cpp \
    modifydbparametergroupresponse.cpp \
    modifydbsnapshotattributerequest.cpp \
    modifydbsnapshotattributeresponse.cpp \
    modifydbsnapshotrequest.cpp \
    modifydbsnapshotresponse.cpp \
    modifydbsubnetgrouprequest.cpp \
    modifydbsubnetgroupresponse.cpp \
    modifyeventsubscriptionrequest.cpp \
    modifyeventsubscriptionresponse.cpp \
    modifyoptiongrouprequest.cpp \
    modifyoptiongroupresponse.cpp \
    promotereadreplicadbclusterrequest.cpp \
    promotereadreplicadbclusterresponse.cpp \
    promotereadreplicarequest.cpp \
    promotereadreplicaresponse.cpp \
    purchasereserveddbinstancesofferingrequest.cpp \
    purchasereserveddbinstancesofferingresponse.cpp \
    rdsclient.cpp \
    rdsclientrequest.cpp \
    rdsclientresponse.cpp \
    rebootdbinstancerequest.cpp \
    rebootdbinstanceresponse.cpp \
    removerolefromdbclusterrequest.cpp \
    removerolefromdbclusterresponse.cpp \
    removesourceidentifierfromsubscriptionrequest.cpp \
    removesourceidentifierfromsubscriptionresponse.cpp \
    removetagsfromresourcerequest.cpp \
    removetagsfromresourceresponse.cpp \
    resetdbclusterparametergrouprequest.cpp \
    resetdbclusterparametergroupresponse.cpp \
    resetdbparametergrouprequest.cpp \
    resetdbparametergroupresponse.cpp \
    restoredbclusterfroms3request.cpp \
    restoredbclusterfroms3response.cpp \
    restoredbclusterfromsnapshotrequest.cpp \
    restoredbclusterfromsnapshotresponse.cpp \
    restoredbclustertopointintimerequest.cpp \
    restoredbclustertopointintimeresponse.cpp \
    restoredbinstancefromdbsnapshotrequest.cpp \
    restoredbinstancefromdbsnapshotresponse.cpp \
    restoredbinstancefroms3request.cpp \
    restoredbinstancefroms3response.cpp \
    restoredbinstancetopointintimerequest.cpp \
    restoredbinstancetopointintimeresponse.cpp \
    revokedbsecuritygroupingressrequest.cpp \
    revokedbsecuritygroupingressresponse.cpp \
    startdbinstancerequest.cpp \
    startdbinstanceresponse.cpp \
    stopdbinstancerequest.cpp \
    stopdbinstanceresponse.cpp \

win32:CONFIG += skip_target_version_ext
