include(../../common.pri)

TARGET = QtAwsConfigService
TEMPLATE = lib
QT -= gui
QT += network
DEFINES += QTAWS_LIBRARY
DEFINES += QT_NO_CAST_FROM_ASCII QT_NO_CAST_TO_ASCII

INCLUDEPATH = $$TOPDIR/src

HEADERS += \
    batchgetaggregateresourceconfigrequest.h \
    batchgetaggregateresourceconfigrequest_p.h \
    batchgetaggregateresourceconfigresponse.h \
    batchgetaggregateresourceconfigresponse_p.h \
    batchgetresourceconfigrequest.h \
    batchgetresourceconfigrequest_p.h \
    batchgetresourceconfigresponse.h \
    batchgetresourceconfigresponse_p.h \
    configserviceclient.h \
    configserviceclient_p.h \
    configservicerequest.h \
    configservicerequest_p.h \
    configserviceresponse.h \
    configserviceresponse_p.h \
    deleteaggregationauthorizationrequest.h \
    deleteaggregationauthorizationrequest_p.h \
    deleteaggregationauthorizationresponse.h \
    deleteaggregationauthorizationresponse_p.h \
    deleteconfigrulerequest.h \
    deleteconfigrulerequest_p.h \
    deleteconfigruleresponse.h \
    deleteconfigruleresponse_p.h \
    deleteconfigurationaggregatorrequest.h \
    deleteconfigurationaggregatorrequest_p.h \
    deleteconfigurationaggregatorresponse.h \
    deleteconfigurationaggregatorresponse_p.h \
    deleteconfigurationrecorderrequest.h \
    deleteconfigurationrecorderrequest_p.h \
    deleteconfigurationrecorderresponse.h \
    deleteconfigurationrecorderresponse_p.h \
    deletedeliverychannelrequest.h \
    deletedeliverychannelrequest_p.h \
    deletedeliverychannelresponse.h \
    deletedeliverychannelresponse_p.h \
    deleteevaluationresultsrequest.h \
    deleteevaluationresultsrequest_p.h \
    deleteevaluationresultsresponse.h \
    deleteevaluationresultsresponse_p.h \
    deleteorganizationconfigrulerequest.h \
    deleteorganizationconfigrulerequest_p.h \
    deleteorganizationconfigruleresponse.h \
    deleteorganizationconfigruleresponse_p.h \
    deletependingaggregationrequestrequest.h \
    deletependingaggregationrequestrequest_p.h \
    deletependingaggregationrequestresponse.h \
    deletependingaggregationrequestresponse_p.h \
    deleteremediationconfigurationrequest.h \
    deleteremediationconfigurationrequest_p.h \
    deleteremediationconfigurationresponse.h \
    deleteremediationconfigurationresponse_p.h \
    deleteretentionconfigurationrequest.h \
    deleteretentionconfigurationrequest_p.h \
    deleteretentionconfigurationresponse.h \
    deleteretentionconfigurationresponse_p.h \
    deliverconfigsnapshotrequest.h \
    deliverconfigsnapshotrequest_p.h \
    deliverconfigsnapshotresponse.h \
    deliverconfigsnapshotresponse_p.h \
    describeaggregatecompliancebyconfigrulesrequest.h \
    describeaggregatecompliancebyconfigrulesrequest_p.h \
    describeaggregatecompliancebyconfigrulesresponse.h \
    describeaggregatecompliancebyconfigrulesresponse_p.h \
    describeaggregationauthorizationsrequest.h \
    describeaggregationauthorizationsrequest_p.h \
    describeaggregationauthorizationsresponse.h \
    describeaggregationauthorizationsresponse_p.h \
    describecompliancebyconfigrulerequest.h \
    describecompliancebyconfigrulerequest_p.h \
    describecompliancebyconfigruleresponse.h \
    describecompliancebyconfigruleresponse_p.h \
    describecompliancebyresourcerequest.h \
    describecompliancebyresourcerequest_p.h \
    describecompliancebyresourceresponse.h \
    describecompliancebyresourceresponse_p.h \
    describeconfigruleevaluationstatusrequest.h \
    describeconfigruleevaluationstatusrequest_p.h \
    describeconfigruleevaluationstatusresponse.h \
    describeconfigruleevaluationstatusresponse_p.h \
    describeconfigrulesrequest.h \
    describeconfigrulesrequest_p.h \
    describeconfigrulesresponse.h \
    describeconfigrulesresponse_p.h \
    describeconfigurationaggregatorsourcesstatusrequest.h \
    describeconfigurationaggregatorsourcesstatusrequest_p.h \
    describeconfigurationaggregatorsourcesstatusresponse.h \
    describeconfigurationaggregatorsourcesstatusresponse_p.h \
    describeconfigurationaggregatorsrequest.h \
    describeconfigurationaggregatorsrequest_p.h \
    describeconfigurationaggregatorsresponse.h \
    describeconfigurationaggregatorsresponse_p.h \
    describeconfigurationrecordersrequest.h \
    describeconfigurationrecordersrequest_p.h \
    describeconfigurationrecordersresponse.h \
    describeconfigurationrecordersresponse_p.h \
    describeconfigurationrecorderstatusrequest.h \
    describeconfigurationrecorderstatusrequest_p.h \
    describeconfigurationrecorderstatusresponse.h \
    describeconfigurationrecorderstatusresponse_p.h \
    describedeliverychannelsrequest.h \
    describedeliverychannelsrequest_p.h \
    describedeliverychannelsresponse.h \
    describedeliverychannelsresponse_p.h \
    describedeliverychannelstatusrequest.h \
    describedeliverychannelstatusrequest_p.h \
    describedeliverychannelstatusresponse.h \
    describedeliverychannelstatusresponse_p.h \
    describeorganizationconfigrulesrequest.h \
    describeorganizationconfigrulesrequest_p.h \
    describeorganizationconfigrulesresponse.h \
    describeorganizationconfigrulesresponse_p.h \
    describeorganizationconfigrulestatusesrequest.h \
    describeorganizationconfigrulestatusesrequest_p.h \
    describeorganizationconfigrulestatusesresponse.h \
    describeorganizationconfigrulestatusesresponse_p.h \
    describependingaggregationrequestsrequest.h \
    describependingaggregationrequestsrequest_p.h \
    describependingaggregationrequestsresponse.h \
    describependingaggregationrequestsresponse_p.h \
    describeremediationconfigurationsrequest.h \
    describeremediationconfigurationsrequest_p.h \
    describeremediationconfigurationsresponse.h \
    describeremediationconfigurationsresponse_p.h \
    describeremediationexecutionstatusrequest.h \
    describeremediationexecutionstatusrequest_p.h \
    describeremediationexecutionstatusresponse.h \
    describeremediationexecutionstatusresponse_p.h \
    describeretentionconfigurationsrequest.h \
    describeretentionconfigurationsrequest_p.h \
    describeretentionconfigurationsresponse.h \
    describeretentionconfigurationsresponse_p.h \
    getaggregatecompliancedetailsbyconfigrulerequest.h \
    getaggregatecompliancedetailsbyconfigrulerequest_p.h \
    getaggregatecompliancedetailsbyconfigruleresponse.h \
    getaggregatecompliancedetailsbyconfigruleresponse_p.h \
    getaggregateconfigrulecompliancesummaryrequest.h \
    getaggregateconfigrulecompliancesummaryrequest_p.h \
    getaggregateconfigrulecompliancesummaryresponse.h \
    getaggregateconfigrulecompliancesummaryresponse_p.h \
    getaggregatediscoveredresourcecountsrequest.h \
    getaggregatediscoveredresourcecountsrequest_p.h \
    getaggregatediscoveredresourcecountsresponse.h \
    getaggregatediscoveredresourcecountsresponse_p.h \
    getaggregateresourceconfigrequest.h \
    getaggregateresourceconfigrequest_p.h \
    getaggregateresourceconfigresponse.h \
    getaggregateresourceconfigresponse_p.h \
    getcompliancedetailsbyconfigrulerequest.h \
    getcompliancedetailsbyconfigrulerequest_p.h \
    getcompliancedetailsbyconfigruleresponse.h \
    getcompliancedetailsbyconfigruleresponse_p.h \
    getcompliancedetailsbyresourcerequest.h \
    getcompliancedetailsbyresourcerequest_p.h \
    getcompliancedetailsbyresourceresponse.h \
    getcompliancedetailsbyresourceresponse_p.h \
    getcompliancesummarybyconfigrulerequest.h \
    getcompliancesummarybyconfigrulerequest_p.h \
    getcompliancesummarybyconfigruleresponse.h \
    getcompliancesummarybyconfigruleresponse_p.h \
    getcompliancesummarybyresourcetyperequest.h \
    getcompliancesummarybyresourcetyperequest_p.h \
    getcompliancesummarybyresourcetyperesponse.h \
    getcompliancesummarybyresourcetyperesponse_p.h \
    getdiscoveredresourcecountsrequest.h \
    getdiscoveredresourcecountsrequest_p.h \
    getdiscoveredresourcecountsresponse.h \
    getdiscoveredresourcecountsresponse_p.h \
    getorganizationconfigruledetailedstatusrequest.h \
    getorganizationconfigruledetailedstatusrequest_p.h \
    getorganizationconfigruledetailedstatusresponse.h \
    getorganizationconfigruledetailedstatusresponse_p.h \
    getresourceconfighistoryrequest.h \
    getresourceconfighistoryrequest_p.h \
    getresourceconfighistoryresponse.h \
    getresourceconfighistoryresponse_p.h \
    listaggregatediscoveredresourcesrequest.h \
    listaggregatediscoveredresourcesrequest_p.h \
    listaggregatediscoveredresourcesresponse.h \
    listaggregatediscoveredresourcesresponse_p.h \
    listdiscoveredresourcesrequest.h \
    listdiscoveredresourcesrequest_p.h \
    listdiscoveredresourcesresponse.h \
    listdiscoveredresourcesresponse_p.h \
    listtagsforresourcerequest.h \
    listtagsforresourcerequest_p.h \
    listtagsforresourceresponse.h \
    listtagsforresourceresponse_p.h \
    putaggregationauthorizationrequest.h \
    putaggregationauthorizationrequest_p.h \
    putaggregationauthorizationresponse.h \
    putaggregationauthorizationresponse_p.h \
    putconfigrulerequest.h \
    putconfigrulerequest_p.h \
    putconfigruleresponse.h \
    putconfigruleresponse_p.h \
    putconfigurationaggregatorrequest.h \
    putconfigurationaggregatorrequest_p.h \
    putconfigurationaggregatorresponse.h \
    putconfigurationaggregatorresponse_p.h \
    putconfigurationrecorderrequest.h \
    putconfigurationrecorderrequest_p.h \
    putconfigurationrecorderresponse.h \
    putconfigurationrecorderresponse_p.h \
    putdeliverychannelrequest.h \
    putdeliverychannelrequest_p.h \
    putdeliverychannelresponse.h \
    putdeliverychannelresponse_p.h \
    putevaluationsrequest.h \
    putevaluationsrequest_p.h \
    putevaluationsresponse.h \
    putevaluationsresponse_p.h \
    putorganizationconfigrulerequest.h \
    putorganizationconfigrulerequest_p.h \
    putorganizationconfigruleresponse.h \
    putorganizationconfigruleresponse_p.h \
    putremediationconfigurationsrequest.h \
    putremediationconfigurationsrequest_p.h \
    putremediationconfigurationsresponse.h \
    putremediationconfigurationsresponse_p.h \
    putretentionconfigurationrequest.h \
    putretentionconfigurationrequest_p.h \
    putretentionconfigurationresponse.h \
    putretentionconfigurationresponse_p.h \
    selectresourceconfigrequest.h \
    selectresourceconfigrequest_p.h \
    selectresourceconfigresponse.h \
    selectresourceconfigresponse_p.h \
    startconfigrulesevaluationrequest.h \
    startconfigrulesevaluationrequest_p.h \
    startconfigrulesevaluationresponse.h \
    startconfigrulesevaluationresponse_p.h \
    startconfigurationrecorderrequest.h \
    startconfigurationrecorderrequest_p.h \
    startconfigurationrecorderresponse.h \
    startconfigurationrecorderresponse_p.h \
    startremediationexecutionrequest.h \
    startremediationexecutionrequest_p.h \
    startremediationexecutionresponse.h \
    startremediationexecutionresponse_p.h \
    stopconfigurationrecorderrequest.h \
    stopconfigurationrecorderrequest_p.h \
    stopconfigurationrecorderresponse.h \
    stopconfigurationrecorderresponse_p.h \
    tagresourcerequest.h \
    tagresourcerequest_p.h \
    tagresourceresponse.h \
    tagresourceresponse_p.h \
    untagresourcerequest.h \
    untagresourcerequest_p.h \
    untagresourceresponse.h \
    untagresourceresponse_p.h \

SOURCES += \
    batchgetaggregateresourceconfigrequest.cpp \
    batchgetaggregateresourceconfigresponse.cpp \
    batchgetresourceconfigrequest.cpp \
    batchgetresourceconfigresponse.cpp \
    configserviceclient.cpp \
    configservicerequest.cpp \
    configserviceresponse.cpp \
    deleteaggregationauthorizationrequest.cpp \
    deleteaggregationauthorizationresponse.cpp \
    deleteconfigrulerequest.cpp \
    deleteconfigruleresponse.cpp \
    deleteconfigurationaggregatorrequest.cpp \
    deleteconfigurationaggregatorresponse.cpp \
    deleteconfigurationrecorderrequest.cpp \
    deleteconfigurationrecorderresponse.cpp \
    deletedeliverychannelrequest.cpp \
    deletedeliverychannelresponse.cpp \
    deleteevaluationresultsrequest.cpp \
    deleteevaluationresultsresponse.cpp \
    deleteorganizationconfigrulerequest.cpp \
    deleteorganizationconfigruleresponse.cpp \
    deletependingaggregationrequestrequest.cpp \
    deletependingaggregationrequestresponse.cpp \
    deleteremediationconfigurationrequest.cpp \
    deleteremediationconfigurationresponse.cpp \
    deleteretentionconfigurationrequest.cpp \
    deleteretentionconfigurationresponse.cpp \
    deliverconfigsnapshotrequest.cpp \
    deliverconfigsnapshotresponse.cpp \
    describeaggregatecompliancebyconfigrulesrequest.cpp \
    describeaggregatecompliancebyconfigrulesresponse.cpp \
    describeaggregationauthorizationsrequest.cpp \
    describeaggregationauthorizationsresponse.cpp \
    describecompliancebyconfigrulerequest.cpp \
    describecompliancebyconfigruleresponse.cpp \
    describecompliancebyresourcerequest.cpp \
    describecompliancebyresourceresponse.cpp \
    describeconfigruleevaluationstatusrequest.cpp \
    describeconfigruleevaluationstatusresponse.cpp \
    describeconfigrulesrequest.cpp \
    describeconfigrulesresponse.cpp \
    describeconfigurationaggregatorsourcesstatusrequest.cpp \
    describeconfigurationaggregatorsourcesstatusresponse.cpp \
    describeconfigurationaggregatorsrequest.cpp \
    describeconfigurationaggregatorsresponse.cpp \
    describeconfigurationrecordersrequest.cpp \
    describeconfigurationrecordersresponse.cpp \
    describeconfigurationrecorderstatusrequest.cpp \
    describeconfigurationrecorderstatusresponse.cpp \
    describedeliverychannelsrequest.cpp \
    describedeliverychannelsresponse.cpp \
    describedeliverychannelstatusrequest.cpp \
    describedeliverychannelstatusresponse.cpp \
    describeorganizationconfigrulesrequest.cpp \
    describeorganizationconfigrulesresponse.cpp \
    describeorganizationconfigrulestatusesrequest.cpp \
    describeorganizationconfigrulestatusesresponse.cpp \
    describependingaggregationrequestsrequest.cpp \
    describependingaggregationrequestsresponse.cpp \
    describeremediationconfigurationsrequest.cpp \
    describeremediationconfigurationsresponse.cpp \
    describeremediationexecutionstatusrequest.cpp \
    describeremediationexecutionstatusresponse.cpp \
    describeretentionconfigurationsrequest.cpp \
    describeretentionconfigurationsresponse.cpp \
    getaggregatecompliancedetailsbyconfigrulerequest.cpp \
    getaggregatecompliancedetailsbyconfigruleresponse.cpp \
    getaggregateconfigrulecompliancesummaryrequest.cpp \
    getaggregateconfigrulecompliancesummaryresponse.cpp \
    getaggregatediscoveredresourcecountsrequest.cpp \
    getaggregatediscoveredresourcecountsresponse.cpp \
    getaggregateresourceconfigrequest.cpp \
    getaggregateresourceconfigresponse.cpp \
    getcompliancedetailsbyconfigrulerequest.cpp \
    getcompliancedetailsbyconfigruleresponse.cpp \
    getcompliancedetailsbyresourcerequest.cpp \
    getcompliancedetailsbyresourceresponse.cpp \
    getcompliancesummarybyconfigrulerequest.cpp \
    getcompliancesummarybyconfigruleresponse.cpp \
    getcompliancesummarybyresourcetyperequest.cpp \
    getcompliancesummarybyresourcetyperesponse.cpp \
    getdiscoveredresourcecountsrequest.cpp \
    getdiscoveredresourcecountsresponse.cpp \
    getorganizationconfigruledetailedstatusrequest.cpp \
    getorganizationconfigruledetailedstatusresponse.cpp \
    getresourceconfighistoryrequest.cpp \
    getresourceconfighistoryresponse.cpp \
    listaggregatediscoveredresourcesrequest.cpp \
    listaggregatediscoveredresourcesresponse.cpp \
    listdiscoveredresourcesrequest.cpp \
    listdiscoveredresourcesresponse.cpp \
    listtagsforresourcerequest.cpp \
    listtagsforresourceresponse.cpp \
    putaggregationauthorizationrequest.cpp \
    putaggregationauthorizationresponse.cpp \
    putconfigrulerequest.cpp \
    putconfigruleresponse.cpp \
    putconfigurationaggregatorrequest.cpp \
    putconfigurationaggregatorresponse.cpp \
    putconfigurationrecorderrequest.cpp \
    putconfigurationrecorderresponse.cpp \
    putdeliverychannelrequest.cpp \
    putdeliverychannelresponse.cpp \
    putevaluationsrequest.cpp \
    putevaluationsresponse.cpp \
    putorganizationconfigrulerequest.cpp \
    putorganizationconfigruleresponse.cpp \
    putremediationconfigurationsrequest.cpp \
    putremediationconfigurationsresponse.cpp \
    putretentionconfigurationrequest.cpp \
    putretentionconfigurationresponse.cpp \
    selectresourceconfigrequest.cpp \
    selectresourceconfigresponse.cpp \
    startconfigrulesevaluationrequest.cpp \
    startconfigrulesevaluationresponse.cpp \
    startconfigurationrecorderrequest.cpp \
    startconfigurationrecorderresponse.cpp \
    startremediationexecutionrequest.cpp \
    startremediationexecutionresponse.cpp \
    stopconfigurationrecorderrequest.cpp \
    stopconfigurationrecorderresponse.cpp \
    tagresourcerequest.cpp \
    tagresourceresponse.cpp \
    untagresourcerequest.cpp \
    untagresourceresponse.cpp \

win32:CONFIG += skip_target_version_ext
