var searchData=
[
  ['kinesisanalyticsclient',['KinesisAnalyticsClient',['../classAWS_1_1KinesisAnalytics_1_1KinesisAnalyticsClient.html',1,'AWS::KinesisAnalytics::KinesisAnalyticsClient'],['../classAWS_1_1KinesisAnalytics_1_1KinesisAnalyticsClient.html#acc455e1e3c9a503ea3d6ce02c4a0c3cc',1,'AWS::KinesisAnalytics::KinesisAnalyticsClient::KinesisAnalyticsClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classAWS_1_1KinesisAnalytics_1_1KinesisAnalyticsClient.html#a6d01b22f7b411acc0d69316b449239e6',1,'AWS::KinesisAnalytics::KinesisAnalyticsClient::KinesisAnalyticsClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['kinesisclient',['KinesisClient',['../classAWS_1_1Kinesis_1_1KinesisClient.html',1,'AWS::Kinesis::KinesisClient'],['../classAWS_1_1Kinesis_1_1KinesisClient.html#ae36ce4f2f04e553b2016c34fcb8e2a04',1,'AWS::Kinesis::KinesisClient::KinesisClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classAWS_1_1Kinesis_1_1KinesisClient.html#a5604ada798b0fc0a61344ae198e390c6',1,'AWS::Kinesis::KinesisClient::KinesisClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['kinesisvideoarchivedmediaclient',['KinesisVideoArchivedMediaClient',['../classAWS_1_1KinesisVideoArchivedMedia_1_1KinesisVideoArchivedMediaClient.html',1,'AWS::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient'],['../classAWS_1_1KinesisVideoArchivedMedia_1_1KinesisVideoArchivedMediaClient.html#a1b6c7037e5eaf5d9d66fe73ceef8348d',1,'AWS::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient::KinesisVideoArchivedMediaClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classAWS_1_1KinesisVideoArchivedMedia_1_1KinesisVideoArchivedMediaClient.html#a6b836556d50d8cae2423737b194b8dce',1,'AWS::KinesisVideoArchivedMedia::KinesisVideoArchivedMediaClient::KinesisVideoArchivedMediaClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['kinesisvideoclient',['KinesisVideoClient',['../classAWS_1_1KinesisVideo_1_1KinesisVideoClient.html',1,'AWS::KinesisVideo::KinesisVideoClient'],['../classAWS_1_1KinesisVideo_1_1KinesisVideoClient.html#aa243454cca1e6762e8a49563adf2ecce',1,'AWS::KinesisVideo::KinesisVideoClient::KinesisVideoClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classAWS_1_1KinesisVideo_1_1KinesisVideoClient.html#ad59e313e189f54d2e390620c1efd4c32',1,'AWS::KinesisVideo::KinesisVideoClient::KinesisVideoClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['kinesisvideomediaclient',['KinesisVideoMediaClient',['../classAWS_1_1KinesisVideoMedia_1_1KinesisVideoMediaClient.html',1,'AWS::KinesisVideoMedia::KinesisVideoMediaClient'],['../classAWS_1_1KinesisVideoMedia_1_1KinesisVideoMediaClient.html#a4e051ac7efa7ffb0b983469a664dd32a',1,'AWS::KinesisVideoMedia::KinesisVideoMediaClient::KinesisVideoMediaClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classAWS_1_1KinesisVideoMedia_1_1KinesisVideoMediaClient.html#afcb48fbf598053982a61d42afb4282e4',1,'AWS::KinesisVideoMedia::KinesisVideoMediaClient::KinesisVideoMediaClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['kmsclient',['KmsClient',['../classAWS_1_1KMS_1_1KmsClient.html',1,'AWS::KMS::KmsClient'],['../classAWS_1_1KMS_1_1KmsClient.html#abee1e401447b8640bd066d6e5d5cdcf7',1,'AWS::KMS::KmsClient::KmsClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classAWS_1_1KMS_1_1KmsClient.html#a9342e7b199ef1582ea707916eb42e04c',1,'AWS::KMS::KmsClient::KmsClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]]
];
