var searchData=
[
  ['machinelearningclient',['MachineLearningClient',['../classMachineLearningClient.html',1,'MachineLearningClient'],['../classMachineLearningClient.html#a5b6ad43dd2aa9f3cdae25335f099c402',1,'MachineLearningClient::MachineLearningClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classMachineLearningClient.html#a8bc727e18733cd8f6d8ae15292c2c156',1,'MachineLearningClient::MachineLearningClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['macroregion',['MacroRegion',['../classAwsRegion.html#ad78b2e6bccc468cc75998dfaa5100c14',1,'AwsRegion']]],
  ['marketplacecommerceanalyticsclient',['MarketplaceCommerceAnalyticsClient',['../classMarketplaceCommerceAnalyticsClient.html',1,'MarketplaceCommerceAnalyticsClient'],['../classMarketplaceCommerceAnalyticsClient.html#ababe79358b06cfaa737c6bfea323833d',1,'MarketplaceCommerceAnalyticsClient::MarketplaceCommerceAnalyticsClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classMarketplaceCommerceAnalyticsClient.html#a610e24b6f99e916c7e255fde295ac564',1,'MarketplaceCommerceAnalyticsClient::MarketplaceCommerceAnalyticsClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['marketplacemeteringclient',['MarketplaceMeteringClient',['../classMarketplaceMeteringClient.html',1,'MarketplaceMeteringClient'],['../classMarketplaceMeteringClient.html#a7814cba2398ce30163f88628bf4f3fc5',1,'MarketplaceMeteringClient::MarketplaceMeteringClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classMarketplaceMeteringClient.html#a9957307c1f1bcc5431373ece52515ff0',1,'MarketplaceMeteringClient::MarketplaceMeteringClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['maximummessagesize',['maximumMessageSize',['../classSqsCreateQueueRequest.html#a10839f9117063bb37b926ce03d619f22',1,'SqsCreateQueueRequest']]],
  ['message',['message',['../classSqsError.html#a4c14570f97be4e93c9d9edf61cc4c0fb',1,'SqsError']]],
  ['messageretentionperiod',['messageRetentionPeriod',['../classSqsCreateQueueRequest.html#a68919e7b2195b7df245150ecc2c449f5',1,'SqsCreateQueueRequest']]],
  ['mobileanalyticsclient',['MobileAnalyticsClient',['../classMobileAnalyticsClient.html',1,'MobileAnalyticsClient'],['../classMobileAnalyticsClient.html#a242162cc1d6547bd8b962613df7e6ae8',1,'MobileAnalyticsClient::MobileAnalyticsClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classMobileAnalyticsClient.html#a30996578aa1169bbc5220a7205cd6c31',1,'MobileAnalyticsClient::MobileAnalyticsClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]]
];
