var searchData=
[
  ['gameliftclient',['GameLiftClient',['../classAWS_1_1GameLift_1_1GameLiftClient.html#a186a36b18b1e09783c7faa6a26bb1b47',1,'AWS::GameLift::GameLiftClient::GameLiftClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classAWS_1_1GameLift_1_1GameLiftClient.html#a57ef5f4b6a92b167870b10f017aea940',1,'AWS::GameLift::GameLiftClient::GameLiftClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['getendpoint',['getEndpoint',['../classAwsEndpoint.html#a972e747803e29799e4b2ca6c211c7240',1,'AwsEndpoint']]],
  ['getqueueurl',['getQueueUrl',['../classSqsClient.html#a2a5e2b31b7064619ff7c8ed79a629a00',1,'SqsClient::getQueueUrl(const SqsGetQueueUrlRequest &amp;request)'],['../classSqsClient.html#ae4cecbd6532edf1badd44c77fe086502',1,'SqsClient::getQueueUrl(const QString &amp;queueName, const QString &amp;queueOwnerAWSAccountId=QString())']]],
  ['glacierclient',['GlacierClient',['../classAWS_1_1Glacier_1_1GlacierClient.html#a3534c8be6dcc0151e2bb887867e2f47f',1,'AWS::Glacier::GlacierClient::GlacierClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classAWS_1_1Glacier_1_1GlacierClient.html#aeee63beace32225a730e90d5710cddfc',1,'AWS::Glacier::GlacierClient::GlacierClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['glueclient',['GlueClient',['../classAWS_1_1Glue_1_1GlueClient.html#a3d96f0f9d871df2e7e78e87af68353be',1,'AWS::Glue::GlueClient::GlueClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classAWS_1_1Glue_1_1GlueClient.html#a60170e3d6707879327b42202faf98fc6',1,'AWS::Glue::GlueClient::GlueClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['greengrassclient',['GreengrassClient',['../classAWS_1_1Greengrass_1_1GreengrassClient.html#a51960c2f4ce198d5ee59222466e4f372',1,'AWS::Greengrass::GreengrassClient::GreengrassClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classAWS_1_1Greengrass_1_1GreengrassClient.html#abcacc2a97b9c2303b327e6675736930c',1,'AWS::Greengrass::GreengrassClient::GreengrassClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]],
  ['guarddutyclient',['GuardDutyClient',['../classAWS_1_1GuardDuty_1_1GuardDutyClient.html#a29e8b6487c368d1cd55855445c303e6d',1,'AWS::GuardDuty::GuardDutyClient::GuardDutyClient(const AwsRegion::Region region=AwsRegion::InvalidRegion, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)'],['../classAWS_1_1GuardDuty_1_1GuardDutyClient.html#ae3302ff261f267da92e9f28c988c1d9a',1,'AWS::GuardDuty::GuardDutyClient::GuardDutyClient(const QUrl &amp;endpoint, AwsAbstractCredentials *credentials=NULL, QNetworkAccessManager *const manager=NULL, QObject *const parent=0)']]]
];
