include(../../common.pri)

TARGET = cloudfront
TEMPLATE = lib
QT -= gui
QT += network
DEFINES += QTAWS_LIBRARY
DEFINES += QT_NO_CAST_FROM_ASCII QT_NO_CAST_TO_ASCII

INCLUDEPATH = $$TOPDIR/src

HEADERS += \
    cloudfrontclient.h \
    cloudfrontclient_p.h \
    cloudfrontrequest.h \
    cloudfrontrequest_p.h \
    cloudfrontresponse.h \
    cloudfrontresponse_p.h \
    createcloudfrontoriginaccessidentityrequest.h \
    createcloudfrontoriginaccessidentityrequest_p.h \
    createcloudfrontoriginaccessidentityresponse.h \
    createcloudfrontoriginaccessidentityresponse_p.h \
    createdistributionrequest.h \
    createdistributionrequest_p.h \
    createdistributionresponse.h \
    createdistributionresponse_p.h \
    createdistributionwithtagsrequest.h \
    createdistributionwithtagsrequest_p.h \
    createdistributionwithtagsresponse.h \
    createdistributionwithtagsresponse_p.h \
    createinvalidationrequest.h \
    createinvalidationrequest_p.h \
    createinvalidationresponse.h \
    createinvalidationresponse_p.h \
    createstreamingdistributionrequest.h \
    createstreamingdistributionrequest_p.h \
    createstreamingdistributionresponse.h \
    createstreamingdistributionresponse_p.h \
    createstreamingdistributionwithtagsrequest.h \
    createstreamingdistributionwithtagsrequest_p.h \
    createstreamingdistributionwithtagsresponse.h \
    createstreamingdistributionwithtagsresponse_p.h \
    deletecloudfrontoriginaccessidentityrequest.h \
    deletecloudfrontoriginaccessidentityrequest_p.h \
    deletecloudfrontoriginaccessidentityresponse.h \
    deletecloudfrontoriginaccessidentityresponse_p.h \
    deletedistributionrequest.h \
    deletedistributionrequest_p.h \
    deletedistributionresponse.h \
    deletedistributionresponse_p.h \
    deleteservicelinkedrolerequest.h \
    deleteservicelinkedrolerequest_p.h \
    deleteservicelinkedroleresponse.h \
    deleteservicelinkedroleresponse_p.h \
    deletestreamingdistributionrequest.h \
    deletestreamingdistributionrequest_p.h \
    deletestreamingdistributionresponse.h \
    deletestreamingdistributionresponse_p.h \
    getcloudfrontoriginaccessidentityconfigrequest.h \
    getcloudfrontoriginaccessidentityconfigrequest_p.h \
    getcloudfrontoriginaccessidentityconfigresponse.h \
    getcloudfrontoriginaccessidentityconfigresponse_p.h \
    getcloudfrontoriginaccessidentityrequest.h \
    getcloudfrontoriginaccessidentityrequest_p.h \
    getcloudfrontoriginaccessidentityresponse.h \
    getcloudfrontoriginaccessidentityresponse_p.h \
    getdistributionconfigrequest.h \
    getdistributionconfigrequest_p.h \
    getdistributionconfigresponse.h \
    getdistributionconfigresponse_p.h \
    getdistributionrequest.h \
    getdistributionrequest_p.h \
    getdistributionresponse.h \
    getdistributionresponse_p.h \
    getinvalidationrequest.h \
    getinvalidationrequest_p.h \
    getinvalidationresponse.h \
    getinvalidationresponse_p.h \
    getstreamingdistributionconfigrequest.h \
    getstreamingdistributionconfigrequest_p.h \
    getstreamingdistributionconfigresponse.h \
    getstreamingdistributionconfigresponse_p.h \
    getstreamingdistributionrequest.h \
    getstreamingdistributionrequest_p.h \
    getstreamingdistributionresponse.h \
    getstreamingdistributionresponse_p.h \
    listcloudfrontoriginaccessidentitiesrequest.h \
    listcloudfrontoriginaccessidentitiesrequest_p.h \
    listcloudfrontoriginaccessidentitiesresponse.h \
    listcloudfrontoriginaccessidentitiesresponse_p.h \
    listdistributionsbywebaclidrequest.h \
    listdistributionsbywebaclidrequest_p.h \
    listdistributionsbywebaclidresponse.h \
    listdistributionsbywebaclidresponse_p.h \
    listdistributionsrequest.h \
    listdistributionsrequest_p.h \
    listdistributionsresponse.h \
    listdistributionsresponse_p.h \
    listinvalidationsrequest.h \
    listinvalidationsrequest_p.h \
    listinvalidationsresponse.h \
    listinvalidationsresponse_p.h \
    liststreamingdistributionsrequest.h \
    liststreamingdistributionsrequest_p.h \
    liststreamingdistributionsresponse.h \
    liststreamingdistributionsresponse_p.h \
    listtagsforresourcerequest.h \
    listtagsforresourcerequest_p.h \
    listtagsforresourceresponse.h \
    listtagsforresourceresponse_p.h \
    tagresourcerequest.h \
    tagresourcerequest_p.h \
    tagresourceresponse.h \
    tagresourceresponse_p.h \
    untagresourcerequest.h \
    untagresourcerequest_p.h \
    untagresourceresponse.h \
    untagresourceresponse_p.h \
    updatecloudfrontoriginaccessidentityrequest.h \
    updatecloudfrontoriginaccessidentityrequest_p.h \
    updatecloudfrontoriginaccessidentityresponse.h \
    updatecloudfrontoriginaccessidentityresponse_p.h \
    updatedistributionrequest.h \
    updatedistributionrequest_p.h \
    updatedistributionresponse.h \
    updatedistributionresponse_p.h \
    updatestreamingdistributionrequest.h \
    updatestreamingdistributionrequest_p.h \
    updatestreamingdistributionresponse.h \
    updatestreamingdistributionresponse_p.h \

SOURCES += \
    cloudfrontclient.cpp \
    cloudfrontrequest.cpp \
    cloudfrontresponse.cpp \
    createcloudfrontoriginaccessidentityrequest.cpp \
    createcloudfrontoriginaccessidentityresponse.cpp \
    createdistributionrequest.cpp \
    createdistributionresponse.cpp \
    createdistributionwithtagsrequest.cpp \
    createdistributionwithtagsresponse.cpp \
    createinvalidationrequest.cpp \
    createinvalidationresponse.cpp \
    createstreamingdistributionrequest.cpp \
    createstreamingdistributionresponse.cpp \
    createstreamingdistributionwithtagsrequest.cpp \
    createstreamingdistributionwithtagsresponse.cpp \
    deletecloudfrontoriginaccessidentityrequest.cpp \
    deletecloudfrontoriginaccessidentityresponse.cpp \
    deletedistributionrequest.cpp \
    deletedistributionresponse.cpp \
    deleteservicelinkedrolerequest.cpp \
    deleteservicelinkedroleresponse.cpp \
    deletestreamingdistributionrequest.cpp \
    deletestreamingdistributionresponse.cpp \
    getcloudfrontoriginaccessidentityconfigrequest.cpp \
    getcloudfrontoriginaccessidentityconfigresponse.cpp \
    getcloudfrontoriginaccessidentityrequest.cpp \
    getcloudfrontoriginaccessidentityresponse.cpp \
    getdistributionconfigrequest.cpp \
    getdistributionconfigresponse.cpp \
    getdistributionrequest.cpp \
    getdistributionresponse.cpp \
    getinvalidationrequest.cpp \
    getinvalidationresponse.cpp \
    getstreamingdistributionconfigrequest.cpp \
    getstreamingdistributionconfigresponse.cpp \
    getstreamingdistributionrequest.cpp \
    getstreamingdistributionresponse.cpp \
    listcloudfrontoriginaccessidentitiesrequest.cpp \
    listcloudfrontoriginaccessidentitiesresponse.cpp \
    listdistributionsbywebaclidrequest.cpp \
    listdistributionsbywebaclidresponse.cpp \
    listdistributionsrequest.cpp \
    listdistributionsresponse.cpp \
    listinvalidationsrequest.cpp \
    listinvalidationsresponse.cpp \
    liststreamingdistributionsrequest.cpp \
    liststreamingdistributionsresponse.cpp \
    listtagsforresourcerequest.cpp \
    listtagsforresourceresponse.cpp \
    tagresourcerequest.cpp \
    tagresourceresponse.cpp \
    untagresourcerequest.cpp \
    untagresourceresponse.cpp \
    updatecloudfrontoriginaccessidentityrequest.cpp \
    updatecloudfrontoriginaccessidentityresponse.cpp \
    updatedistributionrequest.cpp \
    updatedistributionresponse.cpp \
    updatestreamingdistributionrequest.cpp \
    updatestreamingdistributionresponse.cpp \

win32:CONFIG += skip_target_version_ext
