/*
    Copyright 2013-2021 Paul Colby

    This file is part of QtAws.

    QtAws is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    QtAws is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with the QtAws.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef QTAWS_SAGEMAKERCLIENT_H
#define QTAWS_SAGEMAKERCLIENT_H

#include "core/awsabstractclient.h"

#include "qtawssagemakerglobal.h"

class QNetworkReply;

namespace QtAws {
namespace SageMaker {

class SageMakerClientPrivate;
class AddAssociationRequest;
class AddAssociationResponse;
class AddTagsRequest;
class AddTagsResponse;
class AssociateTrialComponentRequest;
class AssociateTrialComponentResponse;
class CreateActionRequest;
class CreateActionResponse;
class CreateAlgorithmRequest;
class CreateAlgorithmResponse;
class CreateAppRequest;
class CreateAppResponse;
class CreateAppImageConfigRequest;
class CreateAppImageConfigResponse;
class CreateArtifactRequest;
class CreateArtifactResponse;
class CreateAutoMLJobRequest;
class CreateAutoMLJobResponse;
class CreateCodeRepositoryRequest;
class CreateCodeRepositoryResponse;
class CreateCompilationJobRequest;
class CreateCompilationJobResponse;
class CreateContextRequest;
class CreateContextResponse;
class CreateDataQualityJobDefinitionRequest;
class CreateDataQualityJobDefinitionResponse;
class CreateDeviceFleetRequest;
class CreateDeviceFleetResponse;
class CreateDomainRequest;
class CreateDomainResponse;
class CreateEdgePackagingJobRequest;
class CreateEdgePackagingJobResponse;
class CreateEndpointRequest;
class CreateEndpointResponse;
class CreateEndpointConfigRequest;
class CreateEndpointConfigResponse;
class CreateExperimentRequest;
class CreateExperimentResponse;
class CreateFeatureGroupRequest;
class CreateFeatureGroupResponse;
class CreateFlowDefinitionRequest;
class CreateFlowDefinitionResponse;
class CreateHumanTaskUiRequest;
class CreateHumanTaskUiResponse;
class CreateHyperParameterTuningJobRequest;
class CreateHyperParameterTuningJobResponse;
class CreateImageRequest;
class CreateImageResponse;
class CreateImageVersionRequest;
class CreateImageVersionResponse;
class CreateLabelingJobRequest;
class CreateLabelingJobResponse;
class CreateModelRequest;
class CreateModelResponse;
class CreateModelBiasJobDefinitionRequest;
class CreateModelBiasJobDefinitionResponse;
class CreateModelExplainabilityJobDefinitionRequest;
class CreateModelExplainabilityJobDefinitionResponse;
class CreateModelPackageRequest;
class CreateModelPackageResponse;
class CreateModelPackageGroupRequest;
class CreateModelPackageGroupResponse;
class CreateModelQualityJobDefinitionRequest;
class CreateModelQualityJobDefinitionResponse;
class CreateMonitoringScheduleRequest;
class CreateMonitoringScheduleResponse;
class CreateNotebookInstanceRequest;
class CreateNotebookInstanceResponse;
class CreateNotebookInstanceLifecycleConfigRequest;
class CreateNotebookInstanceLifecycleConfigResponse;
class CreatePipelineRequest;
class CreatePipelineResponse;
class CreatePresignedDomainUrlRequest;
class CreatePresignedDomainUrlResponse;
class CreatePresignedNotebookInstanceUrlRequest;
class CreatePresignedNotebookInstanceUrlResponse;
class CreateProcessingJobRequest;
class CreateProcessingJobResponse;
class CreateProjectRequest;
class CreateProjectResponse;
class CreateTrainingJobRequest;
class CreateTrainingJobResponse;
class CreateTransformJobRequest;
class CreateTransformJobResponse;
class CreateTrialRequest;
class CreateTrialResponse;
class CreateTrialComponentRequest;
class CreateTrialComponentResponse;
class CreateUserProfileRequest;
class CreateUserProfileResponse;
class CreateWorkforceRequest;
class CreateWorkforceResponse;
class CreateWorkteamRequest;
class CreateWorkteamResponse;
class DeleteActionRequest;
class DeleteActionResponse;
class DeleteAlgorithmRequest;
class DeleteAlgorithmResponse;
class DeleteAppRequest;
class DeleteAppResponse;
class DeleteAppImageConfigRequest;
class DeleteAppImageConfigResponse;
class DeleteArtifactRequest;
class DeleteArtifactResponse;
class DeleteAssociationRequest;
class DeleteAssociationResponse;
class DeleteCodeRepositoryRequest;
class DeleteCodeRepositoryResponse;
class DeleteContextRequest;
class DeleteContextResponse;
class DeleteDataQualityJobDefinitionRequest;
class DeleteDataQualityJobDefinitionResponse;
class DeleteDeviceFleetRequest;
class DeleteDeviceFleetResponse;
class DeleteDomainRequest;
class DeleteDomainResponse;
class DeleteEndpointRequest;
class DeleteEndpointResponse;
class DeleteEndpointConfigRequest;
class DeleteEndpointConfigResponse;
class DeleteExperimentRequest;
class DeleteExperimentResponse;
class DeleteFeatureGroupRequest;
class DeleteFeatureGroupResponse;
class DeleteFlowDefinitionRequest;
class DeleteFlowDefinitionResponse;
class DeleteHumanTaskUiRequest;
class DeleteHumanTaskUiResponse;
class DeleteImageRequest;
class DeleteImageResponse;
class DeleteImageVersionRequest;
class DeleteImageVersionResponse;
class DeleteModelRequest;
class DeleteModelResponse;
class DeleteModelBiasJobDefinitionRequest;
class DeleteModelBiasJobDefinitionResponse;
class DeleteModelExplainabilityJobDefinitionRequest;
class DeleteModelExplainabilityJobDefinitionResponse;
class DeleteModelPackageRequest;
class DeleteModelPackageResponse;
class DeleteModelPackageGroupRequest;
class DeleteModelPackageGroupResponse;
class DeleteModelPackageGroupPolicyRequest;
class DeleteModelPackageGroupPolicyResponse;
class DeleteModelQualityJobDefinitionRequest;
class DeleteModelQualityJobDefinitionResponse;
class DeleteMonitoringScheduleRequest;
class DeleteMonitoringScheduleResponse;
class DeleteNotebookInstanceRequest;
class DeleteNotebookInstanceResponse;
class DeleteNotebookInstanceLifecycleConfigRequest;
class DeleteNotebookInstanceLifecycleConfigResponse;
class DeletePipelineRequest;
class DeletePipelineResponse;
class DeleteProjectRequest;
class DeleteProjectResponse;
class DeleteTagsRequest;
class DeleteTagsResponse;
class DeleteTrialRequest;
class DeleteTrialResponse;
class DeleteTrialComponentRequest;
class DeleteTrialComponentResponse;
class DeleteUserProfileRequest;
class DeleteUserProfileResponse;
class DeleteWorkforceRequest;
class DeleteWorkforceResponse;
class DeleteWorkteamRequest;
class DeleteWorkteamResponse;
class DeregisterDevicesRequest;
class DeregisterDevicesResponse;
class DescribeActionRequest;
class DescribeActionResponse;
class DescribeAlgorithmRequest;
class DescribeAlgorithmResponse;
class DescribeAppRequest;
class DescribeAppResponse;
class DescribeAppImageConfigRequest;
class DescribeAppImageConfigResponse;
class DescribeArtifactRequest;
class DescribeArtifactResponse;
class DescribeAutoMLJobRequest;
class DescribeAutoMLJobResponse;
class DescribeCodeRepositoryRequest;
class DescribeCodeRepositoryResponse;
class DescribeCompilationJobRequest;
class DescribeCompilationJobResponse;
class DescribeContextRequest;
class DescribeContextResponse;
class DescribeDataQualityJobDefinitionRequest;
class DescribeDataQualityJobDefinitionResponse;
class DescribeDeviceRequest;
class DescribeDeviceResponse;
class DescribeDeviceFleetRequest;
class DescribeDeviceFleetResponse;
class DescribeDomainRequest;
class DescribeDomainResponse;
class DescribeEdgePackagingJobRequest;
class DescribeEdgePackagingJobResponse;
class DescribeEndpointRequest;
class DescribeEndpointResponse;
class DescribeEndpointConfigRequest;
class DescribeEndpointConfigResponse;
class DescribeExperimentRequest;
class DescribeExperimentResponse;
class DescribeFeatureGroupRequest;
class DescribeFeatureGroupResponse;
class DescribeFlowDefinitionRequest;
class DescribeFlowDefinitionResponse;
class DescribeHumanTaskUiRequest;
class DescribeHumanTaskUiResponse;
class DescribeHyperParameterTuningJobRequest;
class DescribeHyperParameterTuningJobResponse;
class DescribeImageRequest;
class DescribeImageResponse;
class DescribeImageVersionRequest;
class DescribeImageVersionResponse;
class DescribeLabelingJobRequest;
class DescribeLabelingJobResponse;
class DescribeModelRequest;
class DescribeModelResponse;
class DescribeModelBiasJobDefinitionRequest;
class DescribeModelBiasJobDefinitionResponse;
class DescribeModelExplainabilityJobDefinitionRequest;
class DescribeModelExplainabilityJobDefinitionResponse;
class DescribeModelPackageRequest;
class DescribeModelPackageResponse;
class DescribeModelPackageGroupRequest;
class DescribeModelPackageGroupResponse;
class DescribeModelQualityJobDefinitionRequest;
class DescribeModelQualityJobDefinitionResponse;
class DescribeMonitoringScheduleRequest;
class DescribeMonitoringScheduleResponse;
class DescribeNotebookInstanceRequest;
class DescribeNotebookInstanceResponse;
class DescribeNotebookInstanceLifecycleConfigRequest;
class DescribeNotebookInstanceLifecycleConfigResponse;
class DescribePipelineRequest;
class DescribePipelineResponse;
class DescribePipelineDefinitionForExecutionRequest;
class DescribePipelineDefinitionForExecutionResponse;
class DescribePipelineExecutionRequest;
class DescribePipelineExecutionResponse;
class DescribeProcessingJobRequest;
class DescribeProcessingJobResponse;
class DescribeProjectRequest;
class DescribeProjectResponse;
class DescribeSubscribedWorkteamRequest;
class DescribeSubscribedWorkteamResponse;
class DescribeTrainingJobRequest;
class DescribeTrainingJobResponse;
class DescribeTransformJobRequest;
class DescribeTransformJobResponse;
class DescribeTrialRequest;
class DescribeTrialResponse;
class DescribeTrialComponentRequest;
class DescribeTrialComponentResponse;
class DescribeUserProfileRequest;
class DescribeUserProfileResponse;
class DescribeWorkforceRequest;
class DescribeWorkforceResponse;
class DescribeWorkteamRequest;
class DescribeWorkteamResponse;
class DisableSagemakerServicecatalogPortfolioRequest;
class DisableSagemakerServicecatalogPortfolioResponse;
class DisassociateTrialComponentRequest;
class DisassociateTrialComponentResponse;
class EnableSagemakerServicecatalogPortfolioRequest;
class EnableSagemakerServicecatalogPortfolioResponse;
class GetDeviceFleetReportRequest;
class GetDeviceFleetReportResponse;
class GetModelPackageGroupPolicyRequest;
class GetModelPackageGroupPolicyResponse;
class GetSagemakerServicecatalogPortfolioStatusRequest;
class GetSagemakerServicecatalogPortfolioStatusResponse;
class GetSearchSuggestionsRequest;
class GetSearchSuggestionsResponse;
class ListActionsRequest;
class ListActionsResponse;
class ListAlgorithmsRequest;
class ListAlgorithmsResponse;
class ListAppImageConfigsRequest;
class ListAppImageConfigsResponse;
class ListAppsRequest;
class ListAppsResponse;
class ListArtifactsRequest;
class ListArtifactsResponse;
class ListAssociationsRequest;
class ListAssociationsResponse;
class ListAutoMLJobsRequest;
class ListAutoMLJobsResponse;
class ListCandidatesForAutoMLJobRequest;
class ListCandidatesForAutoMLJobResponse;
class ListCodeRepositoriesRequest;
class ListCodeRepositoriesResponse;
class ListCompilationJobsRequest;
class ListCompilationJobsResponse;
class ListContextsRequest;
class ListContextsResponse;
class ListDataQualityJobDefinitionsRequest;
class ListDataQualityJobDefinitionsResponse;
class ListDeviceFleetsRequest;
class ListDeviceFleetsResponse;
class ListDevicesRequest;
class ListDevicesResponse;
class ListDomainsRequest;
class ListDomainsResponse;
class ListEdgePackagingJobsRequest;
class ListEdgePackagingJobsResponse;
class ListEndpointConfigsRequest;
class ListEndpointConfigsResponse;
class ListEndpointsRequest;
class ListEndpointsResponse;
class ListExperimentsRequest;
class ListExperimentsResponse;
class ListFeatureGroupsRequest;
class ListFeatureGroupsResponse;
class ListFlowDefinitionsRequest;
class ListFlowDefinitionsResponse;
class ListHumanTaskUisRequest;
class ListHumanTaskUisResponse;
class ListHyperParameterTuningJobsRequest;
class ListHyperParameterTuningJobsResponse;
class ListImageVersionsRequest;
class ListImageVersionsResponse;
class ListImagesRequest;
class ListImagesResponse;
class ListLabelingJobsRequest;
class ListLabelingJobsResponse;
class ListLabelingJobsForWorkteamRequest;
class ListLabelingJobsForWorkteamResponse;
class ListModelBiasJobDefinitionsRequest;
class ListModelBiasJobDefinitionsResponse;
class ListModelExplainabilityJobDefinitionsRequest;
class ListModelExplainabilityJobDefinitionsResponse;
class ListModelPackageGroupsRequest;
class ListModelPackageGroupsResponse;
class ListModelPackagesRequest;
class ListModelPackagesResponse;
class ListModelQualityJobDefinitionsRequest;
class ListModelQualityJobDefinitionsResponse;
class ListModelsRequest;
class ListModelsResponse;
class ListMonitoringExecutionsRequest;
class ListMonitoringExecutionsResponse;
class ListMonitoringSchedulesRequest;
class ListMonitoringSchedulesResponse;
class ListNotebookInstanceLifecycleConfigsRequest;
class ListNotebookInstanceLifecycleConfigsResponse;
class ListNotebookInstancesRequest;
class ListNotebookInstancesResponse;
class ListPipelineExecutionStepsRequest;
class ListPipelineExecutionStepsResponse;
class ListPipelineExecutionsRequest;
class ListPipelineExecutionsResponse;
class ListPipelineParametersForExecutionRequest;
class ListPipelineParametersForExecutionResponse;
class ListPipelinesRequest;
class ListPipelinesResponse;
class ListProcessingJobsRequest;
class ListProcessingJobsResponse;
class ListProjectsRequest;
class ListProjectsResponse;
class ListSubscribedWorkteamsRequest;
class ListSubscribedWorkteamsResponse;
class ListTagsRequest;
class ListTagsResponse;
class ListTrainingJobsRequest;
class ListTrainingJobsResponse;
class ListTrainingJobsForHyperParameterTuningJobRequest;
class ListTrainingJobsForHyperParameterTuningJobResponse;
class ListTransformJobsRequest;
class ListTransformJobsResponse;
class ListTrialComponentsRequest;
class ListTrialComponentsResponse;
class ListTrialsRequest;
class ListTrialsResponse;
class ListUserProfilesRequest;
class ListUserProfilesResponse;
class ListWorkforcesRequest;
class ListWorkforcesResponse;
class ListWorkteamsRequest;
class ListWorkteamsResponse;
class PutModelPackageGroupPolicyRequest;
class PutModelPackageGroupPolicyResponse;
class RegisterDevicesRequest;
class RegisterDevicesResponse;
class RenderUiTemplateRequest;
class RenderUiTemplateResponse;
class SearchRequest;
class SearchResponse;
class SendPipelineExecutionStepFailureRequest;
class SendPipelineExecutionStepFailureResponse;
class SendPipelineExecutionStepSuccessRequest;
class SendPipelineExecutionStepSuccessResponse;
class StartMonitoringScheduleRequest;
class StartMonitoringScheduleResponse;
class StartNotebookInstanceRequest;
class StartNotebookInstanceResponse;
class StartPipelineExecutionRequest;
class StartPipelineExecutionResponse;
class StopAutoMLJobRequest;
class StopAutoMLJobResponse;
class StopCompilationJobRequest;
class StopCompilationJobResponse;
class StopEdgePackagingJobRequest;
class StopEdgePackagingJobResponse;
class StopHyperParameterTuningJobRequest;
class StopHyperParameterTuningJobResponse;
class StopLabelingJobRequest;
class StopLabelingJobResponse;
class StopMonitoringScheduleRequest;
class StopMonitoringScheduleResponse;
class StopNotebookInstanceRequest;
class StopNotebookInstanceResponse;
class StopPipelineExecutionRequest;
class StopPipelineExecutionResponse;
class StopProcessingJobRequest;
class StopProcessingJobResponse;
class StopTrainingJobRequest;
class StopTrainingJobResponse;
class StopTransformJobRequest;
class StopTransformJobResponse;
class UpdateActionRequest;
class UpdateActionResponse;
class UpdateAppImageConfigRequest;
class UpdateAppImageConfigResponse;
class UpdateArtifactRequest;
class UpdateArtifactResponse;
class UpdateCodeRepositoryRequest;
class UpdateCodeRepositoryResponse;
class UpdateContextRequest;
class UpdateContextResponse;
class UpdateDeviceFleetRequest;
class UpdateDeviceFleetResponse;
class UpdateDevicesRequest;
class UpdateDevicesResponse;
class UpdateDomainRequest;
class UpdateDomainResponse;
class UpdateEndpointRequest;
class UpdateEndpointResponse;
class UpdateEndpointWeightsAndCapacitiesRequest;
class UpdateEndpointWeightsAndCapacitiesResponse;
class UpdateExperimentRequest;
class UpdateExperimentResponse;
class UpdateImageRequest;
class UpdateImageResponse;
class UpdateModelPackageRequest;
class UpdateModelPackageResponse;
class UpdateMonitoringScheduleRequest;
class UpdateMonitoringScheduleResponse;
class UpdateNotebookInstanceRequest;
class UpdateNotebookInstanceResponse;
class UpdateNotebookInstanceLifecycleConfigRequest;
class UpdateNotebookInstanceLifecycleConfigResponse;
class UpdatePipelineRequest;
class UpdatePipelineResponse;
class UpdatePipelineExecutionRequest;
class UpdatePipelineExecutionResponse;
class UpdateTrainingJobRequest;
class UpdateTrainingJobResponse;
class UpdateTrialRequest;
class UpdateTrialResponse;
class UpdateTrialComponentRequest;
class UpdateTrialComponentResponse;
class UpdateUserProfileRequest;
class UpdateUserProfileResponse;
class UpdateWorkforceRequest;
class UpdateWorkforceResponse;
class UpdateWorkteamRequest;
class UpdateWorkteamResponse;

class QTAWSSAGEMAKER_EXPORT SageMakerClient : public QtAws::Core::AwsAbstractClient {
    Q_OBJECT

public:
    SageMakerClient(
        const QtAws::Core::AwsRegion::Region region = QtAws::Core::AwsRegion::InvalidRegion,
        QtAws::Core::AwsAbstractCredentials * credentials = NULL,
        QNetworkAccessManager * const manager = NULL,
        QObject * const parent = 0);

    explicit SageMakerClient(
        const QUrl &endpoint, QtAws::Core::AwsAbstractCredentials * credentials = NULL,
        QNetworkAccessManager * const manager = NULL,
        QObject * const parent = 0);

public slots:
    AddAssociationResponse * addAssociation(const AddAssociationRequest &request);
    AddTagsResponse * addTags(const AddTagsRequest &request);
    AssociateTrialComponentResponse * associateTrialComponent(const AssociateTrialComponentRequest &request);
    CreateActionResponse * createAction(const CreateActionRequest &request);
    CreateAlgorithmResponse * createAlgorithm(const CreateAlgorithmRequest &request);
    CreateAppResponse * createApp(const CreateAppRequest &request);
    CreateAppImageConfigResponse * createAppImageConfig(const CreateAppImageConfigRequest &request);
    CreateArtifactResponse * createArtifact(const CreateArtifactRequest &request);
    CreateAutoMLJobResponse * createAutoMLJob(const CreateAutoMLJobRequest &request);
    CreateCodeRepositoryResponse * createCodeRepository(const CreateCodeRepositoryRequest &request);
    CreateCompilationJobResponse * createCompilationJob(const CreateCompilationJobRequest &request);
    CreateContextResponse * createContext(const CreateContextRequest &request);
    CreateDataQualityJobDefinitionResponse * createDataQualityJobDefinition(const CreateDataQualityJobDefinitionRequest &request);
    CreateDeviceFleetResponse * createDeviceFleet(const CreateDeviceFleetRequest &request);
    CreateDomainResponse * createDomain(const CreateDomainRequest &request);
    CreateEdgePackagingJobResponse * createEdgePackagingJob(const CreateEdgePackagingJobRequest &request);
    CreateEndpointResponse * createEndpoint(const CreateEndpointRequest &request);
    CreateEndpointConfigResponse * createEndpointConfig(const CreateEndpointConfigRequest &request);
    CreateExperimentResponse * createExperiment(const CreateExperimentRequest &request);
    CreateFeatureGroupResponse * createFeatureGroup(const CreateFeatureGroupRequest &request);
    CreateFlowDefinitionResponse * createFlowDefinition(const CreateFlowDefinitionRequest &request);
    CreateHumanTaskUiResponse * createHumanTaskUi(const CreateHumanTaskUiRequest &request);
    CreateHyperParameterTuningJobResponse * createHyperParameterTuningJob(const CreateHyperParameterTuningJobRequest &request);
    CreateImageResponse * createImage(const CreateImageRequest &request);
    CreateImageVersionResponse * createImageVersion(const CreateImageVersionRequest &request);
    CreateLabelingJobResponse * createLabelingJob(const CreateLabelingJobRequest &request);
    CreateModelResponse * createModel(const CreateModelRequest &request);
    CreateModelBiasJobDefinitionResponse * createModelBiasJobDefinition(const CreateModelBiasJobDefinitionRequest &request);
    CreateModelExplainabilityJobDefinitionResponse * createModelExplainabilityJobDefinition(const CreateModelExplainabilityJobDefinitionRequest &request);
    CreateModelPackageResponse * createModelPackage(const CreateModelPackageRequest &request);
    CreateModelPackageGroupResponse * createModelPackageGroup(const CreateModelPackageGroupRequest &request);
    CreateModelQualityJobDefinitionResponse * createModelQualityJobDefinition(const CreateModelQualityJobDefinitionRequest &request);
    CreateMonitoringScheduleResponse * createMonitoringSchedule(const CreateMonitoringScheduleRequest &request);
    CreateNotebookInstanceResponse * createNotebookInstance(const CreateNotebookInstanceRequest &request);
    CreateNotebookInstanceLifecycleConfigResponse * createNotebookInstanceLifecycleConfig(const CreateNotebookInstanceLifecycleConfigRequest &request);
    CreatePipelineResponse * createPipeline(const CreatePipelineRequest &request);
    CreatePresignedDomainUrlResponse * createPresignedDomainUrl(const CreatePresignedDomainUrlRequest &request);
    CreatePresignedNotebookInstanceUrlResponse * createPresignedNotebookInstanceUrl(const CreatePresignedNotebookInstanceUrlRequest &request);
    CreateProcessingJobResponse * createProcessingJob(const CreateProcessingJobRequest &request);
    CreateProjectResponse * createProject(const CreateProjectRequest &request);
    CreateTrainingJobResponse * createTrainingJob(const CreateTrainingJobRequest &request);
    CreateTransformJobResponse * createTransformJob(const CreateTransformJobRequest &request);
    CreateTrialResponse * createTrial(const CreateTrialRequest &request);
    CreateTrialComponentResponse * createTrialComponent(const CreateTrialComponentRequest &request);
    CreateUserProfileResponse * createUserProfile(const CreateUserProfileRequest &request);
    CreateWorkforceResponse * createWorkforce(const CreateWorkforceRequest &request);
    CreateWorkteamResponse * createWorkteam(const CreateWorkteamRequest &request);
    DeleteActionResponse * deleteAction(const DeleteActionRequest &request);
    DeleteAlgorithmResponse * deleteAlgorithm(const DeleteAlgorithmRequest &request);
    DeleteAppResponse * deleteApp(const DeleteAppRequest &request);
    DeleteAppImageConfigResponse * deleteAppImageConfig(const DeleteAppImageConfigRequest &request);
    DeleteArtifactResponse * deleteArtifact(const DeleteArtifactRequest &request);
    DeleteAssociationResponse * deleteAssociation(const DeleteAssociationRequest &request);
    DeleteCodeRepositoryResponse * deleteCodeRepository(const DeleteCodeRepositoryRequest &request);
    DeleteContextResponse * deleteContext(const DeleteContextRequest &request);
    DeleteDataQualityJobDefinitionResponse * deleteDataQualityJobDefinition(const DeleteDataQualityJobDefinitionRequest &request);
    DeleteDeviceFleetResponse * deleteDeviceFleet(const DeleteDeviceFleetRequest &request);
    DeleteDomainResponse * deleteDomain(const DeleteDomainRequest &request);
    DeleteEndpointResponse * deleteEndpoint(const DeleteEndpointRequest &request);
    DeleteEndpointConfigResponse * deleteEndpointConfig(const DeleteEndpointConfigRequest &request);
    DeleteExperimentResponse * deleteExperiment(const DeleteExperimentRequest &request);
    DeleteFeatureGroupResponse * deleteFeatureGroup(const DeleteFeatureGroupRequest &request);
    DeleteFlowDefinitionResponse * deleteFlowDefinition(const DeleteFlowDefinitionRequest &request);
    DeleteHumanTaskUiResponse * deleteHumanTaskUi(const DeleteHumanTaskUiRequest &request);
    DeleteImageResponse * deleteImage(const DeleteImageRequest &request);
    DeleteImageVersionResponse * deleteImageVersion(const DeleteImageVersionRequest &request);
    DeleteModelResponse * deleteModel(const DeleteModelRequest &request);
    DeleteModelBiasJobDefinitionResponse * deleteModelBiasJobDefinition(const DeleteModelBiasJobDefinitionRequest &request);
    DeleteModelExplainabilityJobDefinitionResponse * deleteModelExplainabilityJobDefinition(const DeleteModelExplainabilityJobDefinitionRequest &request);
    DeleteModelPackageResponse * deleteModelPackage(const DeleteModelPackageRequest &request);
    DeleteModelPackageGroupResponse * deleteModelPackageGroup(const DeleteModelPackageGroupRequest &request);
    DeleteModelPackageGroupPolicyResponse * deleteModelPackageGroupPolicy(const DeleteModelPackageGroupPolicyRequest &request);
    DeleteModelQualityJobDefinitionResponse * deleteModelQualityJobDefinition(const DeleteModelQualityJobDefinitionRequest &request);
    DeleteMonitoringScheduleResponse * deleteMonitoringSchedule(const DeleteMonitoringScheduleRequest &request);
    DeleteNotebookInstanceResponse * deleteNotebookInstance(const DeleteNotebookInstanceRequest &request);
    DeleteNotebookInstanceLifecycleConfigResponse * deleteNotebookInstanceLifecycleConfig(const DeleteNotebookInstanceLifecycleConfigRequest &request);
    DeletePipelineResponse * deletePipeline(const DeletePipelineRequest &request);
    DeleteProjectResponse * deleteProject(const DeleteProjectRequest &request);
    DeleteTagsResponse * deleteTags(const DeleteTagsRequest &request);
    DeleteTrialResponse * deleteTrial(const DeleteTrialRequest &request);
    DeleteTrialComponentResponse * deleteTrialComponent(const DeleteTrialComponentRequest &request);
    DeleteUserProfileResponse * deleteUserProfile(const DeleteUserProfileRequest &request);
    DeleteWorkforceResponse * deleteWorkforce(const DeleteWorkforceRequest &request);
    DeleteWorkteamResponse * deleteWorkteam(const DeleteWorkteamRequest &request);
    DeregisterDevicesResponse * deregisterDevices(const DeregisterDevicesRequest &request);
    DescribeActionResponse * describeAction(const DescribeActionRequest &request);
    DescribeAlgorithmResponse * describeAlgorithm(const DescribeAlgorithmRequest &request);
    DescribeAppResponse * describeApp(const DescribeAppRequest &request);
    DescribeAppImageConfigResponse * describeAppImageConfig(const DescribeAppImageConfigRequest &request);
    DescribeArtifactResponse * describeArtifact(const DescribeArtifactRequest &request);
    DescribeAutoMLJobResponse * describeAutoMLJob(const DescribeAutoMLJobRequest &request);
    DescribeCodeRepositoryResponse * describeCodeRepository(const DescribeCodeRepositoryRequest &request);
    DescribeCompilationJobResponse * describeCompilationJob(const DescribeCompilationJobRequest &request);
    DescribeContextResponse * describeContext(const DescribeContextRequest &request);
    DescribeDataQualityJobDefinitionResponse * describeDataQualityJobDefinition(const DescribeDataQualityJobDefinitionRequest &request);
    DescribeDeviceResponse * describeDevice(const DescribeDeviceRequest &request);
    DescribeDeviceFleetResponse * describeDeviceFleet(const DescribeDeviceFleetRequest &request);
    DescribeDomainResponse * describeDomain(const DescribeDomainRequest &request);
    DescribeEdgePackagingJobResponse * describeEdgePackagingJob(const DescribeEdgePackagingJobRequest &request);
    DescribeEndpointResponse * describeEndpoint(const DescribeEndpointRequest &request);
    DescribeEndpointConfigResponse * describeEndpointConfig(const DescribeEndpointConfigRequest &request);
    DescribeExperimentResponse * describeExperiment(const DescribeExperimentRequest &request);
    DescribeFeatureGroupResponse * describeFeatureGroup(const DescribeFeatureGroupRequest &request);
    DescribeFlowDefinitionResponse * describeFlowDefinition(const DescribeFlowDefinitionRequest &request);
    DescribeHumanTaskUiResponse * describeHumanTaskUi(const DescribeHumanTaskUiRequest &request);
    DescribeHyperParameterTuningJobResponse * describeHyperParameterTuningJob(const DescribeHyperParameterTuningJobRequest &request);
    DescribeImageResponse * describeImage(const DescribeImageRequest &request);
    DescribeImageVersionResponse * describeImageVersion(const DescribeImageVersionRequest &request);
    DescribeLabelingJobResponse * describeLabelingJob(const DescribeLabelingJobRequest &request);
    DescribeModelResponse * describeModel(const DescribeModelRequest &request);
    DescribeModelBiasJobDefinitionResponse * describeModelBiasJobDefinition(const DescribeModelBiasJobDefinitionRequest &request);
    DescribeModelExplainabilityJobDefinitionResponse * describeModelExplainabilityJobDefinition(const DescribeModelExplainabilityJobDefinitionRequest &request);
    DescribeModelPackageResponse * describeModelPackage(const DescribeModelPackageRequest &request);
    DescribeModelPackageGroupResponse * describeModelPackageGroup(const DescribeModelPackageGroupRequest &request);
    DescribeModelQualityJobDefinitionResponse * describeModelQualityJobDefinition(const DescribeModelQualityJobDefinitionRequest &request);
    DescribeMonitoringScheduleResponse * describeMonitoringSchedule(const DescribeMonitoringScheduleRequest &request);
    DescribeNotebookInstanceResponse * describeNotebookInstance(const DescribeNotebookInstanceRequest &request);
    DescribeNotebookInstanceLifecycleConfigResponse * describeNotebookInstanceLifecycleConfig(const DescribeNotebookInstanceLifecycleConfigRequest &request);
    DescribePipelineResponse * describePipeline(const DescribePipelineRequest &request);
    DescribePipelineDefinitionForExecutionResponse * describePipelineDefinitionForExecution(const DescribePipelineDefinitionForExecutionRequest &request);
    DescribePipelineExecutionResponse * describePipelineExecution(const DescribePipelineExecutionRequest &request);
    DescribeProcessingJobResponse * describeProcessingJob(const DescribeProcessingJobRequest &request);
    DescribeProjectResponse * describeProject(const DescribeProjectRequest &request);
    DescribeSubscribedWorkteamResponse * describeSubscribedWorkteam(const DescribeSubscribedWorkteamRequest &request);
    DescribeTrainingJobResponse * describeTrainingJob(const DescribeTrainingJobRequest &request);
    DescribeTransformJobResponse * describeTransformJob(const DescribeTransformJobRequest &request);
    DescribeTrialResponse * describeTrial(const DescribeTrialRequest &request);
    DescribeTrialComponentResponse * describeTrialComponent(const DescribeTrialComponentRequest &request);
    DescribeUserProfileResponse * describeUserProfile(const DescribeUserProfileRequest &request);
    DescribeWorkforceResponse * describeWorkforce(const DescribeWorkforceRequest &request);
    DescribeWorkteamResponse * describeWorkteam(const DescribeWorkteamRequest &request);
    DisableSagemakerServicecatalogPortfolioResponse * disableSagemakerServicecatalogPortfolio(const DisableSagemakerServicecatalogPortfolioRequest &request);
    DisassociateTrialComponentResponse * disassociateTrialComponent(const DisassociateTrialComponentRequest &request);
    EnableSagemakerServicecatalogPortfolioResponse * enableSagemakerServicecatalogPortfolio(const EnableSagemakerServicecatalogPortfolioRequest &request);
    GetDeviceFleetReportResponse * getDeviceFleetReport(const GetDeviceFleetReportRequest &request);
    GetModelPackageGroupPolicyResponse * getModelPackageGroupPolicy(const GetModelPackageGroupPolicyRequest &request);
    GetSagemakerServicecatalogPortfolioStatusResponse * getSagemakerServicecatalogPortfolioStatus(const GetSagemakerServicecatalogPortfolioStatusRequest &request);
    GetSearchSuggestionsResponse * getSearchSuggestions(const GetSearchSuggestionsRequest &request);
    ListActionsResponse * listActions(const ListActionsRequest &request);
    ListAlgorithmsResponse * listAlgorithms(const ListAlgorithmsRequest &request);
    ListAppImageConfigsResponse * listAppImageConfigs(const ListAppImageConfigsRequest &request);
    ListAppsResponse * listApps(const ListAppsRequest &request);
    ListArtifactsResponse * listArtifacts(const ListArtifactsRequest &request);
    ListAssociationsResponse * listAssociations(const ListAssociationsRequest &request);
    ListAutoMLJobsResponse * listAutoMLJobs(const ListAutoMLJobsRequest &request);
    ListCandidatesForAutoMLJobResponse * listCandidatesForAutoMLJob(const ListCandidatesForAutoMLJobRequest &request);
    ListCodeRepositoriesResponse * listCodeRepositories(const ListCodeRepositoriesRequest &request);
    ListCompilationJobsResponse * listCompilationJobs(const ListCompilationJobsRequest &request);
    ListContextsResponse * listContexts(const ListContextsRequest &request);
    ListDataQualityJobDefinitionsResponse * listDataQualityJobDefinitions(const ListDataQualityJobDefinitionsRequest &request);
    ListDeviceFleetsResponse * listDeviceFleets(const ListDeviceFleetsRequest &request);
    ListDevicesResponse * listDevices(const ListDevicesRequest &request);
    ListDomainsResponse * listDomains(const ListDomainsRequest &request);
    ListEdgePackagingJobsResponse * listEdgePackagingJobs(const ListEdgePackagingJobsRequest &request);
    ListEndpointConfigsResponse * listEndpointConfigs(const ListEndpointConfigsRequest &request);
    ListEndpointsResponse * listEndpoints(const ListEndpointsRequest &request);
    ListExperimentsResponse * listExperiments(const ListExperimentsRequest &request);
    ListFeatureGroupsResponse * listFeatureGroups(const ListFeatureGroupsRequest &request);
    ListFlowDefinitionsResponse * listFlowDefinitions(const ListFlowDefinitionsRequest &request);
    ListHumanTaskUisResponse * listHumanTaskUis(const ListHumanTaskUisRequest &request);
    ListHyperParameterTuningJobsResponse * listHyperParameterTuningJobs(const ListHyperParameterTuningJobsRequest &request);
    ListImageVersionsResponse * listImageVersions(const ListImageVersionsRequest &request);
    ListImagesResponse * listImages(const ListImagesRequest &request);
    ListLabelingJobsResponse * listLabelingJobs(const ListLabelingJobsRequest &request);
    ListLabelingJobsForWorkteamResponse * listLabelingJobsForWorkteam(const ListLabelingJobsForWorkteamRequest &request);
    ListModelBiasJobDefinitionsResponse * listModelBiasJobDefinitions(const ListModelBiasJobDefinitionsRequest &request);
    ListModelExplainabilityJobDefinitionsResponse * listModelExplainabilityJobDefinitions(const ListModelExplainabilityJobDefinitionsRequest &request);
    ListModelPackageGroupsResponse * listModelPackageGroups(const ListModelPackageGroupsRequest &request);
    ListModelPackagesResponse * listModelPackages(const ListModelPackagesRequest &request);
    ListModelQualityJobDefinitionsResponse * listModelQualityJobDefinitions(const ListModelQualityJobDefinitionsRequest &request);
    ListModelsResponse * listModels(const ListModelsRequest &request);
    ListMonitoringExecutionsResponse * listMonitoringExecutions(const ListMonitoringExecutionsRequest &request);
    ListMonitoringSchedulesResponse * listMonitoringSchedules(const ListMonitoringSchedulesRequest &request);
    ListNotebookInstanceLifecycleConfigsResponse * listNotebookInstanceLifecycleConfigs(const ListNotebookInstanceLifecycleConfigsRequest &request);
    ListNotebookInstancesResponse * listNotebookInstances(const ListNotebookInstancesRequest &request);
    ListPipelineExecutionStepsResponse * listPipelineExecutionSteps(const ListPipelineExecutionStepsRequest &request);
    ListPipelineExecutionsResponse * listPipelineExecutions(const ListPipelineExecutionsRequest &request);
    ListPipelineParametersForExecutionResponse * listPipelineParametersForExecution(const ListPipelineParametersForExecutionRequest &request);
    ListPipelinesResponse * listPipelines(const ListPipelinesRequest &request);
    ListProcessingJobsResponse * listProcessingJobs(const ListProcessingJobsRequest &request);
    ListProjectsResponse * listProjects(const ListProjectsRequest &request);
    ListSubscribedWorkteamsResponse * listSubscribedWorkteams(const ListSubscribedWorkteamsRequest &request);
    ListTagsResponse * listTags(const ListTagsRequest &request);
    ListTrainingJobsResponse * listTrainingJobs(const ListTrainingJobsRequest &request);
    ListTrainingJobsForHyperParameterTuningJobResponse * listTrainingJobsForHyperParameterTuningJob(const ListTrainingJobsForHyperParameterTuningJobRequest &request);
    ListTransformJobsResponse * listTransformJobs(const ListTransformJobsRequest &request);
    ListTrialComponentsResponse * listTrialComponents(const ListTrialComponentsRequest &request);
    ListTrialsResponse * listTrials(const ListTrialsRequest &request);
    ListUserProfilesResponse * listUserProfiles(const ListUserProfilesRequest &request);
    ListWorkforcesResponse * listWorkforces(const ListWorkforcesRequest &request);
    ListWorkteamsResponse * listWorkteams(const ListWorkteamsRequest &request);
    PutModelPackageGroupPolicyResponse * putModelPackageGroupPolicy(const PutModelPackageGroupPolicyRequest &request);
    RegisterDevicesResponse * registerDevices(const RegisterDevicesRequest &request);
    RenderUiTemplateResponse * renderUiTemplate(const RenderUiTemplateRequest &request);
    SearchResponse * search(const SearchRequest &request);
    SendPipelineExecutionStepFailureResponse * sendPipelineExecutionStepFailure(const SendPipelineExecutionStepFailureRequest &request);
    SendPipelineExecutionStepSuccessResponse * sendPipelineExecutionStepSuccess(const SendPipelineExecutionStepSuccessRequest &request);
    StartMonitoringScheduleResponse * startMonitoringSchedule(const StartMonitoringScheduleRequest &request);
    StartNotebookInstanceResponse * startNotebookInstance(const StartNotebookInstanceRequest &request);
    StartPipelineExecutionResponse * startPipelineExecution(const StartPipelineExecutionRequest &request);
    StopAutoMLJobResponse * stopAutoMLJob(const StopAutoMLJobRequest &request);
    StopCompilationJobResponse * stopCompilationJob(const StopCompilationJobRequest &request);
    StopEdgePackagingJobResponse * stopEdgePackagingJob(const StopEdgePackagingJobRequest &request);
    StopHyperParameterTuningJobResponse * stopHyperParameterTuningJob(const StopHyperParameterTuningJobRequest &request);
    StopLabelingJobResponse * stopLabelingJob(const StopLabelingJobRequest &request);
    StopMonitoringScheduleResponse * stopMonitoringSchedule(const StopMonitoringScheduleRequest &request);
    StopNotebookInstanceResponse * stopNotebookInstance(const StopNotebookInstanceRequest &request);
    StopPipelineExecutionResponse * stopPipelineExecution(const StopPipelineExecutionRequest &request);
    StopProcessingJobResponse * stopProcessingJob(const StopProcessingJobRequest &request);
    StopTrainingJobResponse * stopTrainingJob(const StopTrainingJobRequest &request);
    StopTransformJobResponse * stopTransformJob(const StopTransformJobRequest &request);
    UpdateActionResponse * updateAction(const UpdateActionRequest &request);
    UpdateAppImageConfigResponse * updateAppImageConfig(const UpdateAppImageConfigRequest &request);
    UpdateArtifactResponse * updateArtifact(const UpdateArtifactRequest &request);
    UpdateCodeRepositoryResponse * updateCodeRepository(const UpdateCodeRepositoryRequest &request);
    UpdateContextResponse * updateContext(const UpdateContextRequest &request);
    UpdateDeviceFleetResponse * updateDeviceFleet(const UpdateDeviceFleetRequest &request);
    UpdateDevicesResponse * updateDevices(const UpdateDevicesRequest &request);
    UpdateDomainResponse * updateDomain(const UpdateDomainRequest &request);
    UpdateEndpointResponse * updateEndpoint(const UpdateEndpointRequest &request);
    UpdateEndpointWeightsAndCapacitiesResponse * updateEndpointWeightsAndCapacities(const UpdateEndpointWeightsAndCapacitiesRequest &request);
    UpdateExperimentResponse * updateExperiment(const UpdateExperimentRequest &request);
    UpdateImageResponse * updateImage(const UpdateImageRequest &request);
    UpdateModelPackageResponse * updateModelPackage(const UpdateModelPackageRequest &request);
    UpdateMonitoringScheduleResponse * updateMonitoringSchedule(const UpdateMonitoringScheduleRequest &request);
    UpdateNotebookInstanceResponse * updateNotebookInstance(const UpdateNotebookInstanceRequest &request);
    UpdateNotebookInstanceLifecycleConfigResponse * updateNotebookInstanceLifecycleConfig(const UpdateNotebookInstanceLifecycleConfigRequest &request);
    UpdatePipelineResponse * updatePipeline(const UpdatePipelineRequest &request);
    UpdatePipelineExecutionResponse * updatePipelineExecution(const UpdatePipelineExecutionRequest &request);
    UpdateTrainingJobResponse * updateTrainingJob(const UpdateTrainingJobRequest &request);
    UpdateTrialResponse * updateTrial(const UpdateTrialRequest &request);
    UpdateTrialComponentResponse * updateTrialComponent(const UpdateTrialComponentRequest &request);
    UpdateUserProfileResponse * updateUserProfile(const UpdateUserProfileRequest &request);
    UpdateWorkforceResponse * updateWorkforce(const UpdateWorkforceRequest &request);
    UpdateWorkteamResponse * updateWorkteam(const UpdateWorkteamRequest &request);

private:
    Q_DECLARE_PRIVATE(SageMakerClient)
    Q_DISABLE_COPY(SageMakerClient)

};

} // namespace SageMaker
} // namespace QtAws

#endif
