// SPDX-FileCopyrightText: 2013-2022 Paul Colby <git@colby.id.au>
// SPDX-License-Identifier: LGPL-3.0-or-later

#ifndef QTAWSELASTICLOADBALANCINGV2GLOBAL_H
#define QTAWSELASTICLOADBALANCINGV2GLOBAL_H

// Export declaration macros.
#if defined(QTAWS_SHARED) || !defined(QTAWS_STATIC)
#  ifdef QTAWS_STATIC
#    error "Both QTAWS_SHARED and QTAWS_STATIC defined."
#  endif
#  if defined QTAWSELASTICLOADBALANCINGV2_LIBRARY
#    define QTAWSELASTICLOADBALANCINGV2_EXPORT Q_DECL_EXPORT
#  else
#    define QTAWSELASTICLOADBALANCINGV2_EXPORT Q_DECL_IMPORT
#  endif
#else
#    define QTAWSELASTICLOADBALANCINGV2_EXPORT
#endif

#endif // QTAWSELASTICLOADBALANCINGV2GLOBAL_H
