// SPDX-FileCopyrightText: 2013-2022 Paul Colby <git@colby.id.au>
// SPDX-License-Identifier: LGPL-3.0-or-later

#ifndef QTAWSMARKETPLACEENTITLEMENTGLOBAL_H
#define QTAWSMARKETPLACEENTITLEMENTGLOBAL_H

// Export declaration macros.
#if defined(QTAWS_SHARED) || !defined(QTAWS_STATIC)
#  ifdef QTAWS_STATIC
#    error "Both QTAWS_SHARED and QTAWS_STATIC defined."
#  endif
#  if defined QTAWSMARKETPLACEENTITLEMENT_LIBRARY
#    define QTAWSMARKETPLACEENTITLEMENT_EXPORT Q_DECL_EXPORT
#  else
#    define QTAWSMARKETPLACEENTITLEMENT_EXPORT Q_DECL_IMPORT
#  endif
#else
#    define QTAWSMARKETPLACEENTITLEMENT_EXPORT
#endif


#endif // QTAWSMARKETPLACEENTITLEMENTGLOBAL_H
