include(../../common.pri)

TARGET = autoscaling
TEMPLATE = lib
QT -= gui
QT += network
DEFINES += QTAWS_LIBRARY
DEFINES += QT_NO_CAST_FROM_ASCII QT_NO_CAST_TO_ASCII

INCLUDEPATH = $$TOPDIR/src

HEADERS += \
    attachinstancesrequest.h \
    attachinstancesrequest_p.h \
    attachinstancesresponse.h \
    attachinstancesresponse_p.h \
    attachloadbalancersrequest.h \
    attachloadbalancersrequest_p.h \
    attachloadbalancersresponse.h \
    attachloadbalancersresponse_p.h \
    attachloadbalancertargetgroupsrequest.h \
    attachloadbalancertargetgroupsrequest_p.h \
    attachloadbalancertargetgroupsresponse.h \
    attachloadbalancertargetgroupsresponse_p.h \
    autoscalingclient.h \
    autoscalingclient_p.h \
    completelifecycleactionrequest.h \
    completelifecycleactionrequest_p.h \
    completelifecycleactionresponse.h \
    completelifecycleactionresponse_p.h \
    createautoscalinggrouprequest.h \
    createautoscalinggrouprequest_p.h \
    createautoscalinggroupresponse.h \
    createautoscalinggroupresponse_p.h \
    createlaunchconfigurationrequest.h \
    createlaunchconfigurationrequest_p.h \
    createlaunchconfigurationresponse.h \
    createlaunchconfigurationresponse_p.h \
    createorupdatetagsrequest.h \
    createorupdatetagsrequest_p.h \
    createorupdatetagsresponse.h \
    createorupdatetagsresponse_p.h \
    deleteautoscalinggrouprequest.h \
    deleteautoscalinggrouprequest_p.h \
    deleteautoscalinggroupresponse.h \
    deleteautoscalinggroupresponse_p.h \
    deletelaunchconfigurationrequest.h \
    deletelaunchconfigurationrequest_p.h \
    deletelaunchconfigurationresponse.h \
    deletelaunchconfigurationresponse_p.h \
    deletelifecyclehookrequest.h \
    deletelifecyclehookrequest_p.h \
    deletelifecyclehookresponse.h \
    deletelifecyclehookresponse_p.h \
    deletenotificationconfigurationrequest.h \
    deletenotificationconfigurationrequest_p.h \
    deletenotificationconfigurationresponse.h \
    deletenotificationconfigurationresponse_p.h \
    deletepolicyrequest.h \
    deletepolicyrequest_p.h \
    deletepolicyresponse.h \
    deletepolicyresponse_p.h \
    deletescheduledactionrequest.h \
    deletescheduledactionrequest_p.h \
    deletescheduledactionresponse.h \
    deletescheduledactionresponse_p.h \
    deletetagsrequest.h \
    deletetagsrequest_p.h \
    deletetagsresponse.h \
    deletetagsresponse_p.h \
    describeaccountlimitsresponse.h \
    describeaccountlimitsresponse_p.h \
    describeadjustmenttypesresponse.h \
    describeadjustmenttypesresponse_p.h \
    describeautoscalinggroupsrequest.h \
    describeautoscalinggroupsrequest_p.h \
    describeautoscalinggroupsresponse.h \
    describeautoscalinggroupsresponse_p.h \
    describeautoscalinginstancesrequest.h \
    describeautoscalinginstancesrequest_p.h \
    describeautoscalinginstancesresponse.h \
    describeautoscalinginstancesresponse_p.h \
    describeautoscalingnotificationtypesresponse.h \
    describeautoscalingnotificationtypesresponse_p.h \
    describelaunchconfigurationsrequest.h \
    describelaunchconfigurationsrequest_p.h \
    describelaunchconfigurationsresponse.h \
    describelaunchconfigurationsresponse_p.h \
    describelifecyclehooksrequest.h \
    describelifecyclehooksrequest_p.h \
    describelifecyclehooksresponse.h \
    describelifecyclehooksresponse_p.h \
    describelifecyclehooktypesresponse.h \
    describelifecyclehooktypesresponse_p.h \
    describeloadbalancersrequest.h \
    describeloadbalancersrequest_p.h \
    describeloadbalancersresponse.h \
    describeloadbalancersresponse_p.h \
    describeloadbalancertargetgroupsrequest.h \
    describeloadbalancertargetgroupsrequest_p.h \
    describeloadbalancertargetgroupsresponse.h \
    describeloadbalancertargetgroupsresponse_p.h \
    describemetriccollectiontypesresponse.h \
    describemetriccollectiontypesresponse_p.h \
    describenotificationconfigurationsrequest.h \
    describenotificationconfigurationsrequest_p.h \
    describenotificationconfigurationsresponse.h \
    describenotificationconfigurationsresponse_p.h \
    describepoliciesrequest.h \
    describepoliciesrequest_p.h \
    describepoliciesresponse.h \
    describepoliciesresponse_p.h \
    describescalingactivitiesrequest.h \
    describescalingactivitiesrequest_p.h \
    describescalingactivitiesresponse.h \
    describescalingactivitiesresponse_p.h \
    describescalingprocesstypesresponse.h \
    describescalingprocesstypesresponse_p.h \
    describescheduledactionsrequest.h \
    describescheduledactionsrequest_p.h \
    describescheduledactionsresponse.h \
    describescheduledactionsresponse_p.h \
    describetagsrequest.h \
    describetagsrequest_p.h \
    describetagsresponse.h \
    describetagsresponse_p.h \
    describeterminationpolicytypesresponse.h \
    describeterminationpolicytypesresponse_p.h \
    detachinstancesrequest.h \
    detachinstancesrequest_p.h \
    detachinstancesresponse.h \
    detachinstancesresponse_p.h \
    detachloadbalancersrequest.h \
    detachloadbalancersrequest_p.h \
    detachloadbalancersresponse.h \
    detachloadbalancersresponse_p.h \
    detachloadbalancertargetgroupsrequest.h \
    detachloadbalancertargetgroupsrequest_p.h \
    detachloadbalancertargetgroupsresponse.h \
    detachloadbalancertargetgroupsresponse_p.h \
    disablemetricscollectionrequest.h \
    disablemetricscollectionrequest_p.h \
    disablemetricscollectionresponse.h \
    disablemetricscollectionresponse_p.h \
    enablemetricscollectionrequest.h \
    enablemetricscollectionrequest_p.h \
    enablemetricscollectionresponse.h \
    enablemetricscollectionresponse_p.h \
    enterstandbyrequest.h \
    enterstandbyrequest_p.h \
    enterstandbyresponse.h \
    enterstandbyresponse_p.h \
    executepolicyrequest.h \
    executepolicyrequest_p.h \
    executepolicyresponse.h \
    executepolicyresponse_p.h \
    exitstandbyrequest.h \
    exitstandbyrequest_p.h \
    exitstandbyresponse.h \
    exitstandbyresponse_p.h \
    putlifecyclehookrequest.h \
    putlifecyclehookrequest_p.h \
    putlifecyclehookresponse.h \
    putlifecyclehookresponse_p.h \
    putnotificationconfigurationrequest.h \
    putnotificationconfigurationrequest_p.h \
    putnotificationconfigurationresponse.h \
    putnotificationconfigurationresponse_p.h \
    putscalingpolicyrequest.h \
    putscalingpolicyrequest_p.h \
    putscalingpolicyresponse.h \
    putscalingpolicyresponse_p.h \
    putscheduledupdategroupactionrequest.h \
    putscheduledupdategroupactionrequest_p.h \
    putscheduledupdategroupactionresponse.h \
    putscheduledupdategroupactionresponse_p.h \
    recordlifecycleactionheartbeatrequest.h \
    recordlifecycleactionheartbeatrequest_p.h \
    recordlifecycleactionheartbeatresponse.h \
    recordlifecycleactionheartbeatresponse_p.h \
    resumeprocessesrequest.h \
    resumeprocessesrequest_p.h \
    resumeprocessesresponse.h \
    resumeprocessesresponse_p.h \
    setdesiredcapacityrequest.h \
    setdesiredcapacityrequest_p.h \
    setdesiredcapacityresponse.h \
    setdesiredcapacityresponse_p.h \
    setinstancehealthrequest.h \
    setinstancehealthrequest_p.h \
    setinstancehealthresponse.h \
    setinstancehealthresponse_p.h \
    setinstanceprotectionrequest.h \
    setinstanceprotectionrequest_p.h \
    setinstanceprotectionresponse.h \
    setinstanceprotectionresponse_p.h \
    suspendprocessesrequest.h \
    suspendprocessesrequest_p.h \
    suspendprocessesresponse.h \
    suspendprocessesresponse_p.h \
    terminateinstanceinautoscalinggrouprequest.h \
    terminateinstanceinautoscalinggrouprequest_p.h \
    terminateinstanceinautoscalinggroupresponse.h \
    terminateinstanceinautoscalinggroupresponse_p.h \
    updateautoscalinggrouprequest.h \
    updateautoscalinggrouprequest_p.h \
    updateautoscalinggroupresponse.h \
    updateautoscalinggroupresponse_p.h \

SOURCES += \
    attachinstancesrequest.cpp \
    attachinstancesresponse.cpp \
    attachloadbalancersrequest.cpp \
    attachloadbalancersresponse.cpp \
    attachloadbalancertargetgroupsrequest.cpp \
    attachloadbalancertargetgroupsresponse.cpp \
    autoscalingclient.cpp \
    completelifecycleactionrequest.cpp \
    completelifecycleactionresponse.cpp \
    createautoscalinggrouprequest.cpp \
    createautoscalinggroupresponse.cpp \
    createlaunchconfigurationrequest.cpp \
    createlaunchconfigurationresponse.cpp \
    createorupdatetagsrequest.cpp \
    createorupdatetagsresponse.cpp \
    deleteautoscalinggrouprequest.cpp \
    deleteautoscalinggroupresponse.cpp \
    deletelaunchconfigurationrequest.cpp \
    deletelaunchconfigurationresponse.cpp \
    deletelifecyclehookrequest.cpp \
    deletelifecyclehookresponse.cpp \
    deletenotificationconfigurationrequest.cpp \
    deletenotificationconfigurationresponse.cpp \
    deletepolicyrequest.cpp \
    deletepolicyresponse.cpp \
    deletescheduledactionrequest.cpp \
    deletescheduledactionresponse.cpp \
    deletetagsrequest.cpp \
    deletetagsresponse.cpp \
    describeaccountlimitsresponse.cpp \
    describeadjustmenttypesresponse.cpp \
    describeautoscalinggroupsrequest.cpp \
    describeautoscalinggroupsresponse.cpp \
    describeautoscalinginstancesrequest.cpp \
    describeautoscalinginstancesresponse.cpp \
    describeautoscalingnotificationtypesresponse.cpp \
    describelaunchconfigurationsrequest.cpp \
    describelaunchconfigurationsresponse.cpp \
    describelifecyclehooksrequest.cpp \
    describelifecyclehooksresponse.cpp \
    describelifecyclehooktypesresponse.cpp \
    describeloadbalancersrequest.cpp \
    describeloadbalancersresponse.cpp \
    describeloadbalancertargetgroupsrequest.cpp \
    describeloadbalancertargetgroupsresponse.cpp \
    describemetriccollectiontypesresponse.cpp \
    describenotificationconfigurationsrequest.cpp \
    describenotificationconfigurationsresponse.cpp \
    describepoliciesrequest.cpp \
    describepoliciesresponse.cpp \
    describescalingactivitiesrequest.cpp \
    describescalingactivitiesresponse.cpp \
    describescalingprocesstypesresponse.cpp \
    describescheduledactionsrequest.cpp \
    describescheduledactionsresponse.cpp \
    describetagsrequest.cpp \
    describetagsresponse.cpp \
    describeterminationpolicytypesresponse.cpp \
    detachinstancesrequest.cpp \
    detachinstancesresponse.cpp \
    detachloadbalancersrequest.cpp \
    detachloadbalancersresponse.cpp \
    detachloadbalancertargetgroupsrequest.cpp \
    detachloadbalancertargetgroupsresponse.cpp \
    disablemetricscollectionrequest.cpp \
    disablemetricscollectionresponse.cpp \
    enablemetricscollectionrequest.cpp \
    enablemetricscollectionresponse.cpp \
    enterstandbyrequest.cpp \
    enterstandbyresponse.cpp \
    executepolicyrequest.cpp \
    executepolicyresponse.cpp \
    exitstandbyrequest.cpp \
    exitstandbyresponse.cpp \
    putlifecyclehookrequest.cpp \
    putlifecyclehookresponse.cpp \
    putnotificationconfigurationrequest.cpp \
    putnotificationconfigurationresponse.cpp \
    putscalingpolicyrequest.cpp \
    putscalingpolicyresponse.cpp \
    putscheduledupdategroupactionrequest.cpp \
    putscheduledupdategroupactionresponse.cpp \
    recordlifecycleactionheartbeatrequest.cpp \
    recordlifecycleactionheartbeatresponse.cpp \
    resumeprocessesrequest.cpp \
    resumeprocessesresponse.cpp \
    setdesiredcapacityrequest.cpp \
    setdesiredcapacityresponse.cpp \
    setinstancehealthrequest.cpp \
    setinstancehealthresponse.cpp \
    setinstanceprotectionrequest.cpp \
    setinstanceprotectionresponse.cpp \
    suspendprocessesrequest.cpp \
    suspendprocessesresponse.cpp \
    terminateinstanceinautoscalinggrouprequest.cpp \
    terminateinstanceinautoscalinggroupresponse.cpp \
    updateautoscalinggrouprequest.cpp \
    updateautoscalinggroupresponse.cpp \

win32:CONFIG += skip_target_version_ext
