include(../../common.pri)

TARGET = QtAwsPinpointEmail
TEMPLATE = lib
QT -= gui
QT += network
DEFINES += QTAWS_LIBRARY
DEFINES += QT_NO_CAST_FROM_ASCII QT_NO_CAST_TO_ASCII

INCLUDEPATH = $$TOPDIR/src

HEADERS += \
    createconfigurationseteventdestinationrequest.h \
    createconfigurationseteventdestinationrequest_p.h \
    createconfigurationseteventdestinationresponse.h \
    createconfigurationseteventdestinationresponse_p.h \
    createconfigurationsetrequest.h \
    createconfigurationsetrequest_p.h \
    createconfigurationsetresponse.h \
    createconfigurationsetresponse_p.h \
    creatededicatedippoolrequest.h \
    creatededicatedippoolrequest_p.h \
    creatededicatedippoolresponse.h \
    creatededicatedippoolresponse_p.h \
    createdeliverabilitytestreportrequest.h \
    createdeliverabilitytestreportrequest_p.h \
    createdeliverabilitytestreportresponse.h \
    createdeliverabilitytestreportresponse_p.h \
    createemailidentityrequest.h \
    createemailidentityrequest_p.h \
    createemailidentityresponse.h \
    createemailidentityresponse_p.h \
    deleteconfigurationseteventdestinationrequest.h \
    deleteconfigurationseteventdestinationrequest_p.h \
    deleteconfigurationseteventdestinationresponse.h \
    deleteconfigurationseteventdestinationresponse_p.h \
    deleteconfigurationsetrequest.h \
    deleteconfigurationsetrequest_p.h \
    deleteconfigurationsetresponse.h \
    deleteconfigurationsetresponse_p.h \
    deletededicatedippoolrequest.h \
    deletededicatedippoolrequest_p.h \
    deletededicatedippoolresponse.h \
    deletededicatedippoolresponse_p.h \
    deleteemailidentityrequest.h \
    deleteemailidentityrequest_p.h \
    deleteemailidentityresponse.h \
    deleteemailidentityresponse_p.h \
    getaccountrequest.h \
    getaccountrequest_p.h \
    getaccountresponse.h \
    getaccountresponse_p.h \
    getblacklistreportsrequest.h \
    getblacklistreportsrequest_p.h \
    getblacklistreportsresponse.h \
    getblacklistreportsresponse_p.h \
    getconfigurationseteventdestinationsrequest.h \
    getconfigurationseteventdestinationsrequest_p.h \
    getconfigurationseteventdestinationsresponse.h \
    getconfigurationseteventdestinationsresponse_p.h \
    getconfigurationsetrequest.h \
    getconfigurationsetrequest_p.h \
    getconfigurationsetresponse.h \
    getconfigurationsetresponse_p.h \
    getdedicatediprequest.h \
    getdedicatediprequest_p.h \
    getdedicatedipresponse.h \
    getdedicatedipresponse_p.h \
    getdedicatedipsrequest.h \
    getdedicatedipsrequest_p.h \
    getdedicatedipsresponse.h \
    getdedicatedipsresponse_p.h \
    getdeliverabilitydashboardoptionsrequest.h \
    getdeliverabilitydashboardoptionsrequest_p.h \
    getdeliverabilitydashboardoptionsresponse.h \
    getdeliverabilitydashboardoptionsresponse_p.h \
    getdeliverabilitytestreportrequest.h \
    getdeliverabilitytestreportrequest_p.h \
    getdeliverabilitytestreportresponse.h \
    getdeliverabilitytestreportresponse_p.h \
    getdomainstatisticsreportrequest.h \
    getdomainstatisticsreportrequest_p.h \
    getdomainstatisticsreportresponse.h \
    getdomainstatisticsreportresponse_p.h \
    getemailidentityrequest.h \
    getemailidentityrequest_p.h \
    getemailidentityresponse.h \
    getemailidentityresponse_p.h \
    listconfigurationsetsrequest.h \
    listconfigurationsetsrequest_p.h \
    listconfigurationsetsresponse.h \
    listconfigurationsetsresponse_p.h \
    listdedicatedippoolsrequest.h \
    listdedicatedippoolsrequest_p.h \
    listdedicatedippoolsresponse.h \
    listdedicatedippoolsresponse_p.h \
    listdeliverabilitytestreportsrequest.h \
    listdeliverabilitytestreportsrequest_p.h \
    listdeliverabilitytestreportsresponse.h \
    listdeliverabilitytestreportsresponse_p.h \
    listemailidentitiesrequest.h \
    listemailidentitiesrequest_p.h \
    listemailidentitiesresponse.h \
    listemailidentitiesresponse_p.h \
    pinpointemailclient.h \
    pinpointemailclient_p.h \
    pinpointemailrequest.h \
    pinpointemailrequest_p.h \
    pinpointemailresponse.h \
    pinpointemailresponse_p.h \
    putaccountdedicatedipwarmupattributesrequest.h \
    putaccountdedicatedipwarmupattributesrequest_p.h \
    putaccountdedicatedipwarmupattributesresponse.h \
    putaccountdedicatedipwarmupattributesresponse_p.h \
    putaccountsendingattributesrequest.h \
    putaccountsendingattributesrequest_p.h \
    putaccountsendingattributesresponse.h \
    putaccountsendingattributesresponse_p.h \
    putconfigurationsetdeliveryoptionsrequest.h \
    putconfigurationsetdeliveryoptionsrequest_p.h \
    putconfigurationsetdeliveryoptionsresponse.h \
    putconfigurationsetdeliveryoptionsresponse_p.h \
    putconfigurationsetreputationoptionsrequest.h \
    putconfigurationsetreputationoptionsrequest_p.h \
    putconfigurationsetreputationoptionsresponse.h \
    putconfigurationsetreputationoptionsresponse_p.h \
    putconfigurationsetsendingoptionsrequest.h \
    putconfigurationsetsendingoptionsrequest_p.h \
    putconfigurationsetsendingoptionsresponse.h \
    putconfigurationsetsendingoptionsresponse_p.h \
    putconfigurationsettrackingoptionsrequest.h \
    putconfigurationsettrackingoptionsrequest_p.h \
    putconfigurationsettrackingoptionsresponse.h \
    putconfigurationsettrackingoptionsresponse_p.h \
    putdedicatedipinpoolrequest.h \
    putdedicatedipinpoolrequest_p.h \
    putdedicatedipinpoolresponse.h \
    putdedicatedipinpoolresponse_p.h \
    putdedicatedipwarmupattributesrequest.h \
    putdedicatedipwarmupattributesrequest_p.h \
    putdedicatedipwarmupattributesresponse.h \
    putdedicatedipwarmupattributesresponse_p.h \
    putdeliverabilitydashboardoptionrequest.h \
    putdeliverabilitydashboardoptionrequest_p.h \
    putdeliverabilitydashboardoptionresponse.h \
    putdeliverabilitydashboardoptionresponse_p.h \
    putemailidentitydkimattributesrequest.h \
    putemailidentitydkimattributesrequest_p.h \
    putemailidentitydkimattributesresponse.h \
    putemailidentitydkimattributesresponse_p.h \
    putemailidentityfeedbackattributesrequest.h \
    putemailidentityfeedbackattributesrequest_p.h \
    putemailidentityfeedbackattributesresponse.h \
    putemailidentityfeedbackattributesresponse_p.h \
    putemailidentitymailfromattributesrequest.h \
    putemailidentitymailfromattributesrequest_p.h \
    putemailidentitymailfromattributesresponse.h \
    putemailidentitymailfromattributesresponse_p.h \
    sendemailrequest.h \
    sendemailrequest_p.h \
    sendemailresponse.h \
    sendemailresponse_p.h \
    updateconfigurationseteventdestinationrequest.h \
    updateconfigurationseteventdestinationrequest_p.h \
    updateconfigurationseteventdestinationresponse.h \
    updateconfigurationseteventdestinationresponse_p.h \

SOURCES += \
    createconfigurationseteventdestinationrequest.cpp \
    createconfigurationseteventdestinationresponse.cpp \
    createconfigurationsetrequest.cpp \
    createconfigurationsetresponse.cpp \
    creatededicatedippoolrequest.cpp \
    creatededicatedippoolresponse.cpp \
    createdeliverabilitytestreportrequest.cpp \
    createdeliverabilitytestreportresponse.cpp \
    createemailidentityrequest.cpp \
    createemailidentityresponse.cpp \
    deleteconfigurationseteventdestinationrequest.cpp \
    deleteconfigurationseteventdestinationresponse.cpp \
    deleteconfigurationsetrequest.cpp \
    deleteconfigurationsetresponse.cpp \
    deletededicatedippoolrequest.cpp \
    deletededicatedippoolresponse.cpp \
    deleteemailidentityrequest.cpp \
    deleteemailidentityresponse.cpp \
    getaccountrequest.cpp \
    getaccountresponse.cpp \
    getblacklistreportsrequest.cpp \
    getblacklistreportsresponse.cpp \
    getconfigurationseteventdestinationsrequest.cpp \
    getconfigurationseteventdestinationsresponse.cpp \
    getconfigurationsetrequest.cpp \
    getconfigurationsetresponse.cpp \
    getdedicatediprequest.cpp \
    getdedicatedipresponse.cpp \
    getdedicatedipsrequest.cpp \
    getdedicatedipsresponse.cpp \
    getdeliverabilitydashboardoptionsrequest.cpp \
    getdeliverabilitydashboardoptionsresponse.cpp \
    getdeliverabilitytestreportrequest.cpp \
    getdeliverabilitytestreportresponse.cpp \
    getdomainstatisticsreportrequest.cpp \
    getdomainstatisticsreportresponse.cpp \
    getemailidentityrequest.cpp \
    getemailidentityresponse.cpp \
    listconfigurationsetsrequest.cpp \
    listconfigurationsetsresponse.cpp \
    listdedicatedippoolsrequest.cpp \
    listdedicatedippoolsresponse.cpp \
    listdeliverabilitytestreportsrequest.cpp \
    listdeliverabilitytestreportsresponse.cpp \
    listemailidentitiesrequest.cpp \
    listemailidentitiesresponse.cpp \
    pinpointemailclient.cpp \
    pinpointemailrequest.cpp \
    pinpointemailresponse.cpp \
    putaccountdedicatedipwarmupattributesrequest.cpp \
    putaccountdedicatedipwarmupattributesresponse.cpp \
    putaccountsendingattributesrequest.cpp \
    putaccountsendingattributesresponse.cpp \
    putconfigurationsetdeliveryoptionsrequest.cpp \
    putconfigurationsetdeliveryoptionsresponse.cpp \
    putconfigurationsetreputationoptionsrequest.cpp \
    putconfigurationsetreputationoptionsresponse.cpp \
    putconfigurationsetsendingoptionsrequest.cpp \
    putconfigurationsetsendingoptionsresponse.cpp \
    putconfigurationsettrackingoptionsrequest.cpp \
    putconfigurationsettrackingoptionsresponse.cpp \
    putdedicatedipinpoolrequest.cpp \
    putdedicatedipinpoolresponse.cpp \
    putdedicatedipwarmupattributesrequest.cpp \
    putdedicatedipwarmupattributesresponse.cpp \
    putdeliverabilitydashboardoptionrequest.cpp \
    putdeliverabilitydashboardoptionresponse.cpp \
    putemailidentitydkimattributesrequest.cpp \
    putemailidentitydkimattributesresponse.cpp \
    putemailidentityfeedbackattributesrequest.cpp \
    putemailidentityfeedbackattributesresponse.cpp \
    putemailidentitymailfromattributesrequest.cpp \
    putemailidentitymailfromattributesresponse.cpp \
    sendemailrequest.cpp \
    sendemailresponse.cpp \
    updateconfigurationseteventdestinationrequest.cpp \
    updateconfigurationseteventdestinationresponse.cpp \

win32:CONFIG += skip_target_version_ext
