// SPDX-FileCopyrightText: 2013-2022 Paul Colby <git@colby.id.au>
// SPDX-License-Identifier: LGPL-3.0-or-later

#ifndef QTAWSCODESTARNOTIFICATIONSGLOBAL_H
#define QTAWSCODESTARNOTIFICATIONSGLOBAL_H

// Export declaration macros.
#if defined(QTAWS_SHARED) || !defined(QTAWS_STATIC)
#  ifdef QTAWS_STATIC
#    error "Both QTAWS_SHARED and QTAWS_STATIC defined."
#  endif
#  if defined QTAWSCODESTARNOTIFICATIONS_LIBRARY
#    define QTAWSCODESTARNOTIFICATIONS_EXPORT Q_DECL_EXPORT
#  else
#    define QTAWSCODESTARNOTIFICATIONS_EXPORT Q_DECL_IMPORT
#  endif
#else
#    define QTAWSCODESTARNOTIFICATIONS_EXPORT
#endif


#endif // QTAWSCODESTARNOTIFICATIONSGLOBAL_H
